CREATE TABLE [dbo].[NBCManager] (
    [SuperRegionID]      INT            NULL,
    [SuperRegion]        NVARCHAR (255) NULL,
    [SuperRegionManager] NVARCHAR (255) NULL,
    [SRUserID]           INT            NULL,
    [RegionID]           INT            NULL,
    [RegionName]         NVARCHAR (255) NULL,
    [Regionmanager]      INT            NULL,
    [RegionManagerName]  NVARCHAR (255) NULL,
    [RegionManagerEmail] NVARCHAR (255) NULL,
    [RegionManagerPhone] NVARCHAR (255) NULL,
    [RUserID]            INT            NULL,
    [StoreManager]       NVARCHAR (255) NULL,
    [StoreManagerEmail]  NVARCHAR (255) NULL,
    [StoreManagerPhone]  NVARCHAR (255) NULL,
    [SUserID]            INT            NULL,
    [CustomerID]         INT            NULL,
    [StoreID]            INT            NULL,
    [StoreNo]            INT            NULL,
    [StoreName]          NVARCHAR (255) NULL,
    [StorePhone]         NVARCHAR (255) NULL,
    [StoreFax]           NVARCHAR (255) NULL,
    [StoreURL]           NVARCHAR (255) NULL,
    [StoreAddress]       NVARCHAR (255) NULL,
    [StoreCity]          NVARCHAR (255) NULL,
    [StoreState]         NVARCHAR (255) NULL,
    [StoreZip]           FLOAT (53)     NULL
);

