//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t access my account.
        /// </summary>
        internal static string cantaccessaccount {
            get {
                return ResourceManager.GetString("cantaccessaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        internal static string digital {
            get {
                return ResourceManager.GetString("digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string emailaddress {
            get {
                return ResourceManager.GetString("emailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string emailaddressvalid {
            get {
                return ResourceManager.GetString("emailaddressvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First letter of your last name.
        /// </summary>
        internal static string firstletterlastname {
            get {
                return ResourceManager.GetString("firstletterlastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (for verification).
        /// </summary>
        internal static string forverfication {
            get {
                return ResourceManager.GetString("forverfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Images/or.png.
        /// </summary>
        internal static string imgOR {
            get {
                return ResourceManager.GetString("imgOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my Subscription.
        /// </summary>
        internal static string managesubscription {
            get {
                return ResourceManager.GetString("managesubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO SUBSCRIBE, please choose your options below (check all that apply)..
        /// </summary>
        internal static string newletterheader {
            get {
                return ResourceManager.GetString("newletterheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subscription.
        /// </summary>
        internal static string newsubscription {
            get {
                return ResourceManager.GetString("newsubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER RESOURCES.
        /// </summary>
        internal static string otherresources {
            get {
                return ResourceManager.GetString("otherresources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of 6 characters, letters and numbers only. No spaces, dashes and special characters.
        /// </summary>
        internal static string passwordText {
            get {
                return ResourceManager.GetString("passwordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Account Information.
        /// </summary>
        internal static string PersonalAccountInfo {
            get {
                return ResourceManager.GetString("PersonalAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20%.
        /// </summary>
        internal static string profileleftColWidth {
            get {
                return ResourceManager.GetString("profileleftColWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80%.
        /// </summary>
        internal static string profileRightColWidth {
            get {
                return ResourceManager.GetString("profileRightColWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates a required field..
        /// </summary>
        internal static string requiredfieldheader {
            get {
                return ResourceManager.GetString("requiredfieldheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;../images/required_field.png&apos; valign=&apos;middle&apos;&gt;.
        /// </summary>
        internal static string requiredfieldImage {
            get {
                return ResourceManager.GetString("requiredfieldImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FROM LIST.
        /// </summary>
        internal static string selectanitem {
            get {
                return ResourceManager.GetString("selectanitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Select Country ----.
        /// </summary>
        internal static string selectcountry {
            get {
                return ResourceManager.GetString("selectcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber ID #.
        /// </summary>
        internal static string subscriberID {
            get {
                return ResourceManager.GetString("subscriberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW CURRENT &amp; UPCOMING EVENTS.
        /// </summary>
        internal static string upcomingevents {
            get {
                return ResourceManager.GetString("upcomingevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a value for the following questions:.
        /// </summary>
        internal static string warningmessage {
            get {
                return ResourceManager.GetString("warningmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
