CREATE PROCEDURE [dbo].[e_Customer_Save]    
(
@CustomerID int, 			
@BaseChannelID int, 
@CustomerName varchar(150),
@ActiveFlag varchar(1),
@Address varchar(255),
@City varchar(255),
@State varchar(255), 
@Country varchar(50), 
@Zip varchar(50), 
@Salutation varchar(50), 
@ContactName varchar(255), 
@FirstName varchar(50), 
@LastName varchar(50), 
@ContactTitle varchar(255), 
@Email varchar(255), 
@Phone varchar(255), 
@Fax varchar(50), 
@WebAddress varchar(255),  
@TechContact varchar(50), 
@TechEmail varchar(255),  
@TechPhone varchar(255),  
@SubscriptionsEmail varchar(255),  
@AccountsLevel varchar(50), 
@CommunicatorLevel varchar(50),
@CommunicatorChannelID varchar(50), 
@CollectorLevel varchar(50), 
@CollectorChannelID int, 
@CreatorLevel varchar(50), 
@CreatorChannelID int,
@PublisherLevel varchar(50), 
@PublisherChannelID int,
@CharityLevel varchar(50), 
@CharityChannelID int,
@CustomerType varchar(50),
@DemoFlag varchar(1),
@IsStrategic bit,
@AccountExecutiveID int,
@AccountManagerID int, 
@Customer_udf1 varchar(255),
@Customer_udf2 varchar(255),
@Customer_udf3 varchar(255),
@Customer_udf4 varchar(255),
@Customer_udf5  varchar(255),
@UserID int,
@MSCustomerID int = null,
@ABWinnerType varchar(10),
@BlastConfigID int = 3,
@DefaultBlastAsTest bit,
@PlatformClientID int
)
AS  

BEGIN   
	SET NOCOUNT ON;  
	
	if (@CustomerID > 0)
	Begin
		UPDATE [ecn5_accounts].[dbo].[Customer]
		   SET [BaseChannelID] = @BaseChannelID,
			CustomerName = @CustomerName, 
			ActiveFlag = @ActiveFlag, 
			Address = @Address,
			City = @City,
			State = @State,
			Country = @Country,
			Zip = @Zip,
			Salutation = @Salutation,
			ContactName = @ContactName,
			FirstName = @FirstName,
			LastName = @LastName,
			ContactTitle = @ContactTitle,
			Email = @Email,
			Phone = @Phone,
			Fax = @Fax,
			WebAddress = @WebAddress, 
			TechContact = @TechContact, 
			TechEmail = @TechEmail, 
			TechPhone = @TechPhone, 
			SubscriptionsEmail = @SubscriptionsEmail, 
			AccountsLevel = @AccountsLevel,  
			CommunicatorLevel =  @CommunicatorLevel,
			CommunicatorChannelID  = @CommunicatorChannelID,
			CollectorLevel  = @CollectorLevel, 
			CollectorChannelID  =  @CollectorChannelID,
			CreatorLevel  = @CreatorLevel,
			CreatorChannelID = @CreatorChannelID, 
			PublisherLevel  = @PublisherLevel,
			PublisherChannelID = @PublisherChannelID,
			CharityLevel =  @CharityLevel,
			CharityChannelID = @CharityChannelID,
			CustomerType = @CustomerType, 
 			DemoFlag = @DemoFlag,
			IsStrategic = @IsStrategic,
			AccountExecutiveID = @AccountExecutiveID,
			AccountManagerID = @AccountManagerID, 
			customer_udf1 = @Customer_udf1,
			customer_udf2 = @Customer_udf2,
			customer_udf3 = @Customer_udf3,
			customer_udf4 = @Customer_udf4,
			customer_udf5 = @Customer_udf5,		   
			[UpdatedUserID] = @UserID,
			[UpdatedDate] = getdate(),
			MSCustomerID = @MSCustomerID,
			ABWinnerType = @ABWinnerType,
			BlastConfigID = @BlastConfigID,
			DefaultBlastAsTest = @DefaultBlastAsTest,
			PlatformClientID = @PlatformClientID
		 WHERE CustomerID = @CustomerID
		 
		 select @CustomerID

	End
	Else
	Begin
		
		INSERT INTO Customer (
			BaseChannelID, 
			CustomerName, 
			ActiveFlag, 
			Address,
			City,
			State,
			Country,
			Zip,
			Salutation,
			ContactName,
			FirstName,
			LastName,
			ContactTitle,
			Email,
			Phone,
			Fax,
			WebAddress, 
			TechContact, 
			TechEmail, 
			TechPhone, 
			SubscriptionsEmail, 
			AccountsLevel ,  
			CommunicatorLevel ,
			CommunicatorChannelID ,
			CollectorLevel , 
			CollectorChannelID ,
			CreatorLevel ,
			CreatorChannelID, 
			PublisherLevel ,
			PublisherChannelID,
			CharityLevel ,
			CharityChannelID,
			CustomerType, 
			DemoFlag,
			IsStrategic,
			AccountExecutiveID,
			AccountManagerID, 
			customer_udf1,
			customer_udf2,
			customer_udf3,
			customer_udf4,
			customer_udf5,
			CreatedUserID,
			CreatedDate,
			IsDeleted,
			MSCustomerID,
			ABWinnerType,
			BlastConfigID,
			DefaultBlastAsTest,
			PlatformClientID) 
		VALUES (
			@BaseChannelID,
			@CustomerName,
			@ActiveFlag,
			@Address,
			@City,
			@State, 
			@Country, 
			@Zip, 
			@Salutation,
			@ContactName,
			@FirstName,
			@LastName,
			@ContactTitle,
			@Email,
			@Phone,
			@Fax,
			@WebAddress, 
			@TechContact, 
			@TechEmail, 
			@TechPhone, 
			@SubscriptionsEmail, 
			@AccountsLevel, 
			@CommunicatorLevel,
			@CommunicatorChannelID, 
			@CollectorLevel, 
			@CollectorChannelID, 
			@CreatorLevel, 
			@CreatorChannelID, 
			@PublisherLevel, 
			@PublisherChannelID,
			@CharityLevel, 
			@CharityChannelID,
			@CustomerType, 
			@DemoFlag,
			@IsStrategic,
			@AccountExecutiveID,
			@AccountManagerID, 
			@Customer_udf1,
			@Customer_udf2,
			@Customer_udf3,
			@Customer_udf4,
			@Customer_udf5,
			@UserID,
			getdate(),
			0,
			@MSCustomerID,
			@ABWinnerType,
			@BlastConfigID,
			@DefaultBlastAsTest,
			@PlatformClientID)
			SELECT @@IDENTITY;
	End
END
GO

