CREATE PROCEDURE dbo.e_FeatureLog_Update
@FLogID int,
@ApplicationID int = -1,
@ProductLine nvarchar(400) = '',
@TargetApp nvarchar(200) = '',
@RequestBy nvarchar(200) = '',
@RequestDate date,
@FeatureName nvarchar(800) = '',
@FetureDescription text = '',
@TargetReleaseDate date,
@IsQuoted bit = 'false',
@QuotedHours real = 0,
@IsApporoved bit = 'false',
@ApprovedBy  nvarchar(200) = '',
@ApprovedDate date,
@IsStarted bit = 'false',
@StartedDate date,
@IsCompleted bit = 'false',
@CompletedDate date,
@DevLead  nvarchar(200) = '',
@DevNotes text = '',
@FeaturePriority int = -1,
@DateUpdated datetime,
@UpdatedBy  nvarchar(200) = ''
AS
UPDATE FeatureLog 
SET ApplicationID = @ApplicationID,
	ProductLine = @ProductLine,
	TargetApp = @TargetApp,
	RequestBy = @RequestBy,
	RequestDate = @RequestDate,
	FeatureName = @FeatureName,
	FetureDescription = @FetureDescription,
	TargetReleaseDate = @TargetReleaseDate,
	IsQuoted = @IsQuoted,
	QuotedHours = @QuotedHours,
	IsApporoved = @IsApporoved,
	ApprovedBy = @ApprovedBy,
	ApprovedDate = @ApprovedDate,
	IsStarted = @IsStarted,
	StartedDate = @StartedDate,
	IsCompleted = @IsCompleted,
	CompletedDate = @CompletedDate,
	DevLead = @DevLead,
	DevNotes = @DevNotes,
	FeaturePriority = @FeaturePriority,
	DateUpdated = @DateUpdated,
	UpdatedBy = @UpdatedBy
WHERE FLogID = @FLogID
