CREATE LOGIN [bill.hipps]
    WITH PASSWORD = N'hwt|fhcisSojijed|LuhkhkkmsFT7_&#$!~<ymaqn|cos+qx', SID = 0xB2752FDAA12AC940A262C2DA7362EBA8, DEFAULT_DATABASE = [ECN5_ACCOUNTS], DEFAULT_LANGUAGE = [us_english];

