CREATE TABLE [dbo].[AcsFileHeader] (
    [AcsFileHeaderId]       INT            IDENTITY (1, 1) NOT NULL,
    [RecordType]            VARCHAR (1)    NULL,
    [FileVersion]           VARCHAR (2)    NULL,
    [CustomerID]            INT            NULL,
    [CreateDate]            DATE           NULL,
    [ShipmentNumber]        BIGINT         NULL,
    [TotalAcsRecordCount]   INT            NULL,
    [TotalCoaCount]         INT            NULL,
    [TotalNixieCount]       INT            NULL,
    [TrdRecordCount]        INT            NULL,
    [TrdAcsFeeAmount]       DECIMAL (9, 2) NULL,
    [TrdCoaCount]           INT            NULL,
    [TrdCoaAcsFeeAmount]    DECIMAL (9, 2) NULL,
    [TrdNixieCount]         INT            NULL,
    [TrdNixieAcsFeeAmount]  DECIMAL (9, 2) NULL,
    [OcdRecordCount]        INT            NULL,
    [OcdAcsFeeAmount]       DECIMAL (9, 2) NULL,
    [OcdCoaCount]           INT            NULL,
    [OcdCoaAcsFeeAmount]    DECIMAL (9, 2) NULL,
    [OcdNixieCount]         INT            NULL,
    [OcdNixieAcsFeeAmount]  DECIMAL (9, 2) NULL,
    [FsRecordCount]         INT            NULL,
    [FsAcsFeeAmount]        DECIMAL (9, 2) NULL,
    [FsCoaCount]            INT            NULL,
    [FsCoaAcsFeeAmount]     DECIMAL (9, 2) NULL,
    [FsNixieCount]          INT            NULL,
    [FsNixieAcsFeeAmount]   DECIMAL (9, 2) NULL,
    [ImpbRecordCount]       INT            NULL,
    [ImpbAcsFeeAmount]      DECIMAL (9, 2) NULL,
    [ImpbCoaCount]          INT            NULL,
    [ImpbCoaAcsFeeAmount]   DECIMAL (9, 2) NULL,
    [ImpbNixieCount]        INT            NULL,
    [ImpbNixieAcsFeeAmount] DECIMAL (9, 2) NULL,
    [Filler]                VARCHAR (405)  NULL,
    [EndMarker]             VARCHAR (1)    NULL,
    [ProcessCode]           VARCHAR (50)   NULL,
    CONSTRAINT [PK_AcsFileHeader_AcsFileHeaderId] PRIMARY KEY CLUSTERED ([AcsFileHeaderId] ASC) WITH (FILLFACTOR = 90)
);

