CREATE TABLE [dbo].[FileValidator_Transformed] (
    [FV_TransformedID]     INT              IDENTITY (1, 1) NOT NULL,
    [SourceFileID]         INT              NOT NULL,
    [PubCode]              VARCHAR (100)    NULL,
    [Sequence]             INT              NOT NULL,
    [FName]                VARCHAR (100)    NULL,
    [LName]                VARCHAR (100)    NULL,
    [Title]                VARCHAR (100)    NULL,
    [Company]              VARCHAR (100)    NULL,
    [Address]              VARCHAR (255)    NULL,
    [MailStop]             VARCHAR (255)    NULL,
    [City]                 VARCHAR (50)     NULL,
    [State]                VARCHAR (50)     NULL,
    [Zip]                  VARCHAR (50)     NULL,
    [Plus4]                VARCHAR (50)     NULL,
    [ForZip]               VARCHAR (50)     NULL,
    [County]               VARCHAR (100)    NULL,
    [Country]              VARCHAR (100)    NULL,
    [CountryID]            INT              NULL,
    [Phone]                VARCHAR (100)    NULL,
    [PhoneExists]          BIT              NULL,
    [Fax]                  VARCHAR (100)    NULL,
    [FaxExists]            BIT              NULL,
    [Email]                VARCHAR (100)    NULL,
    [EmailExists]          BIT              NULL,
    [CategoryID]           INT              NULL,
    [TransactionID]        INT              NULL,
    [TransactionDate]      DATETIME         NULL,
    [QDate]                DATETIME         NULL,
    [QSourceID]            INT              NULL,
    [RegCode]              VARCHAR (5)      NULL,
    [Verified]             VARCHAR (100)    NULL,
    [SubSrc]               VARCHAR (50)     NULL,
    [OrigsSrc]             VARCHAR (50)     NULL,
    [Par3C]                VARCHAR (10)      NULL,
    [Demo31]               BIT              NULL,
    [Demo32]               BIT              NULL,
    [Demo33]               BIT              NULL,
    [Demo34]               BIT              NULL,
    [Demo35]               BIT              NULL,
    [Demo36]               BIT              NULL,
    [Source]               VARCHAR (50)     NULL,
    [Priority]             VARCHAR (4)      NULL,
    [IGrp_No]              UNIQUEIDENTIFIER NULL,
    [IGrp_Cnt]             INT              NULL,
    [CGrp_No]              UNIQUEIDENTIFIER NULL,
    [CGrp_Cnt]             INT              NULL,
    [StatList]             BIT              NULL,
    [Sic]                  VARCHAR (8)      NULL,
    [SicCode]              VARCHAR (20)     NULL,
    [Gender]               VARCHAR (1024)   NULL,
    [IGrp_Rank]            VARCHAR (2)      NULL,
    [CGrp_Rank]            VARCHAR (2)      NULL,
    [Address3]             VARCHAR (255)    NULL,
    [Home_Work_Address]    VARCHAR (10)     NULL,
    [PubIDs]               VARCHAR (2000)   NULL,
    [Demo7]                VARCHAR (1)      NULL,
    [IsExcluded]           BIT              NULL,
    [Mobile]               VARCHAR (30)     NULL,
    [Latitude]             DECIMAL (18, 15) NULL,
    [Longitude]            DECIMAL (18, 15) NULL,
    [IsLatLonValid]        BIT              NULL,
    [LatLonMsg]            NVARCHAR (500)   NULL,
    [InSuppression]        BIT              NULL,
    [Score]                INT              NULL,
    [SuppressedDate]       DATE             NULL,
    [SuppressedEmail]      VARCHAR (100)    NULL,
    [EmailStatusID]        INT              NULL,
    [StatusUpdatedDate]    DATETIME         NULL,
    [StatusUpdatedReason]  NVARCHAR (200)   NULL,
    [IsMailable]           BIT              NULL,
    [Ignore]               BIT              NOT NULL,
    [IsDQMProcessFinished] BIT              NOT NULL,
    [DQMProcessDate]       DATETIME         NULL,
    [IsUpdatedInLive]      BIT              NOT NULL,
    [UpdateInLiveDate]     DATETIME         NULL,
    [STRecordIdentifier]   UNIQUEIDENTIFIER NOT NULL,
    [DateCreated]          DATETIME         CONSTRAINT [DF_FileValidator_Transformed_DateCreated] DEFAULT (getdate()) NULL,
    [DateUpdated]          DATETIME         NULL,
    [CreatedByUserID]      INT              NULL,
    [UpdatedByUserID]      INT              NULL,
    [ProcessCode]          VARCHAR (50)     NULL,
    [ImportRowNumber]      INT              NULL,
    CONSTRAINT [PK_FV_Transformed] PRIMARY KEY CLUSTERED ([STRecordIdentifier] ASC) WITH (FILLFACTOR = 90)
);


