CREATE TABLE [dbo].[IssueArchiveSubscription]
(
	IssueArchiveSubscriptionId int identity(1,1) not null,
	IssueArchiveSubscriberId int not null,
	IsComp bit not null,
	CompId int NULL,
	SubscriptionID int NULL,
	[SequenceID]                     INT          NULL,
    [PublisherID]                    INT          NOT NULL,
    [SubscriberID]                   INT          NOT NULL,
    [PublicationID]                  INT          NOT NULL,
    [ActionID_Current]               INT          NOT NULL,
    [ActionID_Previous]              INT          NULL,
    [SubscriptionStatusID]           INT          NULL,
    [IsPaid]                         BIT          NOT NULL,
    [QSourceID]                      INT          NULL,
    [QSourceDate]                    DATE         NULL,
    [DeliverabilityID]               INT          NULL,
    [IsSubscribed]                   BIT          NOT NULL,
    [SubscriberSourceCode]           varchar(256) NULL,
    [Copies]                         INT          NOT NULL,
    [OriginalSubscriberSourceCode]   varchar(256) NULL,
    [Par3cID]                        INT          NULL,
    [SubsrcTypeID]                   INT          NULL,
    [AccountNumber]                  VARCHAR (50) NULL,
	GraceIssues						 INT,
    [OnBehalfOf] 					 VARCHAR(256) NULL, 
    [MemberGroup] 					 VARCHAR(256) NULL, 
	[Verify] 						 VARCHAR(256) NULL, 
	IsNewSubscription				 bit,
	[DateCreated]                    DATETIME     NOT NULL,
    [DateUpdated]                    DATETIME     NULL,
    [CreatedByUserID]                INT          NOT NULL,
    [UpdatedByUserID]                INT          NULL, 
    CONSTRAINT [PK_IssueArchiveSubscription] PRIMARY KEY ([IssueArchiveSubscriptionId])
)
