CREATE TABLE [dbo].[IssueArchiveProductSubscription]
(
	IssueArchiveSubscriptionId int identity(1,1) not null,
	IsComp bit not null default((0)),
	CompId int NULL,
	IssueID int null,
	SplitID int null,
	[PubSubscriptionID]   INT           NOT NULL,
    [SubscriptionID]      INT           NOT NULL,
    [PubID]               INT           NOT NULL,
    [Demo7]               VARCHAR (1)   NULL,
    [QualificationDate]   DATE          NULL,
    [PubQSourceID]        INT           NULL,
    [PubCategoryID]       INT           NULL,
    [PubTransactionID]    INT           NULL,
    [EmailStatusID]       INT           NULL,
    [StatusUpdatedDate]   DATETIME      NULL,
    [StatusUpdatedReason] VARCHAR (200) NULL,
    [Email]               VARCHAR (100) NULL,
	[DateCreated]        DATETIME  CONSTRAINT [DF_PubSubscriptions_DateCreated] DEFAULT (getdate()) NULL,
    [DateUpdated]        DATETIME         NULL,
    [CreatedByUserID]    INT              NULL,
    [UpdatedByUserID]    INT              NULL,
	[SubscriptionStatusID] INT			  NULL DEFAULT ((1)),
	[AccountNumber]			VARCHAR(50)			NULL,
	[AddRemoveID]			INT			NULL DEFAULT ((0)),
	[Copies]				INT			NULL DEFAULT ((1)),
	[GraceIssues]			INT			NULL DEFAULT ((0)),
	[IMBSEQ]				VARCHAR(256) NULL,
	[IsActive]				BIT NULL,
	[IsPaid]				BIT NULL,
	[IsSubscribed]			BIT NULL,
	[MemberGroup]			VARCHAR(256) NULL,
	[OnBehalfOf]			VARCHAR(256) null,
	[OrigsSrc]				VARCHAR(256) null,
	[Par3CID]				int null,
	[SequenceID]			INT NULL,
	[Status]				VARCHAR(50) NULL,
	[SubscriberSourceCode]		VARCHAR(100) NULL,
	[SubSrcID]				int null,
	[Verify]				varchar(100) null,
	[ExternalKeyID]            INT              NULL,
    [FirstName]                VARCHAR (50)     NULL,
    [LastName]                 VARCHAR (50)     NULL,
    [Company]                  VARCHAR (100)    NULL,
    [Title]                    VARCHAR (255)    NULL,
    [Occupation]               VARCHAR (50)     NULL,
    [AddressTypeID]            INT              NULL,
    [Address1]                 VARCHAR (256)    NULL,
    [Address2]                 VARCHAR (256)    NULL,
	[Address3]                 VARCHAR (256)    NULL,
    [City]                     VARCHAR (50)     NULL,
    [RegionCode]               VARCHAR (50)     NULL,
    [RegionID]                 INT              NULL,
    [ZipCode]                  VARCHAR (50)     NULL,
    [Plus4]                    VARCHAR (10)        NULL,
    [CarrierRoute]             VARCHAR (10)     NULL,
    [County]                   VARCHAR (50)     NULL,
    [Country]                  VARCHAR (50)     NULL,
    [CountryID]                INT              NULL,
    [Latitude]                 DECIMAL (18, 15) NULL,
    [Longitude]                DECIMAL (18, 15) NULL,
    [IsAddressValidated]       BIT              NOT NULL DEFAULT((0)),
    [AddressValidationDate]    DATETIME         NULL,
    [AddressValidationSource]  VARCHAR (50)     NULL,
    [AddressValidationMessage] VARCHAR (MAX)    NULL,
    [Phone]                    VARCHAR (100)     NULL,
    [Fax]                      VARCHAR (100)     NULL,
    [Mobile]                   VARCHAR (100)     NULL,
    [Website]                  VARCHAR (255)    NULL,
    [Birthdate]                DATE             NULL,
    [Age]                      INT              NULL,
    [Income]                   VARCHAR (50)     NULL,
    [Gender]                   VARCHAR (50)     NULL,
    [tmpSubscriptionID]        INT              NULL,
    [IsLocked]                 BIT              DEFAULT ((0)) NOT NULL,
	[LockedByUserID]		   INT				NULL,
	[LockDate]				   DATETIME			NULL,
	[LockDateRelease]		   DATETIME         NULL,
    [PhoneExt]				   VARCHAR(25)	    NULL, 
    [IsInActiveWaveMailing]	   BIT				DEFAULT ((0)) NOT NULL,
	AddressTypeCodeId int null,
	AddressLastUpdatedDate datetime null,
	AddressUpdatedSourceTypeCodeId int null,
    [WaveMailingID] INT NULL, 
    [IGrp_No] UNIQUEIDENTIFIER NULL, 
    [SFRecordIdentifier] UNIQUEIDENTIFIER NULL, 
    [ReqFlag] INT NULL DEFAULT ((0)), 
    [SubGenSubscriberID] INT NULL DEFAULT ((0)), 
	[MailPermission] BIT NULL, 
    [FaxPermission] BIT NULL, 
    [PhonePermission] BIT NULL, 
    [OtherProductsPermission] BIT NULL, 
    [ThirdPartyPermission] BIT NULL, 
    [EmailRenewPermission] BIT NULL, 
    [TextPermission] BIT NULL, 
    CONSTRAINT [PK_IssueArchiveProductSubscription] PRIMARY KEY ([IssueArchiveSubscriptionId]), 
);
GO

CREATE NONCLUSTERED INDEX [IX_IssueArchiveProductSubscription_IssueArchiveSubscriptionId]
    ON [dbo].[IssueArchiveProductSubscription]([IssueArchiveSubscriptionId] ASC) WITH (FILLFACTOR = 90);
GO

CREATE NONCLUSTERED INDEX [IX_IssueArchiveProductSubscription_PubSubscriptionID]
    ON [dbo].[IssueArchiveProductSubscription]([PubSubscriptionID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_IssueArchiveProductSubscription_IssueID_PubSubscriptionID] 
	ON [dbo].[IssueArchiveProductSubscription] ([IssueID] ASC,[PubSubscriptionID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_IssueArchiveProductSubscription_SubscriptionID]
    ON [dbo].[IssueArchiveProductSubscription]([SubscriptionID] ASC);
GO


