CREATE TABLE [dbo].[Subscriptions] (
    [SubscriptionID]    INT              IDENTITY (1, 1) NOT NULL,
    [SEQUENCE]          INT              NOT NULL,
    [FNAME]             VARCHAR (100)    NULL,
    [LNAME]             VARCHAR (100)    NULL,
    [TITLE]             VARCHAR (100)    NULL,
    [COMPANY]           VARCHAR (100)    NULL,
    [ADDRESS]           VARCHAR (255)    NULL,
    [MAILSTOP]          VARCHAR (255)    NULL,
    [CITY]              VARCHAR (50)     NULL,
    [STATE]             VARCHAR (50)     NULL,
    [ZIP]               VARCHAR (10)     NULL,
    [PLUS4]             VARCHAR (4)      NULL,
    [FORZIP]            VARCHAR (50)     NULL,
    [COUNTY]            VARCHAR (20)     NULL,
    [COUNTRY]           VARCHAR (100)    NULL,
    [CountryID]         INT              NULL,
    [PHONE]             VARCHAR (100)    NULL,
    [PhoneExists]       BIT              NULL,
    [FAX]               VARCHAR (100)    NULL,
    [FaxExists]         BIT              NULL,
    [EMAIL]             VARCHAR (100)    NULL,
    [EmailExists]       BIT              NULL,
    [CategoryID]        INT              NULL,
    [TransactionID]     INT              NULL,
    [TransactionDATE]   SMALLDATETIME    NULL,
    [QDate]             DATETIME         NULL,
    [QSourceID]         INT              NULL,
    [REGCODE]           VARCHAR (5)      NULL,
    [VERIFIED]          VARCHAR (100)    NULL,
    [SUBSRC]            VARCHAR (8)      NULL,
    [ORIGSSRC]          VARCHAR (8)      NULL,
    [PAR3C]             VARCHAR (1)      NULL,
    [Demo31]            BIT              NULL,
    [Demo32]            BIT              NULL,
    [Demo33]            BIT              NULL,
    [Demo34]            BIT              NULL,
    [Demo35]            BIT              NULL,
    [Demo36]            BIT              NULL,
    [SOURCE]            VARCHAR (50)     NULL,
    [PRIORITY]          VARCHAR (4)      NULL,
    [IGRP_CNT]          INT              NULL,
    [CGRP_NO]           INT              NULL,
    [CGRP_CNT]          INT              NULL,
    [STATLIST]          BIT              NULL,
    [SIC]               VARCHAR (8)      NULL,
    [SICCODE]           VARCHAR (20)     NULL,
    [Gender]            VARCHAR (1024)   NULL,
    [IGRP_RANK]         VARCHAR (2)      NULL,
    [CGRP_RANK]         VARCHAR (2)      NULL,
    [ADDRESS3]          VARCHAR (255)    NULL,
    [HOME_WORK_ADDRESS] VARCHAR (10)     NULL,
    [PubIDs]            VARCHAR (2000)   NULL,
    [Demo7]             VARCHAR (1)      NULL,
    [IsExcluded]        BIT              NULL,
    [mobile]            VARCHAR (30)     NULL,
    [Latitude]          DECIMAL (18, 15) NULL,
    [Longitude]         DECIMAL (18, 15) NULL,
    [IsLatLonValid]     BIT              NULL,
    [LatLonMsg]         NVARCHAR (500)   NULL,
    [InSuppression]     BIT              NULL,
    [Score]             INT              NULL,
    [SuppressedDate]    DATE             NULL,
    [SuppressedEmail]   VARCHAR (100)    NULL,
    [IGRP_NO]           UNIQUEIDENTIFIER NOT NULL,
    [Notes]             VARCHAR (2000)   NULL,
    CONSTRAINT [PK_Subscriptions] PRIMARY KEY CLUSTERED ([SubscriptionID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Subscriptions_Category] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[Category] ([CategoryID]),
    CONSTRAINT [FK_Subscriptions_QSource] FOREIGN KEY ([QSourceID]) REFERENCES [dbo].[QSource] ([QsourceID]),
    CONSTRAINT [FK_Subscriptions_Transaction] FOREIGN KEY ([TransactionID]) REFERENCES [dbo].[Transaction] ([TransactionID])
);


GO

