CREATE TABLE [dbo].[SubscriptionsPurged](
	[SubscriptionPurgedID] [int] IDENTITY(1,1) NOT NULL,
	[PurgedDate] [datetime] NOT NULL,
	[SubscriptionID] [int] NOT NULL,
	[SEQUENCE] [int] NOT NULL,
	[FNAME] [varchar](100) NULL,
	[LNAME] [varchar](100) NULL,
	[TITLE] [varchar](100) NULL,
	[COMPANY] [varchar](100) NULL,
	[ADDRESS] [varchar](255) NULL,
	[MAILSTOP] [varchar](255) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](50) NULL,
	[ZIP] [varchar](10) NULL,
	[PLUS4] [varchar](4) NULL,
	[FORZIP] [varchar](50) NULL,
	[COUNTY] [varchar](50) NULL,
	[COUNTRY] [varchar](100) NULL,
	[CountryID] [int] NULL,
	[PHONE] [varchar](100) NULL,
	[PhoneExists] [bit] NULL,
	[FAX] [varchar](100) NULL,
	[FaxExists] [bit] NULL,
	[EMAIL] [varchar](100) NULL,
	[EmailExists] [bit] NULL,
	[CategoryID] [int] NULL,
	[TransactionID] [int] NULL,
	[TransactionDATE] [smalldatetime] NULL,
	[QDate] [datetime] NULL,
	[QSourceID] [int] NULL,
	[REGCODE] [varchar](5) NULL,
	[VERIFIED] [varchar](100) NULL,
	[SUBSRC] [varchar](25) NULL,
	[ORIGSSRC] [varchar](25) NULL,
	[PAR3C] [varchar](10) NULL,
	[SOURCE] [varchar](50) NULL,
	[PRIORITY] [varchar](4) NULL,
	[IGRP_CNT] [int] NULL,
	[CGRP_NO] [uniqueidentifier] NULL,
	[CGRP_CNT] [int] NULL,
	[STATLIST] [bit] NULL,
	[SIC] [varchar](8) NULL,
	[SICCODE] [varchar](20) NULL,
	[Gender] [varchar](1024) NULL,
	[IGRP_RANK] [varchar](2) NULL,
	[CGRP_RANK] [varchar](2) NULL,
	[ADDRESS3] [varchar](255) NULL,
	[HOME_WORK_ADDRESS] [varchar](10) NULL,
	[PubIDs] [varchar](2000) NULL,
	[Demo7] [varchar](1) NULL,
	[IsExcluded] [bit] NULL,
	[mobile] [varchar](30) NULL,
	[Latitude] [decimal](18, 15) NULL,
	[Longitude] [decimal](18, 15) NULL,
	[IsLatLonValid] [bit] NULL,
	[LatLonMsg] [varchar](1000) NULL,
	[Score] [int] NULL,
	[IGRP_NO] [uniqueidentifier] NOT NULL,
	[Notes] [varchar](2000) NULL,
	[DateCreated] [datetime] NULL,
	[DateUpdated] [datetime] NULL,
	[CreatedByUserID] [int] NULL,
	[UpdatedByUserID] [int] NULL,
	[AddressTypeCodeId] [int] NULL,
	[AddressLastUpdatedDate] [datetime] NULL,
	[AddressUpdatedSourceTypeCodeId] [int] NULL,
	[IsActive] [bit] NULL,
	[IsMailable] [bit] NULL,
	[ExternalKeyId] [int] NULL,
	[AccountNumber] [varchar](50) NULL,
	[EmailID] [int] NULL,
	[MailPermission] [bit] NULL,
	[FaxPermission] [bit] NULL,
	[PhonePermission] [bit] NULL,
	[OtherProductsPermission] [bit] NULL,
	[ThirdPartyPermission] [bit] NULL,
	[EmailRenewPermission] [bit] NULL,
	[TextPermission] [bit] NULL,
	[OriginatedPubID] [int] NULL,
 CONSTRAINT [PK_SubscriptionsPurged] PRIMARY KEY CLUSTERED 
(
	[SubscriptionPurgedID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
go
ALTER TABLE [dbo].[SubscriptionsPurged] ADD  CONSTRAINT [DF_SubscriptionsPurged_PurgedDate]  DEFAULT (getdate()) FOR [PurgedDate]
GO