(function(a,h){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI;
var d=Telerik.Web.Browser;
var c="rslDraghandleActive";
function g(i){if(a.isNumeric(i)){return null;
}if(i.endsWith("px")){return"px";
}if(i.endsWith("%")){return"%";
}if(i.endsWith("em")){return"em";
}return null;
}$telerik.toSlider=function(i){return i;
};
$telerik.findSlider=$find;
a.registerEnum(b,"SliderItemType",{None:1,Item:2,Tick:3});
a.registerEnum(b,"SliderTrackPosition",{Center:1,TopLeft:2,BottomRight:3});
a.registerEnum(b,"SliderThumbsInteractionMode",{Free:1,Lock:2,Push:3});
b.DecimalNumber={add:function(i,j,k){return f.parseDecimal((i+j),k);
},subtract:function(i,j,k){return f.parseDecimal((i-j),k);
},multiply:function(i,j,k){return f.parseDecimal((i*j),k);
},divide:function(i,j,k){return f.parseDecimal((i/j),k);
},remainder:function(i,j,k){i=Math.round(i*k);
j=Math.round(j*k);
return f.parseDecimal((i%j)/k,k);
},parseDecimal:function(j,k){if(typeof(j)=="undefined"){return Number.NaN;
}if(typeof(j)!="number"){try{j=parseFloat(j);
}catch(i){return Number.NaN;
}}if(isNaN(j)){return j;
}return(Math.round(j*k)/k);
}};
var f=b.DecimalNumber;
b.RadSlider=function(i){var j=this;
b.RadSlider.initializeBase(j,[i]);
j._minimumValue=0;
j._maximumValue=100;
j._value=0;
j._orientation=b.Orientation.Horizontal;
j._isHorizontal=true;
j._animationDuration=100;
j._showDecreaseHandle=true;
j._showIncreaseHandle=true;
j._showDragHandle=true;
j._enabled=true;
j._slideStep=1;
j._smallChange=1;
j._largeChange=0;
j._clickOffset=0;
j._trackMouseWheel=true;
j._width="";
j._height="";
j._skin="Default";
j._autoPostBack=false;
j._initializedInternal=false;
j._disposed=false;
j._selectedRegionStartValue=0;
j._firstValueOffset;
j._firstValueDragHandlePosition;
j._wrapperElement=null;
j._dragHandleElement=null;
j._mouseupHandler=null;
j._mouseWheelHandler=null;
j._documentKeyDownDelegate=null;
j._handleFocusDelegate=null;
j._handleBlurDelegate=null;
j._inSlidingMode=false;
j._dragText="Drag";
j._increaseText="Increase";
j._decreaseText="Decrease";
j._uniqueID=null;
j._resizeExtender=null;
j._selectionEnd=0;
j._isSelectionRangeEnabled=false;
j._endDragHandleElement=null;
j._endResizeExtender=null;
j._enableDragRange=false;
j._rangeResizeExtender=null;
j._children=null;
j._itemData=null;
j._childControlsCreated=false;
j._itemType=b.SliderItemType.None;
j._itemBinding={textField:"",valueField:"",toolTipField:""};
j._appendDataBoundItems=false;
j._clientDataSourceID="";
j._clientDataSource=null;
j._clientDataSourceChangeHanlderDelgate=Function.createDelegate(j,j._clientDataSourceChangeHanlder);
j._smallTickSize=0;
j._largeTickSize=0;
j._renderLargeTicks=false;
j._renderSmallTicks=false;
j._liveDrag=true;
j._liveDragValue;
j._liveDragHandleElement=null;
j._liveDragEndHandleElement=null;
j._trackPosition=b.SliderTrackPosition.Center;
j._isDirectionReversed=false;
j._enableServerSideRendering=false;
j._thumbsInteractionMode=b.SliderThumbsInteractionMode.Free;
j._rightToLeft=false;
j._precision=100;
j._accessKey="";
j._tabIndex=0;
j._valueBeforeAnimation=null;
j._selectionEndBeforeAnimation=null;
j.repaint=j.redraw;
j.Redraw=j.redraw;
j._onWindowResizeDelegate=null;
};
b.RadSlider.prototype={initialize:function(){var j=this;
var i=j._minimumValue;
if(i>j._maximumValue){throw Error.argumentOutOfRange("_minimumValue",i,"MinimumValue should be smaller than MaximumValue");
}j._initializeSelectedRegionStartValue();
j._initializeSliderSelection();
j.updateClientState();
if(j._enableServerSideRendering){j._initializeFields();
}b.RadSlider.callBaseMethod(j,"initialize");
j._initializeSliderControl();
j._keyboardNavigationSettings&&j._keyboardNavigationSettings.set_element(j._dragHandleElement);
j._initializeClientDataBinding();
a.raiseControlEvent(j,"load",{});
},_initializeSliderSelection:function(){var l=this;
var k=l._value=l._getValueFromIndex(l._value);
var j;
var i=l._isDirectionReversed;
var m;
if(l._isSelectionRangeEnabled){j=l._selectionEnd=l._getValueFromIndex(l._selectionEnd);
if((j<k&&!i)||(j>k&&i)){m=l._selectionEnd;
l._selectionEnd=k;
l._value=m;
}}},_initializeClientDataBinding:function(){var j=this,i=j.get_clientDataSourceID();
if(i&&$find(i)==null){Sys.Application.add_load(function(){j.dataBind();
});
}else{j.dataBind();
}},dataBind:function(){var j=this,i=j.get_clientDataSource();
if(i){j._bindToClientDataSource(i);
}else{j._dataBind();
}},_bindToClientDataSource:function(i){if(i&&(i instanceof b.RadClientDataSource)){i.remove_change(this._clientDataSourceChangeHanlderDelgate);
i.add_change(this._clientDataSourceChangeHanlderDelgate);
i.fetch();
}},_clientDataSourceChangeHanlder:function(k){var i=this.get_clientDataSource();
if(!i){return;
}var j=i.view();
this.set_dataSource(j);
this._dataBind();
},_dataBind:function(){var o=this,l=o.get_dataSource();
if(!l||typeof(l.length)=="undefined"){return;
}if(!o._appendDataBoundItems){o._removeAllItems();
}var n=o._itemBinding,q=n.textField,s=n.valueField,r=n.toolTipField;
for(var m=0;
m<l.length;
m++){var k=l[m];
var p={text:k[q],value:k[s],tooltip:k[r]};
var j=new b.SliderItemDataBindingEventArgs(k);
this.raiseEvent("itemDataBinding",j);
if(j.get_cancel()){continue;
}o._addItem(p);
o._raiseItemDataBoundEvent(p,k);
}o._initializeSliderSelection();
o.raiseEvent("dataBound");
o.redraw(true);
o.updateClientState();
},_removeAllItems:function(){var j=this,i=j.get_itemData();
while(i.length){j._removeItem();
}},_raiseItemDataBoundEvent:function(k,j){var i=new b.SliderItemDataBoundEventArgs(k,j);
this.raiseEvent("itemDataBound",i);
},get_clientDataSourceID:function(){return this._clientDataSourceID;
},set_clientDataSourceID:function(i){this._clientDataSource=null;
this._dataSource=null;
this._clientDataSourceID=i;
},get_clientDataSource:function(){var i=this.get_clientDataSourceID();
if(i){var j=$find(i);
if(j&&j instanceof b.RadClientDataSource){return j;
}}return this._clientDataSource;
},set_clientDataSource:function(i){this.set_clientDataSourceID("");
this._clientDataSource=i;
},get_dataSource:function(){return this._dataSource;
},set_dataSource:function(i){this._dataSource=i;
},get_itemBinding:function(){return this._itemBinding;
},_addParentVisibilityChangeHandler:function(i,j){if(i){if($telerik.isIE){$telerik.addHandler(i,"propertychange",j);
}else{i.addEventListener("DOMAttrModified",j,false);
}}},_removeParentVisibilityChangeHandler:function(i,j){if(i&&j){if($telerik.isIE){$telerik.removeHandler(i,"propertychange",j);
}else{i.removeEventListener("DOMAttrModified",j,false);
}}},_initializeSliderControl:function(k){if(k){var m=$telerik.isIE;
if(m){k=k.rawEvent;
}var j=(m&&k&&(k.propertyName=="style.display"||k.propertyName=="className"));
var i=(!m&&(k.attrName=="style"||k.attrName=="class"));
if(!(i||j)){return;
}}this._disposeParentVisibilityChangeHandler();
var l=$telerik.getInvisibleParent(this.get_element());
if(l){this.add_parentShown(this.get_element());
}else{if(!this._initializedInternal){this._initializedInternal=true;
if(!this._wrapperElement){this._initializeLayout();
}else{this._setEnabled();
}this._setSliderElementsSize();
this._initializeSlider();
this._createChildControls();
this._setValuesForSlider();
}}},_disposeParentVisibilityChangeHandler:function(){if(this._invisibleParent&&this._onParentVisibilityChangeDelegate){this._removeParentVisibilityChangeHandler(this._invisibleParent,this._onParentVisibilityChangeDelegate);
this._invisibleParent=null;
this._onParentVisibilityChangeDelegate=null;
}},_initializeFields:function(){var i=this.get_id();
var n=this._wrapperElement=$get("RadSliderWrapper_"+i);
if(!n){return;
}n.setAttribute("unselectable","on");
$addHandler(this.get_element(),"click",$telerik.cancelRawEvent);
this._setRightToLeft();
var j=this._decreaseHandleElement=$get("RadSliderDecrease_"+i);
if(j){$addHandler(j,"mouseup",Function.createDelegate(j,this._clearFocus));
$addHandlers(j,{mousedown:this._onDecreaseMouseDown},this);
}var m=this._trackElement=$get("RadSliderTrack_"+i);
m.setAttribute("unselectable","on");
var l=this._selectedRegionElement=$get("RadSliderSelected_"+i);
l.setAttribute("unselectable","on");
this._dragHandleElement=$get("RadSliderDrag_"+i);
j=this._liveDragHandleElement=$get("liveDrag_RadSliderDrag_"+i);
if(j){$addHandler(j,"mouseup",Function.createDelegate(j,this._clearFocus));
}this._endDragHandleElement=$get("RadSliderEndDrag_"+i);
j=this._liveDragEndHandleElement=$get("liveDrag_RadSliderEndDrag_"+i);
if(j){$addHandler(j,"mouseup",Function.createDelegate(j,this._clearFocus));
}j=this._increaseHandleElement=$get("RadSliderIncrease_"+i);
if(j){$addHandler(j,"mouseup",Function.createDelegate(j,this._clearFocus));
$addHandlers(j,{mousedown:this._onIncreaseMouseDown},this);
}var k=this._listElement=$telerik.getElementByClassName(n,"rslItemsWrapper","ul");
if(k){k.setAttribute("unselectable","on");
$telerik.addMobileHandler(this,k,"mousedown",this._onTrackMouseDown);
}},_initializeLayout:function(){var j=this.get_element();
$addHandler(j,"click",$telerik.cancelRawEvent);
var m=j.className;
var l=this._skin;
if(m==""||m.indexOf("RadSlider")==-1){m="RadSlider "+("RadSlider_"+l);
Sys.UI.DomElement.addCssClass(j,m);
}this._setRightToLeft();
var i=this.get_id();
var o=this._wrapperElement=document.createElement("div");
j.appendChild(o);
o.id="RadSliderWrapper_"+i;
o.setAttribute("unselectable","on");
this._setWidth();
this._setHeight();
this._setOrientation();
this._setEnabled();
this._setTrackPosition();
this._setShowHandle(true);
var n=this._trackElement=document.createElement("div");
n.setAttribute("unselectable","on");
n.id="RadSliderTrack_"+i;
Sys.UI.DomElement.addCssClass(n,"rslTrack");
if(!this._showDecreaseHandle){n.style[this._getLocationProperty()]="0px";
}o.appendChild(n);
var k=this._selectedRegionElement=document.createElement("div");
k.setAttribute("unselectable","on");
k.id="RadSliderSelected_"+i;
Sys.UI.DomElement.addCssClass(k,"rslSelectedregion");
k.innerHTML="<!-- -->";
n.appendChild(k);
this._setEnableDragRange();
this._setShowDragHandle();
this._setShowHandle(false);
},_setRightToLeft:function(){var i=this.get_element();
if($telerik.isRightToLeft(i)){Sys.UI.DomElement.addCssClass(i,"RadSliderRTL");
Sys.UI.DomElement.addCssClass(i,"RadSliderRTL_"+this._skin);
this._rightToLeft=true;
}},_createHandleUI:function(k,n,i,m){var j=document.createElement("a");
j.id=k;
j.href="#";
Sys.UI.DomElement.addCssClass(j,i);
j.title=n;
if(!m){$addHandler(j,"mouseup",Function.createDelegate(j,this._clearFocus));
}var l=document.createElement("span");
l.innerHTML=n;
j.appendChild(l);
return j;
},addSliderItem:function(j,i){if(this._canAddItem()){this._addItem(j,i);
this.redraw(true);
}},_canAddItem:function(){return this._itemType==b.SliderItemType.Item;
},_addItem:function(k,j){var i=this._itemData;
if(!i.length){this._maximumValue=this._minimumValue;
}if(isNaN(j)){i.push(k);
}else{i.splice(j,0,k);
}this._maximumValue+=2;
},removeSliderItem:function(i){if(this._canRemoveItem()){this._removeItem(i);
this.redraw(true);
}},_canRemoveItem:function(){return this._itemType==b.SliderItemType.Item&&this._itemData.length>0;
},_removeItem:function(j){var i=this._itemData;
if(isNaN(j)){i.pop();
}else{i.splice(j,1);
}this._maximumValue-=2;
},setValue:function(j,i){this._setNewValue(j,true,i,i);
},_clearFocus:function(i){this.blur();
},_initializeSelectedRegionStartValue:function(){if(this._selectedRegionStartValue==this._minimumValue){this._selectedRegionStartValue=h;
}else{this._selectedRegionStartValue=this._getValueFromIndex(this._selectedRegionStartValue);
}},_addDragHandleElement:function(o,m){var l=this._dragText;
var i="rslDraghandle";
var k=(m?"RadSliderEndDrag_":"RadSliderDrag_")+this.get_id();
var j=this._createHandleUI(k,l,i,true);
o.appendChild(j);
this[m?"_endDragHandleElement":"_dragHandleElement"]=j;
if(!this._liveDrag){var n=this._createHandleUI(("liveDrag_"+k),l,(i+" rslLiveDragHandle"));
o.appendChild(n);
this[m?"_liveDragEndHandleElement":"_liveDragHandleElement"]=n;
}},_setWidth:function(){var k=parseInt(this._width,10);
var l=g(this._width);
var j=(this._renderMode===b.RenderMode.Lite);
if(!isNaN(k)&&(k>0)){if(j&&l!==null){k+=l;
}else{k+="px";
}var i=this.get_element();
var m=this._wrapperElement;
if(i.style.width!=k){i.style.width=k;
}if(m.style.width!=k){m.style.width=j?"100%":k;
}}},_setHeight:function(){var j=parseInt(this._height,10);
if(!isNaN(j)&&(j>0)){j+="px";
var i=this.get_element();
var k=this._wrapperElement;
if(i.style.height!=j){i.style.height=j;
}if(k.style.height!=j){k.style.height=j;
}}},_setOrientation:function(){var k=this._wrapperElement;
var i=this._isHorizontal;
Sys.UI.DomElement.removeCssClass(k,(!i?"rslHorizontal":"rslVertical"));
Sys.UI.DomElement.addCssClass(k,(i?"rslHorizontal":"rslVertical"));
this._isHorizontal=!i;
var j=this._getTrackPositionClass(this._trackPosition);
this._isHorizontal=i;
Sys.UI.DomElement.removeCssClass(k,j);
this._setTrackPosition();
},_setEnabled:function(){var j=this._wrapperElement;
var i=this._isSelectionRangeEnabled;
if(this._enabled){Sys.UI.DomElement.removeCssClass(j,"rslDisabled");
this._createDragHandleExtender();
if(i){this._createDragHandleExtender(true);
this._setEnableDragRange();
}}else{Sys.UI.DomElement.addCssClass(j,"rslDisabled");
this._disposeObject("_resizeExtender");
if(i){this._disposeObject("_endResizeExtender");
this._disposeObject("_rangeResizeExtender");
}}},_getTrackPositionClass:function(k){var i=this._isHorizontal;
var j=(i)?"rslMiddle":"rslCenter";
if(k==b.SliderTrackPosition.TopLeft){j=(i)?"rslTop":"rslLeft";
}else{if(k==b.SliderTrackPosition.BottomRight){j=(i)?"rslBottom":"rslRight";
}}return j;
},_setTrackPosition:function(j){if(this._itemType==b.SliderItemType.None){return;
}var k=this._wrapperElement;
var i;
if(j!=null){i=this._getTrackPositionClass(j);
Sys.UI.DomElement.removeCssClass(k,i);
}i=this._getTrackPositionClass(this._trackPosition);
Sys.UI.DomElement.addCssClass(k,i);
},_setShowHandle:function(i){var s=i?"_showDecreaseHandle":"_showIncreaseHandle";
var m=i?"_decreaseHandleElement":"_increaseHandleElement";
var q=this._getLocationProperty();
var u=this._trackElement;
var p=this._listElement;
var r=this[s];
var l=this[m];
if(l){if(!r){clearTimeout(this[i?"_decreaseMDownInterval":"_increaseMDownInterval"]);
$clearHandlers(l);
l.parentNode.removeChild(l);
this[m]=null;
if(i){if(u){u.style[q]="0";
}if(p){p.style[q]="0";
}}}}else{if(r){if(i){if(u){u.style[q]="";
}if(p){p.style[q]="";
}}var k=this._getHandleCssClass(i);
var o=this._isDirectionReversed;
var t=this[(i&&!o)||(!i&&o)?"_decreaseText":"_increaseText"];
var n=(i?"RadSliderDecrease_":"RadSliderIncrease_")+this.get_id();
var j=this[m]=this._createHandleUI(n,t,("rslHandle "+k));
this._wrapperElement.appendChild(j);
$addHandlers(j,{mousedown:this[i?"_onDecreaseMouseDown":"_onIncreaseMouseDown"]},this);
}}this._setupHandlesRelatedCssClasses();
},_getHandleCssClass:function(i){var o=this._renderMode==b.RenderMode.Lite,n=this._isHorizontal,m="p-icon ",l="p-i-arrow-right",k="p-i-arrow-left",q="p-i-arrow-down",p="p-i-arrow-up";
if(o){if(n){j=i?"rslDecrease "+m+k:"rslIncrease "+m+l;
}else{j=i?"rslDecrease "+m+p:"rslIncrease "+m+q;
}}else{var j=i?"rslDecrease":"rslIncrease ";
}return j;
},_initializeDragHandle:function(i){this._addDragHandleElement(this._trackElement,i);
this._createDragHandleExtender(i);
},_disposeDragHandle:function(j){this._disposeObject(j?"_endResizeExtender":"_resizeExtender");
var i=this[j?"_endDragHandleElement":"_dragHandleElement"];
i.parentNode.removeChild(i);
this[j?"_endDragHandleElement":"_dragHandleElement"]=null;
if(!this._liveDrag){var k=this[j?"_liveDragEndHandleElement":"_liveDragHandleElement"];
k.parentNode.removeChild(k);
this[j?"_liveDragEndHandleElement":"_liveDragHandleElement"]=null;
}},_setShowEndDragHandle:function(){var j=this._isSelectionRangeEnabled;
var k=this._showDragHandle;
var i=this._endDragHandleElement;
if(i){if(!k||!j){if(!j&&(i.id=="RadSliderDrag_"+this.get_id())){this._isSelectionRangeEnabled=true;
this._switchDragHanldes();
this._isSelectionRangeEnabled=false;
}this._disposeDragHandle(true);
}}else{if(k&&j){this._initializeDragHandle(true);
}}},_setShowDragHandle:function(){var i=this._showDragHandle;
if(this._dragHandleElement){if(!i){this._disposeDragHandle();
this._setShowEndDragHandle();
this._handleInSlidingMode=null;
}}else{if(i){this._initializeDragHandle();
this._setShowEndDragHandle();
}}},_setEnableDragRange:function(){var i=this._enableDragRange;
var j=this._isSelectionRangeEnabled;
if(this._rangeResizeExtender){if(!i||!j){this._disposeObject("_rangeResizeExtender");
}}else{if(i&&j){this._createRangeExtender(this._selectedRegionElement);
}}},_createDragHandleExtender:function(j){var m;
var l;
var k={};
if(!this._enabled){return;
}var i=this._liveDrag?this[j?"_endDragHandleElement":"_dragHandleElement"]:this[j?"_liveDragEndHandleElement":"_liveDragHandleElement"];
if(i){if(!j&&!this._resizeExtender){l=$telerik.getCurrentStyle(i,"cursor","pointer");
k[l]=i;
m=this._resizeExtender=new b.ResizeExtender(this,i,k,null,null,l,false);
m.set_hideIframes(false);
}else{if(j&&!this._endResizeExtender){l=$telerik.getCurrentStyle(i,"cursor","pointer");
k[l]=i;
m=this._endResizeExtender=new b.ResizeExtender(this,i,k,null,null,l,false);
m.set_hideIframes(false);
}}}},_createRangeExtender:function(k){if(!this._enabled){return;
}if(k&&!this._rangeResizeExtender){var j=$telerik.getCurrentStyle(k,"cursor","pointer");
var i={};
i[j]=k;
var l=this._rangeResizeExtender=new b.ResizeExtender(this,k,i,null,null,j,false);
l.set_hideIframes(false);
}},_refreshLayout:function(){var i=this.get_element();
if(!i||$telerik.getInvisibleParent(i)){return;
}this._setSliderElementsSize();
this._setValuesForSlider();
},_setValuesForSlider:function(){this._setNewValue(this._value,true,true);
if(this._isSelectionRangeEnabled){this._setNewValue(this._selectionEnd,false,true);
}},_setSliderElementsSize:function(){if(!this._wrapperElement){return;
}var j=(this._showIncreaseHandle)?this._getIncreaseHandleBounds().width:0;
var i=(this._showDecreaseHandle)?this._getDecreaseHandleBounds().width:0;
var p=this._trackElement;
var s=(this._renderMode==b.RenderMode.Lite)?this.get_length():(this.get_length()-(i+j+this._getTrackMargin()));
p.style.width="";
p.style.height="";
var r=$telerik.getSize(p);
var k=this._isHorizontal;
var t=(k)?s:r.width;
var q=(!k)?s:r.height;
if(this._renderMode==b.RenderMode.Lite){this._setupHandlesRelatedCssClasses();
t=t-parseFloat(a(this._wrapperElement).css("padding-left"))-parseFloat(a(this._wrapperElement).css("padding-right"));
q=q-parseFloat(a(this._wrapperElement).css("padding-top"))-parseFloat(a(this._wrapperElement).css("padding-bottom"));
}if(t>0&&q>0){$telerik.setSize(p,{width:t,height:q});
}var l=false;
if(this._itemsUICreated&&this._children&&this._itemType==b.SliderItemType.Tick){var o=this._checkRenderTicks();
var m=o.renderLargeTicks;
var n=o.renderSmallTicks;
if(this._renderLargeTicks!=m||this._renderSmallTicks!=n){this._children.clear();
this._itemsUICreated=false;
this._itemData=[];
this._renderLargeTicks=m;
this._renderSmallTicks=n;
this._createChildControls();
l=true;
}}if(!l){this._setItemsSize();
}this._setFirstValueOffset();
},_setFirstValueOffset:function(){var i=Math.floor(this._getHalfDragHandleSize());
if(this._itemType==b.SliderItemType.Tick){this._firstValueOffset=i;
this._firstValueDragHandlePosition=0;
}else{this._firstValueOffset=0;
this._firstValueDragHandlePosition=-i;
}},_initializeSlider:function(){this._initializeEventHandlers();
},_initializeEventHandlers:function(){var m=this;
this._mouseupHandler=Function.createDelegate(this,this._onMouseUp);
$telerik.addExternalHandler(document,"mouseup",this._mouseupHandler);
$telerik.addExternalHandler(document,"mousemove",this._mouseupHandler);
$telerik.addMobileHandler(this,this._trackElement,"mousedown",this._onTrackMouseDown);
this._setTrackMouseWheel();
var l=this._dragHandleElement;
if(l){this._applyAccessKey();
this._documentKeyDownDelegate=Function.createDelegate(this,this._onKeyDown);
$telerik.addExternalHandler(document,"keydown",this._documentKeyDownDelegate);
this._handleFocusDelegate=Function.createDelegate(this,this._handleFocus);
this._handleBlurDelegate=Function.createDelegate(this,this._handleBlur);
var n=this._tabIndex;
for(var k=0;
k<2;
k++){var j=(k==0)?l:this._endDragHandleElement;
if(j){$telerik.addExternalHandler(j,"focus",this._handleFocusDelegate);
$telerik.addExternalHandler(j,"blur",this._handleBlurDelegate);
if(n){j.tabIndex=n;
}}}}if(m._renderMode==b.RenderMode.Lite){m._onWindowResizeDelegate=Function.createDelegate(m,m._windowResizeHandler);
$addHandler(window,"resize",m._onWindowResizeDelegate);
}},_setTrackMouseWheel:function(){this._disposeTrackMouseWheelHandler();
if(!this._trackMouseWheel||this._isSelectionRangeEnabled){return;
}var i=this._trackElement;
this._mouseWheelHandler=Function.createDelegate(this,this._onMouseWheel);
$telerik.addExternalHandler(i,"mousewheel",this._mouseWheelHandler);
if($telerik.isFirefox){$telerik.addExternalHandler(i,"DOMMouseScroll",this._mouseWheelHandler);
}},_disposeTrackMouseWheelHandler:function(){var i=this._trackElement;
if(this._mouseWheelHandler&&i){$telerik.removeExternalHandler(i,"mousewheel",this._mouseWheelHandler);
if($telerik.isFirefox){$telerik.removeExternalHandler(i,"DOMMouseScroll",this._mouseWheelHandler);
}this._mouseWheelHandler=null;
}},dispose:function(){this._disposed=true;
this._animatedHandle=null;
this._handleInSlidingMode=null;
this._disposeHandlers();
this._disposeSlider();
b.RadSlider.callBaseMethod(this,"dispose");
},_disposeSlider:function(){this._disposeObject("_resizeExtender");
this._disposeObject("_endResizeExtender");
this._disposeObject("_rangeResizeExtender");
clearTimeout(this._increaseMDownInterval);
clearTimeout(this._decreaseMDownInterval);
clearTimeout(this._mDownInterval);
this._dragHandleElement=null;
this._endDragHandleElement=null;
this._decreaseHandleElement=null;
this._increaseHandleElement=null;
this._trackElement=null;
this._selectedRegionElement=null;
this._liveDragHandleElement=null;
this._liveDragEndHandleElement=null;
this._listElement=null;
this._wrapperElement=null;
},_disposeHandlers:function(){if(this.get_element()){$clearHandlers(this.get_element());
}if(this._trackElement){$clearHandlers(this._trackElement);
}if(this._listElement){$clearHandlers(this._listElement);
}if(this._decreaseHandleElement){$clearHandlers(this._decreaseHandleElement);
}if(this._increaseHandleElement){$clearHandlers(this._increaseHandleElement);
}if(this._selectedRegionElement){$clearHandlers(this._selectedRegionElement);
}if(this._mouseupHandler){$telerik.removeExternalHandler(document,"mouseup",this._mouseupHandler);
$telerik.removeExternalHandler(document,"mousemove",this._mouseupHandler);
this._mouseupHandler=null;
}if(this._documentKeyDownDelegate){$telerik.removeExternalHandler(document,"keydown",this._documentKeyDownDelegate);
this._documentKeyDownDelegate=null;
}for(var k=0;
k<2;
k++){var j=(k==0)?this._dragHandleElement:this._endDragHandleElement;
if(j){$telerik.removeExternalHandler(j,"focus",this._handleFocusDelegate);
$telerik.removeExternalHandler(j,"blur",this._handleBlurDelegate);
}}this._handleFocusDelegate=null;
this._handleFocusDelegate=null;
if(this._accessKeyTextbox){$clearHandlers(this._accessKeyTextbox);
this._accessKeyTextbox.removeAttribute("accessKey");
this._accessKeyTextbox=null;
}this._disposeTrackMouseWheelHandler();
this._disposeParentVisibilityChangeHandler();
if(this._onWindowResizeDelegate){$removeHandler(window,"resize",this._onWindowResizeDelegate);
this._onWindowResizeDelegate=null;
}},_disposeObject:function(i){if(this[i]){this[i].dispose();
this[i]=null;
}},onDragStart:function(k){var m=k.element;
var i=a(m);
if(m===this._selectedRegionElement){return this._onDragStartRange(k);
}this._ensureActiveStateIsAdded(m);
var v=parseFloat(i.css("left"),10)||0;
if(isNaN(parseInt(m.style.left,10))){m.style.left=v+"px";
}var z=parseFloat(i.css("top"),10)||0;
if(isNaN(parseInt(m.style.top,10))){m.style.top=z+"px";
}var t=this._isSelectionRangeEnabled;
var q=this._thumbsInteractionMode;
var u=t&&(b.SliderThumbsInteractionMode.Lock==q);
var A=t&&(b.SliderThumbsInteractionMode.Push==q);
var o=this._dragHandleElement;
var r=(m.id.indexOf(o.id)>-1);
var w=this._liveDrag;
if(!w){Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandleActive");
if(u||A){this[r?"_liveDragEndHandleElement":"_liveDragHandleElement"].style.zIndex="";
m.style.zIndex="2";
}m=r?o:this._endDragHandleElement;
}this._handleInSlidingMode=m;
this._valueOnSlideStart=this._getActiveDragHandleValue(this._updateSelectionStart(null,m));
if(!w){this._liveDragValue=this._valueOnSlideStart;
}this._inSlidingMode=true;
var n=this._cachedDragHandleSize=$telerik.getSize(m);
var B=this._trackElement;
var C=$telerik.getBorderBox(B);
var D=$telerik.getSize(B);
D.width-=C.horizontal;
D.height-=C.vertical;
var p=this._firstValueDragHandlePosition;
var j=(r?this._endDragHandleElement:o);
var y=j?parseInt((j).style[this._getLocationProperty()],10):0;
if(u||A){j.style.zIndex="";
m.style.zIndex="1";
if(u){var x=this._getSizeProperty();
D[x]=r?y+n[x]:(D[x]-y);
D[x]+=p;
}}var s=this._isHorizontal;
var l=new Telerik.Web.UI.Bounds((s?p:v),(!s?p:z),((s)?(D.width+(p==0?0:n.width)):n.width),((!s)?(D.height+(p==0?0:n.height)):n.height));
if(u&&!r){l[this._getPointProperty()]=y;
}this._cachedSliderBounds=l;
this.raiseEvent("slideStart");
return true;
},_ensureActiveStateIsAdded:function(i){Sys.UI.DomElement.addCssClass(i,c);
},_onDragStartRange:function(j){var o=j.element;
var i=a(o);
var n=parseFloat(i.css("left"),10)||0;
if(isNaN(parseInt(o.style.left,10))){o.style.left=n+"px";
}var q=parseFloat(i.css("top"),10)||0;
if(isNaN(parseInt(o.style.top,10))){o.style.top=q+"px";
}var r=this._trackElement;
var s=$telerik.getBorderBox(r);
var t=$telerik.getSize(r);
t.width-=s.horizontal;
t.height-=s.vertical;
this._valuesOnSlideStart=[this._value,this._selectionEnd];
if(!this._liveDrag){this._liveDragValue=this._valuesOnSlideStart[0];
if(this._showDragHandle){var l=this._liveDragHandleElement;
Sys.UI.DomElement.removeCssClass(l,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(l,"rslLiveDragHandleActive");
l.blur();
l=this._liveDragEndHandleElement;
Sys.UI.DomElement.removeCssClass(l,"rslLiveDragHandle");
Sys.UI.DomElement.addCssClass(l,"rslLiveDragHandleActive");
l.blur();
}}this._inSlidingMode=true;
var p=this._cachedRangeSize=$telerik.getSize(o);
var m=this._isHorizontal;
var k=new Telerik.Web.UI.Bounds((m?0:n),(!m?0:q),((m)?t.width:p.width),((!m)?t.height:p.height));
this._cachedSliderBounds=k;
this.raiseEvent("slideRangeStart");
return true;
},onDragEnd:function(k){var i=k.element;
if(i===this._selectedRegionElement){return this._onDragEndRange(k);
}var m=this._handleInSlidingMode;
var v=this._updateSelectionStart(null,m);
if(!this._liveDrag){Sys.UI.DomElement.removeCssClass(i,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(i,"rslLiveDragHandle");
var o=this._liveDragValue;
var r=this._calculateDragHandleOffset(o);
var p=this._getLocationProperty();
var n=this._isDirectionReversed;
var t=this._value;
var s=this._selectionEnd;
var u=v&&((o>s&&!n)||(o<s&&n));
u=u||(!v&&((o<t&&!n)||(o>t&&n)));
var q=u&&this._isSelectionRangeEnabled&&(b.SliderThumbsInteractionMode.Push==this._thumbsInteractionMode);
var l=q&&this._setActiveDragHandleValue(o,!v);
if(!l){l=this._setActiveDragHandleValue(o,v);
}if(!l){if(q){var j=v?this._endDragHandleElement:this._dragHandleElement;
j.style[p]=r+"px";
this._updateRelativeLiveDragHandlePosition(j);
if(!v){this._selectedRegionElement.style[p]=r+"px";
}}m.style[p]=r+"px";
this._updateSelectedRegion(m,r);
}else{if(q){this._setActiveDragHandleValue((v?t:s),v,true,false);
}this._updateRelativeLiveDragHandlePosition(m);
}}else{this.updateClientState();
}this._cachedSliderBounds=null;
this._cachedDragHandleSize=null;
this._inSlidingMode=false;
this._ensureActiveStateIsRemoved(m);
this.raiseEvent("slideEnd");
if(this._autoPostBack&&this._valueOnSlideStart!=this._getActiveDragHandleValue(v)){this._raiseValueChangedServerEvent();
}},_ensureActiveStateIsRemoved:function(j){var i=$telerik.getElementByClassName(this.get_element(),c);
if(i&&j){Sys.UI.DomElement.removeCssClass(j,c);
}},_onDragEndRange:function(j){var r=this._valuesOnSlideStart;
if(!this._liveDrag){var q=this._showDragHandle;
if(q){var m=this._liveDragHandleElement;
Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandle");
m=this._liveDragEndHandleElement;
Sys.UI.DomElement.removeCssClass(m,"rslLiveDragHandleActive");
Sys.UI.DomElement.addCssClass(m,"rslLiveDragHandle");
}var o=this._liveDragValue;
var n=o+r[1]-r[0];
var k=this._setActiveDragHandleValue(n,false,null,null,true);
if(!k){k=this._setActiveDragHandleValue(o,true,null,null,true);
}var l=this._dragHandleElement;
var i=this._endDragHandleElement;
var p=this._getLocationProperty();
if(k){this._setActiveDragHandleValue(r[1],false,true,false,true);
this._selectedRegionElement.style[p]=this._calculateDragHandleOffset(r[0])+this._getHalfDragHandleSize();
if(q){this._updateRelativeLiveDragHandlePosition(l);
this._updateRelativeLiveDragHandlePosition(i);
}}else{if(q){l.style[p]=this._calculateDragHandleOffset(o)+"px";
i.style[p]=this._calculateDragHandleOffset(n)+"px";
}}}else{this.updateClientState();
}this._cachedSliderBounds=null;
this._cachedRangeSize=null;
this._inSlidingMode=false;
this.raiseEvent("slideRangeEnd");
if(this._autoPostBack&&r[0]!=this._value&&r[1]!=this._selectionEnd){this._raiseValueChangedServerEvent();
}},onDrag:function(j){var l=j.element;
if(l===this._selectedRegionElement){return this._onDragRange(j);
}var m=this._cachedDragHandleSize;
var x=this._cachedSliderBounds;
if(x.width<1||x.height<1){return false;
}var w=b.ResizeExtender.containsBounds(x,new Telerik.Web.UI.Bounds(j.x,j.y,m.width,m.height));
if(!w){if(j.x<=x.x){j.x=x.x;
}else{if(x.x+x.width<=j.x+m.width){j.x=x.x+x.width-m.width;
}}if(j.y<=x.y){j.y=x.y;
}else{if(x.y+x.height<=j.y+m.height){j.y=x.y+x.height-m.height;
}}w=true;
}var z=this._updateSelectionStart(null,l);
var r=this._calcValue(null,null,j,z);
var s=this._calculateDragHandleOffset(r);
var v=this._getPointProperty();
j[v]=s;
var o=this._liveDrag;
if(o&&this._getActiveDragHandleValue(z)!=r){var n=this._isDirectionReversed;
var u=this._value;
var t=this._selectionEnd;
var y=z&&((r>t&&!n)||(r<t&&n));
y=y||(!z&&((r<u&&!n)||(r>u&&n)));
var q=y&&this._isSelectionRangeEnabled&&(b.SliderThumbsInteractionMode.Push==this._thumbsInteractionMode);
var k=q&&this._setActiveDragHandleValue(r,!z,false,true);
if(!k){k=this._setActiveDragHandleValue(r,z,false,true);
}if(k){if(q){this._setActiveDragHandleValue((z?u:t),z,true,true);
}w=false;
}else{if(q){var p=this._getLocationProperty();
var i=z?this._endDragHandleElement:this._dragHandleElement;
i.style[p]=s+"px";
if(!z){this._selectedRegionElement.style[p]=s+"px";
}}this._updateSelectedRegion(l,s);
}}else{if(!o&&this._liveDragValue!=r){this._liveDragValue=r;
}else{w=false;
}}this.raiseEvent("slide");
return w;
},_onDragRange:function(i){var C=this._cachedRangeSize;
var G=this._cachedSliderBounds;
if(G.width<1||G.height<1){return false;
}var n=(this._children&&this._children.get_count()>0&&(this._itemType==b.SliderItemType.Item));
var H=this._smallChange;
var t=this._minimumValue+(n?H:0);
var s=this._maximumValue-(n?H:0);
var m=this._isHorizontal;
var I=this._valuesOnSlideStart;
var A=(I[1]-I[0]);
var x=null;
var D=b.ResizeExtender.containsBounds(G,new Telerik.Web.UI.Bounds(i.x,i.y,C.width,C.height));
if(!D){var l=this._isDirectionReversed;
var o=l?s:t;
var E=!l?s:t;
if(i.x<=G.x){i.x=G.x;
if(m){x={start:o,end:(o+A)};
}}else{if(G.x+G.width<=i.x+C.width){i.x=G.x+G.width-C.width;
if(m){x={start:(E-A),end:E};
}}}if(i.y<=G.y){i.y=G.y;
if(!m){x={start:o,end:(o+A)};
}}else{if(G.y+G.height<=i.y+C.height){i.y=G.y+G.height-C.height;
if(!m){x={start:(E-A),end:E};
}}}D=true;
}var B=this._getPointProperty();
var k=this._getHalfDragHandleSize();
if(!x){var w={};
w[B]=i[B]-k;
var v=this._calcValue(null,null,w,true);
v=Math.min(Math.max(v,t),s);
var u=v+A;
u=Math.max(Math.min(u,s),t);
v=u-A;
x={start:v,end:u};
}var y=this._calculateDragHandleOffset(x.start);
i[B]=y+k;
var p=this._liveDrag;
var q=this._liveDragValue;
var z={start:(p?this._value:q),end:(p?this._selectionEnd:(q+A))};
if(x.start!=z.start&&x.end!=z.end){var F=this._showDragHandle;
var r=this._getLocationProperty();
if(p){var j=this._setActiveDragHandleValue(x.end,false,false,true,true);
if(!j){j=this._setActiveDragHandleValue(x.start,true,false,true,true);
}if(j){this._setActiveDragHandleValue(z.end,false,true,true,true);
D=false;
}else{if(F){this._dragHandleElement.style[r]=y+"px";
this._endDragHandleElement.style[r]=this._calculateDragHandleOffset(x.end)+"px";
}}}else{this._liveDragValue=x.start;
if(F){this._liveDragHandleElement.style[r]=y+"px";
this._liveDragEndHandleElement.style[r]=this._calculateDragHandleOffset(x.end)+"px";
}}}else{D=false;
}this.raiseEvent("slideRange");
return D;
},_playAnimation:function(o,u,s){if(this._animationEnded==false){this._handleInSlidingMode=this._animatedHandle;
return;
}this._animationEnded=false;
var t=this;
var q=function(){t._setActiveDragHandleValue(o,u,true,false,false,s);
t._animationEnded=true;
};
var n=this._isHorizontal;
var j=this._animationDuration;
var p=this._calculateDragHandleOffset(o);
var k=this._getSelectionAnimationEndBounds(p,u);
var r=n?{width:k.width+"px",left:k.x+"px"}:{height:k.height+"px",top:k.y+"px"};
a(this._selectedRegionElement).stopTransition().transition(r,j,null,q);
if(this._showDragHandle){var m=this._animatedHandle=u?this._dragHandleElement:this._endDragHandleElement;
var l=n?{left:p+"px"}:{top:p+"px"};
var i=Function.createDelegate(this,this._onDragHandleAnimationEnded);
a(m).stopTransition().transition(l,j,null,i);
}},_getSelectionAnimationEndBounds:function(l,q){var n=this._getSelectedRegionBounds();
var i=Math.floor(l+this._getHalfDragHandleSize());
var o=this._getSizeProperty();
var k=this._getPointProperty();
if(this._isSelectionRangeEnabled){var p=n[k];
var j=p+n[o];
if(q){n[k]=i;
p=i;
}else{j=i;
}i=j-p;
}else{if(!isNaN(this._selectedRegionStartValue)){var m=this._calculateSelectedRegionBySelectionStart(i);
n[k]=m.start;
i=m.size;
}else{if(this._isDirectionReversed){n[k]=i;
i=this._getTrackBounds().width-i;
}}}i=(i<0)?0:i;
n[o]=i;
return n;
},_onDragHandleAnimationEnded:function(){this._updateRelativeLiveDragHandlePosition(this._handleInSlidingMode);
},_ensureChildControls:function(){},_createChildControls:function(){if(this._itemsUICreated){return;
}if(!this._children){this._children=new b.RadSliderItemCollection(this);
}if(!this._wrapperElement){return;
}var i=this._itemData;
if(!i||i.length==0){if(this._itemType==b.SliderItemType.Tick){this._calculateTickSize();
var k=this._largeChange;
if(this._largeChange>0){this._calculateTickSize(true);
}if(this._smallTickSize>0&&((this._largeTickSize>0&&k>0)||k<=0)){var j=this._createItemDataForTicks();
if(!j||j.length==0){return;
}this._createChildControlsUI(j);
}}}else{this._createChildControlsUI(i);
}},_createChildControlsUI:function(p){if(this._itemsUICreated){return;
}this._itemsUICreated=true;
var t=this.get_childListElement();
var q=this._children;
var n=this._isDirectionReversed;
var j=$telerik.getChildrenByTagName(t,"li");
var k=j.length;
var r=p.length;
var u=k!=r;
if(u){t.innerHTML="";
}this._childControlsCreated=u;
for(var m=0,s=p.length;
m<s;
m++){var o=new b.RadSliderItem();
var l=p[n?(r-1-m):m];
if(u){o._loadFromDictionary(l);
}else{o._initialize(l,j[m]);
}q.add(o);
}this._setItemsSize();
if(this._itemType==b.SliderItemType.Item){this._updateSelectedItemsStatus();
}this._childControlsCreated=true;
a.raiseControlEvent(this,"itemsCreated",{});
},_createChildListElement:function(){var i=document.createElement("ul");
i.className="rslItemsWrapper";
i.unselectable="on";
if(!this._showDecreaseHandle){i.style[this._getLocationProperty()]="0px";
}var j=this._trackElement;
j.parentNode.insertBefore(i,j);
$telerik.addMobileHandler(this,i,"mousedown",this._onTrackMouseDown);
this._listElement=i;
return i;
},_logInserted:function(i){},_clearSelection:function(){var k=this._children;
for(var j=0,l=k.get_count();
j<l;
j++){k.getItem(j)._updatedSelectedView(false);
}},_getItemOffset:function(q,t,i){var u=t;
if(!u){u=this._getUlSize()[this._getSizeProperty()];
}var l=this._children.get_count();
if(l<2){return{startPoint:0,endPoint:u};
}var m=0;
if(this._itemType==b.SliderItemType.Tick){var p=(this._getDragHandleBounds().width/2);
var j=p+Math.floor((u-2*p)/(2*(l-1)));
var r=j;
m=j;
if(this._isDirectionReversed){m+=i;
}else{r+=i;
}if(q==0){return{startPoint:0,endPoint:m};
}else{if(q==(l-1)){return{startPoint:(u-r),endPoint:u};
}}u-=(m+r);
l-=2;
q-=1;
if(u<0||l<=0){return{startPoint:0,endPoint:u};
}}var o=q/l;
var n=(q+1)/l;
var s=parseInt((o*u),10)+m;
var k=parseInt((n*u),10)+m;
return{startPoint:s,endPoint:k};
},_checkHitInItem:function(i,k){var j=this._getItemOffset(i);
if(k<j.startPoint){if(i<=0){return null;
}return this._checkHitInItem(i-1,k);
}else{if(k>j.endPoint){if(i>=this._children.get_count()-1){return null;
}return this._checkHitInItem(i+1,k);
}}return i;
},_getItemFromValue:function(l){if(this._itemType==b.SliderItemType.Item){var j=this.get_items();
var i=this._getIndexFromValue(l);
if(j&&j[i]){return j[i];
}}var k=this._calculateDragHandleOffset(l)+this._firstValueOffset;
return this._getItemFromOffset(k);
},_getItemFromOffset:function(m){var j=this._children;
var k=j.get_count();
var l=this._getItemSize(0)[this._getSizeProperty()];
if(l>0){var i=Math.floor(m/l);
i=this._checkHitInItem(i,m);
if(i>=k){i=k-1;
}if(i>=0){return j.getItem(i);
}}return null;
},_updateSelectedItemsStatus:function(){var i=this._children;
if(i.get_count()>0){this._clearSelection();
var k=this._getItemFromValue(this._value);
if(k){k._updatedSelectedView(true);
}if(this._isSelectionRangeEnabled){var j=this._getItemFromValue(this._selectionEnd);
if(j){j._updatedSelectedView(true);
}}}},_getUlSize:function(){var m=this._trackElement;
var n=$telerik.getBorderBox(m);
var r=$telerik.getSize(m);
r.width-=n.horizontal;
r.height-=n.vertical;
var t=r;
var i=this._isHorizontal;
var u=i?this._height:this._width;
if(!/px$/i.test(u)){u=$telerik.getComputedStyle(this.get_element(),i?"height":"width");
}u=parseInt(u,10);
var p=this._trackPosition;
if(p!=b.SliderTrackPosition.Center){u-=r[i?"height":"width"];
var j=p==b.SliderTrackPosition.TopLeft;
var l=i?(j?"top":"bottom"):(j?"left":"right");
var q=parseInt(($telerik.getCurrentStyle(m,l)),10);
if(!isNaN(q)){u-=q;
}var k=i?(j?"marginTop":"marginBottom"):(j?"marginLeft":"marginRight");
var o=parseInt(($telerik.getCurrentStyle(m,k)),10);
if(!isNaN(o)){u-=o;
}var s=parseInt(($telerik.getCurrentStyle(this._listElement,k)),10);
if(!isNaN(s)){u-=s;
}}if(u>=0){t[i?"height":"width"]=u;
}return t;
},_getItemSize:function(j,n,i){var o=n;
if(!o){o=this._getUlSize();
}var l={width:o.width,height:o.height};
var m=this._getSizeProperty();
var k=this._getItemOffset(j,o[m],i);
l[m]=k.endPoint-k.startPoint;
return l;
},_getAsymmetricAddOn:function(s){var i=0;
if(b.SliderItemType.Tick==this._itemType){var l=this._isDirectionReversed;
var p=this._maximumValue;
var q=this._minimumValue;
var n=this._children;
var o=l?0:(n.get_count()-1);
var m=n.getItem(o).get_isSmallTick();
var r=f.remainder((p-q),(m?this._smallChange:this._largeChange),this._precision);
if(r!=0){var j=l?(q+r):(p-r);
var k=this._calculateDragHandleOffset(j);
i=s-k-this._getDragHandleBounds().width;
}}return i;
},_setItemsSize:function(){if(!this._itemsUICreated){return;
}var r=this._children;
var t=r.get_count();
if(t==0){return;
}var l=(this._itemType==b.SliderItemType.Tick);
var p=this._isHorizontal;
var v=this._getSizeProperty();
var y=this._getUlSize();
var j=this._getAsymmetricAddOn(y[p?"width":"height"]);
var k={lastItemSize:0,asymmetricAddOn:j};
var s=0;
for(var n=0;
n<t;
n++){var q=r.getItem(n).get_element();
s=this._getItemSize(n,y,j);
$telerik.setSize(q,s);
if(p&&this._trackPosition==b.SliderTrackPosition.BottomRight){var o=q.getElementsByTagName("span")[0];
if(o){$telerik.setSize(o,s);
}}if(n==t-1){k.lastItemSize=s[v];
}else{if(l&&(n>0)){var x=q.getElementsByTagName("SPAN");
var w=Math.max(s[v],12)+"px";
for(var m=0,u=x.length;
m<u;
m++){if(!p){x[m].style.lineHeight=w;
}else{x[m].style.lineHeight="";
}}}}}this._setEndTicksBackgroundPosition(k);
},get_childListElement:function(){var i=this._listElement;
if(!i){i=this._createChildListElement();
}return i;
},get_selectedItem:function(){var i=this.get_selectedItems();
if(i.length>0){return i[0];
}return null;
},get_selectedItems:function(){if(this._itemType!=b.SliderItemType.Item){return[];
}var l=this._children;
var i=l.get_count();
var k=this._isDirectionReversed;
var n=k?(i-1-this.get_selectionStart()):this.get_selectionStart();
var m=[l.getItem(n)];
if(this._isSelectionRangeEnabled){var j=k?(i-1-this.get_selectionEnd()):this.get_selectionEnd();
Array.add(m,l.getItem(j));
}return m;
},get_selectedValue:function(){var i=this.get_selectedItem();
if(i){return i.get_value();
}return"";
},_calculateDragHandleOffset:function(o){var n=this._minimumValue;
var m=this._maximumValue;
var q=this._getTrackBounds();
var j=this._firstValueDragHandlePosition;
if(j==0){q.width=(q.width-this._getDragHandleBounds().width);
}var i=m-n;
var k=(o-n)/i;
if(this._isDirectionReversed){k=1-k;
o=m+n-o;
}var l=parseInt((k*(q.width)),10);
var p=(o==n)?j:(o==m)?(q.width+j):l+j;
return p;
},_getBoundsInternal:function(k,l){var j=$telerik.getBounds(k);
if(l){var i=$telerik.getBorderBox(k);
j.width-=i.horizontal;
j.height-=i.vertical;
j.x+=i.left;
j.y+=i.top;
}if(this._orientation==b.Orientation.Vertical){j={x:j.y,y:j.x,height:j.width,width:j.height};
}return j;
},_getHalfDragHandleSize:function(){return(this._getDragHandleBounds().width/2);
},_getTrackBounds:function(){return this._getBoundsInternal(this._trackElement,true);
},_getSelectedRegionBounds:function(){var j=$telerik.getContentSize(this._selectedRegionElement);
j.y=0;
j.x=0;
var i=this._isSelectionRangeEnabled;
if(i||(!i&&this._isDirectionReversed)){var k=this._getElementLocation(this._selectedRegionElement);
j[this._getPointProperty()]=k;
}return j;
},_getSelectedRegionPoints:function(){var j=this._getSelectedRegionBounds();
var k=j[this._getPointProperty()];
var i=k+j[this._getSizeProperty()];
return{startPoint:k,endPoint:i};
},_getDragHandleBounds:function(j){if(!this._showDragHandle){return{x:0,y:0,height:0,width:0};
}var i=j;
if(!i){i=this._dragHandleElement;
if(this._isSelectionRangeEnabled&&this._handleInSlidingMode){i=this._handleInSlidingMode;
}}return this._getBoundsInternal(i);
},_getDecreaseHandleBounds:function(){return this._getBoundsInternal(this._decreaseHandleElement);
},_getIncreaseHandleBounds:function(){return this._getBoundsInternal(this._increaseHandleElement);
},_getTrackMargin:function(){var k=this._trackElement;
var j=$telerik.getMarginBox(k);
var i=(this._orientation==b.Orientation.Horizontal);
return i?j.horizontal:j.vertical;
},_getLocationProperty:function(){if(!this._locationProperty){this._locationProperty=this._isHorizontal?"left":"top";
}return this._locationProperty;
},_updateLocationProperty:function(){this._locationProperty=this._isHorizontal?"left":"top";
},_getSizeProperty:function(){if(!this._sizeProperty){this._sizeProperty=this._isHorizontal?"width":"height";
}return this._sizeProperty;
},_updateSizeProperty:function(){this._sizeProperty=this._isHorizontal?"width":"height";
},_getPointProperty:function(){if(!this._pointProperty){this._pointProperty=this._isHorizontal?"x":"y";
}return this._pointProperty;
},_updatePointProperty:function(){this._pointProperty=this._isHorizontal?"x":"y";
},_doSmallStep:function(j){var m=this._smallChange;
var k=this._isDirectionReversed;
if((!j&&!k)||(j&&k)){m*=-1;
}var i=true;
if(this._isSelectionRangeEnabled&&j){i=false;
}var l=this._getActiveDragHandleValue(i)+m;
l=this._calcValue(l,null,null,i);
this._setHandlePosition(l,null,i,null,true);
},_calcValue:function(w,r,l,v){var i;
var q=this._minimumValue;
var p=this._maximumValue;
var j=v?this._dragHandleElement:this._endDragHandleElement;
var x;
if(w!=null){if(!Number.isInstanceOfType(w)){try{w=parseFloat(w);
}catch(m){w=Number.NaN;
}}if(isNaN(w)){w=q;
}i=(w<q)?q:(w>p)?p:w;
}else{var u=this._getTrackBounds();
var k=this._getDragHandleBounds(j);
if(l){k.x=(l[this._getPointProperty()])+u.x;
}var n=this._firstValueOffset;
x=(r!=null)?(r-n):(k.x+Math.floor(k.width/2)-u.x-n);
if(this._firstValueDragHandlePosition==0){u.width=(u.width-k.width);
}var s=x/u.width;
if(this._isDirectionReversed){x=u.width-x;
s=1-s;
}i=(x==0)?q:(x==u.width)?p:q+s*(p-q);
}i=this._getNearestStepValue(i);
i=(i<q)?q:(i>p)?p:i;
if(this._children&&this._children.get_count()>0&&(this._itemType==b.SliderItemType.Item)){var t=this._smallChange;
var o=this._getItemFromOffset(x);
if(o){i=this._getValueFromIndex(o.get_index());
}else{if(i%2==0){if(i<this._getActiveDragHandleValue(v)){i-=t;
}else{i+=t;
}i=(i<q)?q+t:(i>p)?p-t:i;
}}}return f.parseDecimal(i,this._precision);
},_setHandlePosition:function(l,k,p,o,j,n){if(!o&&this.raise_valueChanging(l,p)){return;
}var i=k;
if(!i){i=this._handleInSlidingMode;
}if((this._animationDuration>0)&&j){this._playAnimation(l,p,n);
}else{var m=this._calculateDragHandleOffset(l);
if(this._showDragHandle&&i){i.style[this._getLocationProperty()]=m+"px";
this._updateRelativeLiveDragHandlePosition(i);
}this._setActiveDragHandleValue(l,p,true,false,false,n);
this._updateSelectedRegion(i,m,p);
}},_setHandlePositionKeyboard:function(t,s,l){var n=this._isDirectionReversed;
var u=this._dragHandleElement;
var j=this._endDragHandleElement;
var k=t?u:j;
var i=!t?u:j;
var o=this._isSelectionRangeEnabled;
var m=this._thumbsInteractionMode;
var p=o&&(b.SliderThumbsInteractionMode.Lock==m);
var v=o&&(b.SliderThumbsInteractionMode.Push==m);
var q=o?this.get_selectionEnd():this._maximumValue;
var r=o?this.get_selectionStart():this._minimumValue;
s=Math.max(Math.min(s,this._maximumValue),this._minimumValue);
if(l){if(o&&(t&&!n)||(!t&&n)){if(p&&s>q){s=q;
}if(v&&s>q){this._setHandlePosition(s,i,!t);
}}this._setHandlePosition(s,k,t);
}else{if(o&&(!t&&!n)||(t&&n)){if(p&&s<r){s=r;
}if(v&&s<r){this._setHandlePosition(s,i,!t);
}}this._setHandlePosition(s,k,t);
}},_getNearestStepValue:function(p){var k=this._minimumValue;
var j=this._maximumValue;
var l=j-k;
if(l==0){return p;
}if(p>=j){return j;
}if(p<=k){return k;
}p-=k;
var o=this._smallChange;
var m=p%o;
if(m==0){return(p+k);
}var i=o-m;
if(m<o/2){i=-1*m;
}var n=p+i+k;
return n;
},_getRelativeLiveDragHandle:function(i){if(this._liveDrag||!this._showDragHandle){return null;
}if(this._updateSelectionStart(null,i)){return this._liveDragHandleElement;
}return this._liveDragEndHandleElement;
},_updateRelativeLiveDragHandlePosition:function(i){if(this._liveDrag||!this._showDragHandle){return;
}if(i){var k=this._getRelativeLiveDragHandle(i);
if(k){var j=this._getLocationProperty();
k.style[j]=i.style[j];
}}else{if(this._dragHandleElement){this._updateRelativeLiveDragHandlePosition(this._dragHandleElement);
if(this._isSelectionRangeEnabled&&this._endDragHandleElement){this._updateRelativeLiveDragHandlePosition(this._endDragHandleElement);
}}}},_getNearestDragHandle:function(j){var i=this._dragHandleElement;
if(this._isSelectionRangeEnabled&&j){var k=this._getSelectedRegionPoints();
var l=k.endPoint;
if((Math.abs(j-k.startPoint)>Math.abs(j-l))||j>l){i=this._endDragHandleElement;
}}return i;
},_getElementLocation:function(i){var k=this._getLocationProperty();
var j=parseInt(i.style[k],10);
if(isNaN(j)){j=0;
}return j;
},_getActiveDragHandleValue:function(j){var i=j?this._dragHandleElement:this._endDragHandleElement;
if(!i&&this._showDragHandle){return this._minimumValue;
}var k=(j!=null)?j:this._updateSelectionStart(null,this._handleInSlidingMode);
return(k?this._value:this._selectionEnd);
},_setActiveDragHandleValue:function(l,s,o,q,r,p){var i=s?this._dragHandleElement:this._endDragHandleElement;
if(!i&&this._showDragHandle){return;
}var n=this._getActiveDragHandleValue(s);
if(!o&&this.raise_valueChanging(l,s)){return true;
}var j=this._isDirectionReversed;
var k=this._isSelectionRangeEnabled;
if(s){if(!r&&((l>this._selectionEnd&&k&&!j)||(l<this._selectionEnd&&k&&j))){this._value=this._selectionEnd;
var m=this._calculateDragHandleOffset(this._value);
this._selectedRegionElement.style[this._getLocationProperty()]=m+this._getHalfDragHandleSize()+"px";
this._switchDragHanldes();
this._selectionEnd=l;
}else{this._value=l;
}}else{if(!r&&((l<this._value&&k&&!j)||(l>this._value&&k&&j))){this._selectionEnd=this._value;
this._selectedRegionElement.style[this._getSizeProperty()]="0px";
this._switchDragHanldes();
this._value=l;
}else{this._selectionEnd=l;
}}if(this._itemType==b.SliderItemType.Item){this._updateSelectedItemsStatus();
}if(!q){this.updateClientState();
}if(l!=n){if(!p){this.raise_valueChanged(n,l);
}if(!this._inSlidingMode&&this._autoPostBack){this._raiseValueChangedServerEvent();
}}},_setNewValue:function(t,q,s,r){t=f.parseDecimal(t,this._precision);
if(isNaN(t)){var j=this._isSelectionRangeEnabled?(q?"SelectionStart":"SelectionEnd")+" should be of type decimal":"Value should be of type decimal";
throw Error(j);
}var m=this._minimumValue;
var l=this._maximumValue;
if(t<m){t=m;
}else{if(t>l){t=l;
}}if(!this._initializedInternal||!this._wrapperElement){if(this._initializedInternal){t=this._getNearestStepValue(t);
}this[q?"_value":"_selectionEnd"]=t;
this.updateClientState();
return;
}if(this._isSelectionRangeEnabled){var k=this._isDirectionReversed;
var p=this._value;
var o=this._selectionEnd;
if((t<p&&!q&&!k)||(t>p&&!q&&k)){q=true;
}else{if((t>o&&q&&!k)||(t<o&&q&&k)){q=false;
}}}var n=this._calcValue(t,null,null,q);
var i=this[q?"_dragHandleElement":"_endDragHandleElement"];
this._setHandlePosition(n,i,q,s,false,r);
},_getIndexFromValue:function(n){if(b.SliderItemType.Item!=this._itemType){return n;
}var l=0;
var k=this._children;
if(k){l=k.get_count();
}if(l==0){var j=this._itemData;
l=j?j.length:0;
}if(l>0){var i=this._minimumValue;
var m=l-1;
n=(n-this._smallChange)/2;
n=(n<i)?i:((n>m)?m:n);
}return n;
},_getValueFromIndex:function(j){if(b.SliderItemType.Item!=this._itemType){return j;
}var m=0;
var l=this._children;
if(l){m=l.get_count();
}if(m==0){var k=this._itemData;
m=k?k.length:0;
}if(m>0){var o=this._smallChange;
var i=this._minimumValue;
var n=m*2-o;
j=(2*j)+o;
j=(j<i)?i:((j>n)?n:j);
}return j;
},_switchDragHanldes:function(){if(!this._isSelectionRangeEnabled){return;
}var i=this._dragHandleElement;
this._dragHandleElement=this._endDragHandleElement;
this._endDragHandleElement=i;
if(!this._liveDrag){i=this._liveDragHandleElement;
this._liveDragHandleElement=this._liveDragEndHandleElement;
this._liveDragEndHandleElement=i;
}if(this._resizeExtender&&this._endResizeExtender){i=this._resizeExtender;
this._resizeExtender=this._endResizeExtender;
this._endResizeExtender=i;
}i=null;
},_updateSelectionStart:function(j,i){if(!this._isSelectionRangeEnabled){return true;
}var l=this._showDragHandle;
if(l&&i!=null){return(i.id==this._dragHandleElement.id);
}else{if(!l&&j!=null){var k=this._getSelectedRegionPoints();
return(Math.abs(j-k.startPoint)<Math.abs(j-k.endPoint));
}}return true;
},_isInIncreaseMode:function(k,j){var l=this._getSelectedRegionPoints();
var n=l.endPoint;
var m=this._isSelectionRangeEnabled;
var i=(!m&&(k<n))||(m&&(((k<n)&&!j)||((k<l.startPoint)&&j)));
if(this._isDirectionReversed){if(!m){i=k>l.startPoint;
}else{i=!i;
}}return i;
},_updateSelectedRegion:function(i,k,r){k+=this._getHalfDragHandleSize();
var o=k;
var m=this._selectedRegionElement;
var q=this._getSizeProperty();
var j=this._getLocationProperty();
if(this._isSelectionRangeEnabled){var n=this._getSelectedRegionBounds();
var p=n[this._getPointProperty()];
o=n[q];
if(r||this._updateSelectionStart(k,i)){m.style[j]=k+"px";
o=o+(p-Math.floor(k));
}else{o=(Math.floor(k)-p);
}}else{if(!isNaN(this._selectedRegionStartValue)){var l=this._calculateSelectedRegionBySelectionStart(k);
m.style[j]=l.start+"px";
o=l.size;
}else{if(this._isDirectionReversed){m.style[j]=k+"px";
o=this._getTrackBounds().width-Math.floor(k);
}}}if(!isNaN(o)&&o>=0){m.style[q]=o+"px";
}else{m.style[q]="";
}},_calculateSelectedRegionBySelectionStart:function(j){var i=this._getSelectedRegionStartOffset(j);
var l=Math.min(j,i);
var k=Math.abs(j-i);
return{start:l,size:k};
},_getSelectedRegionStartOffset:function(){return this._calculateDragHandleOffset(this._selectedRegionStartValue)+this._getHalfDragHandleSize();
},_setEndTicksBackgroundPosition:function(j){if(this._itemType==b.SliderItemType.Tick){var u=this._showDragHandle;
var r=this._largeTickSize;
var v=this._smallTickSize;
var m=Math.ceil(this._getHalfDragHandleSize());
var n=Math.floor(r/2);
var o=Math.floor(v/2);
var q=this._children;
var k=q.getItem(0).get_element();
var s=q.getItem(q.get_count()-1).get_element();
var p=this._isDirectionReversed;
var i=j.asymmetricAddOn;
var l=p?i:0;
this._setBackgroundPosition(k,(l+(u?(m-n):0)),(l+(u?(m-o):0)));
var t=Math.ceil(j.lastItemSize)-m-(!p?i:0);
this._setBackgroundPosition(s,(t-(u?n:r)),(t-(u?o:v)));
}},_setBackgroundPosition:function(m,q,t){var p=(m.className.indexOf("rslLarge")>-1);
q=(q<0)?0:q;
t=(t<0)?0:t;
var k;
var l;
if(this._isHorizontal){k=(p?q:t)+"px";
l=this._getImageBackgroundPosition();
}else{l=(p?q:t)+"px";
k=this._getImageBackgroundPosition();
}m.style.backgroundPosition=k+" "+l;
if(p){var o=this._isHorizontal;
var s=this._getSizeProperty();
var j=(s=="width")?"height":"width";
var v=m.getElementsByTagName("SPAN");
var w=Math.max((2*q+this._largeTickSize),12)+"px";
for(var n=0,r=v.length;
n<r;
n++){var u=v[n];
u.style[j]="";
u.style[s]=w;
if(!o){u.style.lineHeight=w;
}else{u.style.lineHeight="";
}}}},_getImageBackgroundPosition:function(){var k=this._trackPosition;
var j=this._isHorizontal;
var i="center";
if(k==b.SliderTrackPosition.TopLeft){i=j?"top":"left";
}else{if(k==b.SliderTrackPosition.BottomRight){i=j?"bottom":"right";
}}return i;
},_calculateTickSize:function(j){var i=document.createElement("div");
i.className=j?"rslLargeTick":"rslSmallTick";
i.style.position="absolute";
i.style.top="-9999px";
this._wrapperElement.appendChild(i);
var k=this._isHorizontal?i.offsetWidth:i.offsetHeight;
i.parentNode.removeChild(i);
if(j){this._largeTickSize=k;
}else{this._smallTickSize=k;
}},_checkRenderTicks:function(){var j=this._largeChange;
var o=this._smallChange;
var l=(this._maximumValue-this._minimumValue)/o;
var i=(this._getTrackBounds().width)/l;
var k=Math.floor(i*(j/o));
i=Math.floor(i);
var m=((j>0)&&(k>=this._largeTickSize));
var n=(i>=this._smallTickSize&&j!=o);
return{renderLargeTicks:m,renderSmallTicks:n};
},_createItemDataForTicks:function(){var l=[];
var n=this._largeChange;
var u=this._smallChange;
var o=this._maximumValue;
var p=this._minimumValue;
var t=this._checkRenderTicks();
var r=this._renderLargeTicks=t.renderLargeTicks;
var s=this._renderSmallTicks=t.renderSmallTicks;
if(!r){n=Math.abs(p)+o+u;
}var q=this._precision;
for(var k=p;
k<=o;
k=f.add(k,n,q)){if(r){l[l.length]={text:k,value:k,tooltip:k,isLargeTick:true};
}if(s){var m=f.add(k,(r?u:0),q);
var v=(r&&((k+n)<=o))?f.add(k,n,q):f.add(o,f.divide(1,q,q),q);
for(;
m<v;
m=f.add(m,u,q)){l[l.length]={text:m,value:m,tooltip:m,isSmallTick:true};
}}}this._itemData=l;
return l;
},_clearSizePosition:function(i){if(!i){return;
}i.style.width="";
i.style.height="";
i.style.top="";
i.style.left="";
},_raiseValueChangedServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},_onMouseUp:function(i){this._trackMouseDownDone=true;
this._incdecreaseMouseDownDone=true;
},_onTrackMouseDown:function(k){if(!this._enabled||(!$telerik.isTouchDevice&&k.button!==0)){return;
}var x=k.target;
var n=(x==this._selectedRegionElement);
var o=(x==this._trackElement);
var p=this._listElement;
var y=x.parentNode;
var m=(p)?((y&&y==p)||(y.parentNode&&y.parentNode==p)):false;
if(!o&&!n&&!m){return;
}var A=this._getTrackBounds();
var z=$telerik.getTouchEventLocation(k);
var s=$telerik.isTouchDevice?{left:z.x,top:z.y}:$telerik.getDocumentRelativeCursorPosition(k);
var u=((this._isHorizontal)?s.left:s.top)-A.x;
var r=0;
if(this._firstValueDragHandlePosition==0){r=this._firstValueOffset;
}var q=A.width-r;
u=(u<r)?r:(u>q)?q:u;
var j=this._handleInSlidingMode=this._getNearestDragHandle(u);
var B=this._updateSelectionStart(u,j);
var t=this._calcValue(null,u,null,B);
if(this._largeChange==0){this._setHandlePosition(t,j,B,null,true);
}else{this._trackMouseDownDone=false;
var l=this._isInIncreaseMode(u,B);
var w=(this._children.get_count()>0&&(this._itemType==b.SliderItemType.Item));
var v=this;
var i=function(D){if(v._disposed){return;
}var F=v._isInIncreaseMode(u,B);
if(v._trackMouseDownDone||F!=l){clearTimeout(v._mDownInterval);
return;
}var C=v._largeChange;
if(w){C*=2;
}if(l){C*=-1;
}var E=v._getActiveDragHandleValue(B)+C;
E=v._calcValue(E,null,null,B);
if((!l&&(t<E))||(l&&(t>E))){E=t;
}v._setHandlePosition(E,j,B,null,true);
v._mDownInterval=setTimeout(i,(D)?D:100);
};
i(300);
}},_onMouseWheel:function(j){if(!this._enabled){return;
}var n=this._getTrackBounds();
if(n.width<1||n.height<1){return;
}var i=(j.wheelDelta)?j.wheelDelta:j.detail;
if($telerik.isIE){i*=-1;
}var l=this._value;
var m=this._smallChange;
var k=l+((i>0)?m:(-1)*m);
k=this._calcValue(k,null,null,true);
this._setHandlePosition(k,this._dragHandleElement,true,null,true);
return $telerik.cancelRawEvent(j);
},_onDecreaseMouseDown:function(i){this._onIncreaseDecreaseMDown(i,false);
},_onIncreaseMouseDown:function(i){this._onIncreaseDecreaseMDown(i,true);
},_onIncreaseDecreaseMDown:function(j,l){if(!this._enabled){return;
}if(j.button!=0){return;
}this._handleInSlidingMode=this._dragHandleElement;
var k=true;
if(this._isSelectionRangeEnabled&&l){this._handleInSlidingMode=this._endDragHandleElement;
k=false;
}this._incdecreaseMouseDownDone=false;
this._inSlidingMode=true;
this._valueOnSlideStart=this._getActiveDragHandleValue(k);
var m=this;
function i(n){if(m._disposed){return;
}if(m._incdecreaseMouseDownDone){m._inSlidingMode=false;
clearTimeout(m._increaseMDownInterval);
if(m._valueOnSlideStart!=m._getActiveDragHandleValue(k)&&m._autoPostBack){m._raiseValueChangedServerEvent();
}return;
}m._doSmallStep(l);
m._increaseMDownInterval=setTimeout(i,(n)?n:50);
}i(300);
},_onKeyDown:function(k){var q=true;
var n=this._isDirectionReversed;
var i=this.get_value();
var j=this._dragHandleElement;
var r=false;
var l=this._endDragHandleElement;
if(l){if(l.getAttribute("hasFocus")){q=false;
i=n?this.get_selectionStart():this.get_selectionEnd();
j=l;
}else{i=n?this.get_selectionEnd():this.get_selectionStart();
}}if(!j||!j.getAttribute("hasFocus")){return;
}var p=null;
var m=true;
var o=k.keyCode?k.keyCode:k.rawEvent.keyCode;
switch(o){case Sys.UI.Key.up:case Sys.UI.Key.right:p=i+this._smallChange;
m=true;
r=true;
break;
case Sys.UI.Key.down:case Sys.UI.Key.left:p=i-this._smallChange;
m=false;
r=true;
break;
case Sys.UI.Key.home:p=this._minimumValue;
m=false;
break;
case Sys.UI.Key.end:p=this._maximumValue;
m=true;
break;
case Sys.UI.Key.pageUp:p=i+this._largeChange;
m=true;
break;
case Sys.UI.Key.pageDown:p=i-this._largeChange;
m=false;
break;
default:return true;
}if(this._itemType==b.SliderItemType.Item&&r){var s=m?this._smallChange:-this._smallChange;
p=this._getActiveDragHandleValue(q)+s;
p=this._calcValue(p,null,null,q);
}this._setHandlePositionKeyboard(q,p,m);
this._clearSizePosition(this._selectedRegionElement);
this._refreshLayout();
$telerik.cancelRawEvent(k);
return false;
},_applyAccessKey:function(){var i=this._accessKey;
if(i){if(!($telerik.isChrome||$telerik.isSafari||d.edge)){this._dragHandleElement.setAttribute("accessKey",i);
}else{var k=document.createElement("div");
k.style.width="0px";
k.style.height="0px";
k.style.overflow="hidden";
this.get_element().appendChild(k);
var j=this._accessKeyTextbox=document.createElement("input");
j.setAttribute("type","text");
var l=this.get_id()+"SliderAccessKey";
j.setAttribute("name",l);
j.setAttribute("id",l);
j.setAttribute("accessKey",i);
k.appendChild(j);
$addHandlers(j,{focus:function(){this._dragHandleElement.focus();
}},this);
}}},_handleFocus:function(i){if(this.get_enabled()){var j=i.target?i.target:i.srcElement;
if(j){j.setAttribute("hasFocus","true");
}}},_handleBlur:function(i){var j=i.target?i.target:i.srcElement;
if(!j||($telerik.isOpera&&a(":focus").filter(j).size()>0)){return;
}j.removeAttribute("hasFocus");
},_getValuesBeforeAnimation:function(){return{selectionStart:this._valueBeforeAnimation,selectionEnd:this._selectionEndBeforeAnimation};
},add_loaded:function(i){this.add_load(i);
},remove_loaded:function(i){this.remove_load(i);
},add_valueChange:function(i){this.add_valueChanged(i);
},remove_valueChange:function(i){this.remove_valueChanged(i);
},raise_valueChange:function(j,i){this.raise_valueChanged(j,i);
},raise_valueChanged:function(j,i){j=this._getIndexFromValue(j);
i=this._getIndexFromValue(i);
a.raiseControlEvent(this,"valueChanged",{oldValue:j,newValue:i});
},add_beforeValueChange:function(i){this.add_valueChanging(i);
},remove_beforeValueChange:function(i){this.remove_valueChanging(i);
},raise_beforeValueChange:function(i,j){return this.raise_valueChanging(i,j);
},raise_valueChanging:function(j,l){var k=this._getActiveDragHandleValue(l);
k=this._getIndexFromValue(k);
j=this._getIndexFromValue(j);
if(this._isSelectionRangeEnabled){this._valueBeforeAnimation=l?j:this._value;
this._selectionEndBeforeAnimation=l?this._selectionEnd:j;
}else{this._valueBeforeAnimation=j;
}var i=a.raiseCancellableControlEvent(this,"valueChanging",{oldValue:k,newValue:j});
if(i){return true;
}return false;
},_windowResizeHandler:function(){var i=this;
i._resizeTimeout=window.setTimeout(function(){window.clearTimeout(i._resizeTimeout);
i.repaint();
},200);
},get_activeHandle:function(){if(!this._liveDrag){return this._getRelativeLiveDragHandle(this._handleInSlidingMode);
}return this._handleInSlidingMode;
},get_dragHandles:function(){return[this._dragHandleElement,this._endDragHandleElement];
},get_value:function(){var i=this._value;
if(this._isDirectionReversed&&this._isSelectionRangeEnabled){i=this._selectionEnd;
}return this._getIndexFromValue(i);
},set_value:function(i){if(this._initializedInternal&&this._wrapperElement){i=this._getValueFromIndex(i);
}this._setNewValue(i,true);
},get_selectionStart:function(){return this.get_value();
},set_selectionStart:function(i){if(this._isSelectionRangeEnabled){this.set_value(i);
}},get_selectionEnd:function(){var i=this._selectionEnd;
if(this._isDirectionReversed&&this._isSelectionRangeEnabled){i=this._value;
}return this._getIndexFromValue(i);
},set_selectionEnd:function(i){if(this._initializedInternal&&this._wrapperElement){i=this._getValueFromIndex(i);
}this._setNewValue(i,false);
},get_isSelectionRangeEnabled:function(){return this._isSelectionRangeEnabled;
},set_isSelectionRangeEnabled:function(l){if(this._isSelectionRangeEnabled!=l){this._isSelectionRangeEnabled=l;
if(this._initializedInternal&&this._wrapperElement){this._setShowEndDragHandle();
this._setTrackMouseWheel();
this._setEnableDragRange();
var k;
if(this._isSelectionRangeEnabled){l=this._value;
var j=this._selectionEnd;
var i=this._isDirectionReversed;
if((l<j&&i)||(l>j&&!i)){this._switchDragHanldes();
k=this._value;
this._value=j;
this._selectionEnd=k;
}}else{if(this._isDirectionReversed){k=this._value;
this._value=this._selectionEnd;
this._selectionEnd=k;
}}this._clearSizePosition(this._selectedRegionElement);
this._refreshLayout();
}this.updateClientState();
}},get_enableDragRange:function(){return this._enableDragRange;
},set_enableDragRange:function(i){if(this._enableDragRange!=i){this._enableDragRange=i;
if(this._initializedInternal&&this._wrapperElement){this._setEnableDragRange();
}this.updateClientState();
}},get_isDirectionReversed:function(){return this._isDirectionReversed;
},set_isDirectionReversed:function(j){if(this._isDirectionReversed!=j){this._isDirectionReversed=j;
if(this._initializedInternal&&this._wrapperElement){if(this._isSelectionRangeEnabled){var i=this._value;
this._value=this._selectionEnd;
this._selectionEnd=i;
}this.repaint(true);
}this.updateClientState();
}},get_liveDrag:function(){return this._liveDrag;
},set_liveDrag:function(i){if(this._liveDrag!=i){this._liveDrag=i;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_minimumValue:function(){return this._minimumValue;
},set_minimumValue:function(i){i=f.parseDecimal(i,this._precision);
if(isNaN(i)){return;
}if(this._minimumValue!=i){this._minimumValue=i;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_maximumValue:function(){return this._maximumValue;
},set_maximumValue:function(i){i=f.parseDecimal(i,this._precision);
if(isNaN(i)){return;
}if(this._maximumValue!=i){this._maximumValue=i;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_orientation:function(){return this._orientation;
},set_orientation:function(m){if(this._orientation!=m){this._orientation=m;
this._isHorizontal=(this._orientation==b.Orientation.Horizontal);
this._updateLocationProperty();
this._updateSizeProperty();
this._updatePointProperty();
if(this._initializedInternal&&this._wrapperElement){this._setOrientation();
this._clearSizePosition(this._selectedRegionElement);
this._clearSizePosition(this._dragHandleElement);
this._clearSizePosition(this._endDragHandleElement);
if(!this._liveDrag){this._clearSizePosition(this._liveDragHandleElement);
this._clearSizePosition(this._liveDragEndHandleElement);
}this._refreshLayout();
if(!this._showDecreaseHandle){var l=this._trackElement;
var j=this._listElement;
var k=this._getLocationProperty();
var i=(k=="top")?"left":"top";
if(l){l.style[i]="";
l.style[k]="0";
}if(j){j.style[i]="";
j.style[k]="0";
}}}this.updateClientState();
}},get_animationDuration:function(){return this._animationDuration;
},set_animationDuration:function(i){if(isNaN(parseInt(i,10))||i<0){throw Error.argumentOutOfRange("value",i,"AnimationDuration should be positive integer");
}if(this._animationDuration!=i){this._animationDuration=i;
this.updateClientState();
}},get_length:function(){var k=this,i=k.get_element(),j;
if(k._renderMode===b.RenderMode.Lite){j=parseInt(((this._isHorizontal)?i.offsetWidth:i.offsetHeight),10);
}else{j=parseInt(((this._isHorizontal)?this._width:this._height),10);
}if(isNaN(j)){j=200;
}return j;
},set_length:function(i){if(this._isHorizontal){this.set_width(i);
}else{this.set_height(i);
}},get_width:function(){return this._width;
},set_width:function(i){if(isNaN(parseInt(i,10))||i<1){throw Error.argumentOutOfRange("value",i,"Width should be an integer bigger than 1");
}if(this._width!=i){this._width=i;
if(this._initializedInternal&&this._wrapperElement){this._setWidth();
this._refreshLayout();
}this.updateClientState();
}},get_height:function(){return this._height;
},set_height:function(i){if(isNaN(parseInt(i,10))||i<1){throw Error.argumentOutOfRange("value",i,"Height should be an integer bigger than 1");
}if(this._height!=i){this._height=i;
if(this._initializedInternal&&this._wrapperElement){this._setHeight();
this._refreshLayout();
}this.updateClientState();
}},_setupHandlesRelatedCssClasses:function(){var n=this;
var j=n.get_element();
var m=n._showIncreaseHandle;
var l=n._showDecreaseHandle;
var i=Sys.UI.DomElement.addCssClass;
var k=Sys.UI.DomElement.removeCssClass;
if(n._renderMode===b.RenderMode.Lite){m?i(j,"rslIncreaseHandle"):k(j,"rslIncreaseHandle");
l?i(j,"rslDecreaseHandle"):k(j,"rslDecreaseHandle");
}},_fixLiteHorizontalWidth:function(){},get_showDecreaseHandle:function(){return this._showDecreaseHandle;
},set_showDecreaseHandle:function(i){if(this._showDecreaseHandle!=i){this._showDecreaseHandle=i;
if(this._initializedInternal&&this._wrapperElement){this._setShowHandle(true);
this._refreshLayout();
}this.updateClientState();
}},get_showIncreaseHandle:function(){return this._showIncreaseHandle;
},set_showIncreaseHandle:function(i){if(this._showIncreaseHandle!=i){this._showIncreaseHandle=i;
if(this._initializedInternal&&this._wrapperElement){this._setShowHandle(false);
this._refreshLayout();
}this.updateClientState();
}},get_showDragHandle:function(){return this._showDragHandle;
},set_showDragHandle:function(i){if(this._showDragHandle!=i){this._showDragHandle=i;
if(this._initializedInternal&&this._wrapperElement){this._setShowDragHandle();
this._setFirstValueOffset();
if(this._children.get_count()>0){this._refreshLayout();
}this._setValuesForSlider();
}this.updateClientState();
}},get_trackMouseWheel:function(){return this._trackMouseWheel;
},set_trackMouseWheel:function(i){if(this._trackMouseWheel!=i){this._trackMouseWheel=i;
if(this._initializedInternal&&this._wrapperElement){this._setTrackMouseWheel();
}this.updateClientState();
}},get_largeChange:function(){return this._largeChange;
},set_largeChange:function(i){i=f.parseDecimal(i,this._precision);
if(isNaN(i)||i<0){throw Error.argumentOutOfRange("value",i,"LargeChange should be positive decimal");
}if(this._largeChange!=i){this._largeChange=i;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_smallChange:function(){return this._smallChange;
},set_smallChange:function(i){i=f.parseDecimal(i,this._precision);
if(isNaN(i)||i<=0){throw Error.argumentOutOfRange("value",i,"SmallChange should be decimal bigger than 0");
}if(this._smallChange!=i){this._smallChange=i;
if(this._initializedInternal&&this._wrapperElement){this.repaint(true);
}this.updateClientState();
}},get_itemType:function(){return this._itemType;
},set_itemType:function(i){if(this._itemType!=i){this._itemType=i;
}},get_trackPosition:function(){return this._trackPosition;
},set_trackPosition:function(u){var t=this._trackPosition;
if(t!=u){this._trackPosition=u;
if(this._initializedInternal&&this._wrapperElement){this._setTrackPosition(t);
var l=(t==b.SliderTrackPosition.Center);
var k=(this._trackPosition==b.SliderTrackPosition.Center);
if((l||k)&&this._itemType==b.SliderItemType.Tick&&this._renderLargeTicks){var s=this._children;
var n=this._listElement;
var r=n.childNodes;
if($telerik.isIE){r=n.children;
}for(var j=0,m=r.length;
j<m;
j++){var q=r[j];
if(q.nodeType==1&&q.className.indexOf("rslLarge")>-1){var p=q.getElementsByTagName("SPAN"),o;
if(p.length>1){o=p[1];
if(k){o.style.display="";
}else{o.style.display="none";
}}else{if(k){o=document.createElement("span");
o.className="rslBRItemText";
o.innerHTML=s.getItem(j).get_value();
q.appendChild(o);
}}}}}this._refreshLayout();
}this.updateClientState();
}},get_thumbsInteractionMode:function(){return this._thumbsInteractionMode;
},set_thumbsInteractionMode:function(i){if(this._thumbsInteractionMode!=i){this._thumbsInteractionMode=i;
this.updateClientState();
}},get_visibleItems:function(){var n=this._children;
var j=n.get_count();
var l=this._isDirectionReversed;
var o=[];
for(var k=0;
k<j;
k++){var m=n.getItem(l?(j-1-k):k);
if(m.get_visible()){Array.add(o,m);
}}return o;
},get_items:function(){var o=[];
var j=this._getChildren();
if(j){var k=j.get_count();
var m=this._isDirectionReversed;
for(var l=0;
l<k;
l++){var n=j.getItem(m?(k-1-l):l);
Array.add(o,n);
}}return o;
},set_items:function(i){this._children=i;
},get_itemData:function(){return this._itemData;
},set_itemData:function(i){this._itemData=i;
},get_enabled:function(){return this._enabled;
},set_enabled:function(j){if(this._enabled!=j){this._enabled=j;
if(this._initializedInternal&&this._wrapperElement){this._setEnabled();
if(this._accessKeyTextbox){var i=this._accessKeyTextbox;
i.removeAttribute("disabled");
if(!j){i.setAttribute("disabled","disabled");
}}}}},get_dragText:function(){return this._dragText;
},set_dragText:function(k){var j=this._dragText;
if(j!=k){this._dragText=k;
var i=this._dragHandleElement;
if(i){i.title=k;
}i=this._endDragHandleElement;
if(i){i.title=k;
}this.updateClientState();
}},get_skin:function(){return this._skin;
},redraw:function(i){if($telerik.getInvisibleParent(this.get_element())){return;
}this._handleInSlidingMode=null;
if(i){if(this._wrapperElement){var j=this._wrapperElement;
j.parentNode.removeChild(j);
this._wrapperElement=null;
if(this._children){this._children.clear();
this._itemsUICreated=false;
if(this._itemType==b.SliderItemType.Tick){this._itemData=[];
}}this._listElement=null;
this._disposeSlider();
this._disposeHandlers();
}this._initializedInternal=false;
this._initializeSliderControl();
}else{if(!this._initializedInternal||!this._wrapperElement){this._initializeSliderControl();
}else{setTimeout(a.proxy(function(){this._refreshLayout();
},this),100);
}}},get_rippleZonesConfiguration:function(){return[{element:this.get_element(),rippleConfigurations:[{rippleType:b.MaterialRippleType.Icon,containerSelector:".rslHandle"}]}];
},saveClientState:function(){var k=["value","selectionStart","selectionEnd","isSelectionRangeEnabled","orientation","smallChange","largeChange","trackMouseWheel","showDragHandle","showDecreaseHandle","showIncreaseHandle","width","height","animationDuration","minimumValue","maximumValue","trackPosition","liveDrag","dragText","thumbsInteractionMode"];
var l={};
for(var j=0;
j<k.length;
j++){l[k[j]]=this["get_"+k[j]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(l);
}};
a.registerControlEvents(b.RadSlider,["slideStart","slide","slideEnd","valueChanged","valueChanging","load","itemsCreated","slideRangeStart","slideRange","slideRangeEnd","itemDataBinding","itemDataBound","dataBound"]);
b.RadSlider.registerClass("Telerik.Web.UI.RadSlider",b.ControlItemContainer);
var e=function(j,i){b[j]=function(){var k=Array.prototype.slice.call(arguments);
b[j].initializeBase(this,k);
};
b[j].registerClass("Telerik.Web.UI."+j,i);
};
b.SliderItemDataBindingEventArgs=function(i){b.SliderItemDataBindingEventArgs.initializeBase(this);
this._dataItem=i;
};
b.SliderItemDataBindingEventArgs.prototype={get_dataItem:function(){return this._dataItem;
}};
b.SliderItemDataBindingEventArgs.registerClass("Telerik.Web.UI.SliderItemDataBindingEventArgs",Sys.CancelEventArgs);
e("RadSliderItemDataBindingEventArgs",Telerik.Web.UI.SliderItemDataBindingEventArgs);
b.SliderItemDataBoundEventArgs=function(j,i){b.SliderItemDataBoundEventArgs.initializeBase(this);
this._sliderItem=j;
this._dataItem=i;
};
b.SliderItemDataBoundEventArgs.prototype={get_sliderItem:function(){return this._sliderItem;
},get_dataItem:function(){return this._dataItem;
}};
b.SliderItemDataBoundEventArgs.registerClass("Telerik.Web.UI.SliderItemDataBoundEventArgs",Sys.EventArgs);
e("RadSliderItemDataBoundEventArgs",Telerik.Web.UI.SliderItemDataBoundEventArgs);
})($telerik.$);
Type.registerNamespace("Telerik.Web.UI");
$telerik.toSliderItem=function(a){return a;
};
$telerik.findSliderItem=$find;
Telerik.Web.UI.RadSliderItem=function(){Telerik.Web.UI.RadSliderItem.initializeBase(this);
this._imageUrl=null;
this._imageElement=null;
};
Telerik.Web.UI.RadSliderItem.prototype={set_visible:function(a){var b=this.get_visible()!=a;
if(!b){return;
}Telerik.Web.UI.RadSliderItem.callBaseMethod(this,"set_visible",[a]);
if(a){this.get_element().style.display="";
}else{this.get_element().style.display="none";
}},_updatedSelectedView:function(a){if(this.get_slider()._itemType==Telerik.Web.UI.SliderItemType.Item){var b=this.get_element();
if(a){Sys.UI.DomElement.addCssClass(b,"rslItemSelected");
}else{Sys.UI.DomElement.removeCssClass(b,"rslItemSelected");
}}},get_selected:function(){var b=false;
var c=this.get_slider();
var a=this.get_index();
if(c.get_isSelectionRangeEnabled()){if(c.get_selectionStart()==a||c.get_selectionEnd()==a){b=true;
}}else{if(c.get_value()==a){b=true;
}}return b;
},set_cssClass:function(a){this._properties.setValue("cssClass",a);
},get_cssClass:function(){return this._properties.getValue("cssClass","");
},set_tooltip:function(a){this._properties.setValue("tooltip",a);
},get_tooltip:function(){return this._properties.getValue("tooltip","");
},set_isLargeTick:function(a){this._properties.setValue("isLargeTick",a);
},get_isLargeTick:function(){return this._properties.getValue("isLargeTick",false);
},set_isSmallTick:function(a){this._properties.setValue("isSmallTick",a);
},get_isSmallTick:function(){return this._properties.getValue("isSmallTick",false);
},_loadFromDictionary:function(a){if(a.text!=null){this.set_text(a.text);
}if(a.value!=null){this.set_value(a.value);
}if(a.enabled!=null){this.set_enabled(a.enabled);
}if(a.cssClass){this.set_cssClass(a.cssClass);
}if(a.tooltip!=null){this.set_tooltip(a.tooltip);
}if(a.isLargeTick!=null){this.set_isLargeTick(a.isLargeTick);
}if(a.isSmallTick!=null){this.set_isSmallTick(a.isSmallTick);
}},_render:function(c){c[c.length]="<li unselectable='on' ";
var j=this.get_tooltip();
if(j.toString()!=""){c[c.length]='title="'+j+'" ';
}var e=this.get_index();
var i=this.get_slider();
var f=i.get_itemData().length;
c[c.length]="class='";
var g=i._itemType;
if(g==Telerik.Web.UI.SliderItemType.Item){var a=this.get_cssClass();
if(a!=""){a=" "+a;
}var b=(this.get_enabled())?"'>":" rslItemDisabled'>";
if(e==0){c[c.length]="rslItem rslItemFirst"+a+b;
}else{if(e==f-1){c[c.length]="rslItem rslItemLast"+a+b;
}else{c[c.length]="rslItem"+a+b;
}}c[c.length]="<span>";
c[c.length]=this.get_text();
c[c.length]="</span>";
}else{if(g==Telerik.Web.UI.SliderItemType.Tick){var d=this.get_isLargeTick();
if(e==0){if(d){c[c.length]="rslLargeTick rslLargeTickFirst'>";
}else{c[c.length]="rslSmallTick rslSmallTickFirst'>";
}}else{if(e==f-1){if(d){c[c.length]="rslLargeTick rslLargeTickLast'>";
}else{c[c.length]="rslSmallTick rslSmallTickLast'>";
}}else{if(d){c[c.length]="rslLargeTick'>";
}else{c[c.length]="rslSmallTick'>";
}}}if(d){var h=this.get_value();
c[c.length]="<span>";
c[c.length]=h;
c[c.length]="</span>";
if(i._trackPosition==Telerik.Web.UI.SliderTrackPosition.Center){c[c.length]="<span class='rslBRItemText'>";
c[c.length]=h;
c[c.length]="</span>";
}}else{c[c.length]="&nbsp;";
}}}c[c.length]="</li>";
},get_textElement:function(){return this.get_element();
},get_slider:function(){return this._parent;
},_createChildListElement:function(){var a=document.createElement("ul");
this.get_slider().get_dropDownElement().appendChild(a);
},_shouldInitializeChild:function(a){return false;
},_createChildControls:function(){},_getHierarchicalIndex:function(){return this.get_index();
}};
Telerik.Web.UI.RadSliderItem.registerClass("Telerik.Web.UI.RadSliderItem",Telerik.Web.UI.ControlItem);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadSliderItemCollection=function(a){Telerik.Web.UI.RadSliderItemCollection.initializeBase(this,[a]);
};
Telerik.Web.UI.RadSliderItemCollection.prototype={};
Telerik.Web.UI.RadSliderItemCollection.registerClass("Telerik.Web.UI.RadSliderItemCollection",Telerik.Web.UI.ControlItemCollection);
