CREATE TABLE [dbo].[CampaignItemTemplates] (
    [CampaignItemTemplateID] INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]             INT           NOT NULL,
    [TemplateName]           VARCHAR (200) NULL,
    [GroupID]                INT           NULL,
    [BlastField1]            VARCHAR (200) NULL,
    [BlastField2]            VARCHAR (200) NULL,
    [BlastField3]            VARCHAR (200) NULL,
    [BlastField4]            VARCHAR (200) NULL,
    [BlastField5]            VARCHAR (200) NULL,
    [FromEmail]              VARCHAR (200) NULL,
    [FromName]               VARCHAR (200) NULL,
    [ReplyTo]                VARCHAR (200) NULL,
    [Subject]                VARCHAR (200) NULL,
    [CreatedUserID]          INT           NULL,
    [CreatedDate]            DATETIME      NULL,
    [UpdatedUserID]          INT           NULL,
    [UpdatedDate]            DATETIME      NULL,
    [IsDeleted]              BIT           NULL,
    [SuppressionGroupID]     INT           NULL,
    [Omniture1]              VARCHAR (200) NULL,
    [Omniture10]             VARCHAR (200) NULL,
    [Omniture2]              VARCHAR (200) NULL,
    [Omniture3]              VARCHAR (200) NULL,
    [Omniture4]              VARCHAR (200) NULL,
    [Omniture5]              VARCHAR (200) NULL,
    [Omniture6]              VARCHAR (200) NULL,
    [Omniture7]              VARCHAR (200) NULL,
    [Omniture8]              VARCHAR (200) NULL,
    [Omniture9]              VARCHAR (200) NULL,
    [Archived]				 BIT NULL, 
	[LayoutID]				 INT NULL, 
	[OptOutMasterSuppression] BIT NULL,
	[OptOutSpecificGroup]	 BIT NULL,
	[OmnitureCustomerSetup]	 BIT NULL,    
    [CampaignID] INT NULL, 
   CONSTRAINT [PK_CampaignItemTemplates] PRIMARY KEY CLUSTERED ([CampaignItemTemplateID] ASC) WITH (FILLFACTOR = 80)
);

