CREATE TABLE [dbo].[Gateway]
(
	[GatewayID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CustomerID] INT NULL, 
    [Name] VARCHAR(50) NULL, 
    [PubCode] VARCHAR(10) NULL, 
    [TypeCode] VARCHAR(10) NULL, 
    [GroupID] INT NULL, 
    [Header] VARCHAR(MAX) NULL, 
    [Footer] VARCHAR(MAX) NULL, 
    [ShowForgotPassword] BIT NULL, 
    [ForgotPasswordText] VARCHAR(1000) NULL, 
    [ShowSignup] BIT NULL, 
    [SignupText] VARCHAR(1000) NULL, 
    [SignupURL] VARCHAR(255) NULL, 
    [SubmitText] VARCHAR(1000) NULL, 
    [UseStyleFrom] VARCHAR(20) NULL, 
    [Style] VARCHAR(100) NULL, 
    [UseConfirmation] BIT NULL, 
    [ConfirmationMessage] VARCHAR(1000) NULL, 
    [ConfirmationText] VARCHAR(1000) NULL, 
    [UseRedirect] BIT NULL, 
    [RedirectURL] VARCHAR(255) NULL, 
    [RedirectDelay] INT NULL, 
    [LoginOrCapture] VARCHAR(20) NULL, 
    [ValidateEmail] BIT NULL, 
    [ValidatePassword] BIT NULL, 
    [ValidateCustom] BIT NULL, 
    [CreatedUserID] INT NULL, 
    [CreatedDate] DATETIME NULL, 
    [UpdatedUserID] INT NULL, 
    [UpdatedDate] DATETIME NULL, 
    [IsDeleted] BIT NULL
)
