CREATE TABLE [dbo].[MTA] (
    [MTAID]         INT           IDENTITY (1, 1) NOT NULL,
    [MTAName]       VARCHAR (100) NOT NULL,
    [DomainName]    VARCHAR (100) NOT NULL,
    [BlastConfigID] INT           NOT NULL,
    CONSTRAINT [PK_MTA] PRIMARY KEY CLUSTERED ([MTAID] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [IX_MTAName] UNIQUE NONCLUSTERED ([MTAName] ASC) WITH (FILLFACTOR = 80)
);

