CREATE TABLE [dbo].[ReportSchedule] (
    [ReportScheduleID] INT            IDENTITY (1, 1) NOT NULL,
    [CustomerID]       INT            NOT NULL,
    [ReportID]         INT            NOT NULL,
    [StartTime]        VARCHAR (10)   NULL,
    [StartDate]        VARCHAR (10)   NULL,
    [EndDate]          VARCHAR (10)   NULL,
    [ScheduleType]     VARCHAR (10)   NULL,
    [RecurrenceType]   VARCHAR (100)  NULL,
    [RunSunday]        BIT            NULL,
    [RunMonday]        BIT            NULL,
    [RunTuesday]       BIT            NULL,
    [RunWednesday]     BIT            NULL,
    [RunThursday]      BIT            NULL,
    [RunFriday]        BIT            NULL,
    [RunSaturday]      BIT            NULL,
    [MonthScheduleDay] INT            NULL,
    [MonthLastDay]     BIT            NULL,
    [FromEmail]        VARCHAR (500)  NULL,
    [FromName]         VARCHAR (200)  NULL,
    [EmailSubject]     VARCHAR (500)  NULL,
    [ToEmail]          VARCHAR (2000) NULL,
    [ReportParameters] VARCHAR (2000) NULL,
    [CreatedUserID]    INT            NULL,
    [CreatedDate]      DATETIME       NULL,
    [UpdatedUserID]    INT            NULL,
    [UpdatedDate]      DATETIME       NULL,
    [IsDeleted]        BIT            NULL,
    [BlastID] INT NULL DEFAULT null, 
    [ExportFormat] VARCHAR(50) NULL, 
    CONSTRAINT [PK_ReportSchedule] PRIMARY KEY CLUSTERED ([ReportScheduleID] ASC)
);

