CREATE TABLE [dbo].[Wizard] (
    [WizardID]            INT            IDENTITY (1, 1) NOT NULL,
    [IsNewMessage]        BIT            NULL,
    [WizardName]          VARCHAR (100)  NULL,
    [EmailSubject]        VARCHAR (255)  NULL,
    [FromName]            VARCHAR (100)  NULL,
    [FromEmail]           VARCHAR (100)  NULL,
    [ReplyTo]             VARCHAR (100)  NULL,
    [GroupID]             INT            NULL,
    [ContentID]           INT            NULL,
    [LayoutID]            INT            NULL,
    [BlastID]             INT            NULL,
    [FilterID]            INT            NULL,
    [StatusCode]          VARCHAR (25)   NULL,
    [CompletedStep]       INT            NULL,
    [CreatedDate]         DATETIME       CONSTRAINT [DF_Wizard_DateCreated] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]         DATETIME       NULL,
    [CardcvNumber]        VARCHAR (50)   NULL,
    [CardExpiration]      VARCHAR (50)   NULL,
    [CardHolderName]      VARCHAR (100)  NULL,
    [CardNumber]          VARCHAR (50)   NULL,
    [CardType]            VARCHAR (20)   NULL,
    [TransactionNo]       VARCHAR (50)   NULL,
    [MultiGroupIDs]       VARCHAR (2000) CONSTRAINT [DF_Wizard_MultiGroupIDs] DEFAULT ('') NULL,
    [SuppressionGroupIDs] VARCHAR (255)  CONSTRAINT [DF_Wizard_SuppressionGroupIDs] DEFAULT ('') NULL,
    [PageWatchID]         INT            NULL,
    [BlastType]           VARCHAR (10)   NULL,
    [EmailSubject2]       VARCHAR (255)  NULL,
    [ContentID2]          INT            NULL,
    [LayoutID2]           INT            NULL,
    [SampleWizardID]      INT            NULL,
    [RefBlastID]          INT            NULL,
    [DynamicFromEmail]    VARCHAR (100)  NULL,
    [DynamicFromName]     VARCHAR (100)  NULL,
    [DynamicReplyToEmail] VARCHAR (100)  NULL,
    [CreatedUserID]       INT            NULL,
    [UpdatedUserID]       INT            NULL,
    [IsDeleted]           BIT            CONSTRAINT [DF_Wizard_IsDeleted] DEFAULT ((0)) NOT NULL,
    [SampleID]            INT            NULL,
    [CampaignItemID]      INT            NULL,
    CONSTRAINT [PK_Wizard] PRIMARY KEY CLUSTERED ([WizardID] ASC) WITH (FILLFACTOR = 80)
);

