CREATE USER [ADMS_Admin] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE LOGIN [ADMS_Admin] WITH PASSWORD=N'é|[«µzUÉªÓ\þuÇ·­÷L·çá-±Ì', DEFAULT_DATABASE=[UAS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;
GO

