CREATE USER [Charles.Vashaw];
GO
CREATE LOGIN [Charles.Vashaw] WITH PASSWORD=N'Ja6/i9h5I3BW0nvrC8fnyByWZYk7crnjOLVYHt/+XQc=', DEFAULT_DATABASE=[UAS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO


