CREATE USER [Cody.Wagner];
GO
CREATE LOGIN [Cody.Wagner] WITH PASSWORD=N'e5bz0hC7oZAura5X3MTnO+iYungHgCcrEOixMGCqMyA=', DEFAULT_DATABASE=[UAS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO


