CREATE USER [Jason.Meier] FOR LOGIN [Jason.Meier] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE LOGIN [Jason.Meier]
    WITH PASSWORD = N'txjqz9d$jpe`mzducu{Rsh{lmsFT7_&#$!~<jc}nHcCxhrkl', SID = 0x46E679369DAC554C8714D0D34B60EB90, DEFAULT_DATABASE = [UAS], DEFAULT_LANGUAGE = [us_english];
