CREATE USER [kay.molencamp];
GO
CREATE LOGIN [kay.molencamp] WITH PASSWORD=N'/EZxJjPfh1A6kHaUdDX86s5q1GbAxUcPHceWxTeKCHQ=', DEFAULT_DATABASE=[KMCOMMON], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO


