CREATE USER [Luke.Juusola];
GO
CREATE LOGIN [Luke.Juusola] WITH PASSWORD=N'fVYwP1wYYC6doKR9lSP1IwnXyzHKRdpBEsh34K5/GRU=', DEFAULT_DATABASE=[UAS], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO


