CREATE USER [Micah.Matheson];
GO
CREATE LOGIN [Micah.Matheson] WITH PASSWORD=N'9LrkLV60hksn9adv+/8vdQX0TDlKA8NmgXvmyiB8C4o=', DEFAULT_DATABASE=[KMCOMMON], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO


