CREATE USER [Tod.Murray];
GO
CREATE LOGIN [Tod.Murray] WITH PASSWORD=N'HFGvoZnCl3l5FUBkh9Mu7bM7oVPSPxfaJ0mPdE5OyCk=', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO


