CREATE USER [webuser] FOR LOGIN [webuser] WITH DEFAULT_SCHEMA=[dbo];
GO
CREATE LOGIN [webuser] WITH PASSWORD=N'çÂõÏ³2ÕØ7á²Ìüó#¦F;]Ä4Ý', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO



