CREATE LOGIN [bill.hipps]
    WITH PASSWORD = N'kwbomUp{sqiqRfaqPzxim{#jmsFT7_&#$!~<{%zqc|Z|psqj', SID = 0xB2752FDAA12AC940A262C2DA7362EBA8, DEFAULT_DATABASE = [ECN5_ACCOUNTS], DEFAULT_LANGUAGE = [us_english];

