//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMPS.MD.Main {
    
    
    public partial class EditDashboard {
        
        /// <summary>
        /// ctlEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KMPS.MD.Main.DashboardEditor.Editor ctlEditor;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new KMPS.MD.MasterPages.Site Master {
            get {
                return ((KMPS.MD.MasterPages.Site)(base.Master));
            }
        }
    }
}
