(function(b,a){a("util/main",["kendo.core"],b);
}(function(){(function(){var q=Math,n=window.kendo,f=n.deepExtend;
var i=q.PI/180,r=Number.MAX_VALUE,u=-Number.MAX_VALUE,N="undefined";
function g(P){return typeof P!==N;
}function G(R,Q){var P=x(Q);
return q.round(R*P)/P;
}function x(P){if(P){return q.pow(10,P);
}else{return 1;
}}function p(R,Q,P){return q.max(q.min(R,P),Q);
}function y(P){return P*i;
}function h(P){return P/i;
}function l(P){return typeof P==="number"&&!isNaN(P);
}function O(Q,P){return g(Q)?Q:P;
}function K(P){return P*P;
}function w(Q){var R=[];
for(var P in Q){R.push(P+Q[P]);
}return R.sort().join("");
}function j(R){var P=2166136261;
for(var Q=0;
Q<R.length;
++Q){P+=(P<<1)+(P<<4)+(P<<7)+(P<<8)+(P<<24);
P^=R.charCodeAt(Q);
}return P>>>0;
}function k(P){return j(w(P));
}var v=Date.now;
if(!v){v=function(){return new Date().getTime();
};
}function c(P){var R=P.length,Q,T=r,S=u;
for(Q=0;
Q<R;
Q++){S=q.max(S,P[Q]);
T=q.min(T,P[Q]);
}return{min:T,max:S};
}function e(P){return c(P).min;
}function d(P){return c(P).max;
}function J(P){return H(P).min;
}function I(P){return H(P).max;
}function H(P){var T=r,S=u;
for(var Q=0,R=P.length;
Q<R;
Q++){var U=P[Q];
if(U!==null&&isFinite(U)){T=q.min(T,U);
S=q.max(S,U);
}}return{min:T===r?undefined:T,max:S===u?undefined:S};
}function o(P){if(P){return P[P.length-1];
}}function a(P,Q){P.push.apply(P,Q);
return P;
}function E(P){return n.template(P,{useWithBlock:false,paramName:"d"});
}function A(P,Q){return g(Q)&&Q!==null?" "+P+"='"+Q+"' ":"";
}function z(P){var R="";
for(var Q=0;
Q<P.length;
Q++){R+=A(P[Q][0],P[Q][1]);
}return R;
}function D(P){var R="";
for(var Q=0;
Q<P.length;
Q++){var S=P[Q][1];
if(g(S)){R+=P[Q][0]+":"+S+";";
}}if(R!==""){return R;
}}function C(P){if(typeof P!=="string"){P+="px";
}return P;
}function B(R){var S=[];
if(R){var Q=n.toHyphens(R).split("-");
for(var P=0;
P<Q.length;
P++){S.push("k-pos-"+Q[P]);
}}return S.join(" ");
}function m(P){return P===""||P===null||P==="none"||P==="transparent"||!g(P);
}function b(Q){var P={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var S=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var R="";
while(Q>0){if(Q<S[0]){S.shift();
}else{R+=P[S[0]];
Q-=S[0];
}}return R;
}function F(S){S=S.toLowerCase();
var P={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var U=0,R=0;
for(var Q=0;
Q<S.length;
++Q){var T=P[S.charAt(Q)];
if(!T){return null;
}U+=T;
if(T>R){U-=2*R;
}R=T;
}return U;
}function s(Q){var P=Object.create(null);
return function(){var S="";
for(var R=arguments.length;
--R>=0;
){S+=":"+arguments[R];
}if(S in P){return P[S];
}return Q.apply(this,arguments);
};
}function L(T){var S=[],P=0,R=T.length,U,Q;
while(P<R){U=T.charCodeAt(P++);
if(U>=55296&&U<=56319&&P<R){Q=T.charCodeAt(P++);
if((Q&64512)==56320){S.push(((U&1023)<<10)+(Q&1023)+65536);
}else{S.push(U);
P--;
}}else{S.push(U);
}}return S;
}function M(P){return P.map(function(R){var Q="";
if(R>65535){R-=65536;
Q+=String.fromCharCode(R>>>10&1023|55296);
R=56320|R&1023;
}Q+=String.fromCharCode(R);
return Q;
}).join("");
}function t(P,Q){if(P.length<2){return P.slice();
}function R(T,V){var Y=[],U=0,W=0,X=0;
while(U<T.length&&W<V.length){if(Q(T[U],V[W])<=0){Y[X++]=T[U++];
}else{Y[X++]=V[W++];
}}if(U<T.length){Y.push.apply(Y,T.slice(U));
}if(W<V.length){Y.push.apply(Y,V.slice(W));
}return Y;
}return function S(T){if(T.length<=1){return T;
}var V=Math.floor(T.length/2);
var U=T.slice(0,V);
var W=T.slice(V);
U=S(U);
W=S(W);
return R(U,W);
}(P);
}f(n,{util:{MAX_NUM:r,MIN_NUM:u,append:a,arrayLimits:c,arrayMin:e,arrayMax:d,defined:g,deg:h,hashKey:j,hashObject:k,isNumber:l,isTransparent:m,last:o,limitValue:p,now:v,objectKey:w,round:G,rad:y,renderAttr:A,renderAllAttr:z,renderPos:B,renderSize:C,renderStyle:D,renderTemplate:E,sparseArrayLimits:H,sparseArrayMin:J,sparseArrayMax:I,sqr:K,valueOrDefault:O,romanToArabic:F,arabicToRoman:b,memoize:s,ucs2encode:M,ucs2decode:L,mergeSort:t}});
n.drawing.util=n.util;
n.dataviz.util=n.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/text-metrics",["kendo.core","util/main"],b);
}(function(){(function(a){var e=document,f=window.kendo,b=f.Class,k=f.util,d=k.defined;
var h=b.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,q){var o=this,p=o._map,m={key:n,value:q};
p[n]=m;
if(!o._head){o._head=o._tail=m;
}else{o._tail.newer=m;
m.older=o._tail;
o._tail=m;
}if(o._length>=o._size){p[o._head.key]=null;
o._head=o._head.newer;
o._head.older=null;
}else{o._length++;
}},get:function(n){var o=this,m=o._map[n];
if(m){if(m===o._head&&m!==o._tail){o._head=m.newer;
o._head.older=null;
}if(m!==o._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=o._tail;
m.newer=null;
o._tail.newer=m;
o._tail=m;
}return m.value;
}}});
var c=a("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function l(){return{width:0,height:0,baseline:0};
}var j=b.extend({init:function(m){this._cache=new h(1000);
this._initOptions(m);
},options:{baselineMarkerSize:1},measure:function(v,t,n){if(!v){return l();
}var u=k.objectKey(t),p=k.hashKey(v+u),o=this._cache.get(p);
if(o){return o;
}var s=l();
var r=n?n:c;
var m=this._baselineMarker().cloneNode(false);
for(var q in t){var w=t[q];
if(d(w)){r.style[q]=w;
}}a(r).text(v);
r.appendChild(m);
e.body.appendChild(r);
if((v+"").length){s.width=r.offsetWidth-this.options.baselineMarkerSize;
s.height=r.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(p,s);
}r.parentNode.removeChild(r);
return s;
},_baselineMarker:function(){return a("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
j.current=new j();
function i(o,n,m){return j.current.measure(o,n,m);
}function g(o,m){var p=[];
if(o.length>0&&document.fonts){try{p=o.map(function(q){return document.fonts.load(q);
});
}catch(n){f.logToConsole(n);
}Promise.all(p).then(m,m);
}else{m();
}}f.util.TextMetrics=j;
f.util.LRUCache=h;
f.util.loadFonts=g;
f.util.measureText=i;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/base64",["util/main"],b);
}(function(){(function(){var e=window.kendo,a=e.deepExtend,d=String.fromCharCode;
var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function b(p){var q="";
var g,h,j,k,l,m,n;
var o=0;
p=c(p);
while(o<p.length){g=p.charCodeAt(o++);
h=p.charCodeAt(o++);
j=p.charCodeAt(o++);
k=g>>2;
l=(g&3)<<4|h>>4;
m=(h&15)<<2|j>>6;
n=j&63;
if(isNaN(h)){m=n=64;
}else{if(isNaN(j)){n=64;
}}q=q+f.charAt(k)+f.charAt(l)+f.charAt(m)+f.charAt(n);
}return q;
}function c(j){var k="";
for(var h=0;
h<j.length;
h++){var g=j.charCodeAt(h);
if(g<128){k+=d(g);
}else{if(g<2048){k+=d(192|g>>>6);
k+=d(128|g&63);
}else{if(g<65536){k+=d(224|g>>>12);
k+=d(128|g>>>6&63);
k+=d(128|g&63);
}}}}return k;
}a(e.util,{encodeBase64:b,encodeUTF8:c});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("mixins/observers",["kendo.core"],b);
}(function(){(function(a){var e=Math,d=window.kendo,b=d.deepExtend,c=a.inArray;
var f={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(g){if(!this._observers){this._observers=[g];
}else{this._observers.push(g);
}return this;
},removeObserver:function(g){var i=this.observers();
var h=c(g,i);
if(h!=-1){i.splice(h,1);
}return this;
},trigger:function(i,g){var k=this._observers;
var j;
var h;
if(k&&!this._suspended){for(h=0;
h<k.length;
h++){j=k[h];
if(j[i]){j[i](g);
}}}return this;
},optionsChange:function(g){g=g||{};
g.element=this;
this.trigger("optionsChange",g);
},geometryChange:function(){this.trigger("geometryChange",{element:this});
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=e.max((this._suspended||0)-1,0);
return this;
},_observerField:function(g,h){if(this[g]){this[g].removeObserver(this);
}this[g]=h;
h.addObserver(this);
}};
b(d,{mixins:{ObserversMixin:f}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.gauge",["kendo.dataviz.core","kendo.drawing","kendo.dataviz.themes"],b);
}(function(){var a={id:"dataviz.gauge",name:"Gauge",category:"dataviz",description:"Radial and Linear gauges.",depends:["dataviz.core","dataviz.themes"]};
(function(b,ao){var V=Math,P=window.kendo,ap=P.util,aq=P.ui.Widget,w=P.deepExtend,v=P.dataviz,k=v.autoMajorUnit,s=v.ChartElement,ab=v.NumericAxis,l=v.Axis,q=v.Box2D,t=P.Class,D=ap.defined,O=ap.isNumber,N=v.interpolateValue,K=v.getSpacing,am=v.round,H=v.geometry,F=v.drawing,ae=H.Point,L=F.Group,ad=F.Path,al=H.Rect,an=F.Text;
var f=150,R=250,g="arrow",h="arrowPointer",m="barPointer",p="#000",r=0.05,u=v.COORD_PRECISION,W=Number.MAX_VALUE,Z=-Number.MAX_VALUE,x=200,y=0.5,C=200,B=60,A=60,z=5,E=V.PI/180,I=180,M="inside",Q="linear",aa="needle",ac="outside",ag="radialPointer",ar="x",at="y";
var af=t.extend({init:function(au,X){var Y=this;
var av=au.options;
s.fn.init.call(Y,X);
X=Y.options;
X.fill=X.color;
Y.scale=au;
if(D(X.value)){X.value=V.min(V.max(X.value,av.min),av.max);
}else{X.value=av.min;
}},options:{color:p},value:function(X){var av=this;
var Y=av.options;
var aw=Y.value;
var au=av.scale.options;
if(arguments.length===0){return aw;
}Y._oldValue=Y._oldValue!==ao?Y.value:au.min;
Y.value=V.min(V.max(X,au.min),au.max);
if(av.elements){av.repaint();
}}});
var ai=af.extend({options:{shape:aa,cap:{size:r},arrow:{width:16,height:14},animation:{type:ag,duration:f}},setRadius:function(X){var Y=this;
if(X){Y.elements.clear();
Y.render(Y.parent,Y.center,X);
}},setAngle:function(X){this.elements.transform(H.transform().rotate(X,this.center));
},repaint:function(){var aw=this;
var av=aw.scale;
var au=aw.options;
var Y=av.slotAngle(au._oldValue);
var X=av.slotAngle(au.value);
if(au.animation.transitions===false){aw.setAngle(X);
}else{new aj(aw.elements,w(au.animation,{oldAngle:Y,newAngle:X})).play();
}},render:function(){var aw=this;
var av=aw.scale;
var X=av.arc.center;
var au=aw.options;
var Y=new L();
if(au.animation!==false){w(au.animation,{startAngle:0,center:X,reverse:av.options.reverse});
}if(au.shape===aa){Y.append(aw._renderNeedle(),aw._renderCap());
}else{Y.append(aw._renderArrow());
}aw.elements=Y;
aw.setAngle(E);
return Y;
},reflow:function(X){var aw=this;
var au=aw.center=X.center;
var av=aw.radius=X.getRadiusX();
var Y=aw.capSize=Math.round(av*aw.options.cap.size);
aw.bbox=al.fromPoints(new ae(au.x-Y,au.y-Y),new ae(au.x+Y,au.y+Y));
},_renderNeedle:function(){var ax=this;
var aw=ax.options;
var Y=ax.scale.options.minorTicks.size;
var X=ax.center;
var au=aw.color;
var av=new ad({fill:{color:au},stroke:{color:au,width:y}});
av.moveTo(X.x+ax.radius-Y,X.y).lineTo(X.x,X.y-ax.capSize/2).lineTo(X.x,X.y+ax.capSize/2).close();
return av;
},_renderCap:function(){var aw=this;
var av=aw.options;
var Y=av.cap.color||av.color;
var au=new H.Circle(aw.center,aw.capSize);
var X=new F.Circle(au,{fill:{color:Y},stroke:{color:Y}});
return X;
}});
var ak=ab.extend({init:function(X){var Y=this;
Y.options=w({},Y.options,X);
Y.options.majorUnit=Y.options.majorUnit||k(Y.options.min,Y.options.max);
Y.options.minorUnit=Y.options.minorUnit||Y.options.majorUnit/10;
l.fn.init.call(Y,Y.options);
},options:{min:0,max:100,majorTicks:{size:15,align:M,color:p,width:y,visible:true},minorTicks:{size:10,align:M,color:p,width:y,visible:true},startAngle:-30,endAngle:210,labels:{position:M,padding:2}},render:function(Y,au){var av=this;
var X=av.renderArc(Y,au);
av.bbox=X.bbox();
av.labelElements=av.renderLabels();
av.ticks=av.renderTicks();
av.ranges=av.renderRanges();
},reflow:function(X){var av=this;
var Y=X.center();
var au=V.min(X.height(),X.width())/2;
if(av.bbox!==ao){av.bbox=av.arc.bbox();
av.radius(av.arc.getRadiusX());
av.repositionRanges();
av.renderLabels();
}else{return av.render(Y,au);
}},slotAngle:function(az){var av=this.options;
var ay=av.startAngle;
var ax=av.reverse;
var X=av.endAngle-ay;
var au=av.min;
var Y=av.max;
var aw;
if(ax){aw=av.endAngle-(az-au)/(Y-au)*X;
}else{aw=(az-au)/(Y-au)*X+ay;
}return aw+I;
},renderLabels:function(){var aS=this;
var aL=aS.options;
var aK=aL.majorTicks.size;
var Y=aS.arc.clone();
var aO=Y.getRadiusX();
var aT=aS.tickAngles(Y,aL.majorUnit);
var aE=aS.labels;
var au=aE.length;
var aG=aL.labels;
var aM=aG.padding;
var aP=aO*0.05;
var aR=aL.rangeSize=aL.rangeSize||aO*0.1;
var aQ=aL.ranges||[];
var ay,ax,aC;
var X,aB,aJ,az,av,aw,aA;
var aF=new L();
var aI,aD,aN,aH;
if(aS.options.rangeDistance!==ao){aP=aS.options.rangeDistance;
}else{aS.options.rangeDistance=aP;
}if(aG.position===M){aO-=aK;
if(aQ.length&&aS.labelElements===ao){aO-=aR+aP;
}Y.setRadiusX(aO).setRadiusY(aO);
}for(az=0;
az<au;
az++){aB=aE[az];
ay=aB.box.width()/2;
ax=aB.box.height()/2;
X=aT[az];
aC=(X-I)*E;
aA=aG.position===M;
aJ=Y.pointAt(X);
av=aJ.x+V.cos(aC)*(ay+aM)*(aA?1:-1);
aw=aJ.y+V.sin(aC)*(ax+aM)*(aA?1:-1);
aB.reflow(new v.Box2D(av-ay,aw-ax,av+ay,aw+ax));
aD=new ae(aB.box.x1,aB.box.y1);
if(aS.labelElements===ao){aI=c(aB,aL.labels);
aF.append(aI);
}else{aI=aS.labelElements.children[az];
aN=aI.bbox().origin;
aH=aI.transform()||H.transform();
aH.translate(aD.x-aN.x,aD.y-aN.y);
aI.transform(aH);
}aS.bbox=al.union(aS.bbox,aI.bbox());
}return aF;
},repositionRanges:function(){var ay=this;
var aw=ay.ranges.children;
var ax=ay.options.rangeSize;
var au=ay.options.rangeDistance;
var av,Y;
if(aw.length>0){av=ay.getRangeRadius();
if(ay.options.labels.position===M){av+=ax+au;
}Y=av+ax/2;
for(var X=0;
X<aw.length;
X++){aw[X]._geometry.setRadiusX(Y).setRadiusY(Y);
}ay.bbox=al.union(ay.bbox,ay.ranges.bbox());
}},renderRanges:function(){var aE=this;
var X=aE.arc;
var az=new L();
var Y,aF;
var aC=aE.rangeSegments();
var aD=aC.length;
var aA=aE.options.reverse;
var ay=aE.options.rangeSize;
var av=aE.options.rangeDistance;
var aB,ax,aw,au;
if(aD){ax=aE.getRangeRadius();
aE.radius(aE.radius()-ay-av);
for(au=0;
au<aD;
au++){aB=aC[au];
Y=aE.slotAngle(aB[aA?"to":"from"]);
aF=aE.slotAngle(aB[!aA?"to":"from"]);
if(aF-Y!==0){aw=new H.Arc(X.center,{radiusX:ax+ay/2,radiusY:ax+ay/2,startAngle:Y,endAngle:aF});
az.append(new F.Arc(aw,{stroke:{width:ay,color:aB.color,opacity:aB.opacity}}));
}}}return az;
},rangeSegments:function(){var au=this;
var az=au.options;
var aB=az.ranges||[];
var X=aB.length;
var aA;
var aF;
var Y=az.rangePlaceholderColor;
var aE=[];
var aD;
var ay=az.min;
var ax=az.max;
var av,aw;
function aC(aH,aJ,aG,aI){return{from:aH,to:aJ,color:aG,opacity:aI};
}if(X){aE.push(aC(ay,ax,Y));
for(av=0;
av<X;
av++){aA=J(aB[av],ay,ax);
aF=aE.length;
for(aw=0;
aw<aF;
aw++){aD=aE[aw];
if(aD.from<=aA.from&&aA.from<=aD.to){aE.push(aC(aA.from,aA.to,aA.color,aA.opacity));
if(aD.from<=aA.to&&aA.to<=aD.to){aE.push(aC(aA.to,aD.to,Y,aA.opacity));
}aD.to=aA.from;
break;
}}}}return aE;
},getRangeRadius:function(){var ay=this;
var au=ay.options;
var Y=au.majorTicks.size;
var ax=au.rangeSize;
var aw=au.rangeDistance;
var X=ay.arc;
var av;
if(au.labels.position===ac){av=X.getRadiusX()-Y-aw-ax;
}else{av=X.getRadiusX()-ax;
}return av;
},renderArc:function(Y,av){var aw=this;
var au=aw.options;
var X=aw.arc=new H.Arc(Y,{radiusX:av,radiusY:av,startAngle:au.startAngle+I,endAngle:au.endAngle+I});
return X;
},renderTicks:function(){var aA=this;
var Y=aA.arc;
var ay=aA.options;
var av=ay.labels.position;
var X=new L();
var aw=ay.majorTicks.size;
var ax=ay.minorTicks.size;
var aB=Y.clone();
var az=aB.getRadiusX();
function au(aC,aG,aL,aI){var aJ=new L(),aD=aC.center,aF=aC.getRadiusX(),aE,aK,aH,aM=aI.visible;
if(aM){for(aE=0;
aE<aG.length;
aE++){aK=aC.pointAt(aG[aE]);
aH=new ae(aD.x+aF-aI.size,aD.y).rotate(aG[aE],aD);
aJ.append(new ad({stroke:{color:aI.color,width:aI.width}}).moveTo(aK).lineTo(aH));
}}return aJ;
}aA.majorTickAngles=aA.tickAngles(Y,ay.majorUnit);
aA.majorTicks=au(aB,aA.majorTickAngles,ay.majorUnit,ay.majorTicks);
X.append(aA.majorTicks);
aA._tickDifference=aw-ax;
if(av===ac){aB.setRadiusX(az-aw+ax).setRadiusY(az-aw+ax);
}aA.minorTickAngles=aA.normalizeTickAngles(aA.tickAngles(Y,ay.minorUnit));
aA.minorTicks=au(aB,aA.minorTickAngles,ay.minorUnit,ay.minorTicks,ay.majorUnit);
X.append(aA.minorTicks);
return X;
},normalizeTickAngles:function(X){var aw=this;
var au=aw.options;
var av=au.majorUnit/au.minorUnit;
for(var Y=X.length-1;
Y>=0;
Y--){if(Y%av===0){X.splice(Y,1);
}}return X;
},tickAngles:function(az,aC){var aA=this;
var au=aA.options;
var ay=au.reverse;
var ax=au.max-au.min;
var X=az.endAngle-az.startAngle;
var av=az.startAngle;
var aD=ax/aC;
var aB=X/aD;
var aw=[];
var Y;
if(ay){av+=X;
aB=-aB;
}for(Y=0;
Y<aD;
Y++){aw.push(am(av,u));
av+=aB;
}if(am(av)<=az.endAngle){aw.push(av);
}return aw;
},radius:function(X){var Y=this;
if(X){Y.arc.setRadiusX(X).setRadiusY(X);
Y.repositionTicks(Y.majorTicks.children,Y.majorTickAngles);
Y.repositionTicks(Y.minorTicks.children,Y.minorTickAngles,true);
}else{return Y.arc.getRadiusX();
}},repositionTicks:function(aB,az,au){var ay=this;
var X=au?ay._tickDifference||0:0;
var aA=ay.arc;
var aw=aA.getRadiusX();
if(au&&ay.options.labels.position===ac&&X!==0){aA=ay.arc.clone();
aA.setRadiusX(aw-X).setRadiusY(aw-X);
}for(var Y=0;
Y<aB.length;
Y++){var av=aA.pointAt(az[Y]);
var ax=aB[Y].segments;
var aC=av.x-ax[0].anchor().x;
var aD=av.y-ax[0].anchor().y;
aB[Y].transform(new H.Transformation().translate(aC,aD));
}}});
var G=aq.extend({init:function(X,aA){var Y=this;
var av;
var ay;
var ax;
var az=v.ui.themes||{};
var aw;
P.destroy(X);
b(X).empty();
aq.fn.init.call(Y,X);
Y.wrapper=Y.element;
Y._originalOptions=w({},aA);
av=w({},Y.options,aA);
ax=av.theme;
aw=az[ax]||az[ax.toLowerCase()];
ay=ax&&aw?aw.gauge:{};
Y.options=w({},ay,av);
if(b.isArray(av.pointer)){for(var au=0;
au<av.pointer.length;
au++){Y.options.pointer[au]=w({},ay.pointer,av.pointer[au]);
}}Y.element.addClass("k-gauge");
Y.surface=Y._createSurface();
Y.redraw();
},options:{plotArea:{},theme:"default",renderAs:"",pointer:{},scale:{},gaugeArea:{}},destroy:function(){this.surface.destroy();
aq.fn.destroy.call(this);
},value:function(au){var Y=this;
var X=Y.pointers[0];
if(arguments.length===0){return X.value();
}X.value(au);
Y._setValueOptions(au);
},_draw:function(){var X=this.surface;
X.clear();
X.draw(this._visuals);
},exportVisual:function(){return this._visuals;
},allValues:function(aw){var av=this;
var au=av.pointers;
var X=[];
var Y;
if(arguments.length===0){for(Y=0;
Y<au.length;
Y++){X.push(au[Y].value());
}return X;
}if(b.isArray(aw)){for(Y=0;
Y<aw.length;
Y++){if(O(aw[Y])){au[Y].value(aw[Y]);
}}}av._setValueOptions(aw);
},_setValueOptions:function(au){var Y=[].concat(this.options.pointer);
au=[].concat(au);
for(var X=0;
X<au.length;
X++){Y[X].value=au[X];
}},_resize:function(){var au=this;
var Y=au.options.transitions;
var X;
au.options.transitions=false;
for(X=0;
X<au.pointers.length;
X++){au.pointers[X].options.animation.transitions=false;
}au.redraw();
au.options.transitions=Y;
for(X=0;
X<au.pointers.length;
X++){au.pointers[X].options.animation.transitions=Y;
}},redraw:function(){var au=this;
var Y=w(au._getSize(),au.options.gaugeArea);
var av=new al([0,0],[Y.width,Y.height]);
var X;
au.surface.clear();
au.gaugeArea=au._createGaugeArea();
au.surface.element.css({width:Y.width,height:Y.height});
au._createModel();
X=e(av.bbox(),au._gaugeAreaMargin);
au.reflow(X);
},_createGaugeArea:function(){var ax=this;
var av=ax.options.gaugeArea;
var aw=ax.surface.size();
var Y=av.border||{};
var X=new al([0,0],[aw.width,aw.height]);
ax._gaugeAreaMargin=av.margin||z;
if(Y.width>0){X=e(X,Y.width);
}var au=ad.fromRect(X,{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType,lineJoin:"round",lineCap:"round"},fill:{color:av.background}});
return au;
},_createSurface:function(){var au=this;
var X=au.options;
var Y=au._getSize();
Y=X.gaugeArea?w(Y,X.gaugeArea):Y;
var av=b("<div></div>").appendTo(au.element).css({width:Y.width,height:Y.height});
return new F.Surface.create(av,{type:X.renderAs});
},getSize:function(){return this._getSize();
},_getSize:function(){var au=this;
var X=au.element;
var av=X.width();
var Y=X.height();
if(!av){av=C;
}if(!Y){Y=x;
}return{width:av,height:Y};
}});
var ah=G.extend({init:function(X,Y){var au=this;
G.fn.init.call(au,X,Y);
P.notify(au,v.ui);
},options:{name:"RadialGauge",transitions:true,gaugeArea:{background:""}},reflow:function(X){var av=this;
var au=av.pointers;
av.scale.reflow(X);
av._initialPlotArea=av.scale.bbox;
for(var Y=0;
Y<au.length;
Y++){au[Y].reflow(av.scale.arc);
av._initialPlotArea=al.union(av._initialPlotArea,au[Y].bbox);
}av.fitScale(X);
av.alignScale(X);
av._buildVisual(av.gaugeArea,au,av.scale);
av._draw();
},_buildVisual:function(Y,av,aw){var ax=new L();
var X;
ax.append(Y);
ax.append(aw.ticks);
ax.append(aw.ranges);
for(var au=0;
au<av.length;
au++){X=av[au];
X.render();
ax.append(X.elements);
X.value(X.options.value);
}ax.append(aw.labelElements);
this._visuals=ax;
},fitScale:function(Y){var aG=this;
var aD=aG.scale;
var X=aD.arc;
var aC=aG._initialPlotArea;
var aF=V.abs(aG.getDiff(aC,Y));
var az=am(aF,u);
var av=am(-aF,u);
var aA,ay,aw,ax,aB;
var aE=0;
var au=0;
while(au++<100){aE=aB===aw?aE+1:0;
if(aE>5){break;
}if(az!=ax){aA=aG.getPlotBox(az,Y,X);
if(0<=aA&&aA<=2){break;
}}if(av!=ax){aw=aG.getPlotBox(av,Y,X);
if(0<=aw&&aw<=2){break;
}}if(aA>0&&aw>0){ax=az*2;
}else{if(aA<0&&aw<0){ax=av*2;
}else{ax=am((az+av)/2||1,u);
}}ay=aG.getPlotBox(ax,Y,X);
if(0<=ay&&ay<=2){break;
}aB=aw;
if(ay>0){av=ax;
aw=ay;
}else{az=ax;
aA=ay;
}}},getPlotBox:function(ay,Y,X){var az=this;
var ax=az.scale;
var av=az.pointers;
var aw=X.getRadiusX();
X=X.clone();
X.setRadiusX(aw+ay).setRadiusY(aw+ay);
ax.arc=X;
ax.reflow(Y);
az.plotBbox=ax.bbox;
for(var au=0;
au<av.length;
au++){av[au].reflow(X);
az.plotBbox=al.union(az.plotBbox,av[au].bbox);
}return az.getDiff(az.plotBbox,Y);
},getDiff:function(Y,X){return V.min(X.width()-Y.width(),X.height()-Y.height());
},alignScale:function(X){var aA=this;
var ax=aA.plotBbox.center();
var Y=X.center();
var av=ax.x-Y.x;
var aw=ax.y-Y.y;
var az=aA.scale;
var ay=aA.pointers;
az.arc.center.x-=av;
az.arc.center.y-=aw;
az.reflow(X);
for(var au=0;
au<ay.length;
au++){ay[au].reflow(az.arc);
aA.plotBbox=al.union(az.bbox,ay[au].bbox);
}},_createModel:function(){var ax=this;
var au=ax.options;
var av=au.pointer;
var aw=ax.scale=new ak(au.scale);
var X;
ax.pointers=[];
av=b.isArray(av)?av:[av];
for(var Y=0;
Y<av.length;
Y++){X=new ai(aw,w({},av[Y],{animation:{transitions:au.transitions}}));
ax.pointers.push(X);
}}});
var S=G.extend({init:function(X,au){var Y=this;
G.fn.init.call(Y,X,au);
P.notify(Y,v.ui);
},options:{name:"LinearGauge",transitions:true,gaugeArea:{background:""},scale:{vertical:true}},reflow:function(X){var ay=this;
var ax=ay.pointers;
var au=X.origin.x;
var av=X.origin.y;
var Y=new v.Box2D(au,av,au+X.width(),av+X.height());
ay.scale.reflow(Y);
for(var aw=0;
aw<ax.length;
aw++){ax[aw].reflow();
}ay.bbox=ay._getBox(Y);
ay._alignElements();
ay._shrinkElements();
ay._buildVisual();
ay._draw();
},_buildVisual:function(){var aw=this;
var ax=new L();
var av=aw.scale.render();
var au=aw.pointers;
var X;
ax.append(aw.gaugeArea);
ax.append(av);
for(var Y=0;
Y<au.length;
Y++){X=au[Y];
ax.append(X.render());
X.value(X.options.value);
}aw._visuals=ax;
},_createModel:function(){var ay=this;
var av=ay.options;
var aw=av.pointer;
var ax=ay.scale=new U(av.scale);
var X,Y;
ay.pointers=[];
aw=b.isArray(aw)?aw:[aw];
for(var au=0;
au<aw.length;
au++){Y=w({},aw[au],{animation:{transitions:av.transitions}});
if(Y.shape===g){X=new i(ax,Y);
}else{X=new n(ax,Y);
}ay.pointers.push(X);
}},_getSize:function(){var Y=this;
var X=Y.element;
var aw=X.width();
var au=X.height();
var av=Y.options.scale.vertical;
if(!aw){aw=av?B:C;
}if(!au){au=av?x:A;
}return{width:aw,height:au};
},_getBox:function(X){var az=this;
var ax=az.scale;
var aw=az.pointers;
var Y=X.center();
var av=aw[0].box.clone().wrap(ax.box);
var ay;
for(var au=0;
au<aw.length;
au++){av.wrap(aw[au].box.clone());
}if(ax.options.vertical){ay=av.width()/2;
av=new q(Y.x-ay,X.y1,Y.x+ay,X.y2);
}else{ay=av.height()/2;
av=new q(X.x1,Y.y-ay,X.x2,Y.y+ay);
}return av;
},_alignElements:function(){var az=this;
var ax=az.scale;
var aw=az.pointers;
var ay=ax.box;
var X=aw[0].box.clone().wrap(ax.box);
var av=az.bbox;
var Y,au;
for(au=0;
au<aw.length;
au++){X.wrap(aw[au].box.clone());
}if(ax.options.vertical){Y=av.center().x-X.center().x;
ax.reflow(new q(ay.x1+Y,av.y1,ay.x2+Y,av.y2));
}else{Y=av.center().y-X.center().y;
ax.reflow(new q(av.x1,ay.y1+Y,av.x2,ay.y2+Y));
}for(au=0;
au<aw.length;
au++){aw[au].reflow(az.bbox);
}},_shrinkElements:function(){var ay=this;
var aw=ay.scale;
var au=ay.pointers;
var ax=aw.box.clone();
var av=aw.options.vertical?"y":"x";
var Y=au[0].box;
var X;
for(X=0;
X<au.length;
X++){Y.wrap(au[X].box.clone());
}ax[av+1]+=V.max(ax[av+1]-Y[av+1],0);
ax[av+2]-=V.max(Y[av+2]-ax[av+2],0);
aw.reflow(ax);
for(X=0;
X<au.length;
X++){au[X].reflow(ay.bbox);
}}});
var U=ab.extend({init:function(X){var Y=this;
Y.options=w({},Y.options,X);
Y.options=w({},Y.options,{labels:{mirror:Y.options.mirror}});
Y.options.majorUnit=Y.options.majorUnit||k(Y.options.min,Y.options.max);
l.fn.init.call(Y,Y.options);
Y.options.minorUnit=Y.options.minorUnit||Y.options.majorUnit/10;
},options:{min:0,max:50,majorTicks:{size:15,align:M,color:p,width:y,visible:true},minorTicks:{size:10,align:M,color:p,width:y,visible:true},line:{width:y},labels:{position:M,padding:2},mirror:false,_alignLines:false},render:function(){var ax=this;
var X=ax.elements=new L();
var Y=ax.renderLabels();
var av=ax.renderLine();
var aw=ax.renderTicks();
var au=ax.renderRanges();
X.append(av,Y,aw,au);
return X;
},renderRanges:function(){var aF=this;
var ay=aF.options;
var aw=ay.min;
var av=ay.max;
var aA=ay.ranges||[];
var aG=ay.vertical;
var ax=ay.labels.mirror;
var Y=new L();
var X=aA.length;
var aB=ay.rangeSize||ay.minorTicks.size/2;
var az,aC,aD,aE,au;
if(X){for(au=0;
au<X;
au++){az=J(aA[au],aw,av);
aC=aF.getSlot(az.from,az.to);
aD=aG?aF.lineBox():aC;
aE=aG?aC:aF.lineBox();
if(aG){aD.x1-=aB*(ax?-1:1);
}else{aE.y2+=aB*(ax?-1:1);
}Y.append(ad.fromRect(new al([aD.x1,aE.y1],[aD.x2-aD.x1,aE.y2-aE.y1]),{fill:{color:az.color,opacity:az.opacity},stroke:{}}));
}}return Y;
},renderLabels:function(){var aw=this;
var av=aw.options;
var au=aw.labels;
var X=new L();
for(var Y=0;
Y<au.length;
Y++){X.append(c(au[Y],av.labels));
}return X;
},renderLine:function(){var ax=this;
var aw=ax.options;
var Y=aw.line;
var au=ax.lineBox();
var av;
var X=new L();
if(Y.width>0&&Y.visible){av=new ad({stroke:{color:Y.color,dashType:Y.dashType,width:Y.width}});
av.moveTo(au.x1,au.y1).lineTo(au.x2,au.y2);
X.append(av);
}return X;
},renderTicks:function(){var ax=this;
var az=new L();
var av=ax.options;
var X=ax.lineBox();
var au=av.labels.mirror;
var Y=av.majorTicks.visible?av.majorUnit:0;
var ay={_alignLines:av._alignLines,vertical:av.vertical};
function aw(aD,aC){var aB,aA=aD.length;
if(aC.visible){for(aB=aC.skip;
aB<aA;
aB+=aC.step){if(aB%aC.skipUnit===0){continue;
}ay.tickX=au?X.x2:X.x2-aC.size;
ay.tickY=au?X.y1-aC.size:X.y1;
ay.position=aD[aB];
az.append(ax.renderAxisTick(ay,aC));
}}}aw(ax.getMajorTickPositions(),av.majorTicks);
aw(ax.getMinorTickPositions(),w({},{skipUnit:Y/av.minorUnit},av.minorTicks));
return az;
},renderAxisTick:function(Y,aw){var ay=Y.tickX;
var az=Y.tickY;
var au=Y.position;
var av,X,ax;
if(Y.vertical){av=new ae(ay,au);
X=new ae(ay+aw.size,au);
}else{av=new ae(au,az);
X=new ae(au,az+aw.size);
}ax=new ad({stroke:{color:aw.color,width:aw.width}}).moveTo(av).lineTo(X);
return ax;
}});
var T=af.extend({init:function(au,X){var Y=this;
af.fn.init.call(Y,au,X);
Y.options=w({track:{visible:D(X.track)}},Y.options);
},options:{shape:m,track:{border:{width:1}},color:p,border:{width:1},opacity:1,margin:K(3),animation:{type:m},visible:true},reflow:function(){var av=this;
var au=av.options;
var az=av.scale;
var aA=az.lineBox();
var aD=au.track.size||au.size;
var ax=au.size/2;
var Y=az.options.mirror;
var X=K(au.margin);
var aE=az.options.vertical;
var aB=aE?X[Y?"left":"right"]:X[Y?"bottom":"top"];
var aw,ay,aC;
aB=Y?-aB:aB;
if(aE){aC=new q(aA.x1+aB,aA.y1,aA.x1+aB,aA.y2);
if(Y){aC.x1-=aD;
}else{aC.x2+=aD;
}if(au.shape!==m){ay=new q(aA.x2+aB,aA.y1-ax,aA.x2+aB,aA.y2+ax);
aw=ay;
}}else{aC=new q(aA.x1,aA.y1-aB,aA.x2,aA.y1-aB);
if(Y){aC.y2+=aD;
}else{aC.y1-=aD;
}if(au.shape!==m){ay=new q(aA.x1-ax,aA.y1-aB,aA.x2+ax,aA.y1-aB);
aw=ay;
}}av.trackBox=aC;
av.pointerRangeBox=ay;
av.box=aw||aC.clone().pad(au.border.width);
},getElementOptions:function(){var X=this.options;
return{fill:{color:X.color,opacity:X.opacity},stroke:D(X.border)?{color:X.border.width?X.border.color||X.color:"",width:X.border.width,dashType:X.border.dashType,opacity:X.opacity}:null};
},_margin:function(){var av=this;
var au=av.options;
var aw=av.scale;
var Y=aw.options.mirror;
var X=K(au.margin);
var ay=aw.options.vertical;
var ax=ay?X[Y?"left":"right"]:X[Y?"bottom":"top"];
return ax;
}});
var i=T.extend({init:function(Y,X){T.fn.init.call(this,Y,X);
if(this.options.size===ao){this.options.size=this.scale.options.majorTicks.size*0.6;
}},pointerShape:function(){var aA=this;
var Y=aA.options;
var aw=aA.scale;
var az=Y.size;
var aB=aw.options.vertical;
var X=az/2;
var ay=aw.options.mirror?-1:1;
var av=aw.options.reverse;
var au,ax;
if(aB){au=av?"y2":"y1";
ax=[new ae(0,0-X),new ae(0-ay*az,0),new ae(0,0+X)];
}else{au=av?"x1":"x2";
ax=[new ae(0-X,0),new ae(0,0+ay*az),new ae(0+X,0)];
}return ax;
},repaint:function(){var av=this;
var au=av.scale;
var Y=av.options;
var X=new j(av.elements,w(Y.animation,{vertical:au.options.vertical,mirror:au.options.mirror,margin:av._margin(Y.margin),from:au.getSlot(Y._oldValue),to:au.getSlot(Y.value)}));
if(Y.animation.transitions===false){X.options.duration=0;
}X.setup();
X.play();
},render:function(){var ay=this;
var au=ay.options;
var Y=new L();
var av=ay.scale;
var X=ay.getElementOptions();
var aw=ay.pointerShape(au.value);
au.animation.type=h;
Y=new ad({stroke:X.stroke,fill:X.fill}).moveTo(aw[0]).lineTo(aw[1]).lineTo(aw[2]).close();
var ax=av.getSlot(au.value);
Y.transform(H.transform().translate(ax.x1,ax.y1));
ay.elements=Y;
return Y;
}});
var n=T.extend({init:function(Y,X){T.fn.init.call(this,Y,X);
if(this.options.size===ao){this.options.size=this.scale.options.majorTicks.size*0.3;
}},pointerShape:function(aH){var aG=this;
var ax=aG.options;
var aC=aG.scale;
var aI=aC.options.vertical;
var aw=aC.options.mirror;
var Y=aw==aI?-1:1;
var aD=ax.size*Y;
var av=aC.getSlot(aC.options.min);
var aF=aC.getSlot(aH);
var X=aI?at:ar;
var aE=aI?ar:at;
var au=aG._margin()*Y;
var ay=new ae();
ay[X]=av[X+"1"];
ay[aE]=av[aE+"1"];
var az=new ae();
az[X]=aF[X+"1"];
az[aE]=aF[aE+"1"];
if(aI){ay.translate(au,0);
az.translate(au,0);
}else{ay.translate(0,au);
az.translate(0,au);
}var aA=az.clone();
var aB=ay.clone();
if(aI){aA.translate(aD,0);
aB.translate(aD,0);
}else{aA.translate(0,aD);
aB.translate(0,aD);
}return[ay,az,aA,aB];
},repaint:function(){var ay=this;
var aw=ay.scale;
var au=ay.options;
var ax=ay.pointerShape(au.value);
var av=ay.elements.children[0];
var Y=ay.pointerShape(au._oldValue);
av.moveTo(ax[0]).lineTo(ax[1]).lineTo(ax[2]).lineTo(ax[3]).close();
var X=new o(av,w(au.animation,{reverse:aw.options.reverse,vertical:aw.options.vertical,oldPoints:[Y[1],Y[2]],newPoints:[ax[1],ax[2]]}));
if(au.animation.transitions===false){X.options.duration=0;
}X.setup();
X.play();
},render:function(){var av=this;
var Y=new L();
var X=av.getElementOptions();
var au=new ad({stroke:X.stroke,fill:X.fill});
Y.append(au);
av.elements=Y;
return Y;
}});
var aj=F.Animation.extend({init:function(X,Y){F.Animation.fn.init.call(this,X,Y);
Y=this.options;
Y.duration=V.max(V.abs(Y.newAngle-Y.oldAngle)/Y.duration*1000,1);
},options:{easing:Q,duration:f},step:function(av){var Y=this;
var au=Y.options;
var X=N(au.oldAngle,au.newAngle,av);
Y.element.transform(H.transform().rotate(X,au.center));
}});
F.AnimationFactory.current.register(ag,aj);
var j=F.Animation.extend({options:{easing:Q,duration:R},setup:function(){var aw=this.options;
var av=aw.margin;
var Y=aw.from;
var ax=aw.to;
var X=aw.vertical?"x1":"y1";
if(aw.mirror==aw.vertical){Y[X]-=av;
ax[X]-=av;
}else{Y[X]+=av;
ax[X]+=av;
}var au=this.fromScale=new ae(Y.x1,Y.y1);
var ay=this.toScale=new ae(ax.x1,ax.y1);
if(aw.duration!==0){aw.duration=V.max(au.distanceTo(ay)/aw.duration*1000,1);
}},step:function(X){var Y=N(this.fromScale.x,this.toScale.x,X);
var au=N(this.fromScale.y,this.toScale.y,X);
this.element.transform(H.transform().translate(Y,au));
}});
F.AnimationFactory.current.register(h,j);
var o=F.Animation.extend({options:{easing:Q,speed:R},setup:function(){var aw=this.options;
var au=aw.newPoints;
var av=aw.oldPoints;
var X=this.axis=aw.vertical?at:ar;
var ax=this.to=au[0][X];
var Y=this.from=av[0][X];
if(aw.duration!==0){aw.duration=V.max(V.abs(ax-Y)/aw.speed*1000,1);
}this._set(Y);
},step:function(X){var Y=N(this.from,this.to,X);
this._set(Y);
},_set:function(au){var Y="set"+this.axis.toUpperCase();
var X=this.options.newPoints;
X[0][Y](au);
X[1][Y](au);
}});
F.AnimationFactory.current.register(m,o);
function c(av,ax){var aw=av.box;
var aB=av.children[0].box;
var Y=ax.border||{};
var X=ax.background||"";
var au=new L();
var ay,az,aC;
aC=ad.fromRect(new al([aw.x1,aw.y1],[aw.width(),aw.height()]),{stroke:{}});
var aA=new an(av.text,new ae(aB.x1,aB.y1),{font:ax.font,fill:{color:ax.color}});
az=d(aA.bbox().clone(),ax.padding);
ay=ad.fromRect(az,{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType,lineJoin:"round",lineCap:"round"},fill:{color:X}});
au.append(aC);
au.append(ay);
au.append(aA);
return au;
}function J(av,au,Y){var X=D(av.from)?av.from:Z;
var aw=D(av.to)?av.to:W;
av.from=V.max(V.min(aw,X),au);
av.to=V.min(V.max(aw,X),Y);
return av;
}function d(X,aw){var Y=X.getOrigin();
var au=X.getSize();
var av=K(aw);
X.setOrigin([Y.x-av.left,Y.y-av.top]);
X.setSize([au.width+(av.left+av.right),au.height+(av.top+av.bottom)]);
return X;
}function e(X,au){var Y=K(au);
Y.left=-Y.left;
Y.top=-Y.top;
Y.right=-Y.right;
Y.bottom=-Y.bottom;
return d(X,Y);
}v.ui.plugin(ah);
v.ui.plugin(S);
v.ExportMixin.extend(G.fn);
w(v,{Gauge:G,RadialPointer:ai,LinearPointer:T,ArrowLinearPointer:i,BarLinearPointer:n,LinearScale:U,RadialScale:ak,LinearGauge:S,RadialGauge:ah});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
