(function(b,a){a("util/main",["kendo.core"],b);
}(function(){(function(){var q=Math,n=window.kendo,f=n.deepExtend;
var i=q.PI/180,r=Number.MAX_VALUE,u=-Number.MAX_VALUE,N="undefined";
function g(P){return typeof P!==N;
}function G(R,Q){var P=x(Q);
return q.round(R*P)/P;
}function x(P){if(P){return q.pow(10,P);
}else{return 1;
}}function p(R,Q,P){return q.max(q.min(R,P),Q);
}function y(P){return P*i;
}function h(P){return P/i;
}function l(P){return typeof P==="number"&&!isNaN(P);
}function O(Q,P){return g(Q)?Q:P;
}function K(P){return P*P;
}function w(Q){var R=[];
for(var P in Q){R.push(P+Q[P]);
}return R.sort().join("");
}function j(R){var P=2166136261;
for(var Q=0;
Q<R.length;
++Q){P+=(P<<1)+(P<<4)+(P<<7)+(P<<8)+(P<<24);
P^=R.charCodeAt(Q);
}return P>>>0;
}function k(P){return j(w(P));
}var v=Date.now;
if(!v){v=function(){return new Date().getTime();
};
}function c(P){var R=P.length,Q,T=r,S=u;
for(Q=0;
Q<R;
Q++){S=q.max(S,P[Q]);
T=q.min(T,P[Q]);
}return{min:T,max:S};
}function e(P){return c(P).min;
}function d(P){return c(P).max;
}function J(P){return H(P).min;
}function I(P){return H(P).max;
}function H(P){var T=r,S=u;
for(var Q=0,R=P.length;
Q<R;
Q++){var U=P[Q];
if(U!==null&&isFinite(U)){T=q.min(T,U);
S=q.max(S,U);
}}return{min:T===r?undefined:T,max:S===u?undefined:S};
}function o(P){if(P){return P[P.length-1];
}}function a(P,Q){P.push.apply(P,Q);
return P;
}function E(P){return n.template(P,{useWithBlock:false,paramName:"d"});
}function A(P,Q){return g(Q)&&Q!==null?" "+P+"='"+Q+"' ":"";
}function z(P){var R="";
for(var Q=0;
Q<P.length;
Q++){R+=A(P[Q][0],P[Q][1]);
}return R;
}function D(P){var R="";
for(var Q=0;
Q<P.length;
Q++){var S=P[Q][1];
if(g(S)){R+=P[Q][0]+":"+S+";";
}}if(R!==""){return R;
}}function C(P){if(typeof P!=="string"){P+="px";
}return P;
}function B(R){var S=[];
if(R){var Q=n.toHyphens(R).split("-");
for(var P=0;
P<Q.length;
P++){S.push("k-pos-"+Q[P]);
}}return S.join(" ");
}function m(P){return P===""||P===null||P==="none"||P==="transparent"||!g(P);
}function b(Q){var P={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var S=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var R="";
while(Q>0){if(Q<S[0]){S.shift();
}else{R+=P[S[0]];
Q-=S[0];
}}return R;
}function F(S){S=S.toLowerCase();
var P={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var U=0,R=0;
for(var Q=0;
Q<S.length;
++Q){var T=P[S.charAt(Q)];
if(!T){return null;
}U+=T;
if(T>R){U-=2*R;
}R=T;
}return U;
}function s(Q){var P=Object.create(null);
return function(){var S="";
for(var R=arguments.length;
--R>=0;
){S+=":"+arguments[R];
}if(S in P){return P[S];
}return Q.apply(this,arguments);
};
}function L(T){var S=[],P=0,R=T.length,U,Q;
while(P<R){U=T.charCodeAt(P++);
if(U>=55296&&U<=56319&&P<R){Q=T.charCodeAt(P++);
if((Q&64512)==56320){S.push(((U&1023)<<10)+(Q&1023)+65536);
}else{S.push(U);
P--;
}}else{S.push(U);
}}return S;
}function M(P){return P.map(function(R){var Q="";
if(R>65535){R-=65536;
Q+=String.fromCharCode(R>>>10&1023|55296);
R=56320|R&1023;
}Q+=String.fromCharCode(R);
return Q;
}).join("");
}function t(P,Q){if(P.length<2){return P.slice();
}function R(T,V){var Y=[],U=0,W=0,X=0;
while(U<T.length&&W<V.length){if(Q(T[U],V[W])<=0){Y[X++]=T[U++];
}else{Y[X++]=V[W++];
}}if(U<T.length){Y.push.apply(Y,T.slice(U));
}if(W<V.length){Y.push.apply(Y,V.slice(W));
}return Y;
}return function S(T){if(T.length<=1){return T;
}var V=Math.floor(T.length/2);
var U=T.slice(0,V);
var W=T.slice(V);
U=S(U);
W=S(W);
return R(U,W);
}(P);
}f(n,{util:{MAX_NUM:r,MIN_NUM:u,append:a,arrayLimits:c,arrayMin:e,arrayMax:d,defined:g,deg:h,hashKey:j,hashObject:k,isNumber:l,isTransparent:m,last:o,limitValue:p,now:v,objectKey:w,round:G,rad:y,renderAttr:A,renderAllAttr:z,renderPos:B,renderSize:C,renderStyle:D,renderTemplate:E,sparseArrayLimits:H,sparseArrayMin:J,sparseArrayMax:I,sqr:K,valueOrDefault:O,romanToArabic:F,arabicToRoman:b,memoize:s,ucs2encode:M,ucs2decode:L,mergeSort:t}});
n.drawing.util=n.util;
n.dataviz.util=n.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/text-metrics",["kendo.core","util/main"],b);
}(function(){(function(a){var e=document,f=window.kendo,b=f.Class,k=f.util,d=k.defined;
var h=b.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,q){var o=this,p=o._map,m={key:n,value:q};
p[n]=m;
if(!o._head){o._head=o._tail=m;
}else{o._tail.newer=m;
m.older=o._tail;
o._tail=m;
}if(o._length>=o._size){p[o._head.key]=null;
o._head=o._head.newer;
o._head.older=null;
}else{o._length++;
}},get:function(n){var o=this,m=o._map[n];
if(m){if(m===o._head&&m!==o._tail){o._head=m.newer;
o._head.older=null;
}if(m!==o._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=o._tail;
m.newer=null;
o._tail.newer=m;
o._tail=m;
}return m.value;
}}});
var c=a("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function l(){return{width:0,height:0,baseline:0};
}var j=b.extend({init:function(m){this._cache=new h(1000);
this._initOptions(m);
},options:{baselineMarkerSize:1},measure:function(v,t,n){if(!v){return l();
}var u=k.objectKey(t),p=k.hashKey(v+u),o=this._cache.get(p);
if(o){return o;
}var s=l();
var r=n?n:c;
var m=this._baselineMarker().cloneNode(false);
for(var q in t){var w=t[q];
if(d(w)){r.style[q]=w;
}}a(r).text(v);
r.appendChild(m);
e.body.appendChild(r);
if((v+"").length){s.width=r.offsetWidth-this.options.baselineMarkerSize;
s.height=r.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(p,s);
}r.parentNode.removeChild(r);
return s;
},_baselineMarker:function(){return a("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
j.current=new j();
function i(o,n,m){return j.current.measure(o,n,m);
}function g(o,m){var p=[];
if(o.length>0&&document.fonts){try{p=o.map(function(q){return document.fonts.load(q);
});
}catch(n){f.logToConsole(n);
}Promise.all(p).then(m,m);
}else{m();
}}f.util.TextMetrics=j;
f.util.LRUCache=h;
f.util.loadFonts=g;
f.util.measureText=i;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/base64",["util/main"],b);
}(function(){(function(){var e=window.kendo,a=e.deepExtend,d=String.fromCharCode;
var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function b(p){var q="";
var g,h,j,k,l,m,n;
var o=0;
p=c(p);
while(o<p.length){g=p.charCodeAt(o++);
h=p.charCodeAt(o++);
j=p.charCodeAt(o++);
k=g>>2;
l=(g&3)<<4|h>>4;
m=(h&15)<<2|j>>6;
n=j&63;
if(isNaN(h)){m=n=64;
}else{if(isNaN(j)){n=64;
}}q=q+f.charAt(k)+f.charAt(l)+f.charAt(m)+f.charAt(n);
}return q;
}function c(j){var k="";
for(var h=0;
h<j.length;
h++){var g=j.charCodeAt(h);
if(g<128){k+=d(g);
}else{if(g<2048){k+=d(192|g>>>6);
k+=d(128|g&63);
}else{if(g<65536){k+=d(224|g>>>12);
k+=d(128|g>>>6&63);
k+=d(128|g&63);
}}}}return k;
}a(e.util,{encodeBase64:b,encodeUTF8:c});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("mixins/observers",["kendo.core"],b);
}(function(){(function(a){var e=Math,d=window.kendo,b=d.deepExtend,c=a.inArray;
var f={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(g){if(!this._observers){this._observers=[g];
}else{this._observers.push(g);
}return this;
},removeObserver:function(g){var i=this.observers();
var h=c(g,i);
if(h!=-1){i.splice(h,1);
}return this;
},trigger:function(i,g){var k=this._observers;
var j;
var h;
if(k&&!this._suspended){for(h=0;
h<k.length;
h++){j=k[h];
if(j[i]){j[i](g);
}}}return this;
},optionsChange:function(g){g=g||{};
g.element=this;
this.trigger("optionsChange",g);
},geometryChange:function(){this.trigger("geometryChange",{element:this});
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=e.max((this._suspended||0)-1,0);
return this;
},_observerField:function(g,h){if(this[g]){this[g].removeObserver(this);
}this[g]=h;
h.addObserver(this);
}};
b(d,{mixins:{ObserversMixin:f}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.stock",["kendo.dataviz.chart"],b);
}(function(){var a={id:"dataviz.stockchart",name:"StockChart",category:"dataviz",description:"StockChart widget and associated financial series.",depends:["dataviz.chart"]};
(function(b,I){var r=window.kendo,g=r.Class,A=r.Observable,l=r.deepExtend,v=Math,B=b.proxy,J=r.util,s=J.last,C=J.renderTemplate,k=r.dataviz,m=J.defined,q=k.filterSeriesByType,F=r.template,f=k.ui.Chart,D=k.Selection,c=k.addDuration,t=J.limitValue,u=k.lteDateIndex,G=k.toDate,H=k.toTime;
var d=28,e="change",j="k-",n="drag",o="dragEnd",y="_navigator",x=y,p=k.EQUALLY_SPACED_SERIES,L=3,K="zoom",M="zoomEnd";
var E=f.extend({init:function(N,O){b(N).addClass(j+"chart");
f.fn.init.call(this,N,O);
},_applyDefaults:function(O,Q){var N=this,R=N.element.width()||k.DEFAULT_WIDTH;
var P={seriesDefaults:{categoryField:O.dateField},axisDefaults:{categoryAxis:{name:"default",majorGridLines:{visible:false},labels:{step:2},majorTicks:{visible:false},maxDateGroups:v.floor(R/d)}}};
if(Q){Q=l({},Q,P);
}w.setup(O,Q);
f.fn._applyDefaults.call(N,O,Q);
},setOptions:function(N){this._destroyNavigator();
f.fn.setOptions.call(this,N);
},_initDataSource:function(W){var U=W||{},N=U.dataSource,R=N&&N.serverFiltering,S=[].concat(U.categoryAxis)[0],T=U.navigator||{},V=T.select,Q=V&&V.from&&V.to,P,O;
if(R&&Q){P=[].concat(N.filter||[]);
O=new k.DateCategoryAxis(l({baseUnit:"fit"},S,{categories:[V.from,V.to]}));
N.filter=w.buildFilter(O.range().min,V.to).concat(P);
}f.fn._initDataSource.call(this,W);
},options:{name:"StockChart",dateField:"date",axisDefaults:{categoryAxis:{type:"date",baseUnit:"fit",justified:true},valueAxis:{narrowRange:true,labels:{format:"C"}}},navigator:{select:{},seriesDefaults:{markers:{visible:false},tooltip:{visible:true,template:"#= kendo.toString(category, 'd') #"},line:{width:2}},hint:{},visible:true},tooltip:{visible:true},legend:{visible:false}},_resize:function(){var N=this.options.transitions;
this.options.transitions=false;
this._fullRedraw();
this.options.transitions=N;
},_redraw:function(){var N=this,O=N._navigator;
if(!this._dirty()&&O&&O.dataSource){O.redrawSlaves();
}else{N._fullRedraw();
}},_dirty:function(){var O=this.options;
var P=[].concat(O.series,O.navigator.series);
var Q=b.grep(P,function(R){return R&&R.visible;
}).length;
var N=this._seriesCount!==Q;
this._seriesCount=Q;
return N;
},_fullRedraw:function(){var N=this,O=N._navigator;
if(!O){O=N._navigator=N.navigator=new w(N);
}O._setRange();
f.fn._redraw.call(N);
O._initSelection();
},_onDataChanged:function(){var N=this;
f.fn._onDataChanged.call(N);
N._dataBound=true;
},_bindCategoryAxis:function(O,T,P){var R=this,Q=R.options.categoryAxis,N=Q.length,S;
f.fn._bindCategoryAxis.apply(this,arguments);
if(O.name===x){while(P<N){S=Q[P++];
if(S.pane==y){S.categories=O.categories;
}}}},_trackSharedTooltip:function(O){var N=this,Q=N._plotArea,P=Q.paneByPoint(O);
if(P&&P.options.name===y){N._unsetActivePoint();
}else{f.fn._trackSharedTooltip.call(N,O);
}},_destroyNavigator:function(){this._navigator.destroy();
this._navigator=null;
},destroy:function(){this._destroyNavigator();
f.fn.destroy.call(this);
}});
var w=A.extend({init:function(N){var O=this;
O.chart=N;
O.options=l({},O.options,N.options.navigator);
O._initDataSource();
if(!m(O.options.hint.visible)){O.options.hint.visible=O.options.visible;
}N.bind(n,B(O._drag,O));
N.bind(o,B(O._dragEnd,O));
N.bind(K,B(O._zoom,O));
N.bind(M,B(O._zoomEnd,O));
},options:{},_initDataSource:function(){var P=this,Q=P.options,N=Q.autoBind,O=Q.dataSource;
if(!m(N)){N=P.chart.options.autoBind;
}P._dataChangedHandler=B(P._onDataChanged,P);
if(O){P.dataSource=r.data.DataSource.create(O).bind(e,P._dataChangedHandler);
if(N){P.dataSource.fetch();
}}},_onDataChanged:function(){var U=this,Q=U.chart,W=Q.options.series,X,Y=W.length,P=Q.options.categoryAxis,O,N=P.length,T=U.dataSource.view(),S,R,V;
for(X=0;
X<Y;
X++){S=W[X];
if(S.axis==x&&Q._isBindable(S)){S.data=T;
}}for(O=0;
O<N;
O++){R=P[O];
if(R.pane==y){if(R.name==x){Q._bindCategoryAxis(R,T,O);
V=R.categories;
}else{R.categories=V;
}}}if(Q._model){U.redraw();
U._setRange();
if(!Q.options.dataSource||Q.options.dataSource&&Q._dataBound){U.redrawSlaves();
}}},destroy:function(){var O=this,N=O.dataSource;
if(N){N.unbind(e,O._dataChangeHandler);
}if(O.selection){O.selection.destroy();
}},redraw:function(){this._redrawSelf();
this._initSelection();
},_initSelection:function(){var U=this,P=U.chart,V=U.options,N=U.mainAxis(),O=h(N),W=N.range(),T=W.min,S=W.max,R=N.options.categories,X=U.options.select,Y=U.selection,Q=G(X.from),Z=G(X.to);
if(R.length===0){return;
}if(Y){Y.destroy();
Y.wrapper.remove();
}O.box=N.box;
Y=U.selection=new D(P,O,{min:T,max:S,from:Q||T,to:Z||S,selectStart:b.proxy(U._selectStart,U),select:b.proxy(U._select,U),selectEnd:b.proxy(U._selectEnd,U),mousewheel:J.valueOrDefault(X.mousewheel,{zoom:"left"}),visible:V.visible});
if(V.hint.visible){U.hint=new z(P.element,{min:T,max:S,template:V.hint.template,format:V.hint.format});
}},_setRange:function(){var R=this.chart._createPlotArea(true);
var N=R.namedCategoryAxes[x];
var S=N.datesRange();
var Q=S.min;
var P=S.max;
var T=this.options.select||{};
var O=G(T.from)||Q;
if(O<Q){O=Q;
}var U=G(T.to)||P;
if(U>P){U=P;
}this.options.select=l({},T,{from:O,to:U});
this.filterAxes();
},_redrawSelf:function(O){var N=this.chart._plotArea;
if(N){N.redraw(s(N.panes),O);
}},redrawSlaves:function(){var O=this,N=O.chart,P=N._plotArea,Q=P.panes.slice(0,-1);
P.srcSeries=N.options.series;
P.redraw(Q);
},_drag:function(R){var U=this,O=U.chart,P=O._eventCoordinates(R.originalEvent),V=U.mainAxis(),W=V.datesRange(),T=V.pane.box.containsPoint(P),N=O._plotArea.categoryAxis,X=R.axisRanges[N.options.name],Y=U.options.select,Z=U.selection,Q,S,aa;
if(!X||T||!Z){return;
}if(Y.from&&Y.to){Q=H(Y.to)-H(Y.from);
}else{Q=H(Z.options.to)-H(Z.options.from);
}S=G(t(H(X.min),W.min,H(W.max)-Q));
aa=G(t(H(S)+Q,H(W.min)+Q,W.max));
U.options.select={from:S,to:aa};
if(U._liveDrag()){U.filterAxes();
U.redrawSlaves();
}Z.set(S,aa);
U.showHint(S,aa);
},_dragEnd:function(){var N=this;
N.filterAxes();
N.filterDataSource();
N.redrawSlaves();
if(N.hint){N.hint.hide();
}},_liveDrag:function(){var R=r.support,Q=R.touch,N=R.browser,O=N.mozilla,P=N.msie&&N.version<9;
return !Q&&!O&&!P;
},readSelection:function(){var O=this,P=O.selection,Q=P.options,N=O.options.select;
N.from=Q.from;
N.to=Q.to;
},filterAxes:function(){var S=this,T=S.options.select||{},P=S.chart,N=P.options.categoryAxis,Q=T.from,U=T.to,R,O;
for(R=0;
R<N.length;
R++){O=N[R];
if(O.pane!==y){O.min=G(Q);
O.max=G(U);
}}},filterDataSource:function(){var R=this,S=R.options.select||{},O=R.chart,P=O.dataSource,Q=P&&P.options.serverFiltering,N;
if(R.dataSource&&Q){N=new k.DateCategoryAxis(l({baseUnit:"fit"},O.options.categoryAxis[0],{categories:[S.from,S.to]})).options;
P.filter(w.buildFilter(c(N.min,-N.baseUnitStep,N.baseUnit),c(N.max,N.baseUnitStep,N.baseUnit)));
}},_zoom:function(R){var T=this,P=T.chart,Q=R.delta,N=P._plotArea.categoryAxis,U=T.options.select,V=T.selection,O=T.mainAxis().options.categories,S,W;
if(!V){return;
}S=u(V.options.from,O);
W=u(V.options.to,O);
R.originalEvent.preventDefault();
if(v.abs(Q)>1){Q*=L;
}if(W-S>1){V.expand(Q);
T.readSelection();
}else{N.options.min=U.from;
U.from=N.scaleRange(-R.delta).min;
}if(!r.support.touch){T.filterAxes();
T.redrawSlaves();
}V.set(U.from,U.to);
T.showHint(T.options.select.from,T.options.select.to);
},_zoomEnd:function(N){this._dragEnd(N);
},showHint:function(O,R){var P=this,N=P.chart,Q=N._plotArea;
if(P.hint){P.hint.show(O,R,Q.backgroundBox());
}},_selectStart:function(O){var N=this.chart;
N._selectStart.call(N,O);
},_select:function(O){var P=this,N=P.chart;
P.showHint(O.from,O.to);
N._select.call(N,O);
},_selectEnd:function(O){var P=this,N=P.chart;
if(P.hint){P.hint.hide();
}P.readSelection();
P.filterAxes();
P.filterDataSource();
P.redrawSlaves();
N._selectEnd.call(N,O);
},mainAxis:function(){var N=this.chart._plotArea;
if(N){return N.namedCategoryAxes[x];
}},select:function(N,P){var O=this.options.select;
if(N&&P){O.from=G(N);
O.to=G(P);
this.filterAxes();
this.filterDataSource();
this.redrawSlaves();
this.selection.set(N,P);
}return{from:O.from,to:O.to};
}});
w.setup=function(O,R){O=O||{};
R=R||{};
if(O.__navi){return;
}O.__navi=true;
var N=l({},R.navigator,O.navigator),Q=O.panes=[].concat(O.panes),P=l({},N.pane,{name:y});
if(!N.visible){P.visible=false;
P.height=0.1;
}Q.push(P);
w.attachAxes(O,N);
w.attachSeries(O,N,R);
};
w.attachAxes=function(S,R){var O,V,T=R.series||[];
O=S.categoryAxis=[].concat(S.categoryAxis);
V=S.valueAxis=[].concat(S.valueAxis);
var P=q(T,p);
var Q=P.length===0;
var N=l({type:"date",pane:y,roundToBaseUnit:!Q,justified:Q,_collapse:false,majorTicks:{visible:true},tooltip:{visible:false},labels:{step:1},autoBind:!R.dataSource,autoBaseUnitSteps:{minutes:[1],hours:[1,2],days:[1,2],weeks:[],months:[1],years:[1]},_overlap:true});
var U=R.categoryAxis;
O.push(l({},N,{maxDateGroups:200},U,{name:x,title:null,baseUnit:"fit",baseUnitStep:"auto",labels:{visible:false},majorTicks:{visible:false}}),l({},N,U,{name:x+"_labels",maxDateGroups:20,baseUnitStep:"auto",plotBands:[],autoBaseUnitSteps:{minutes:[]}}),l({},N,U,{name:x+"_ticks",maxDateGroups:200,majorTicks:{width:0.5},plotBands:[],title:null,labels:{visible:false,mirror:true}}));
V.push(l({name:x,pane:y,majorGridLines:{visible:false},visible:false},R.valueAxis));
};
w.attachSeries=function(R,Q,U){var S=R.series=R.series||[],P=[].concat(Q.series||[]),T=U.seriesColors,N=Q.seriesDefaults,O;
for(O=0;
O<P.length;
O++){S.push(l({color:T[O%T.length],categoryField:Q.dateField,visibleInLegend:false,tooltip:{visible:false}},N,P[O],{axis:x,categoryAxis:x,autoBind:!Q.dataSource}));
}};
w.buildFilter=function(N,O){return[{field:"Date",operator:"gte",value:G(N)},{field:"Date",operator:"lt",value:G(O)}];
};
var z=g.extend({init:function(N,P){var O=this;
O.options=l({},O.options,P);
O.container=N;
O.chartPadding={top:parseInt(N.css("paddingTop"),10),left:parseInt(N.css("paddingLeft"),10)};
O.template=O.template;
if(!O.template){O.template=O.template=C("<div class='"+j+"navigator-hint' style='display: none; position: absolute; top: 1px; left: 1px;'><div class='"+j+"tooltip "+j+"chart-tooltip'>&nbsp;</div><div class='"+j+"scroll' /></div>");
}O.element=b(O.template()).appendTo(N);
},options:{format:"{0:d} - {1:d}",hideDelay:500},show:function(O,ac,N){var P=this,S=G(H(O)+H(ac-O)/2),V=P.options,ab=r.format(P.options.format,O,ac),ad=P.element.find("."+j+"tooltip"),Z=P.element.find("."+j+"scroll"),aa=N.width()*0.4,T=N.center().x-aa,R=N.center().x,W=R-T,X=V.max-V.min,Y=W/X,U=S-V.min,Q;
if(P._hideTimeout){clearTimeout(P._hideTimeout);
}if(!P._visible){P.element.stop(false,true).css("visibility","hidden").show();
P._visible=true;
}if(V.template){Q=F(V.template);
ab=Q({from:O,to:ac});
}ad.html(ab).css({left:N.center().x-ad.outerWidth()/2,top:N.y1});
Z.css({width:aa,left:T+U*Y,top:N.y1+parseInt(ad.css("margin-top"),10)+parseInt(ad.css("border-top-width"),10)+ad.height()/2});
P.element.css("visibility","visible");
},hide:function(){var N=this;
if(N._hideTimeout){clearTimeout(N._hideTimeout);
}N._hideTimeout=setTimeout(function(){N._visible=false;
N.element.fadeOut("slow");
},N.options.hideDelay);
}});
function i(){}function h(N){i.prototype=N;
return new i();
}k.ui.plugin(E);
l(k,{Navigator:w});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
