CREATE TABLE [dbo].[MAF_MEISTER_Enews] (
    [Client_ID]         INT           NOT NULL,
    [ClientName]        VARCHAR (7)   NOT NULL,
    [EmailID]           INT           NOT NULL,
    [EmailAddress]      VARCHAR (255) NOT NULL,
    [Title]             VARCHAR (50)  NULL,
    [FirstName]         VARCHAR (50)  NULL,
    [LastName]          VARCHAR (50)  NULL,
    [FullName]          VARCHAR (50)  NULL,
    [Company]           VARCHAR (100) NULL,
    [Occupation]        VARCHAR (50)  NULL,
    [Address]           VARCHAR (255) NULL,
    [Address2]          VARCHAR (255) NULL,
    [City]              VARCHAR (50)  NULL,
    [State]             VARCHAR (50)  NULL,
    [Zip]               VARCHAR (50)  NULL,
    [Country]           VARCHAR (50)  NULL,
    [Voice]             VARCHAR (50)  NULL,
    [Mobile]            VARCHAR (50)  NULL,
    [Fax]               VARCHAR (50)  NULL,
    [Website]           VARCHAR (50)  NULL,
    [Age]               VARCHAR (50)  NULL,
    [Income]            VARCHAR (50)  NULL,
    [Gender]            VARCHAR (50)  NULL,
    [User1]             VARCHAR (255) NULL,
    [User2]             VARCHAR (255) NULL,
    [User3]             VARCHAR (255) NULL,
    [User4]             VARCHAR (255) NULL,
    [User5]             VARCHAR (255) NULL,
    [User6]             VARCHAR (255) NULL,
    [Birthdate]         DATETIME      NULL,
    [UserEvent1]        VARCHAR (50)  NULL,
    [UserEvent1Date]    DATETIME      NULL,
    [UserEvent2]        VARCHAR (50)  NULL,
    [UserEvent2Date]    DATETIME      NULL,
    [Notes]             VARCHAR (30)  NULL,
    [CreatedOn]         DATETIME      NULL,
    [LastChanged]       DATETIME      NULL,
    [FormatTypeCode]    VARCHAR (5)   NOT NULL,
    [SubscribeTypeCode] VARCHAR (50)  NULL,
    [GroupId]           INT           NOT NULL,
    [SUDF_GID]          INT           NULL,
    [tmp_EmailID]       INT           NULL,
    [Business]          VARCHAR (500) NULL,
    [BUSINESSTEXT]      VARCHAR (500) NULL,
    [CAT]               VARCHAR (500) NULL,
    [COUNTY]            VARCHAR (500) NULL,
    [DEMO1]             VARCHAR (500) NULL,
    [DEMO10]            VARCHAR (500) NULL,
    [DEMO11]            VARCHAR (500) NULL,
    [DEMO12]            VARCHAR (500) NULL,
    [DEMO2]             VARCHAR (500) NULL,
    [DEMO3]             VARCHAR (500) NULL,
    [DEMO31]            VARCHAR (500) NULL,
    [DEMO32]            VARCHAR (500) NULL,
    [DEMO33]            VARCHAR (500) NULL,
    [DEMO34]            VARCHAR (500) NULL,
    [DEMO35]            VARCHAR (500) NULL,
    [DEMO36]            VARCHAR (500) NULL,
    [DEMO39]            VARCHAR (500) NULL,
    [DEMO4]             VARCHAR (500) NULL,
    [DEMO5]             VARCHAR (500) NULL,
    [DEMO6]             VARCHAR (500) NULL,
    [DEMO7]             VARCHAR (500) NULL,
    [DEMO9]             VARCHAR (500) NULL,
    [department]        VARCHAR (500) NULL,
    [FORZIP]            VARCHAR (500) NULL,
    [FUNCTION]          VARCHAR (500) NULL,
    [FUNCTIONTEXT]      VARCHAR (500) NULL,
    [Plus4]             VARCHAR (500) NULL,
    [promocode]         VARCHAR (500) NULL,
    [PUBCODE]           VARCHAR (500) NULL,
    [PublicationCode]   VARCHAR (500) NULL,
    [qdate]             VARCHAR (500) NULL,
    [SOURCE]            VARCHAR (500) NULL,
    [SubscriberID]      VARCHAR (500) NULL,
    [subsrc]            VARCHAR (500) NULL,
    [VERIFY]            VARCHAR (500) NULL,
    [XACT]              VARCHAR (500) NULL
);



