CREATE TABLE [dbo].[MAF_UPI_Enews] (
    [Client_ID]         INT              NOT NULL,
    [ClientName]        VARCHAR (3)      NOT NULL,
    [EmailID]           INT              NOT NULL,
    [EmailAddress]      VARCHAR (255)    NOT NULL,
    [Title]             VARCHAR (50)     NULL,
    [FirstName]         VARCHAR (50)     NULL,
    [LastName]          VARCHAR (50)     NULL,
    [FullName]          VARCHAR (50)     NULL,
    [Company]           VARCHAR (100)    NULL,
    [Occupation]        VARCHAR (50)     NULL,
    [Address]           VARCHAR (255)    NULL,
    [Address2]          VARCHAR (255)    NULL,
    [City]              VARCHAR (50)     NULL,
    [State]             VARCHAR (50)     NULL,
    [Zip]               VARCHAR (50)     NULL,
    [Country]           VARCHAR (50)     NULL,
    [Voice]             VARCHAR (50)     NULL,
    [Mobile]            VARCHAR (50)     NULL,
    [Fax]               VARCHAR (50)     NULL,
    [Website]           VARCHAR (50)     NULL,
    [Age]               VARCHAR (50)     NULL,
    [Income]            VARCHAR (50)     NULL,
    [Gender]            VARCHAR (50)     NULL,
    [User1]             VARCHAR (255)    NULL,
    [User2]             VARCHAR (255)    NULL,
    [User3]             VARCHAR (255)    NULL,
    [User4]             VARCHAR (255)    NULL,
    [User5]             VARCHAR (255)    NULL,
    [User6]             VARCHAR (255)    NULL,
    [Birthdate]         DATETIME         NULL,
    [UserEvent1]        VARCHAR (50)     NULL,
    [UserEvent1Date]    DATETIME         NULL,
    [UserEvent2]        VARCHAR (50)     NULL,
    [UserEvent2Date]    DATETIME         NULL,
    [Notes]             VARCHAR (30)     NULL,
    [CreatedOn]         DATETIME         NULL,
    [LastChanged]       DATETIME         NULL,
    [FormatTypeCode]    VARCHAR (5)      NOT NULL,
    [SubscribeTypeCode] VARCHAR (50)     NULL,
    [GroupId]           INT              NOT NULL,
    [SUDF_GID]          INT              NULL,
    [tmp_EmailID]       INT              NULL,
    [BADGE]             VARCHAR (500)    NULL,
    [BATCH]             VARCHAR (500)    NULL,
    [BUSINESS]          VARCHAR (500)    NULL,
    [BUSINESSTEXT]      VARCHAR (500)    NULL,
    [CAT]               VARCHAR (500)    NULL,
    [DEMO1]             VARCHAR (500)    NULL,
    [DEMO10]            VARCHAR (500)    NULL,
    [DEMO14]            VARCHAR (500)    NULL,
    [DEMO14TEXT]        VARCHAR (500)    NULL,
    [DEMO31]            VARCHAR (500)    NULL,
    [DEMO32]            VARCHAR (500)    NULL,
    [DEMO33]            VARCHAR (500)    NULL,
    [DEMO34]            VARCHAR (500)    NULL,
    [DEMO35]            VARCHAR (500)    NULL,
    [DEMO36]            VARCHAR (500)    NULL,
    [DEMO39]            VARCHAR (500)    NULL,
    [DEMO5]             VARCHAR (500)    NULL,
    [DEMO7]             VARCHAR (500)    NULL,
    [EMPLOY]            VARCHAR (500)    NULL,
    [EXPDATE]           VARCHAR (500)    NULL,
    [EXT]               VARCHAR (500)    NULL,
    [FORZIP]            VARCHAR (500)    NULL,
    [FUNCTION]          VARCHAR (500)    NULL,
    [FUNCTIONTEXT]      VARCHAR (500)    NULL,
    [HISTBATCH]         VARCHAR (500)    NULL,
    [HOWDIDYOUHEAR]     VARCHAR (500)    NULL,
    [HOWDIDYOUHEARTXT]  VARCHAR (500)    NULL,
    [JOB]               VARCHAR (500)    NULL,
    [KEYSOURCE]         VARCHAR (500)    NULL,
    [MAILSTOP]          VARCHAR (500)    NULL,
    [OPENS]             VARCHAR (500)    NULL,
    [ORIGSSRC]          VARCHAR (500)    NULL,
    [PA1EMAIL]          VARCHAR (500)    NULL,
    [PA1FNAME]          VARCHAR (500)    NULL,
    [PA1FUNCTION]       VARCHAR (500)    NULL,
    [PA1FUNCTXT]        VARCHAR (500)    NULL,
    [PA1LNAME]          VARCHAR (500)    NULL,
    [PA2EMAIL]          VARCHAR (500)    NULL,
    [PA2FNAME]          VARCHAR (500)    NULL,
    [PA2FUNCTION]       VARCHAR (500)    NULL,
    [PA2FUNCTXT]        VARCHAR (500)    NULL,
    [PA2LNAME]          VARCHAR (500)    NULL,
    [PA3EMAIL]          VARCHAR (500)    NULL,
    [PA3FNAME]          VARCHAR (500)    NULL,
    [PA3FUNCTION]       VARCHAR (500)    NULL,
    [PA3FUNCTXT]        VARCHAR (500)    NULL,
    [PA3LNAME]          VARCHAR (500)    NULL,
    [PAIDorFREE]        VARCHAR (500)    NULL,
    [PAR3C]             VARCHAR (500)    NULL,
    [PASSALONG]         VARCHAR (500)    NULL,
    [PLUS4]             VARCHAR (500)    NULL,
    [PROMOCODE]         VARCHAR (500)    NULL,
    [PUBLICATIONCODE]   VARCHAR (500)    NULL,
    [QDATE]             VARCHAR (500)    NULL,
    [QSOURCE]           VARCHAR (500)    NULL,
    [RECOMMEND]         VARCHAR (500)    NULL,
    [SDN_BUSINESS]      VARCHAR (500)    NULL,
    [SDN_DEMO14]        VARCHAR (500)    NULL,
    [SDN_EMPLOY]        VARCHAR (500)    NULL,
    [SDN_FUNCTION]      VARCHAR (500)    NULL,
    [SDN_RECOMMEND]     VARCHAR (500)    NULL,
    [STATE_INT]         VARCHAR (500)    NULL,
    [STATUS]            VARCHAR (500)    NULL,
    [SUBSCRIBERID]      VARCHAR (500)    NULL,
    [SUBSCRIPTION]      VARCHAR (500)    NULL,
    [SUBSRC]            VARCHAR (500)    NULL,
    [TERMS]             VARCHAR (500)    NULL,
    [TRANSACTIONTYPE]   VARCHAR (500)    NULL,
    [VERIFY]            VARCHAR (500)    NULL,
    [XACT]              VARCHAR (500)    NULL,
    [TUDF_GID]          INT              NULL,
    [tmp_EmailID1]      INT              NULL,
    [entryID]           UNIQUEIDENTIFIER NULL,
    [PaymentStatus]     VARCHAR (500)    NULL,
    [PromoCodeDiscount] VARCHAR (500)    NULL,
    [PUB]               VARCHAR (500)    NULL,
    [PUBCODE]           VARCHAR (500)    NULL,
    [SHIPTO_ADDRESS1]   VARCHAR (500)    NULL,
    [SHIPTO_ADDRESS2]   VARCHAR (500)    NULL,
    [SHIPTO_CITY]       VARCHAR (500)    NULL,
    [SHIPTO_FORZIP]     VARCHAR (500)    NULL,
    [SHIPTO_STATE]      VARCHAR (500)    NULL,
    [SHIPTO_STATE_INT]  VARCHAR (500)    NULL,
    [SHIPTO_ZIP]        VARCHAR (500)    NULL,
    [t_AmountPaid]      VARCHAR (500)    NULL,
    [t_CardBillZip]     VARCHAR (500)    NULL,
    [t_CardNumber]      VARCHAR (500)    NULL,
    [t_CardType]        VARCHAR (500)    NULL,
    [t_City]            VARCHAR (500)    NULL,
    [t_Country]         VARCHAR (500)    NULL,
    [t_ExpirationDate]  VARCHAR (500)    NULL,
    [t_FullName]        VARCHAR (500)    NULL,
    [t_State]           VARCHAR (500)    NULL,
    [t_Street]          VARCHAR (500)    NULL,
    [t_Street2]         VARCHAR (500)    NULL,
    [t_TransactionID]   VARCHAR (500)    NULL,
    [t_Transdate]       VARCHAR (500)    NULL,
    [t_Zip]             VARCHAR (500)    NULL,
    [TOPIC]             VARCHAR (500)    NULL
);

