CREATE TABLE [dbo].[MAF_WATT_Enews] (
    [Client_ID]         INT              NOT NULL,
    [ClientName]        VARCHAR (4)      NOT NULL,
    [EmailID]           INT              NOT NULL,
    [EmailAddress]      VARCHAR (255)    NOT NULL,
    [Title]             VARCHAR (50)     NULL,
    [FirstName]         VARCHAR (50)     NULL,
    [LastName]          VARCHAR (50)     NULL,
    [FullName]          VARCHAR (50)     NULL,
    [Company]           VARCHAR (100)    NULL,
    [Occupation]        VARCHAR (50)     NULL,
    [Address]           VARCHAR (255)    NULL,
    [Address2]          VARCHAR (255)    NULL,
    [City]              VARCHAR (50)     NULL,
    [State]             VARCHAR (50)     NULL,
    [Zip]               VARCHAR (50)     NULL,
    [Country]           VARCHAR (50)     NULL,
    [Voice]             VARCHAR (50)     NULL,
    [Mobile]            VARCHAR (50)     NULL,
    [Fax]               VARCHAR (50)     NULL,
    [Website]           VARCHAR (50)     NULL,
    [Age]               VARCHAR (50)     NULL,
    [Income]            VARCHAR (50)     NULL,
    [Gender]            VARCHAR (50)     NULL,
    [User1]             VARCHAR (255)    NULL,
    [User2]             VARCHAR (255)    NULL,
    [User3]             VARCHAR (255)    NULL,
    [User4]             VARCHAR (255)    NULL,
    [User5]             VARCHAR (255)    NULL,
    [User6]             VARCHAR (255)    NULL,
    [Birthdate]         DATETIME         NULL,
    [UserEvent1]        VARCHAR (50)     NULL,
    [UserEvent1Date]    DATETIME         NULL,
    [UserEvent2]        VARCHAR (50)     NULL,
    [UserEvent2Date]    DATETIME         NULL,
    [Notes]             VARCHAR (30)     NULL,
    [CreatedOn]         DATETIME         NULL,
    [LastChanged]       DATETIME         NULL,
    [FormatTypeCode]    VARCHAR (5)      NOT NULL,
    [SubscribeTypeCode] VARCHAR (50)     NULL,
    [GroupId]           INT              NOT NULL,
    [SUDF_GID]          INT              NULL,
    [tmp_EmailID]       INT              NULL,
    [BUSINESS]          VARCHAR (500)    NULL,
    [BUSINESSTEXT]      VARCHAR (500)    NULL,
    [BUSINESSTXT]       VARCHAR (500)    NULL,
    [Date_Subscribed]   VARCHAR (500)    NULL,
    [Date_Unsubscribed] VARCHAR (500)    NULL,
    [DEMO1]             VARCHAR (500)    NULL,
    [DEMO10]            VARCHAR (500)    NULL,
    [DEMO10TEXT]        VARCHAR (500)    NULL,
    [DEMO13]            VARCHAR (500)    NULL,
    [DEMO2]             VARCHAR (500)    NULL,
    [DEMO32]            VARCHAR (500)    NULL,
    [DEMO33]            VARCHAR (500)    NULL,
    [DEMO35]            VARCHAR (500)    NULL,
    [DEMO39]            VARCHAR (500)    NULL,
    [DEMO40]            VARCHAR (500)    NULL,
    [DEMO41]            VARCHAR (500)    NULL,
    [DEMO5]             VARCHAR (500)    NULL,
    [DEMO6]             VARCHAR (500)    NULL,
    [DEMO8]             VARCHAR (500)    NULL,
    [DEMO9]             VARCHAR (500)    NULL,
    [DEPARTMENT]        VARCHAR (500)    NULL,
    [EMPLOY]            VARCHAR (500)    NULL,
    [EMPLOYTEXT]        VARCHAR (500)    NULL,
    [FORZIP]            VARCHAR (500)    NULL,
    [FUNCTION]          VARCHAR (500)    NULL,
    [FUNCTIONTEXT]      VARCHAR (500)    NULL,
    [FUNCTIONTXT]       VARCHAR (500)    NULL,
    [INDUSTRY]          VARCHAR (500)    NULL,
    [JOBTITLE]          VARCHAR (500)    NULL,
    [MAILSTOP]          VARCHAR (500)    NULL,
    [PA1EMAIL]          VARCHAR (500)    NULL,
    [PA1FNAME]          VARCHAR (500)    NULL,
    [PA1FUNCTION]       VARCHAR (500)    NULL,
    [PA1LNAME]          VARCHAR (500)    NULL,
    [PAIDorFREE]        VARCHAR (500)    NULL,
    [PASSALONG]         VARCHAR (500)    NULL,
    [PaymentStatus]     VARCHAR (500)    NULL,
    [PLUS4]             VARCHAR (500)    NULL,
    [promoCode]         VARCHAR (500)    NULL,
    [PUBLICATIONCODE]   VARCHAR (500)    NULL,
    [QDate]             VARCHAR (500)    NULL,
    [Reason]            VARCHAR (500)    NULL,
    [STATE_INT]         VARCHAR (500)    NULL,
    [Status]            VARCHAR (500)    NULL,
    [SUBSCRIPTION]      VARCHAR (500)    NULL,
    [SUBSRC]            VARCHAR (500)    NULL,
    [TRANSACTIONTYPE]   VARCHAR (500)    NULL,
    [VERIFY]            VARCHAR (500)    NULL,
    [TUDF_GID]          INT              NULL,
    [tmp_EmailID1]      INT              NULL,
    [entryID]           UNIQUEIDENTIFIER NULL,
    [Topics]            VARCHAR (500)    NULL
);

