CREATE TABLE [dbo].[MAF_CANON_Enews] (
    [Client_ID]            INT              NOT NULL,
    [ClientName]           VARCHAR (5)      NOT NULL,
    [EmailID]              INT              NOT NULL,
    [EmailAddress]         VARCHAR (255)    NOT NULL,
    [Title]                VARCHAR (50)     NULL,
    [FirstName]            VARCHAR (50)     NULL,
    [LastName]             VARCHAR (50)     NULL,
    [FullName]             VARCHAR (50)     NULL,
    [Company]              VARCHAR (100)    NULL,
    [Occupation]           VARCHAR (50)     NULL,
    [Address]              VARCHAR (255)    NULL,
    [Address2]             VARCHAR (255)    NULL,
    [City]                 VARCHAR (50)     NULL,
    [State]                VARCHAR (50)     NULL,
    [Zip]                  VARCHAR (50)     NULL,
    [Country]              VARCHAR (50)     NULL,
    [Voice]                VARCHAR (50)     NULL,
    [Mobile]               VARCHAR (50)     NULL,
    [Fax]                  VARCHAR (50)     NULL,
    [Website]              VARCHAR (50)     NULL,
    [Age]                  VARCHAR (50)     NULL,
    [Income]               VARCHAR (50)     NULL,
    [Gender]               VARCHAR (50)     NULL,
    [User1]                VARCHAR (255)    NULL,
    [User2]                VARCHAR (255)    NULL,
    [User3]                VARCHAR (255)    NULL,
    [User4]                VARCHAR (255)    NULL,
    [User5]                VARCHAR (255)    NULL,
    [User6]                VARCHAR (255)    NULL,
    [Birthdate]            DATETIME         NULL,
    [UserEvent1]           VARCHAR (50)     NULL,
    [UserEvent1Date]       DATETIME         NULL,
    [UserEvent2]           VARCHAR (50)     NULL,
    [UserEvent2Date]       DATETIME         NULL,
    [Notes]                VARCHAR (30)     NULL,
    [CreatedOn]            DATETIME         NULL,
    [LastChanged]          DATETIME         NULL,
    [FormatTypeCode]       VARCHAR (5)      NOT NULL,
    [SubscribeTypeCode]    VARCHAR (50)     NULL,
    [GroupId]              INT              NOT NULL,
    [SUDF_GID]             INT              NULL,
    [tmp_EmailID]          INT              NULL,
    [acctid]               VARCHAR (500)    NULL,
    [Andrea_list]          VARCHAR (500)    NULL,
    [AOI1]                 VARCHAR (500)    NULL,
    [AOI2]                 VARCHAR (500)    NULL,
    [AOI3]                 VARCHAR (500)    NULL,
    [BATCH]                VARCHAR (500)    NULL,
    [Both_C]               VARCHAR (500)    NULL,
    [BUSINESS]             VARCHAR (500)    NULL,
    [BUSINESSTEXT]         VARCHAR (500)    NULL,
    [BUSINESSTXT]          VARCHAR (500)    NULL,
    [CAT]                  VARCHAR (500)    NULL,
    [CategoryID]           VARCHAR (500)    NULL,
    [Code]                 VARCHAR (500)    NULL,
    [County]               VARCHAR (500)    NULL,
    [Ctry]                 VARCHAR (500)    NULL,
    [Demo05]               VARCHAR (500)    NULL,
    [Demo1]                VARCHAR (500)    NULL,
    [DEMO10]               VARCHAR (500)    NULL,
    [Demo10Text]           VARCHAR (500)    NULL,
    [DEMO11]               VARCHAR (500)    NULL,
    [DEMO11TEXT]           VARCHAR (500)    NULL,
    [DEMO13]               VARCHAR (500)    NULL,
    [DEMO14]               VARCHAR (500)    NULL,
    [DEMO15]               VARCHAR (500)    NULL,
    [Demo2]                VARCHAR (500)    NULL,
    [Demo31]               VARCHAR (500)    NULL,
    [Demo32]               VARCHAR (500)    NULL,
    [DEMO33]               VARCHAR (500)    NULL,
    [Demo34]               VARCHAR (500)    NULL,
    [Demo35]               VARCHAR (500)    NULL,
    [Demo36]               VARCHAR (500)    NULL,
    [Demo39]               VARCHAR (500)    NULL,
    [Demo5]                VARCHAR (500)    NULL,
    [DEMO7]                VARCHAR (500)    NULL,
    [DEMO8]                VARCHAR (500)    NULL,
    [DEMO9]                VARCHAR (500)    NULL,
    [DEMO9TEXT]            VARCHAR (500)    NULL,
    [EDITION]              VARCHAR (500)    NULL,
    [Effort_Code]          VARCHAR (500)    NULL,
    [EMPLOY]               VARCHAR (500)    NULL,
    [EMPLOYEES]            VARCHAR (500)    NULL,
    [EMPLOYER]             VARCHAR (500)    NULL,
    [END_PRODUCT]          VARCHAR (500)    NULL,
    [F1]                   VARCHAR (500)    NULL,
    [F2]                   VARCHAR (500)    NULL,
    [F3]                   VARCHAR (500)    NULL,
    [F4]                   VARCHAR (500)    NULL,
    [F5]                   VARCHAR (500)    NULL,
    [F6]                   VARCHAR (500)    NULL,
    [Film_Sheet_B]         VARCHAR (500)    NULL,
    [ForPre]               VARCHAR (500)    NULL,
    [FORZIP]               VARCHAR (500)    NULL,
    [FUNCTION]             VARCHAR (500)    NULL,
    [FUNCTIONTEXT]         VARCHAR (500)    NULL,
    [HISTBATCH]            VARCHAR (500)    NULL,
    [HR]                   VARCHAR (500)    NULL,
    [INDUSTRY]             VARCHAR (500)    NULL,
    [Job]                  VARCHAR (500)    NULL,
    [job_]                 VARCHAR (500)    NULL,
    [Job_Num]              VARCHAR (500)    NULL,
    [JOBT1]                VARCHAR (500)    NULL,
    [JOBT2]                VARCHAR (500)    NULL,
    [JOBT3]                VARCHAR (500)    NULL,
    [Mailstop]             VARCHAR (500)    NULL,
    [NoofTrials]           VARCHAR (500)    NULL,
    [Original_Effort_Code] VARCHAR (500)    NULL,
    [PaidOrFree]           VARCHAR (500)    NULL,
    [PAR3C]                VARCHAR (500)    NULL,
    [Pin]                  VARCHAR (500)    NULL,
    [Pipe_Profile_A]       VARCHAR (500)    NULL,
    [PLAN_TO_PURCHASE]     VARCHAR (500)    NULL,
    [Plus4]                VARCHAR (500)    NULL,
    [PRINT_Business]       VARCHAR (500)    NULL,
    [Print_Function]       VARCHAR (500)    NULL,
    [Print_Products]       VARCHAR (500)    NULL,
    [Print_Purchase]       VARCHAR (500)    NULL,
    [Print_Specify]        VARCHAR (500)    NULL,
    [PROD1]                VARCHAR (500)    NULL,
    [PRODUCT]              VARCHAR (500)    NULL,
    [pswd]                 VARCHAR (500)    NULL,
    [Pub]                  VARCHAR (500)    NULL,
    [PubCode]              VARCHAR (500)    NULL,
    [PubID]                VARCHAR (500)    NULL,
    [pubids]               VARCHAR (500)    NULL,
    [PUBLICATIONCODE]      VARCHAR (500)    NULL,
    [PURCHASE]             VARCHAR (500)    NULL,
    [QDATE]                VARCHAR (500)    NULL,
    [QSOURCE]              VARCHAR (500)    NULL,
    [reg_visitor_id]       VARCHAR (500)    NULL,
    [Responsibility]       VARCHAR (500)    NULL,
    [SECTOR]               VARCHAR (500)    NULL,
    [Source]               VARCHAR (500)    NULL,
    [Sub_Account_Number]   VARCHAR (500)    NULL,
    [SubDate]              VARCHAR (500)    NULL,
    [SUBSCR]               VARCHAR (500)    NULL,
    [Subscriber_ID]        VARCHAR (500)    NULL,
    [SubscriberID]         VARCHAR (500)    NULL,
    [SUBSCRIPTION]         VARCHAR (500)    NULL,
    [SubSrc]               VARCHAR (500)    NULL,
    [TOE1]                 VARCHAR (500)    NULL,
    [TOE2]                 VARCHAR (500)    NULL,
    [TransactionDATE]      VARCHAR (500)    NULL,
    [TRANSACTIONTYPE]      VARCHAR (500)    NULL,
    [User_Name]            VARCHAR (500)    NULL,
    [username]             VARCHAR (500)    NULL,
    [Verification_Date]    VARCHAR (500)    NULL,
    [VERIFY]               VARCHAR (500)    NULL,
    [XACT]                 VARCHAR (500)    NULL,
    [XActDate]             VARCHAR (500)    NULL,
    [TUDF_GID]             INT              NULL,
    [tmp_EmailID1]         INT              NULL,
    [entryID]              UNIQUEIDENTIFIER NULL,
    [amountpaid]           VARCHAR (500)    NULL,
    [CardNumber]           VARCHAR (500)    NULL,
    [CardType]             VARCHAR (500)    NULL,
    [Deferredamount]       VARCHAR (500)    NULL,
    [earnedamount]         VARCHAR (500)    NULL,
    [enddate]              VARCHAR (500)    NULL,
    [PaymentMethod]        VARCHAR (500)    NULL,
    [PromoCode]            VARCHAR (500)    NULL,
    [startdate]            VARCHAR (500)    NULL,
    [SubType]              VARCHAR (500)    NULL,
    [TotalSent]            VARCHAR (500)    NULL,
    [TransactionID]        VARCHAR (500)    NULL
);



