CREATE TABLE [dbo].[MAF_AB_Enews] (
    [Client_ID]         INT              NOT NULL,
    [ClientName]        VARCHAR (2)      NOT NULL,
    [EmailID]           INT              NOT NULL,
    [EmailAddress]      VARCHAR (255)    NOT NULL,
    [Title]             VARCHAR (50)     NULL,
    [FirstName]         VARCHAR (50)     NULL,
    [LastName]          VARCHAR (50)     NULL,
    [FullName]          VARCHAR (50)     NULL,
    [Company]           VARCHAR (100)    NULL,
    [Occupation]        VARCHAR (50)     NULL,
    [Address]           VARCHAR (255)    NULL,
    [Address2]          VARCHAR (255)    NULL,
    [City]              VARCHAR (50)     NULL,
    [State]             VARCHAR (50)     NULL,
    [Zip]               VARCHAR (50)     NULL,
    [Country]           VARCHAR (50)     NULL,
    [Voice]             VARCHAR (50)     NULL,
    [Mobile]            VARCHAR (50)     NULL,
    [Fax]               VARCHAR (50)     NULL,
    [Website]           VARCHAR (50)     NULL,
    [Age]               VARCHAR (50)     NULL,
    [Income]            VARCHAR (50)     NULL,
    [Gender]            VARCHAR (50)     NULL,
    [User1]             VARCHAR (255)    NULL,
    [User2]             VARCHAR (255)    NULL,
    [User3]             VARCHAR (255)    NULL,
    [User4]             VARCHAR (255)    NULL,
    [User5]             VARCHAR (255)    NULL,
    [User6]             VARCHAR (255)    NULL,
    [Birthdate]         DATETIME         NULL,
    [UserEvent1]        VARCHAR (50)     NULL,
    [UserEvent1Date]    DATETIME         NULL,
    [UserEvent2]        VARCHAR (50)     NULL,
    [UserEvent2Date]    DATETIME         NULL,
    [Notes]             VARCHAR (30)     NULL,
    [CreatedOn]         DATETIME         NULL,
    [LastChanged]       DATETIME         NULL,
    [FormatTypeCode]    VARCHAR (5)      NOT NULL,
    [SubscribeTypeCode] VARCHAR (50)     NULL,
    [GroupId]           INT              NOT NULL,
    [SUDF_GID]          INT              NULL,
    [tmp_EmailID]       INT              NULL,
    [Business]          VARCHAR (500)    NULL,
    [Demo1]             VARCHAR (500)    NULL,
    [Demo2]             VARCHAR (500)    NULL,
    [Demo3]             VARCHAR (500)    NULL,
    [Demo4]             VARCHAR (500)    NULL,
    [Demo6]             VARCHAR (500)    NULL,
    [Function]          VARCHAR (500)    NULL,
    [PAIDorFREE]        VARCHAR (500)    NULL,
    [plus4]             VARCHAR (500)    NULL,
    [Qsource]           VARCHAR (500)    NULL,
    [Segment]           VARCHAR (500)    NULL,
    [SOURCE]            VARCHAR (500)    NULL,
    [SubscriberID]      VARCHAR (500)    NULL,
    [SUBSRC]            VARCHAR (500)    NULL,
    [WebID]             VARCHAR (500)    NULL,
    [TUDF_GID]          INT              NULL,
    [tmp_EmailID1]      INT              NULL,
    [entryID]           UNIQUEIDENTIFIER NULL,
    [TOPICS]            VARCHAR (500)    NULL
);



