CREATE TABLE [dbo].[Match_TEST_2] (
    [_key_in]              INT           NULL,
    [_key_out]             INT           NULL,
    [_score]               REAL          NULL,
    [Address]              VARCHAR (255) NULL,
    [mailstop]             VARCHAR (255) NULL,
    [city]                 VARCHAR (255) NULL,
    [state]                VARCHAR (255) NULL,
    [zip]                  VARCHAR (255) NULL,
    [fname]                VARCHAR (255) NULL,
    [lname]                VARCHAR (255) NULL,
    [email]                VARCHAR (255) NULL,
    [phone]                VARCHAR (255) NULL,
    [fax]                  VARCHAR (255) NULL,
    [mobile]               VARCHAR (255) NULL,
    [company]              VARCHAR (255) NULL,
    [Address_clean]        VARCHAR (255) NULL,
    [mailstop_clean]       VARCHAR (255) NULL,
    [city_clean]           VARCHAR (255) NULL,
    [state_clean]          VARCHAR (255) NULL,
    [zip_clean]            VARCHAR (255) NULL,
    [fname_clean]          VARCHAR (255) NULL,
    [lname_clean]          VARCHAR (255) NULL,
    [email_clean]          VARCHAR (255) NULL,
    [phone_clean]          VARCHAR (255) NULL,
    [fax_clean]            VARCHAR (255) NULL,
    [mobile_clean]         VARCHAR (255) NULL,
    [_Similarity_Address]  REAL          NULL,
    [_Similarity_mailstop] REAL          NULL,
    [_Similarity_city]     REAL          NULL,
    [_Similarity_state]    REAL          NULL,
    [_Similarity_zip]      REAL          NULL,
    [_Similarity_fname]    REAL          NULL,
    [_Similarity_lname]    REAL          NULL,
    [_Similarity_email]    REAL          NULL,
    [_Similarity_phone]    REAL          NULL,
    [_Similarity_fax]      REAL          NULL,
    [_Similarity_mobile]   REAL          NULL,
    [igrp_no]              INT           NULL,
    [z_id]                 INT           NULL,
    [company_clean]        VARCHAR (255) NULL,
    [_Similarity_company]  REAL          NULL
);

