CREATE TABLE [dbo].[smtplog] (
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [type1]             VARCHAR (100)  NULL,
    [type]              VARCHAR (1000) NULL,
    [timeLogged]        DATETIME       NULL,
    [timeQueued]        DATETIME       NULL,
    [orig]              VARCHAR (1000) NULL,
    [rcpt]              VARCHAR (1000) NULL,
    [orcpt]             VARCHAR (1000) NULL,
    [dsnAction]         VARCHAR (1000) NULL,
    [dsnStatus]         VARCHAR (1000) NULL,
    [dsnDiag]           VARCHAR (1000) NULL,
    [dsnMta]            VARCHAR (1000) NULL,
    [bounceCat]         VARCHAR (1000) NULL,
    [srcType]           VARCHAR (1000) NULL,
    [srcMta]            VARCHAR (1000) NULL,
    [dlvType]           VARCHAR (1000) NULL,
    [dlvSourceIp]       VARCHAR (1000) NULL,
    [dlvDestinationIp]  VARCHAR (1000) NULL,
    [dlvEsmtpAvailable] VARCHAR (1000) NULL,
    [dlvSize]           VARCHAR (1000) NULL,
    [vmta]              VARCHAR (1000) NULL,
    [jobId]             VARCHAR (100)  NULL,
    [envId]             VARCHAR (1000) NULL,
    [queue]             VARCHAR (1000) NULL,
    [vmtaPool]          VARCHAR (100)  NULL,
    [emailID]           INT            NULL,
    [blastID]           INT            NULL,
    [IsTestBlast]       BIT            NULL
);

