CREATE TABLE [dbo].[tmp_WattMasterGroup] (
    [EmailID]                                  INT              NOT NULL,
    [emailaddress]                             VARCHAR (255)    NOT NULL,
    [subscribeTypecode]                        VARCHAR (50)     NULL,
    [createdon]                                DATETIME         NULL,
    [lastchanged]                              DATETIME         NULL,
    [tmp_EmailID]                              INT              NULL,
    [EntryID]                                  UNIQUEIDENTIFIER NULL,
    [Agribusiness]                             VARCHAR (500)    NULL,
    [DesignTips]                               VARCHAR (500)    NULL,
    [EquipmentTips]                            VARCHAR (500)    NULL,
    [Feed_ENews]                               VARCHAR (500)    NULL,
    [IA_Ciberboletin]                          VARCHAR (500)    NULL,
    [Management_Tips]                          VARCHAR (500)    NULL,
    [Pet_ENews]                                VARCHAR (500)    NULL,
    [Petfood_Nutrition]                        VARCHAR (500)    NULL,
    [Pig_ENews]                                VARCHAR (500)    NULL,
    [Shoptips]                                 VARCHAR (500)    NULL,
    [TipSheet]                                 VARCHAR (500)    NULL,
    [WPOU_ENews]                               VARCHAR (500)    NULL,
    [Agribusiness_Source]                      VARCHAR (500)    NULL,
    [DesignTips_Source]                        VARCHAR (500)    NULL,
    [EquipmentTips_Source]                     VARCHAR (500)    NULL,
    [Feed_ENews_Source]                        VARCHAR (500)    NULL,
    [IA_Ciberboletin_Source]                   VARCHAR (500)    NULL,
    [Management_Tips_Source]                   VARCHAR (500)    NULL,
    [Pet_ENews_Source]                         VARCHAR (500)    NULL,
    [Petfood_Nutrition_Source]                 VARCHAR (500)    NULL,
    [Pig_ENews_Source]                         VARCHAR (500)    NULL,
    [Shoptips_Source]                          VARCHAR (500)    NULL,
    [TipSheet_Source]                          VARCHAR (500)    NULL,
    [WPOU_ENews_Source]                        VARCHAR (500)    NULL,
    [PoultryUpdate]                            VARCHAR (500)    NULL,
    [PoultryUpdate_Source]                     VARCHAR (500)    NULL,
    [DailyBrief]                               VARCHAR (500)    NULL,
    [DailyBrief_Source]                        VARCHAR (500)    NULL,
    [ALIMENTOSBALANCEADOSLATINOAMÉRICA]        VARCHAR (500)    NULL,
    [ALIMENTOSBALANCEADOSLATINOAMÉRICA_Source] VARCHAR (500)    NULL
);

