CREATE TABLE [dbo].[IssueCompDetail]
(
	IssueCompDetailId int identity(1,1) not null,
	[IssueCompID]				   INT				NOT NULL,	
	[ExternalKeyID]            INT              NULL,
    [FirstName]                VARCHAR (50)     NULL,
    [LastName]                 VARCHAR (50)     NULL,
    [Company]                  VARCHAR (100)    NULL,
    [Title]                    VARCHAR (255)    NULL,
    [Occupation]               VARCHAR (50)     NULL,
    [AddressTypeID]            INT              NULL,
    [Address1]                 VARCHAR (100)    NULL,
    [Address2]                 VARCHAR (100)    NULL,
	[Address3]                 VARCHAR (100)    NULL,
    [City]                     VARCHAR (50)     NULL,
    [RegionCode]               VARCHAR (50)     NULL,
    [RegionID]                 INT              NULL,
    [ZipCode]                  VARCHAR (50)     NULL,
    [Plus4]                    VARCHAR (10)     NULL,
    [CarrierRoute]             VARCHAR (10)     NULL,
    [County]                   VARCHAR (50)     NULL,
    [Country]                  VARCHAR (50)     NULL,
    [CountryID]                INT              NULL,
    [Latitude]                 DECIMAL (18, 15) NULL,
    [Longitude]                DECIMAL (18, 15) NULL,
    [IsAddressValidated]       BIT              NOT NULL,
    [AddressValidationDate]    DATETIME         NULL,
    [AddressValidationSource]  VARCHAR (50)     NULL,
    [AddressValidationMessage] VARCHAR (MAX)    NULL,
    [Email]                    VARCHAR (255)    NULL,
    [Phone]                    VARCHAR (25)     NULL,
    [Fax]                      VARCHAR (25)     NULL,
    [Mobile]                   VARCHAR (25)     NULL,
    [Website]                  VARCHAR (255)    NULL,
    [Birthdate]                DATE             NULL,
    [Age]                      INT              NULL,
    [Income]                   VARCHAR (50)     NULL,
    [Gender]                   VARCHAR (50)     NULL,
    [IsLocked]                 BIT              NOT NULL,
    [PhoneExt] 				   VARCHAR(25) 		NULL, 
	[SequenceID]                     INT          NULL,
    [PublisherID]                    INT          NOT NULL,
    [SubscriberID]                   INT          NOT NULL,
    [PublicationID]                  INT          NOT NULL,
    [ActionID_Current]               INT          NOT NULL,
    [ActionID_Previous]              INT          NULL,
    [SubscriptionStatusID]           INT          NULL,
    [IsPaid]                         BIT          NOT NULL,
    [QSourceID]                      INT          NULL,
    [QSourceDate]                    DATE         NULL,
    [DeliverabilityID]               INT          NULL,
    [IsSubscribed]                   BIT          NOT NULL,
    [SubscriberSourceCode]           varchar(256) NULL,
    [Copies]                         INT          NOT NULL,
    [OriginalSubscriberSourceCode]   varchar(256) NULL,
    [Par3cID]                        INT          NULL,
    [SubsrcTypeID]                   INT          NULL,
    [AccountNumber]                  VARCHAR (50) NULL,
    [OnBehalfOf] 					 VARCHAR(256) NULL, 
    [MemberGroup] 					 VARCHAR(256) NULL, 
	[Verify] 						 VARCHAR(256) NULL, 
	[DateCreated]              		 DATETIME     NOT NULL,
    [DateUpdated]              		 DATETIME     NULL,
    [CreatedByUserID]          		 INT          NOT NULL,
    [UpdatedByUserID]          		 INT          NULL, 
    CONSTRAINT [PK_IssueCompDetail] PRIMARY KEY ([IssueCompDetailId])
)
