CREATE TABLE [dbo].[SurveyStyles] (
    [SurveyID]       INT           NOT NULL,
    [pWidth]         VARCHAR (5)   NULL,
    [pbgcolor]       VARCHAR (25)  NULL,
    [pAlign]         VARCHAR (10)  NULL,
    [pBorder]        BIT           NULL,
    [pBordercolor]   VARCHAR (25)  NULL,
    [pfontfamily]    VARCHAR (50)  NULL,
    [hImage]         VARCHAR (250) NULL,
    [hAlign]         VARCHAR (10)  NULL,
    [hMargin]        VARCHAR (25)  NULL,
    [hbgcolor]       VARCHAR (25)  NULL,
    [phbgcolor]      VARCHAR (25)  NULL,
    [phfontsize]     VARCHAR (5)   NULL,
    [phcolor]        VARCHAR (25)  NULL,
    [phBold]         BIT           NULL,
    [pdbgcolor]      VARCHAR (25)  NULL,
    [pdfontsize]     VARCHAR (5)   NULL,
    [pdcolor]        VARCHAR (25)  NULL,
    [pdbold]         BIT           NULL,
    [bbgcolor]       VARCHAR (25)  NULL,
    [qcolor]         VARCHAR (25)  NULL,
    [qfontsize]      VARCHAR (5)   NULL,
    [qbold]          BIT           NULL,
    [acolor]         VARCHAR (25)  NULL,
    [abold]          BIT           NULL,
    [afontsize]      VARCHAR (5)   NULL,
    [fImage]         VARCHAR (250) NULL,
    [fAlign]         VARCHAR (10)  NULL,
    [fMargin]        VARCHAR (25)  NULL,
    [fbgcolor]       VARCHAR (25)  NULL,
    [ShowQuestionNo] BIT           CONSTRAINT [DF_Survey_Styles_ShowQuestionNO] DEFAULT (1) NULL,
    CONSTRAINT [PK_SurveyStyles] PRIMARY KEY CLUSTERED ([SurveyID] ASC),
    CONSTRAINT [FK_Survey_Styles_survey] FOREIGN KEY ([SurveyID]) REFERENCES [dbo].[Survey] ([SurveyID])
);

