CREATE TABLE [dbo].[Templates] (
    [TemplateID]     INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]     INT           NULL,
    [TemplateName]   VARCHAR (50)  NOT NULL,
    [TemplateImage]  VARCHAR (250) NULL,
    [IsDefault]      BIT           NULL,
    [pbgcolor]       VARCHAR (25)  NULL,
    [pAlign]         VARCHAR (10)  NULL,
    [pBorder]        BIT           NULL,
    [pBordercolor]   VARCHAR (25)  NULL,
    [pfontfamily]    VARCHAR (50)  NULL,
    [pWidth]         VARCHAR (5)   NULL,
    [hImage]         VARCHAR (250) NULL,
    [hAlign]         VARCHAR (10)  NULL,
    [hMargin]        VARCHAR (25)  NULL,
    [hbgcolor]       VARCHAR (25)  NULL,
    [phbgcolor]      VARCHAR (25)  NULL,
    [phfontsize]     VARCHAR (5)   NULL,
    [phcolor]        VARCHAR (25)  NULL,
    [phBold]         BIT           NULL,
    [pdbgcolor]      VARCHAR (25)  NULL,
    [pdfontsize]     VARCHAR (5)   NULL,
    [pdcolor]        VARCHAR (25)  NULL,
    [pdbold]         BIT           NULL,
    [bbgcolor]       VARCHAR (25)  NULL,
    [qcolor]         VARCHAR (25)  NULL,
    [qfontsize]      VARCHAR (5)   NULL,
    [qbold]          BIT           NULL,
    [ShowQuestionNo] BIT           CONSTRAINT [DF_Templates_ShowQuestionNo] DEFAULT (1) NULL,
    [acolor]         VARCHAR (25)  NULL,
    [abold]          BIT           NULL,
    [afontsize]      VARCHAR (5)   NULL,
    [fImage]         VARCHAR (250) NULL,
    [fAlign]         VARCHAR (10)  NULL,
    [fMargin]        VARCHAR (25)  NULL,
    [fbgcolor]       VARCHAR (25)  NULL,
    [IsActive]       BIT           CONSTRAINT [DF_Templates_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]    DATETIME      NULL,
    [CreatedUserID]  INT           NULL,
    [UpdatedDate]    DATETIME      NULL,
    [UpdatedUserID]  INT           NULL,
    CONSTRAINT [PK_Templates] PRIMARY KEY CLUSTERED ([TemplateID] ASC) WITH (FILLFACTOR = 80)
);

