(function(b,a){a("kendo.gantt.timeline",["kendo.dom","kendo.touch","kendo.draganddrop"],b);
}(function(){var a={id:"gantt.timeline",name:"Gantt Timeline",category:"web",description:"The Gantt Timeline",depends:["dom","touch","draganddrop"],hidden:true};
(function(b){var M=kendo.ui.Widget;
var p=kendo.dom.element;
var r=kendo.dom.text;
var q=kendo.dom.html;
var n=b.isPlainObject;
var j=b.extend;
var A=b.proxy;
var d=kendo.support.browser;
var o=false;
var t=kendo.keys;
var B=kendo.data.Query;
var F="string";
var y=".kendoGanttTimeline";
var e="click";
var g="dblclick";
var x="mousemove";
var v="mouseenter";
var w="mouseleave";
var s="keydown";
var i=".";
var H=kendo.template("#=kendo.toString(start, 't')#");
var f=kendo.template("#=kendo.toString(start, 'ddd M/dd')#");
var L=kendo.template("#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#");
var u=kendo.template("#=kendo.toString(start, 'MMM')#");
var N=kendo.template("#=kendo.toString(start, 'yyyy')#");
var C=kendo.template('<div class="#=styles.marquee#"><div class="#=styles.marqueeColor#"></div></div>');
var D=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#"><div class="#=styles.tooltipContent#"><div>#=messages.start#: #=kendo.toString(start, format)#</div><div>#=messages.end#: #=kendo.toString(end, format)#</div></div></div>');
var z=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#" ><div class="#=styles.tooltipContent#">#=text#%</div><div class="#=styles.tooltipCallout#" style="left:13px;"></div></div>');
var G=kendo.template('<div class="#=styles.taskDetails#"><strong>#=task.title#</strong><div class="#=styles.taskDetailsPercent#">#=kendo.toString(task.percentComplete, "p0")#</div><ul class="#=styles.reset#"><li>#=messages.start#: #=kendo.toString(task.start, "h:mm tt ddd, MMM d")#</li><li>#=messages.end#: #=kendo.toString(task.end, "h:mm tt ddd, MMM d")#</li></ul></div>');
var E="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>";
var h={day:{type:"kendo.ui.GanttDayView"},week:{type:"kendo.ui.GanttWeekView"},month:{type:"kendo.ui.GanttMonthView"},year:{type:"kendo.ui.GanttYearView"}};
function J(O){delete O.name;
delete O.prefix;
delete O.views;
return O;
}function m(P){var Q=[];
var O=P.workWeekStart;
Q.push(O);
while(P.workWeekEnd!=O){if(O>6){O-=7;
}else{O++;
}Q.push(O);
}return Q;
}function c(){var O=kendo._activeElement();
if(O&&O.nodeName.toLowerCase()!=="body"){b(O).blur();
}}var K={alt:"k-alt",reset:"k-reset",nonWorking:"k-nonwork-hour",header:"k-header",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasksWrapper:"k-gantt-tables",rowsTable:"k-gantt-rows",columnsTable:"k-gantt-columns",tasksTable:"k-gantt-tasks",dependenciesWrapper:"k-gantt-dependencies",resource:"k-resource",resourceAlt:"k-resource k-alt",task:"k-task",taskSingle:"k-task-single",taskMilestone:"k-task-milestone",taskSummary:"k-task-summary",taskWrap:"k-task-wrap",taskMilestoneWrap:"k-milestone-wrap",resourcesWrap:"k-resources-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",taskDragHandle:"k-task-draghandle",taskContent:"k-task-content",taskTemplate:"k-task-template",taskActions:"k-task-actions",taskDelete:"k-task-delete",taskComplete:"k-task-complete",taskDetails:"k-task-details",taskDetailsPercent:"k-task-pct",link:"k-link",icon:"k-icon",iconDelete:"k-si-close",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskResizeHandleEast:"k-resize-e",taskSummaryProgress:"k-task-summary-progress",taskSummaryComplete:"k-task-summary-complete",line:"k-line",lineHorizontal:"k-line-h",lineVertical:"k-line-v",arrowWest:"k-arrow-w",arrowEast:"k-arrow-e",dragHint:"k-drag-hint",dependencyHint:"k-dependency-hint",tooltipWrapper:"k-widget k-tooltip k-popup k-group k-reset",tooltipContent:"k-tooltip-content",tooltipCallout:"k-callout k-callout-s",callout:"k-callout",marquee:"k-marquee k-gantt-marquee",marqueeColor:"k-marquee-color"};
var l=kendo.ui.GanttView=M.extend({init:function(O,P){M.fn.init.call(this,O,P);
this.title=this.options.title||this.options.name;
this.header=this.element.find(i+l.styles.gridHeader);
this.content=this.element.find(i+l.styles.gridContent);
this.contentWidth=this.content.width();
this._workDays=m(this.options);
this._headerTree=P.headerTree;
this._taskTree=P.taskTree;
this._taskTemplate=P.taskTemplate?kendo.template(P.taskTemplate,j({},kendo.Template,P.templateSettings)):null;
this._dependencyTree=P.dependencyTree;
this._taskCoordinates={};
this._currentTime();
},destroy:function(){M.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
this.headerRow=null;
this.header=null;
this.content=null;
this._dragHint=null;
this._resizeHint=null;
this._resizeTooltip=null;
this._taskTooltip=null;
this._percentCompleteResizeTooltip=null;
this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
},options:{showWorkHours:false,showWorkDays:false,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,slotSize:100,currentTimeMarker:{updateInterval:10000}},renderLayout:function(){this._slots=this._createSlots();
this._tableWidth=this._calculateTableWidth();
this.createLayout(this._layout());
this._slotDimensions();
this._adjustHeight();
this.content.find(i+l.styles.dependenciesWrapper).width(this._tableWidth);
},_adjustHeight:function(){this.content.height(this.element.height()-this.header.outerHeight());
},createLayout:function(R){var Q=this._headers(R);
var O=this._colgroup();
var T=this._headerTree;
var P=p("thead",null,Q);
var S=p("table",{style:{width:this._tableWidth+"px"}},[O,P]);
T.render([S]);
this.headerRow=this.header.find("table:first tr").last();
},_slotDimensions:function(){var P=this.headerRow[0].children;
var T=this._timeSlots();
var S;
var O;
for(var Q=0,R=P.length;
Q<R;
Q++){O=P[Q];
S=T[Q];
S.offsetLeft=O.offsetLeft;
S.offsetWidth=O.offsetWidth;
}},render:function(V){var U=V.length;
var T=l.styles;
var Q;
var S=this._rowsTable(U);
var P=this._columnsTable(U);
var W=this._tasksTable(V);
var R=this.options.currentTimeMarker;
var O=this.options.calculatedSize;
var X;
this._taskTree.render([S,P,W]);
Q=this.content.find(i+T.rowsTable);
if(O){X=O.row*V.length;
this.content.find(i+T.tasksTable).height(X);
Q.height(X);
}this._contentHeight=Q.height();
this._rowHeight=O?O.row:this._contentHeight/Q.find("tr").length;
this.content.find(i+T.columnsTable).height(this._contentHeight);
if(R!==false&&R.updateInterval!==undefined){this._renderCurrentTime();
}},_rowsTable:function(R){var S=[];
var Q;
var T=l.styles;
var O=[null,{className:T.alt}];
for(var P=0;
P<R;
P++){Q=p("tr",O[P%2],[p("td",null,[r("\xA0")])]);
S.push(Q);
}return this._createTable(1,S,{className:T.rowsTable});
},_columnsTable:function(){var P=[];
var R;
var W=l.styles;
var T=this._timeSlots();
var U=T.length;
var S;
var V;
var X=0;
var O;
for(var Q=0;
Q<U;
Q++){S=T[Q];
O={};
V=S.span;
X+=V;
if(V!==1){O.colspan=V;
}if(S.isNonWorking){O.className=W.nonWorking;
}P.push(p("td",O,[r("\xA0")]));
}R=p("tr",null,P);
return this._createTable(X,[R],{className:W.columnsTable});
},_tasksTable:function(ah){var ac=[];
var ab;
var Q;
var W;
var af;
var ae=l.styles;
var S=this._taskCoordinates={};
var ad=this._calculateMilestoneWidth();
var V=Math.round(ad.width);
var X=this.options.resourcesField;
var R=[ae.resource,ae.resourceAlt];
var P=this.options.calculatedSize;
var Z;
var Y=this._calculateResourcesMargin();
var ag=this._calculateTaskBorderWidth();
var aa;
var O=function(ai){var aj;
var ak;
aj=W.left;
ak=aj+W.width;
if(af.isMilestone()){aj-=V/2;
ak=aj+V;
}S[af.id]={start:aj,end:ak,rowIndex:ai};
};
for(var T=0,U=ah.length;
T<U;
T++){af=ah[T];
W=this._taskPosition(af);
W.borderWidth=ag;
ab=p("tr",null);
if(af.start<=this.end&&af.end>=this.start){Q=p("td",null,[this._renderTask(ah[T],W)]);
if(af[X]&&af[X].length){if(o){Z=this._tableWidth-W.left;
}else{Z=Math.max(W.width||ad.clientWidth,0)+W.left;
}aa={width:this._tableWidth-(Z+Y)+"px"};
aa[o?"right":"left"]=Z+"px";
if(P){aa.height=P.cell+"px";
}Q.children.push(p("div",{className:ae.resourcesWrap,style:aa},this._renderResources(af[X],R[T%2])));
}ab.children.push(Q);
O(T);
}ac.push(ab);
}return this._createTable(1,ac,{className:l.styles.tasksTable});
},_createTable:function(Q,S,T){var P=[];
var O;
var U;
for(var R=0;
R<Q;
R++){P.push(p("col"));
}O=p("colgroup",null,P);
U=p("tbody",null,S);
if(!T.style){T.style={};
}T.style.width=this._tableWidth+"px";
return p("table",T,[O,U]);
},_calculateTableWidth:function(){var S=this._timeSlots();
var R=0;
var U=0;
var O;
var T;
for(var P=0,Q=S.length;
P<Q;
P++){O=S[P].span;
U+=O;
if(O>R){R=O;
}}T=Math.round(U*this.options.slotSize/R);
return T;
},_calculateMilestoneWidth:function(){var R;
var P=l.styles.task+" "+l.styles.taskMilestone;
var Q=b("<div class='"+P+"' style='visibility: hidden; position: absolute'>");
var O;
this.content.append(Q);
O=Q[0].getBoundingClientRect();
R={width:O.right-O.left,clientWidth:Q[0].clientWidth};
Q.remove();
return R;
},_calculateResourcesMargin:function(){var O;
var P=b("<div class='"+l.styles.resourcesWrap+"' style='visibility: hidden; position: absolute'>");
this.content.append(P);
O=parseInt(P.css(o?"margin-right":"margin-left"),10);
P.remove();
return O;
},_calculateTaskBorderWidth:function(){var R;
var O=l.styles.task+" "+l.styles.taskSingle;
var Q=b("<div class='"+O+"' style='visibility: hidden; position: absolute'>");
var P;
this.content.append(Q);
P=kendo.getComputedStyles(Q[0],["border-left-width"]);
R=parseFloat(P["border-left-width"],10);
Q.remove();
return R;
},_renderTask:function(U,R){var Y;
var V;
var Q=this.options.editable;
var S;
var W=R.left;
var T=l.styles;
var Z=T.taskWrap;
var O=this.options.calculatedSize;
var P={};
var X={className:Z,style:{left:W+"px"}};
if(O){X.style.height=O.cell+"px";
}if(U.summary){V=this._renderSummary(U,R);
}else{if(U.isMilestone()){V=this._renderMilestone(U,R);
X.className+=" "+T.taskMilestoneWrap;
}else{V=this._renderSingleTask(U,R);
}}Y=p("div",X,[V]);
if(Q&&Q.dependencyCreate!==false){Y.children.push(p("div",{className:T.taskDot+" "+T.taskDotStart}));
Y.children.push(p("div",{className:T.taskDot+" "+T.taskDotEnd}));
}if(!U.summary&&!U.isMilestone()&&Q&&Q.dragPercentComplete!==false&&Q.update!==false&&this._taskTemplate===null){S=Math.round(R.width*U.percentComplete);
P[o?"right":"left"]=S+"px";
Y.children.push(p("div",{className:T.taskDragHandle,style:P}));
}return Y;
},_renderSingleTask:function(U,R){var T=l.styles;
var S=Math.round(R.width*U.percentComplete);
var V=[];
var W;
var P=this.options.editable;
if(this._taskTemplate!==null){W=q(this._taskTemplate(U));
}else{W=r(U.title);
V.push(p("div",{className:T.taskComplete,style:{width:S+"px"}}));
}var O=p("div",{className:T.taskContent},[p("div",{className:T.taskTemplate},[W])]);
V.push(O);
if(P){if(P.destroy!==false){O.children.push(p("span",{className:T.taskActions},[p("a",{className:T.link+" "+T.taskDelete,href:"#"},[p("span",{className:T.icon+" "+T.iconDelete})])]));
}if(P.resize!==false&&P.update!==false){O.children.push(p("span",{className:T.taskResizeHandle+" "+T.taskResizeHandleWest}));
O.children.push(p("span",{className:T.taskResizeHandle+" "+T.taskResizeHandleEast}));
}}var Q=p("div",{className:T.task+" "+T.taskSingle,"data-uid":U.uid,style:{width:Math.max(R.width-R.borderWidth*2,0)+"px"}},V);
return Q;
},_renderMilestone:function(Q){var P=l.styles;
var O=p("div",{className:P.task+" "+P.taskMilestone,"data-uid":Q.uid});
return O;
},_renderSummary:function(S,P){var R=l.styles;
var Q=Math.round(P.width*S.percentComplete);
var O=p("div",{className:R.task+" "+R.taskSummary,"data-uid":S.uid,style:{width:P.width+"px"}},[p("div",{className:R.taskSummaryProgress,style:{width:Q+"px"}},[p("div",{className:R.taskSummaryComplete,style:{width:P.width+"px"}})])]);
return O;
},_renderResources:function(T,P){var O=[];
var S;
for(var Q=0,R=T.length;
Q<R;
Q++){S=T[Q];
O.push(p("span",{className:P,style:{color:S.get("color")}},[r(S.get("name"))]));
}if(o){O.reverse();
}return O;
},_taskPosition:function(R){var P=Math.round;
var Q=P(this._offset(o?R.end:R.start));
var O=P(this._offset(o?R.start:R.end));
return{left:Q,width:O-Q};
},_offset:function(O){var S=this._timeSlots();
var P;
var U;
var Q;
var R=0;
var T;
if(!S.length){return 0;
}T=this._slotIndex("start",O);
P=S[T];
if(P.end<O){R=P.offsetWidth;
}else{if(P.start<=O){U=O-P.start;
Q=P.end-P.start;
R=U/Q*P.offsetWidth;
}}if(o){R=P.offsetWidth+1-R;
}return P.offsetLeft+R;
},_slotIndex:function(P,U,R){var S=this._timeSlots();
var T=0;
var O=S.length-1;
var Q;
if(R){S=[].slice.call(S).reverse();
}do{Q=Math.ceil((O+T)/2);
if(S[Q][P]<U){T=Q;
}else{if(Q===O){Q--;
}O=Q;
}}while(T!==O);
if(R){T=S.length-1-T;
}return T;
},_timeByPosition:function(U,S,T){var Q=this._slotByPosition(U);
if(S){return T?Q.end:Q.start;
}var P=U-b(i+l.styles.tasksTable).offset().left;
var O=Q.end-Q.start;
var R=P-Q.offsetLeft;
if(o){R=Q.offsetWidth-R;
}return new Date(Q.start.getTime()+O*(R/Q.offsetWidth));
},_slotByPosition:function(Q){var O=Q-b(i+l.styles.tasksTable).offset().left;
var P=this._slotIndex("offsetLeft",O,o);
return this._timeSlots()[P];
},_renderDependencies:function(O){var P=[];
var S=this._dependencyTree;
for(var Q=0,R=O.length;
Q<R;
Q++){P.push.apply(P,this._renderDependency(O[Q]));
}S.render(P);
},_renderDependency:function(O){var T=this._taskCoordinates[O.predecessorId];
var U=this._taskCoordinates[O.successorId];
var P;
var S;
if(!T||!U){return[];
}S="_render"+["FF","FS","SF","SS"][o?3-O.type:O.type];
P=this[S](T,U);
for(var Q=0,R=P.length;
Q<R;
Q++){P[Q].attr["data-uid"]=O.uid;
}return P;
},_renderFF:function(O,Q){var P=this._dependencyFF(O,Q,false);
P[P.length-1].children[0]=this._arrow(true);
return P;
},_renderSS:function(O,Q){var P=this._dependencyFF(Q,O,true);
P[0].children[0]=this._arrow(false);
return P.reverse();
},_renderFS:function(O,Q){var P=this._dependencyFS(O,Q,false);
P[P.length-1].children[0]=this._arrow(false);
return P;
},_renderSF:function(O,Q){var P=this._dependencyFS(Q,O,true);
P[0].children[0]=this._arrow(true);
return P.reverse();
},_dependencyFF:function(T,ae,aa){var ad=this;
var X=[];
var W=0;
var af=0;
var ah=0;
var V=0;
var S=aa?"start":"end";
var R;
var Z=2;
var Q=1;
var ab=this._rowHeight;
var Y=10;
var U=T.rowIndex*ab+Math.floor(ab/2)-1;
var ag=ae.rowIndex*ab+Math.floor(ab/2)-1;
var ac=l.styles;
var O=function(){X.push(ad._line(ac.line+" "+ac.lineHorizontal,{left:W+"px",top:af+"px",width:ah+"px"}));
};
var P=function(){X.push(ad._line(ac.line+" "+ac.lineVertical,{left:W+"px",top:af+"px",height:V+"px"}));
};
W=T[S];
af=U;
ah=Y;
R=ae[S]-T[S];
if(R>0!==aa){ah=Math.abs(R)+Y;
}if(aa){W-=ah;
ah-=Q;
O();
}else{O();
W+=ah-Z;
}if(ag<af){V=af-ag;
V+=Z;
af=ag;
P();
}else{V=ag-af;
V+=Z;
P();
af+=V-Z;
}ah=Math.abs(W-ae[S]);
if(!aa){ah-=Q;
W-=ah;
}O();
return X;
},_dependencyFS:function(S,af,ab){var ae=this;
var W=[];
var V=0;
var ag=0;
var ai=0;
var U=0;
var ac=this._rowHeight;
var Y=Math.floor(ac/2);
var Z=10;
var X=2*Z;
var R=af.start-S.end;
var aa=2;
var Q=1;
var T=S.rowIndex*ac+Math.floor(ac/2)-1;
var ah=af.rowIndex*ac+Math.floor(ac/2)-1;
var ad=l.styles;
var O=function(){W.push(ae._line(ad.line+" "+ad.lineHorizontal,{left:V+"px",top:ag+"px",width:ai+"px"}));
};
var P=function(){W.push(ae._line(ad.line+" "+ad.lineVertical,{left:V+"px",top:ag+"px",height:U+"px"}));
};
V=S.end;
ag=T;
ai=Z;
if(ab){V+=Q;
if(R>X){ai=R-(Z-aa);
}ai-=Q;
}O();
V+=ai-aa;
if(R<=X){U=ab?Math.abs(ah-T)-Y:Y;
if(ah<T){ag-=U;
U+=aa;
P();
}else{P();
ag+=U;
}ai=S.end-af.start+X;
if(ai<Z){ai=Z;
}V-=ai-aa;
O();
}if(ah<T){U=ag-ah;
ag=ah;
U+=aa;
P();
}else{U=ah-ag;
P();
ag+=U;
}ai=af.start-V;
if(!ab){ai-=Q;
}O();
return W;
},_line:function(O,P){return p("div",{className:O,style:P});
},_arrow:function(O){return p("span",{className:O?l.styles.arrowWest:l.styles.arrowEast});
},_colgroup:function(){var T=this._timeSlots();
var P=T.length;
var O=[];
for(var Q=0;
Q<P;
Q++){for(var R=0,S=T[Q].span;
R<S;
R++){O.push(p("col"));
}}return p("colgroup",null,O);
},_createDragHint:function(O){this._dragHint=O.clone().addClass(l.styles.dragHint).css("cursor","move");
O.parent().append(this._dragHint);
},_updateDragHint:function(P){var O=this._offset(P);
this._dragHint.css({left:O});
},_removeDragHint:function(){this._dragHint.remove();
this._dragHint=null;
},_createResizeHint:function(R){var Q=l.styles;
var S=this._taskCoordinates[R.id].rowIndex*this._rowHeight;
var T;
var U;
var P=this.options;
var O=P.messages;
this._resizeHint=b(C({styles:Q})).css({top:0,height:this._contentHeight});
this.content.append(this._resizeHint);
this._resizeTooltip=b(D({styles:Q,start:R.start,end:R.end,messages:O.views,format:P.resizeTooltipFormat})).css({top:0,left:0});
this.content.append(this._resizeTooltip);
this._resizeTooltipWidth=this._resizeTooltip.outerWidth();
T=this._resizeTooltip.outerHeight();
U=S-T;
if(U<0){U=S+this._rowHeight;
}this._resizeTooltipTop=U;
},_updateResizeHint:function(U,O,S){var P=this._offset(o?O:U);
var T=this._offset(o?U:O);
var Z=T-P;
var X=S!==o?P:T;
var W=this._tableWidth-kendo.support.scrollbar();
var Y=this._resizeTooltipWidth;
var R=this.options;
var Q=R.messages;
var V=b(i+l.styles.tasksTable).offset().left-b(i+l.styles.tasksWrapper).offset().left;
if(o){P+=V;
}this._resizeHint.css({left:P,width:Z});
if(this._resizeTooltip){this._resizeTooltip.remove();
}X-=Math.round(Y/2);
if(X<0){X=0;
}else{if(X+Y>W){X=W-Y;
}}if(o){X+=V;
}this._resizeTooltip=b(D({styles:l.styles,start:U,end:O,messages:Q.views,format:R.resizeTooltipFormat})).css({top:this._resizeTooltipTop,left:X,"min-width":Y}).appendTo(this.content);
},_removeResizeHint:function(){this._resizeHint.remove();
this._resizeHint=null;
this._resizeTooltip.remove();
this._resizeTooltip=null;
},_updatePercentCompleteTooltip:function(U,Q,R){this._removePercentCompleteTooltip();
var S=this._percentCompleteResizeTooltip=b(z({styles:l.styles,text:R})).appendTo(this.element);
var T=Math.round(S.outerWidth()/2);
var O=S.find(i+l.styles.callout);
var P=Math.round(O.outerWidth()/2);
S.css({top:U-(S.outerHeight()+P),left:Q-T});
O.css("left",T-P);
},_removePercentCompleteTooltip:function(){if(this._percentCompleteResizeTooltip){this._percentCompleteResizeTooltip.remove();
}this._percentCompleteResizeTooltip=null;
},_updateDependencyDragHint:function(O,P,Q){this._removeDependencyDragHint();
if(Q){this._creteVmlDependencyDragHint(O,P);
}else{this._creteDependencyDragHint(O,P);
}},_creteDependencyDragHint:function(R,T){var S=l.styles;
var P=T.x-R.x;
var Q=T.y-R.y;
var U=Math.sqrt(P*P+Q*Q);
var O=Math.atan(Q/P);
if(P<0){O+=Math.PI;
}b("<div class='"+S.line+" "+S.lineHorizontal+" "+S.dependencyHint+"'></div>").css({top:R.y,left:R.x,width:U,"transform-origin":"0% 0","-ms-transform-origin":"0% 0","-webkit-transform-origin":"0% 0",transform:"rotate("+O+"rad)","-ms-transform":"rotate("+O+"rad)","-webkit-transform":"rotate("+O+"rad)"}).appendTo(this.content);
},_creteVmlDependencyDragHint:function(O,Q){var P=b("<kvml:line class='"+l.styles.dependencyHint+"' style='position:absolute; top: 0px; left: 0px;' strokecolor='black' strokeweight='2px' from='"+O.x+"px,"+O.y+"px' to='"+Q.x+"px,"+Q.y+"px'></kvml:line>").appendTo(this.content);
P[0].outerHTML=P[0].outerHTML;
},_removeDependencyDragHint:function(){this.content.find(i+l.styles.dependencyHint).remove();
},_createTaskTooltip:function(Z,S,U){var Y=l.styles;
var V=this.options;
var O=this.content;
var P=O.offset();
var R=O.width();
var Q=kendo.scrollLeft(O);
var W=b(S).parents("tr").first();
var X=W.offset();
var aa=V.tooltip&&V.tooltip.template?kendo.template(V.tooltip.template):G;
var T=o?U-(P.left+Q+kendo.support.scrollbar()):U-(P.left-Q);
var ad=X.top+W.outerHeight()-P.top+O.scrollTop();
var ab=this._taskTooltip=b('<div style="z-index: 100002;" class="'+Y.tooltipWrapper+'" ><div class="'+Y.taskContent+'"></div></div>');
var ac;
ab.css({left:T,top:ad}).appendTo(O).find(i+Y.taskContent).append(aa({styles:Y,task:Z,messages:V.messages.views}));
if(ab.outerHeight()<X.top-P.top){ab.css("top",X.top-P.top-ab.outerHeight()+O.scrollTop());
}ac=ab.outerWidth();
if(ac+T-Q>R){T-=ac;
if(T<Q){T=Q+R-(ac+17);
}ab.css("left",T);
}},_removeTaskTooltip:function(){if(this._taskTooltip){this._taskTooltip.remove();
}this._taskTooltip=null;
},_scrollTo:function(W){var X=W.offset().left;
var Z=W.width();
var Y=X+Z;
var aa=W.closest("tr");
var ad=aa.offset().top;
var ac=aa.height();
var ab=ad+ac;
var O=this.content;
var S=O.offset();
var U=S.top;
var Q=O.height();
var P=U+Q;
var R=S.left;
var V=O.width();
var T=R+V;
var ae=kendo.support.scrollbar();
if(ad<U){O.scrollTop(O.scrollTop()+(ad-U));
}else{if(ab>P){O.scrollTop(O.scrollTop()+(ab+ae-P));
}}if(X<R&&Z>V&&Y<T||Y>T&&Z<V){O.scrollLeft(O.scrollLeft()+(Y+ae-T));
}else{if(Y>T&&Z>V&&X>R||X<R&&Z<V){O.scrollLeft(O.scrollLeft()+(X-R));
}}},_scrollToDate:function(O){var R=this.start;
var Q=this.end;
var P;
if(O>=R&&O<Q){P=this._offset(O);
if(kendo.support.isRtl(this.element)){P=this._tableWidth-P;
}kendo.scrollLeft(this.content,P);
}},_timeSlots:function(){if(!this._slots||!this._slots.length){return[];
}return this._slots[this._slots.length-1];
},_headers:function(R){var X=[];
var U;
var S;
var O;
var T;
var Y=l.styles;
for(var W=0,V=R.length;
W<V;
W++){U=R[W];
S=[];
for(var Q=0,P=U.length;
Q<P;
Q++){O=U[Q];
T=r(O.text);
S.push(p("th",{colspan:O.span,className:Y.header+(O.isNonWorking?" "+Y.nonWorking:"")},[T]));
}X.push(p("tr",null,S));
}return X;
},_hours:function(V,O){var T;
var U=[];
var S=this.options;
var X=S.workDayStart.getHours();
var W=S.workDayEnd.getHours();
var R;
var P;
var Q=S.hourSpan;
V=new Date(V);
O=new Date(O);
while(V<O){T=new Date(V);
P=T.getHours();
R=P>=X&&P<W;
T.setHours(T.getHours()+Q);
if(P==T.getHours()){T.setHours(T.getHours()+2*Q);
}if(!S.showWorkHours||R){U.push({start:V,end:T,isNonWorking:!R,span:1});
}V=T;
}return U;
},_days:function(S,O){var Q;
var R=[];
var P;
S=new Date(S);
O=new Date(O);
while(S<O){Q=O<kendo.date.nextDay(S)?O:kendo.date.nextDay(S);
P=this._isWorkDay(S);
if(!this.options.showWorkDays||P){R.push({start:S,end:Q,isNonWorking:!P,span:1});
}S=Q;
}return R;
},_weeks:function(U,P){var R;
var S=[];
var Q=this.calendarInfo().firstDay;
var O;
var T;
U=new Date(U);
P=new Date(P);
while(U<P){R=kendo.date.dayOfWeek(kendo.date.addDays(U,1),Q,1);
if(R>P){R=P;
}O=this._days(U,R);
T=O.length;
if(T>0){S.push({start:O[0].start,end:O[T-1].end,span:T});
}U=R;
}return S;
},_months:function(U,P){var R;
var Q;
var S=[];
var O;
var T;
U=new Date(U);
P=new Date(P);
while(U<P){R=new Date(U);
Q=kendo.date.firstDayOfMonth(new Date(R.setMonth(R.getMonth()+1)));
R=P<Q?P:Q;
O=this._days(U,R);
T=O.length;
if(T>0){S.push({start:O[0].start,end:O[T-1].end,span:T});
}U=R;
}return S;
},_years:function(T,O){var R;
var Q;
var P;
var S=[];
T=new Date(T);
O=new Date(O);
while(T<O){R=new Date(T);
R=kendo.date.firstDayOfMonth(new Date(R.setMonth(12)));
if(R>=O){R=O;
}P=R.getMonth()||12;
Q=P-T.getMonth();
S.push({start:T,end:R,span:Q});
T=R;
}return S;
},_slotHeaders:function(S,T){var O=[];
var R;
for(var P=0,Q=S.length;
P<Q;
P++){R=S[P];
O.push({text:T(R),isNonWorking:!!R.isNonWorking,span:R.span});
}return O;
},_isWorkDay:function(O){var P=O.getDay();
var S=this._workDays;
for(var Q=0,R=S.length;
Q<R;
Q++){if(S[Q]===P){return true;
}}return false;
},calendarInfo:function(){return kendo.getCulture().calendars.standard;
},_renderCurrentTime:function(){var O=this._getCurrentTime();
var T=this._offset(O);
var P=b("<div class='k-current-time'></div>");
var U=l.styles;
var R=b(i+U.tasksWrapper);
var S=b(i+U.tasksTable);
var Q;
if(!this.content||!this._timeSlots().length){return;
}this.content.find(".k-current-time").remove();
Q=this._timeSlots()[this._slotIndex("start",O)];
if(O<Q.start||O>Q.end){return;
}if(R.length&&S.length){T+=S.offset().left-R.offset().left;
}P.css({left:T+"px",top:"0px",width:"1px",height:this._contentHeight+"px"}).appendTo(this.content);
},_getCurrentTime:function(){return new Date();
},_currentTime:function(){var O=this.options.currentTimeMarker;
if(O!==false&&O.updateInterval!==undefined){this._renderCurrentTime();
this._currentTimeUpdateTimer=setInterval(A(this._renderCurrentTime,this),O.updateInterval);
}}});
j(true,l,{styles:K});
kendo.ui.GanttDayView=l.extend({name:"day",options:{timeHeaderTemplate:H,dayHeaderTemplate:f,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(P){var O=this.options.range;
this.start=kendo.date.getDate(P.start);
this.end=kendo.date.getDate(P.end);
if(kendo.date.getMilliseconds(P.end)>0||this.end.getTime()===this.start.getTime()){this.end=kendo.date.addDays(this.end,1);
}if(O&&O.start){this.start=kendo.date.getDate(O.start);
this.start.setHours(O.start.getHours());
}if(O&&O.end){this.end=kendo.date.getDate(O.end);
this.end.setHours(O.end.getHours());
}},_createSlots:function(){var P;
var O;
var R;
var Q;
var U=[];
P=this._days(this.start,this.end);
R=[];
for(var S=0,T=P.length;
S<T;
S++){O=P[S];
Q=this._hours(O.start,O.end);
O.span=Q.length;
R.push.apply(R,Q);
}U.push(P);
U.push(R);
return U;
},_layout:function(){var P=[];
var O=this.options;
P.push(this._slotHeaders(this._slots[0],kendo.template(O.dayHeaderTemplate)));
P.push(this._slotHeaders(this._slots[1],kendo.template(O.timeHeaderTemplate)));
return P;
}});
kendo.ui.GanttWeekView=l.extend({name:"week",options:{dayHeaderTemplate:f,weekHeaderTemplate:L,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(S){var R=this.options.range;
var O=this.calendarInfo();
var Q=O.firstDay;
var T=S.end;
var P;
if(Q===T.getDay()){T.setDate(T.getDate()+7);
}this.start=kendo.date.getDate(kendo.date.dayOfWeek(S.start,Q,-1));
this.end=kendo.date.getDate(kendo.date.dayOfWeek(T,Q,1));
if(R&&R.start){this.start=kendo.date.getDate(R.start);
}if(R&&R.end){P=new Date(R.end);
if(kendo.date.getDate(P)<R.end){this.end=kendo.date.getDate(new Date(P.setDate(P.getDate()+1)));
}else{this.end=kendo.date.getDate(P);
}}},_createSlots:function(){var O=[];
O.push(this._weeks(this.start,this.end));
O.push(this._days(this.start,this.end));
return O;
},_layout:function(){var P=[];
var O=this.options;
P.push(this._slotHeaders(this._slots[0],kendo.template(O.weekHeaderTemplate)));
P.push(this._slotHeaders(this._slots[1],kendo.template(O.dayHeaderTemplate)));
return P;
}});
kendo.ui.GanttMonthView=l.extend({name:"month",options:{weekHeaderTemplate:L,monthHeaderTemplate:u,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(Q){var P=this.options.range;
var O;
this.start=kendo.date.firstDayOfMonth(Q.start);
this.end=kendo.date.addDays(kendo.date.getDate(kendo.date.lastDayOfMonth(Q.end)),1);
if(P&&P.start){this.start=kendo.date.getDate(P.start);
}if(P&&P.end){O=new Date(P.end);
if(kendo.date.getDate(O)<P.end){this.end=kendo.date.getDate(new Date(O.setDate(O.getDate()+1)));
}else{this.end=kendo.date.getDate(O);
}}},_createSlots:function(){var O=[];
O.push(this._months(this.start,this.end));
O.push(this._weeks(this.start,this.end));
return O;
},_layout:function(){var P=[];
var O=this.options;
P.push(this._slotHeaders(this._slots[0],kendo.template(O.monthHeaderTemplate)));
P.push(this._slotHeaders(this._slots[1],kendo.template(O.weekHeaderTemplate)));
return P;
}});
kendo.ui.GanttYearView=l.extend({name:"year",options:{yearHeaderTemplate:N,monthHeaderTemplate:u,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(Q){var P=this.options.range;
var O;
this.start=kendo.date.firstDayOfMonth(new Date(Q.start.setMonth(0)));
this.end=kendo.date.firstDayOfMonth(new Date(Q.end.setMonth(12)));
if(P&&P.start){this.start=kendo.date.firstDayOfMonth(P.start);
}if(P&&P.end){O=kendo.date.firstDayOfMonth(P.end);
this.end=kendo.date.getDate(new Date(O.setMonth(O.getMonth()+1)));
}},_createSlots:function(){var P=[];
var O=this._months(this.start,this.end);
b(O).each(function(Q,R){R.span=1;
});
P.push(this._years(this.start,this.end));
P.push(O);
return P;
},_layout:function(){var P=[];
var O=this.options;
P.push(this._slotHeaders(this._slots[0],kendo.template(O.yearHeaderTemplate)));
P.push(this._slotHeaders(this._slots[1],kendo.template(O.monthHeaderTemplate)));
return P;
}});
var I={wrapper:"k-timeline k-grid k-widget",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",tasksWrapper:"k-gantt-tables",dependenciesWrapper:"k-gantt-dependencies",task:"k-task",line:"k-line",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskDragHandle:"k-task-draghandle",taskComplete:"k-task-complete",taskDelete:"k-task-delete",taskWrapActive:"k-task-wrap-active",taskWrap:"k-task-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",hovered:"k-state-hover",selected:"k-state-selected",origin:"k-origin"};
var k=kendo.ui.GanttTimeline=M.extend({init:function(O,P){M.fn.init.call(this,O,P);
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}o=kendo.support.isRtl(O);
this._wrapper();
this._domTrees();
this._views();
this._selectable();
this._draggable();
this._resizable();
this._percentResizeDraggable();
this._createDependencyDraggable();
this._attachEvents();
this._tooltip();
},options:{name:"GanttTimeline",messages:{views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"}},snap:true,selectable:true,editable:true},destroy:function(){M.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
if(this._currentTimeUpdateTimer){clearInterval(this._currentTimeUpdateTimer);
}this._unbindView(this._selectedView);
if(this._moveDraggable){this._moveDraggable.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}if(this._percentDraggable){this._percentDraggable.destroy();
}if(this._dependencyDraggable){this._dependencyDraggable.destroy();
}if(this.touch){this.touch.destroy();
}this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
this.wrapper.off(y);
kendo.destroy(this.wrapper);
},_wrapper:function(){var Q=k.styles;
var R=this;
var P=this.options;
var O=function(){var V=typeof P.rowHeight===F?P.rowHeight:P.rowHeight+"px";
var W=b(kendo.format(E,V));
var T;
var S;
var U=R.wrapper.find(i+Q.tasksWrapper);
U.append(W);
T=W.find("tr").outerHeight();
S=W.find("td").height();
W.remove();
return{row:T,cell:S};
};
this.wrapper=this.element.addClass(Q.wrapper).append("<div class='"+Q.gridHeader+"'><div class='"+Q.gridHeaderWrap+"'></div></div>").append("<div class='"+Q.gridContentWrap+"'><div class='"+Q.tasksWrapper+"'></div><div class='"+Q.dependenciesWrapper+"'></div></div>");
if(P.rowHeight){this._calculatedSize=O();
}},_domTrees:function(){var O=k.styles;
var P=kendo.dom.Tree;
var Q=this.wrapper;
this._headerTree=new P(Q.find(i+O.gridHeaderWrap)[0]);
this._taskTree=new P(Q.find(i+O.tasksWrapper)[0]);
this._dependencyTree=new P(Q.find(i+O.dependenciesWrapper)[0]);
},_views:function(){var V=this.options.views;
var U;
var Q;
var S;
var O;
var T;
this.views={};
for(var P=0,R=V.length;
P<R;
P++){U=V[P];
Q=n(U);
if(Q&&U.selectable===false){continue;
}S=Q?typeof U.type!=="string"?U.title:U.type:U;
O=h[S];
if(O){if(Q){U.type=O.type;
}O.title=this.options.messages.views[S];
}U=j({title:S},O,Q?U:{});
if(S){this.views[S]=U;
if(!T||U.selected){T=S;
}}}if(T){this._selectedViewName=T;
}},view:function(O){if(O){this._selectView(O);
this.trigger("navigate",{view:O,action:"changeView"});
}return this._selectedView;
},_selectView:function(O){if(O&&this.views[O]){if(this._selectedView){this._unbindView(this._selectedView);
}this._selectedView=this._initializeView(O);
this._selectedViewName=O;
}},_viewByIndex:function(O){var P;
var Q=this.views;
for(P in Q){if(!O){return P;
}O--;
}},_initializeView:function(O){var S=this.views[O];
if(S){var R=S.type;
if(typeof R==="string"){R=kendo.getter(S.type)(window);
}if(R){var Q={};
j(Q,this.options.range,S.range);
var P=S.date||this.options.date;
S=new R(this.wrapper,J(j(true,{headerTree:this._headerTree,taskTree:this._taskTree,dependencyTree:this._dependencyTree,calculatedSize:this._calculatedSize},S,this.options,{date:P,range:Q})));
}else{throw new Error("There is no such view");
}}return S;
},_unbindView:function(O){if(O){O.destroy();
}},_range:function(S){var R={field:"start",dir:"asc"};
var P={field:"end",dir:"desc"};
if(!S||!S.length){return{start:new Date(),end:new Date()};
}var Q=new B(S).sort(R).toArray()[0].start||new Date();
var O=new B(S).sort(P).toArray()[0].end||new Date();
return{start:new Date(Q),end:new Date(O)};
},_render:function(Q){var R=this.view();
var P=this._range(Q);
var O=R.options.date;
this._tasks=Q;
R.range(P);
R.renderLayout();
R.render(Q);
if(O){R._scrollToDate(O);
}},_renderDependencies:function(O){this.view()._renderDependencies(O);
},_taskByUid:function(S){var R=this._tasks;
var P=R.length;
var Q;
for(var O=0;
O<P;
O++){Q=R[O];
if(Q.uid===S){return Q;
}}},_draggable:function(){var W=this;
var R;
var V;
var P;
var T;
var S=this.options.snap;
var U=k.styles;
var Q=this.options.editable;
var O=function(){W.view()._removeDragHint();
if(R){R.css("opacity",1);
}R=null;
V=null;
W.dragInProgress=false;
};
if(!Q||Q.move===false||Q.update===false){return;
}this._moveDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+U.task,holdToDrag:kendo.support.mobileOS,ignore:i+U.taskResizeHandle});
this._moveDraggable.bind("dragstart",function(X){var Y=W.view();
R=X.currentTarget.parent();
V=W._taskByUid(X.currentTarget.attr("data-uid"));
if(W.trigger("moveStart",{task:V})){X.preventDefault();
return;
}P=V.start;
T=Y._timeByPosition(X.x.location,S)-P;
Y._createDragHint(R);
R.css("opacity",0.5);
clearTimeout(W._tooltipTimeout);
W.dragInProgress=true;
}).bind("drag",kendo.throttle(function(Y){if(!W.dragInProgress){return;
}var aa=W.view();
var X=new Date(aa._timeByPosition(Y.x.location,S)-T);
var Z=X;
if(!W.trigger("move",{task:V,start:X})){P=X;
if(o){Z=new Date(P.getTime()+V.duration());
}aa._updateDragHint(Z);
}},15)).bind("dragend",function(){W.trigger("moveEnd",{task:V,start:P});
O();
}).bind("dragcancel",function(){O();
}).userEvents.bind("select",function(){c();
});
},_resizable:function(){var X=this;
var S;
var W;
var Q;
var P;
var T;
var U=this.options.snap;
var V=k.styles;
var R=this.options.editable;
var O=function(){X.view()._removeResizeHint();
S=null;
W=null;
X.dragInProgress=false;
};
if(!R||R.resize===false||R.update===false){return;
}this._resizeDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+V.taskResizeHandle,holdToDrag:false});
this._resizeDraggable.bind("dragstart",function(Y){T=Y.currentTarget.hasClass(V.taskResizeHandleWest);
if(o){T=!T;
}S=Y.currentTarget.closest(i+V.task);
W=X._taskByUid(S.attr("data-uid"));
if(X.trigger("resizeStart",{task:W})){Y.preventDefault();
return;
}Q=W.start;
P=W.end;
X.view()._createResizeHint(W);
clearTimeout(X._tooltipTimeout);
X.dragInProgress=true;
}).bind("drag",kendo.throttle(function(Z){if(!X.dragInProgress){return;
}var aa=X.view();
var Y=aa._timeByPosition(Z.x.location,U,!T);
if(T){if(Y<P){Q=Y;
}else{Q=P;
}}else{if(Y>Q){P=Y;
}else{P=Q;
}}if(!X.trigger("resize",{task:W,start:Q,end:P})){aa._updateResizeHint(Q,P,T);
}},15)).bind("dragend",function(){X.trigger("resizeEnd",{task:W,resizeStart:T,start:Q,end:P});
O();
}).bind("dragcancel",function(){O();
}).userEvents.bind("select",function(){c();
});
},_percentResizeDraggable:function(){var Y=this;
var V;
var W;
var X;
var Z;
var T;
var S;
var P;
var ab;
var aa;
var U=k.styles;
var Q;
var R=this.options.editable;
var O=function(){Y.view()._removePercentCompleteTooltip();
W=null;
V=null;
Y.dragInProgress=false;
};
var ac=function(ad){W.find(i+U.taskComplete).width(ad).end().siblings(i+U.taskDragHandle).css(o?"right":"left",ad);
};
if(!R||R.dragPercentComplete===false||R.update===false){return;
}this._percentDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+U.taskDragHandle,holdToDrag:false});
this._percentDraggable.bind("dragstart",function(ad){if(Y.trigger("percentResizeStart")){ad.preventDefault();
return;
}W=ad.currentTarget.siblings(i+U.task);
V=Y._taskByUid(W.attr("data-uid"));
P=V.percentComplete;
X=W.offset();
Z=this.element.offset();
T=W.find(i+U.taskComplete).width();
S=W.outerWidth();
clearTimeout(Y._tooltipTimeout);
Y.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ae){if(!Y.dragInProgress){return;
}Q=o?-ae.x.initialDelta:ae.x.initialDelta;
var ad=Math.max(0,Math.min(S,T+Q));
P=Math.round(ad/S*100);
ac(ad);
ab=X.top-Z.top;
aa=X.left+ad-Z.left;
if(o){aa+=S-2*ad;
}Y.view()._updatePercentCompleteTooltip(ab,aa,P);
},15)).bind("dragend",function(){Y.trigger("percentResizeEnd",{task:V,percentComplete:P/100});
O();
}).bind("dragcancel",function(){ac(T);
O();
}).userEvents.bind("select",function(){c();
});
},_createDependencyDraggable:function(){var W=this;
var S;
var Q=b();
var R=b();
var T;
var U;
var Y=d.msie&&d.version<9;
var V=k.styles;
var P=this.options.editable;
var O=function(){S.css("display","").removeClass(V.hovered);
S.parent().removeClass(V.origin);
S=null;
X(false);
R=b();
Q=b();
W.view()._removeDependencyDragHint();
W.dragInProgress=false;
};
var X=function(Z){if(!R.hasClass(V.origin)){R.find(i+V.taskDot).css("display",Z?"block":"");
Q.toggleClass(V.hovered,Z);
}};
if(!P||P.dependencyCreate===false){return;
}if(Y&&document.namespaces){document.namespaces.add("kvml","urn:schemas-microsoft-com:vml","#default#VML");
}this._dependencyDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:i+V.taskDot,holdToDrag:false});
this._dependencyDraggable.bind("dragstart",function(Z){if(W.trigger("dependencyDragStart")){Z.preventDefault();
return;
}S=Z.currentTarget.css("display","block").addClass(V.hovered);
S.parent().addClass(V.origin);
var aa=S.offset();
var ab=W.wrapper.find(i+V.tasksWrapper).offset();
T=Math.round(aa.left-ab.left+S.outerHeight()/2);
U=Math.round(aa.top-ab.top+S.outerWidth()/2);
clearTimeout(W._tooltipTimeout);
W.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ab){if(!W.dragInProgress){return;
}W.view()._removeDependencyDragHint();
var ad=b(kendo.elementUnderCursor(ab));
var ac=W.wrapper.find(i+V.tasksWrapper).offset();
var Z=ab.x.location-ac.left;
var aa=ab.y.location-ac.top;
W.view()._updateDependencyDragHint({x:T,y:U},{x:Z,y:aa},Y);
X(false);
Q=ad.hasClass(V.taskDot)?ad:b();
R=ad.closest(i+V.taskWrap);
X(true);
},15)).bind("dragend",function(){if(Q.length){var Z=S.hasClass(V.taskDotStart);
var ac=Q.hasClass(V.taskDotStart);
var ad=Z?ac?3:2:ac?1:0;
var aa=W._taskByUid(S.siblings(i+V.task).attr("data-uid"));
var ab=W._taskByUid(Q.siblings(i+V.task).attr("data-uid"));
if(aa!==ab){W.trigger("dependencyDragEnd",{type:ad,predecessor:aa,successor:ab});
}}O();
}).bind("dragcancel",function(){O();
}).userEvents.bind("select",function(){c();
});
},_selectable:function(){var P=this;
var O=k.styles;
if(this.options.selectable){this.wrapper.on(e+y,i+O.task,function(Q){Q.stopPropagation();
if(!Q.ctrlKey){P.trigger("select",{uid:b(this).attr("data-uid")});
}else{P.trigger("clear");
}}).on(e+y,i+O.taskWrap,function(Q){Q.stopPropagation();
b(this).css("z-index","0");
var R=b(document.elementFromPoint(Q.clientX,Q.clientY));
if(R.hasClass(O.line)){R.click();
}b(this).css("z-index","");
}).on(e+y,i+O.tasksWrapper,function(){if(P.selectDependency().length>0){P.clearSelection();
}else{P.trigger("clear");
}}).on(e+y,i+O.line,function(Q){Q.stopPropagation();
P.selectDependency(this);
});
}},select:function(Q){var O=this.wrapper.find(Q);
var P=k.styles;
if(O.length){this.clearSelection();
O.addClass(P.selected);
if(kendo.support.mobileOS){O.parent().addClass(P.taskWrapActive);
}return;
}return this.wrapper.find(i+P.task+i+P.selected);
},selectDependency:function(R){var O=this.wrapper.find(R);
var Q;
var P=k.styles;
if(O.length){this.clearSelection();
this.trigger("clear");
Q=b(O).attr("data-uid");
this.wrapper.find(i+P.line+"[data-uid='"+Q+"']").addClass(P.selected);
return;
}return this.wrapper.find(i+P.line+i+P.selected);
},clearSelection:function(){var O=k.styles;
this.wrapper.find(i+O.selected).removeClass(O.selected);
if(kendo.support.mobileOS){this.wrapper.find(i+O.taskWrapActive).removeClass(O.taskWrapActive);
}},_attachEvents:function(){var Q=this;
var P=k.styles;
var O=this.options.editable;
if(O){this._tabindex();
this.wrapper.on(e+y,i+P.taskDelete,function(R){Q.trigger("removeTask",{uid:b(this).closest(i+P.task).attr("data-uid")});
R.stopPropagation();
R.preventDefault();
}).on(s+y,function(R){var T;
var S=Q.options.editable;
if(R.keyCode===t.DELETE&&S&&S.dependencyDestroy!==false){T=Q.selectDependency();
if(T.length){Q.trigger("removeDependency",{uid:T.attr("data-uid")});
Q.clearSelection();
}}});
if(!kendo.support.mobileOS){this.wrapper.on(g+y,i+P.task,function(R){if(Q.options.editable.update!==false){Q.trigger("editTask",{uid:b(this).attr("data-uid")});
R.stopPropagation();
R.preventDefault();
}});
}else{this.touch=this.wrapper.kendoTouch({filter:i+P.task,doubletap:function(R){if(Q.options.editable.update!==false){Q.trigger("editTask",{uid:b(R.touch.currentTarget).attr("data-uid")});
}}}).data("kendoTouch");
}}},_tooltip:function(){var R=this;
var S=this.options.tooltip;
var Q=k.styles;
var O;
var P=function(T){O=T.clientX;
};
if(S&&S.visible===false){return;
}if(!kendo.support.mobileOS){this.wrapper.on(v+y,i+Q.task,function(){var T=this;
var U=R._taskByUid(b(this).attr("data-uid"));
if(R.dragInProgress){return;
}R._tooltipTimeout=setTimeout(function(){R.view()._createTaskTooltip(U,T,O);
},800);
b(this).on(x,P);
}).on(w+y,i+Q.task,function(){clearTimeout(R._tooltipTimeout);
R.view()._removeTaskTooltip();
b(this).off(x,P);
});
}else{this.wrapper.on(e+y,i+Q.taskDelete,function(T){T.stopPropagation();
R.view()._removeTaskTooltip();
}).on(w+y,i+Q.task,function(T){var U=b(T.relatedTarget).parents(i+Q.taskWrap,i+Q.task);
if(U.length===0){R.view()._removeTaskTooltip();
}});
if(this.touch){this.touch.bind("tap",function(U){var V=U.touch.target;
var W=R._taskByUid(b(V).attr("data-uid"));
var T=U.touch.x.client;
if(R.view()._taskTooltip){R.view()._removeTaskTooltip();
}R.view()._createTaskTooltip(W,V,T);
}).bind("doubletap",function(){R.view()._removeTaskTooltip();
});
}}}});
j(true,k,{styles:I});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
