using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Text;
using System.Web.UI;
   
//
// Les informations gnrales relatives  un assembly dpendent de 
// l'ensemble d'attributs suivant. Pour modifier les informations
// associes  un assembly, changez les valeurs de ces attributs.
//
[assembly: AssemblyTitle("Active Web.Controls")]
[assembly: AssemblyDescription("A web controls suite")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Active Up SPRL")]
[assembly: AssemblyProduct("Active Web.Controls")]
[assembly: AssemblyCopyright("Copyright (c) 2000-2006 Active Up SPRL - All Rights Reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]		
[assembly: AllowPartiallyTrustedCallers]

//
// Les informations de version pour un assembly se composent des quatre valeurs suivantes:
//
//      Version principale
//      Version secondaire 
//      Numro de build
//      Rvision
//
// Vous pouvez spcifier toutes les valeurs ou indiquer des numros de rvision et de build par dfaut 
// en utilisant '*', comme ci-dessous :

[assembly: AssemblyVersion("5.0.3119.50")]

// Pour signer votre assembly, vous devez spcifier la cl  utiliser. Consultez 
// la documentation Microsoft .NET Framework pour plus d'informations sur la signature d'un assembly.
//
// Utilisez les attributs ci-dessous pour contrler la cl utilise lors de la signature. 
//
// Remarques: 
//   (*) Si aucune cl n'est spcifie, l'assembly n'est pas sign.
//   (*) KeyName fait rfrence  une cl installe dans le fournisseur de
//       services cryptographiques (CSP) de votre ordinateur. KeyFile fait rfrence  un fichier qui contient
//       une cl.
//   (*) Si les valeurs de KeyFile et de KeyName sont spcifies, le 
//       traitement suivant se produit:
//       (1) Si KeyName se trouve dans le CSP, la cl est utilise.
//       (2) Si KeyName n'existe pas mais que KeyFile existe, la cl 
//           de KeyFile est installe dans le CSP et utilise.
//   (*) Pour crer KeyFile, vous pouvez utiliser l'utilitaire sn.exe (Strong Name, Nom fort).
//        Lors de la spcification de KeyFile, son emplacement doit tre
//        relatif au rpertoire de sortie du projet qui est
//       %Project Directory%\obj\<configuration>. Par exemple, si votre KeyFile se trouve
//       dans le rpertoire du projet, vous devez spcifier l'attribut 
//       AssemblyKeyFile sous la forme [assembly: AssemblyKeyFile("..\\..\\mykey.snk")]
//   (*) DelaySign (signature diffre) est une option avance. Pour plus d'informations, consultez la
//       documentation Microsoft .NET Framework.
//
[assembly: AssemblyDelaySign(false)]
//[assembly: AssemblyKeyFile("")]
//[assembly: AssemblyKeyFile(@"..\..\ActiveUp.WebControls.snk")]
[assembly: AssemblyKeyFile(@"ActiveUp.WebControls.snk")]
[assembly: AssemblyKeyName("")]
[assembly: InternalsVisibleTo("ActiveUp.WebControls.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100db6d0447d837c3" +
"39286106da0940aa4a483ae2a3149e01659adedf6e63b45ef84a874a45a5915f61ffcecbf22cdb" +
"0ead075ba5cea8811cae4ec0cdaae7634730e1907ffbab90b239a69cde87714b66cde066d6e0d4" +
"253785cec5abe8520a0bde065b9432cee21045b13b7b69a6416326202210d16d8532ced424e945" +
"86ee42b3")]

#if (!FX1_1)
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveAjax.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveAutoSuggest.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveCalendar.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveImage.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveInput.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveLoader.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveMenu.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActivePanel.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveRotator.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveSlider.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveTimer.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveToolbar.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveTree.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlProtector.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlTextBox.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlTextBox_Startup.js", "text/javascript", PerformSubstitution = true)]

[assembly: WebResource("ActiveUp.WebControls._resources.Images.aligncenter_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.aligncenter_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignjustify_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignjustify_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignleft_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignleft_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignright_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignright_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.back_l.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bold_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bold_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bolditalicunderline_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bolditalicunderline_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.canvassize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.canvassize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.close.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codecleaner_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codecleaner_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codesnippets_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codesnippets_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.color.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.dock.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.copy_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.copy_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.crop_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.crop_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.customtags_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.customtags_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.cut_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.cut_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.delete_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.delete_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.down.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.edit_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.edit_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.find_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.find_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.findandreplace_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.findandreplace_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flash_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flash_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flip_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flip_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontcolor_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontcolor_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontface_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontface_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontsize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontsize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.highlight_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.highlight_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.image_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.image_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.imagesize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.imagesize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.indent_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.indent_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.italic_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.italic_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.library_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.library_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.link_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.link_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.mirror_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.mirror_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.orderedlist_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.orderedlist_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.outdent_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.outdent_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paragraph_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paragraph_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paste_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paste_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.print_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.print_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.redo_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.redo_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.replace_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.replace_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rotate_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rotate_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rule_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rule_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.save_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.save_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.saveas_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.saveas_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.separator.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spacer.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.specialchars_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.specialchars_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spell_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spell_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.strikethrough_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.strikethrough_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.style_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.style_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.subscript_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.subscript_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.superscript_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.superscript_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_design.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_html.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_preview.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.table_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.table_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.text_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.text_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.underline_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.underline_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.undo_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.undo_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.unorderedlist_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.unorderedlist_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.upload_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.upload_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.zoom_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.zoom_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_down_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_left_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_right_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_up_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.collapsed.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.expanded.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.drop.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.resize.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.minus.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.plus.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.folder.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.picker.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowUpOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowUpOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowDownOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowDownOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.BackgroundVertOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.BackgroundVertOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertCenterOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertGrabberOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertEndOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertStartOff.gif", "image/gif")]
#endif

#if (!FX1_1)
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveAjax.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveCalendar.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveImage.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveInput.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveLoader.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveMenu.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActivePanel.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveRotator.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveSlider.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveTimer.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveToolbar.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.ActiveTree.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlProtector.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlTextBox.js", "text/javascript", PerformSubstitution = true)]
[assembly: WebResource("ActiveUp.WebControls._resources.HtmlTextBox_Startup.js", "text/javascript", PerformSubstitution = true)]

[assembly: WebResource("ActiveUp.WebControls._resources.Images.aligncenter_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.aligncenter_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignjustify_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignjustify_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignleft_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignleft_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignright_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.alignright_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.back_l.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bold_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bold_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bolditalicunderline_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.bolditalicunderline_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.canvassize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.canvassize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.close.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codecleaner_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codecleaner_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codesnippets_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.codesnippets_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.color.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.copy_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.copy_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.crop_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.crop_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.customtags_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.customtags_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.cut_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.cut_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.delete_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.delete_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.down.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.edit_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.edit_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.find_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.find_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.findandreplace_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.findandreplace_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flash_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flash_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flip_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.flip_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontcolor_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontcolor_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontface_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontface_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontsize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.fontsize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.highlight_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.highlight_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.image_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.image_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.imagesize_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.imagesize_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.indent_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.indent_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.italic_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.italic_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.library_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.library_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.link_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.link_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.mirror_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.mirror_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.orderedlist_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.orderedlist_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.outdent_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.outdent_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paragraph_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paragraph_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paste_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.paste_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.print_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.print_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.redo_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.redo_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.replace_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.replace_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rotate_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rotate_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rule_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.rule_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.save_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.save_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.saveas_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.saveas_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.separator.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spacer.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.specialchars_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.specialchars_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spell_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.spell_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.strikethrough_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.strikethrough_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.style_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.style_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.subscript_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.subscript_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.superscript_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.superscript_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_design.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_html.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.tab_preview.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.table_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.table_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.text_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.text_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.underline_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.underline_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.undo_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.undo_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.unorderedlist_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.unorderedlist_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.upload_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.upload_over.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.zoom_off.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_down_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_left_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_right_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.arrow_up_blue.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.collapsed.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.expanded.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.drop.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.resize.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.minus.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.plus.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.folder.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.picker.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowUpOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowUpOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowDownOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ArrowDownOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.BackgroundVertOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.BackgroundVertOn.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertCenterOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertGrabberOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertEndOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.ButtonVertStartOff.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.button.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.UploadAppletDesigner.gif", "image/gif")]
[assembly: WebResource("ActiveUp.WebControls._resources.Images.UploadAppletDesigner.jpg", "image/jpg")]
#endif
