CREATE TABLE [dbo].[AdmsLog]
(
	AdmsLogId int identity(1,1),
	ClientId int not null,
	SourceFileId int not null,
	FileNameExact varchar(260) not null,
	FileStart datetime not null,
	FileEnd datetime null,
	FileStatusId int not null,
	StatusMessage varchar(max) null,
	AdmsStepId int not null,
	ProcessingStatusId int null,
	ExecutionPointId int null,
	RecordSource varchar(50) not null,
	ProcessCode varchar(50) not null,
	OriginalRecordCount int null,
	OriginalProfileCount int null,
	OriginalDemoCount int null,
	TransformedRecordCount int null,
	TransformedProfileCount int null,
	TransformedDemoCount int null,
	DuplicateRecordCount int null,
	DuplicateProfileCount int null,
	DuplicateDemoCount int null,
	FailedRecordCount int null,
	FailedProfileCount int null,
	FailedDemoCount int null,
	FinalRecordCount int null,
	FinalProfileCount int null,
	FinalDemoCount int null,
	MatchedRecordCount int null,
	UadConsensusCount int null,
	DateCreated datetime not null,
	DateUpdated datetime null,
	CreatedByUserID int not null,
	UpdatedByUserID int null,
	IgnoredRecordCount int null,
	IgnoredProfileCount int null,
	IgnoredDemoCount int null,
	DimensionRecordCount int null,
	DimensionProfileCount int null,
	CONSTRAINT [PK_AdmsLog] PRIMARY KEY CLUSTERED (AdmsLogId ASC) WITH (FILLFACTOR = 90),
	CONSTRAINT [UQ_AdmsLog_ProcessCode] UNIQUE(ProcessCode) WITH (FILLFACTOR = 90)
)
