CREATE TABLE [dbo].[FilterSchedule]
(
	FilterScheduleId int identity(1,1) not null,
	FilterId int not null,
	ExportTypeId int not null,
	IsRecurring bit default('false') not null,
	RecurrenceTypeId int not null,
	StartDate date null,
	StartTime time null,
	EndDate date null,
	RunSunday bit default('false') not null,
	RunMonday bit default('false') not null,
	RunTuesday bit default('false') not null,
	RunWednesday bit default('false') not null,
	RunThursday bit default('false') not null,
	RunFriday bit default('false') not null,
	RunSaturday bit default('false') not null,
	MonthScheduleDay int null,
	MonthLastDay bit default('false') not null,
	EmailNotification varchar(500) null,
	Server varchar(50) null,
	UserName varchar(50) null,
	Password varchar(50) null,
	Folder varchar(50) null,
	ExportFormatTypeId int not null,
	FileName varchar(50) null,
	IsDeleted bit default('false') not null,
	ClientID int not null,
	FilterGroupId_Selected int not null,
	FilterGroupId_Suppressed int not null,
	FolderId int not null,
	GroupId int not null,
	OperatorsTypeId  int not null,
	DateCreated datetime not null,
	DateUpdated datetime null,
	CreatedByUserID int not null,
	UpdatedByUserID int null,
    CONSTRAINT [PK_FilterSchedule] PRIMARY KEY CLUSTERED ([FilterScheduleID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_FilterSchedule_Filters] FOREIGN KEY ([FilterId]) REFERENCES [dbo].[Filter] ([FilterId])
)
