CREATE proc [dbo].[e_FilterSchedule_Save]
@FilterScheduleID int,
@FilterID int,
@ExportTypeID int,
@IsRecurring bit,
@RecurrenceTypeID int,
@StartDate date,
@StartTime varchar(8),
@EndDate date,
@RunSunday bit,
@RunMonday bit,
@RunTuesday bit,
@RunWednesday bit,
@RunThursday bit,
@RunFriday bit,
@RunSaturday bit,
@MonthScheduleDay int,
@MonthLastDay bit,
@UserID int,
@EmailNotification varchar(500),
@Server  varchar(50),
@UserName varchar(50),
@Password varchar(50),
@Folder varchar(50),
@ExportFormat varchar(50),
@FileName varchar(50),
@FilterGroupID_Selected varchar(500),
@FilterGroupID_Suppressed varchar(500),
@CustomerID int,
@GroupID int,
@FolderID int,
@ShowHeader bit = 0,
@ExportName varchar(50),
@ExportNotes varchar(250),
@FilterSegmentationID int,
@SelectedOperation varchar(50),
@SuppressedOperation varchar(50),
@FileNameFormat varchar(50) = null
as
BEGIN

	SET NOCOUNT ON
	
	if (@FilterScheduleID > 0)
		Begin
			Update FilterSchedule set
				FilterID = @FilterID,
				ExportTypeID = @ExportTypeID,
				IsRecurring = @IsRecurring,
				RecurrenceTypeID = @RecurrenceTypeID,
				StartDate = @StartDate,
				StartTime = @StartTime,
				EndDate = @EndDate,
				RunSunday = @RunSunday,
				RunMonday = @RunMonday,
				RunTuesday = @RunTuesday,
				RunWednesday = @RunWednesday,
				RunThursday = @RunThursday,
				RunFriday = @RunFriday,
				RunSaturday = @RunSaturday,
				MonthScheduleDay = @MonthScheduleDay,
				MonthLastDay = @MonthLastDay,
				EmailNotification = @EmailNotification,
				[Server] = @Server,
				UserName = @UserName,
				[Password] = @Password,
				Folder = @Folder, 
				ExportFormat = @ExportFormat,
				[FileName] = @FileName,
				UpdatedBy = @UserID,
				UpdatedDate = GETDATE(),
				FilterGroupID_Selected = @FilterGroupID_Selected,
				FilterGroupID_Suppressed = @FilterGroupID_Suppressed,
				CustomerID = @CustomerID,
				GroupID = @GroupID,
				FolderID = @FolderID,
				ShowHeader =  @ShowHeader,
				ExportName = @ExportName,
				ExportNotes = @ExportNotes,
				FilterSegmentationID = @FilterSegmentationID,
				SelectedOperation = @SelectedOperation,
				SuppressedOperation = @SuppressedOperation,		
				FileNameFormat = @FileNameFormat		
			where FilterScheduleID =  @FilterScheduleID	
	
			Select @FilterScheduleID
		End	
	Else	
		Begin
			insert into FilterSchedule (
				FilterID,
				ExporttypeID,
				IsRecurring,
				RecurrenceTypeID,
				StartDate,
				StartTime,
				EndDate,
				RunSunday,
				RunMonday,
				RunTuesday,
				RunWednesday,
				RunThursday,
				RunFriday,
				RunSaturday,
				MonthScheduleDay,
				MonthLastDay,
				CreatedBy,
				EmailNotification,
				[Server],
				UserName,
				[Password],
				Folder,
				ExportFormat,
				[FileName],
				CreatedDate,
				FilterGroupID_Selected,
				FilterGroupID_Suppressed,
				CustomerID,
				GroupID,
				FolderID,
				ShowHeader,
				ExportName,
				ExportNotes,
				FilterSegmentationID,
				SelectedOperation,
				SuppressedOperation,
				FileNameFormat) 
			values (
				@FilterID,
				@ExportTypeID,
				@IsRecurring,
				@RecurrenceTypeID,
				@StartDate,
				@StartTime,
				@EndDate,
				@RunSunday,
				@RunMonday,
				@RunTuesday,
				@RunWednesday,
				@RunThursday,
				@RunFriday,
				@RunSaturday,
				@MonthScheduleDay,
				@MonthLastDay,
				@UserID,
				@EmailNotification,
				@Server,
				@UserName,
				@Password,
				@Folder, 
				@ExportFormat,
				@FileName,
				GETDATE(),
				@FilterGroupID_Selected,
				@FilterGroupID_Suppressed,
				@CustomerID,
				@GroupID,
				@FolderID,
				@ShowHeader,
				@ExportName,
				@ExportNotes,
				@FilterSegmentationID,
				@SelectedOperation,
				@SuppressedOperation,
				@FileNameFormat)

			Select @@IDENTITY;
			
		End 
End