CREATE PROCEDURE e_IssueArchiveProductSubscription_Save
@IssueArchiveSubscriptionId int,
@IsComp bit,
@CompId int,
@IssueID int = 0,
@PubSubscriptionID int,
@SubscriptionID	int,
@PubID int,
@Demo7 varchar(1),
@QualificationDate date,
@PubQSourceID int,
@PubCategoryID int,
@PubTransactionID int,
@EmailStatusID int,
@StatusUpdatedDate datetime,
@StatusUpdatedReason varchar(200),
@Email varchar(100),
@DateCreated datetime,
@DateUpdated datetime,
@CreatedByUserID int,
@UpdatedByUserID int,
@SubscriptionStatusID int = 1,
@AddRemoveID int = 0,
@Copies int = 1,
@GraceIssues int = 0,
@IMBSEQ varchar(256) = '',
@IsActive bit = 'true',
@IsPaid bit = 'false',
@IsSubscribed bit = 'fasle',
@MemberGroup varchar(256) = '',
@OnBehalfOf varchar(256) = '',
@OrigsSrc varchar(256) = '',
@Par3CID  varchar(256) = '',
@SequenceID int = 0, 
@Status  varchar(256) = '',
@SubscriberSourceCode  varchar(256) = '',
@SubSrcID varchar(256) = '',
@Verified varchar(100) = '',
@ExternalKeyID int = 0,
@FirstName varchar(50) = '',
@LastName varchar(50) = '',
@Company varchar(100) = '',
@Title varchar(50) = '',
@Occupation varchar(50) = '',
@AddressTypeID int = 0,
@Address1 varchar(100) = '',
@Address2 varchar(100) = '',
@Address3 varchar(100) = '',
@City varchar(50) = '',
@RegionCode varchar(50) = 0,
@RegionID int = 0,
@ZipCode varchar(10) = '',
@Plus4 varchar(10) = '',
@CarrierRoute varchar(10) = '',
@County varchar(50) = '',
@Country varchar(50) = '',
@CountryID int = 0,
@Latitude decimal(18,15) = 0,
@Longitude decimal(18,15) = 0,
@IsAddressValidated bit = 0,
@AddressValidationDate datetime = '',
@AddressValidationSource varchar(50) = '',
@AddressValidationMessage varchar(max) = '',
@Phone varchar(50) = '',
@Fax varchar(50) = '',
@Mobile varchar(50) = '',
@Website varchar(100) = '',
@Birthdate date = '',
@Age int = 0,
@Income varchar(50) = '',
@Gender varchar(50) = '',
@PhoneExt varchar(25) = '',
@IsInActiveWaveMailing bit = 0,
@AddressTypeCodeId int = 0,
@AddressLastUpdatedDate datetime = '',
@AddressUpdatedSourceTypeCodeId int = 0,
@WaveMailingID int = 0,
@IGrp_No uniqueidentifier = '',
@SFRecordIdentifier uniqueidentifier = ''
AS
BEGIN

	SET NOCOUNT ON

	IF @IssueArchiveSubscriptionId > 0
		BEGIN
			IF @DateUpdated IS NULL
				BEGIN
					SET @DateUpdated = GETDATE();
				END
			UPDATE IssueArchiveProductSubscription
			SET PubSubscriptionID = @PubSubscriptionID,
				IsComp = @IsComp,
				CompId = @CompId,
				IssueID = @IssueID,
				[SubscriptionID] = @SubscriptionID,
				[PubID] = @PubID,
				[Demo7] = @Demo7,
				[QualificationDate] = @QualificationDate,
				[PubQSourceID] = @PubQSourceID,
				[PubCategoryID] = @PubCategoryID,
				[PubTransactionID] = @PubTransactionID,
				[EmailStatusID] = @EmailStatusID,
				[StatusUpdatedDate] = @StatusUpdatedDate,
				[StatusUpdatedReason] = @StatusUpdatedReason,
				[Email] = @Email,
				[DateCreated] = @DateCreated,
				[DateUpdated] = @DateUpdated,
				[CreatedByUserID] = @CreatedByUserID,
				[UpdatedByUserID] = @UpdatedByUserID,
				[SubscriptionStatusID] = @SubscriptionStatusID,
				[AddRemoveID] = @AddRemoveID,
				[Copies] = @Copies,
				[GraceIssues] = @GraceIssues,
				[IMBSEQ] = @IMBSEQ,
				[IsActive]	= @IsActive,
				[IsPaid] = @IsPaid,
				[IsSubscribed] = @IsSubscribed,
				[MemberGroup] = @MemberGroup,
				[OnBehalfOf] = @OnBehalfOf,
				[OrigsSrc] = @OrigsSrc,
				[Par3CID]	= @Par3CID,
				[SequenceID] = @SequenceID, 
				[Status] = @Status,
				[SubscriberSourceCode] = @SubscriberSourceCode,
				[SubSrcID] = @SubSrcID,
				[Verify] = @Verified,
				ExternalKeyID = @ExternalKeyID,
				FirstName = @FirstName,
				LastName = @LastName,
				Company = @Company,
				Title = @Title,
				Occupation = @Occupation,
				AddressTypeID = @AddressTypeID,
				Address1 = @Address1,
				Address2 = @Address2,
				Address3 = @Address3,
				City = @City,
				RegionCode = @RegionCode,
				RegionID = @RegionID,
				ZipCode = @ZipCode,
				Plus4 = @Plus4,
				CarrierRoute = @CarrierRoute,
				County = @County,
				Country = @Country,
				CountryID = @CountryID,
				Latitude = @Latitude,
				Longitude = @Longitude,
				IsAddressValidated = @IsAddressValidated,
				AddressValidationDate = @AddressValidationDate,
				AddressValidationSource = @AddressValidationSource,
				AddressValidationMessage = @AddressValidationMessage,
				Phone = @Phone,
				Fax = @Fax,
				Mobile = @Mobile,
				Website = @Website,
				Birthdate = @Birthdate,
				Age = @Age,
				Income = @Income,
				Gender = @Gender, 
				PhoneExt = @PhoneExt,
				IsInActiveWaveMailing = @IsInActiveWaveMailing,
				AddressTypeCodeId = @AddressTypeCodeId,
				AddressLastUpdatedDate = @AddressLastUpdatedDate,
				AddressUpdatedSourceTypeCodeId = @AddressUpdatedSourceTypeCodeId,
				WaveMailingID = @WaveMailingID,
				IGrp_No = @IGrp_No,
				SFRecordIdentifier = @SFRecordIdentifier
			WHERE IssueArchiveSubscriptionId = @IssueArchiveSubscriptionId;

			SELECT @IssueArchiveSubscriptionId;
		END
	ELSE
		BEGIN
			IF @DateCreated IS NULL
				BEGIN
					SET @DateCreated = GETDATE();
				END
			INSERT INTO IssueArchiveProductSubscription (IsComp,CompID,IssueID,PubSubscriptionID,[SubscriptionID],[PubID],[Demo7],[QualificationDate],[PubQSourceID],[PubCategoryID],[PubTransactionID],[EmailStatusID],[StatusUpdatedDate],[StatusUpdatedReason],
				[Email],[DateCreated],[DateUpdated],[CreatedByUserID],[UpdatedByUserID],[SubscriptionStatusID],[AddRemoveID],[Copies],	[GraceIssues],[IMBSEQ],[IsActive],[IsPaid],[IsSubscribed],
				[MemberGroup],[OnBehalfOf],[OrigsSrc],[Par3CID],[SequenceID],[Status],[SubscriberSourceCode],[SubSrcID],[Verify],ExternalKeyID,FirstName,LastName,Company,Title,Occupation,AddressTypeID,Address1,
				Address2,Address3,City,RegionCode,RegionID,ZipCode,Plus4,CarrierRoute,County,Country,CountryID,Latitude,Longitude,IsAddressValidated,AddressValidationDate,AddressValidationSource,
				AddressValidationMessage,Phone,Fax,Mobile,Website,Birthdate,Age,Income,Gender,PhoneExt,AddressTypeCodeId,AddressLastUpdatedDate,AddressUpdatedSourceTypeCodeId, 
				IsInActiveWaveMailing, WaveMailingID, IGrp_No, SFRecordIdentifier)
			VALUES(@IsComp,@CompId,@IssueID,@PubSubscriptionID,@SubscriptionID,@PubID,@Demo7,@QualificationDate,@PubQSourceID,@PubCategoryID,@PubTransactionID,@EmailStatusID,@StatusUpdatedDate,@StatusUpdatedReason,@Email,@DateCreated,@DateUpdated,
				@CreatedByUserID,@UpdatedByUserID,@SubscriptionStatusID,@AddRemoveID,@Copies,@GraceIssues,@IMBSEQ,@IsActive,@IsPaid,@IsSubscribed,@MemberGroup,@OnBehalfOf,@OrigsSrc,@Par3CID,
				@SequenceID,@Status,@SubscriberSourceCode,@SubSrcID,@Verified,@ExternalKeyID,@FirstName,@LastName,@Company,@Title,@Occupation,@AddressTypeID,@Address1,@Address2,@Address3,@City,@RegionCode,@RegionID,@ZipCode,@Plus4,@CarrierRoute,@County,
				@Country,@CountryID,@Latitude,@Longitude,@IsAddressValidated,@AddressValidationDate,@AddressValidationSource,@AddressValidationMessage,@Phone,@Fax,@Mobile,
				@Website,@Birthdate,@Age,@Income,@Gender,@PhoneExt,@AddressTypeCodeId,@AddressLastUpdatedDate,@AddressUpdatedSourceTypeCodeId, 
				@IsInActiveWaveMailing, @WaveMailingID, @IGrp_No, @SFRecordIdentifier);
				SELECT @@IDENTITY;
		END

END
GO