CREATE PROCEDURE e_IssueArchiveSubscription_Save
@IssueArchiveSubscriptionId int,
@IssueId int,
@IsComp bit,
@CompId int ,
@SubscriptionID int,
@Sequence int,
@FName varchar(100),
@LName varchar(100),
@Title varchar(100),
@Company	varchar(100),
@Address	varchar(255),
@MailStop varchar(255),
@City varchar(50),
@State varchar(50),
@Zip	varchar(10),
@Plus4 varchar(4),
@ForZip varchar(50),
@County varchar(20),
@Country varchar(100),
@CountryID int,
@Phone varchar(100),
@PhoneExists	bit,
@Fax	varchar(100),
@FaxExists bit,
@Email varchar(100),
@EmailExists	bit,
@CategoryID int,
@TransactionID int,
@TransactionDate smalldatetime,
@QDate datetime,
@QSourceID int,
@RegCode	varchar(5),
@Verified varchar(100),
@SubSrc varchar(8),
@OrigsSrc varchar(8),
@Par3C varchar(1),
@Demo31 bit,
@Demo32 bit,
@Demo33 bit,
@Demo34 bit,
@Demo35 bit,
@Demo36 bit,
@Source varchar(50),
@Priority varchar(4),
@IGrp_Cnt int,
@CGrp_No int,
@CGrp_Cnt int,
@StatList bit,
@Sic varchar(8),
@SicCode varchar(20),
@Gender varchar(1024),
@IGrp_Rank varchar(2),
@CGrp_Rank varchar(2),
@Address3 varchar(255),
@Home_Work_Address varchar(10),
@PubIDs varchar(2000),
@Demo7 varchar(1),
@IsExcluded bit,
@Mobile varchar(30),
@Latitude decimal(18,15),
@Longitude decimal(18,15),
@IsLatLonValid bit,
@LatLonMsg nvarchar(1000),
@Score int,
@IGrp_No uniqueidentifier,
@Notes varchar(2000),
@DateCreated datetime,
@DateUpdated datetime,
@CreatedByUserID int,
@UpdatedByUserID int,
@AddressTypeCodeId int,
@AddressLastUpdatedDate datetime,
@AddressUpdatedSourceTypeCodeId int,
@IsActive BIT = 'true',
@IsMailable BIT = 'true',
@AccountNumber VARCHAR(256) = '',
@AddRemoveID int = 0,
@AddressValidationDate DateTime = '',
@AddressValidationMessage DateTime = '',
@AddressValidationSource DateTime = '',
@Age int = 0,
@BirthDate DateTime = '',
@CarrierRoute VARCHAR(50) = '',
@Copies int = 0,
@ExternalKeyID int = 0,
@GraceIssues int = 0,
@IMBSeq VARCHAR(256) = '',
@Income VARCHAR(256) = '',
@IsAddressValidated bit  = 'false',
@IsNewSubscription bit = 0,
@IsPaid bit = 'false',
@IsSubscribed bit = 'false',
@Occupation VARCHAR(256) = '',
@OnBehalfOf VARCHAR(256) = '',
@PhoneExt VARCHAR(50) = '',
@RegionID int = 0,
@SubscriberSourceCode VARCHAR(256) = '',
@SubscriptionStatusID int = 0,
@WaveMailingID int = 0,
@Website VARCHAR(256) = '',
@tmpSubscriptionID int = 0,
@ReqFlag int = 0
AS
BEGIN

	SET NOCOUNT ON

	IF @IssueId > 0
		BEGIN
			IF @DateUpdated IS NULL
				BEGIN
					SET @DateUpdated = GETDATE();
				END
			UPDATE IssueArchiveSubscription
			SET IssueId = @IssueId,
				IsComp = @IsComp,
				CompId = @CompId,			
				FName = @FName,
				LName = @LName,
				Title = @Title,
				Company = @Company,
				Address = @Address,
				MailStop = @MailStop,
				City = @City,
				State = @State,
				Zip = @Zip,
				Plus4 = @Plus4,
				ForZip = @ForZip,
				County = @County,
				Country = @Country,
				CountryID = @CountryID,
				Phone = @Phone,
				PhoneExists = @PhoneExists,
				Fax = @Fax,
				FaxExists = @FaxExists,
				Email = @Email,
				EmailExists = @EmailExists,
				CategoryID = @CategoryID,
				TransactionID = @TransactionID,
				TransactionDate = @TransactionDate,
				QDate = @QDate,
				QSourceID = @QSourceID,
				RegCode = @RegCode,
				Verified = @Verified,
				SubSrc = @SubSrc,
				OrigsSrc = @OrigsSrc,
				Par3C = @Par3C,
				Demo31 = @Demo31,
				Demo32 = @Demo32,
				Demo33 = @Demo33,
				Demo34 = @Demo34,
				Demo35 = @Demo35,
				Demo36 = @Demo36,
				Source = @Source,
				Priority = @Priority,
				IGrp_Cnt = @IGrp_Cnt,
				CGrp_No = @CGrp_No,
				CGrp_Cnt = @CGrp_Cnt,
				StatList = @StatList,
				Sic = @Sic,
				SicCode = @SicCode,
				Gender = @Gender,
				IGrp_Rank = @IGrp_Rank,
				CGrp_Rank = @CGrp_Rank,
				Address3 = @Address3,
				Home_Work_Address = @Home_Work_Address,
				PubIDs = @PubIDs,
				Demo7 = @Demo7,
				IsExcluded = @IsExcluded,
				Mobile = @Mobile,
				Latitude = @Latitude,
				Longitude = @Longitude,
				IsLatLonValid = @IsLatLonValid,
				LatLonMsg = @LatLonMsg,
				Score = @Score,
				IGrp_No = @IGrp_No,
				Notes = @Notes,
				AddressTypeCodeId = @AddressTypeCodeId,
				AddressLastUpdatedDate = @AddressLastUpdatedDate,
				AddressUpdatedSourceTypeCodeId = @AddressUpdatedSourceTypeCodeId,
				IsActive = @IsActive,
				IsMailable = @IsMailable,
				AccountNumber = @AccountNumber,
				AddRemoveID = @AddRemoveID,
				AddressValidationDate = @AddressValidationDate,
				AddressValidationMessage = @AddressValidationMessage,
				AddressValidationSource= @AddressValidationSource,
				Age = @Age,
				BirthDate = @BirthDate,
				CarrierRoute = @CarrierRoute,
				Copies = @Copies,
				ExternalKeyID = @ExternalKeyID,
				GraceIssues = @GraceIssues,
				IMBSeq = @IMBSeq,
				Income = @Income,
				IsAddressValidated = @IsAddressValidated,
				IsNewSubscription = @IsNewSubscription,
				IsPaid = @IsPaid,
				IsSubscribed = @IsSubscribed,
				Occupation = @Occupation,
				OnBehalfOf = @OnBehalfOf,
				PhoneExt = @PhoneExt,
				RegionID = @RegionID,
				SubscriberSourceCode = @SubscriberSourceCode,
				SubscriptionStatusID = @SubscriptionStatusID,
				WaveMailingID = @WaveMailingID,
				Website = @Website,
				IsComp = @IsComp,
				tmpSubscriptionID = @tmpSubscriptionID,
				ReqFlag = @ReqFlag
			WHERE IssueArchiveSubscriptionId = @IssueArchiveSubscriptionId;

			SELECT @IssueArchiveSubscriptionId;
		END
	ELSE
		BEGIN
			IF @DateCreated IS NULL
				BEGIN
					SET @DateCreated = GETDATE();
				END
			INSERT INTO IssueArchiveSubscription 
						(CompId,IssueId,FName,LName,Title,Company,Address,MailStop,City,State,Zip,Plus4,ForZip,County,Country,CountryID,Phone,PhoneExists,Fax,
						FaxExists,Email,EmailExists,CategoryID,TransactionID,TransactionDate,QDate,QSourceID,RegCode,Verified,SubSrc,OrigsSrc,Par3C,Demo31,Demo32,Demo33,
						Demo34,Demo35,Demo36,Source,Priority,IGrp_Cnt,CGrp_No,CGrp_Cnt,StatList,Sic,SicCode,Gender,IGrp_Rank,CGrp_Rank,Address3,Home_Work_Address,PubIDs,
						Demo7,IsExcluded,Mobile,Latitude,Longitude,IsLatLonValid,LatLonMsg,Score,IGrp_No,Notes,DateCreated,CreatedByUserID,AddressTypeCodeId,AddressLastUpdatedDate,AddressUpdatedSourceTypeCodeId,IsActive,IsMailable,
						AccountNumber,AddRemoveID,AddressValidationDate,AddressValidationMessage,AddressValidationSource,Age,BirthDate,CarrierRoute ,Copies,ExternalKeyID,GraceIssues,
						IMBSeq,Income,IsAddressValidated,IsNewSubscription,IsPaid,IsSubscribed,Occupation,OnBehalfOf,PhoneExt,RegionID,SubscriberSourceCode,SubscriptionStatusID ,
						WaveMailingID,Website,IsComp,tmpSubscriptionID, ReqFlag)
			VALUES(@CompId,@IssueId,@Sequence,@FName,@LName,@Title,@Company,@Address,@MailStop,@City,@State,@Zip,@Plus4,@ForZip,@County,@Country,@CountryID,@Phone,@PhoneExists,@Fax,
					@FaxExists,@Email,@EmailExists,@CategoryID,@TransactionID,@TransactionDate,@QDate,@QSourceID,@RegCode,@Verified,@SubSrc,@OrigsSrc,@Par3C,@Demo31,@Demo32,@Demo33,
					@Demo34,@Demo35,@Demo36,@Source,@Priority,@IGrp_Cnt,@CGrp_No,@CGrp_Cnt,@StatList,@Sic,@SicCode,@Gender,@IGrp_Rank,@CGrp_Rank,@Address3,@Home_Work_Address,@PubIDs,
					@Demo7,@IsExcluded,@Mobile,@Latitude,@Longitude,@IsLatLonValid,@LatLonMsg,@Score,@IGrp_No,@Notes,@DateCreated,@CreatedByUserID,@AddressTypeCodeId,@AddressLastUpdatedDate,@AddressUpdatedSourceTypeCodeId,@IsActive,@IsMailable,
					@AccountNumber,@AddRemoveID,@AddressValidationDate,@AddressValidationMessage,@AddressValidationSource, @Age,@BirthDate,@CarrierRoute,@Copies,@ExternalKeyID, @GraceIssues,
					@IMBSeq, @Income,@IsAddressValidated,@IsNewSubscription,@IsPaid,@IsSubscribed,@Occupation,@OnBehalfOf,@PhoneExt,@RegionID,@SubscriberSourceCode,@SubscriptionStatusID,
					@WaveMailingID, @Website,@IsComp,@tmpSubscriptionID, @ReqFlag);SELECT @@IDENTITY;
		END

END
GO