CREATE PROCEDURE [dbo].[e_SubscriberTransformed_Save]
@SubscriberTransformedID int,
@SORecordIdentifier uniqueidentifier,
@SourceFileID int,
@PubCode varchar(100),
@Sequence int,
@FName varchar(100),
@LName varchar(100),
@Title varchar(100),
@Company varchar(100),
@Address varchar(255),
@MailStop varchar(255),
@City varchar(50),
@State varchar(50),
@Zip varchar(10),
@Plus4 varchar(4),
@ForZip varchar(50),
@County varchar(20),
@Country varchar(100),
@CountryID int,
@Phone varchar(100),
@PhoneExists bit,
@Fax varchar(100),
@FaxExists bit,
@Email varchar(100),
@EmailExists bit,
@CategoryID int,
@TransactionID int,
@TransactionDate smalldatetime,
@QDate datetime,
@QSourceID int,
@RegCode varchar(5),
@Verified varchar(100),
@SubSrc varchar(8),
@OrigsSrc varchar(8),
@Par3C varchar(10),
@MailPermission bit,
@FaxPermission bit,
@PhonePermission bit,
@OtherProductsPermission bit,
@ThirdPartyPermission bit,
@EmailRenewPermission bit,
@TextPermission bit,
@Source varchar(50),
@Priority varchar(4),
@IGrp_No uniqueidentifier,
@IGrp_Cnt int,
@CGrp_No uniqueidentifier,
@CGrp_Cnt int,
@StatList bit,
@Sic varchar(8),
@SicCode varchar(20),
@Gender varchar(1024),
@IGrp_Rank varchar(2),
@CGrp_Rank varchar(2),
@Address3 varchar(255),
@Home_Work_Address varchar(10),
@PubIDs varchar(2000),
@Demo7 varchar(1),
@IsExcluded bit,
@Mobile varchar(30),
@Latitude decimal(18, 15),
@Longitude decimal(18, 15),
@IsLatLonValid bit,
@LatLonMsg nvarchar(500),
@Score int,
@EmailStatusID int,
@StatusUpdatedDate datetime,
@StatusUpdatedReason nvarchar(200),
@IsMailable bit,
@Ignore bit,
@IsDQMProcessFinished bit,
@DQMProcessDate datetime,
@IsUpdatedInLive bit,
@UpdateInLiveDate datetime,
@STRecordIdentifier uniqueidentifier,
@ProcessCode varchar(50),
@ImportRowNumber int,
@IsActive BIT = 'true',
@ExternalKeyId int = 0,
@AccountNumber varchar(50) = '',
@EmailID int = 0,
@Copies int = 0,
@GraceIssues int = 0,
@IsComp bit = 'false',
@IsPaid bit = 'false',
@IsSubscribed bit = 'true',
@Occupation varchar(50) = '',
@SubscriptionStatusID int = 0,
@SubsrcID int = 0,
@Website varchar(255),
@SubGenSubscriberID int = 0,
@SubGenSubscriptionID int = 0,
@SubGenPublicationID int = 0,
@SubGenMailingAddressId int = 0,
@SubGenBillingAddressId int = 0,
@IssuesLeft int = 0,
@UnearnedReveue money = 0,
@SubGenIsLead bit = 0,
@SubGenRenewalCode varchar(50) = '',
@SubGenSubscriptionRenewDate date = null,
@SubGenSubscriptionExpireDate date = null,
@SubGenSubscriptionLastQualifiedDate date = null
AS
BEGIN

	SET NOCOUNT ON

	IF EXISTS(SELECT SubscriberTransformedID FROM SubscriberTransformed with(nolock) WHERE SubscriberTransformedID = @SubscriberTransformedID)
		BEGIN
			UPDATE SubscriberTransformed
			SET
				SORecordIdentifier = @SORecordIdentifier,
				SourceFileID = @SourceFileID,
				PubCode = @PubCode,
				Sequence = @Sequence,
				FName = @FName,
				LName = @LName,
				Title = @Title,
				Company = @Company,
				Address = @Address,
				MailStop = @MailStop,
				City = @City,
				State = @State,
				Zip = @Zip,
				Plus4 = @Plus4,
				ForZip = @ForZip,
				County = @County,
				Country = @Country,
				CountryID = @CountryID,
				Phone = @Phone,
				--PhoneExists = @PhoneExists,
				Fax = @Fax,
				--FaxExists = @FaxExists,
				Email = @Email,
				--EmailExists = @EmailExists,
				CategoryID = @CategoryID,
				TransactionID = @TransactionID,
				TransactionDate = @TransactionDate,
				QDate = @QDate,
				QSourceID = @QSourceID,
				RegCode = @RegCode,
				Verified = @Verified,
				SubSrc = @SubSrc,
				OrigsSrc = @OrigsSrc,
				Par3C = @Par3C,
				MailPermission = @MailPermission,
				FaxPermission = @FaxPermission,
				PhonePermission = @PhonePermission,
				OtherProductsPermission = @OtherProductsPermission,
				ThirdPartyPermission = @ThirdPartyPermission,
				EmailRenewPermission = @EmailRenewPermission,
				TextPermission = @TextPermission,
				Source = @Source,
				Priority = @Priority,
				--IGrp_No = @IGrp_No,
				--IGrp_Cnt = @IGrp_Cnt,
				--CGrp_No = @CGrp_No,
				--CGrp_Cnt = @CGrp_Cnt,
				--StatList = @StatList,
				Sic = @Sic,
				SicCode = @SicCode,
				Gender = @Gender,
				--IGrp_Rank = @IGrp_Rank,
				--CGrp_Rank = @CGrp_Rank,
				Address3 = @Address3,
				Home_Work_Address = @Home_Work_Address,
				--PubIDs = @PubIDs,
				Demo7 = @Demo7,
				--IsExcluded = @IsExcluded,
				Mobile = @Mobile,
				Latitude = @Latitude,
				Longitude = @Longitude,
				IsLatLonValid = @IsLatLonValid,
				LatLonMsg = @LatLonMsg,
				--Score = @Score,
				EmailStatusID = @EmailStatusID,
				--StatusUpdatedDate = @StatusUpdatedDate,
				--StatusUpdatedReason = @StatusUpdatedReason,
				--IsMailable = @IsMailable,
				--Ignore = @Ignore,
				--IsDQMProcessFinished = @IsDQMProcessFinished,
				--DQMProcessDate = @DQMProcessDate,
				--IsUpdatedInLive = @IsUpdatedInLive,
				--UpdateInLiveDate = @UpdateInLiveDate,
				STRecordIdentifier = @STRecordIdentifier,
				ProcessCode = @ProcessCode,
				ImportRowNumber = @ImportRowNumber,
				DateUpdated = GETDATE(),
				IsActive = @IsActive,
				ExternalKeyId = @ExternalKeyId,
				AccountNumber = @AccountNumber,
				EmailID = @EmailID,
				Copies = @Copies,
				GraceIssues = @GraceIssues,
				IsComp = @IsComp,
				IsPaid = @IsPaid,
				IsSubscribed = @IsSubscribed,
				Occupation = @Occupation,
				SubscriptionStatusID = @SubscriptionStatusID,
				SubsrcID = @SubsrcID,
				Website = @Website,
				SubGenSubscriberID = @SubGenSubscriberID,
				SubGenSubscriptionID = @SubGenSubscriptionID,
				SubGenPublicationID = @SubGenPublicationID,
				SubGenMailingAddressId = @SubGenMailingAddressId,
				SubGenBillingAddressId = @SubGenBillingAddressId,
				IssuesLeft = @IssuesLeft,
				UnearnedReveue = @UnearnedReveue,
				SubGenIsLead = @SubGenIsLead,
				SubGenRenewalCode = @SubGenRenewalCode,
				SubGenSubscriptionRenewDate = @SubGenSubscriptionRenewDate,
				SubGenSubscriptionExpireDate = @SubGenSubscriptionExpireDate,
				SubGenSubscriptionLastQualifiedDate = @SubGenSubscriptionLastQualifiedDate
			WHERE SubscriberTransformedID = @SubscriberTransformedID
		END 
	ELSE
		BEGIN
			INSERT INTO SubscriberTransformed ([SORecordIdentifier],[SourceFileID],[PubCode],[Sequence],[FName],[LName],[Title],[Company],[Address],[MailStop],[City],[State],[Zip],[Plus4]
           ,[ForZip],[County],[Country],[CountryID],[Phone],[Fax],[Email],[CategoryID],[TransactionID],[TransactionDate],[QDate]
           ,[QSourceID],[RegCode],[Verified],[SubSrc],[OrigsSrc],[Par3C],[Source],[Priority]
		   ,[Sic],[SicCode],[Gender],[Address3],[Home_Work_Address],[Demo7],[Mobile],[Latitude]
           ,[Longitude],[IsLatLonValid],[LatLonMsg],[EmailStatusID],STRecordIdentifier,ProcessCode,ImportRowNumber,IsActive,ExternalKeyId,AccountNumber,EmailID,
		   Copies,GraceIssues,IsComp,IsPaid,IsSubscribed,Occupation,SubscriptionStatusID,SubsrcID,Website,
		   MailPermission,FaxPermission,PhonePermission,OtherProductsPermission,ThirdPartyPermission,EmailRenewPermission,TextPermission,
		   SubGenSubscriberID,SubGenSubscriptionID,SubGenPublicationID,SubGenMailingAddressId,SubGenBillingAddressId,IssuesLeft,UnearnedReveue,
		   SubGenIsLead,SubGenRenewalCode,SubGenSubscriptionRenewDate,SubGenSubscriptionExpireDate,SubGenSubscriptionLastQualifiedDate)
           
			VALUES(@SORecordIdentifier,@SourceFileID,@PubCode,@Sequence,@FName,@LName,@Title,@Company,@Address,@MailStop,@City,@State,@Zip,@Plus4,@ForZip,@County,@Country,@CountryID,@Phone,
					@Fax,@Email,@CategoryID,@TransactionID,@TransactionDate,@QDate,@QSourceID,@RegCode,@Verified,@SubSrc,@OrigsSrc,@Par3C,
					@Source,@Priority,@Sic,@SicCode,@Gender,@Address3,@Home_Work_Address,@Demo7,
					@Mobile,@Latitude,@Longitude,@IsLatLonValid,@LatLonMsg,@EmailStatusID,@STRecordIdentifier,@ProcessCode,@ImportRowNumber,@IsActive,@ExternalKeyId,@AccountNumber,@EmailID,
					@Copies,@GraceIssues,@IsComp,@IsPaid,@IsSubscribed,@Occupation,@SubscriptionStatusID,@SubsrcID,@Website,
					@MailPermission,@FaxPermission,@PhonePermission,@OtherProductsPermission,@ThirdPartyPermission,@EmailRenewPermission,@TextPermission,
					@SubGenSubscriberID,@SubGenSubscriptionID,@SubGenPublicationID,@SubGenMailingAddressId,@SubGenBillingAddressId,@IssuesLeft,@UnearnedReveue,
					@SubGenIsLead,@SubGenRenewalCode,@SubGenSubscriptionRenewDate,@SubGenSubscriptionExpireDate,@SubGenSubscriptionLastQualifiedDate);SELECT @@IDENTITY;
		END

END
GO