create procedure e_Subscription_Save
@SubscriptionID int,
@Sequence int,
@FName varchar(100),
@LName varchar(100),
@Title varchar(100),
@Company	varchar(100),
@Address	varchar(255),
@MailStop varchar(255),
@City varchar(50),
@State varchar(50),
@Zip	varchar(10),
@Plus4 varchar(4),
@ForZip varchar(50),
@County varchar(20),
@Country varchar(100),
@CountryID int,
@Phone varchar(100),
@PhoneExists	bit,
@Fax	varchar(100),
@FaxExists bit,
@Email varchar(100),
@EmailExists	bit,
@CategoryID int,
@TransactionID int,
@TransactionDate smalldatetime,
@QDate datetime,
@QSourceID int,
@RegCode	varchar(5),
@Verified varchar(100),
@SubSrc varchar(8),
@OrigsSrc varchar(8),
@Par3C varchar(10),
@MailPermission bit = null,
@FaxPermission bit = null,
@PhonePermission bit = null,
@OtherProductsPermission bit = null,
@ThirdPartyPermission bit = null,
@EmailRenewPermission bit = null,
@TextPermission bit = null,
@Source varchar(50),
@Priority varchar(4),
@IGrp_Cnt int,
@CGrp_No uniqueidentifier,
@CGrp_Cnt int,
@StatList bit,
@Sic varchar(8),
@SicCode varchar(20),
@Gender varchar(1024),
@IGrp_Rank varchar(2),
@CGrp_Rank varchar(2),
@Address3 varchar(255),
@Home_Work_Address varchar(10),
@PubIDs varchar(2000),
@Demo7 varchar(1),
@IsExcluded bit,
@Mobile varchar(30),
@Latitude decimal(18,15),
@Longitude decimal(18,15),
@IsLatLonValid bit,
@LatLonMsg nvarchar(1000),
@Score int,
@IGrp_No uniqueidentifier,
@Notes varchar(2000),
@DateCreated datetime,
@DateUpdated datetime,
@CreatedByUserID int,
@UpdatedByUserID int,
@AddressTypeCodeId int,
@AddressLastUpdatedDate datetime,
@AddressUpdatedSourceTypeCodeId int,
@IsActive BIT = 'true',
@IsMailable BIT = 'true'
as
BEGIN

	SET NOCOUNT ON

	IF @SubscriptionID > 0
		BEGIN
			IF @DateUpdated IS NULL
				BEGIN
					SET @DateUpdated = GETDATE();
				END
			UPDATE Subscriptions
			SET Sequence = @Sequence,
				FName = @FName,
				LName = @LName,
				Title = @Title,
				Company = @Company,
				Address = @Address,
				MailStop = @MailStop,
				City = @City,
				State = @State,
				Zip = @Zip,
				Plus4 = @Plus4,
				ForZip = @ForZip,
				County = @County,
				Country = @Country,
				CountryID = @CountryID,
				Phone = @Phone,
				PhoneExists = @PhoneExists,
				Fax = @Fax,
				FaxExists = @FaxExists,
				Email = @Email,
				EmailExists = @EmailExists,
				CategoryID = @CategoryID,
				TransactionID = @TransactionID,
				TransactionDate = @TransactionDate,
				QDate = @QDate,
				QSourceID = @QSourceID,
				RegCode = @RegCode,
				Verified = @Verified,
				SubSrc = @SubSrc,
				OrigsSrc = @OrigsSrc,
				Par3C = @Par3C,
				MailPermission = @MailPermission,
				FaxPermission = @FaxPermission,
				PhonePermission = @PhonePermission,
				OtherProductsPermission = @OtherProductsPermission,
				ThirdPartyPermission = @ThirdPartyPermission,
				EmailRenewPermission = @EmailRenewPermission,
				TextPermission = @TextPermission,
				Source = @Source,
				Priority = @Priority,
				IGrp_Cnt = @IGrp_Cnt,
				CGrp_No = @CGrp_No,
				CGrp_Cnt = @CGrp_Cnt,
				StatList = @StatList,
				Sic = @Sic,
				SicCode = @SicCode,
				Gender = @Gender,
				IGrp_Rank = @IGrp_Rank,
				CGrp_Rank = @CGrp_Rank,
				Address3 = @Address3,
				Home_Work_Address = @Home_Work_Address,
				PubIDs = @PubIDs,
				Demo7 = @Demo7,
				IsExcluded = @IsExcluded,
				Mobile = @Mobile,
				Latitude = @Latitude,
				Longitude = @Longitude,
				IsLatLonValid = @IsLatLonValid,
				LatLonMsg = @LatLonMsg,
				Score = @Score,
				IGrp_No = @IGrp_No,
				Notes = @Notes,
				AddressTypeCodeId = @AddressTypeCodeId,
				AddressLastUpdatedDate = @AddressLastUpdatedDate,
				AddressUpdatedSourceTypeCodeId = @AddressUpdatedSourceTypeCodeId,
				IsActive = @IsActive,
				IsMailable = @IsMailable		
			WHERE SubscriptionID = @SubscriptionID;

			SELECT @SubscriptionID;
		END
	ELSE
		BEGIN
			IF @DateCreated IS NULL
				BEGIN
					SET @DateCreated = GETDATE();
				END
			INSERT INTO Subscriptions (Sequence,FName,LName,Title,Company,Address,MailStop,City,State,Zip,Plus4,ForZip,County,Country,CountryID,Phone,PhoneExists,Fax,
									   FaxExists,Email,EmailExists,CategoryID,TransactionID,TransactionDate,QDate,QSourceID,RegCode,Verified,SubSrc,OrigsSrc,Par3C,
									   MailPermission,FaxPermission,PhonePermission,OtherProductsPermission,ThirdPartyPermission,EmailRenewPermission,TextPermission,
									   Source,Priority,IGrp_Cnt,CGrp_No,CGrp_Cnt,StatList,Sic,SicCode,Gender,IGrp_Rank,CGrp_Rank,Address3,Home_Work_Address,PubIDs,
									   Demo7,IsExcluded,Mobile,Latitude,Longitude,IsLatLonValid,LatLonMsg,Score,IGrp_No,Notes,DateCreated,CreatedByUserID,AddressTypeCodeId,AddressLastUpdatedDate,AddressUpdatedSourceTypeCodeId,IsActive,IsMailable)
			VALUES(@Sequence,@FName,@LName,@Title,@Company,@Address,@MailStop,@City,@State,@Zip,@Plus4,@ForZip,@County,@Country,@CountryID,@Phone,@PhoneExists,@Fax,
				   @FaxExists,@Email,@EmailExists,@CategoryID,@TransactionID,@TransactionDate,@QDate,@QSourceID,@RegCode,@Verified,@SubSrc,@OrigsSrc,@Par3C,
				   @MailPermission,@FaxPermission,@PhonePermission,@OtherProductsPermission,@ThirdPartyPermission,@EmailRenewPermission,@TextPermission,
				   @Source,@Priority,@IGrp_Cnt,@CGrp_No,@CGrp_Cnt,@StatList,@Sic,@SicCode,@Gender,@IGrp_Rank,@CGrp_Rank,@Address3,@Home_Work_Address,@PubIDs,
				   @Demo7,@IsExcluded,@Mobile,@Latitude,@Longitude,@IsLatLonValid,@LatLonMsg,@Score,@IGrp_No,@Notes,@DateCreated,@CreatedByUserID,@AddressTypeCodeId,@AddressLastUpdatedDate,@AddressUpdatedSourceTypeCodeId,@IsActive,@IsMailable);SELECT @@IDENTITY;
		END

END
go