//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecn.accounts.main.billingSystem {
    
    
    public partial class PriceItemDetails {
        
        /// <summary>
        /// ddlChannels control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlChannels;
        
        /// <summary>
        /// TechAccessPriceItemEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ecn.accounts.includes.PriceItemEditor TechAccessPriceItemEditor;
        
        /// <summary>
        /// EmailUsagePriceItemEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ecn.accounts.includes.PriceItemEditor EmailUsagePriceItemEditor;
        
        /// <summary>
        /// OptionPriceItemEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ecn.accounts.includes.PriceItemEditor OptionPriceItemEditor;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ecn.accounts.MasterPages.Accounts Master {
            get {
                return ((ecn.accounts.MasterPages.Accounts)(base.Master));
            }
        }
    }
}
