CREATE USER [bill.hipps] WITHOUT LOGIN;


GO
CREATE LOGIN [bill.hipps] WITH PASSWORD=N'Mëå×I¹1xwZìÖnaFë´ªÞoFÛWû^5Ì¦', DEFAULT_DATABASE=[ecn5_accounts], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

