(function(){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI,a=$telerik.$;
Telerik.Web.UI.GridMobileFilterView=function(c){b.GridMobileFilterView.initializeBase(this,[c]);
this._titleFormat=null;
this._column=null;
this._$values=null;
this._$inputs=null;
};
b.GridMobileFilterView.prototype={initialize:function(){b.GridMobileFilterView.callBaseMethod(this,"initialize");
this._$values=this.get_$element().find(".rgValue").on("change keydown",a.proxy(this._change,this));
this._$inputs=this._$values.filter("input");
},dispose:function(){b.GridMobileFilterView.callBaseMethod(this,"dispose");
},show:function(c){this._column=c;
this._setFilterControls(c._data);
this._setFilterFunctions();
this._setFilterValues();
this.set_title(String.format(this._titleFormat,c._data.HeaderText||c._data.DataField));
b.GridMobileFilterView.callBaseMethod(this,"show");
},onInit:function(){this._$element.find(".rgClear").onEvent("down",a.proxy(this._down,this));
},onShown:function(c){},onApplyChanges:function(){var e=[this._column._data.UniqueName];
var c="";
var d=true;
this._$values.each(function(){var f=a(this);
var g=f.attr("type");
if(g=="checkbox"){e.push(f.prop("checked"));
}else{e.push(f.val());
}});
e.forEach(function(f){c+=f+(d?"|?":"|");
d=!d;
});
this._fireContextMenuFilterCommand(c,e,false);
},_fireContextMenuFilterCommand:function(d,p,o){var e=this._column;
var l=this.get_owner();
var f=e._data.UniqueName;
var j=$find(l.get_owner().get_id());
var k=typeof(j.ClientSettings.DataBinding.Location)!="undefined"&&j.ClientSettings.DataBinding.Location!=""&&!j.get_masterTableView()._virtualization;
if(k||j._clientDataSourceID){while(l._filterExpressions.get_count()!=0){var g=l._filterExpressions.getItem(0);
if(g.get_columnUniqueName()==f){l._filterExpressions.remove(g);
}}var h=p[1]||"NoFilter";
var i=p[2]||"";
var m=p[3]||"NoFilter";
var n=p[4]||"";
if(h!="NoFilter"&&i!==""){l.filter(f,i,h,true,true);
}if(m!="NoFilter"&&n!==""){l.filter(f,n,m,false,true);
}e._data.CurrentFilterFunctionName=h;
e._data.AndCurrentFilterFunctionName=m;
e._data.CurrentFilterValue=h=="NoFilter"?"":i;
e._data.AndCurrentFilterValue=m=="NoFilter"?"":n;
if(o){Sys.UI.DomElement.removeCssClass(e.get_element(),"rgFiltered");
this.close();
}var c=l._getViewByType(b.Grid.MobileViewType.Column);
if(c){c.close();
}}l.fireCommand("HeaderContextMenuFilter",d);
},_down:function(){var c=this._column._data.UniqueName+"|?NoFilter||?NoFilter|";
this._fireContextMenuFilterCommand(c,[this._column._data.UniqueName,"NoFilter","","NoFilter",""],true);
},_change:function(c){this.changed();
},_setFilterControls:function(c){var f=c.ColumnType;
var e=c.PickerType;
var d=true;
switch(e){case"DatePicker":this._setInputsType("date");
break;
case"TimePicker":this._setInputsType("time");
break;
case"DateTimePicker":this._setInputsType("datetime-local");
break;
default:d=false;
break;
}if(!d){switch(f){case"GridCheckBoxColumn":this._setInputsType("checkbox");
break;
case"GridNumericColumn":this._setInputsType("number");
break;
default:this._setInputsType("text");
break;
}}},_setInputsType:function(c){this._$inputs.attr("type",c);
},_setFilterFunctions:function(){var e=this._column;
var f=e._data.DataTypeName;
var g=e.get_filterFunction();
var c=this._$element.find("select.rgValue");
var d;
var h;
c.children().each(function(){d=a(this);
h=d.val();
this.style.display="";
if(f=="System.Boolean"){if(h=="GreaterThan"||h=="LessThan"||h=="GreaterThanOrEqualTo"||h=="LessThanOrEqualTo"){this.style.display="none";
}}if(f!="System.String"){if(h=="StartsWith"||h=="EndsWith"||h=="Contains"||h=="DoesNotContain"||h=="IsEmpty"||h=="NotIsEmpty"){this.style.display="none";
}}if(h=="Custom"){this.style.display="none";
}});
c.first().val(g);
c.last().val(e._data.AndCurrentFilterFunctionName);
},_setFilterValues:function(){var c=this._column._data;
this._$element.find("input.rgValue").eq(0).val(c.CurrentFilterValue).end().eq(1).val(c.AndCurrentFilterValue);
}};
b.GridMobileFilterView.registerClass("Telerik.Web.UI.GridMobileFilterView",Telerik.Web.UI.GridMobileView);
})();
