CREATE TABLE [dbo].[ImportOrder] (
    [OrderID]                INT           NOT NULL,
    [OrderItemID]            INT           NULL,
    [SubscriberID]           INT           NULL,
    [SubscriberFirstName]    VARCHAR (500) NULL,
    [SubscriberLastName]     VARCHAR (500) NULL,
    [ShippingFirstName]      VARCHAR (500) NULL,
    [ShippingLastName]       VARCHAR (500) NULL,
    [ShippingAddressLine1]   VARCHAR (500) NULL,
    [ShippingCity]           VARCHAR (500) NULL,
    [ShippingState]          VARCHAR (500) NULL,
    [ShippingPostalCode]     VARCHAR (500) NULL,
    [ShippingCountry]        VARCHAR (500) NULL,
    [BillingFirstName]       VARCHAR (500) NULL,
    [BillingLastName]        VARCHAR (500) NULL,
    [BillingAddressLine1]    VARCHAR (500) NULL,
    [BillingCity]            VARCHAR (500) NULL,
    [BillingState]           VARCHAR (500) NULL,
    [BillingPostalCode]      VARCHAR (500) NULL,
    [BillingCountry]         VARCHAR (500) NULL,
    [CreatedbyRep]           VARCHAR (500) NULL,
    [OrderDate]              DATE          NULL,
    [ProductName]            VARCHAR (500) NULL,
    [PublicationName]        VARCHAR (500) NULL,
    [PublicationProductCode] INT           NULL,
    [PublicationRevenueCode] INT           NULL,
    [SubscriptionOfferName]  VARCHAR (500) NULL,
    [StarterIssues]          BIT           NULL,
    [TotalIssues]            INT           NULL,
    [Copies]                 INT           NULL,
    [Quantity]               INT           NULL,
    [ParentOrderItemID]      INT           NULL,
    [FulfilledDate]          DATE          NULL,
    [RefundedDate]           DATE          NULL,
    [SubTotal]               MONEY         NULL,
    [TaxTotal]               MONEY         NULL,
    [GrandTotal]             MONEY         NULL,
    [ProductID]              INT           NULL,
    [account_id]             INT           NULL,
    [DateCreated]            DATETIME      CONSTRAINT [DF_ImportOrder_DateCreated] DEFAULT (getdate()) NOT NULL,
    [DateUpdated]            DATETIME      NULL,
    [IsMergedToUAD]          BIT           CONSTRAINT [DF_ImportOrder_IsMergedToUAD] DEFAULT ('false') NOT NULL,
    [DateMergedToUAD]        DATETIME      NULL
);



