CREATE TABLE [dbo].[ImportSubscriber] (
    [SystemSubscriberID]                 INT           NOT NULL,
    [IsLead]                             BIT           NULL,
    [RenewalCode_CustomerID]             VARCHAR (500) NULL,
    [SubscriberAccountFirstName]         VARCHAR (500) NULL,
    [SubscriberAccountLastName]          VARCHAR (500) NULL,
    [SubscriberEmail]                    VARCHAR (500) NULL,
    [SubscriberPhone]                    VARCHAR (500) NULL,
    [SubscriberSource]                   VARCHAR (500) NULL,
    [SubscriptionGeniusMailingAddressID] INT           NULL,
    [MailingAddressFirstName]            VARCHAR (500) NULL,
    [MailingAddressLastName]             VARCHAR (500) NULL,
    [MailingAddressTitle]                VARCHAR (500) NULL,
    [MailingAddressLine1]                VARCHAR (500) NULL,
	[MailingAddressLine2]                VARCHAR (500) NULL,
    [MailingAddressCity]                 VARCHAR (500) NULL,
    [MailingAddressState]                VARCHAR (500) NULL,
    [MailingAddressZip]                  VARCHAR (500) NULL,
	[MailingAddressCountry]              VARCHAR (500) NULL,
    [MailingAddressCompany]              VARCHAR (500) NULL,
    [SystemBillingAddressID]             INT           NULL,
    [BillingAddressFirstName]            VARCHAR (500) NULL,
    [BillingAddressLastName]             VARCHAR (500) NULL,
    [BillingAddressLine1]                VARCHAR (500) NULL,
	[BillingAddressLine2]                VARCHAR (500) NULL,
    [BillingAddressCity]                 VARCHAR (500) NULL,
    [BillingAddressState]                VARCHAR (500) NULL,
    [BillingAddressZip]                  VARCHAR (500) NULL,
	[BillingAddressCountry]              VARCHAR (500) NULL,
    [BillingAddressCompany]              VARCHAR (500) NULL,
    [PublicationName]                    VARCHAR (500) NULL,
    [IssuesLeft]                         INT           NULL,
    [UnearnedRevenue]                    MONEY         NULL,
    [Copies]                             INT           NULL,
    [SubscriptionID]                     INT           NULL,
    [SubscriptionCreatedDate]            DATE          NULL,
    [SubscriptionRenewDate]              DATE          NULL,
    [SubscriptionExpireDate]             DATE          NULL,
    [SubscriptionLastQualifiedDate]      DATE          NULL,
    [SubscriptionType]                   VARCHAR (500) NULL,
    [AuditCategoryName]                  VARCHAR (500) NULL,
    [AuditCategoryCode]                  VARCHAR (500) NULL,
    [AuditRequestTypeName]               VARCHAR (500) NULL,
    [AuditRequestTypeCode]               VARCHAR (500) NULL,
    [TransactionID]                      INT           NULL,
    [PublicationID]                      INT           NULL,
    [account_id]                         INT           NULL,
    [DateUpdated]                        DATETIME      NULL,
    [IsMergedToUAD]                      BIT           CONSTRAINT [DF_ImportSubscriber_IsMergedToUAD] DEFAULT ('false') NOT NULL,
    [DateMergedToUAD]                    DATETIME      NULL,
	[ParentSubscriptionID]				 INT		   NULL,
	[IsSiteLicenseMaster]				 BIT		   CONSTRAINT [DF_ImportSubscriber_IsSiteLicenseMaster] DEFAULT ('false') NOT NULL,
	[IsSiteLicenseSeat]				     BIT		   CONSTRAINT [DF_ImportSubscriber_IsSiteLicenseSeat] DEFAULT ('false') NOT NULL
);

