CREATE TABLE [dbo].[FeatureLog] (
    [FLogID]            INT            IDENTITY (1, 1) NOT NULL,
    [ApplicationID]     INT            NULL,
    [ProductLine]       NVARCHAR (200) NULL,
    [TargetApp]         NVARCHAR (100) NULL,
    [EnteredBy]         NVARCHAR (100) NOT NULL,
    [EnteredDate]       DATETIME       NOT NULL,
    [RequestBy]         NVARCHAR (100) NOT NULL,
    [RequestDate]       DATE           NOT NULL,
    [FeatureName]       NVARCHAR (400) NOT NULL,
    [FetureDescription] TEXT           NOT NULL,
    [TargetReleaseDate] DATE           NULL,
    [IsQuoted]          BIT            CONSTRAINT [DF_FeatureLog_IsQuoted] DEFAULT ((0)) NOT NULL,
    [QuotedHours]       REAL           CONSTRAINT [DF_FeatureLog_QuotedHours] DEFAULT ((0)) NOT NULL,
    [IsApporoved]       BIT            CONSTRAINT [DF_FeatureLog_IsApporoved] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]        NVARCHAR (100) NULL,
    [ApprovedDate]      DATE           NULL,
    [IsStarted]         BIT            CONSTRAINT [DF_FeatureLog_IsStarted] DEFAULT ((0)) NOT NULL,
    [StartedDate]       DATE           NULL,
    [IsCompleted]       BIT            CONSTRAINT [DF_FeatureLog_IsCompleted] DEFAULT ((0)) NOT NULL,
    [CompletedDate]     DATE           NULL,
    [DevLead]           NVARCHAR (100) NULL,
    [DevNotes]          TEXT           NULL,
    [FeaturePriority]   INT            NULL,
    [DateAdded]         DATETIME       NOT NULL,
    [DateUpdated]       DATETIME       NULL,
    [UpdatedBy]         NVARCHAR (100) NULL,
    CONSTRAINT [PK_FeatureLog] PRIMARY KEY CLUSTERED ([FLogID] ASC) WITH (FILLFACTOR = 80)
);

