Type.registerNamespace("Telerik.Web.UI");
(function(){$telerik.toSlidingZone=function(c){return c;
};
$telerik.findSlidingZone=$find;
var a=Telerik.Web.UI;
var b=".rspTabsContainer";
a.SplitterSlideDirection=function(){};
a.SplitterSlideDirection.prototype={Right:1,Left:2,Top:3,Bottom:4};
a.SplitterSlideDirection.registerEnum("Telerik.Web.UI.SplitterSlideDirection",false);
a.RadSlidingZone=function(c){a.RadSlidingZone.initializeBase(this,[c]);
this._width=null;
this._height=null;
this._clickToOpen=false;
this._resizeStep=0;
this._slideDuration=300;
this._splitter=null;
this._slideDirection=a.SplitterSlideDirection.Right;
this._slidingPanes=null;
this._slidingPanesById=null;
this._initiallyDockedPaneId=null;
this._dockedPaneId=null;
this._initiallyExpandedPaneId=null;
this._expandedPaneId=null;
this.GetPaneById=this.getPaneById;
this.GetTabsContainer=this.getTabsContainer;
this.DockPane=this.dockPane;
this.UndockPane=this.undockPane;
this.GetPanes=this.getPanes;
this.ExpandPane=this.expandPane;
this.CollapsePane=this.collapsePane;
this.IsLeftDirection=this.isLeftDirection;
this.IsRightDirection=this.isRightDirection;
this.IsTopDirection=this.isTopDirection;
this.IsBottomDirection=this.isBottomDirection;
};
a.RadSlidingZone.prototype={endUpdate:function(){if(this._width.toString().indexOf("px")>-1){this._width=parseInt(this._width,10);
}if(this._height.toString().indexOf("px")>-1){this._height=parseInt(this._height,10);
}a.RadSlidingZone.callBaseMethod(this,"endUpdate");
},dispose:function(){var e=this.getPanes();
for(var c=0,d=e.length;
c<d;
c++){var f=e[c];
if(f){f._moveRootToParent(true);
}}if(this._paneTabMoutTimeout){window.clearTimeout(this._paneTabMoutTimeout);
this._paneTabMoutTimeout=null;
}a.RadSplitterController.getInstance()._removeSlidingZone(this.get_id());
a.RadSlidingZone.callBaseMethod(this,"dispose");
},initialize:function(){var e=this;
var d=e._slideDirection;
var f=a.SplitterSlideDirection;
a.RadSlidingZone.callBaseMethod(this,"initialize");
var c=this._getPanesContainer();
var g=this.get_element();
if(this._isVerticalSlide()){c=c.parentNode;
if(this.isTopDirection()&&($telerik.isIE6||$telerik.isIE7)){g.style.marginTop="-1px";
}}else{if(this.isLeftDirection()&&$telerik.isSafari){g.style.marginLeft="-1px";
}}if($telerik.isIE6||$telerik.isIE7){g.setAttribute("cellSpacing","0");
g.setAttribute("cellPadding","0");
}c.style.display="";
if(d===f.Top||d===f.Bottom){$telerik.$(g).find(b).css({height:e.get_height()});
}},set_clickToOpen:function(c){this._clickToOpen=c;
this.updateClientState();
},get_clickToOpen:function(){return this._clickToOpen;
},set_resizeStep:function(c){this._resizeStep=c;
this.updateClientState();
},get_resizeStep:function(){return this._resizeStep;
},set_slideDuration:function(f){this._slideDuration=f;
this.updateClientState();
var e=this.getPanes();
for(var c=0;
c<e.length;
c++){var d=e[c];
d._slideDuration=f;
if(d._animation){d._animation._expandAnimation.set_duration(f);
}}},get_slideDuration:function(){return this._slideDuration;
},get_width:function(){return this._width;
},get_height:function(){return this._height;
},get_expandedPaneId:function(){return this._expandedPaneId;
},get_dockedPaneId:function(){return this._dockedPaneId;
},get_parent:function(){return this._getParentPane();
},_getParentPane:function(){var c=this._parent;
if(!c){c=this._parent=a.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return c;
},get_splitter:function(){var c=this._splitter;
if(!c){c=this._splitter=a.RadSplitterController.getInstance()._getSplitter(this.get_id());
}return c;
},set_splitter:function(c){this._splitter=c;
},add_loaded:function(c){this.add_load(c);
},remove_loaded:function(c){this.remove_load(c);
},add_load:function(c){this.get_events().addHandler("load",c);
},remove_load:function(c){this.get_events().removeHandler("load",c);
},getPaneById:function(c){return this._getSlidingPanesById()[c];
},getTabsContainer:function(){return $get("RAD_SLIDING_ZONE_TABS_CONTAINER_"+this.get_id());
},_getPanesContainer:function(){return $get("RAD_SLIDING_ZONE_PANES_CONTAINER_"+this.get_id());
},dockPane:function(i){var k=this.getPaneById(i);
if(!k||!k.get_enableDock()){return false;
}var e=new Sys.CancelEventArgs();
k.raiseEvent("docking",e);
if(e.get_cancel()){return false;
}var d=this._dockedPaneId;
if(d&&!this.undockPane(d)){return false;
}k._moveRootToParent(true);
var j=this._getPanesContainer();
var f=this.isLeftDirection();
var g=this.isTopDirection();
this._dockingMode=true;
var p=this._getTabsContainerSize();
var m=p+k[this._isHorizontalSlide()?"get_width":"get_height"]();
var l=this.get_parent();
var n=l.getVarSize();
var o=(f||g)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
var h=n+this.get_splitter()._getAvailIncreaseDelta(l.get_indexInPanes(),o);
m=Math.min(m,h);
var c=m-n;
if(c!=0){l.resize(c,o);
}k._dock();
k._setSlidingContainerSize();
k._setTabDockedState();
var q=this.get_element();
if(g&&($telerik.isIE6||$telerik.isIE7)){q.style.marginTop="0";
}else{if(f&&$telerik.isSafari){j.style.width="1px";
setTimeout(function(){j.style.width="";
},0);
q.style.marginLeft="0";
}}this._dockedPaneId=i;
this._dockingMode=false;
this.updateClientState();
k.raiseEvent("docked",new Sys.EventArgs());
return true;
},undockPane:function(h){var j=this.getPaneById(h);
if(!j){return false;
}var e=new Sys.CancelEventArgs();
j.raiseEvent("undocking",e);
if(e.get_cancel()){return false;
}if(!h){h=this._dockedPaneId;
}var k=this.get_parent();
if(k.get_collapsed()){return false;
}j._moveRootToParent(false);
this._dockingMode=true;
j._undock();
j._setTabDefaultState();
this._dockedPaneId=null;
var g=this.isTopDirection();
var f=this.isLeftDirection();
var i=this._getPanesContainer();
var m=this.get_element();
if(g&&($telerik.isIE6||$telerik.isIE7)){m.style.marginTop="-1px";
}else{if(f&&$telerik.isSafari){i.style.width="1px";
setTimeout(function(){i.style.width="";
},0);
m.style.marginLeft="-1px";
}}var c=k.getVarSize();
var d=c-this._getTabsContainerSize();
var l=(f||g)?a.SplitterDirection.Backward:a.SplitterDirection.Forward;
k.resize(d*(-1),l);
this.updateClientState();
this._dockingMode=false;
j.raiseEvent("undocked",new Sys.EventArgs());
this._paneTabInMover=null;
return true;
},getPanes:function(){var c=this._slidingPanes;
if(!c){var d=this.get_id();
c=this._slidingPanes=a.RadSplitterController.getInstance()._getSlidingPanes(d);
}return c;
},_getSlidingPanesById:function(){var g=this._slidingPanesById;
if(!g){g=[];
var f=this.getPanes();
for(var c=0,d=f.length;
c<d;
c++){var e=f[c];
g[e.get_id()]=e;
}this._slidingPanesById=g;
}return g;
},expandPane:function(f){if(!f){return false;
}var e=this.getPaneById(f);
if(!e){return false;
}if(e._dockOnOpen){this.dockPane(f);
this._dockedPaneId=f;
this.updateClientState();
return false;
}var d=this._expandedPaneId;
if((f==this._paneTabInMover)||(d&&f==d)){return false;
}if(d&&!this.collapsePane(d)){this._paneTabInMover=null;
return;
}if(f==this._dockedPaneId){return false;
}var c=new Sys.CancelEventArgs();
e.raiseEvent("expanding",c);
if(c.get_cancel()){return false;
}this._paneTabInMover=f;
e._setTabExpandedState();
e._expand();
this._expandedPaneId=f;
this.updateClientState();
return true;
},collapsePane:function(f,e){if(this._expandedPaneId!=f){return true;
}if(this._dockedPaneId==f){return false;
}var g=this.getPaneById(f);
if(!g){return false;
}var d=new Sys.CancelEventArgs();
g.raiseEvent("collapsing",d);
if(d.get_cancel()){return false;
}g._setTabDefaultState();
var c=g._animation;
if(c){c._stopAnimation();
}if(!e){g._tableElement.style.position="";
}g._collapse();
this._expandedPaneId=null;
this.updateClientState();
this._paneTabInMover=null;
return true;
},isLeftDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Left);
},isRightDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Right);
},isTopDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Top);
},isBottomDirection:function(){return(this._slideDirection==a.SplitterSlideDirection.Bottom);
},_paneTab_OnMouseOver:function(c){if(this._clickToOpen){return;
}window.clearTimeout(this._paneTabMoutTimeout);
var d=this._getPaneIdFromTabElement(c.target);
this.expandPane(d);
},_paneTab_OnMouseOut:function(c){if(this._clickToOpen){return;
}var d=this._getPaneIdFromTabElement(c.target);
if(!d){return;
}if($telerik.isMouseOverElementEx(this.getPaneById(d).getTabContainer(),c)){return $telerik.cancelRawEvent(c);
}this._paneTabMoutTimeout=setTimeout(Function.createDelegate(this,function(){this._paneTabInMover=null;
this.collapsePane(d);
}),100);
},_paneTab_OnMouseDown:function(c){if(!this._clickToOpen){return;
}var g=c.target;
var f=this._getPaneIdFromTabElement(g);
var d=this._expandedPaneId;
if(d==f){this.collapsePane(f);
}else{this.expandPane(f);
}},_isHorizontalSlide:function(){return(this._slideDirection==a.SplitterSlideDirection.Left||this._slideDirection==a.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},_getPaneIdFromTabElement:function(c){while(c&&c.tagName!="DIV"){c=c.parentNode;
}if(!c||c.id.indexOf("RAD_SLIDING_PANE_TAB_")==-1){return"";
}return c.id.substr("RAD_SLIDING_PANE_TAB_".length);
},_handleParentPaneResizing:function(l,c){if(this._dockingMode){return;
}var e=c.get_delta();
if(this._dockedPaneId){var f=this.getPaneById(this._dockedPaneId);
if(!f.get_enableResize()){c.set_cancel(true);
return;
}var m=this._getTabsContainerSize();
var i=m+(this._isHorizontalSlide())?f.get_minWidth():f.get_minHeight();
var h=m+(this._isHorizontalSlide())?f.get_maxWidth():f.get_maxHeight();
var g=f.get_slidingPaneBounds();
var d=(this._isHorizontalSlide())?g.width:g.height;
var j=d+e;
if(j>h||j<i){c.set_cancel(true);
return;
}var k=new a.PaneResizingEventArgs(e);
f.raiseEvent("resizing",k);
c.set_cancel(k.get_cancel());
}},_getTabsContainerSize:function(){var c=this.getTabsContainer();
return(this._isHorizontalSlide())?c.offsetWidth:c.offsetHeight;
},_handleParentPaneResized:function(r,c){var i=this._dockedPaneId;
if(this._dockingMode||!i){return;
}var h=this.getPaneById(i);
var k=h.get_enableResize();
var l=h._isVerticalSlide();
var j=h.get_slidingPaneBounds();
var e=j.width;
var g=(!k&&!l)?0:(r.get_width()-c.get_oldWidth());
var o=e+g;
var d=j.height;
var f=(!k&&l)?0:r.get_height()-c.get_oldHeight();
var n=d+f;
h._setSlidingContainerSize(o,n);
var q=h.get_width();
var p=c.get_oldHeight();
var m=r.get_height();
h.set_width(o);
h.set_height(m);
h.raiseEvent("resized",new a.PaneResizedEventArgs(q,p));
},_handleSplitterResized:function(e,c){if(this._expandedPaneId){if(e.get_width()!=c.get_oldWidth()||e.get_height()!=c.get_oldHeight()){var d=this._expandedPaneId;
this.collapsePane(d);
this.expandPane(d);
}}},_splitterLoadHandler:function(){var g=this.get_parent();
g.add_resizing(Function.createDelegate(this,this._handleParentPaneResizing));
g.add_resized(Function.createDelegate(this,this._handleParentPaneResized));
var l=this.get_splitter();
l.add_resized(Function.createDelegate(this,this._handleSplitterResized));
if($telerik.quirksMode||$telerik.isFirefox2){var k=this.getPanes();
for(var e=0,f=k.length;
e<f;
e++){var j=k[e];
var h=j.get_element();
h.className=l.getContainerElement().className+" RadSlidingPaneQuirksMode "+h.className;
j._originalParent=j.get_element().parentNode;
j._moveRootToParent(false);
}}var c=this._initiallyDockedPaneId;
if(c!=null){this.dockPane(c);
}var d=this._initiallyExpandedPaneId;
if(d!=null){this.expandPane(d);
}this.updateClientState();
this.raiseEvent("load");
},saveClientState:function(){if(this.get_isUpdating()){return null;
}var g={dockedPaneId:this._dockedPaneId||"",expandedPaneId:this._expandedPaneId||""};
var e=["clickToOpen","resizeStep","slideDuration"];
for(var c=0,d=e.length;
c<d;
c++){var f=e[c];
g[f]=this["get_"+f]();
}return Sys.Serialization.JavaScriptSerializer.serialize(g);
}};
a.RadSlidingZone._preInitialize=function(d,e,c){a.RadSplitterController.getInstance()._addSlidingZone(d,e,c);
};
a.RadSlidingZone.registerClass("Telerik.Web.UI.RadSlidingZone",a.RadWebControl);
})();
Type.registerNamespace("Telerik.Web.UI");
(function(a,i){$telerik.toSlidingPane=function(j){return j;
};
$telerik.findSlidingPane=$find;
var g=a.proxy;
var b=Telerik.Web.UI;
var c=Telerik.Web.Browser;
var e=Telerik.Web.BrowserFeatures;
var f=".telerikSlidingPane";
var d="click"+f;
var h={width:1,height:1};
b.RadSlidingPane=function(j){b.RadSlidingPane.initializeBase(this,[j]);
this._title="";
this._isTabRotated=false;
this._enableResize=true;
this._enableDock=true;
this._dockOnOpen=false;
this._parentPane=null;
this._clickToOpen=false;
this._slideDirection=b.SplitterSlideDirection.Right;
this._slideDuration=300;
this._resizeBarSize=null;
this._isExpanded=false;
this._isDocked=false;
this._width=150;
this._height=150;
this._minWidth=60;
this._minHeight=60;
this._overlay=false;
this._isInitialSizeApplied=false;
this._popupBehavior=null;
this._popupElement=null;
this._contentElement=null;
this._tableElement=null;
this._tabContainer=null;
this._resizeElement=null;
this._originalParent=null;
this.GetContentContainer=this.getContentContainer;
this.GetContent=this.getContent;
this.SetContent=this.setContent;
this.GetDockIconElement=this.getDockIconElement;
this.GetUndockIconElement=this.getUndockIconElement;
this.GetCollapseIconElement=this.getCollapseIconElement;
this.GetSlidingContainerTitle=this.getSlidingContainerTitle;
this.GetSlidingPaneResizeContainer=this.getSlidingPaneResizeContainer;
this.GetTabContainer=this.getTabContainer;
this.HideTab=this.hideTab;
this.ShowTab=this.showTab;
this.IsTabDisplayed=this.isTabDisplayed;
};
b.RadSlidingPane.prototype={initialize:function(){var o=this;
b.RadSlidingPane.callBaseMethod(this,"initialize");
this._popupElement=this.get_element();
this._contentElement=this.getContentContainer();
this._tableElement=this._popupElement.getElementsByTagName("TABLE")[0];
this._tabContainer=this.getTabContainer();
this._resizeElement=this.getSlidingPaneResizeContainer();
var r=this._tabContainer;
$addHandlers(r,{mouseover:this._paneTab_OnMouseOver,mouseout:this._paneTab_OnMouseOut},this);
a(r).onEvent(d,g(o._paneTab_OnMouseDown,o));
var q=this._popupElement;
$addHandlers(q,{mouseover:this._slidingContainer_OnMouseOver,mouseout:this._slidingContainer_OnMouseOut},this);
var p=this._resizeElement;
if(p){p.setAttribute("unselectable","on");
$addHandlers(p,{mouseover:this._resizeSlidePane_OnMouseOver,mouseout:this._resizeSlidePane_OnMouseOut},this);
this._createResizeHelper();
var n=this._getCursorStyle();
var l={};
l[n]=p;
this._resizeExtender=new b.ResizeExtender(this,this._helperBar,l,null,null,n,false);
}var k=this.getDockIconElement();
$addHandlers(k,{mouseover:this._dockElement_OnMouseOver,mouseout:this._dockElement_OnMouseOut},this);
a(k).onEvent(d,g(o._dockElement_OnMouseDown,o));
var s=this.getUndockIconElement();
$addHandlers(s,{mouseover:this._undockElement_OnMouseOver,mouseout:this._undockElement_OnMouseOut},this);
a(s).onEvent(d,g(o._undockElement_OnMouseDown,o));
var j=this.getCollapseIconElement();
$addHandlers(j,{mouseover:this._collapseElement_OnMouseOver,mouseout:this._collapseElement_OnMouseOut},this);
a(j).onEvent(d,g(o._collapseElement_OnMouseDown,o));
if(this._scrollingEnabled&&this._persistScrollPosition){this._attachScrollHandler(true);
}var m=this._tableElement.getElementsByTagName("table")[0];
if($telerik.isIE6||$telerik.isIE7){this._tableElement.setAttribute("cellSpacing","0");
this._tableElement.setAttribute("cellPadding","0");
m.setAttribute("cellSpacing","0");
m.setAttribute("cellPadding","0");
}if(this._resizeElement){this._setResizeElSpan();
}if(this._shouldRotateTabs()){this._applyTabRotation();
}this._appLoadDelegate=Function.createDelegate(this,this._appLoadHandler);
Sys.Application.add_load(this._appLoadDelegate);
this.updateClientState();
},_shouldRotateTabs:function(){return this._isHorizontalSlide()&&!$telerik.getInvisibleParent(this.get_element())&&!$telerik.isIE;
},dispose:function(){this._moveRootToParent(true);
this._originalParent=null;
var n=this._popupBehavior;
if(n){n.dispose();
this._popupBehavior=null;
}var j=this._animation;
if(this._expandAnimationEndedDelegate){if(j){j.remove_expandAnimationEnded(this._expandAnimationEndedDelegate);
}this._expandAnimationEndedDelegate=null;
}if(j){j.dispose();
this._animation=null;
}var q=this._tabContainer;
if(q){$clearHandlers(q);
a(q).offEvent(f);
}var p=this._popupElement;
if(p){$clearHandlers(p);
}this._popupElement=null;
var o=this._resizeElement;
if(o){$clearHandlers(o);
}this._resizeElement=null;
var m=this.getDockIconElement();
if(m){$clearHandlers(m);
a(m).offEvent(f);
}var r=this.getUndockIconElement();
if(r){$clearHandlers(r);
a(r).offEvent(f);
}var l=this.getCollapseIconElement();
if(l){$clearHandlers(l);
a(l).offEvent(f);
}var k=this._appLoadDelegate;
if(k){Sys.Application.remove_load(this._appLoadDelegate);
this._appLoadDelegate=null;
}this._attachScrollHandler(false);
this._contentElement=null;
b.RadSplitterController.getInstance()._removeSlidingPane(this.get_id());
b.RadSlidingPane.callBaseMethod(this,"dispose");
},repaint:function(){b.RadSlidingPane.callBaseMethod(this,"repaint");
if(!this._isTabRotated&&!$telerik.isIE){this._applyTabRotation();
}},get_parent:function(){return this._getSlidingZone();
},_getSlidingZone:function(){var j=this._parent;
if(!j){j=this._parent=b.RadSplitterController.getInstance()._getSlidingZone(this.get_id());
}return j;
},get_enableResize:function(){return this._enableResize;
},set_enableResize:function(j){this._enableResize=j;
this.updateClientState();
},get_enableDock:function(){return this._enableDock;
},set_enableDock:function(j){this._enableDock=j;
this.updateClientState();
},get_dockOnOpen:function(){return this._dockOnOpen;
},set_dockOnOpen:function(j){this._dockOnOpen=j;
this.updateClientState();
},set_title:function(l){this._title=l;
var j=this._getTitleContainerElement();
if(j!=null){j.innerHTML=l;
}var k=this.getSlidingContainerTitle();
if(k){k.innerHTML=l;
}this.updateClientState();
},get_title:function(){return this._title;
},get_expanded:function(){return this._isExpanded;
},get_docked:function(){return this._isDocked;
},get_overlay:function(){return this._overlay;
},set_overlay:function(k){this._overlay=k;
var j=this._popupBehavior;
if(j){j.set_overlay(this._overlay);
}},get_parentPane:function(){var j=this._parentPane;
if(!j){j=this._parentPane=b.RadSplitterController.getInstance()._getParentPane(this.get_id());
}return j;
},set_parentPane:function(j){this._parentPane=j;
},add_docked:function(j){this.get_events().addHandler("docked",j);
},remove_docked:function(j){this.get_events().removeHandler("docked",j);
},add_undocked:function(j){this.get_events().addHandler("undocked",j);
},remove_undocked:function(j){this.get_events().removeHandler("undocked",j);
},add_beforeDock:function(j){this.add_docking(j);
},remove_beforeDock:function(j){this.remove_docking(j);
},add_docking:function(j){this.get_events().addHandler("docking",j);
},remove_docking:function(j){this.get_events().removeHandler("docking",j);
},add_beforeUndock:function(j){this.add_undocking(j);
},remove_beforeUndock:function(j){this.remove_undocking(j);
},add_undocking:function(j){this.get_events().addHandler("undocking",j);
},remove_undocking:function(j){this.get_events().removeHandler("undocking",j);
},getContentContainer:function(){if(!this._contentElement){this._contentElement=$get("RAD_SLIDING_PANE_CONTENT_"+this.get_id());
}return this._contentElement;
},get_pane:function(){return this.get_parentPane().get_element();
},get_paneBounds:function(){var j=this.get_pane();
return $telerik.getBounds(j);
},_show:function(k,l){var j=this._popupBehavior;
j._setCoordinates(k,l);
j.show();
},get_slidingPaneBounds:function(){var j=this._popupElement;
var l=(j.style.top==""&&!this._isDocked);
if(l){this._setSlidingContainerSize();
}var k=$telerik.getBounds(j);
return k;
},_fixIeHeight:function(m,k){if($telerik.standardsMode){var j=(m.offsetHeight-parseInt(k,10));
if(j>0){var l=(parseInt(m.style.height,10)-j);
if(l>0){m.style.height=l+"px";
}}}},getContent:function(){return this._contentElement.innerHTML;
},setContent:function(j){this._contentElement.innerHTML=j;
},getDockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_DOCK_"+this.get_id());
},getDockIconWrapperElement:function(){return this.getDockIconElement().parentNode;
},getUndockIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_UNDOCK_"+this.get_id());
},getUnDockIconWrapperElement:function(){return this.getUndockIconElement().parentNode;
},getCollapseIconElement:function(){return $get("RAD_SPLITTER_SLIDING_PANE_COLLAPSE_"+this.get_id());
},getCollapseIconWrapperElement:function(){return this.getCollapseIconElement().parentNode;
},getSlidingContainerTitle:function(){return $get("RAD_SPLITTER_SLIDING_TITLE_"+this.get_id());
},getSlidingPaneResizeContainer:function(){if(!this._resizeElement){this._resizeElement=$get("RAD_SPLITTER_SLIDING_ZONE_RESIZE_"+this.get_id());
}return this._resizeElement;
},getTabContainer:function(){if(!this._tabContainer){this._tabContainer=$get("RAD_SLIDING_PANE_TAB_"+this.get_id());
}return this._tabContainer;
},hideTab:function(){var j=this._tabContainer;
if(j==null){return;
}j.style.display="none";
},showTab:function(){var j=this._tabContainer;
if(j==null){return;
}j.style.display="";
},isTabDisplayed:function(){var j=this._tabContainer;
if(j==null){return false;
}return(j.style.display!="none");
},_setResizeElSpan:function(){if(this._isHorizontalSlide()){this._resizeElement.setAttribute("rowSpan","2");
}else{this._resizeElement.setAttribute("colSpan","2");
}},_getIsLeftDirection:function(){var j=$telerik.isRightToLeft(this.get_element());
return(this._isLeftDirection()&&!j)||(j&&this._isRightDirection());
},_getIsRightDirection:function(){var j=$telerik.isRightToLeft(this.get_element());
return(this._isRightDirection()&&!j)||(j&&this._isLeftDirection());
},_setTabDefaultState:function(){var j=this._tabContainer;
if(j==null){return false;
}Sys.UI.DomElement.removeCssClass(j,"rspPaneTabContainerDocked");
Sys.UI.DomElement.removeCssClass(j,"rspPaneTabContainerExpanded");
},_setTabDockedState:function(){var j=this._tabContainer;
if(j==null){return false;
}Sys.UI.DomElement.addCssClass(j,"rspPaneTabContainerDocked");
},_setTabExpandedState:function(){var j=this._tabContainer;
if(j==null){return false;
}Sys.UI.DomElement.addCssClass(j,"rspPaneTabContainerExpanded");
},_applyTabRotation:function(){if(this._isTabRotated){return;
}var n=a("span",this._tabContainer).get(0),j=this._getTabIconElement(),k=j?a(j).outerHeight(true):0;
if(this._isHorizontalSlide()&&!e.writingMode){a(this._tabContainer).height(a(n).width()+k);
}var q=0;
var m=a(n);
if($telerik.isRightToLeft(this.get_element())){q=m.width()+parseInt(m.css("margin-left"),10)-m.height();
}if(e.writingMode){var s=m.hasClass("rspRotatedTabText")?"vertical-rl":"horizontal-tb";
m.css({transform:"rotate(0)",writingMode:s});
}else{var p=String.format("{0}transform",this._getBrowserCssPrefix());
m.css(p,"matrix(0, 1, -1, 0, "+q+", 0)");
var o=this._calculateTabTextLineHeight();
var l=Math.ceil(o/2);
var r=String.format("{0}transform-origin",this._getBrowserCssPrefix());
m.css(r,String.format("{0}px {0}px",l)).css("line-height",o+"px");
}this._isTabRotated=true;
},_calculateTabTextLineHeight:function(){var j=(this._isHorizontalSlide())?"width":"height";
return parseInt($telerik.getComputedStyle(this._tabContainer,j),10);
},_getTabIconElement:function(){return $get("RAD_SLIDING_PANE_ICON_"+this.get_id());
},_resizeSlidePane_OnMouseOver:function(j){var k=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.addCssClass(this._resizeElement,k);
},_resizeSlidePane_OnMouseOut:function(j){var k=(this._isHorizontalSlide())?"rspSlideContainerResizeOver":"rspSlideContainerResizeOverHorizontal";
Sys.UI.DomElement.removeCssClass(this._resizeElement,k);
},_resizeByDelta:function(j){var k=new b.PaneResizingEventArgs(j);
this.raiseEvent("resizing",k);
if(k.get_cancel()){return;
}var n=this._isTopDirection();
var m=this._getIsLeftDirection();
if(n||m){j*=-1;
}var l=this._isHorizontalSlide();
var t=this.get_slidingPaneBounds();
var p=l?(t.width+j):null;
var o=!l?(t.height+j):null;
this._setSlidingContainerSize(p,o);
var s=this._popupBehavior;
var u=s.get_x()-(m?j:0);
var v=s.get_y()-(n?j:0);
this._show(u,v);
var r=this.get_width();
var q=this.get_height();
if(l){this.set_width(p);
this._resizeTitleElemWidth(p);
}else{this.set_height(o);
}$telerik.repaintChildren(this);
this.raiseEvent("resized",new b.PaneResizedEventArgs(r,q));
},_resizeTitleElemWidth:function(m){var l=this.getSlidingContainerTitle(),j=$telerik.getMarginBox(l),k=$telerik.getComputedStyle(l,"overflow");
l.style.overflow="hidden";
l.style.width="1px";
m=m-j.horizontal-this._resizeElement.offsetWidth-this._getCommandsWidth();
l.style.width=m>18?m+"px":18+"px";
l.style.overflow=k;
},_appLoadHandler:function(){if(this._shouldRotateTabs()){this._applyTabRotation();
}},_getIconWrapperElements:function(){return $telerik.getElementsByClassName(this.get_element(),"rspSlideHeaderIconWrapper");
},_getCommandsWidth:function(){var m=0;
var l=this._getIconWrapperElements();
for(var j=0;
j<l.length;
j++){var k=l[j];
if($telerik.getVisible(k)){m+=k.offsetWidth;
}}return m;
},_getCursorStyle:function(){return(this._isHorizontalSlide()?"w-resize":"n-resize");
},_createResizeHelper:function(){var n=this._popupElement.style.zIndex+2;
var l=this._isHorizontalSlide();
var j=this._getCursorStyle();
var m=document.createElement("div");
m.unselectable="on";
a(m).css({display:"none",position:"absolute",cursor:j,zIndex:n});
document.body.insertBefore(m,document.body.firstChild);
Sys.UI.DomElement.addCssClass(m,"RadSplitter");
var k=document.createElement("div");
k.unselectable="on";
a(k).css({cursor:j,fontSize:"1px",margin:(l?"0 150px":"150px 0")});
k.innerHTML="<!-- / -->";
m.appendChild(k);
Sys.UI.DomElement.addCssClass(k,"rspHelperBarSlideDrag");
this._helperBar=m;
this._helperBarDecoration=k;
},_getHelperSize:function(){var k={width:4,height:4};
var j=this.get_parentPane();
if(this._isHorizontalSlide()){k.height=j.get_height();
}else{k.width=j.get_width();
}return k;
},onDragStart:function(j){var E=this._getSlidingZone();
var m=E.get_dockedPaneId();
if(m==this.get_id()){return false;
}var q=this._isHorizontalSlide();
var D=this.get_width();
var o=this.get_height();
var s=q?(D-this.get_minWidth()):(o-this.get_minHeight());
var u=q?(this.get_maxWidth()-D):(this.get_maxHeight()-o);
var w=this.get_parentPane();
var y=this.get_splitter()._getAvailDecreaseDelta(w.get_indexInPanes(),b.SplitterDirection.Forward);
var x=Math.min(w._getAvailIncreaseDelta(),y);
if(m!=null){var l=E.getPaneById(m);
x+=(q)?l.get_width():l.get_height();
}x-=(q)?D:o;
u=Math.min(u,x);
if(this._getIsLeftDirection()||this._isTopDirection()){var C=u;
u=s;
s=C;
}var B=this.get_splitter();
var v=B._getDragOverlay();
a(v).css({zIndex:(this._popupElement.style.zIndex+1),cursor:this._getCursorStyle(),display:"block"});
$telerik.setBounds(v,$telerik.getBounds(B.get_element()));
var A=this._getHelperSize();
$telerik.setSize(this._helperBarDecoration,A);
var z=this._resizeElement;
var r=$telerik.getLocation(z);
if($telerik.isSafari&&q){r.y=$telerik.getLocation(z.parentNode).y;
}var k=this._cachedResizeHelperBounds=a.extend({},A,r);
this._liveResizePosition=a.extend({},k);
this._cachedSplitterBounds={x:k.x-(q?s:0),y:k.y-(!q?s:0),width:k.width+(q?(s+u):0),height:k.height+(!q?(s+u):0)};
r[q?"x":"y"]-=150;
var p=this._helperBar;
p.style.display="";
$telerik.setLocation(p,r);
var n=this._resizeExtender;
n._originalBounds=a.extend({},k,r);
this._resizeMode=true;
return true;
},onDragEnd:function(j){if(!this.get_expanded()){return;
}var l=this._isHorizontalSlide()?"x":"y";
var k=this._liveResizePosition[l]-this._cachedResizeHelperBounds[l];
if(k!=0){this._resizeByDelta(k);
}this.get_splitter()._getDragOverlay().style.display="none";
this._helperBar.style.display="none";
Sys.UI.DomElement.removeCssClass(this._helperBarDecoration,"rspHelperBarSlideError");
this._liveResizePosition=null;
this._cachedSplitterBounds=null;
this._cachedResizeHelperBounds=null;
this._resizeMode=false;
},onDrag:function(j){var r=this._cachedSplitterBounds;
if(r.width<1||r.height<1){return false;
}var k=this._helperBarDecoration;
Sys.UI.DomElement.removeCssClass(k,"rspHelperBarSlideError");
var l=this._isHorizontalSlide();
var n=l?"x":"y";
j[n]+=150;
var q=this._cachedResizeHelperBounds;
var p=b.ResizeExtender.containsBounds(r,new Telerik.Web.UI.Bounds(j.x,j.y,q.width,q.height));
if(!p){var m=false;
if(j.x<=r.x){j.x=r.x;
if(l){m=true;
}}else{if(r.x+r.width<=j.x+q.width){j.x=r.x+r.width-q.width;
if(l){m=true;
}}}if(j.y<=r.y){j.y=r.y;
if(!l){m=true;
}}else{if(r.y+r.height<=j.y+q.height){j.y=r.y+r.height-q.height;
if(!l){m=true;
}}}p=true;
if(m){Sys.UI.DomElement.addCssClass(k,"rspHelperBarSlideError");
}}var o=this._resizeStep;
if(o>0){j[n]-=(j[n]-q[n])%o;
}this._liveResizePosition=a.extend({},j);
j[n]-=150;
return p;
},_paneTab_OnMouseDown:function(j){var k=this._getSlidingZone();
k._paneTab_OnMouseDown(j);
},_paneTab_OnMouseOver:function(j){var k=this._getSlidingZone();
k._paneTab_OnMouseOver(j);
},_paneTab_OnMouseOut:function(j){var k=this._getSlidingZone();
k._paneTab_OnMouseOut(j);
},_slidingContainer_OnMouseOut:function(j){if(this.get_docked()||this._resizeMode||this._clickToOpen||!this.get_expanded()){return;
}if($telerik.isMouseOverElementEx(this._popupElement,j)){return;
}var l=this;
var k=function(){var n=l._getSlidingZone();
n._paneTabInMover=null;
n.collapsePane(l.get_id());
};
var m=this._getSlidingZone();
window.clearTimeout(m._paneTabMoutTimeout);
m._paneTabMoutTimeout=window.setTimeout(k,1000);
},_slidingContainer_OnMouseOver:function(j){if(this.get_docked()||this._resizeMode){return;
}var k=this._getSlidingZone();
window.setTimeout(function(){window.clearTimeout(k._paneTabMoutTimeout);
},0);
},_dockElement_OnMouseDown:function(j){if(j.button&&j.button!=1){return true;
}if(!this.get_expanded()){return;
}var k=this._getSlidingZone();
if(!k.collapsePane(this.get_id(),true)){return;
}k.dockPane(this.get_id());
this.getDockIconElement().className="rspSlideHeaderDockIcon";
},_dockElement_OnMouseOver:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_dockElement_OnMouseOut:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getDockIconElement(),"rspSlideHeaderDockIconOver");
},_undockElement_OnMouseDown:function(j){if(j.button&&j.button!=1){return true;
}if(!this.get_docked()){return;
}this._getSlidingZone().undockPane(this.get_id());
},_undockElement_OnMouseOver:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_undockElement_OnMouseOut:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getUndockIconElement(),"rspSlideHeaderUndockIconOver");
},_collapseElement_OnMouseDown:function(j){if(j.button&&j.button!=1){return true;
}if(!this.get_expanded()){return;
}var k=this._getSlidingZone();
k._paneTabInMover=null;
k.collapsePane(this.get_id());
},_collapseElement_OnMouseOver:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.addCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_collapseElement_OnMouseOut:function(j){if(j.button&&j.button!=1){return true;
}Sys.UI.DomElement.removeCssClass(this.getCollapseIconElement(),"rspSlideHeaderCollapseIconOver");
},_onExpandAnimationEnded:function(){this._tableElement.style.position="static";
if($telerik.isFirefox){this._configureScrolling();
Sys.UI.DomElement.removeCssClass(this._contentElement,"rspHideContentOverflow");
}if($telerik.getVisible(this.get_element())){this._showOverlayElement(true);
}this.setScrollPos(this._scrollLeft,this._scrollTop);
this._element.style.overflow="hidden";
$telerik.repaintChildren(this);
this.raiseEvent("expanded",new Sys.EventArgs());
},_expandSlidingContainer:function(){this._showOverlayElement(false);
if($telerik.isFirefox){var j=this._contentElement;
j.style.overflow="hidden";
Sys.UI.DomElement.addCssClass(j,"rspHideContentOverflow");
}var n=this._tableElement;
var o=$telerik.getOuterSize(n);
var k=b.jSlideDirection.Right;
if(this._getIsLeftDirection()){k=b.jSlideDirection.Left;
n.style.left=o.width+"px";
}else{if(this._isBottomDirection()){k=b.jSlideDirection.Down;
n.style.top=-o.height+"px";
}else{if(this._isTopDirection()){k=b.jSlideDirection.Up;
n.style.top=o.height+"px";
}else{n.style.left=-o.width+"px";
}}}if(!this._animation){var l=new b.AnimationSettings({duration:this._slideDuration});
var m=new b.jSlide(n,l,null,false);
m.initialize();
m.set_direction(k);
this._expandAnimationEndedDelegate=Function.createDelegate(this,this._onExpandAnimationEnded);
m.add_expandAnimationEnded(this._expandAnimationEndedDelegate);
this._animation=m;
}this._animation.expand();
},_collapseSlidingContainer:function(){try{this._animation.stop();
}catch(j){}this._hideSlidingContainer();
this.raiseEvent("collapsed",new Sys.EventArgs());
},_setSlidingContainerSize:function(q,l){var p=$telerik.getSize(this.get_parentPane()._contentElement);
var m=this._isVerticalSlide();
if(q==null){q=(!m)?this.get_width():p.width;
}if(l==null){l=m?this.get_height():p.height;
}var j=this._contentElement;
if($telerik.isSafari){j.style.width=q+"px";
j.style.height=l+"px";
}var n=this._popupElement;
if(parseInt(n.style.width,10)!=q){n.style.width=q+"px";
}if(parseInt(n.style.height,10)!=l){n.style.height=l+"px";
}if(c.ie&&c.version===8){this._setContentOuterSize(h);
}var o=this._getResizeElementSize();
var k={height:(l-this._getHeaderHeight()-(m?o.height:0)),width:(q-(!m?o.width:0))};
this._setContentOuterSize(k);
this._isInitialSizeApplied=true;
},_getHeaderHeight:function(){var j=0;
var k=$telerik.getElementByClassName(this._tableElement,"rspSlideHeader","tr");
if(k){j=$telerik.getOuterSize(k).height;
}return j;
},_getResizeElementSize:function(){var k={width:0,height:0};
if(this._enableResize){var j=this._resizeElement;
if("none"!=$telerik.getCurrentStyle(j,"display","")){k=$telerik.getOuterSize(j);
}}return k;
},_setContentOuterSize:function(n){var k=this._contentElement;
var j=$telerik.getBorderBox(k);
var m=$telerik.getPaddingBox(k);
var l=$telerik.getMarginBox(k);
n.height-=(j.vertical+m.vertical+l.vertical);
if(parseInt(k.style.height,10)!=n.height&&n.height>=0){k.style.height=n.height+"px";
}n.width-=(j.horizontal+m.horizontal+l.horizontal);
if(parseInt(k.style.width,10)!=n.width&&n.width>=0){k.style.width=n.width+"px";
}},_hideSlidingContainer:function(){var j=this._popupElement;
j.style.top="";
j.style.left="";
this._showOverlayElement(false);
},_dockSlidingContainer:function(){this._popupElement.style.position="static";
this._tableElement.style.position="static";
this._showOverlayElement(false);
},_unDockSlidingContainer:function(){this._popupElement.style.position="";
this._tableElement.style.position="";
this._showOverlayElement(true);
},_setSlidingContainerResizable:function(l){var n=this._resizeElement;
var k=this._isVerticalSlide();
if(k){n=n.parentNode;
}if(l&&n.style.display==""){return;
}if(this._enableResize){var m=this._resizeBarSize;
if(null==m){m=this._getResizeElementSize()[k?"height":"width"];
if(m>0){this._resizeBarSize=m;
}}if(l){m*=-1;
}var j=this._contentElement;
if(k){j.style.height=parseInt(j.style.height,10)+m+"px";
}else{j.style.width=parseInt(j.style.width,10)+m+"px";
}}n.style.display=(l)?"":"none";
},_setIconsExpandedState:function(){this._hideAllIcons();
this.getDockIconWrapperElement().style.display=(this.get_enableDock())?"":"none";
this.getCollapseIconWrapperElement().style.display="";
},_setIconsDockedState:function(){this._hideAllIcons();
this.getUnDockIconWrapperElement().style.display="";
},_hideAllIcons:function(){this.getDockIconWrapperElement().style.display="none";
this.getUnDockIconWrapperElement().style.display="none";
this.getCollapseIconWrapperElement().style.display="none";
},_getTitleContainerElement:function(){return $get("RAD_SLIDING_PANE_TEXT_"+this.get_id());
},_dock:function(){if(!this._isInitialSizeApplied){this._setSlidingContainerSize();
}this._setIconsDockedState();
this._setSlidingContainerResizable(false);
this._dockSlidingContainer();
this.setScrollPos(this._scrollLeft,this._scrollTop);
$telerik.repaintChildren(this);
this._isExpanded=false;
this._isDocked=true;
},_undock:function(){this._isExpanded=false;
this._isDocked=false;
this._setSlidingContainerResizable(this._enableResize);
this._unDockSlidingContainer();
this._hideSlidingContainer();
},_expand:function(){var n=this._getSlidingZone().getTabsContainer();
var m=this._popupElement;
if(!this._popupBehavior){var j=(new Date()-100)+"PopupBehavior";
this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:j,parentElement:n,overlay:this._overlay,keepInScreenBounds:false,manageVisibility:false},null,null,m);
}this._setSlidingContainerResizable(this._enableResize);
this._setIconsExpandedState();
var o=0;
var p=0;
var k=this.get_slidingPaneBounds();
var l=$telerik.getSize(n);
if(this._getIsRightDirection()){o=l.width;
}else{if(this._getIsLeftDirection()){o=-k.width;
}else{if(this._isBottomDirection()){p=l.height;
}else{if(this._isTopDirection()){p=-k.height;
}}}}this._show(o,p);
this._expandSlidingContainer();
if(this._isHorizontalSlide()){this._resizeTitleElemWidth(k.width);
}this._isExpanded=true;
this._isDocked=false;
},_collapse:function(){this._isExpanded=false;
this._isDocked=false;
this._collapseSlidingContainer();
},_isLeftDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Left);
},_isRightDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Right);
},_isTopDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Top);
},_isBottomDirection:function(){return(this._slideDirection==b.SplitterSlideDirection.Bottom);
},_isHorizontalSlide:function(){return(this._slideDirection==b.SplitterSlideDirection.Left||this._slideDirection==b.SplitterSlideDirection.Right);
},_isVerticalSlide:function(){return !this._isHorizontalSlide();
},saveClientState:function(){var n=this.getScrollPos();
var o={_scrollLeft:n.left,_scrollTop:n.top};
var l=["width","height","title","enableResize","minWidth","maxWidth","minHeight","maxHeight","enableDock"];
for(var j=0,k=l.length;
j<k;
j++){var m=l[j];
o[m]=this["get_"+m]();
}return Sys.Serialization.JavaScriptSerializer.serialize(o);
},_getOverlayElement:function(){return this._popupElement._hideWindowedElementsIFrame;
},_showOverlayElement:function(k){var j=this._getOverlayElement();
if(!j){return;
}j.style.display=k?"":"none";
},_getRadioButtons:function(){var j=this._contentElement.getElementsByTagName("input");
var n=[];
for(var k=0,m=j.length;
k<m;
k++){var l=j[k];
if(l.type=="radio"){n.push(l);
}}return n;
},_getRadioButtonsStatus:function(l){var m=[];
for(var j=0,k=l.length;
j<k;
j++){m.push(l[j].getAttribute("checked"));
}return m;
},_restoreRadioButtonsStatus:function(l,k){for(var j=k.length-1;
j>=0;
j--){if(l.length==0){break;
}k[j].setAttribute("checked",l.pop());
}},_moveRootToParent:function(o){if(!$telerik.quirksMode&&!$telerik.isFirefox2){return;
}var j=(o)?this._originalParent:this.get_splitter().get_element();
var n=this._popupElement;
if(!n){return;
}var k=n.parentNode;
var l;
var m;
if(!j||!k||j.id==k.id){return;
}if($telerik.isIE){l=this._getRadioButtons();
m=this._getRadioButtonsStatus(l);
}k.removeChild(n);
j.appendChild(n);
if($telerik.isIE){this._restoreRadioButtonsStatus(m,l);
}},_getBrowserCssPrefix:function(){if($telerik.isFirefox){return"-moz-";
}else{if($telerik.isChrome||$telerik.isSafari){return"-webkit-";
}else{if($telerik.isOpera){return"-o-";
}else{return"";
}}}}};
b.RadSlidingPane._preInitialize=function(l,m,n,k,j){b.RadSplitterController.getInstance()._addSlidingPane(l,m,n,k,j);
};
b.RadSlidingPane.registerClass("Telerik.Web.UI.RadSlidingPane",b.SplitterPaneBase);
Sys.Application.add_init(function(){e.addTest("writingMode",function(){var m='<span style="position: absolute; left: -999999px; top: -999999px; width: auto; height: auto;"><span style="writing-mode: vertical-rl;">some long content</span></span>';
var j=a(m).appendTo("body");
var k=j.children(":first")[0];
var l=k&&k.offsetWidth<k.offsetHeight;
j.remove();
return l;
});
});
})($telerik.$);
