using System.Diagnostics.CodeAnalysis;

namespace ECN.MarketinAutomation.Tests.Models.PostModels.Controls
{
    [ExcludeFromCodeCoverage]
    public static class ControlTestConsts
    {
        internal const string ClickDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':1,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':'Group Email Click',
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
	          'fontSize':16,
	          'text':'',
	          'align':null,
	          'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
	          'remove':true,
	          'snap':false
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'Group Email Click',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
	          {  
		         'name':'Top'
	          },
	          {  
		         'name':'Bottom'
	          },
	          {  
		         'name':'Left'
	          },
	          {  
		         'name':'Right'
	          },
	          {  
		         'name':'Auto'
	          }
           ],
           'rotation':{  
	          'angle':0
           }
        }";

        internal const string ClickModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':678,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string DirectClickDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'linkRb':false,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':null,
           'ControlType':2,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Direct_Click',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string DirectClickModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'linkRb':false,
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':678,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string DirectNoOpenDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'campaigntemplate_value':false,
           'citemplatename':null,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':null,
           'ControlType':3,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Direct_NoOpen',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string DirectNoOpenModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'campaigntemplate_value':true,
           'citemplatename':'SampleCampaignItemTemplateName',
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':678,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string EndDefaultExpectedJson = @"
        {  
           'ControlType':5,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':'End',
           'x':0.0,
           'y':0.0,
           'width':140.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'End',
              'align':'center middle',
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'End',
           'isConfigured':false,
           'control_label':'End',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string EndModifiedExpectedJson = @"
        {  
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':140.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'End',
              'align':'center middle',
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormAbandonDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'linkRb':false,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':null,
           'ControlType':8,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'FormAbandon',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormAbandonModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'linkRb':false,
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':678,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormSubmitDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'linkRb':false,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'campaign_item_name':null,
           'ControlType':7,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'FormSubmit',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormSubmitModifiedExpectedJson = @"
        {  
           'linkRb':false,
           'isCancelled':false,
           'cancelDate':null,
           'width':150.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'campaign_item_name':'SampleCampaignItemName',
           'HeatMapStats':678,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'height':40.0,
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormDefaultExpectedJson = @"
        {  
           'linkRb':false,
           'formId':0,
           'formname':null,
           'ControlType':6,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Form',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string FormModifiedExpectedJson = @"
        {  
           'linkRb':false,
           'formId':0,
           'formname':null,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':null,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string WaitDefaultExpectedJson = @"
        {  
           'wait_time':0.0,
           'time_changed':null,
           'original_days':null,
           'original_hours':null,
           'original_minutes':null,
           'HeatMapStats':null,
           'ControlType':20,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':'Wait',
           'x':0.0,
           'y':0.0,
           'width':140.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Wait',
           'isConfigured':false,
           'control_label':'Wait',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string WaitModifiedExpectedJson = @"
        {  
           'wait_time':0.0,
           'time_changed':null,
           'original_days':null,
           'original_hours':null,
           'original_minutes':null,
           'HeatMapStats':null,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':140.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string SentDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'ControlType':15,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Sent',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string SentModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NoClickDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':10,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'NoClick',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NoClickModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string UnsubscribeDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':null,
           'campaign_item_name':null,
           'ControlType':19,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Unsubscribe',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string UnsubscribeModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':678,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string SuppressedDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'ControlType':18,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Suppressed',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";
        
        internal const string SuppressedModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string SubscribeDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':null,
           'campaign_item_name':null,
           'ControlType':17,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Subscribe',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string SubscribeModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':678,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string StartDefaultExpectedJson = @"
        {  
           'ControlType':16,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'text':null,
           'x':0.0,
           'y':0.0,
           'width':138.0,
           'height':38.0,
           'content':{  
              'fontSize':16,
              'text':'Start',
              'align':'center middle',
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Start',
           'isConfigured':false,
           'control_label':null,
           'control_text':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string StartModifiedExpectedJson = @"
        {  
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':138.0,
           'height':38.0,
           'content':{  
              'fontSize':16,
              'text':'Start',
              'align':'center middle',
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'control_text':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string OpenNoClickDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':14,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Open_NoClick',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string OpenNoClickModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string OpenDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':13,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Open',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string OpenModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NotSentDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':12,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'NotSent',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NotSentModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NoOpenDefaultExpectedJson = @"
        {  
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'campaigntemplate_value':false,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'HeatMapStats':null,
           'estSendTime':null,
           'campaign_item_name':null,
           'customerId':0,
           'ControlType':11,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'NoOpen',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string NoOpenModifiedExpectedJson = @"
        {  
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'campaigntemplate_value':true,
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'HeatMapStats':678,
           'estSendTime':null,
           'campaign_item_name':'SampleCampaignItemName',
           'customerId':345,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string GroupDefaultExpectedJson = @"
        {  
           'groupID':0,
           'group':null,
           'customerid':0,
           'customer':null,
           'HeatMapStats':null,
           'Subscribed':null,
           'Unsubscribed':null,
           'Suppressed':null,
           'ControlType':9,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Group',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string GroupModifiedExpectedJson = @"
        {  
           'groupID':0,
           'group':null,
           'customerid':0,
           'customer':null,
           'HeatMapStats':null,
           'Subscribed':null,
           'Unsubscribed':null,
           'Suppressed':null,
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string Direct_OpenDefaultExpectedJson = @"
        {  
           'customerId':0,
           'campaign_itemtemplateID':0,
           'campaigntemplate_value':false,
           'citemplatename':null,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':null,
           'campaign_item_name':null,
           'ControlType':4,
           'MAControlID':0,
           'id':null,
           'ECNID':0,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':null,
           'x':0.0,
           'y':0.0,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'Direct_Open',
           'isConfigured':false,
           'control_label':null,
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string Direct_OpenModifiedExpectedJson = @"
        {  
           'customerId':345,
           'campaign_itemtemplateID':456,
           'campaigntemplate_value':true,
           'citemplatename':'SampleCampaignItemTemplateName',
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'isCancelled':false,
           'cancelDate':null,
           'HeatMapStats':678,
           'campaign_item_name':'SampleCampaignItemName',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'width':150.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':null,
              'color':'#142a52'
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string CampaignItemDefaultExpectedJson = @"
        {  
           'customerid':0,
           'customer':null,
           'subcategory':null,
           'groups':null,
           'suppression_groups':null,
           'groups_filter':null,
           'suppression_groups_filter':null,
           'messageId':0,
           'message':null,
           'from_email':null,
           'reply_to':null,
           'from_name':null,
           'subject':null,
           'schedule':'0001-01-01T00:00:00',
           'campaign_ID':-1,
           'campaign_name':null,
           'campaign_itemID':-1,
           'campaign_item_name':null,
           'campaign_item_value':false,
           'campaign_value':false,
           'campaigntemplate_value':false,
           'campaign_itemtemplateID':0,
           'citemplatename':null,
           'blastfield1':null,
           'blastfield2':null,
           'blastfield3':null,
           'blastfield4':null,
           'blastfield5':null,
           'ControlType':0,
           'MAControlID':-1,
           'id':null,
           'ECNID':-1,
           'extratext':null,
           'isdirty':false,
           'MarketingAutomationID':0,
           'control_text':'Campaign Item',
           'x':0.0,
           'y':0.0,
           'HeatMapStats':null,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':true,
              'snap':false
           },
           'category':'CampaignItem',
           'isConfigured':false,
           'control_label':'Campaign Item',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";

        internal const string CampaignItemModifiedExpectedJson = @"
        {  
           'customerid':345,
           'customer':null,
           'subcategory':null,
           'groups':null,
           'suppression_groups':null,
           'groups_filter':null,
           'suppression_groups_filter':null,
           'messageId':567,
           'message':'SampleMessageName',
           'from_email':'SampleFromEmail',
           'reply_to':'SampleReplyTo',
           'from_name':'SampleFromName',
           'subject':'SampleEmailSubject',
           'schedule':'0001-01-01T00:00:00',
           'campaign_ID':-1,
           'campaign_name':null,
           'campaign_itemID':-1,
           'campaign_item_name':'SampleCampaignItemName',
           'campaign_item_value':false,
           'campaign_value':false,
           'campaigntemplate_value':true,
           'campaign_itemtemplateID':456,
           'citemplatename':'SampleCampaignItemTemplateName',
           'blastfield1':'SampleBlastField1',
           'blastfield2':'SampleBlastField2',
           'blastfield3':'SampleBlastField3',
           'blastfield4':'SampleBlastField4',
           'blastfield5':'SampleBlastField5',
           'ControlType':1,
           'MAControlID':123,
           'id':'SampleControlId',
           'ECNID':234,
           'extratext':'SampleExtraText',
           'isdirty':true,
           'MarketingAutomationID':345,
           'control_text':'SampleText',
           'x':1.23,
           'y':2.34,
           'HeatMapStats':678,
           'width':200.0,
           'height':40.0,
           'content':{  
              'fontSize':16,
              'text':'',
              'align':'center middle',
              'color':''
           },
           'fill':'#FFFFFF',
           'type':'rectangle',
           'editable':{  
              'remove':false,
              'snap':true
           },
           'category':'Click',
           'isConfigured':false,
           'control_label':'SampleText',
           'cursor':'pointer',
           'selectable':true,
           'serializable':true,
           'enable':true,
           'path':'',
           'autoSize':true,
           'visual':null,
           'minWidth':20,
           'minHeight':20,
           'connectors':[  
              {  
                 'name':'Top'
              },
              {  
                 'name':'Bottom'
              },
              {  
                 'name':'Left'
              },
              {  
                 'name':'Right'
              },
              {  
                 'name':'Auto'
              }
           ],
           'rotation':{  
              'angle':0
           }
        }";
    }
}
