using System;
using System.Linq;
using System.Runtime.Serialization;

namespace KMPlatform
{
    public class Enums
    {
        [DataContract]
        public enum Services
        {
            [EnumMember]
            FULFILLMENT,
            [EnumMember]
            UAD,
            [EnumMember]
            UADAPP,
            [EnumMember]
            EMAILMARKETING,
            [EnumMember]
            FORMSDESIGNER,
            [EnumMember]
            SURVEY,
            [EnumMember]
            DOMAINTRACKING,
            [EnumMember]
            CREATOR,
            [EnumMember]
            DIGITALEDITION,
            [EnumMember]
            PRT,
            [EnumMember]
            UADFILEMAPPER,
            [EnumMember]
            CIRCFILEMAPPER,
            [EnumMember]
            MARKETINGAUTOMATION
        }
        [DataContract]
        public enum ServiceFeatures
        {
            [EnumMember]
            SRCH,
            [EnumMember]
            FSUAD,
            [EnumMember]
            RPT,
            [EnumMember]
            FSC,
            [EnumMember]
            FHUAD,
            [EnumMember]
            FHC,
            [EnumMember]
            FILEUAD,
            [EnumMember]
            FILEC,
            [EnumMember]
            FILEVALUAD,
            [EnumMember]
            HIST,
            [EnumMember]
            OC,
            [EnumMember]
            FV,
            [EnumMember]
            Groups,
            [EnumMember]
            GroupFilter,
            [EnumMember]
            GroupFolder,
            [EnumMember]
            GroupUDFs,
            [EnumMember]
            GroupConfig, //global UDFs??
            [EnumMember]
            SmartForm,
            [EnumMember]
            SmartFormsPrePop,
            [EnumMember]
            Content,
            [EnumMember]
            ContentFilter,
            [EnumMember]
            ContentFolder,
            [EnumMember]
            PersonalizationBlast,
            [EnumMember]
            Blast,
            //BlastLayout,
            [EnumMember]
            BlastReport,
            [EnumMember]
            BlastReportSends,
            [EnumMember]
            BlastReportClicks,
            [EnumMember]
            BlastReportClickThroughRatio,
            [EnumMember]
            BlastReportOpens,
            [EnumMember]
            BlastReportUnopened,
            [EnumMember]
            BlastReportNoClicks,
            [EnumMember]
            BlastReportBounces,
            [EnumMember]
            BlastReportResends,
            [EnumMember]
            BlastReportForwards,
            [EnumMember]
            BlastReportUnsubscribes,
            [EnumMember]
            BlastReportMasterSuppressed,
            [EnumMember]
            BlastReportAbuse,
            [EnumMember]
            BlastReportISPFeedback,
            [EnumMember]
            BlastReportSuppressed,
            [EnumMember]
            BlastReportSocialMedia,
            [EnumMember]
            Campaign,
            [EnumMember]
            DomainSuppression,
            [EnumMember]
            DynamicTag,
            [EnumMember]
            Email,
            [EnumMember]
            Trigger,
            [EnumMember]
            ImagesFolder,
            //Domain tracking Features
            [EnumMember]
            DomainSetup,
            [EnumMember]
            ManageImages,
            //ECN Product Details - some do not have access level..
            [EnumMember]
            AddDupeSubscribers,
            [EnumMember]
            AutoMasterSuppressBounces,
            [EnumMember]
            BlastCategories,
            [EnumMember]
            BlastSuppression,
            [EnumMember]
            ClickThroughReport,
            [EnumMember]
            ContentSharing,
            [EnumMember]
            ConversionTracking,
            [EnumMember]
            CustomTemplates,
            [EnumMember]
            DynamicContent,
            [EnumMember]
            EmailListandProfilePreferences,
            [EnumMember]
            EmailListPreferences,
            [EnumMember]
            EmailPersonalization,
            [EnumMember]
            EmailPreview,
            [EnumMember]
            EmailProfilePreferences,
            [EnumMember]
            EmailSearch,
            [EnumMember]
            EventTriggers,
            [EnumMember]
            FlashReporting,
            [EnumMember]
            ForwardtoaFriend,
            [EnumMember]
            GoogleAnalytics,
            [EnumMember]
            GroupFiltering,
            [EnumMember]
            ISPReporting,
            [EnumMember]
            LinkOwner,
            [EnumMember]
            MultiGroupBlast,
            [EnumMember]
            Omniture,
            [EnumMember]
            OptOutPreference,
            [EnumMember]
            PageKnowtice,
            [EnumMember]
            ProfileHistory,
            [EnumMember]
            ReportingBlastFields,
            [EnumMember]
            ROIReporting,
            [EnumMember]
            SeedList,
            [EnumMember]
            SetMessagePriority,
            [EnumMember]
            SetMessageThresholds,
            [EnumMember]
            SmartSegment,
            [EnumMember]
            SMS,
            [EnumMember]
            TrackmailtoClickThru,
            [EnumMember]
            Transnippets,
            [EnumMember]
            UsersDepartments,
            //CampaignItem,
            [EnumMember]
            CampaignItemTemplate,
            //CampaignItemBlast,
            //CampaignItemTestBlast,
            //CampaignItemSuppression,
            [EnumMember]
            ABSummaryReport,
            [EnumMember]
            BlastComparisonReport,
            [EnumMember]
            CampaignStatisticsReport,
            [EnumMember]
            ChampionAuditReport,
            [EnumMember]
            BlastDeliveryReport,
            [EnumMember]
            EmailFatigueReport,
            [EnumMember]
            EmailPerformanceByDomainReport,
            [EnumMember]
            LinkReport,
            [EnumMember]
            PerformanceByDayAndTimeReport,
            [EnumMember]
            TopEvangelistsReport,
            [EnumMember]
            UndeliverableReport,
            [EnumMember]
            UnsubscribeReasonReport,
            [EnumMember]
            EmailDeliveredByPercentageReport,
            [EnumMember]
            AudienceEngagementReport,
            [EnumMember]
            BlastStatisticsReport,
            [EnumMember]
            AdvertiserClickReport,
            [EnumMember]
            GroupAttributeReport,
            [EnumMember]
            GroupStatisticsReport,
            [EnumMember]
            ListSizeOverTimeReport,
            [EnumMember]
            OnOffReport,
            [EnumMember]
            GroupExport, //GroupExport to FTP option in Scheduled Exports.
            [EnumMember]
            RSSFeed,
            [EnumMember]
            MasterSuppressionSourceReport,
            [EnumMember]
            BlastEnvelopes,
            [EnumMember]
            EmailPreviewUsageReport,
            [EnumMember]
            MarketingAutomationTemplates,
            [EnumMember]
            MarketingAutomation,            
            //UAD Service Features
            [EnumMember]
            Dashboard,
            [EnumMember]
            ConsensusView,
            [EnumMember]
            RecencyView,
            [EnumMember]
            ProductView,
            [EnumMember]
            CrossProductView,
            [EnumMember]
            RecordDetails,
            [EnumMember]
            SalesView,
            [EnumMember]
            Market,
            [EnumMember]
            MarketComparison,
            [EnumMember]
            UADFilter,
            [EnumMember]
            ScheduledExport,
            [EnumMember]
            FilterComparison,
            [EnumMember]
            FilterCategory,
            [EnumMember]
            QuestionCategory,
            [EnumMember]
            UADExport,
            [EnumMember]
            CampaignComparison,
            [EnumMember]
            GeoCode,
            [EnumMember]
            SummaryReport,
            [EnumMember]
            DataMasking,
            //PRT Servive Features
            [EnumMember]
            RecordView,
            [EnumMember]
            PRTFilter,
            [EnumMember]
            Report,
            [EnumMember]
            PRTExport,
            //Fulfillment
            [EnumMember]
            History,
            [EnumMember]
            Search,
            [EnumMember]
            OpenClose,
            [EnumMember]
            Reports,
            [EnumMember]
            ReportBuilder,
            [EnumMember]
            FileValidator,
            [EnumMember]
            ControlCenter,
            [EnumMember]
            ApplicationManagement,
            [EnumMember]
            MenuManagement,
            [EnumMember]
            PublicationManagement,
            [EnumMember]
            ClientManagement,
            [EnumMember]
            SecurityGroupManagement,
            [EnumMember]
            UserManagement,
            [EnumMember]
            CodeSheetViewer,
            [EnumMember]
            ClientGroupMgmt,
            [EnumMember]
            ServiceMgmt,
            [EnumMember]
            ServiceFeatureMgmt,
            [EnumMember]
            MenuFeatureMgmt,
            [EnumMember]
            MarketMgmt,
            [EnumMember]
            BrandMgmt,
            [EnumMember]
            FilterMgmt,
            [EnumMember]
            CampaignMgmt,
            [EnumMember]
            UADDataRemovalMgmt,
            [EnumMember]
            ECNSecurityGroupManagement,
            [EnumMember]
            FileMapper,
            [EnumMember]
            DQM,
            [EnumMember]
            UADExplorer,
            [EnumMember]
            ADMSDashboard,
            [EnumMember]
            DataCompare,
            [EnumMember]
            AudienceViews,
            [EnumMember]
            Product,
            [EnumMember]
            Consensus,
            [EnumMember]
            Markets,
            [EnumMember]
            Tools,
            [EnumMember]
            FormsDesigner,
            [EnumMember]
            Survey,
            [EnumMember]
            Creator,
            [EnumMember]
            DigitalEdition,
            [EnumMember]
            Marketo,
            [EnumMember]
            UADAPI,
            //Domain Tracking
            [EnumMember]
            TrackAnonymous

        }
        [DataContract]
        public enum Access
        {
            [EnumMember]
            View,
            [EnumMember]
            Edit,
            [EnumMember]
            Delete,
            [EnumMember]
            ImportEmails,
            [EnumMember]
            AddEmails,
            [EnumMember]
            CleanEmails,
            [EnumMember]
            Download,
            [EnumMember]
            ExternalImport,
            //UAD access 
            [EnumMember]
            ExportToGroup,
            [EnumMember]
            SaveToCampaign,
            [EnumMember]
            DownloadSample,
            [EnumMember]
            ViewDetails,
            [EnumMember]
            DownloadDetails,
            [EnumMember]
            FullAccess,
            [EnumMember]
            Yes
        }
        [DataContract]
        [Flags]
        public enum UserStatus
        {
            [EnumMember]
            Disabled,
            [EnumMember]
            Active,
            [EnumMember]
            Invited,
            [EnumMember]
            Locked
        }
        [DataContract]
        [Flags]
        public enum SecurityGroupAdministrativeLevel
        {
            [EnumMember]
            None,
            [EnumMember]
            ChannelAdministrator,
            [EnumMember]
            Administrator
            
        }

        [DataContract]
        [Flags]
        public enum UserLoginStatus
        {
            [EnumMember]
            InvalidPassword,
            [EnumMember]
            DisabledUser,
            [EnumMember]
            LockedUser,
            [EnumMember]
            NoRoles,
            [EnumMember]
            NoActiveClients,
            [EnumMember]
            ShowProfileChangeMessage
        }

    }
}
