(function(a,c){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI;
b.CheckBoxListSelectedIndexChangedEventArgs=function(d){b.CheckBoxListSelectedIndexChangedEventArgs.initializeBase(this);
this._newSelectedIndex=d;
};
b.CheckBoxListSelectedIndexChangedEventArgs.prototype={get_newSelectedIndex:function(){return this._newSelectedIndex;
}};
b.CheckBoxListSelectedIndexChangedEventArgs.registerClass("Telerik.Web.UI.CheckBoxListSelectedIndexChangedEventArgs",Sys.EventArgs);
if(b.createRadEventArgs===c){b.createRadEventArgs=function(e,d){b[e]=function(){var f=Array.prototype.slice.call(arguments);
b[e].initializeBase(this,f);
};
b[e].registerClass("Telerik.Web.UI."+e,d);
};
}b.createRadEventArgs("RadCheckBoxListSelectedIndexChangedEventArgs",b.CheckBoxListSelectedIndexChangedEventArgs);
})($telerik.$);
(function(a,b,c){Type.registerNamespace("Telerik.Web.UI");
$telerik.toCheckBoxList=function(d){return d;
};
$telerik.findCheckBoxList=$find;
b.RadCheckBoxList=function(d){b.RadCheckBoxList.initializeBase(this,[d]);
this._rtlCssClass="RadCheckBoxList_Rtl";
this._waiAriaRole="group";
this._selectedIndices=[];
};
b.RadCheckBoxList.prototype={initialize:function(){b.RadCheckBoxList.callBaseMethod(this,"initialize");
},get_selectedItems:function(){var d=[];
this.get_items().forEach(function(e){if(e.get_selected()){d.push(e);
}});
return d;
},_onCheckableButtonCheckedChanged:function(f,e){b.RadCheckBoxList.callBaseMethod(this,"_onCheckableButtonCheckedChanged",[f,e]);
var d=a(this.get_element()).find(".RadButton").index(f.get_element());
this._selectIndex(d);
},_selectIndex:function(e){var f=this._getSelectedIndices();
this._selectedIndices=f;
this._selectedIndex=f[0];
var d=new b.CheckBoxListSelectedIndexChangedEventArgs(e);
b.RadCheckBoxList.callBaseMethod(this,"_selectIndex",[d,true]);
},_getSelectedIndices:function(){var d=[];
this.get_items().forEach(function(f,e){if(f.get_selected()){d.push(e);
}});
return d;
},saveClientState:function(){return b.RadCheckBoxList.callBaseMethod(this,"saveClientState",[["selectedIndices"]]);
}};
b.RadCheckBoxList.registerClass("Telerik.Web.UI.RadCheckBoxList",b.RadButtonList);
a.registerControlProperties(b.RadCheckBoxList,{selectedIndices:[]});
})($telerik.$,Telerik.Web.UI);
