(function(b,a){a("kendo.color",["kendo.core"],b);
}(function(){var a={id:"color",name:"Color utils",category:"framework",advanced:true,description:"Color utilities used across components",depends:["core"]};
(function(b,o,p){var h=function(x){var r=this,s=h.formats,w,v,u,t,q;
if(arguments.length===1){x=r.resolveColor(x);
for(t=0;
t<s.length;
t++){w=s[t].re;
v=s[t].process;
u=w.exec(x);
if(u){q=v(u);
r.r=q[0];
r.g=q[1];
r.b=q[2];
}}}else{r.r=arguments[0];
r.g=arguments[1];
r.b=arguments[2];
}r.r=r.normalizeByte(r.r);
r.g=r.normalizeByte(r.g);
r.b=r.normalizeByte(r.b);
};
h.prototype={toHex:function(){var q=this,t=q.padDigit,u=q.r.toString(16),s=q.g.toString(16),i=q.b.toString(16);
return"#"+t(u)+t(s)+t(i);
},resolveColor:function(i){i=i||"black";
if(i.charAt(0)=="#"){i=i.substr(1,6);
}i=i.replace(/ /g,"");
i=i.toLowerCase();
i=h.namedColors[i]||i;
return i;
},normalizeByte:function(i){return i<0||isNaN(i)?0:i>255?255:i;
},padDigit:function(i){return i.length===1?"0"+i:i;
},brightness:function(r){var i=this,q=Math.round;
i.r=q(i.normalizeByte(i.r*r));
i.g=q(i.normalizeByte(i.g*r));
i.b=q(i.normalizeByte(i.b*r));
return i;
},percBrightness:function(){var i=this;
return Math.sqrt(0.241*i.r*i.r+0.691*i.g*i.g+0.06800000000000001*i.b*i.b);
}};
h.formats=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(i){return[p(i[1],10),p(i[2],10),p(i[3],10)];
}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(i){return[p(i[1],16),p(i[2],16),p(i[3],16)];
}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(i){return[p(i[1]+i[1],16),p(i[2]+i[2],16),p(i[3]+i[3],16)];
}}];
h.namedColors={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgrey:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",grey:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"778899",lightslategrey:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"};
var m=["transparent"];
for(var l in h.namedColors){if(h.namedColors.hasOwnProperty(l)){m.push(l);
}}m=new RegExp("^("+m.join("|")+")(\\W|$)","i");
function n(i,r){var q,s;
if(i==null||i=="none"){return null;
}if(i instanceof d){return i;
}i=i.toLowerCase();
if(q=m.exec(i)){if(q[1]=="transparent"){i=new g(1,1,1,0);
}else{i=n(h.namedColors[q[1]],r);
}i.match=[q[1]];
return i;
}if(q=/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})\b/i.exec(i)){s=new c(p(q[1],16),p(q[2],16),p(q[3],16),1);
}else{if(q=/^#?([0-9a-f])([0-9a-f])([0-9a-f])\b/i.exec(i)){s=new c(p(q[1]+q[1],16),p(q[2]+q[2],16),p(q[3]+q[3],16),1);
}else{if(q=/^rgb\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/.exec(i)){s=new c(p(q[1],10),p(q[2],10),p(q[3],10),1);
}else{if(q=/^rgba\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9.]+)\s*\)/.exec(i)){s=new c(p(q[1],10),p(q[2],10),p(q[3],10),o(q[4]));
}else{if(q=/^rgb\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*\)/.exec(i)){s=new g(o(q[1])/100,o(q[2])/100,o(q[3])/100,1);
}else{if(q=/^rgba\(\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9]*\.?[0-9]+)%\s*,\s*([0-9.]+)\s*\)/.exec(i)){s=new g(o(q[1])/100,o(q[2])/100,o(q[3])/100,o(q[4]));
}}}}}}if(s){s.match=q;
}else{if(!r){throw new Error("Cannot parse color: "+i);
}}return s;
}function j(i,r,q){if(!q){q="0";
}i=i.toString(16);
while(r>i.length){i="0"+i;
}return i;
}function k(i,r,s){if(s<0){s+=1;
}if(s>1){s-=1;
}if(s<1/6){return i+(r-i)*6*s;
}if(s<1/2){return r;
}if(s<2/3){return i+(r-i)*(2/3-s)*6;
}return i;
}var d=kendo.Class.extend({toHSV:function(){return this;
},toRGB:function(){return this;
},toHex:function(){return this.toBytes().toHex();
},toBytes:function(){return this;
},toCss:function(){return"#"+this.toHex();
},toCssRgba:function(){var i=this.toBytes();
return"rgba("+i.r+", "+i.g+", "+i.b+", "+o((+this.a).toFixed(3))+")";
},toDisplay:function(){if(kendo.support.browser.msie&&kendo.support.browser.version<9){return this.toCss();
}return this.toCssRgba();
},equals:function(i){return i===this||i!==null&&this.toCssRgba()==n(i).toCssRgba();
},diff:function(q){if(q==null){return NaN;
}var i=this.toBytes();
q=q.toBytes();
return Math.sqrt(Math.pow((i.r-q.r)*0.3,2)+Math.pow((i.g-q.g)*0.59,2)+Math.pow((i.b-q.b)*0.11,2));
},clone:function(){var i=this.toBytes();
if(i===this){i=new c(i.r,i.g,i.b,i.a);
}return i;
}});
var g=d.extend({init:function(t,s,q,i){this.r=t;
this.g=s;
this.b=q;
this.a=i;
},toHSV:function(){var x,w,q,u,z,A;
var y=this.r,t=this.g,i=this.b;
x=Math.min(y,t,i);
w=Math.max(y,t,i);
A=w;
q=w-x;
if(q===0){return new f(0,0,A,this.a);
}if(w!==0){z=q/w;
if(y==w){u=(t-i)/q;
}else{if(t==w){u=2+(i-y)/q;
}else{u=4+(y-t)/q;
}}u*=60;
if(u<0){u+=360;
}}else{z=0;
u=-1;
}return new f(u,z,A,this.a);
},toHSL:function(){var y=this.r,t=this.g,i=this.b;
var w=Math.max(y,t,i),x=Math.min(y,t,i);
var u,z,v=(w+x)/2;
if(w==x){u=z=0;
}else{var q=w-x;
z=v>0.5?q/(2-w-x):q/(w+x);
switch(w){case y:u=(t-i)/q+(t<i?6:0);
break;
case t:u=(i-y)/q+2;
break;
case i:u=(y-t)/q+4;
break;
}u*=60;
z*=100;
v*=100;
}return new e(u,z,v,this.a);
},toBytes:function(){return new c(this.r*255,this.g*255,this.b*255,this.a);
}});
var c=g.extend({init:function(t,s,q,i){this.r=Math.round(t);
this.g=Math.round(s);
this.b=Math.round(q);
this.a=i;
},toRGB:function(){return new g(this.r/255,this.g/255,this.b/255,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toHSL:function(){return this.toRGB().toHSL();
},toHex:function(){return j(this.r,2)+j(this.g,2)+j(this.b,2);
},toBytes:function(){return this;
}});
var f=d.extend({init:function(q,r,t,i){this.h=q;
this.s=r;
this.v=t;
this.a=i;
},toRGB:function(){var y=this.h,D=this.s,F=this.v;
var z,C,x,u,w,A,B,E;
if(D===0){C=x=u=F;
}else{y/=60;
z=Math.floor(y);
w=y-z;
A=F*(1-D);
B=F*(1-D*w);
E=F*(1-D*(1-w));
switch(z){case 0:C=F;
x=E;
u=A;
break;
case 1:C=B;
x=F;
u=A;
break;
case 2:C=A;
x=F;
u=E;
break;
case 3:C=A;
x=B;
u=F;
break;
case 4:C=E;
x=A;
u=F;
break;
default:C=F;
x=A;
u=B;
break;
}}return new g(C,x,u,this.a);
},toHSL:function(){return this.toRGB().toHSL();
},toBytes:function(){return this.toRGB().toBytes();
}});
var e=d.extend({init:function(q,t,r,i){this.h=q;
this.s=t;
this.l=r;
this.a=i;
},toRGB:function(){var u=this.h,z=this.s,v=this.l;
var y,t,i;
if(z===0){y=t=i=v;
}else{u/=360;
z/=100;
v/=100;
var x=v<0.5?v*(1+z):v+z-v*z;
var w=2*v-x;
y=k(w,x,u+1/3);
t=k(w,x,u);
i=k(w,x,u-1/3);
}return new g(y,t,i,this.a);
},toHSV:function(){return this.toRGB().toHSV();
},toBytes:function(){return this.toRGB().toBytes();
}});
h.fromBytes=function(t,s,q,i){return new c(t,s,q,i!=null?i:1);
};
h.fromRGB=function(t,s,q,i){return new g(t,s,q,i!=null?i:1);
};
h.fromHSV=function(q,r,t,i){return new f(q,r,t,i!=null?i:1);
};
h.fromHSL=function(q,t,r,i){return new e(q,t,r,i!=null?i:1);
};
kendo.Color=h;
kendo.parseColor=n;
}(window.kendo.jQuery,parseFloat,parseInt));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
