(function(b,a){a("kendo.core",["jquery"],b);
}(function(){var a={id:"core",name:"Core",category:"framework",description:"The core of the Kendo framework."};
(function(b,aP,aL){var W=aP.kendo=aP.kendo||{cultures:{}},D=b.extend,u=b.each,P=b.isArray,at=b.proxy,ae=b.noop,aa=Math,aF,T=aP.JSON||{},aE={},ap=/%/,F=/\{(\d+)(:[^\}]+)?\}/g,j=/(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+)?/i,ah=/^(\+|-?)\d+(\.?)\d*$/,G="function",aD="string",ag="number",ai="object",af="null",i="boolean",aM="undefined",M={},az={},aC=[].slice;
W.version="2016.3.913".replace(/^\s+|\s+$/g,"");
function k(){}k.extend=function(aW){var aT=function(){},aV,aY=this,aX=aW&&aW.init?aW.init:function(){aY.apply(this,arguments);
},aU;
aT.prototype=aY.prototype;
aU=aX.fn=aX.prototype=new aT();
for(aV in aW){if(aW[aV]!=null&&aW[aV].constructor===Object){aU[aV]=D(true,{},aT.prototype[aV],aW[aV]);
}else{aU[aV]=aW[aV];
}}aU.constructor=aX;
aX.extend=aY.extend;
return aX;
};
k.prototype._initOptions=function(aT){this.options=r({},this.options,aT);
};
var R=W.isFunction=function(aT){return typeof aT==="function";
};
var ar=function(){this._defaultPrevented=true;
};
var Q=function(){return this._defaultPrevented===true;
};
var aj=k.extend({init:function(){this._events={};
},bind:function(aT,aX,a1){var a3=this,aZ,aU=typeof aT===aD?[aT]:aT,a0,a2,aW,aY=typeof aX===G,aV;
if(aX===aL){for(aZ in aT){a3.bind(aZ,aT[aZ]);
}return a3;
}for(aZ=0,a0=aU.length;
aZ<a0;
aZ++){aT=aU[aZ];
aW=aY?aX:aX[aT];
if(aW){if(a1){a2=aW;
aW=function(){a3.unbind(aT,aW);
a2.apply(a3,arguments);
};
aW.original=a2;
}aV=a3._events[aT]=a3._events[aT]||[];
aV.push(aW);
}}return a3;
},one:function(aT,aU){return this.bind(aT,aU,true);
},first:function(aT,aX){var a1=this,aZ,aU=typeof aT===aD?[aT]:aT,a0,aW,aY=typeof aX===G,aV;
for(aZ=0,a0=aU.length;
aZ<a0;
aZ++){aT=aU[aZ];
aW=aY?aX:aX[aT];
if(aW){aV=a1._events[aT]=a1._events[aT]||[];
aV.unshift(aW);
}}return a1;
},trigger:function(aU,aT){var aY=this,aV=aY._events[aU],aW,aX;
if(aV){aT=aT||{};
aT.sender=aY;
aT._defaultPrevented=false;
aT.preventDefault=ar;
aT.isDefaultPrevented=Q;
aV=aV.slice();
for(aW=0,aX=aV.length;
aW<aX;
aW++){aV[aW].call(aY,aT);
}return aT._defaultPrevented===true;
}return false;
},unbind:function(aT,aV){var aX=this,aU=aX._events[aT],aW;
if(aT===aL){aX._events={};
}else{if(aU){if(aV){for(aW=aU.length-1;
aW>=0;
aW--){if(aU[aW]===aV||aU[aW].original===aV){aU.splice(aW,1);
}}}else{aX._events[aT]=[];
}}}return aX;
}});
function l(aU,aW){if(aW){return"'"+aU.split("'").join("\\'").split('\\"').join('\\\\\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")+"'";
}else{var aT=aU.charAt(0),aV=aU.substring(1);
if(aT==="="){return"+("+aV+")+";
}else{if(aT===":"){return"+$kendoHtmlEncode("+aV+")+";
}else{return";"+aU+";$kendoOutput+=";
}}}}var h=/^\w+/,w=/\$\{([^}]*)\}/g,x=/\\\}/g,o=/__CURLY__/g,y=/\\#/g,aA=/__SHARP__/g,aS=["","0","00","000","0000"];
aF={paramName:"data",useWithBlock:true,render:function(aX,aT){var aV,aW,aU="";
for(aV=0,aW=aT.length;
aV<aW;
aV++){aU+=aX(aT[aV]);
}return aU;
},compile:function(a2,aY){var a1=D({},this,aY),aZ=a1.paramName,aT=aZ.match(h)[0],a3=a1.useWithBlock,aW="var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;",aV,a0,aX;
if(R(a2)){return a2;
}aW+=a3?"with("+aZ+"){":"";
aW+="$kendoOutput=";
a0=a2.replace(x,"__CURLY__").replace(w,"#=$kendoHtmlEncode($1)#").replace(o,"}").replace(y,"__SHARP__").split("#");
for(aX=0;
aX<a0.length;
aX++){aW+=l(a0[aX],aX%2===0);
}aW+=a3?";}":";";
aW+="return $kendoOutput;";
aW=aW.replace(aA,"#");
try{aV=new Function(aT,aW);
aV._slotCount=Math.floor(a0.length/2);
return aV;
}catch(aU){throw new Error(W.format("Invalid template:'{0}' Generated code:'{1}'",a2,aW));
}}};
function al(aV,aT,aU){aV=aV+"";
aT=aT||2;
aU=aT-aV.length;
if(aU){return aS[aT].substring(0,aU)+aV;
}return aV;
}(function(){var aT=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,aU,aV,aW={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},aY,a0={}.toString;
if(typeof Date.prototype.toJSON!==G){Date.prototype.toJSON=function(){var a1=this;
return isFinite(a1.valueOf())?al(a1.getUTCFullYear(),4)+"-"+al(a1.getUTCMonth()+1)+"-"+al(a1.getUTCDate())+"T"+al(a1.getUTCHours())+":"+al(a1.getUTCMinutes())+":"+al(a1.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();
};
}function aX(a1){aT.lastIndex=0;
return aT.test(a1)?'"'+a1.replace(aT,function(a2){var a3=aW[a2];
return typeof a3===aD?a3:"\\u"+("0000"+a2.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+a1+'"';
}function aZ(a4,a1){var a2,a3,a9,a5,a6=aU,a7,ba=a1[a4],a8;
if(ba&&typeof ba===ai&&typeof ba.toJSON===G){ba=ba.toJSON(a4);
}if(typeof aY===G){ba=aY.call(a1,a4,ba);
}a8=typeof ba;
if(a8===aD){return aX(ba);
}else{if(a8===ag){return isFinite(ba)?String(ba):af;
}else{if(a8===i||a8===af){return String(ba);
}else{if(a8===ai){if(!ba){return af;
}aU+=aV;
a7=[];
if(a0.apply(ba)==="[object Array]"){a5=ba.length;
for(a2=0;
a2<a5;
a2++){a7[a2]=aZ(a2,ba)||af;
}a9=a7.length===0?"[]":aU?"[\n"+aU+a7.join(",\n"+aU)+"\n"+a6+"]":"["+a7.join(",")+"]";
aU=a6;
return a9;
}if(aY&&typeof aY===ai){a5=aY.length;
for(a2=0;
a2<a5;
a2++){if(typeof aY[a2]===aD){a3=aY[a2];
a9=aZ(a3,ba);
if(a9){a7.push(aX(a3)+(aU?": ":":")+a9);
}}}}else{for(a3 in ba){if(Object.hasOwnProperty.call(ba,a3)){a9=aZ(a3,ba);
if(a9){a7.push(aX(a3)+(aU?": ":":")+a9);
}}}}a9=a7.length===0?"{}":aU?"{\n"+aU+a7.join(",\n"+aU)+"\n"+a6+"}":"{"+a7.join(",")+"}";
aU=a6;
return a9;
}}}}}if(typeof T.stringify!==G){T.stringify=function(a4,a2,a3){var a1;
aU="";
aV="";
if(typeof a3===ag){for(a1=0;
a1<a3;
a1+=1){aV+=" ";
}}else{if(typeof a3===aD){aV=a3;
}}aY=a2;
if(a2&&typeof a2!==G&&(typeof a2!==ai||typeof a2.length!==ag)){throw new Error("JSON.stringify");
}return aZ("",{"":a4});
};
}}());
(function(){var aV=/dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|HH|H|hh|h|mm|m|fff|ff|f|tt|ss|s|zzz|zz|z|"[^"]*"|'[^']*'/g,a9=/^(n|c|p|e)(\d*)$/i,a3=/(\\.)|(['][^']*[']?)|(["][^"]*["]?)/g,aU=/\,/g,aW="",a6=".",aT=",",a8="#",bb="0",a5="??",aX="en-US",a4={}.toString;
W.cultures["en-US"]={name:aX,numberFormat:{pattern:["-n"],decimals:2,",":",",".":".",groupSize:[3],percent:{pattern:["-n %","n %"],decimals:2,",":",",".":".",groupSize:[3],symbol:"%"},currency:{name:"US Dollar",abbr:"USD",pattern:["($n)","$n"],decimals:2,",":",",".":".",groupSize:[3],symbol:"$"}},calendars:{standard:{days:{names:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],namesAbbr:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],namesShort:["Su","Mo","Tu","We","Th","Fr","Sa"]},months:{names:["January","February","March","April","May","June","July","August","September","October","November","December"],namesAbbr:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},AM:["AM","am","AM"],PM:["PM","pm","PM"],patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",F:"dddd, MMMM dd, yyyy h:mm:ss tt",g:"M/d/yyyy h:mm tt",G:"M/d/yyyy h:mm:ss tt",m:"MMMM dd",M:"MMMM dd",s:"yyyy'-'MM'-'ddTHH':'mm':'ss",t:"h:mm tt",T:"h:mm:ss tt",u:"yyyy'-'MM'-'dd HH':'mm':'ss'Z'",y:"MMMM, yyyy",Y:"MMMM, yyyy"},"/":"/",":":":",firstDay:0,twoDigitYearMax:2029}}};
function aY(bc){if(bc){if(bc.numberFormat){return bc;
}if(typeof bc===aD){var bd=W.cultures;
return bd[bc]||bd[bc.split("-")[0]]||null;
}return null;
}return null;
}function a1(bc){if(bc){bc=aY(bc);
}return bc||W.cultures.current;
}W.culture=function(bd){var be=W.cultures,bc;
if(bd!==aL){bc=aY(bd)||be[aX];
bc.calendar=bc.calendars.standard;
be.current=bc;
}else{return be.current;
}};
W.findCulture=aY;
W.getCulture=a1;
W.culture(aX);
function aZ(be,bg,bd){bd=a1(bd);
var bc=bd.calendars.standard,bf=bc.days,bh=bc.months;
bg=bc.patterns[bg]||bg;
return bg.replace(aV,function(bi){var bj;
var bk;
var bl;
if(bi==="d"){bk=be.getDate();
}else{if(bi==="dd"){bk=al(be.getDate());
}else{if(bi==="ddd"){bk=bf.namesAbbr[be.getDay()];
}else{if(bi==="dddd"){bk=bf.names[be.getDay()];
}else{if(bi==="M"){bk=be.getMonth()+1;
}else{if(bi==="MM"){bk=al(be.getMonth()+1);
}else{if(bi==="MMM"){bk=bh.namesAbbr[be.getMonth()];
}else{if(bi==="MMMM"){bk=bh.names[be.getMonth()];
}else{if(bi==="yy"){bk=al(be.getFullYear()%100);
}else{if(bi==="yyyy"){bk=al(be.getFullYear(),4);
}else{if(bi==="h"){bk=be.getHours()%12||12;
}else{if(bi==="hh"){bk=al(be.getHours()%12||12);
}else{if(bi==="H"){bk=be.getHours();
}else{if(bi==="HH"){bk=al(be.getHours());
}else{if(bi==="m"){bk=be.getMinutes();
}else{if(bi==="mm"){bk=al(be.getMinutes());
}else{if(bi==="s"){bk=be.getSeconds();
}else{if(bi==="ss"){bk=al(be.getSeconds());
}else{if(bi==="f"){bk=aa.floor(be.getMilliseconds()/100);
}else{if(bi==="ff"){bk=be.getMilliseconds();
if(bk>99){bk=aa.floor(bk/10);
}bk=al(bk);
}else{if(bi==="fff"){bk=al(be.getMilliseconds(),3);
}else{if(bi==="tt"){bk=be.getHours()<12?bc.AM[0]:bc.PM[0];
}else{if(bi==="zzz"){bj=be.getTimezoneOffset();
bl=bj<0;
bk=aa.abs(bj/60).toString().split(".")[0];
bj=aa.abs(bj)-bk*60;
bk=(bl?"+":"-")+al(bk);
bk+=":"+al(bj);
}else{if(bi==="zz"||bi==="z"){bk=be.getTimezoneOffset()/60;
bl=bk<0;
bk=aa.abs(bk).toString().split(".")[0];
bk=(bl?"+":"-")+(bi==="zz"?al(bk):bk);
}}}}}}}}}}}}}}}}}}}}}}}}return bk!==aL?bk:bi.slice(1,bi.length-1);
});
}function a0(bz,bj,bd){bd=a1(bd);
var bA=bd.numberFormat,bg=bA[a6],bD=bA.decimals,bB=bA.pattern[0],bx=[],bI,bu,bv,bf,bk,by=bz<0,bs,bl,bt,bm,bE=aW,bJ=aW,br,bw,bc,bn,bo,bh,bF,bK,bq,bp,bC,be,bH,bG=-1,bi;
if(bz===aL){return aW;
}if(!isFinite(bz)){return bz;
}if(!bj){return bd.name.length?bz.toLocaleString():bz.toString();
}bk=a9.exec(bj);
if(bk){bj=bk[1].toLowerCase();
bu=bj==="c";
bv=bj==="p";
if(bu||bv){bA=bu?bA.currency:bA.percent;
bg=bA[a6];
bD=bA.decimals;
bI=bA.symbol;
bB=bA.pattern[by?0:1];
}bf=bk[2];
if(bf){bD=+bf;
}if(bj==="e"){return bf?bz.toExponential(bD):bz.toExponential();
}if(bv){bz*=100;
}bz=a7(bz,bD);
by=bz<0;
bz=bz.split(a6);
bs=bz[0];
bl=bz[1];
if(by){bs=bs.substring(1);
}bJ=a2(bs,0,bs.length,bA);
if(bl){bJ+=bg+bl;
}if(bj==="n"&&!by){return bJ;
}bz=aW;
for(br=0,bw=bB.length;
br<bw;
br++){bc=bB.charAt(br);
if(bc==="n"){bz+=bJ;
}else{if(bc==="$"||bc==="%"){bz+=bI;
}else{bz+=bc;
}}}return bz;
}if(by){bz=-bz;
}if(bj.indexOf("'")>-1||bj.indexOf('"')>-1||bj.indexOf("\\")>-1){bj=bj.replace(a3,function(bM){var bN=bM.charAt(0).replace("\\",""),bL=bM.slice(1).replace(bN,"");
bx.push(bL);
return a5;
});
}bj=bj.split(";");
if(by&&bj[1]){bj=bj[1];
bo=true;
}else{if(bz===0){bj=bj[2]||bj[0];
if(bj.indexOf(a8)==-1&&bj.indexOf(bb)==-1){return bj;
}}else{bj=bj[0];
}}bC=bj.indexOf("%");
be=bj.indexOf("$");
bv=bC!=-1;
bu=be!=-1;
if(bv){bz*=100;
}if(bu&&bj[be-1]==="\\"){bj=bj.split("\\").join("");
bu=false;
}if(bu||bv){bA=bu?bA.currency:bA.percent;
bg=bA[a6];
bD=bA.decimals;
bI=bA.symbol;
}bn=bj.indexOf(aT)>-1;
if(bn){bj=bj.replace(aU,aW);
}bh=bj.indexOf(a6);
bw=bj.length;
if(bh!=-1){bl=bz.toString().split("e");
if(bl[1]){bl=a7(bz,Math.abs(bl[1]));
}else{bl=bl[0];
}bl=bl.split(a6)[1]||aW;
bK=bj.lastIndexOf(bb)-bh;
bF=bj.lastIndexOf(a8)-bh;
bq=bK>-1;
bp=bF>-1;
br=bl.length;
if(!bq&&!bp){bj=bj.substring(0,bh)+bj.substring(bh+1);
bw=bj.length;
bh=-1;
br=0;
}if(bq&&bK>bF){br=bK;
}else{if(bF>bK){if(bp&&br>bF){br=bF;
}else{if(bq&&br<bK){br=bK;
}}}}if(br>-1){bz=a7(bz,br);
}}else{bz=a7(bz);
}bF=bj.indexOf(a8);
bH=bK=bj.indexOf(bb);
if(bF==-1&&bK!=-1){bG=bK;
}else{if(bF!=-1&&bK==-1){bG=bF;
}else{bG=bF>bK?bK:bF;
}}bF=bj.lastIndexOf(a8);
bK=bj.lastIndexOf(bb);
if(bF==-1&&bK!=-1){bi=bK;
}else{if(bF!=-1&&bK==-1){bi=bF;
}else{bi=bF>bK?bF:bK;
}}if(bG==bw){bi=bG;
}if(bG!=-1){bJ=bz.toString().split(a6);
bs=bJ[0];
bl=bJ[1]||aW;
bt=bs.length;
bm=bl.length;
if(by&&bz*-1>=0){by=false;
}bz=bj.substring(0,bG);
if(by&&!bo){bz+="-";
}for(br=bG;
br<bw;
br++){bc=bj.charAt(br);
if(bh==-1){if(bi-br<bt){bz+=bs;
break;
}}else{if(bK!=-1&&bK<br){bE=aW;
}if(bh-br<=bt&&bh-br>-1){bz+=bs;
br=bh;
}if(bh===br){bz+=(bl?bg:aW)+bl;
br+=bi-bh+1;
continue;
}}if(bc===bb){bz+=bc;
bE=bc;
}else{if(bc===a8){bz+=bE;
}}}if(bn){bz=a2(bz,bG+(by?1:0),Math.max(bi,bt+bG),bA);
}if(bi>=bG){bz+=bj.substring(bi+1);
}if(bu||bv){bJ=aW;
for(br=0,bw=bz.length;
br<bw;
br++){bc=bz.charAt(br);
bJ+=bc==="$"||bc==="%"?bI:bc;
}bz=bJ;
}bw=bx.length;
if(bw){for(br=0;
br<bw;
br++){bz=bz.replace(a5,bx[br]);
}}}return bz;
}var a2=function(bk,bn,bd,bl){var bc=bk.indexOf(bl[a6]);
var bf=bl.groupSize.slice();
var be=bf.shift();
var bh,bi;
var bg,bm,bo;
var bj;
bd=bc!==-1?bc:bd+1;
bh=bk.substring(bn,bd);
bi=bh.length;
if(bi>=be){bg=bi;
bm=[];
while(bg>-1){bo=bh.substring(bg-be,bg);
if(bo){bm.push(bo);
}bg-=be;
bj=bf.shift();
be=bj!==aL?bj:be;
if(be===0){bm.push(bh.substring(0,bg));
break;
}}bh=bm.reverse().join(bl[aT]);
bk=bk.substring(0,bn)+bh+bk.substring(bd);
}return bk;
};
var a7=function(bd,bc){bc=bc||0;
bd=bd.toString().split("e");
bd=Math.round(+(bd[0]+"e"+(bd[1]?+bd[1]+bc:bc)));
bd=bd.toString().split("e");
bd=+(bd[0]+"e"+(bd[1]?+bd[1]-bc:-bc));
return bd.toFixed(Math.min(bc,20));
};
var ba=function(be,bd,bc){if(bd){if(a4.call(be)==="[object Date]"){return aZ(be,bd,bc);
}else{if(typeof be===ag){return a0(be,bd,bc);
}}}return be!==aL?be:"";
};
W.format=function(bc){var bd=arguments;
return bc.replace(F,function(bf,be,bg){var bh=bd[parseInt(be,10)+1];
return ba(bh,bg?bg.substring(1):"");
});
};
W._extractFormat=function(bc){if(bc.slice(0,3)==="{0:"){bc=bc.slice(3,bc.length-1);
}return bc;
};
W._activeElement=function(){try{return document.activeElement;
}catch(bc){return document.documentElement.activeElement;
}};
W._round=a7;
W.toString=ba;
}());
(function(){var a3=/\u00A0/g,aW=/[eE][\-+]?[0-9]+/,ba=/[+|\-]\d{1,2}/,aZ=/[+|\-]\d{1,2}:?\d{2}/,aU=/^\/Date\((.*?)\)\/$/,a6=/[+-]\d*/,aX=[[],["G","g","F"],["D","d","y","m","T","t"]],bb=[["yyyy-MM-ddTHH:mm:ss.fffffffzzz","yyyy-MM-ddTHH:mm:ss.fffffff","yyyy-MM-ddTHH:mm:ss.fffzzz","yyyy-MM-ddTHH:mm:ss.fff","ddd MMM dd yyyy HH:mm:ss","yyyy-MM-ddTHH:mm:sszzz","yyyy-MM-ddTHH:mmzzz","yyyy-MM-ddTHH:mmzz","yyyy-MM-ddTHH:mm:ss","yyyy-MM-dd HH:mm:ss","yyyy/MM/dd HH:mm:ss"],["yyyy-MM-ddTHH:mm","yyyy-MM-dd HH:mm","yyyy/MM/dd HH:mm"],["yyyy/MM/dd","yyyy-MM-dd","HH:mm:ss","HH:mm"]],a4={2:/^\d{1,2}/,3:/^\d{1,3}/,4:/^\d{4}/},a5={}.toString;
function a7(be,bd,bc){return !(be>=bd&&be<=bc);
}function aV(bc){return bc.charAt(0);
}function a2(bc){return b.map(bc,aV);
}function aT(bc,bd){if(!bd&&bc.getHours()===23){bc.setHours(bc.getHours()+2);
}}function a0(bd){var be=0,bf=bd.length,bc=[];
for(;
be<bf;
be++){bc[be]=(bd[be]+"").toLowerCase();
}return bc;
}function a1(bc){var bd={},be;
for(be in bc){bd[be]=a0(bc[be]);
}return bd;
}function a8(bH,bl,bh){if(!bH){return null;
}var bu=function(bL){var bK=0;
while(bl[br]===bL){bK++;
br++;
}if(bK>0){br-=1;
}return bK;
},bn=function(bM){var bL=a4[bM]||new RegExp("^\\d{1,"+bM+"}"),bK=bH.substr(bI,bM).match(bL);
if(bK){bK=bK[0];
bI+=bK.length;
return parseInt(bK,10);
}return null;
},bm=function(bR,bM){var bK=0,bL=bR.length,bP,bQ,bO=0,bN=0,bS;
for(;
bK<bL;
bK++){bP=bR[bK];
bQ=bP.length;
bS=bH.substr(bI,bQ);
if(bM){bS=bS.toLowerCase();
}if(bS==bP&&bQ>bO){bO=bQ;
bN=bK;
}}if(bO){bI+=bO;
return bN+1;
}return null;
},bf=function(){var bK=false;
if(bH.charAt(bI)===bl[br]){bI++;
bK=true;
}return bK;
},bd=bh.calendars.standard,bJ=null,bA=null,bj=null,bp=null,by=null,bE=null,bx=null,br=0,bI=0,bt=false,bi=new Date(),bF=bd.twoDigitYearMax||2029,bk=bi.getFullYear(),be,bg,bs,bB,bD,bG,bw,bc,bC,bq,bz,bo,bv;
if(!bl){bl="d";
}bB=bd.patterns[bl];
if(bB){bl=bB;
}bl=bl.split("");
bs=bl.length;
for(;
br<bs;
br++){be=bl[br];
if(bt){if(be==="'"){bt=false;
}else{bf();
}}else{if(be==="d"){bg=bu("d");
if(!bd._lowerDays){bd._lowerDays=a1(bd.days);
}if(bj!==null&&bg>2){continue;
}bj=bg<3?bn(2):bm(bd._lowerDays[bg==3?"namesAbbr":"names"],true);
if(bj===null||a7(bj,1,31)){return null;
}}else{if(be==="M"){bg=bu("M");
if(!bd._lowerMonths){bd._lowerMonths=a1(bd.months);
}bA=bg<3?bn(2):bm(bd._lowerMonths[bg==3?"namesAbbr":"names"],true);
if(bA===null||a7(bA,1,12)){return null;
}bA-=1;
}else{if(be==="y"){bg=bu("y");
bJ=bn(bg);
if(bJ===null){return null;
}if(bg==2){if(typeof bF==="string"){bF=bk+parseInt(bF,10);
}bJ=bk-bk%100+bJ;
if(bJ>bF){bJ-=100;
}}}else{if(be==="h"){bu("h");
bp=bn(2);
if(bp==12){bp=0;
}if(bp===null||a7(bp,0,11)){return null;
}}else{if(be==="H"){bu("H");
bp=bn(2);
if(bp===null||a7(bp,0,23)){return null;
}}else{if(be==="m"){bu("m");
by=bn(2);
if(by===null||a7(by,0,59)){return null;
}}else{if(be==="s"){bu("s");
bE=bn(2);
if(bE===null||a7(bE,0,59)){return null;
}}else{if(be==="f"){bg=bu("f");
bv=bH.substr(bI,bg).match(a4[3]);
bx=bn(bg);
if(bx!==null){bx=parseFloat("0."+bv[0],10);
bx=W._round(bx,3);
bx*=1000;
}if(bx===null||a7(bx,0,999)){return null;
}}else{if(be==="t"){bg=bu("t");
bc=bd.AM;
bC=bd.PM;
if(bg===1){bc=a2(bc);
bC=a2(bC);
}bD=bm(bC);
if(!bD&&!bm(bc)){return null;
}}else{if(be==="z"){bG=true;
bg=bu("z");
if(bH.substr(bI,1)==="Z"){bf();
continue;
}bw=bH.substr(bI,6).match(bg>2?aZ:ba);
if(!bw){return null;
}bw=bw[0].split(":");
bq=bw[0];
bz=bw[1];
if(!bz&&bq.length>3){bI=bq.length-2;
bz=bq.substring(bI);
bq=bq.substring(0,bI);
}bq=parseInt(bq,10);
if(a7(bq,-12,13)){return null;
}if(bg>2){bz=parseInt(bz,10);
if(isNaN(bz)||a7(bz,0,59)){return null;
}}}else{if(be==="'"){bt=true;
bf();
}else{if(!bf()){return null;
}}}}}}}}}}}}}}bo=bp!==null||by!==null||bE||null;
if(bJ===null&&bA===null&&bj===null&&bo){bJ=bk;
bA=bi.getMonth();
bj=bi.getDate();
}else{if(bJ===null){bJ=bk;
}if(bj===null){bj=1;
}}if(bD&&bp<12){bp+=12;
}if(bG){if(bq){bp+=-bq;
}if(bz){by+=-bz;
}bH=new Date(Date.UTC(bJ,bA,bj,bp,by,bE,bx));
}else{bH=new Date(bJ,bA,bj,bp,by,bE,bx);
aT(bH,bp);
}if(bJ<100){bH.setFullYear(bJ);
}if(bH.getDate()!==bj&&bG===aL){return null;
}return bH;
}function a9(bc){var bd=bc.substr(0,1)==="-"?-1:1;
bc=bc.substring(1);
bc=parseInt(bc.substr(0,2),10)*60+parseInt(bc.substring(2),10);
return bd*bc;
}function aY(bc){var bh=aa.max(aX.length,bb.length);
var bi=bc.calendar.patterns;
var bd,be,bg;
var bf=[];
for(bg=0;
bg<bh;
bg++){bd=aX[bg];
for(be=0;
be<bd.length;
be++){bf.push(bi[bd[be]]);
}bf=bf.concat(bb[bg]);
}return bf;
}W.parseDate=function(bi,be,bc){if(a5.call(bi)==="[object Date]"){return bi;
}var bf=0;
var bd=null;
var bg;
var bh;
if(bi&&bi.indexOf("/D")===0){bd=aU.exec(bi);
if(bd){bd=bd[1];
bh=a6.exec(bd.substring(1));
bd=new Date(parseInt(bd,10));
if(bh){bh=a9(bh[0]);
bd=W.timezone.apply(bd,0);
bd=W.timezone.convert(bd,0,-1*bh);
}return bd;
}}bc=W.getCulture(bc);
if(!be){be=aY(bc);
}be=P(be)?be:[be];
bg=be.length;
for(;
bf<bg;
bf++){bd=a8(bi,be[bf],bc);
if(bd){return bd;
}}return bd;
};
W.parseInt=function(be,bc){var bd=W.parseFloat(be,bc);
if(bd){bd=bd|0;
}return bd;
};
W.parseFloat=function(bm,bc,be){if(!bm&&bm!==0){return null;
}if(typeof bm===ag){return bm;
}bm=bm.toString();
bc=W.getCulture(bc);
var bh=bc.numberFormat,bj=bh.percent,bd=bh.currency,bl=bd.symbol,bk=bj.symbol,bg=bm.indexOf("-"),bi,bf;
if(aW.test(bm)){bm=parseFloat(bm.replace(bh["."],"."));
if(isNaN(bm)){bm=null;
}return bm;
}if(bg>0){return null;
}else{bg=bg>-1;
}if(bm.indexOf(bl)>-1||be&&be.toLowerCase().indexOf("c")>-1){bh=bd;
bi=bh.pattern[0].replace("$",bl).split("n");
if(bm.indexOf(bi[0])>-1&&bm.indexOf(bi[1])>-1){bm=bm.replace(bi[0],"").replace(bi[1],"");
bg=true;
}}else{if(bm.indexOf(bk)>-1){bf=true;
bh=bj;
bl=bk;
}}bm=bm.replace("-","").replace(bl,"").replace(a3," ").split(bh[","].replace(a3," ")).join("").replace(bh["."],".");
bm=parseFloat(bm);
if(isNaN(bm)){bm=null;
}else{if(bg){bm*=-1;
}}if(bm&&bf){bm/=100;
}return bm;
};
}());
function L(aU){var aW=aU.css(W.support.transitions.css+"box-shadow")||aU.css("box-shadow"),aV=aW?aW.match(j)||[0,0,0,0,0]:[0,0,0,0,0],aT=aa.max(+aV[3],+(aV[4]||0));
return{left:-aV[1]+aT,right:+aV[1]+aT,bottom:+aV[2]+aT};
}function aQ(aV,aT){var aU=aE.browser,aY,aX=aV.css("direction")=="rtl";
if(!aV.parent().hasClass("k-animation-container")){var a1=L(aV),a2=aV[0].style.width,aW=aV[0].style.height,a0=ap.test(a2),aZ=ap.test(aW);
if(aU.opera){a1.left=a1.right=a1.bottom=5;
}aY=a0||aZ;
if(!a0&&(!aT||aT&&a2)){a2=aV.outerWidth();
}if(!aZ&&(!aT||aT&&aW)){aW=aV.outerHeight();
}aV.wrap(b("<div/>").addClass("k-animation-container").css({width:a2,height:aW,marginLeft:a1.left*(aX?1:-1),paddingLeft:a1.left,paddingRight:a1.right,paddingBottom:a1.bottom}));
if(aY){aV.css({width:"100%",height:"100%",boxSizing:"border-box",mozBoxSizing:"border-box",webkitBoxSizing:"border-box"});
}}else{var a3=aV.parent(".k-animation-container"),a4=a3[0].style;
if(a3.is(":hidden")){a3.show();
}aY=ap.test(a4.width)||ap.test(a4.height);
if(!aY){a3.css({width:aV.outerWidth(),height:aV.outerHeight(),boxSizing:"content-box",mozBoxSizing:"content-box",webkitBoxSizing:"content-box"});
}}if(aU.msie&&aa.floor(aU.version)<=7){aV.css({zoom:1});
aV.children(".k-menu").width(aV.width());
}return aV.parent();
}function r(aT){var aU=1,aV=arguments.length;
for(aU=1;
aU<aV;
aU++){s(aT,arguments[aU]);
}return aT;
}function s(aU,a3){var aY=W.data.ObservableArray,aX=W.data.LazyObservableArray,aT=W.data.DataSource,aW=W.data.HierarchicalDataSource,aZ,a2,a1,a0,aV;
for(aZ in a3){a2=a3[aZ];
a1=typeof a2;
if(a1===ai&&a2!==null){a0=a2.constructor;
}else{a0=null;
}if(a0&&a0!==Array&&a0!==aY&&a0!==aX&&a0!==aT&&a0!==aW){if(a2 instanceof Date){aU[aZ]=new Date(a2.getTime());
}else{if(R(a2.clone)){aU[aZ]=a2.clone();
}else{aV=aU[aZ];
if(typeof aV===ai){aU[aZ]=aV||{};
}else{aU[aZ]={};
}s(aU[aZ],a2);
}}}else{if(a1!==aM){aU[aZ]=a2;
}}}return aU;
}function aH(aT,aW,aU){for(var aV in aW){if(aW.hasOwnProperty(aV)&&aW[aV].test(aT)){return aV;
}}return aU!==aL?aU:aT;
}function aK(aT){return aT.replace(/([a-z][A-Z])/g,function(aU){return aU.charAt(0)+"-"+aU.charAt(1).toLowerCase();
});
}function aI(aT){return aT.replace(/\-(\w)/g,function(aV,aU){return aU.toUpperCase();
});
}function I(aU,aV){var aW={},aT;
if(document.defaultView&&document.defaultView.getComputedStyle){aT=document.defaultView.getComputedStyle(aU,"");
if(aV){b.each(aV,function(aX,aY){aW[aY]=aT.getPropertyValue(aY);
});
}}else{aT=aU.currentStyle;
if(aV){b.each(aV,function(aX,aY){aW[aY]=aT[aI(aY)];
});
}}if(!W.size(aW)){aW=aT;
}return aW;
}function S(aT){if(aT&&aT.className&&typeof aT.className==="string"&&aT.className.indexOf("k-auto-scrollable")>-1){return true;
}var aU=I(aT,["overflow"]).overflow;
return aU=="auto"||aU=="scroll";
}function ay(aU,aX){var aY=aE.browser.webkit;
var aW=aE.browser.mozilla;
var aT=aU instanceof b?aU[0]:aU;
var aV;
if(!aU){return;
}aV=aE.isRtl(aU);
if(aX!==aL){if(aV&&aY){aT.scrollLeft=aT.scrollWidth-aT.clientWidth-aX;
}else{if(aV&&aW){aT.scrollLeft=-aX;
}else{aT.scrollLeft=aX;
}}}else{if(aV&&aY){return aT.scrollWidth-aT.clientWidth-aT.scrollLeft;
}else{return Math.abs(aT.scrollLeft);
}}}(function(){aE._scrollbar=aL;
aE.scrollbar=function(a2){if(!isNaN(aE._scrollbar)&&!a2){return aE._scrollbar;
}else{var a1=document.createElement("div"),a3;
a1.style.cssText="overflow:scroll;overflow-x:hidden;zoom:1;clear:both;display:block";
a1.innerHTML="&nbsp;";
document.body.appendChild(a1);
aE._scrollbar=a3=a1.offsetWidth-a1.scrollWidth;
document.body.removeChild(a1);
return a3;
}};
aE.isRtl=function(a1){return b(a1).closest(".k-rtl").length>0;
};
var aY=document.createElement("table");
try{aY.innerHTML="<tr><td></td></tr>";
aE.tbodyInnerHtml=true;
}catch(aU){aE.tbodyInnerHtml=false;
}aE.touch="ontouchstart" in aP;
aE.msPointers=aP.MSPointerEvent;
aE.pointers=aP.PointerEvent;
var a0=aE.transitions=false,aZ=aE.transforms=false,aV="HTMLElement" in aP?HTMLElement.prototype:[];
aE.hasHW3D="WebKitCSSMatrix" in aP&&"m11" in new aP.WebKitCSSMatrix()||"MozPerspective" in document.documentElement.style||"msPerspective" in document.documentElement.style;
u(["Moz","webkit","O","ms"],function(){var a3=this.toString(),a1=typeof aY.style[a3+"Transition"]===aD;
if(a1||typeof aY.style[a3+"Transform"]===aD){var a2=a3.toLowerCase();
aZ={css:a2!="ms"?"-"+a2+"-":"",prefix:a3,event:a2==="o"||a2==="webkit"?a2:""};
if(a1){a0=aZ;
a0.event=a0.event?a0.event+"TransitionEnd":"transitionend";
}return false;
}});
aY=null;
aE.transforms=aZ;
aE.transitions=a0;
aE.devicePixelRatio=aP.devicePixelRatio===aL?1:aP.devicePixelRatio;
try{aE.screenWidth=aP.outerWidth||aP.screen?aP.screen.availWidth:aP.innerWidth;
aE.screenHeight=aP.outerHeight||aP.screen?aP.screen.availHeight:aP.innerHeight;
}catch(aU){aE.screenWidth=aP.screen.availWidth;
aE.screenHeight=aP.screen.availHeight;
}aE.detectOS=function(ba){var a8=false,a6,a5=[],a7=!/mobile safari/i.test(ba),a2={wp:/(Windows Phone(?: OS)?)\s(\d+)\.(\d+(\.\d+)?)/,fire:/(Silk)\/(\d+)\.(\d+(\.\d+)?)/,android:/(Android|Android.*(?:Opera|Firefox).*?\/)\s*(\d+)\.(\d+(\.\d+)?)/,iphone:/(iPhone|iPod).*OS\s+(\d+)[\._]([\d\._]+)/,ipad:/(iPad).*OS\s+(\d+)[\._]([\d_]+)/,meego:/(MeeGo).+NokiaBrowser\/(\d+)\.([\d\._]+)/,webos:/(webOS)\/(\d+)\.(\d+(\.\d+)?)/,blackberry:/(BlackBerry|BB10).*?Version\/(\d+)\.(\d+(\.\d+)?)/,playbook:/(PlayBook).*?Tablet\s*OS\s*(\d+)\.(\d+(\.\d+)?)/,windows:/(MSIE)\s+(\d+)\.(\d+(\.\d+)?)/,tizen:/(tizen).*?Version\/(\d+)\.(\d+(\.\d+)?)/i,sailfish:/(sailfish).*rv:(\d+)\.(\d+(\.\d+)?).*firefox/i,ffos:/(Mobile).*rv:(\d+)\.(\d+(\.\d+)?).*Firefox/},a9={ios:/^i(phone|pad|pod)$/i,android:/^android|fire$/i,blackberry:/^blackberry|playbook/i,windows:/windows/,wp:/wp/,flat:/sailfish|ffos|tizen/i,meego:/meego/},a4={tablet:/playbook|ipad|fire/i},a3={omini:/Opera\sMini/i,omobile:/Opera\sMobi/i,firefox:/Firefox|Fennec/i,mobilesafari:/version\/.*safari/i,ie:/MSIE|Windows\sPhone/i,chrome:/chrome|crios/i,webkit:/webkit/i};
for(var a1 in a2){if(a2.hasOwnProperty(a1)){a5=ba.match(a2[a1]);
if(a5){if(a1=="windows"&&"plugins" in navigator){return false;
}a8={};
a8.device=a1;
a8.tablet=aH(a1,a4,false);
a8.browser=aH(ba,a3,"default");
a8.name=aH(a1,a9);
a8[a8.name]=true;
a8.majorVersion=a5[2];
a8.minorVersion=a5[3].replace("_",".");
a6=a8.minorVersion.replace(".","").substr(0,2);
a8.flatVersion=a8.majorVersion+a6+new Array(3-(a6.length<3?a6.length:2)).join("0");
a8.cordova=typeof aP.PhoneGap!==aM||typeof aP.cordova!==aM;
a8.appMode=aP.navigator.standalone||/file|local|wmapp/.test(aP.location.protocol)||a8.cordova;
if(a8.android&&(aE.devicePixelRatio<1.5&&a8.flatVersion<400||a7)&&(aE.screenWidth>800||aE.screenHeight>800)){a8.tablet=a1;
}break;
}}}return a8;
};
var aX=aE.mobileOS=aE.detectOS(navigator.userAgent);
aE.wpDevicePixelRatio=aX.wp?screen.width/320:0;
aE.kineticScrollNeeded=aX&&(aE.touch||aE.msPointers||aE.pointers);
aE.hasNativeScrolling=false;
if(aX.ios||aX.android&&aX.majorVersion>2||aX.wp){aE.hasNativeScrolling=aX;
}aE.delayedClick=function(){if(aE.touch){if(aX.ios){return true;
}if(aX.android){if(!aE.browser.chrome){return true;
}if(aE.browser.version<32){return false;
}return !(b("meta[name=viewport]").attr("content")||"").match(/user-scalable=no/i);
}}return false;
};
aE.mouseAndTouchPresent=aE.touch&&!(aE.mobileOS.ios||aE.mobileOS.android);
aE.detectBrowser=function(a5){var a2=false,a4=[],a3={edge:/(edge)[ \/]([\w.]+)/i,webkit:/(chrome)[ \/]([\w.]+)/i,safari:/(webkit)[ \/]([\w.]+)/i,opera:/(opera)(?:.*version|)[ \/]([\w.]+)/i,msie:/(msie\s|trident.*? rv:)([\w.]+)/i,mozilla:/(mozilla)(?:.*? rv:([\w.]+)|)/i};
for(var a1 in a3){if(a3.hasOwnProperty(a1)){a4=a5.match(a3[a1]);
if(a4){a2={};
a2[a1]=true;
a2[a4[1].toLowerCase().split(" ")[0].split("/")[0]]=true;
a2.version=parseInt(document.documentMode||a4[2],10);
break;
}}}return a2;
};
aE.browser=aE.detectBrowser(navigator.userAgent);
aE.detectClipboardAccess=function(){var a1={copy:document.queryCommandSupported?document.queryCommandSupported("copy"):false,cut:document.queryCommandSupported?document.queryCommandSupported("cut"):false,paste:document.queryCommandSupported?document.queryCommandSupported("paste"):false};
if(aE.browser.chrome){a1.paste=false;
if(aE.browser.version>=43){a1.copy=true;
a1.cut=true;
}}return a1;
};
aE.clipboard=aE.detectClipboardAccess();
aE.zoomLevel=function(){try{var a1=aE.browser;
var a4=0;
var a2=document.documentElement;
if(a1.msie&&a1.version==11&&a2.scrollHeight>a2.clientHeight&&!aE.touch){a4=aE.scrollbar();
}return aE.touch?a2.clientWidth/aP.innerWidth:a1.msie&&a1.version>=10?((top||aP).document.documentElement.offsetWidth+a4)/(top||aP).innerWidth:1;
}catch(a3){return 1;
}};
aE.cssBorderSpacing=typeof document.documentElement.style.borderSpacing!="undefined"&&!(aE.browser.msie&&aE.browser.version<8);
(function(a1){var a2="",a3=b(document.documentElement),a4=parseInt(a1.version,10);
if(a1.msie){a2="ie";
}else{if(a1.mozilla){a2="ff";
}else{if(a1.safari){a2="safari";
}else{if(a1.webkit){a2="webkit";
}else{if(a1.opera){a2="opera";
}else{if(a1.edge){a2="edge";
}}}}}}if(a2){a2="k-"+a2+" k-"+a2+a4;
}if(aE.mobileOS){a2+=" k-mobile";
}a3.addClass(a2);
}(aE.browser));
aE.eventCapture=document.documentElement.addEventListener;
var aW=document.createElement("input");
aE.placeholder="placeholder" in aW;
aE.propertyChangeEvent="onpropertychange" in aW;
aE.input=function(){var a5=["number","date","time","month","week","datetime","datetime-local"];
var a2=a5.length;
var a6="test";
var a3={};
var a1=0;
var a4;
for(;
a1<a2;
a1++){a4=a5[a1];
aW.setAttribute("type",a4);
aW.value=a6;
a3[a4.replace("-","")]=aW.type!=="text"&&aW.value!==a6;
}return a3;
}();
aW.style.cssText="float:left;";
aE.cssFloat=!!aW.style.cssFloat;
aW=null;
aE.stableSort=function(){var a3=513;
var a2=[{index:0,field:"b"}];
for(var a1=1;
a1<a3;
a1++){a2.push({index:a1,field:"a"});
}a2.sort(function(a4,a5){return a4.field>a5.field?1:a4.field<a5.field?-1:0;
});
return a2[0].index===1;
}();
aE.matchesSelector=aV.webkitMatchesSelector||aV.mozMatchesSelector||aV.msMatchesSelector||aV.oMatchesSelector||aV.matchesSelector||aV.matches||function(a3){var a2=document.querySelectorAll?(this.parentNode||document).querySelectorAll(a3)||[]:b(a3),a1=a2.length;
while(a1--){if(a2[a1]==this){return true;
}}return false;
};
aE.pushState=aP.history&&aP.history.pushState;
var aT=document.documentMode;
aE.hashChange="onhashchange" in aP&&!(aE.browser.msie&&(!aT||aT<=8));
aE.customElements="registerElement" in aP.document;
}());
function aB(aU){var aV=0,aT;
for(aT in aU){if(aU.hasOwnProperty(aT)&&aT!="toJSON"){aV++;
}}return aV;
}function K(aT,aX,aU){if(!aX){aX="offset";
}var aV=aT[aX]();
if(aE.mobileOS.android){aV.top-=aP.scrollY;
aV.left-=aP.scrollX;
}if(aE.browser.msie&&(aE.pointers||aE.msPointers)&&!aU){var aW=aE.isRtl(aT)?1:-1;
aV.top-=aP.pageYOffset+aW*document.documentElement.scrollTop;
aV.left-=aP.pageXOffset+aW*document.documentElement.scrollLeft;
}return aV;
}var t={left:{reverse:"right"},right:{reverse:"left"},down:{reverse:"up"},up:{reverse:"down"},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out"},out:{reverse:"in"}};
function am(aU){var aT={};
u(typeof aU==="string"?aU.split(" "):aU,function(aV){aT[aV]=this;
});
return aT;
}function H(aT){return new W.effects.Element(aT);
}var v={};
b.extend(v,{enabled:true,Element:function(aT){this.element=b(aT);
},promise:function(aT,aU){if(!aT.is(":visible")){aT.css({display:aT.data("olddisplay")||"block"}).css("display");
}if(aU.hide){aT.data("olddisplay",aT.css("display")).hide();
}if(aU.init){aU.init();
}if(aU.completeCallback){aU.completeCallback(aT);
}aT.dequeue();
},disable:function(){this.enabled=false;
this.promise=this.promiseShim;
},enable:function(){this.enabled=true;
this.promise=this.animatedPromise;
}});
v.promiseShim=v.promise;
function aq(aV,aU,aW,aT){if(typeof aV===aD){if(R(aU)){aT=aU;
aU=400;
aW=false;
}if(R(aW)){aT=aW;
aW=false;
}if(typeof aU===i){aW=aU;
aU=400;
}aV={effects:aV,duration:aU,reverse:aW,complete:aT};
}return D({effects:{},duration:400,reverse:false,init:ae,teardown:ae,hide:false},aV,{completeCallback:aV.complete,complete:ae});
}function d(aV,aZ,aU,a0,aT){var aW=0,aY=aV.length,aX;
for(;
aW<aY;
aW++){aX=b(aV[aW]);
aX.queue(function(){v.promise(aX,aq(aZ,aU,a0,aT));
});
}return aV;
}function aJ(aV,aU,aW,aT){if(aU){aU=aU.split(" ");
u(aU,function(aX,aY){aV.toggleClass(aY,aT);
});
}return aV;
}if(!("kendoAnimate" in b.fn)){D(b.fn,{kendoStop:function(aT,aU){return this.stop(aT,aU);
},kendoAnimate:function(aV,aU,aW,aT){return d(this,aV,aU,aW,aT);
},kendoAddClass:function(aT,aU){return W.toggleClass(this,aT,aU,true);
},kendoRemoveClass:function(aT,aU){return W.toggleClass(this,aT,aU,false);
},kendoToggleClass:function(aT,aU,aV){return W.toggleClass(this,aT,aU,aV);
}});
}var c=/&/g,Z=/</g,av=/"/g,g=/'/g,N=/>/g;
function O(aT){return(""+aT).replace(c,"&amp;").replace(Z,"&lt;").replace(N,"&gt;").replace(av,"&quot;").replace(g,"&#39;");
}var B=function(aT){return aT.target;
};
if(aE.touch){B=function(aT){var aU="originalEvent" in aT?aT.originalEvent.changedTouches:"changedTouches" in aT?aT.changedTouches:null;
return aU?document.elementFromPoint(aU[0].clientX,aU[0].clientY):aT.target;
};
u(["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","tap"],function(aT,aU){b.fn[aU]=function(aV){return this.bind(aU,aV);
};
});
}if(aE.touch){if(!aE.mobileOS){aE.mousedown="mousedown touchstart";
aE.mouseup="mouseup touchend";
aE.mousemove="mousemove touchmove";
aE.mousecancel="mouseleave touchcancel";
aE.click="click";
aE.resize="resize";
}else{aE.mousedown="touchstart";
aE.mouseup="touchend";
aE.mousemove="touchmove";
aE.mousecancel="touchcancel";
aE.click="touchend";
aE.resize="orientationchange";
}}else{if(aE.pointers){aE.mousemove="pointermove";
aE.mousedown="pointerdown";
aE.mouseup="pointerup";
aE.mousecancel="pointercancel";
aE.click="pointerup";
aE.resize="orientationchange resize";
}else{if(aE.msPointers){aE.mousemove="MSPointerMove";
aE.mousedown="MSPointerDown";
aE.mouseup="MSPointerUp";
aE.mousecancel="MSPointerCancel";
aE.click="MSPointerUp";
aE.resize="orientationchange resize";
}else{aE.mousemove="mousemove";
aE.mousedown="mousedown";
aE.mouseup="mouseup";
aE.mousecancel="mouseleave";
aE.click="click";
aE.resize="resize";
}}}var aR=function(aY,aZ){var a0=aZ||"d",aV,aU,aW,aX,aT=1;
for(aU=0,aW=aY.length;
aU<aW;
aU++){aX=aY[aU];
if(aX!==""){aV=aX.indexOf("[");
if(aV!==0){if(aV==-1){aX="."+aX;
}else{aT++;
aX="."+aX.substring(0,aV)+" || {})"+aX.substring(aV);
}}aT++;
a0+=aX+(aU<aW-1?" || {})":")");
}}return new Array(aT).join("(")+a0;
},Y=/^([a-z]+:)?\/\//i;
D(W,{widgets:[],_widgetRegisteredCallbacks:[],ui:W.ui||{},fx:W.fx||H,effects:W.effects||v,mobile:W.mobile||{},data:W.data||{},dataviz:W.dataviz||{},drawing:W.drawing||{},spreadsheet:{messages:{}},keys:{INSERT:45,DELETE:46,BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F2:113,F10:121,F12:123,NUMPAD_PLUS:107,NUMPAD_MINUS:109,NUMPAD_DOT:110},support:W.support||aE,animate:W.animate||d,ns:"",attr:function(aT){return"data-"+W.ns+aT;
},getShadows:L,wrap:aQ,deepExtend:r,getComputedStyles:I,webComponents:W.webComponents||[],isScrollable:S,scrollLeft:ay,size:aB,toCamelCase:aI,toHyphens:aK,getOffset:W.getOffset||K,parseEffects:W.parseEffects||am,toggleClass:W.toggleClass||aJ,directions:W.directions||t,Observable:aj,Class:k,Template:aF,template:at(aF.compile,aF),render:at(aF.render,aF),stringify:at(T.stringify,T),eventTarget:B,htmlEncode:O,isLocalUrl:function(aT){return aT&&!Y.test(aT);
},expr:function(aT,aV,aU){aT=aT||"";
if(typeof aV==aD){aU=aV;
aV=false;
}aU=aU||"d";
if(aT&&aT.charAt(0)!=="["){aT="."+aT;
}if(aV){aT=aT.replace(/"([^.]*)\.([^"]*)"/g,'"$1_$DOT$_$2"');
aT=aT.replace(/'([^.]*)\.([^']*)'/g,"'$1_$DOT$_$2'");
aT=aR(aT.split("."),aU);
aT=aT.replace(/_\$DOT\$_/g,".");
}else{aT=aU+aT;
}return aT;
},getter:function(aT,aV){var aU=aT+aV;
return M[aU]=M[aU]||new Function("d","return "+W.expr(aT,aV));
},setter:function(aT){return az[aT]=az[aT]||new Function("d,value",W.expr(aT)+"=value");
},accessor:function(aT){return{get:W.getter(aT),set:W.setter(aT)};
},guid:function(){var aU="",aT,aV;
for(aT=0;
aT<32;
aT++){aV=aa.random()*16|0;
if(aT==8||aT==12||aT==16||aT==20){aU+="-";
}aU+=(aT==12?4:aT==16?aV&3|8:aV).toString(16);
}return aU;
},roleSelector:function(aT){return aT.replace(/(\S+)/g,"["+W.attr("role")+"=$1],").slice(0,-1);
},directiveSelector:function(aT){var aV=aT.split(" ");
if(aV){for(var aU=0;
aU<aV.length;
aU++){if(aV[aU]!="view"){aV[aU]=aV[aU].replace(/(\w*)(view|bar|strip|over)$/,"$1-$2");
}}}return aV.join(" ").replace(/(\S+)/g,"kendo-mobile-$1,").slice(0,-1);
},triggeredByInput:function(aT){return/^(label|input|textarea|select)$/i.test(aT.target.tagName);
},onWidgetRegistered:function(aT){for(var aU=0,aV=W.widgets.length;
aU<aV;
aU++){aT(W.widgets[aU]);
}W._widgetRegisteredCallbacks.push(aT);
},logToConsole:function(aU,aV){var aT=aP.console;
if(!W.suppressLog&&typeof aT!="undefined"&&aT.log){aT[aV||"log"](aU);
}}});
var aO=aj.extend({init:function(aU,aV){var aW=this;
aW.element=W.jQuery(aU).handler(aW);
aW.angular("init",aV);
aj.fn.init.call(aW);
var aT=aV?aV.dataSource:null;
if(aT){aV=D({},aV,{dataSource:{}});
}aV=aW.options=D(true,{},aW.options,aV);
if(aT){aV.dataSource=aT;
}if(!aW.element.attr(W.attr("role"))){aW.element.attr(W.attr("role"),(aV.name||"").toLowerCase());
}aW.element.data("kendo"+aV.prefix+aV.name,aW);
aW.bind(aW.events,aV);
},events:[],options:{prefix:""},_hasBindingTarget:function(){return !!this.element[0].kendoBindingTarget;
},_tabindex:function(aW){aW=aW||this.wrapper;
var aT=this.element,aV="tabindex",aU=aW.attr(aV)||aT.attr(aV);
aT.removeAttr(aV);
aW.attr(aV,!isNaN(aU)?aU:0);
},setOptions:function(aT){this._setEvents(aT);
b.extend(this.options,aT);
},_setEvents:function(aW){var aX=this,aU=0,aV=aX.events.length,aT;
for(;
aU<aV;
aU++){aT=aX.events[aU];
if(aX.options[aT]&&aW[aT]){aX.unbind(aT,aX.options[aT]);
}}aX.bind(aX.events,aW);
},resize:function(aU){var aV=this.getSize(),aT=this._size;
if(aU||(aV.width>0||aV.height>0)&&(!aT||aV.width!==aT.width||aV.height!==aT.height)){this._size=aV;
this._resize(aV,aU);
this.trigger("resize",aV);
}},getSize:function(){return W.dimensions(this.element);
},size:function(aT){if(!aT){return this.getSize();
}else{this.setSize(aT);
}},setSize:b.noop,_resize:b.noop,destroy:function(){var aT=this;
aT.element.removeData("kendo"+aT.options.prefix+aT.options.name);
aT.element.removeData("handler");
aT.unbind();
},_destroy:function(){this.destroy();
},angular:function(){},_muteAngularRebind:function(aT){this._muteRebind=true;
aT.call(this);
this._muteRebind=false;
}});
var q=aO.extend({dataItems:function(){return this.dataSource.flatView();
},_angularItems:function(aT){var aU=this;
aU.angular(aT,function(){return{elements:aU.items(),data:b.map(aU.dataItems(),function(aV){return{dataItem:aV};
})};
});
}});
W.dimensions=function(aV,aT){var aU=aV[0];
if(aT){aV.css(aT);
}return{width:aU.offsetWidth,height:aU.offsetHeight};
};
W.notify=ae;
var aG=/template$/i,V=/^\s*(?:\{(?:.|\r\n|\n)*\}|\[(?:.|\r\n|\n)*\])\s*$/,U=/^\{(\d+)(:[^\}]+)?\}|^\[[A-Za-z_]*\]$/,p=/([A-Z])/g;
function an(aT,aU){var aV;
if(aU.indexOf("data")===0){aU=aU.substring(4);
aU=aU.charAt(0).toLowerCase()+aU.substring(1);
}aU=aU.replace(p,"-$1");
aV=aT.getAttribute("data-"+W.ns+aU);
if(aV===null){aV=aL;
}else{if(aV==="null"){aV=null;
}else{if(aV==="true"){aV=true;
}else{if(aV==="false"){aV=false;
}else{if(ah.test(aV)){aV=parseFloat(aV);
}else{if(V.test(aV)&&!U.test(aV)){aV=new Function("return ("+aV+")")();
}}}}}}return aV;
}function ao(aT,aV){var aW={},aU,aX;
for(aU in aV){aX=an(aT,aU);
if(aX!==aL){if(aG.test(aU)){aX=W.template(b("#"+aX).html());
}aW[aU]=aX;
}}return aW;
}W.initWidget=function(aV,a1,a4){var a2,a0,a6,aX,aZ,a3,a5,aU,aW,a8;
if(!a4){a4=W.ui.roles;
}else{if(a4.roles){a4=a4.roles;
}}aV=aV.nodeType?aV:aV[0];
a3=aV.getAttribute("data-"+W.ns+"role");
if(!a3){return;
}aW=a3.indexOf(".")===-1;
if(aW){a6=a4[a3];
}else{a6=W.getter(a3)(aP);
}var aT=b(aV).data(),a7=a6?"kendo"+a6.fn.options.prefix+a6.fn.options.name:"";
if(aW){a8=new RegExp("^kendo.*"+a3+"$","i");
}else{a8=new RegExp("^"+a7+"$","i");
}for(var aY in aT){if(aY.match(a8)){if(aY===a7){a2=aT[aY];
}else{return aT[aY];
}}}if(!a6){return;
}aU=an(aV,"dataSource");
a1=b.extend({},ao(aV,a6.fn.options),a1);
if(aU){if(typeof aU===aD){a1.dataSource=W.getter(aU)(aP);
}else{a1.dataSource=aU;
}}for(aX=0,aZ=a6.fn.events.length;
aX<aZ;
aX++){a0=a6.fn.events[aX];
a5=an(aV,a0);
if(a5!==aL){a1[a0]=W.getter(a5)(aP);
}}if(!a2){a2=new a6(aV,a1);
}else{if(!b.isEmptyObject(a1)){a2.setOptions(a1);
}}return a2;
};
W.rolesFromNamespaces=function(aV){var aW=[],aT,aU;
if(!aV[0]){aV=[W.ui,W.dataviz.ui];
}for(aT=0,aU=aV.length;
aT<aU;
aT++){aW[aT]=aV[aT].roles;
}return D.apply(null,[{}].concat(aW.reverse()));
};
W.init=function(aT){var aU=W.rolesFromNamespaces(aC.call(arguments,1));
b(aT).find("[data-"+W.ns+"role]").addBack().each(function(){W.initWidget(this,{},aU);
});
};
W.destroy=function(aT){b(aT).find("[data-"+W.ns+"role]").addBack().each(function(){var aU=b(this).data();
for(var aV in aU){if(aV.indexOf("kendo")===0&&typeof aU[aV].destroy===G){aU[aV].destroy();
}}});
};
function n(aT,aU){return b.contains(aT,aU)?-1:1;
}function aw(){var aT=b(this);
return b.inArray(aT.attr("data-"+W.ns+"role"),["slider","rangeslider"])>-1||aT.is(":visible");
}W.resize=function(aT,aU){var aV=b(aT).find("[data-"+W.ns+"role]").addBack().filter(aw);
if(!aV.length){return;
}var aW=b.makeArray(aV);
aW.sort(n);
b.each(aW,function(){var aX=W.widgetInstance(b(this));
if(aX){aX.resize(aU);
}});
};
W.parseOptions=ao;
D(W.ui,{Widget:aO,DataBoundWidget:q,roles:{},progress:function(aU,a0){var aY=aU.find(".k-loading-mask"),aZ=W.support,aT=aZ.browser,aW,aX,a1,aV;
if(a0){if(!aY.length){aW=aZ.isRtl(aU);
aX=aW?"right":"left";
aV=aU.scrollLeft();
a1=aT.webkit?!aW?0:aU[0].scrollWidth-aU.width()-2*aV:0;
aY=b("<div class='k-loading-mask'><span class='k-loading-text'>"+W.ui.progress.messages.loading+"</span><div class='k-loading-image'/><div class='k-loading-color'/></div>").width("100%").height("100%").css("top",aU.scrollTop()).css(aX,Math.abs(aV)+a1).prependTo(aU);
}}else{if(aY){aY.remove();
}}},plugin:function(aZ,aY,aX){var aW=aZ.fn.options.name,aT;
aY=aY||W.ui;
aX=aX||"";
aY[aW]=aZ;
aY.roles[aW.toLowerCase()]=aZ;
aT="getKendo"+aX+aW;
aW="kendo"+aX+aW;
var a0={name:aW,widget:aZ,prefix:aX||""};
W.widgets.push(a0);
for(var aU=0,aV=W._widgetRegisteredCallbacks.length;
aU<aV;
aU++){W._widgetRegisteredCallbacks[aU](a0);
}b.fn[aW]=function(a2){var a3=this,a1;
if(typeof a2===aD){a1=aC.call(arguments,1);
this.each(function(){var a6=b.data(this,aW),a4,a5;
if(!a6){throw new Error(W.format("Cannot call method '{0}' of {1} before it is initialized",a2,aW));
}a4=a6[a2];
if(typeof a4!==G){throw new Error(W.format("Cannot find method '{0}' of {1}",a2,aW));
}a5=a4.apply(a6,a1);
if(a5!==aL){a3=a5;
return false;
}});
}else{this.each(function(){return new aZ(this,a2);
});
}return a3;
};
b.fn[aW].widget=aZ;
b.fn[aT]=function(){return this.data(aW);
};
}});
W.ui.progress.messages={loading:"Loading..."};
var m={bind:function(){return this;
},nullObject:true,options:{}};
var ab=aO.extend({init:function(aT,aU){aO.fn.init.call(this,aT,aU);
this.element.autoApplyNS();
this.wrapper=this.element;
this.element.addClass("km-widget");
},destroy:function(){aO.fn.destroy.call(this);
this.element.kendoDestroy();
},options:{prefix:"Mobile"},events:[],view:function(){var aT=this.element.closest(W.roleSelector("view splitview modalview drawer"));
return W.widgetInstance(aT,W.mobile.ui)||m;
},viewHasNativeScrolling:function(){var aT=this.view();
return aT&&aT.options.useNativeScrolling;
},container:function(){var aT=this.element.closest(W.roleSelector("view layout modalview drawer splitview"));
return W.widgetInstance(aT.eq(0),W.mobile.ui)||m;
}});
D(W.mobile,{init:function(aT){W.init(aT,W.mobile.ui,W.ui,W.dataviz.ui);
},appLevelNativeScrolling:function(){return W.mobile.application&&W.mobile.application.options&&W.mobile.application.options.useNativeScrolling;
},roles:{},ui:{Widget:ab,DataBoundWidget:q.extend(ab.prototype),roles:{},plugin:function(aT){W.ui.plugin(aT,W.mobile.ui,"Mobile");
}}});
r(W.dataviz,{init:function(aT){W.init(aT,W.dataviz.ui);
},ui:{roles:{},themes:{},views:[],plugin:function(aT){W.ui.plugin(aT,W.dataviz.ui);
}},roles:{}});
W.touchScroller=function(aT,aU){if(!aU){aU={};
}aU.useNative=true;
return b(aT).map(function(aW,aV){aV=b(aV);
if(aE.kineticScrollNeeded&&W.mobile.ui.Scroller&&!aV.data("kendoMobileScroller")){aV.kendoMobileScroller(aU);
return aV.data("kendoMobileScroller");
}else{return false;
}})[0];
};
W.preventDefault=function(aT){aT.preventDefault();
};
W.widgetInstance=function(aT,aY){var aX=aT.data(W.ns+"role"),a0=[],aU,aW;
if(aX){if(aX==="content"){aX="scroller";
}if(aY){if(aY[0]){for(aU=0,aW=aY.length;
aU<aW;
aU++){a0.push(aY[aU].roles[aX]);
}}else{a0.push(aY.roles[aX]);
}}else{a0=[W.ui.roles[aX],W.dataviz.ui.roles[aX],W.mobile.ui.roles[aX]];
}if(aX.indexOf(".")>=0){a0=[W.getter(aX)(aP)];
}for(aU=0,aW=a0.length;
aU<aW;
aU++){var aZ=a0[aU];
if(aZ){var aV=aT.data("kendo"+aZ.fn.options.prefix+aZ.fn.options.name);
if(aV){return aV;
}}}}};
W.onResize=function(aT){var aU=aT;
if(aE.mobileOS.android){aU=function(){setTimeout(aT,600);
};
}b(aP).on(aE.resize,aU);
return aU;
};
W.unbindResize=function(aT){b(aP).off(aE.resize,aT);
};
W.attrValue=function(aT,aU){return aT.data(W.ns+aU);
};
W.days={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function E(aT,aU){var aV=aT.nodeName.toLowerCase();
return(/input|select|textarea|button|object/.test(aV)?!aT.disabled:"a"===aV?aT.href||aU:aU)&&aN(aT);
}function aN(aT){return b.expr.filters.visible(aT)&&!b(aT).parents().addBack().filter(function(){return b.css(this,"visibility")==="hidden";
}).length;
}b.extend(b.expr[":"],{kendoFocusable:function(aT){var aU=b.attr(aT,"tabindex");
return E(aT,!isNaN(aU)&&aU>-1);
}});
var ac=["mousedown","mousemove","mouseenter","mouseleave","mouseover","mouseout","mouseup","click"];
var C="label, input, [data-rel=external]";
var ad={setupMouseMute:function(){var aV=0,aW=ac.length,aT=document.documentElement;
if(ad.mouseTrap||!aE.eventCapture){return;
}ad.mouseTrap=true;
ad.bustClick=false;
ad.captureMouse=false;
var aU=function(aX){if(ad.captureMouse){if(aX.type==="click"){if(ad.bustClick&&!b(aX.target).is(C)){aX.preventDefault();
aX.stopPropagation();
}}else{aX.stopPropagation();
}}};
for(;
aV<aW;
aV++){aT.addEventListener(ac[aV],aU,true);
}},muteMouse:function(aT){ad.captureMouse=true;
if(aT.data.bustClick){ad.bustClick=true;
}clearTimeout(ad.mouseTrapTimeoutID);
},unMuteMouse:function(){clearTimeout(ad.mouseTrapTimeoutID);
ad.mouseTrapTimeoutID=setTimeout(function(){ad.captureMouse=false;
ad.bustClick=false;
},400);
}};
var z={down:"touchstart mousedown",move:"mousemove touchmove",up:"mouseup touchend touchcancel",cancel:"mouseleave touchcancel"};
if(aE.touch&&(aE.mobileOS.ios||aE.mobileOS.android)){z={down:"touchstart",move:"touchmove",up:"touchend touchcancel",cancel:"touchcancel"};
}else{if(aE.pointers){z={down:"pointerdown",move:"pointermove",up:"pointerup",cancel:"pointercancel pointerleave"};
}else{if(aE.msPointers){z={down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp",cancel:"MSPointerCancel MSPointerLeave"};
}}}if(aE.msPointers&&!("onmspointerenter" in aP)){b.each({MSPointerEnter:"MSPointerOver",MSPointerLeave:"MSPointerOut"},function(aU,aT){b.event.special[aU]={delegateType:aT,bindType:aT,handle:function(aV){var aY,aZ=this,aX=aV.relatedTarget,aW=aV.handleObj;
if(!aX||aX!==aZ&&!b.contains(aZ,aX)){aV.type=aW.origType;
aY=aW.handler.apply(this,arguments);
aV.type=aT;
}return aY;
}};
});
}var J=function(aT){return z[aT]||aT;
},A=/([^ ]+)/g;
W.applyEventMap=function(aT,aU){aT=aT.replace(A,J);
if(aU){aT=aT.replace(A,"$1."+aU);
}return aT;
};
var ak=b.fn.on;
function X(aU,aT){return new X.fn.init(aU,aT);
}D(true,X,b);
X.fn=X.prototype=new b();
X.fn.constructor=X;
X.fn.init=function(aU,aT){if(aT&&aT instanceof b&&!(aT instanceof X)){aT=X(aT);
}return b.fn.init.call(this,aU,aT,ax);
};
X.fn.init.prototype=X.fn;
var ax=X(document);
D(X.fn,{handler:function(aT){this.data("handler",aT);
return this;
},autoApplyNS:function(aT){this.data("kendoNS",aT||W.guid());
return this;
},on:function(){var a0=this,aY=a0.data("kendoNS");
if(arguments.length===1){return ak.call(a0,arguments[0]);
}var aW=a0,aT=aC.call(arguments);
if(typeof aT[aT.length-1]===aM){aT.pop();
}var aV=aT[aT.length-1],aX=W.applyEventMap(aT[0],aY);
if(aE.mouseAndTouchPresent&&aX.search(/mouse|click/)>-1&&this[0]!==document.documentElement){ad.setupMouseMute();
var aZ=aT.length===2?null:aT[1],aU=aX.indexOf("click")>-1&&aX.indexOf("touchend")>-1;
ak.call(this,{touchstart:ad.muteMouse,touchend:ad.unMuteMouse},aZ,{bustClick:aU});
}if(typeof aV===aD){aW=a0.data("handler");
aV=aW[aV];
aT[aT.length-1]=function(a1){aV.call(aW,a1);
};
}aT[0]=aX;
ak.apply(a0,aT);
return a0;
},kendoDestroy:function(aT){aT=aT||this.data("kendoNS");
if(aT){this.off("."+aT);
}return this;
}});
W.jQuery=X;
W.eventMap=z;
W.timezone=function(){var aZ={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
var aW={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function a2(bd,ba){var a6;
var bb;
var a9;
var a7=ba[3];
var a8=ba[4];
var bc=ba[5];
var a5=ba[8];
if(!a5){ba[8]=a5={};
}if(a5[bd]){return a5[bd];
}if(!isNaN(a8)){a6=new Date(Date.UTC(bd,aZ[a7],a8,bc[0],bc[1],bc[2],0));
}else{if(a8.indexOf("last")===0){a6=new Date(Date.UTC(bd,aZ[a7]+1,1,bc[0]-24,bc[1],bc[2],0));
bb=aW[a8.substr(4,3)];
a9=a6.getUTCDay();
a6.setUTCDate(a6.getUTCDate()+bb-a9-(bb>a9?7:0));
}else{if(a8.indexOf(">=")>=0){a6=new Date(Date.UTC(bd,aZ[a7],a8.substr(5),bc[0],bc[1],bc[2],0));
bb=aW[a8.substr(0,3)];
a9=a6.getUTCDay();
a6.setUTCDate(a6.getUTCDate()+bb-a9+(bb<a9?7:0));
}}}return a5[bd]=a6;
}function aX(a9,a7,bb){a7=a7[bb];
if(!a7){var a8=bb.split(":");
var a5=0;
if(a8.length>1){a5=a8[0]*60+Number(a8[1]);
}return[-1000000,"max","-","Jan",1,[0,0,0],a5,"-"];
}var ba=new Date(a9).getUTCFullYear();
a7=jQuery.grep(a7,function(bd){var bc=bd[0];
var be=bd[1];
return bc<=ba&&(be>=ba||bc==ba&&be=="only"||be=="max");
});
a7.push(a9);
a7.sort(function(bc,bd){if(typeof bc!="number"){bc=Number(a2(ba,bc));
}if(typeof bd!="number"){bd=Number(a2(ba,bd));
}return bc-bd;
});
var a6=a7[jQuery.inArray(a9,a7)-1]||a7[a7.length-1];
return isNaN(a6)?a6:null;
}function aY(a8,bb,a6){var ba=bb[a6];
if(typeof ba==="string"){ba=bb[ba];
}if(!ba){throw new Error('Timezone "'+a6+'" is either incorrect, or kendo.timezones.min.js is not included.');
}for(var a5=ba.length-1;
a5>=0;
a5--){var a7=ba[a5][3];
if(a7&&a8>a7){break;
}}var a9=ba[a5+1];
if(!a9){throw new Error('Timezone "'+a6+'" not found on '+a8+".");
}return a9;
}function a4(a7,a9,a5,a6){if(typeof a7!=ag){a7=Date.UTC(a7.getFullYear(),a7.getMonth(),a7.getDate(),a7.getHours(),a7.getMinutes(),a7.getSeconds(),a7.getMilliseconds());
}var a8=aY(a7,a9,a6);
return{zone:a8,rule:aX(a7,a5,a8[1])};
}function a0(a8,a7){if(a7=="Etc/UTC"||a7=="Etc/GMT"){return 0;
}var a5=a4(a8,this.zones,this.rules,a7);
var a9=a5.zone;
var a6=a5.rule;
return W.parseFloat(a6?a9[0]-a6[6]:a9[0]);
}function aT(a9,a8){var a6=a4(a9,this.zones,this.rules,a8);
var ba=a6.zone;
var a7=a6.rule;
var a5=ba[2];
if(a5.indexOf("/")>=0){return a5.split("/")[a7&&+a7[6]?1:0];
}else{if(a5.indexOf("%s")>=0){return a5.replace("%s",!a7||a7[7]=="-"?"":a7[7]);
}}return a5;
}function aV(a5,a7,a9){if(typeof a7==aD){a7=this.offset(a5,a7);
}if(typeof a9==aD){a9=this.offset(a5,a9);
}var a6=a5.getTimezoneOffset();
a5=new Date(a5.getTime()+(a7-a9)*60000);
var a8=a5.getTimezoneOffset();
return new Date(a5.getTime()+(a8-a6)*60000);
}function aU(a5,a6){return this.convert(a5,a5.getTimezoneOffset(),a6);
}function a1(a5,a6){return this.convert(a5,a6,a5.getTimezoneOffset());
}function a3(a5){return this.apply(new Date(a5),"Etc/UTC");
}return{zones:{},rules:{},offset:a0,convert:aV,apply:aU,remove:a1,abbr:aT,toLocalDate:a3};
}();
W.date=function(){var a4=60000,a3=86400000;
function aU(bb,bc){if(bc===0&&bb.getHours()===23){bb.setHours(bb.getHours()+2);
return true;
}return false;
}function a5(bb,bc,bd){var be=bb.getHours();
bd=bd||1;
bc=(bc-bb.getDay()+7*bd)%7;
bb.setDate(bb.getDate()+bc);
aU(bb,be);
}function aV(bb,bc,bd){bb=new Date(bb);
a5(bb,bc,bd);
return bb;
}function aW(bb){return new Date(bb.getFullYear(),bb.getMonth(),1);
}function a2(bb){var bd=new Date(bb.getFullYear(),bb.getMonth()+1,0),bc=aW(bb),be=Math.abs(bd.getTimezoneOffset()-bc.getTimezoneOffset());
if(be){bd.setHours(bc.getHours()+be/60);
}return bd;
}function aX(bb){bb=new Date(bb.getFullYear(),bb.getMonth(),bb.getDate(),0,0,0);
aU(bb,0);
return bb;
}function ba(bb){return Date.UTC(bb.getFullYear(),bb.getMonth(),bb.getDate(),bb.getHours(),bb.getMinutes(),bb.getSeconds(),bb.getMilliseconds());
}function aY(bb){return bb.getTime()-aX(bb);
}function a0(bg,bc,bb){var be=aY(bc),bd=aY(bb),bf;
if(!bg||be==bd){return true;
}if(bc>=bb){bb+=a3;
}bf=aY(bg);
if(be>bf){bf+=a3;
}if(bd<be){bd+=a3;
}return bf>=be&&bf<=bd;
}function aZ(bg,bc,bb){var be=bc.getTime(),bd=bb.getTime(),bf;
if(be>=bd){bd+=a3;
}bf=bg.getTime();
return bf>=be&&bf<=bd;
}function aT(bb,bd){var bc=bb.getHours();
bb=new Date(bb);
a7(bb,bd*a3);
aU(bb,bc);
return bb;
}function a7(bb,be,bd){var bf=bb.getTimezoneOffset();
var bc;
bb.setTime(bb.getTime()+be);
if(!bd){bc=bb.getTimezoneOffset()-bf;
bb.setTime(bb.getTime()+bc*a4);
}}function a6(bb,bc){bb=new Date(W.date.getDate(bb).getTime()+W.date.getMilliseconds(bc));
aU(bb,bc.getHours());
return bb;
}function a8(){return aX(new Date());
}function a1(bb){return aX(bb).getTime()==a8().getTime();
}function a9(bb){var bc=new Date(1980,1,1,0,0,0);
if(bb){bc.setHours(bb.getHours(),bb.getMinutes(),bb.getSeconds(),bb.getMilliseconds());
}return bc;
}return{adjustDST:aU,dayOfWeek:aV,setDayOfWeek:a5,getDate:aX,isInDateRange:aZ,isInTimeRange:a0,isToday:a1,nextDay:function(bb){return aT(bb,1);
},previousDay:function(bb){return aT(bb,-1);
},toUtcTime:ba,MS_PER_DAY:a3,MS_PER_HOUR:60*a4,MS_PER_MINUTE:a4,setTime:a7,setHours:a6,addDays:aT,today:a8,toInvariantTime:a9,firstDayOfMonth:aW,lastDayOfMonth:a2,getMilliseconds:aY};
}();
W.stripWhitespace=function(aU){if(document.createNodeIterator){var aW=document.createNodeIterator(aU,NodeFilter.SHOW_TEXT,function(aX){return aX.parentNode==aU?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
},false);
while(aW.nextNode()){if(aW.referenceNode&&!aW.referenceNode.textContent.trim()){aW.referenceNode.parentNode.removeChild(aW.referenceNode);
}}}else{for(var aV=0;
aV<aU.childNodes.length;
aV++){var aT=aU.childNodes[aV];
if(aT.nodeType==3&&!/\S/.test(aT.nodeValue)){aU.removeChild(aT);
aV--;
}if(aT.nodeType==1){W.stripWhitespace(aT);
}}}};
var e=aP.requestAnimationFrame||aP.webkitRequestAnimationFrame||aP.mozRequestAnimationFrame||aP.oRequestAnimationFrame||aP.msRequestAnimationFrame||function(aT){setTimeout(aT,1000/60);
};
W.animationFrame=function(aT){e.call(aP,aT);
};
var f=[];
W.queueAnimation=function(aT){f[f.length]=aT;
if(f.length===1){W.runNextAnimation();
}};
W.runNextAnimation=function(){W.animationFrame(function(){if(f[0]){f.shift()();
if(f[0]){W.runNextAnimation();
}}});
};
W.parseQueryStringParams=function(aY){var aX=aY.split("?")[1]||"",aW={},aV=aX.split(/&|=/),aU=aV.length,aT=0;
for(;
aT<aU;
aT+=2){if(aV[aT]!==""){aW[decodeURIComponent(aV[aT])]=decodeURIComponent(aV[aT+1]);
}}return aW;
};
W.elementUnderCursor=function(aT){if(typeof aT.x.client!="undefined"){return document.elementFromPoint(aT.x.client,aT.y.client);
}};
W.wheelDeltaY=function(aW){var aV=aW.originalEvent,aU=aV.wheelDeltaY,aT;
if(aV.wheelDelta){if(aU===aL||aU){aT=aV.wheelDelta;
}}else{if(aV.detail&&aV.axis===aV.VERTICAL_AXIS){aT=-aV.detail*10;
}}return aT;
};
W.throttle=function(aU,aT){var aX;
var aV=0;
if(!aT||aT<=0){return aU;
}var aW=function(){var a1=this;
var aZ=+new Date()-aV;
var aY=arguments;
function a0(){aU.apply(a1,aY);
aV=+new Date();
}if(!aV){return a0();
}if(aX){clearTimeout(aX);
}if(aZ>aT){a0();
}else{aX=setTimeout(a0,aT-aZ);
}};
aW.cancel=function(){clearTimeout(aX);
};
return aW;
};
W.caret=function(aU,a1,aV){var aY;
var aW=a1!==aL;
if(aV===aL){aV=a1;
}if(aU[0]){aU=aU[0];
}if(aW&&aU.disabled){return;
}try{if(aU.selectionStart!==aL){if(aW){aU.focus();
aU.setSelectionRange(a1,aV);
}else{a1=[aU.selectionStart,aU.selectionEnd];
}}else{if(document.selection){if(b(aU).is(":visible")){aU.focus();
}aY=aU.createTextRange();
if(aW){aY.collapse(true);
aY.moveStart("character",a1);
aY.moveEnd("character",aV-a1);
aY.select();
}else{var aX=aY.duplicate(),a0,aZ;
aY.moveToBookmark(document.selection.createRange().getBookmark());
aX.setEndPoint("EndToStart",aY);
a0=aX.text.length;
aZ=a0+aY.text.length;
a1=[a0,aZ];
}}}}catch(aT){a1=[];
}return a1;
};
W.compileMobileDirective=function(aU,aV){var aT=aP.angular;
aU.attr("data-"+W.ns+"role",aU[0].tagName.toLowerCase().replace("kendo-mobile-","").replace("-",""));
aT.element(aU).injector().invoke(["$compile",function(aW){aW(aU)(aV);
if(!/^\$(digest|apply)$/.test(aV.$$phase)){aV.$digest();
}}]);
return W.widgetInstance(aU,W.mobile.ui);
};
W.antiForgeryTokens=function(){var aV={},aU=b("meta[name=csrf-token],meta[name=_csrf]").attr("content"),aT=b("meta[name=csrf-param],meta[name=_csrf_header]").attr("content");
b("input[name^='__RequestVerificationToken']").each(function(){aV[this.name]=this.value;
});
if(aT!==aL&&aU!==aL){aV[aT]=aU;
}return aV;
};
W.cycleForm=function(aV){var aT=aV.find("input, .k-widget").first();
var aW=aV.find("button, .k-button").last();
function aU(aX){var aY=W.widgetInstance(aX);
if(aY&&aY.focus){aY.focus();
}else{aX.focus();
}}aW.on("keydown",function(aX){if(aX.keyCode==W.keys.TAB&&!aX.shiftKey){aX.preventDefault();
aU(aT);
}});
aT.on("keydown",function(aX){if(aX.keyCode==W.keys.TAB&&aX.shiftKey){aX.preventDefault();
aU(aW);
}});
};
(function(){function aV(aZ,a0,a5,a4){var a1=b("<form>").attr({action:a5,method:"POST",target:a4});
var aY=W.antiForgeryTokens();
aY.fileName=a0;
var a3=aZ.split(";base64,");
aY.contentType=a3[0].replace("data:","");
aY.base64=a3[1];
for(var a2 in aY){if(aY.hasOwnProperty(a2)){b("<input>").attr({value:aY[a2],name:a2,type:"hidden"}).appendTo(a1);
}}a1.appendTo("body").submit().remove();
}var aU=document.createElement("a");
var aT="download" in aU&&!W.support.browser.edge;
function aW(a2,a3){var a0=a2;
if(typeof a2=="string"){var a5=a2.split(";base64,");
var a1=a5[0];
var aZ=atob(a5[1]);
var aY=new Uint8Array(aZ.length);
for(var a4=0;
a4<aZ.length;
a4++){aY[a4]=aZ.charCodeAt(a4);
}a0=new Blob([aY.buffer],{type:a1});
}navigator.msSaveBlob(a0,a3);
}function aX(aY,a0){if(aP.Blob&&aY instanceof Blob){aY=URL.createObjectURL(aY);
}aU.download=a0;
aU.href=aY;
var aZ=document.createEvent("MouseEvents");
aZ.initMouseEvent("click",true,false,aP,0,0,0,0,0,false,false,false,false,0,null);
aU.dispatchEvent(aZ);
setTimeout(function(){URL.revokeObjectURL(aY);
});
}W.saveAs=function(aY){var aZ=aV;
if(!aY.forceProxy){if(aT){aZ=aX;
}else{if(navigator.msSaveBlob){aZ=aW;
}}}aZ(aY.dataURI,aY.fileName,aY.proxyURL,aY.proxyTarget);
};
}());
W.proxyModelSetters=function au(aT){var aU={};
Object.keys(aT||{}).forEach(function(aV){Object.defineProperty(aU,aV,{get:function(){return aT[aV];
},set:function(aW){aT[aV]=aW;
aT.dirty=true;
}});
});
return aU;
};
}($telerik.$,window));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
