(function(b,a){a("kendo.dom",["kendo.core"],b);
}(function(){var a={id:"dom",name:"Virtual DOM",category:"framework",depends:["core"],advanced:true};
(function(h){function i(){this.node=null;
}i.prototype={remove:function(){this.node.parentNode.removeChild(this.node);
this.attr={};
},attr:{},text:function(){return"";
}};
function k(){}k.prototype={nodeName:"#null",attr:{style:{}},children:[],remove:function(){}};
var j=new k();
function c(q,o,p){this.nodeName=q;
this.attr=o||{};
this.children=p||[];
}c.prototype=new i();
c.prototype.appendTo=function(r){var q=document.createElement(this.nodeName);
var o=this.children;
for(var p=0;
p<o.length;
p++){o[p].render(q,j);
}r.appendChild(q);
return q;
};
c.prototype.render=function(v,o){var u;
if(o.nodeName!==this.nodeName){o.remove();
u=this.appendTo(v);
}else{u=o.node;
var s;
var r=this.children;
var t=r.length;
var p=o.children;
var q=p.length;
if(Math.abs(q-t)>2){this.render({appendChild:function(w){v.replaceChild(w,o.node);
}},j);
return;
}for(s=0;
s<t;
s++){r[s].render(u,p[s]||j);
}for(s=t;
s<q;
s++){p[s].remove();
}}this.node=u;
this.syncAttributes(o.attr);
this.removeAttributes(o.attr);
};
c.prototype.syncAttributes=function(p){var o=this.attr;
for(var r in o){var s=o[r];
var q=p[r];
if(r==="style"){this.setStyle(s,q);
}else{if(s!==q){this.setAttribute(r,s,q);
}}}};
c.prototype.setStyle=function(r,o){var q=this.node;
var p;
if(o){for(p in r){if(r[p]!==o[p]){q.style[p]=r[p];
}}}else{for(p in r){q.style[p]=r[p];
}}};
c.prototype.removeStyle=function(o){var r=this.attr.style||{};
var q=this.node;
for(var p in o){if(r[p]===undefined){q.style[p]="";
}}};
c.prototype.removeAttributes=function(p){var o=this.attr;
for(var q in p){if(q==="style"){this.removeStyle(p.style);
}else{if(o[q]===undefined){this.removeAttribute(q);
}}}};
c.prototype.removeAttribute=function(o){var p=this.node;
if(o==="style"){p.style.cssText="";
}else{if(o==="className"){p.className="";
}else{p.removeAttribute(o);
}}};
c.prototype.setAttribute=function(o,q){var p=this.node;
if(p[o]!==undefined){p[o]=q;
}else{p.setAttribute(o,q);
}};
c.prototype.text=function(){var p="";
for(var o=0;
o<this.children.length;
++o){p+=this.children[o].text();
}return p;
};
function m(o){this.nodeValue=o;
}m.prototype=new i();
m.prototype.nodeName="#text";
m.prototype.render=function(q,o){var p;
if(o.nodeName!==this.nodeName){o.remove();
p=document.createTextNode(this.nodeValue);
q.appendChild(p);
}else{p=o.node;
if(this.nodeValue!==o.nodeValue){p.nodeValue=this.nodeValue;
}}this.node=p;
};
m.prototype.text=function(){return this.nodeValue;
};
function f(o){this.html=o;
}f.prototype={nodeName:"#html",attr:{},remove:function(){for(var o=0;
o<this.nodes.length;
o++){this.nodes[o].parentNode.removeChild(this.nodes[o]);
}},render:function(r,o){if(o.nodeName!==this.nodeName||o.html!==this.html){o.remove();
var q=r.lastChild;
g(r,this.html);
this.nodes=[];
for(var p=q?q.nextSibling:r.firstChild;
p;
p=p.nextSibling){this.nodes.push(p);
}}else{this.nodes=o.nodes.slice(0);
}}};
var e=document.createElement("div");
function g(p,o){e.innerHTML=o;
while(e.firstChild){p.appendChild(e.firstChild);
}}function d(o){return new f(o);
}function b(q,o,p){return new c(q,o,p);
}function l(o){return new m(o);
}function n(o){this.root=o;
this.children=[];
}n.prototype={html:d,element:b,text:l,render:function(p){var o=this.children;
var q;
var r;
for(q=0,r=p.length;
q<r;
q++){p[q].render(this.root,o[q]||j);
}for(q=r;
q<o.length;
q++){o[q].remove();
}this.children=p;
}};
h.dom={html:d,text:l,element:b,Tree:n,Node:i};
}(window.kendo));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
