(function(b,a){a("kendo.dropdownlist",["kendo.list","kendo.mobile.scroller"],b);
}(function(){var a={id:"dropdownlist",name:"DropDownList",category:"web",description:"The DropDownList widget displays a list of values and allows the selection of a single value from the list.",depends:["list"],features:[{id:"mobile-scroller",name:"Mobile scroller",description:"Support for kinetic scrolling in mobile device",depends:["mobile.scroller"]},{id:"virtualization",name:"VirtualList",description:"Support for virtualization",depends:["virtuallist"]}]};
(function(b,C){var l=window.kendo,B=l.ui,n=B.List,v=B.Select,z=l.support,c=l._activeElement,r=l.data.ObservableObject,m=l.keys,q=".kendoDropDownList",h="disabled",t="readonly",f="change",j="k-state-focused",g="k-state-default",y="k-state-disabled",d="aria-disabled",k="mouseenter"+q+" mouseleave"+q,A="tabindex",x="filter",w="accept",o="The `optionLabel` option is not valid due to missing fields. Define a custom optionLabel as shown here http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#configuration-optionLabel",s=b.proxy;
var i=v.extend({init:function(E,H){var J=this;
var F=H&&H.index;
var G,I,D;
J.ns=q;
H=b.isArray(H)?{dataSource:H}:H;
v.fn.init.call(J,E,H);
H=J.options;
E=J.element.on("focus"+q,s(J._focusHandler,J));
J._focusInputHandler=b.proxy(J._focusInput,J);
J.optionLabel=b();
J._optionLabel();
J._inputTemplate();
J._reset();
J._prev="";
J._word="";
J._wrapper();
J._tabindex();
J.wrapper.data(A,J.wrapper.attr(A));
J._span();
J._popup();
J._mobile();
J._dataSource();
J._ignoreCase();
J._filterHeader();
J._aria();
J._enable();
J._oldIndex=J.selectedIndex=-1;
if(F!==C){H.index=F;
}J._initialIndex=H.index;
J.requireValueMapper(J.options);
J._initList();
J._cascade();
if(H.autoBind){J.dataSource.fetch();
}else{if(J.selectedIndex===-1){I=H.text||"";
if(!I){G=H.optionLabel;
if(G&&H.index===0){I=G;
}else{if(J._isSelect){I=E.children(":selected").text();
}}}J._textAccessor(I);
}}D=b(J.element).parents("fieldset").is(":disabled");
if(D){J.enable(false);
}J.listView.bind("click",function(K){K.preventDefault();
});
l.notify(J);
},options:{name:"DropDownList",enabled:true,autoBind:true,index:0,text:null,value:null,delay:500,height:200,dataTextField:"",dataValueField:"",optionLabel:"",cascadeFrom:"",cascadeFromField:"",ignoreCase:true,animation:{},filter:"none",minLength:1,enforceMinLength:false,virtual:false,template:null,valueTemplate:null,optionLabelTemplate:null,groupTemplate:"#:data#",fixedGroupTemplate:"#:data#"},events:["open","close",f,"select","filtering","dataBinding","dataBound","cascade","set"],setOptions:function(D){v.fn.setOptions.call(this,D);
this.listView.setOptions(this._listOptions(D));
this._optionLabel();
this._inputTemplate();
this._accessors();
this._filterHeader();
this._enable();
this._aria();
if(!this.value()&&this.hasOptionLabel()){this.select(0);
}},destroy:function(){var D=this;
v.fn.destroy.call(D);
D.wrapper.off(q);
D.element.off(q);
D._inputWrapper.off(q);
D._arrow.off();
D._arrow=null;
D.optionLabel.off();
},open:function(){var D=this;
if(D.popup.visible()){return;
}if(!D.listView.bound()||D._state===w){D._open=true;
D._state="rebind";
if(D.filterInput){D.filterInput.val("");
D._prev="";
}if(D.filterInput&&D.options.minLength!==1){D.refresh();
D.popup.one("activate",D._focusInputHandler);
D.popup.open();
if(D.filterInput){D._resizeFilterInput();
}}else{D._filterSource();
}}else{if(D._allowOpening()){D.popup.one("activate",D._focusInputHandler);
D.popup.open();
if(D.filterInput){D._resizeFilterInput();
}D._focusItem();
}}},_focusInput:function(){this._focusElement(this.filterInput);
},_resizeFilterInput:function(){this.filterInput.css("display","none");
this.filterInput.css("width",this.popup.element.css("width"));
this.filterInput.css("display","inline-block");
},_allowOpening:function(){return this.hasOptionLabel()||this.filterInput||v.fn._allowOpening.call(this);
},toggle:function(D){this._toggle(D,true);
},current:function(D){var E;
if(D===C){E=this.listView.focus();
if(!E&&this.selectedIndex===0&&this.hasOptionLabel()){return this.optionLabel;
}return E;
}this._focus(D);
},dataItem:function(E){var F=this;
var D=null;
if(E===null){return E;
}if(E===C){D=F.listView.selectedDataItems()[0];
}else{if(typeof E!=="number"){if(F.options.virtual){return F.dataSource.getByUid(b(E).data("uid"));
}if(E.hasClass("k-list-optionlabel")){E=-1;
}else{E=b(F.items()).index(E);
}}else{if(F.hasOptionLabel()){E-=1;
}}D=F.dataSource.flatView()[E];
}if(!D){D=F._optionLabelDataItem();
}return D;
},refresh:function(){this.listView.refresh();
},text:function(G){var H=this;
var D,F;
var E=H.options.ignoreCase;
G=G===null?"":G;
if(G!==C){if(typeof G==="string"){F=E?G.toLowerCase():G;
H._select(function(I){I=H._text(I);
if(E){I=(I+"").toLowerCase();
}return I===F;
});
D=H.dataItem();
if(D){G=D;
}}H._textAccessor(G);
}else{return H._textAccessor();
}},_clearFilter:function(){b(this.filterInput).val("");
v.fn._clearFilter.call(this);
},value:function(G){var F=this;
var E=F.listView;
var D=F.dataSource;
if(G===C){G=F._accessor()||F.listView.value()[0];
return G===C||G===null?"":G;
}F.requireValueMapper(F.options,G);
if(G||!F.hasOptionLabel()){F._initialIndex=null;
}this.trigger("set",{value:G});
if(F._request&&F.options.cascadeFrom&&F.listView.bound()){if(F._valueSetter){D.unbind(f,F._valueSetter);
}F._valueSetter=s(function(){F.value(G);
},F);
D.one(f,F._valueSetter);
return;
}if(F._isFilterEnabled()&&E.bound()&&E.isFiltered()){F._clearFilter();
}else{F._fetchData();
}E.value(G).done(function(){if(F.selectedIndex===-1&&F.text()){F.text("");
F._accessor("",-1);
}F._old=F._accessor();
F._oldIndex=F.selectedIndex;
});
},hasOptionLabel:function(){return this.optionLabel&&!!this.optionLabel[0];
},_optionLabel:function(){var G=this;
var E=G.options;
var D=E.optionLabel;
var F=E.optionLabelTemplate;
if(!D){G.optionLabel.off().remove();
G.optionLabel=b();
return;
}if(!F){F="#:";
if(typeof D==="string"){F+="data";
}else{F+=l.expr(E.dataTextField,"data");
}F+="#";
}if(typeof F!=="function"){F=l.template(F);
}G.optionLabelTemplate=F;
if(!G.hasOptionLabel()){G.optionLabel=b('<div class="k-list-optionlabel"></div>').prependTo(G.list);
}G.optionLabel.html(F(D)).off().click(s(G._click,G)).on(k,G._toggleHover);
G.angular("compile",function(){return{elements:G.optionLabel,data:[{dataItem:G._optionLabelDataItem()}]};
});
},_optionLabelText:function(){var D=this.options.optionLabel;
return typeof D==="string"?D:this._text(D);
},_optionLabelDataItem:function(){var E=this;
var D=E.options.optionLabel;
if(E.hasOptionLabel()){return b.isPlainObject(D)?new r(D):E._assignInstance(E._optionLabelText(),"");
}return null;
},_buildOptions:function(D){var G=this;
if(!G._isSelect){return;
}var H=G.listView.value()[0];
var E=G._optionLabelDataItem();
var F=E&&G._value(E);
if(H===C||H===null){H="";
}if(E){if(F===C||F===null){F="";
}E='<option value="'+F+'">'+G._text(E)+"</option>";
}G._options(D,E,H);
if(H!==n.unifyType(G._accessor(),typeof H)){G._customOption=null;
G._custom(H);
}},_listBound:function(){var H=this;
var G=H._initialIndex;
var F=H._state===x;
var D=H.dataSource.flatView();
var E;
H._presetValue=false;
H._renderFooter();
H._renderNoData();
H._toggleNoData(!D.length);
H._resizePopup(true);
H.popup.position();
H._buildOptions(D);
H._makeUnselectable();
if(!F){if(H._open){H.toggle(H._allowOpening());
}H._open=false;
if(!H._fetch){if(D.length){if(!H.listView.value().length&&G>-1&&G!==null){H.select(G);
}H._initialIndex=null;
E=H.listView.selectedDataItems()[0];
if(E&&H.text()!==H._text(E)){H._selectValue(E);
}}else{if(H._textAccessor()!==H._optionLabelText()){H.listView.value("");
H._selectValue(null);
H._oldIndex=H.selectedIndex;
}}}}H._hideBusy();
H.trigger("dataBound");
},_listChange:function(){this._selectValue(this.listView.selectedDataItems()[0]);
if(this._presetValue||this._old&&this._oldIndex===-1){this._oldIndex=this.selectedIndex;
}},_filterPaste:function(){this._search();
},_focusHandler:function(){this.wrapper.focus();
},_focusinHandler:function(){this._inputWrapper.addClass(j);
this._prevent=false;
},_focusoutHandler:function(){var H=this;
var E=H._state===x;
var G=window.self!==window.top;
var F=H._focus();
var D=H._getElementDataItem(F);
if(!H._prevent){clearTimeout(H._typingTimeout);
if(!E&&F&&!H.trigger("select",{dataItem:D,item:F})){H._select(F,!H.dataSource.view().length);
}if(z.mobileOS.ios&&G){H._change();
}else{H._blur();
}H._inputWrapper.removeClass(j);
H._prevent=true;
H._open=false;
H.element.blur();
}},_wrapperMousedown:function(){this._prevent=!!this.filterInput;
},_wrapperClick:function(D){D.preventDefault();
this.popup.unbind("activate",this._focusInputHandler);
this._focused=this.wrapper;
this._toggle();
},_editable:function(G){var I=this;
var F=I.element;
var D=G.disable;
var H=G.readonly;
var J=I.wrapper.add(I.filterInput).off(q);
var E=I._inputWrapper.off(k);
if(!H&&!D){F.removeAttr(h).removeAttr(t);
E.addClass(g).removeClass(y).on(k,I._toggleHover);
J.attr(A,J.data(A)).attr(d,false).on("keydown"+q,s(I._keydown,I)).on("focusin"+q,s(I._focusinHandler,I)).on("focusout"+q,s(I._focusoutHandler,I)).on("mousedown"+q,s(I._wrapperMousedown,I)).on("paste"+q,s(I._filterPaste,I));
I.wrapper.on("click"+q,s(I._wrapperClick,I));
if(!I.filterInput){J.on("keypress"+q,s(I._keypress,I));
}}else{if(D){J.removeAttr(A);
E.addClass(y).removeClass(g);
}else{E.addClass(g).removeClass(y);
J.on("focusin"+q,s(I._focusinHandler,I)).on("focusout"+q,s(I._focusoutHandler,I));
}}F.attr(h,D).attr(t,H);
J.attr(d,D);
},_keydown:function(F){var K=this;
var J=F.keyCode;
var D=F.altKey;
var H;
var G;
var I=K.popup.visible();
if(K.filterInput){H=K.filterInput[0]===c();
}if(J===m.LEFT){J=m.UP;
G=true;
}else{if(J===m.RIGHT){J=m.DOWN;
G=true;
}}if(G&&H){return;
}F.keyCode=J;
if(D&&J===m.UP||J===m.ESC){K._focusElement(K.wrapper);
}if(K._state===x&&J===m.ESC){K._clearFilter();
}if(J===m.ENTER&&K._typingTimeout&&K.filterInput&&I){F.preventDefault();
return;
}G=K._move(F);
if(G){return;
}if(!I||!K.filterInput){var E=K._focus();
if(J===m.HOME){G=true;
K._firstItem();
}else{if(J===m.END){G=true;
K._lastItem();
}}if(G){if(K.trigger("select",{dataItem:K._getElementDataItem(K._focus()),item:K._focus()})){K._focus(E);
return;
}K._select(K._focus(),true);
if(!I){K._blur();
}}}if(!D&&!G&&K.filterInput){K._search();
}},_matchText:function(E,F){var D=this.options.ignoreCase;
if(E===C||E===null){return false;
}E=E+"";
if(D){E=E.toLowerCase();
}return E.indexOf(F)===0;
},_shuffleData:function(D,F){var E=this._optionLabelDataItem();
if(E){D=[E].concat(D);
}return D.slice(F).concat(D.slice(0,F));
},_selectNext:function(){var K=this;
var D=K.dataSource.flatView();
var E=D.length+(K.hasOptionLabel()?1:0);
var G=u(K._word,K._last);
var I=K.selectedIndex;
var H;
var J;
if(I===-1){I=0;
}else{I+=G?1:0;
I=p(I,E);
}D=D.toJSON?D.toJSON():D.slice();
D=K._shuffleData(D,I);
for(var F=0;
F<E;
F++){J=K._text(D[F]);
if(G&&K._matchText(J,K._last)){break;
}else{if(K._matchText(J,K._word)){break;
}}}if(F!==E){H=K._focus();
K._select(p(I+F,E));
if(K.trigger("select",{dataItem:K._getElementDataItem(K._focus()),item:K._focus()})){K._select(H);
}if(!K.popup.visible()){K._change();
}}},_keypress:function(E){var F=this;
if(E.which===0||E.keyCode===l.keys.ENTER){return;
}var D=String.fromCharCode(E.charCode||E.keyCode);
if(F.options.ignoreCase){D=D.toLowerCase();
}if(D===" "){E.preventDefault();
}F._word+=D;
F._last=D;
F._search();
},_popupOpen:function(){var D=this.popup;
D.wrapper=l.wrap(D.element);
if(D.element.closest(".km-root")[0]){D.wrapper.addClass("km-popup km-widget");
this.wrapper.addClass("km-widget");
}},_popup:function(){v.fn._popup.call(this);
this.popup.one("open",s(this._popupOpen,this));
},_getElementDataItem:function(D){if(!D||!D[0]){return null;
}if(D[0]===this.optionLabel[0]){return this._optionLabelDataItem();
}return this.listView.dataItemByIndex(this.listView.getElementIndex(D));
},_click:function(D){var E=D.item||b(D.currentTarget);
D.preventDefault();
if(this.trigger("select",{dataItem:this._getElementDataItem(E),item:E})){this.close();
return;
}this._userTriggered=true;
this._select(E);
this._focusElement(this.wrapper);
this._blur();
},_focusElement:function(F){var D=c();
var I=this.wrapper;
var G=this.filterInput;
var E=F===G?I:G;
var H=z.mobileOS&&(z.touch||z.MSPointers||z.pointers);
if(G&&G[0]===F[0]&&H){return;
}if(G&&E[0]===D){this._prevent=true;
this._focused=F.focus();
}},_searchByWord:function(F){if(F){var E=this;
var D=E.options.ignoreCase;
if(D){F=F.toLowerCase();
}E._select(function(G){return E._matchText(E._text(G),F);
});
}},_inputValue:function(){return this.text();
},_search:function(){var E=this;
var D=E.dataSource;
clearTimeout(E._typingTimeout);
if(E._isFilterEnabled()){E._typingTimeout=setTimeout(function(){var F=E.filterInput.val();
if(E._prev!==F){E._prev=F;
E.search(F);
E._resizeFilterInput();
}E._typingTimeout=null;
},E.options.delay);
}else{E._typingTimeout=setTimeout(function(){E._word="";
},E.options.delay);
if(!E.listView.bound()){D.fetch().done(function(){E._selectNext();
});
return;
}E._selectNext();
}},_get:function(D){var E,F,G;
var H=typeof D==="function";
var I=!H?b(D):b();
if(this.hasOptionLabel()){if(typeof D==="number"){if(D>-1){D-=1;
}}else{if(I.hasClass("k-list-optionlabel")){D=-1;
}}}if(H){E=this.dataSource.flatView();
for(G=0;
G<E.length;
G++){if(D(E[G])){D=G;
F=true;
break;
}}if(!F){D=-1;
}}return D;
},_firstItem:function(){if(this.hasOptionLabel()){this._focus(this.optionLabel);
}else{this.listView.focusFirst();
}},_lastItem:function(){this._resetOptionLabel();
this.listView.focusLast();
},_nextItem:function(){if(this.optionLabel.hasClass("k-state-focused")){this._resetOptionLabel();
this.listView.focusFirst();
}else{this.listView.focusNext();
}},_prevItem:function(){if(this.optionLabel.hasClass("k-state-focused")){return;
}this.listView.focusPrev();
if(!this.listView.focus()){this._focus(this.optionLabel);
}},_focusItem:function(){var F=this.listView;
var D=F.focus();
var E=F.select();
E=E[E.length-1];
if(E===C&&this.options.highlightFirst&&!D){E=0;
}if(E!==C){F.focus(E);
}else{if(this.options.optionLabel){this._focus(this.optionLabel);
this._select(this.optionLabel);
}else{F.scrollToIndex(0);
}}},_resetOptionLabel:function(D){this.optionLabel.removeClass("k-state-focused"+(D||"")).removeAttr("id");
},_focus:function(D){var E=this.listView;
var F=this.optionLabel;
if(D===C){D=E.focus();
if(!D&&F.hasClass("k-state-focused")){D=F;
}return D;
}this._resetOptionLabel();
D=this._get(D);
E.focus(D);
if(D===-1){F.addClass("k-state-focused").attr("id",E._optionID);
this._focused.add(this.filterInput).removeAttr("aria-activedescendant").attr("aria-activedescendant",E._optionID);
}},_select:function(D,E){var F=this;
D=F._get(D);
F.listView.select(D);
if(!E&&F._state===x){F._state=w;
}if(D===-1){F._selectValue(null);
}},_selectValue:function(D){var H=this;
var F=H.options.optionLabel;
var E=H.listView.select();
var I="";
var G="";
E=E[E.length-1];
if(E===C){E=-1;
}this._resetOptionLabel(" k-state-selected");
if(D){G=D;
I=H._dataValue(D);
if(F){E+=1;
}}else{if(F){H._focus(H.optionLabel.addClass("k-state-selected"));
G=H._optionLabelText();
if(typeof F==="string"){I="";
}else{I=H._value(F);
}E=0;
}}H.selectedIndex=E;
if(I===null){I="";
}H._textAccessor(G);
H._accessor(I,E);
H._triggerCascade();
},_mobile:function(){var G=this,E=G.popup,D=z.mobileOS,F=E.element.parents(".km-root").eq(0);
if(F.length&&D){E.options.animation.open.effects=D.android||D.meego?"fadeIn":D.ios||D.wp?"slideIn:up":E.options.animation.open.effects;
}},_filterHeader:function(){var D;
if(this.filterInput){this.filterInput.off(q).parent().remove();
this.filterInput=null;
}if(this._isFilterEnabled()){D='<span class="k-icon k-i-search"></span>';
this.filterInput=b('<input class="k-textbox"/>').attr({placeholder:this.element.attr("placeholder"),title:this.element.attr("title"),role:"listbox","aria-haspopup":true,"aria-expanded":false});
this.list.prepend(b('<span class="k-list-filter" />').append(this.filterInput.add(D)));
}},_span:function(){var F=this,G=F.wrapper,D="span.k-input",E;
E=G.find(D);
if(!E[0]){G.append('<span unselectable="on" class="k-dropdown-wrap k-state-default"><span unselectable="on" class="k-input">&nbsp;</span><span unselectable="on" class="k-select" aria-label="select"><span class="k-icon k-i-arrow-s"></span></span></span>').append(F.element);
E=G.find(D);
}F.span=E;
F._inputWrapper=b(G[0].firstChild);
F._arrow=G.find(".k-icon");
},_wrapper:function(){var F=this,E=F.element,D=E[0],G;
G=E.parent();
if(!G.is("span.k-widget")){G=E.wrap("<span />").parent();
G[0].style.cssText=D.style.cssText;
G[0].title=D.title;
}F._focused=F.wrapper=G.addClass("k-widget k-dropdown k-header").addClass(D.className).css("display","").attr({accesskey:E.attr("accesskey"),unselectable:"on",role:"listbox","aria-haspopup":true,"aria-expanded":false});
E.hide().removeAttr("accesskey");
},_clearSelection:function(D){this.select(D.value()?0:-1);
},_inputTemplate:function(){var F=this,E=F.options.valueTemplate;
if(!E){E=b.proxy(l.template("#:this._text(data)#",{useWithBlock:false}),F);
}else{E=l.template(E);
}F.valueTemplate=E;
if(F.hasOptionLabel()&&!F.options.optionLabelTemplate){try{F.valueTemplate(F._optionLabelDataItem());
}catch(D){throw new Error(o);
}}},_textAccessor:function(J){var D=null;
var I=this.valueTemplate;
var G=this._optionLabelText();
var H=this.span;
if(J===C){return H.text();
}if(b.isPlainObject(J)||J instanceof r){D=J;
}else{if(G&&G===J){D=this.options.optionLabel;
}}if(!D){D=this._assignInstance(J,this._accessor());
}if(this.hasOptionLabel()){if(D===G||this._text(D)===G){I=this.optionLabelTemplate;
if(typeof this.options.optionLabel==="string"&&!this.options.optionLabelTemplate){D=G;
}}}var F=function(){return{elements:H.get(),data:[{dataItem:D}]};
};
this.angular("cleanup",F);
try{H.html(I(D));
}catch(E){H.html("");
}this.angular("compile",F);
},_preselect:function(E,D){if(!E&&!D){D=this._optionLabelText();
}this._accessor(E);
this._textAccessor(D);
this._old=this._accessor();
this._oldIndex=this.selectedIndex;
this.listView.setValue(E);
this._initialIndex=null;
this._presetValue=true;
},_assignInstance:function(F,G){var E=this.options.dataTextField;
var D={};
if(E){e(D,E.split("."),F);
e(D,this.options.dataValueField.split("."),G);
D=new r(D);
}else{D=F;
}return D;
}});
function e(G,E,I){var F=0,H=E.length-1,D;
for(;
F<H;
++F){D=E[F];
if(!(D in G)){G[D]={};
}G=G[D];
}G[E[H]]=I;
}function p(D,E){if(D>=E){D-=E;
}return D;
}function u(F,D){for(var E=0;
E<F.length;
E++){if(F.charAt(E)!==D){return false;
}}return true;
}B.plugin(i);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
