(function(b,a){a("kendo.editable",["kendo.datepicker","kendo.numerictextbox","kendo.validator","kendo.binder"],b);
}(function(){var a={id:"editable",name:"Editable",category:"framework",depends:["datepicker","numerictextbox","validator","binder"],hidden:true};
(function(b,u){var p=window.kendo,t=p.ui,v=t.Widget,k=b.extend,r=p.support.browser.msie&&p.support.browser.version<9,n=p.isFunction,o=b.isPlainObject,m=b.inArray,q=/("|\%|'|\[|\]|\$|\.|\,|\:|\;|\+|\*|\&|\!|\#|\(|\)|<|>|\=|\?|\@|\^|\{|\}|\~|\/|\||`)/g,j='<div class="k-widget k-tooltip k-tooltip-validation" style="margin:0.5em"><span class="k-icon k-i-warning"> </span>#=message#<div class="k-callout k-callout-n"></div></div>',d="change";
var s=["url","email","number","date","boolean"];
function l(w){w=w!=null?w:"";
return w.type||b.type(w)||"string";
}function f(w){w.find(":input:not(:button, ["+p.attr("role")+"=upload], ["+p.attr("skip")+"], [type=file]), select").each(function(){var x=p.attr("bind"),y=this.getAttribute(x)||"",z=this.type==="checkbox"||this.type==="radio"?"checked:":"value:",A=this.name;
if(y.indexOf(z)===-1&&A){y+=(y.length?",":"")+z+A;
b(this).attr(x,y);
}});
}function g(A){var z=(A.model.fields||A.model)[A.field],D=l(z),E=z?z.validation:{},C,y=p.attr("type"),x=p.attr("bind"),B,w={name:A.field};
for(C in E){B=E[C];
if(m(C,s)>=0){w[y]=C;
}else{if(!n(B)){w[C]=o(B)?B.value||C:B;
}}w[p.attr(C+"-msg")]=B.message;
}if(m(D,s)>=0){w[y]=D;
}w[x]=(D==="boolean"?"checked:":"value:")+A.field;
return w;
}function e(y){var w,z,x,C,B,A;
if(y&&y.length){A=[];
for(w=0,z=y.length;
w<z;
w++){x=y[w];
B=x.text||x.value||x;
C=x.value==null?x.text||x:x.value;
A[w]={text:B,value:C};
}}return A;
}var i={number:function(x,y){var w=g(y);
b('<input type="text"/>').attr(w).appendTo(x).kendoNumericTextBox({format:y.format});
b("<span "+p.attr("for")+'="'+y.field+'" class="k-invalid-msg"/>').hide().appendTo(x);
},date:function(x,z){var w=g(z),y=z.format;
if(y){y=p._extractFormat(y);
}w[p.attr("format")]=y;
b('<input type="text"/>').attr(w).appendTo(x).kendoDatePicker({format:z.format});
b("<span "+p.attr("for")+'="'+z.field+'" class="k-invalid-msg"/>').hide().appendTo(x);
},string:function(x,y){var w=g(y);
b('<input type="text" class="k-input k-textbox"/>').attr(w).appendTo(x);
},"boolean":function(x,y){var w=g(y);
b('<input type="checkbox" />').attr(w).appendTo(x);
},values:function(x,z){var w=g(z);
var y=p.stringify(e(z.values));
b("<select "+p.attr("text-field")+'="text"'+p.attr("value-field")+'="value"'+p.attr("source")+"='"+(y?y.replace(/\'/g,"&apos;"):y)+"'"+p.attr("role")+'="dropdownlist"/>').attr(w).appendTo(x);
b("<span "+p.attr("for")+'="'+z.field+'" class="k-invalid-msg"/>').hide().appendTo(x);
}};
function c(x,z){var A=x?x.validation||{}:{},y,w;
for(y in A){w=A[y];
if(o(w)&&w.value){w=w.value;
}if(n(w)){z[y]=w;
}}}var h=v.extend({init:function(w,x){var y=this;
if(x.target){x.$angular=x.target.options.$angular;
}v.fn.init.call(y,w,x);
y._validateProxy=b.proxy(y._validate,y);
y.refresh();
},events:[d],options:{name:"Editable",editors:i,clearContainer:true,errorTemplate:j},editor:function(z,F){var G=this,y=G.options.editors,C=o(z),A=C?z.field:z,E=G.options.model||{},D=C&&z.values,H=D?"values":l(F),B=C&&z.editor,x=B?z.editor:y[H],w=G.element.find("["+p.attr("container-for")+"="+A.replace(q,"\\$1")+"]");
x=x?x:y.string;
if(B&&typeof z.editor==="string"){x=function(I){I.append(z.editor);
};
}w=w.length?w:G.element;
x(w,k(true,{},C?z:{field:A},{model:E}));
},_validate:function(y){var C=this,A,D=y.value,B=C._validationEventInProgress,E={},w=p.attr("bind"),z=y.field.replace(q,"\\$1"),x=new RegExp("(value|checked)\\s*:\\s*"+z+"\\s*(,|$)");
E[y.field]=y.value;
A=b(":input["+w+'*="'+z+'"]',C.element).filter("["+p.attr("validate")+"!='false']").filter(function(){return x.test(b(this).attr(w));
});
if(A.length>1){A=A.filter(function(){var F=b(this);
return !F.is(":radio")||F.val()==D;
});
}try{C._validationEventInProgress=true;
if(!C.validatable.validateInput(A)||!B&&C.trigger(d,{values:E})){y.preventDefault();
}}finally{C._validationEventInProgress=false;
}},end:function(){return this.validatable.validate();
},destroy:function(){var w=this;
w.angular("cleanup",function(){return{elements:w.element};
});
v.fn.destroy.call(w);
w.options.model.unbind("set",w._validateProxy);
p.unbind(w.element);
if(w.validatable){w.validatable.destroy();
}p.destroy(w.element);
w.element.removeData("kendoValidator");
if(w.element.is("["+p.attr("role")+"=editable]")){w.element.removeAttr(p.attr("role"));
}},refresh:function(){var I=this,B,D,z=I.options.fields||[],w=I.options.clearContainer?I.element.empty():I.element,E=I.options.model||{},H={},x,C,y,F,G;
if(!b.isArray(z)){z=[z];
}for(B=0,D=z.length;
B<D;
B++){x=z[B];
C=o(x);
y=C?x.field:x;
F=(E.fields||E)[y];
c(F,H);
I.editor(x,F);
}if(I.options.target){I.angular("compile",function(){return{elements:w,data:w.map(function(){return{dataItem:E};
})};
});
}if(!D){G=E.fields||E;
for(y in G){c(G[y],H);
}}f(w);
if(I.validatable){I.validatable.destroy();
}p.bind(w,I.options.model);
I.options.model.unbind("set",I._validateProxy);
I.options.model.bind("set",I._validateProxy);
I.validatable=new p.ui.Validator(w,{validateOnBlur:false,errorTemplate:I.options.errorTemplate||u,rules:H});
var A=w.find(":kendoFocusable").eq(0).focus();
if(r){A.focus();
}}});
t.plugin(h);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
