(function(b,a){a("kendo.menu",["kendo.popup"],b);
}(function(){var a={id:"menu",name:"Menu",category:"web",description:"The Menu widget displays hierarchical data as a multi-level menu.",depends:["popup"]};
(function(b,ai){var B=window.kendo,ah=B.ui,d=B._activeElement,af=B.support.touch&&B.support.mobileOS,M="mousedown",g="click",s=b.extend,X=b.proxy,p=b.each,ab=B.template,D=B.keys,am=ah.Widget,q=/^(ul|a|div)$/i,R=".kendoMenu",z="img",S="open",J="k-menu",G="k-link",E="k-last",h="close",ae="timer",t="k-first",y="k-image",Z="select",an="zIndex",c="activate",k="deactivate",U="touchstart"+R+" MSPointerDown"+R+" pointerdown"+R,V=B.support.pointers,P=B.support.msPointers,f=P||V,N=V?"pointerover":P?"MSPointerOver":"mouseenter",O=V?"pointerout":P?"MSPointerOut":"mouseleave",L=af||f,o=b(document.documentElement),C="kendoPopup",l="k-state-default",x="k-state-hover",u="k-state-focused",n="k-state-disabled",aa="k-state-selected",K=".k-menu",w=".k-menu-group",W=w+",.k-animation-container",e=":not(.k-list) > .k-item",m=".k-item.k-state-disabled",A=".k-item:not(.k-state-disabled)",H=".k-item:not(.k-state-disabled) > .k-link",r=":not(.k-item.k-separator)",Q=r+":eq(0)",F=r+":last",ad="> div:not(.k-animation-container,.k-list-container)",ag={"2":1,touch:1},ac={content:ab("<div #= contentCssAttributes(item) # tabindex='-1'>#= content(item) #</div>"),group:ab("<ul class='#= groupCssClass(group) #'#= groupAttributes(group) # role='menu' aria-hidden='true'>#= renderItems(data) #</ul>"),itemWrapper:ab("<#= tag(item) # class='#= textClass(item) #'#= textAttributes(item) #>#= image(data) ##= sprite(item) ##= text(item) ##= arrow(data) #</#= tag(item) #>"),item:ab("<li class='#= wrapperCssClass(group, item) #' #= itemCssAttributes(item) # role='menuitem'  #=item.items ? \"aria-haspopup='true'\": \"\"##=item.enabled === false ? \"aria-disabled='true'\" : ''#>#= itemWrapper(data) ## if (item.items) { ##= subGroup({ items: item.items, menu: menu, group: { expanded: item.expanded } }) ## } else if (item.content || item.contentUrl) { ##= renderContent(data) ## } #</li>"),image:ab("<img #= imageCssAttributes(item) # alt='' src='#= item.imageUrl #' />"),arrow:ab("<span class='#= arrowClass(item, group) #'></span>"),sprite:ab("<span class='k-sprite #= spriteCssClass #'></span>"),empty:ab("")},Y={wrapperCssClass:function(ao,aq){var ar="k-item",ap=aq.index;
if(aq.enabled===false){ar+=" k-state-disabled";
}else{ar+=" k-state-default";
}if(ao.firstLevel&&ap===0){ar+=" k-first";
}if(ap==ao.length-1){ar+=" k-last";
}if(aq.cssClass){ar+=" "+aq.cssClass;
}if(aq.attr&&aq.attr.hasOwnProperty("class")){ar+=" "+aq.attr["class"];
}if(aq.selected){ar+=" "+aa;
}return ar;
},itemCssAttributes:function(aq){var ar="";
var ap=aq.attr||{};
for(var ao in ap){if(ap.hasOwnProperty(ao)&&ao!=="class"){ar+=ao+'="'+ap[ao]+'" ';
}}return ar;
},imageCssAttributes:function(aq){var ar="";
var ap=aq.imageAttr||{};
if(!ap["class"]){ap["class"]=y;
}else{ap["class"]+=" "+y;
}for(var ao in ap){if(ap.hasOwnProperty(ao)){ar+=ao+'="'+ap[ao]+'" ';
}}return ar;
},contentCssAttributes:function(ar){var at="";
var ap=ar.contentAttr||{};
var aq="k-content k-group k-menu-group";
if(!ap["class"]){ap["class"]=aq;
}else{ap["class"]+=" "+aq;
}for(var ao in ap){if(ap.hasOwnProperty(ao)){at+=ao+'="'+ap[ao]+'" ';
}}return at;
},textClass:function(){return G;
},textAttributes:function(ao){return ao.url?" href='"+ao.url+"'":"";
},arrowClass:function(ap,ao){var aq="k-icon";
if(ao.horizontal){aq+=" k-i-arrow-s";
}else{aq+=" k-i-arrow-e";
}return aq;
},text:function(ao){return ao.encoded===false?ao.text:B.htmlEncode(ao.text);
},tag:function(ao){return ao.url?"a":"span";
},groupAttributes:function(ao){return ao.expanded!==true?" style='display:none'":"";
},groupCssClass:function(){return"k-group k-menu-group";
},content:function(ao){return ao.content?ao.content:"&nbsp;";
}};
function v(ao,ap){ao=ao.split(" ")[!ap+0]||ao;
return ao.replace("top","up").replace("bottom","down");
}function T(ao,at,aq){ao=ao.split(" ")[!at+0]||ao;
var ar={origin:["bottom",aq?"right":"left"],position:["top",aq?"right":"left"]},ap=/left|right/.test(ao);
if(ap){ar.origin=["top",ao];
ar.position[1]=B.directions[ao].reverse;
}else{ar.origin[0]=ao;
ar.position[0]=B.directions[ao].reverse;
}ar.origin=ar.origin.join(" ");
ar.position=ar.position.join(" ");
return ar;
}function i(aq,ao){try{return b.contains(aq,ao);
}catch(ap){return false;
}}function al(ao){ao=b(ao);
ao.addClass("k-item").children(z).addClass(y);
ao.children("a").addClass(G).children(z).addClass(y);
ao.filter(":not([disabled])").addClass(l);
ao.filter(".k-separator").empty().append("&nbsp;");
ao.filter("li[disabled]").addClass(n).removeAttr("disabled").attr("aria-disabled",true);
if(!ao.filter("[role]").length){ao.attr("role","menuitem");
}if(!ao.children("."+G).length){ao.contents().filter(function(){return !this.nodeName.match(q)&&!(this.nodeType==3&&!b.trim(this.nodeValue));
}).wrapAll("<span class='"+G+"'/>");
}aj(ao);
ak(ao);
}function aj(ao){ao=b(ao);
ao.find("> .k-link > [class*=k-i-arrow]:not(.k-sprite)").remove();
ao.filter(":has(.k-menu-group)").children(".k-link:not(:has([class*=k-i-arrow]:not(.k-sprite)))").each(function(){var ap=b(this),aq=ap.parent().parent();
ap.append("<span class='k-icon "+(aq.hasClass(J+"-horizontal")?"k-i-arrow-s":"k-i-arrow-e")+"'/>");
});
}function ak(ao){ao=b(ao);
ao.filter(".k-first:not(:first-child)").removeClass(t);
ao.filter(".k-last:not(:last-child)").removeClass(E);
ao.filter(":first-child").addClass(t);
ao.filter(":last-child").addClass(E);
}var I=am.extend({init:function(ao,ap){var aq=this;
am.fn.init.call(aq,ao,ap);
ao=aq.wrapper=aq.element;
ap=aq.options;
aq._initData(ap);
aq._updateClasses();
aq._animations(ap);
aq.nextItemZIndex=100;
aq._tabindex();
aq._focusProxy=X(aq._focusHandler,aq);
ao.on(U,A,aq._focusProxy).on(g+R,m,false).on(g+R,A,X(aq._click,aq)).on("keydown"+R,X(aq._keydown,aq)).on("focus"+R,X(aq._focus,aq)).on("focus"+R,".k-content",X(aq._focus,aq)).on(U+" "+M+R,".k-content",X(aq._preventClose,aq)).on("blur"+R,X(aq._removeHoverItem,aq)).on("blur"+R,"[tabindex]",X(aq._checkActiveElement,aq)).on(N+R,A,X(aq._mouseenter,aq)).on(O+R,A,X(aq._mouseleave,aq)).on(N+R+" "+O+R+" "+M+R+" "+g+R,H,X(aq._toggleHover,aq));
if(ap.openOnClick){aq.clicked=false;
aq._documentClickHandler=X(aq._documentClick,aq);
b(document).click(aq._documentClickHandler);
}ao.attr("role","menubar");
if(ao[0].id){aq._ariaId=B.format("{0}_mn_active",ao[0].id);
}B.notify(aq);
},events:[S,h,c,k,Z],options:{name:"Menu",animation:{open:{duration:200},close:{duration:100}},orientation:"horizontal",direction:"default",openOnClick:false,closeOnClick:true,hoverDelay:100,popupCollision:ai},_initData:function(ao){var ap=this;
if(ao.dataSource){ap.angular("cleanup",function(){return{elements:ap.element.children()};
});
ap.element.empty();
ap.append(ao.dataSource,ap.element);
ap.angular("compile",function(){return{elements:ap.element.children()};
});
}},setOptions:function(ap){var ao=this.options.animation;
this._animations(ap);
ap.animation=s(true,ao,ap.animation);
if("dataSource" in ap){this._initData(ap);
}this._updateClasses();
am.fn.setOptions.call(this,ap);
},destroy:function(){var ao=this;
am.fn.destroy.call(ao);
ao.element.off(R);
if(ao._documentClickHandler){b(document).unbind("click",ao._documentClickHandler);
}B.destroy(ao.element);
},enable:function(ao,ap){this._toggleDisabled(ao,ap!==false);
return this;
},disable:function(ao){this._toggleDisabled(ao,false);
return this;
},append:function(ap,aq){aq=this.element.find(aq);
var ao=this._insert(ap,aq,aq.length?aq.find("> .k-menu-group, > .k-animation-container > .k-menu-group"):null);
p(ao.items,function(){ao.group.append(this);
aj(this);
});
aj(aq);
ak(ao.group.find(".k-first, .k-last").add(ao.items));
return this;
},insertBefore:function(ap,aq){aq=this.element.find(aq);
var ao=this._insert(ap,aq,aq.parent());
p(ao.items,function(){aq.before(this);
aj(this);
ak(this);
});
ak(aq);
return this;
},insertAfter:function(ap,aq){aq=this.element.find(aq);
var ao=this._insert(ap,aq,aq.parent());
p(ao.items,function(){aq.after(this);
aj(this);
ak(this);
});
ak(aq);
return this;
},_insert:function(aq,av,at){var aw=this,ar,ap;
if(!av||!av.length){at=aw.element;
}var au=b.isPlainObject(aq),ao={firstLevel:at.hasClass(J),horizontal:at.hasClass(J+"-horizontal"),expanded:true,length:at.children().length};
if(av&&!at.length){at=b(I.renderGroup({group:ao})).appendTo(av);
}if(au||b.isArray(aq)){ar=b(b.map(au?[aq]:aq,function(ay,ax){if(typeof ay==="string"){return b(ay).get();
}else{return b(I.renderItem({group:ao,item:s(ay,{index:ax})})).get();
}}));
}else{if(typeof aq=="string"&&aq.charAt(0)!="<"){ar=aw.element.find(aq);
}else{ar=b(aq);
}ap=ar.find("> ul").addClass("k-menu-group").attr("role","menu");
ar=ar.filter("li");
ar.add(ap.find("> li")).each(function(){al(this);
});
}return{items:ar,group:at};
},remove:function(ap){ap=this.element.find(ap);
var at=this,ar=ap.parentsUntil(at.element,e),aq=ap.parent("ul:not(.k-menu)");
ap.remove();
if(aq&&!aq.children(e).length){var ao=aq.parent(".k-animation-container");
if(ao.length){ao.remove();
}else{aq.remove();
}}if(ar.length){ar=ar.eq(0);
aj(ar);
ak(ar);
}return at;
},open:function(ap){var au=this,at=au.options,aq=at.orientation=="horizontal",ao=at.direction,ar=B.support.isRtl(au.wrapper);
ap=au.element.find(ap);
if(/^(top|bottom|default)$/.test(ao)){if(ar){ao=aq?(ao+" left").replace("default","bottom"):"left";
}else{ao=aq?(ao+" right").replace("default","bottom"):"right";
}}ap.siblings().find(">.k-popup:visible,>.k-animation-container>.k-popup:visible").each(function(){var av=b(this).data("kendoPopup");
if(av){av.close();
}});
ap.each(function(){var av=b(this);
clearTimeout(av.data(ae));
av.data(ae,setTimeout(function(){var aD=av.find(".k-menu-group:first:hidden"),aA;
if(aD[0]&&au._triggerEvent({item:av[0],type:S})===false){if(!aD.find(".k-menu-group")[0]&&aD.children(".k-item").length>1){var aE=b(window).height(),aC=function(){aD.css({maxHeight:aE-(aD.outerHeight()-aD.height())-B.getShadows(aD).bottom,overflow:"auto"});
};
if(B.support.browser.msie&&B.support.browser.version<=7){setTimeout(aC,0);
}else{aC();
}}else{aD.css({maxHeight:"",overflow:""});
}av.data(an,av.css(an));
av.css(an,au.nextItemZIndex++);
aA=aD.data(C);
var aB=av.parent().hasClass(J),az=aB&&aq,aw=T(ao,aB,ar),ax=at.animation.open.effects,ay=ax!==ai?ax:"slideIn:"+v(ao,aB);
if(!aA){aA=aD.kendoPopup({activate:function(){au._triggerEvent({item:this.wrapper.parent(),type:c});
},deactivate:function(aF){aF.sender.element.removeData("targetTransform").css({opacity:""});
au._triggerEvent({item:this.wrapper.parent(),type:k});
},origin:aw.origin,position:aw.position,collision:at.popupCollision!==ai?at.popupCollision:az?"fit":"fit flip",anchor:av,appendTo:av,animation:{open:s(true,{effects:ay},at.animation.open),close:at.animation.close},close:function(aF){var aG=aF.sender.wrapper.parent();
if(!au._triggerEvent({item:aG[0],type:h})){aG.css(an,aG.data(an));
aG.removeData(an);
if(af){aG.removeClass(x);
au._removeHoverItem();
}}else{aF.preventDefault();
}}}).data(C);
}else{aA=aD.data(C);
aA.options.origin=aw.origin;
aA.options.position=aw.position;
aA.options.animation.open.effects=ay;
}aD.removeAttr("aria-hidden");
aA.open();
}},au.options.hoverDelay));
});
return au;
},close:function(aq,ao){var ar=this,ap=ar.element;
aq=ap.find(aq);
if(!aq.length){aq=ap.find(">.k-item");
}aq.each(function(){var at=b(this);
if(!ao&&ar._isRootItem(at)){ar.clicked=false;
}clearTimeout(at.data(ae));
at.data(ae,setTimeout(function(){var au=at.find(".k-menu-group:not(.k-list-container):not(.k-calendar-container):first:visible").data(C);
if(au){au.close();
au.element.attr("aria-hidden",true);
}},ar.options.hoverDelay));
});
return ar;
},_toggleDisabled:function(ap,ao){this.element.find(ap).each(function(){b(this).toggleClass(l,ao).toggleClass(n,!ao).attr("aria-disabled",!ao);
});
},_toggleHover:function(ao){var aq=b(B.eventTarget(ao)||ao.target).closest(e),ap=ao.type==N||M.indexOf(ao.type)!==-1;
if(!aq.parents("li."+n).length){aq.toggleClass(x,ap||ao.type=="mousedown"||ao.type=="click");
}this._removeHoverItem();
},_preventClose:function(){if(!this.options.closeOnClick){this._closurePrevented=true;
}},_checkActiveElement:function(ao){var ar=this,ap=b(ao?ao.currentTarget:this._hoverItem()),aq=ar._findRootParent(ap)[0];
if(!this._closurePrevented){setTimeout(function(){if(!document.hasFocus()||!i(aq,B._activeElement())&&ao&&!i(aq,ao.currentTarget)){ar.close(aq);
}},0);
}this._closurePrevented=false;
},_removeHoverItem:function(){var ao=this._hoverItem();
if(ao&&ao.hasClass(u)){ao.removeClass(u);
this._oldHoverItem=null;
}},_updateClasses:function(){var ao=this.element,aq=".k-menu-init div ul",ap;
ao.removeClass("k-menu-horizontal k-menu-vertical");
ao.addClass("k-widget k-reset k-header k-menu-init "+J).addClass(J+"-"+this.options.orientation);
ao.find("li > ul").filter(function(){return !B.support.matchesSelector.call(this,aq);
}).addClass("k-group k-menu-group").attr("role","menu").attr("aria-hidden",ao.is(":visible")).end().find("li > div").addClass("k-content").attr("tabindex","-1");
ap=ao.find("> li,.k-menu-group > li");
ao.removeClass("k-menu-init");
ap.each(function(){al(this);
});
},_mouseenter:function(ao){var ar=this,ap=b(ao.currentTarget),aq=ap.children(".k-animation-container").length||ap.children(w).length;
if(ao.delegateTarget!=ap.parents(K)[0]){return;
}if((!ar.options.openOnClick||ar.clicked)&&!af&&!((V||P)&&ao.originalEvent.pointerType in ag&&ar._isRootItem(ap.closest(e)))){if(!i(ao.currentTarget,ao.relatedTarget)&&aq){ar.open(ap);
}}if(ar.options.openOnClick&&ar.clicked||L){ap.siblings().each(X(function(at,au){ar.close(au,true);
},ar));
}},_mouseleave:function(ao){var ar=this,ap=b(ao.currentTarget),aq=ap.children(".k-animation-container").length||ap.children(w).length;
if(ap.parentsUntil(".k-animation-container",".k-list-container,.k-calendar-container")[0]){ao.stopImmediatePropagation();
return;
}if(!ar.options.openOnClick&&!af&&!((V||P)&&ao.originalEvent.pointerType in ag)&&!i(ao.currentTarget,ao.relatedTarget||ao.target)&&aq&&!i(ao.currentTarget,B._activeElement())){ar.close(ap);
}},_click:function(aq){var aG=this,aA,aB=aG.options,aE=b(B.eventTarget(aq)),az=aE[0]?aE[0].nodeName.toUpperCase():"",at=az=="INPUT"||az=="SELECT"||az=="BUTTON"||az=="LABEL",ay=aE.closest("."+G),ar=aE.closest(e),au=ay.attr("href"),ao,ap,aF=aE.attr("href"),aC=b("<a href='#' />").attr("href"),av=!!au&&au!==aC,aw=av&&!!au.match(/^#/),ax=!!aF&&aF!==aC,aD=aB.openOnClick&&ap&&aG._isRootItem(ar);
if(aE.closest(ad,ar[0]).length){return;
}if(ar.hasClass(n)){aq.preventDefault();
return;
}if(!aq.handled&&aG._triggerEvent({item:ar[0],type:Z})&&!at){aq.preventDefault();
}aq.handled=true;
ao=ar.children(W);
ap=ao.is(":visible");
if(aB.closeOnClick&&(!av||aw)&&(!ao.length||aD)){ar.removeClass(x).css("height");
aG._oldHoverItem=aG._findRootParent(ar);
aG.close(ay.parentsUntil(aG.element,e));
aG.clicked=false;
if("MSPointerUp".indexOf(aq.type)!=-1){aq.preventDefault();
}return;
}if(av&&aq.enterKey){ay[0].click();
}if((!aG._isRootItem(ar)||!aB.openOnClick)&&!B.support.touch&&!((V||P)&&aG._isRootItem(ar.closest(e)))){return;
}if(!av&&!at&&!ax){aq.preventDefault();
}aG.clicked=true;
aA=ao.is(":visible")?h:S;
if(!aB.closeOnClick&&aA==h){return;
}aG[aA](ar);
},_documentClick:function(ao){if(i(this.element[0],ao.target)){return;
}this.clicked=false;
},_focus:function(ap){var at=this,ar=ap.target,aq=at._hoverItem(),ao=d();
if(ar!=at.wrapper[0]&&!b(ar).is(":kendoFocusable")){ap.stopPropagation();
b(ar).closest(".k-content").closest(".k-menu-group").closest(".k-item").addClass(u);
at.wrapper.focus();
return;
}if(ao===ap.currentTarget){if(aq.length){at._moveHover([],aq);
}else{if(!at._oldHoverItem){at._moveHover([],at.wrapper.children().first());
}}}},_keydown:function(ap){var aw=this,au=ap.keyCode,ar=aw._oldHoverItem,av,ao,aq,at=B.support.isRtl(aw.wrapper);
if(ap.target!=ap.currentTarget&&au!=D.ESC){return;
}if(!ar){ar=aw._oldHoverItem=aw._hoverItem();
}ao=aw._itemBelongsToVertival(ar);
aq=aw._itemHasChildren(ar);
if(au==D.RIGHT){av=aw[at?"_itemLeft":"_itemRight"](ar,ao,aq);
}else{if(au==D.LEFT){av=aw[at?"_itemRight":"_itemLeft"](ar,ao,aq);
}else{if(au==D.DOWN){av=aw._itemDown(ar,ao,aq);
}else{if(au==D.UP){av=aw._itemUp(ar,ao,aq);
}else{if(au==D.ESC){av=aw._itemEsc(ar,ao);
}else{if(au==D.ENTER||au==D.SPACEBAR){av=ar.children(".k-link");
if(av.length>0){aw._click({target:av[0],preventDefault:function(){},enterKey:true});
aw._moveHover(ar,aw._findRootParent(ar));
}}else{if(au==D.TAB){av=aw._findRootParent(ar);
aw._moveHover(ar,av);
aw._checkActiveElement();
return;
}}}}}}}if(av&&av[0]){ap.preventDefault();
ap.stopPropagation();
}},_hoverItem:function(){return this.wrapper.find(".k-item.k-state-hover,.k-item.k-state-focused").filter(":visible");
},_itemBelongsToVertival:function(ao){var ap=this.wrapper.hasClass("k-menu-vertical");
if(!ao.length){return ap;
}return ao.parent().hasClass("k-menu-group")||ap;
},_itemHasChildren:function(ao){if(!ao.length){return false;
}return ao.children("ul.k-menu-group, div.k-animation-container").length>0;
},_moveHover:function(ap,aq){var ar=this,ao=ar._ariaId;
if(ap.length&&aq.length){ap.removeClass(u);
}if(aq.length){if(aq[0].id){ao=aq[0].id;
}aq.addClass(u);
ar._oldHoverItem=aq;
if(ao){ar.element.removeAttr("aria-activedescendant");
b("#"+ao).removeAttr("id");
aq.attr("id",ao);
ar.element.attr("aria-activedescendant",ao);
}}},_findRootParent:function(ao){if(this._isRootItem(ao)){return ao;
}else{return ao.parentsUntil(K,"li.k-item").last();
}},_isRootItem:function(ao){return ao.parent().hasClass(J);
},_itemRight:function(aq,ao,ap){var au=this,ar,at;
if(aq.hasClass(n)){return;
}if(!ao){ar=aq.nextAll(Q);
if(!ar.length){ar=aq.prevAll(F);
}}else{if(ap){au.open(aq);
ar=aq.find(".k-menu-group").children().first();
}else{if(au.options.orientation=="horizontal"){at=au._findRootParent(aq);
au.close(at);
ar=at.nextAll(Q);
}}}if(ar&&!ar.length){ar=au.wrapper.children(".k-item").first();
}else{if(!ar){ar=[];
}}au._moveHover(aq,ar);
return ar;
},_itemLeft:function(ap,ao){var ar=this,aq;
if(!ao){aq=ap.prevAll(Q);
if(!aq.length){aq=ap.nextAll(F);
}}else{aq=ap.parent().closest(".k-item");
ar.close(aq);
if(ar._isRootItem(aq)&&ar.options.orientation=="horizontal"){aq=aq.prevAll(Q);
}}if(!aq.length){aq=ar.wrapper.children(".k-item").last();
}ar._moveHover(ap,aq);
return aq;
},_itemDown:function(aq,ao,ap){var at=this,ar;
if(!ao){if(!ap||aq.hasClass(n)){return;
}else{at.open(aq);
ar=aq.find(".k-menu-group").children().first();
}}else{ar=aq.nextAll(Q);
}if(!ar.length&&aq.length){ar=aq.parent().children().first();
}else{if(!aq.length){ar=at.wrapper.children(".k-item").first();
}}at._moveHover(aq,ar);
return ar;
},_itemUp:function(ap,ao){var ar=this,aq;
if(!ao){return;
}else{aq=ap.prevAll(Q);
}if(!aq.length&&ap.length){aq=ap.parent().children().last();
}else{if(!ap.length){aq=ar.wrapper.children(".k-item").last();
}}ar._moveHover(ap,aq);
return aq;
},_itemEsc:function(ap,ao){var ar=this,aq;
if(!ao){return ap;
}else{aq=ap.parent().closest(".k-item");
ar.close(aq);
ar._moveHover(ap,aq);
}return aq;
},_triggerEvent:function(ao){var ap=this;
return ap.trigger(ao.type,{type:ao.type,item:ao.item});
},_focusHandler:function(ao){var aq=this,ap=b(B.eventTarget(ao)).closest(e);
setTimeout(function(){aq._moveHover([],ap);
if(ap.children(".k-content")[0]){ap.parent().closest(".k-item").removeClass(u);
}},200);
},_animations:function(ao){if(ao&&"animation" in ao&&!ao.animation){ao.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}}});
s(I,{renderItem:function(aq){aq=s({menu:{},group:{}},aq);
var ao=ac.empty,ap=aq.item;
return ac.item(s(aq,{image:ap.imageUrl?ac.image:ao,sprite:ap.spriteCssClass?ac.sprite:ao,itemWrapper:ac.itemWrapper,renderContent:I.renderContent,arrow:ap.items||ap.content?ac.arrow:ao,subGroup:I.renderGroup},Y));
},renderGroup:function(ao){return ac.group(s({renderItems:function(av){var aq="",ar=0,at=av.items,au=at?at.length:0,ap=s({length:au},av.group);
for(;
ar<au;
ar++){aq+=I.renderItem(s(av,{group:ap,item:s({index:ar},at[ar])}));
}return aq;
}},ao,Y));
},renderContent:function(ao){return ac.content(s(ao,Y));
}});
var j=I.extend({init:function(ao,ap){var aq=this;
I.fn.init.call(aq,ao,ap);
aq._marker=B.guid().substring(0,8);
aq.target=b(aq.options.target);
aq._popup();
aq._wire();
},options:{name:"ContextMenu",filter:null,showOn:"contextmenu",orientation:"vertical",alignToAnchor:false,target:"body"},events:[S,h,c,k,Z],setOptions:function(ao){var ap=this;
I.fn.setOptions.call(ap,ao);
ap.target.off(ap.showOn+R+ap._marker,ap._showProxy);
if(ap.userEvents){ap.userEvents.destroy();
}ap.target=b(ap.options.target);
if(ao.orientation&&ap.popup.wrapper[0]){ap.popup.element.unwrap();
}ap._wire();
I.fn.setOptions.call(this,ao);
},destroy:function(){var ao=this;
ao.target.off(ao.options.showOn+R+ao._marker);
o.off(B.support.mousedown+R+ao._marker,ao._closeProxy);
if(ao.userEvents){ao.userEvents.destroy();
}I.fn.destroy.call(ao);
},open:function(ap,aq){var ao=this;
ap=b(ap)[0];
if(i(ao.element[0],b(ap)[0])){I.fn.open.call(ao,ap);
}else{if(ao._triggerEvent({item:ao.element,type:S})===false){if(ao.popup.visible()&&ao.options.filter){ao.popup.close(true);
ao.popup.element.kendoStop(true);
}if(aq!==ai){ao.popup.wrapper.hide();
ao.popup.open(ap,aq);
}else{ao.popup.options.anchor=(ap?ap:ao.popup.anchor)||ao.target;
ao.popup.element.kendoStop(true);
ao.popup.open();
}o.off(ao.popup.downEvent,ao.popup._mousedownProxy);
o.on(B.support.mousedown+R+ao._marker,ao._closeProxy);
}}return ao;
},close:function(){var ao=this;
if(i(ao.element[0],b(arguments[0])[0])){I.fn.close.call(ao,arguments[0]);
}else{if(ao.popup.visible()){if(ao._triggerEvent({item:ao.element,type:h})===false){ao.popup.close();
o.off(B.support.mousedown+R,ao._closeProxy);
ao.unbind(Z,ao._closeTimeoutProxy);
}}}},_showHandler:function(ao){var ap=ao,aq,at=this,ar=at.options;
if(ao.event){ap=ao.event;
ap.pageX=ao.x.location;
ap.pageY=ao.y.location;
}if(i(at.element[0],ao.relatedTarget||ao.target)){return;
}at._eventOrigin=ap;
ap.preventDefault();
ap.stopImmediatePropagation();
at.element.find("."+u).removeClass(u);
if(ar.filter&&B.support.matchesSelector.call(ap.currentTarget,ar.filter)||!ar.filter){if(ar.alignToAnchor){at.popup.options.anchor=ap.currentTarget;
at.open(ap.currentTarget);
}else{at.popup.options.anchor=ap.currentTarget;
if(at._targetChild){aq=at.target.offset();
at.open(ap.pageX-aq.left,ap.pageY-aq.top);
}else{at.open(ap.pageX,ap.pageY);
}}}},_closeHandler:function(aq){var av=this,au=b(aq.relatedTarget||aq.target),at=au.closest(av.target.selector)[0]==av.target[0],ao=au.closest(A).children(W),ap=i(av.element[0],au[0]);
av._eventOrigin=aq;
var ar=aq.which!==3;
if(av.popup.visible()&&(ar&&at||!at)&&(av.options.closeOnClick&&!ao[0]&&ap||!ap)){if(ap){this.unbind(Z,this._closeTimeoutProxy);
av.bind(Z,av._closeTimeoutProxy);
}else{av.close();
}}},_wire:function(){var aq=this,ao=aq.options,ap=aq.target;
aq._showProxy=X(aq._showHandler,aq);
aq._closeProxy=X(aq._closeHandler,aq);
aq._closeTimeoutProxy=X(aq.close,aq);
if(ap[0]){if(B.support.mobileOS&&ao.showOn=="contextmenu"){aq.userEvents=new B.UserEvents(ap,{filter:ao.filter,allowSelection:false});
ap.on(ao.showOn+R+aq._marker,false);
aq.userEvents.bind("hold",aq._showProxy);
}else{if(ao.filter){ap.on(ao.showOn+R+aq._marker,ao.filter,aq._showProxy);
}else{ap.on(ao.showOn+R+aq._marker,aq._showProxy);
}}}},_triggerEvent:function(ap){var ar=this,ao=b(ar.popup.options.anchor)[0],aq=ar._eventOrigin;
ar._eventOrigin=ai;
return ar.trigger(ap.type,s({type:ap.type,item:ap.item||this.element[0],target:ao},aq?{event:aq}:{}));
},_popup:function(){var ao=this;
ao._triggerProxy=X(ao._triggerEvent,ao);
ao.popup=ao.element.addClass("k-context-menu").kendoPopup({anchor:ao.target||"body",copyAnchorStyles:ao.options.copyAnchorStyles,collision:ao.options.popupCollision||"fit",animation:ao.options.animation,activate:ao._triggerProxy,deactivate:ao._triggerProxy}).data("kendoPopup");
ao._targetChild=i(ao.target[0],ao.popup.element[0]);
}});
ah.plugin(I);
ah.plugin(j);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
