(function(b,a){a("kendo.numerictextbox",["kendo.core","kendo.userevents"],b);
}(function(){var a={id:"numerictextbox",name:"NumericTextBox",category:"web",description:"The NumericTextBox widget can format and display numeric, percentage or currency textbox.",depends:["core","userevents"]};
(function(b,K){var t=window.kendo,g=t.caret,u=t.keys,J=t.ui,L=J.Widget,c=t._activeElement,l=t._extractFormat,z=t.parseFloat,A=t.support.placeholder,o=t.getCulture,h="change",j="disabled",D="readonly",r="k-input",F="spin",w=".kendoNumericTextBox",H="touchend",v="mouseleave"+w,q="mouseenter"+w+" "+v,i="k-state-default",n="k-state-focused",p="k-state-hover",m="focus",B=".",E="k-state-selected",G="k-state-disabled",d="aria-disabled",e="aria-readonly",s=/^(-)?(\d*)$/,x=null,C=b.proxy,k=b.extend;
var y=L.extend({init:function(N,R){var T=this,O=R&&R.step!==K,Q,P,S,U,M;
L.fn.init.call(T,N,R);
R=T.options;
N=T.element.on("focusout"+w,C(T._focusout,T)).attr("role","spinbutton");
R.placeholder=R.placeholder||N.attr("placeholder");
T._initialOptions=k({},R);
Q=T.min(N.attr("min"));
P=T.max(N.attr("max"));
S=T._parse(N.attr("step"));
if(R.min===x&&Q!==x){R.min=Q;
}if(R.max===x&&P!==x){R.max=P;
}if(!O&&S!==x){R.step=S;
}T._reset();
T._wrapper();
T._arrows();
T._input();
if(!t.support.mobileOS){T._text.on(m+w,C(T._click,T));
}else{T._text.on(H+w+" "+m+w,function(){if(t.support.browser.edge){T._text.one(m+w,function(){T._toggleText(false);
N.focus();
});
}else{T._toggleText(false);
N.focus();
}});
}N.attr("aria-valuemin",R.min).attr("aria-valuemax",R.max);
R.format=l(R.format);
U=R.value;
T.value(U!==x?U:N.val());
M=N.is("[disabled]")||b(T.element).parents("fieldset").is(":disabled");
if(M){T.enable(false);
}else{T.readonly(N.is("[readonly]"));
}t.notify(T);
},options:{name:"NumericTextBox",decimals:x,restrictDecimals:false,min:x,max:x,value:x,step:1,round:true,culture:"",format:"n",spinners:true,placeholder:"",upArrowText:"Increase value",downArrowText:"Decrease value"},events:[h,F],_editable:function(O){var R=this,N=R.element,M=O.disable,P=O.readonly,Q=R._text.add(N),S=R._inputWrapper.off(q);
R._toggleText(true);
R._upArrowEventHandler.unbind("press");
R._downArrowEventHandler.unbind("press");
N.off("keydown"+w).off("keypress"+w).off("paste"+w);
if(!P&&!M){S.addClass(i).removeClass(G).on(q,R._toggleHover);
Q.removeAttr(j).removeAttr(D).attr(d,false).attr(e,false);
R._upArrowEventHandler.bind("press",function(T){T.preventDefault();
R._spin(1);
R._upArrow.addClass(E);
});
R._downArrowEventHandler.bind("press",function(T){T.preventDefault();
R._spin(-1);
R._downArrow.addClass(E);
});
R.element.on("keydown"+w,C(R._keydown,R)).on("keypress"+w,C(R._keypress,R)).on("paste"+w,C(R._paste,R));
}else{S.addClass(M?G:i).removeClass(M?i:G);
Q.attr(j,M).attr(D,P).attr(d,M).attr(e,P);
}},readonly:function(M){this._editable({readonly:M===K?true:M,disable:false});
},enable:function(M){this._editable({readonly:false,disable:!(M=M===K?true:M)});
},destroy:function(){var M=this;
M.element.add(M._text).add(M._upArrow).add(M._downArrow).add(M._inputWrapper).off(w);
M._upArrowEventHandler.destroy();
M._downArrowEventHandler.destroy();
if(M._form){M._form.off("reset",M._resetHandler);
}L.fn.destroy.call(M);
},min:function(M){return this._option("min",M);
},max:function(M){return this._option("max",M);
},step:function(M){return this._option("step",M);
},value:function(O){var N=this,M;
if(O===K){return N._value;
}O=N._parse(O);
M=N._adjust(O);
if(O!==M){return;
}N._update(O);
N._old=N._value;
},focus:function(){this._focusin();
},_adjust:function(Q){var P=this,O=P.options,N=O.min,M=O.max;
if(Q===x){return Q;
}if(N!==x&&Q<N){Q=N;
}else{if(M!==x&&Q>M){Q=M;
}}return Q;
},_arrows:function(){var R=this,N,M=function(){clearTimeout(R._spinning);
N.removeClass(E);
},P=R.options,Q=P.spinners,O=R.element;
N=O.siblings(".k-icon");
if(!N[0]){N=b(f("increase",P.upArrowText)+f("decrease",P.downArrowText)).insertAfter(O);
N.wrapAll('<span class="k-select"/>');
}if(!Q){N.parent().toggle(Q);
R._inputWrapper.addClass("k-expand-padding");
}R._upArrow=N.eq(0);
R._upArrowEventHandler=new t.UserEvents(R._upArrow,{release:M});
R._downArrow=N.eq(1);
R._downArrowEventHandler=new t.UserEvents(R._downArrow,{release:M});
},_blur:function(){var M=this;
M._toggleText(true);
M._change(M.element.val());
},_click:function(M){var N=this;
clearTimeout(N._focusing);
N._focusing=setTimeout(function(){var U=M.target,T=g(U)[0],W=U.value.substring(0,T),Q=N._format(N.options.format),R=Q[","],V,S,P,O=0;
if(R){S=new RegExp("\\"+R,"g");
P=new RegExp("([\\d\\"+R+"]+)(\\"+Q[B]+")?(\\d+)?");
}if(P){V=P.exec(W);
}if(V){O=V[0].replace(S,"").length;
if(W.indexOf("(")!=-1&&N._value<0){O++;
}}N._focusin();
g(N.element[0],O);
});
},_change:function(N){var M=this;
M._update(N);
N=M._value;
if(M._old!=N){M._old=N;
if(!M._typing){M.element.trigger(h);
}M.trigger(h);
}M._typing=false;
},_culture:function(M){return M||o(this.options.culture);
},_focusin:function(){var M=this;
M._inputWrapper.addClass(n);
M._toggleText(false);
M.element[0].focus();
},_focusout:function(){var M=this;
clearTimeout(M._focusing);
M._inputWrapper.removeClass(n).removeClass(p);
M._blur();
},_format:function(N,M){var O=this._culture(M).numberFormat;
N=N.toLowerCase();
if(N.indexOf("c")>-1){O=O.currency;
}else{if(N.indexOf("p")>-1){O=O.percent;
}}return O;
},_input:function(){var S=this,Q=S.options,N="k-formatted-value",P=S.element.addClass(r).show()[0],M=P.accessKey,T=S.wrapper,R;
R=T.find(B+N);
if(!R[0]){R=b('<input type="text"/>').insertBefore(P).addClass(N);
}try{P.setAttribute("type","text");
}catch(O){P.type="text";
}R[0].tabIndex=P.tabIndex;
R[0].style.cssText=P.style.cssText;
R[0].title=P.title;
R.prop("placeholder",Q.placeholder);
if(M){R.attr("accesskey",M);
P.accessKey="";
}S._text=R.addClass(P.className).attr({role:"spinbutton","aria-valuemin":Q.min,"aria-valuemax":Q.max});
},_keydown:function(M){var O=this,N=M.keyCode;
O._key=N;
if(N==u.DOWN){O._step(-1);
}else{if(N==u.UP){O._step(1);
}else{if(N==u.ENTER){O._change(O.element.val());
}else{O._typing=true;
}}}},_keypress:function(N){if(N.which===0||N.metaKey||N.ctrlKey||N.keyCode===u.BACKSPACE||N.keyCode===u.ENTER){return;
}var W=this;
var R=W.options.min;
var O=W.element;
var T=g(O);
var V=T[0];
var U=T[1];
var M=String.fromCharCode(N.which);
var S=W._format(W.options.format);
var P=W._key===u.NUMPAD_DOT;
var X=O.val();
var Q;
if(P){M=S[B];
}X=X.substring(0,V)+M+X.substring(U);
Q=W._numericRegex(S).test(X);
if(Q&&P){O.val(X);
g(O,V+M.length);
N.preventDefault();
}else{if(R!==null&&R>=0&&X.charAt(0)==="-"||!Q){N.preventDefault();
}}W._key=0;
},_numericRegex:function(N){var Q=this;
var P=N[B];
var O=Q.options.decimals;
var M="*";
if(P===B){P="\\"+P;
}if(O===x){O=N.decimals;
}if(O===0){return s;
}if(Q.options.restrictDecimals){M="{0,"+O+"}";
}if(Q._separator!==P){Q._separator=P;
Q._floatRegExp=new RegExp("^(-)?(((\\d+("+P+"\\d"+M+")?)|("+P+"\\d"+M+")))?$");
}return Q._floatRegExp;
},_paste:function(M){var P=this;
var N=M.target;
var Q=N.value;
var O=P._format(P.options.format);
setTimeout(function(){var S=P._parse(N.value);
var R=P._numericRegex(O).test(N.value);
if(S===x||P._adjust(S)!==S||!R){P._update(Q);
}});
},_option:function(N,Q){var P=this,M=P.element,O=P.options;
if(Q===K){return O[N];
}Q=P._parse(Q);
if(!Q&&N==="step"){return;
}O[N]=Q;
M.add(P._text).attr("aria-value"+N,Q);
M.attr(N,Q);
},_spin:function(M,O){var N=this;
O=O||500;
clearTimeout(N._spinning);
N._spinning=setTimeout(function(){N._spin(M,50);
},O);
N._step(M);
},_step:function(N){var O=this,M=O.element,P=O._parse(M.val())||0;
if(c()!=M[0]){O._focusin();
}P+=O.options.step*N;
O._update(O._adjust(P));
O._typing=false;
O.trigger(F);
},_toggleHover:function(M){b(M.currentTarget).toggleClass(p,M.type==="mouseenter");
},_toggleText:function(N){var M=this;
M._text.toggle(N);
M.element.toggle(!N);
},_parse:function(N,M){return z(N,this._culture(M),this.options.format);
},_round:function(O,M){var N=this.options.round?t._round:I;
return N(O,M);
},_update:function(T){var S=this,R=S.options,O=R.format,N=R.decimals,M=S._culture(),Q=S._format(O,M),P;
if(N===x){N=Q.decimals;
}T=S._parse(T,M);
P=T!==x;
if(P){T=parseFloat(S._round(T,N),10);
}S._value=T=S._adjust(T);
S._placeholder(t.toString(T,O,M));
if(P){T=T.toString();
if(T.indexOf("e")!==-1){T=S._round(+T,N);
}T=T.replace(B,Q[B]);
}else{T="";
}S.element.val(T);
S.element.add(S._text).attr("aria-valuenow",T);
},_placeholder:function(N){var M=this._text;
M.val(N);
if(!A&&!N){M.val(this.options.placeholder);
}M.attr("title",M.attr("title")||M.val());
M.attr("aria-title",M.attr("title")||M.val());
},_wrapper:function(){var O=this,N=O.element,M=N[0],P;
P=N.parents(".k-numerictextbox");
if(!P.is("span.k-numerictextbox")){P=N.hide().wrap('<span class="k-numeric-wrap k-state-default" />').parent();
P=P.wrap("<span/>").parent();
}P[0].style.cssText=M.style.cssText;
M.style.width="";
O.wrapper=P.addClass("k-widget k-numerictextbox").addClass(M.className).css("display","");
O._inputWrapper=b(P[0].firstChild);
},_reset:function(){var P=this,M=P.element,O=M.attr("form"),N=O?b("#"+O):M.closest("form");
if(N[0]){P._resetHandler=function(){setTimeout(function(){P.value(M[0].value);
P.max(P._initialOptions.max);
P.min(P._initialOptions.min);
});
};
P._form=N.on("reset",P._resetHandler);
}}});
function f(N,O){var M="k-i-arrow-"+(N==="increase"?"n":"s");
return'<span unselectable="on" class="k-link k-link-'+N+'" aria-label="'+O+'"><span unselectable="on" class="k-icon '+M+'"></span></span>';
}function I(O,N){var M=parseFloat(O,10).toString().split(B);
if(M[1]){M[1]=M[1].substring(0,N);
}return M.join(B);
}J.plugin(y);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
