(function(b,a){a("util/main",["kendo.core"],b);
}(function(){(function(){var q=Math,n=window.kendo,f=n.deepExtend;
var i=q.PI/180,r=Number.MAX_VALUE,u=-Number.MAX_VALUE,N="undefined";
function g(P){return typeof P!==N;
}function G(R,Q){var P=x(Q);
return q.round(R*P)/P;
}function x(P){if(P){return q.pow(10,P);
}else{return 1;
}}function p(R,Q,P){return q.max(q.min(R,P),Q);
}function y(P){return P*i;
}function h(P){return P/i;
}function l(P){return typeof P==="number"&&!isNaN(P);
}function O(Q,P){return g(Q)?Q:P;
}function K(P){return P*P;
}function w(Q){var R=[];
for(var P in Q){R.push(P+Q[P]);
}return R.sort().join("");
}function j(R){var P=2166136261;
for(var Q=0;
Q<R.length;
++Q){P+=(P<<1)+(P<<4)+(P<<7)+(P<<8)+(P<<24);
P^=R.charCodeAt(Q);
}return P>>>0;
}function k(P){return j(w(P));
}var v=Date.now;
if(!v){v=function(){return new Date().getTime();
};
}function c(P){var R=P.length,Q,T=r,S=u;
for(Q=0;
Q<R;
Q++){S=q.max(S,P[Q]);
T=q.min(T,P[Q]);
}return{min:T,max:S};
}function e(P){return c(P).min;
}function d(P){return c(P).max;
}function J(P){return H(P).min;
}function I(P){return H(P).max;
}function H(P){var T=r,S=u;
for(var Q=0,R=P.length;
Q<R;
Q++){var U=P[Q];
if(U!==null&&isFinite(U)){T=q.min(T,U);
S=q.max(S,U);
}}return{min:T===r?undefined:T,max:S===u?undefined:S};
}function o(P){if(P){return P[P.length-1];
}}function a(P,Q){P.push.apply(P,Q);
return P;
}function E(P){return n.template(P,{useWithBlock:false,paramName:"d"});
}function A(P,Q){return g(Q)&&Q!==null?" "+P+"='"+Q+"' ":"";
}function z(P){var R="";
for(var Q=0;
Q<P.length;
Q++){R+=A(P[Q][0],P[Q][1]);
}return R;
}function D(P){var R="";
for(var Q=0;
Q<P.length;
Q++){var S=P[Q][1];
if(g(S)){R+=P[Q][0]+":"+S+";";
}}if(R!==""){return R;
}}function C(P){if(typeof P!=="string"){P+="px";
}return P;
}function B(R){var S=[];
if(R){var Q=n.toHyphens(R).split("-");
for(var P=0;
P<Q.length;
P++){S.push("k-pos-"+Q[P]);
}}return S.join(" ");
}function m(P){return P===""||P===null||P==="none"||P==="transparent"||!g(P);
}function b(Q){var P={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var S=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var R="";
while(Q>0){if(Q<S[0]){S.shift();
}else{R+=P[S[0]];
Q-=S[0];
}}return R;
}function F(S){S=S.toLowerCase();
var P={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var U=0,R=0;
for(var Q=0;
Q<S.length;
++Q){var T=P[S.charAt(Q)];
if(!T){return null;
}U+=T;
if(T>R){U-=2*R;
}R=T;
}return U;
}function s(Q){var P=Object.create(null);
return function(){var S="";
for(var R=arguments.length;
--R>=0;
){S+=":"+arguments[R];
}if(S in P){return P[S];
}return Q.apply(this,arguments);
};
}function L(T){var S=[],P=0,R=T.length,U,Q;
while(P<R){U=T.charCodeAt(P++);
if(U>=55296&&U<=56319&&P<R){Q=T.charCodeAt(P++);
if((Q&64512)==56320){S.push(((U&1023)<<10)+(Q&1023)+65536);
}else{S.push(U);
P--;
}}else{S.push(U);
}}return S;
}function M(P){return P.map(function(R){var Q="";
if(R>65535){R-=65536;
Q+=String.fromCharCode(R>>>10&1023|55296);
R=56320|R&1023;
}Q+=String.fromCharCode(R);
return Q;
}).join("");
}function t(P,Q){if(P.length<2){return P.slice();
}function R(T,V){var Y=[],U=0,W=0,X=0;
while(U<T.length&&W<V.length){if(Q(T[U],V[W])<=0){Y[X++]=T[U++];
}else{Y[X++]=V[W++];
}}if(U<T.length){Y.push.apply(Y,T.slice(U));
}if(W<V.length){Y.push.apply(Y,V.slice(W));
}return Y;
}return function S(T){if(T.length<=1){return T;
}var V=Math.floor(T.length/2);
var U=T.slice(0,V);
var W=T.slice(V);
U=S(U);
W=S(W);
return R(U,W);
}(P);
}f(n,{util:{MAX_NUM:r,MIN_NUM:u,append:a,arrayLimits:c,arrayMin:e,arrayMax:d,defined:g,deg:h,hashKey:j,hashObject:k,isNumber:l,isTransparent:m,last:o,limitValue:p,now:v,objectKey:w,round:G,rad:y,renderAttr:A,renderAllAttr:z,renderPos:B,renderSize:C,renderStyle:D,renderTemplate:E,sparseArrayLimits:H,sparseArrayMin:J,sparseArrayMax:I,sqr:K,valueOrDefault:O,romanToArabic:F,arabicToRoman:b,memoize:s,ucs2encode:M,ucs2decode:L,mergeSort:t}});
n.drawing.util=n.util;
n.dataviz.util=n.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/core",["kendo.core","util/main"],b);
}(function(){(function(al,M,ai){var x=al.kendo;
var q=!!al.Uint8Array;
var J="\n";
var ah=0;
var b=function(){var ao="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(aB){var ay=aB.replace(/[^A-Za-z0-9\+\/\=]/g,""),ax=0,az=ay.length,aA=[];
while(ax<az){var at=ao.indexOf(ay.charAt(ax++));
var au=ao.indexOf(ay.charAt(ax++));
var av=ao.indexOf(ay.charAt(ax++));
var aw=ao.indexOf(ay.charAt(ax++));
var ap=at<<2|au>>>4;
var aq=(au&15)<<4|av>>>2;
var ar=(av&3)<<6|aw;
aA.push(ap);
if(av!=64){aA.push(aq);
}if(aw!=64){aA.push(ar);
}}return aA;
},encode:function(ap){var ay=0,az=ap.length;
var aA="";
while(ay<az){var aq=ap[ay++];
var ar=ap[ay++];
var at=ap[ay++];
var au=aq>>>2;
var av=(aq&3)<<4|ar>>>4;
var aw=(ar&15)<<2|at>>>6;
var ax=at&63;
if(ay-az==2){aw=ax=64;
}else{if(ay-az==1){ax=64;
}}aA+=ao.charAt(au)+ao.charAt(av)+ao.charAt(aw)+ao.charAt(ax);
}return aA;
}};
}();
var L={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function F(){var ao=0,aq=c();
function ap(){for(var ar=0;
ar<arguments.length;
++ar){var au=arguments[ar];
if(au===ai){throw new Error("Cannot output undefined to PDF");
}else{if(au instanceof ae){au.beforeRender(ap);
au.render(ap);
}else{if(u(au)){af(au,ap);
}else{if(v(au)){ag(au,ap);
}else{if(typeof au=="number"){if(isNaN(au)){throw new Error("Cannot output NaN to PDF");
}var at=au.toFixed(7);
if(at.indexOf(".")>=0){at=at.replace(/\.?0+$/,"");
}if(at=="-0"){at="0";
}aq.writeString(at);
}else{if(/string|boolean/.test(typeof au)){aq.writeString(au+"");
}else{if(typeof au.get=="function"){aq.write(au.get());
}else{if(typeof au=="object"){if(!au){aq.writeString("null");
}else{ap(new P(au));
}}}}}}}}}}}ap.writeData=function(ar){aq.write(ar);
};
ap.withIndent=function(ar){++ao;
ar(ap);
--ao;
};
ap.indent=function(){ap(J,K("",ao*2,"  "));
ap.apply(null,arguments);
};
ap.offset=function(){return aq.offset();
};
ap.toString=function(){throw new Error("FIX CALLER");
};
ap.get=function(){return aq.get();
};
ap.stream=function(){return aq;
};
return ap;
}function am(ar,ap){var ao=ar.beforeRender;
var aq=ar.render;
ar.beforeRender=function(){};
ar.render=function(at){at(ap," 0 R");
};
ar.renderFull=function(at){ar._offset=at.offset();
at(ap," 0 obj ");
ao.call(ar,at);
aq.call(ar,at);
at(" endobj");
};
}function p(ao){if(typeof ao!="function"){var aq=ao;
ao=function(au,at){return au in aq?aq[au]:at;
};
}var ar=ao("paperSize",L.a4);
if(!ar){return{};
}if(typeof ar=="string"){ar=L[ar.toLowerCase()];
if(ar==null){throw new Error("Unknown paper size");
}}ar[0]=aj(ar[0]);
ar[1]=aj(ar[1]);
if(ao("landscape",false)){ar=[Math.max(ar[0],ar[1]),Math.min(ar[0],ar[1])];
}var ap=ao("margin");
if(ap){if(typeof ap=="string"||typeof ap=="number"){ap=aj(ap,0);
ap={left:ap,top:ap,right:ap,bottom:ap};
}else{ap={left:aj(ap.left,0),top:aj(ap.top,0),right:aj(ap.right,0),bottom:aj(ap.bottom,0)};
}if(ao("addMargin")){ar[0]+=ap.left+ap.right;
ar[1]+=ap.top+ap.bottom;
}}return{paperSize:ar,margin:ap};
}function Q(at){var aw=this;
var au=F();
var aq=0;
var ar=[];
function ap(ay,ax){return at&&at[ay]!=null?at[ay]:ax;
}aw.getOption=ap;
aw.attach=function(ax){if(ar.indexOf(ax)<0){am(ax,++aq);
ar.push(ax);
}return ax;
};
aw.pages=[];
aw.FONTS={};
aw.IMAGES={};
aw.GRAD_COL_FUNCTIONS={};
aw.GRAD_OPC_FUNCTIONS={};
aw.GRAD_COL={};
aw.GRAD_OPC={};
var ao=aw.attach(new O());
var av=aw.attach(new X());
ao.setPages(av);
aw.addPage=function(aB){var aD=p(function(aH,aG){return aB&&aB[aH]!=null?aB[aH]:aG;
});
var aE=aD.paperSize;
var aA=aD.margin;
var az=aE[0];
var ay=aE[1];
if(aA){az-=aA.left+aA.right;
ay-=aA.top+aA.bottom;
}var ax=new aa(F(),null,true);
var aF={Contents:aw.attach(ax),Parent:av,MediaBox:[0,0,aE[0],aE[1]]};
var aC=new W(aw,aF);
aC._content=ax;
av.addPage(aw.attach(aC));
aC.transform(1,0,0,-1,0,aE[1]);
if(aA){aC.translate(aA.left,aA.top);
aC.rect(0,0,az,ay);
aC.clip();
}aw.pages.push(aC);
return aC;
};
aw.render=function(){var ax;
au("%PDF-1.4",J,"%базон",J,J);
for(ax=0;
ax<ar.length;
++ax){ar[ax].renderFull(au);
au(J,J);
}var ay=au.offset();
au("xref",J,0," ",ar.length+1,J);
au("0000000000 65535 f ",J);
for(ax=0;
ax<ar.length;
++ax){au(an(ar[ax]._offset,10)," 00000 n ",J);
}au(J);
au("trailer",J);
au(new P({Size:ar.length+1,Root:ao,Info:new P({Producer:new ab(ap("producer","Kendo UI PDF Generator v."+x.version)),Title:new ab(ap("title","")),Author:new ab(ap("author","")),Subject:new ab(ap("subject","")),Keywords:new ab(ap("keywords","")),Creator:new ab(ap("creator","Kendo UI PDF Generator v."+x.version)),CreationDate:ap("date",new Date())})}),J,J);
au("startxref",J,ay,J);
au("%%EOF",J);
return au.stream().offset(0);
};
}var l={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function y(ar,ao){function ap(){if(al.console){if(al.console.error){al.console.error("Cannot load URL: %s",ar);
}else{al.console.log("Cannot load URL: %s",ar);
}}ao(null);
}var aq=new XMLHttpRequest();
aq.open("GET",ar,true);
if(q){aq.responseType="arraybuffer";
}aq.onload=function(){if(aq.status==200||aq.status==304){if(q){ao(new Uint8Array(aq.response));
}else{ao(new VBArray(aq.responseBody).toArray());
}}else{ap();
}};
aq.onerror=ap;
aq.send(null);
}function z(aq,ao){var ap=l[aq];
if(ap){ao(ap);
}else{y(aq,function(ar){if(ar==null){throw new Error("Cannot load font from "+aq);
}else{var at=new x.pdf.TTFFont(ar);
l[aq]=at;
ao(at);
}});
}}var s={};
function B(aw,au){var av=s[aw],at,ar;
if(av){au(av);
}else{av=new Image();
if(!/^data:/i.test(aw)){av.crossOrigin="Anonymous";
}if(q&&!/^data:/i.test(aw)){var ax=new XMLHttpRequest();
ax.onload=function(){ar=ax.response;
at=URL.createObjectURL(ar);
ao(at);
};
ax.onerror=ap;
ax.open("GET",aw,true);
ax.responseType="blob";
ax.send();
}else{ao(aw);
}}function ao(ay){av.src=ay;
if(av.complete&&!x.support.browser.msie){aq();
}else{av.onload=aq;
av.onerror=ap;
}}function ap(){au(s[aw]="TAINTED");
}function aq(){if(ar&&/^image\/jpe?g$/i.test(ar.type)){var aI=new FileReader();
aI.onload=function(){av=new T(av.width,av.height,c(new Uint8Array(this.result)));
URL.revokeObjectURL(at);
au(s[aw]=av);
};
aI.readAsArrayBuffer(ar);
return;
}var aA=document.createElement("canvas");
aA.width=av.width;
aA.height=av.height;
var aB=aA.getContext("2d");
aB.drawImage(av,0,0);
var aG;
try{aG=aB.getImageData(0,0,av.width,av.height);
}catch(aD){return ap();
}finally{if(at){URL.revokeObjectURL(at);
}}var aE=false,aJ=c(),az=c();
var aH=aG.data;
var aF=0;
while(aF<aH.length){aJ.writeByte(aH[aF++]);
aJ.writeByte(aH[aF++]);
aJ.writeByte(aH[aF++]);
var ay=aH[aF++];
if(ay<255){aE=true;
}az.writeByte(ay);
}if(aE){av=new Y(av.width,av.height,aJ,az);
}else{var aC=aA.toDataURL("image/jpeg");
aC=aC.substr(aC.indexOf(";base64,")+8);
var aK=c();
aK.writeBase64(aC);
aK.offset(0);
av=new T(av.width,av.height,aK);
}au(s[aw]=av);
}}function G(ao){return function(at,ap){var ar=at.length,aq=ar;
if(ar===0){return ap();
}while(aq-->0){ao(at[aq],function(){if(--ar===0){ap();
}});
}};
}var A=G(z);
var C=G(B);
Q.prototype={loadFonts:A,loadImages:C,getFont:function(ap){var ao=this.FONTS[ap];
if(!ao){ao=l[ap];
if(!ao){throw new Error("Font "+ap+" has not been loaded");
}if(ao===true){ao=this.attach(new Z(ap));
}else{ao=this.attach(new R(this,ao));
}this.FONTS[ap]=ao;
}return ao;
},getImage:function(ap){var ao=this.IMAGES[ap];
if(!ao){ao=s[ap];
if(!ao){throw new Error("Image "+ap+" has not been loaded");
}if(ao==="TAINTED"){return null;
}ao=this.IMAGES[ap]=this.attach(ao.asStream(this));
}return ao;
},getOpacityGS:function(at,ap){var ar=M(at).toFixed(3);
at=M(ar);
ar+=ap?"S":"F";
var ao=this._opacityGSCache||(this._opacityGSCache={});
var aq=ao[ar];
if(!aq){var au={Type:a("ExtGState")};
if(ap){au.CA=at;
}else{au.ca=at;
}aq=this.attach(new P(au));
aq._resourceName=a("GS"+ ++ah);
ao[ar]=aq;
}return aq;
},dict:function(ao){return new P(ao);
},name:function(ao){return a(ao);
},stream:function(ap,ao){return new aa(ao,ap);
}};
function K(aq,ap,ao){while(aq.length<ap){aq=ao+aq;
}return aq;
}function an(ap,ao){return K(ap+"",ao,"0");
}function r(ap,ao){return Object.prototype.hasOwnProperty.call(ap,ao);
}var u=Array.isArray||function(ao){return ao instanceof Array;
};
function v(ao){return ao instanceof Date;
}function af(ao,ap){ap("[");
if(ao.length>0){ap.withIndent(function(){for(var aq=0;
aq<ao.length;
++aq){if(aq>0&&aq%8===0){ap.indent(ao[aq]);
}else{ap(" ",ao[aq]);
}}});
}ap(" ]");
}function ag(ao,ap){ap("(D:",an(ao.getUTCFullYear(),4),an(ao.getUTCMonth()+1,2),an(ao.getUTCDate(),2),an(ao.getUTCHours(),2),an(ao.getUTCMinutes(),2),an(ao.getUTCSeconds(),2),"Z)");
}function H(ao){return ao*(72/25.4);
}function i(ao){return H(ao*10);
}function t(ao){return ao*72;
}function aj(ar,ao){if(typeof ar=="number"){return ar;
}if(typeof ar=="string"){var ap;
ap=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(ar);
if(ap){var aq=M(ap[1]);
if(!isNaN(aq)){if(ap[2]=="pt"){return aq;
}return{mm:H,cm:i,"in":t}[ap[2]](aq);
}}}if(ao!=null){return ao;
}throw new Error("Can't parse unit: "+ar);
}function ae(){}ae.prototype.beforeRender=function(){};
function j(ap,ar,ao){if(!ao){ao=ae;
}ap.prototype=new ao();
for(var aq in ar){if(r(ar,aq)){ap.prototype[aq]=ar[aq];
}}return ap;
}var ab=j(function ab(ao){this.value=ao;
},{render:function(aq){var ar="",ao=this.escape();
for(var ap=0;
ap<ao.length;
++ap){ar+=String.fromCharCode(ao.charCodeAt(ap)&255);
}aq("(",ar,")");
},escape:function(){return this.value.replace(/([\(\)\\])/g,"\\$1");
},toString:function(){return this.value;
}});
var S=j(function S(ao){this.value=ao;
},{render:function(ap){ap("<");
for(var ao=0;
ao<this.value.length;
++ao){ap(an(this.value.charCodeAt(ao).toString(16),4));
}ap(">");
}},ab);
var U=j(function U(ao){this.name=ao;
},{render:function(ao){ao("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(ao){return"#"+an(ao.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var V={};
U.get=a;
function a(ao){if(r(V,ao)){return V[ao];
}return V[ao]=new U(ao);
}var P=j(function P(ao){this.props=ao;
},{render:function(ap){var aq=this.props,ao=true;
ap("<<");
ap.withIndent(function(){for(var ar in aq){if(r(aq,ar)&&!/^_/.test(ar)){ao=false;
ap.indent(a(ar)," ",aq[ar]);
}}});
if(!ao){ap.indent();
}ap(">>");
}});
var aa=j(function aa(ap,aq,ao){if(typeof ap=="string"){var ar=c();
ar.write(ap);
ap=ar;
}this.data=ap;
this.props=aq||{};
this.compress=ao;
},{render:function(ap){var ao=this.data.get(),aq=this.props;
if(this.compress&&al.pako&&typeof al.pako.deflate=="function"){if(!aq.Filter){aq.Filter=[];
}else{if(!(aq.Filter instanceof Array)){aq.Filter=[aq.Filter];
}}aq.Filter.unshift(a("FlateDecode"));
ao=al.pako.deflate(ao);
}aq.Length=ao.length;
ap(new P(aq)," stream",J);
ap.writeData(ao);
ap(J,"endstream");
}});
var O=j(function O(ao){ao=this.props=ao||{};
ao.Type=a("Catalog");
},{setPages:function(ao){this.props.Pages=ao;
}},P);
var X=j(function X(){this.props={Type:a("Pages"),Kids:[],Count:0};
},{addPage:function(ao){this.props.Kids.push(ao);
this.props.Count++;
}},P);
function T(aq,ap,ao){this.asStream=function(){var ar=new aa(ao,{Type:a("XObject"),Subtype:a("Image"),Width:aq,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),Filter:a("DCTDecode")});
ar._resourceName=a("I"+ ++ah);
return ar;
};
}function Y(ar,ap,aq,ao){this.asStream=function(au){var at=new aa(ao,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceGray")},true);
var av=new aa(aq,{Type:a("XObject"),Subtype:a("Image"),Width:ar,Height:ap,BitsPerComponent:8,ColorSpace:a("DeviceRGB"),SMask:au.attach(at)},true);
av._resourceName=a("I"+ ++ah);
return av;
};
}var Z=j(function Z(ao){this.props={Type:a("Font"),Subtype:a("Type1"),BaseFont:a(ao)};
this._resourceName=a("F"+ ++ah);
},{encodeText:function(ao){return new ab(ao+"");
}},P);
var R=j(function R(aq,ao,ar){ar=this.props=ar||{};
ar.Type=a("Font");
ar.Subtype=a("Type0");
ar.Encoding=a("Identity-H");
this._pdf=aq;
this._font=ao;
this._sub=ao.makeSubset();
this._resourceName=a("F"+ ++ah);
var ap=ao.head;
this.name=ao.psName;
var at=this.scale=ao.scale;
this.bbox=[ap.xMin*at,ap.yMin*at,ap.xMax*at,ap.yMax*at];
this.italicAngle=ao.post.italicAngle;
this.ascent=ao.ascent*at;
this.descent=ao.descent*at;
this.lineGap=ao.lineGap*at;
this.capHeight=ao.os2.capHeight||this.ascent;
this.xHeight=ao.os2.xHeight||0;
this.stemV=0;
this.familyClass=(ao.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=(ao.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|1<<5;
},{encodeText:function(ao){return new S(this._sub.encodeText(ao+""));
},getTextWidth:function(ap,at){var au=0,ao=this._font.cmap.codeMap;
for(var ar=0;
ar<at.length;
++ar){var aq=ao[at.charCodeAt(ar)];
au+=this._font.widthOfGlyph(aq||0);
}return au*ap/1000;
},beforeRender:function(){var az=this;
var aA=az._sub;
var aq=aA.render();
var aw=new aa(c(aq),{Length1:aq.length},true);
var at=az._pdf.attach(new P({Type:a("FontDescriptor"),FontName:a(az._sub.psName),FontBBox:az.bbox,Flags:az.flags,StemV:az.stemV,ItalicAngle:az.italicAngle,Ascent:az.ascent,Descent:az.descent,CapHeight:az.capHeight,XHeight:az.xHeight,FontFile2:az._pdf.attach(aw)}));
var ap=aA.ncid2ogid;
var av=aA.firstChar;
var ax=aA.lastChar;
var ao=[];
(function ay(aF,aD){if(aF<=ax){var aE=ap[aF];
if(aE==null){ay(aF+1);
}else{if(!aD){ao.push(aF,aD=[]);
}aD.push(az._font.widthOfGlyph(aE));
ay(aF+1,aD);
}}}(av));
var ar=new P({Type:a("Font"),Subtype:a("CIDFontType2"),BaseFont:a(az._sub.psName),CIDSystemInfo:new P({Registry:new ab("Adobe"),Ordering:new ab("Identity"),Supplement:0}),FontDescriptor:at,FirstChar:av,LastChar:ax,DW:Math.round(az._font.widthOfGlyph(0)),W:ao,CIDToGIDMap:az._pdf.attach(az._makeCidToGidMap())});
var au=az.props;
au.BaseFont=a(az._sub.psName);
au.DescendantFonts=[az._pdf.attach(ar)];
var aB=new ac(av,ax,aA.subset);
var aC=new aa(F(),null,true);
aC.data(aB);
au.ToUnicode=az._pdf.attach(aC);
},_makeCidToGidMap:function(){return new aa(c(this._sub.cidToGidMap()),null,true);
}},P);
var ac=j(function ad(ao,ap,aq){this.firstChar=ao;
this.lastChar=ap;
this.map=aq;
},{render:function(ao){ao.indent("/CIDInit /ProcSet findresource begin");
ao.indent("12 dict begin");
ao.indent("begincmap");
ao.indent("/CIDSystemInfo <<");
ao.indent("  /Registry (Adobe)");
ao.indent("  /Ordering (UCS)");
ao.indent("  /Supplement 0");
ao.indent(">> def");
ao.indent("/CMapName /Adobe-Identity-UCS def");
ao.indent("/CMapType 2 def");
ao.indent("1 begincodespacerange");
ao.indent("  <0000><ffff>");
ao.indent("endcodespacerange");
var ap=this;
ao.indent(ap.lastChar-ap.firstChar+1," beginbfchar");
ao.withIndent(function(){for(var aq=ap.firstChar;
aq<=ap.lastChar;
++aq){var au=ap.map[aq];
var at=x.util.ucs2encode([au]);
ao.indent("<",an(aq.toString(16),4),">","<");
for(var ar=0;
ar<at.length;
++ar){ao(an(at.charCodeAt(ar).toString(16),4));
}ao(">");
}});
ao.indent("endbfchar");
ao.indent("endcmap");
ao.indent("CMapName currentdict /CMap defineresource pop");
ao.indent("end");
ao.indent("end");
}});
function E(ao){return ao.map(function(ap){return u(ap)?E(ap):typeof ap=="number"?(Math.round(ap*1000)/1000).toFixed(3):ap;
}).join(" ");
}function e(av,aw,ar,ao,ax,at,ap){var au=E([aw,ar,ao,ax,at,ap]);
var aq=av.GRAD_COL_FUNCTIONS[au];
if(!aq){aq=av.GRAD_COL_FUNCTIONS[au]=av.attach(new P({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[aw,ar,ao],C1:[ax,at,ap]}));
}return aq;
}function h(at,ao,ap){var ar=E([ao,ap]);
var aq=at.GRAD_OPC_FUNCTIONS[ar];
if(!aq){aq=at.GRAD_OPC_FUNCTIONS[ar]=at.attach(new P({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[ao],C1:[ap]}));
}return aq;
}function D(ay,aB){var au=false;
var ax=[];
var ap=[];
var aw=[];
var at=[];
var av,az,aq,aA,ar;
for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ap.push(e(ay,aA.r,aA.g,aA.b,ar.r,ar.g,ar.b));
if(aA.a<1||ar.a<1){au=true;
}aw.push(aq.offset);
at.push(0,1);
}if(au){for(av=1;
av<aB.length;
++av){az=aB[av-1];
aq=aB[av];
aA=az.color;
ar=aq.color;
ax.push(h(ay,aA.a,ar.a));
}}aw.pop();
return{hasAlpha:au,colors:ao(ap),opacities:au?ao(ax):null};
function ao(aC){if(aC.length==1){return aC[0];
}return{FunctionType:3,Functions:aC,Domain:[0,1],Bounds:aw,Encode:at};
}}function d(av,au,ax,aq,ar,ap){var aw,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.r,ay.color.g,ay.color.b);
});
at=E(ao);
aw=av.GRAD_COL[at];
}if(!aw){aw=new P({Type:a("Shading"),ShadingType:au?3:2,ColorSpace:a("DeviceRGB"),Coords:aq,Domain:[0,1],Function:ar,Extend:[true,true]});
av.attach(aw);
aw._resourceName="S"+ ++ah;
if(at){av.GRAD_COL[at]=aw;
}}return aw;
}function g(aw,au,ax,aq,ar,ap){var av,at;
if(!ap){var ao=[au].concat(aq);
ax.forEach(function(ay){ao.push(ay.offset,ay.color.a);
});
at=E(ao);
av=aw.GRAD_OPC[at];
}if(!av){av=new P({Type:a("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:a("Mask"),S:a("Luminosity"),G:aw.attach(new aa("/a0 gs /s0 sh",{Type:a("XObject"),Subtype:a("Form"),FormType:1,BBox:ap?[ap.left,ap.top+ap.height,ap.left+ap.width,ap.top]:[0,1,1,0],Group:{Type:a("Group"),S:a("Transparency"),CS:a("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:a("DeviceGray"),Coords:aq,Domain:[0,1],ShadingType:au?3:2,Function:ar,Extend:[true,true]}}}}))}});
aw.attach(av);
av._resourceName="O"+ ++ah;
if(at){aw.GRAD_OPC[at]=av;
}}return av;
}function f(av,ar,ao){var at=ar.type=="radial";
var aq=D(av,ar.stops);
var ap=at?[ar.start.x,ar.start.y,ar.start.r,ar.end.x,ar.end.y,ar.end.r]:[ar.start.x,ar.start.y,ar.end.x,ar.end.y];
var aw=d(av,at,ar.stops,ap,aq.colors,ar.userSpace&&ao);
var au=aq.hasAlpha?g(av,at,ar.stops,ap,aq.opacities,ar.userSpace&&ao):null;
return{hasAlpha:aq.hasAlpha,shading:aw,opacity:au};
}var W=j(function W(ao,ap){this._pdf=ao;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
ap=this.props=ap||{};
ap.Type=a("Page");
ap.ProcSet=[a("PDF"),a("Text"),a("ImageB"),a("ImageC"),a("ImageI")];
ap.Resources=new P({Font:new P(this._fontResources),ExtGState:new P(this._gsResources),XObject:new P(this._xResources),Pattern:new P(this._patResources),Shading:new P(this._shResources)});
ap.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(ao,ap,aq,ar,at,au){if(!w(arguments)){this._matrix=I(arguments,this._matrix);
this._out(ao," ",ap," ",aq," ",ar," ",at," ",au," cm");
this._out(J);
}},translate:function(ao,ap){this.transform(1,0,0,1,ao,ap);
},scale:function(ao,ap){this.transform(ao,0,0,ap,0,0);
},rotate:function(ao){var ap=Math.cos(ao),aq=Math.sin(ao);
this.transform(ap,aq,-aq,ap,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",J);
},endText:function(){this._textMode=false;
this._out("ET",J);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(ao,ap){this._requireTextMode();
if(ao==null){ao=this._font;
}else{if(!(ao instanceof R)){ao=this._pdf.getFont(ao);
}}if(ap==null){ap=this._fontSize;
}this._fontResources[ao._resourceName]=ao;
this._font=ao;
this._fontSize=ap;
this._out(ao._resourceName," ",ap," Tf",J);
},setTextLeading:function(ao){this._requireTextMode();
this._out(ao," TL",J);
},setTextRenderingMode:function(ao){this._requireTextMode();
this._out(ao," Tr",J);
},showText:function(ar,ap){this._requireFont();
if(ar.length>1&&ap&&this._font instanceof R){var ao=this._font.getTextWidth(this._fontSize,ar);
var aq=ap/ao*100;
this._out(aq," Tz ");
}this._out(this._font.encodeText(ar)," Tj",J);
},showTextNL:function(ao){this._requireFont();
this._out(this._font.encodeText(ao)," '",J);
},addLink:function(ar,ao){var ap=this._toPage({x:ao.left,y:ao.bottom});
var aq=this._toPage({x:ao.right,y:ao.top});
this._annotations.push(new P({Type:a("Annot"),Subtype:a("Link"),Rect:[ap.x,ap.y,aq.x,aq.y],Border:[0,0,0],A:new P({Type:a("Action"),S:a("URI"),URI:new ab(ar)})}));
},setStrokeColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," RG",J);
},setOpacity:function(ao){this.setFillOpacity(ao);
this.setStrokeOpacity(ao);
this._opacity*=ao;
},setStrokeOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,true);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",J);
}},setFillColor:function(aq,ap,ao){this._out(aq," ",ap," ",ao," rg",J);
},setFillOpacity:function(ap){if(ap<1){var ao=this._pdf.getOpacityGS(this._opacity*ap,false);
this._gsResources[ao._resourceName]=ao;
this._out(ao._resourceName," gs",J);
}},gradient:function(aq,ao){this.save();
this.rect(ao.left,ao.top,ao.width,ao.height);
this.clip();
if(!aq.userSpace){this.transform(ao.width,0,0,ao.height,ao.left,ao.top);
}var ap=f(this._pdf,aq,ao);
var at=ap.shading._resourceName,ar;
this._shResources[at]=ap.shading;
if(ap.hasAlpha){ar=ap.opacity._resourceName;
this._gsResources[ar]=ap.opacity;
this._out("/"+ar+" gs ");
}this._out("/"+at+" sh",J);
this.restore();
},setDashPattern:function(ao,ap){this._out(ao," ",ap," d",J);
},setLineWidth:function(ao){this._out(ao," w",J);
},setLineCap:function(ao){this._out(ao," J",J);
},setLineJoin:function(ao){this._out(ao," j",J);
},setMitterLimit:function(ao){this._out(ao," M",J);
},save:function(){this._contextStack.push(this._context());
this._out("q",J);
},restore:function(){this._out("Q",J);
this._context(this._contextStack.pop());
},moveTo:function(ao,ap){this._out(ao," ",ap," m",J);
},lineTo:function(ao,ap){this._out(ao," ",ap," l",J);
},bezier:function(ao,ar,ap,at,aq,au){this._out(ao," ",ar," ",ap," ",at," ",aq," ",au," c",J);
},bezier1:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," y",J);
},bezier2:function(ao,aq,ap,ar){this._out(ao," ",aq," ",ap," ",ar," v",J);
},close:function(){this._out("h",J);
},rect:function(aq,ar,ap,ao){this._out(aq," ",ar," ",ap," ",ao," re",J);
},ellipse:function(au,av,ar,at){function ao(aw){return au+aw;
}function ap(aw){return av+aw;
}var aq=0.5522847498307936;
this.moveTo(ao(0),ap(at));
this.bezier(ao(ar*aq),ap(at),ao(ar),ap(at*aq),ao(ar),ap(0));
this.bezier(ao(ar),ap(-at*aq),ao(ar*aq),ap(-at),ao(0),ap(-at));
this.bezier(ao(-ar*aq),ap(-at),ao(-ar),ap(-at*aq),ao(-ar),ap(0));
this.bezier(ao(-ar),ap(at*aq),ao(-ar*aq),ap(at),ao(0),ap(at));
},circle:function(ap,aq,ao){this.ellipse(ap,aq,ao,ao);
},stroke:function(){this._out("S",J);
},nop:function(){this._out("n",J);
},clip:function(){this._out("W n",J);
},clipStroke:function(){this._out("W S",J);
},closeStroke:function(){this._out("s",J);
},fill:function(){this._out("f",J);
},fillStroke:function(){this._out("B",J);
},drawImage:function(ap){var ao=this._pdf.getImage(ap);
if(ao){this._xResources[ao._resourceName]=ao;
this._out(ao._resourceName," Do",J);
}},comment:function(ap){var ao=this;
ap.split(/\r?\n/g).forEach(function(aq){ao._out("% ",aq,J);
});
},_context:function(ao){if(ao!=null){this._opacity=ao.opacity;
this._matrix=ao.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(aw){var av=this._matrix;
var ao=av[0],ap=av[1],aq=av[2],ar=av[3],at=av[4],au=av[5];
return{x:ao*aw.x+aq*aw.y+at,y:ap*aw.x+ar*aw.y+au};
}},P);
function c(ao){var au=0,at=0;
if(ao==null){ao=q?new Uint8Array(256):[];
}else{at=ao.length;
}var ap=q?function(aQ){if(aQ>=ao.length){var aR=new Uint8Array(Math.max(aQ+256,ao.length*2));
aR.set(ao,0);
ao=aR;
}}:function(){};
var ar=q?function(){return new Uint8Array(ao.buffer,0,at);
}:function(){return ao;
};
var aH=q?function(aQ){if(typeof aQ=="string"){return aP(aQ);
}var aR=aQ.length;
ap(au+aR);
ao.set(aQ,au);
au+=aR;
if(au>at){at=au;
}}:function(aQ){if(typeof aQ=="string"){return aP(aQ);
}for(var aR=0;
aR<aQ.length;
++aR){aI(aQ[aR]);
}};
var aE=q?function(aR,aQ){if(ao.buffer.slice){return new Uint8Array(ao.buffer.slice(aR,aR+aQ));
}else{var aS=new Uint8Array(aQ);
aS.set(new Uint8Array(ao.buffer,aR,aQ));
return aS;
}}:function(aR,aQ){return ao.slice(aR,aR+aQ);
};
function aq(){return au>=at;
}function aw(){return au<at?ao[au++]:0;
}function aI(aQ){ap(au);
ao[au++]=aQ&255;
if(au>at){at=au;
}}function aB(){return aw()<<8|aw();
}function aN(aQ){aI(aQ>>8);
aI(aQ);
}function aC(){var aQ=aB();
return aQ>=32768?aQ-65536:aQ;
}function aO(aQ){aN(aQ<0?aQ+65536:aQ);
}function az(){return aB()*65536+aB();
}function aL(aQ){aN(aQ>>>16&65535);
aN(aQ&65535);
}function aA(){var aQ=az();
return aQ>=2147483648?aQ-4294967296:aQ;
}function aM(aQ){aL(aQ<0?aQ+4294967296:aQ);
}function ax(){return az()/65536;
}function aJ(aQ){aL(Math.round(aQ*65536));
}function ay(){return aA()/65536;
}function aK(aQ){aM(Math.round(aQ*65536));
}function av(aQ){return aG(aQ,aw);
}function aD(aQ){return String.fromCharCode.apply(String,av(aQ));
}function aP(aR){for(var aQ=0;
aQ<aR.length;
++aQ){aI(aR.charCodeAt(aQ));
}}function aG(aR,aS){for(var aT=new Array(aR),aQ=0;
aQ<aR;
++aQ){aT[aQ]=aS();
}return aT;
}var aF={eof:aq,readByte:aw,writeByte:aI,readShort:aB,writeShort:aN,readLong:az,writeLong:aL,readFixed:ax,writeFixed:aJ,readShort_:aC,writeShort_:aO,readLong_:aA,writeLong_:aM,readFixed_:ay,writeFixed_:aK,read:av,write:aH,readString:aD,writeString:aP,times:aG,get:ar,slice:aE,offset:function(aQ){if(aQ!=null){au=aQ;
return aF;
}return au;
},skip:function(aQ){au+=aQ;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return at;
},saveExcursion:function(aQ){var aR=au;
try{return aQ();
}finally{au=aR;
}},writeBase64:function(aQ){if(al.atob){aP(al.atob(aQ));
}else{aH(b.decode(aQ));
}},base64:function(){return b.encode(ar());
}};
return aF;
}function ak(ao){return ao.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function N(ao){var ar=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var aq=ar.exec(ao);
if(!aq){return{fontSize:12,fontFamily:"sans-serif"};
}var ap=aq[8]?parseInt(aq[8],10):12;
return{italic:aq[2]&&aq[2].toLowerCase()=="italic",variant:aq[4],bold:aq[6]&&/bold|700/i.test(aq[6]),fontSize:ap,lineHeight:aq[12]?aq[12]=="normal"?ap:parseInt(aq[12],10):null,fontFamily:aq[14].split(/\s*,\s*/g).map(ak)};
}function o(at){function aq(av){if(at.bold){av+="|bold";
}if(at.italic){av+="|italic";
}return av.toLowerCase();
}var ao=at.fontFamily;
var ar,au;
if(ao instanceof Array){for(var ap=0;
ap<ao.length;
++ap){ar=aq(ao[ap]);
au=m[ar];
if(au){break;
}}}else{au=m[ao.toLowerCase()];
}while(typeof au=="function"){au=au();
}if(!au){au="Times-Roman";
}return au;
}var m={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function n(ao,ap){ao=ao.toLowerCase();
m[ao]=function(){return m[ap];
};
m[ao+"|bold"]=function(){return m[ap+"|bold"];
};
m[ao+"|italic"]=function(){return m[ap+"|italic"];
};
m[ao+"|bold|italic"]=function(){return m[ap+"|bold|italic"];
};
}n("Times New Roman","serif");
n("Courier New","monospace");
n("Arial","sans-serif");
n("Helvetica","sans-serif");
n("Verdana","sans-serif");
n("Tahoma","sans-serif");
n("Georgia","sans-serif");
n("Monaco","monospace");
n("Andale Mono","monospace");
function k(ap,aq){if(arguments.length==1){for(var ao in ap){if(r(ap,ao)){k(ao,ap[ao]);
}}}else{ap=ap.toLowerCase();
m[ap]=aq;
switch(ap){case"dejavu sans":m["sans-serif"]=aq;
break;
case"dejavu sans|bold":m["sans-serif|bold"]=aq;
break;
case"dejavu sans|italic":m["sans-serif|italic"]=aq;
break;
case"dejavu sans|bold|italic":m["sans-serif|bold|italic"]=aq;
break;
case"dejavu serif":m.serif=aq;
break;
case"dejavu serif|bold":m["serif|bold"]=aq;
break;
case"dejavu serif|italic":m["serif|italic"]=aq;
break;
case"dejavu serif|bold|italic":m["serif|bold|italic"]=aq;
break;
case"dejavu mono":m.monospace=aq;
break;
case"dejavu mono|bold":m["monospace|bold"]=aq;
break;
case"dejavu mono|italic":m["monospace|italic"]=aq;
break;
case"dejavu mono|bold|italic":m["monospace|bold|italic"]=aq;
break;
}}}x.pdf={Document:Q,BinaryStream:c,defineFont:k,parseFontDef:N,getFontURL:o,loadFonts:A,loadImages:C,getPaperOptions:p,TEXT_RENDERING_MODE:{fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7}};
function I(ao,ar){var ap=ao[0],at=ao[1],av=ao[2],ax=ao[3],az=ao[4],aB=ao[5];
var aq=ar[0],au=ar[1],aw=ar[2],ay=ar[3],aA=ar[4],aC=ar[5];
return[ap*aq+at*aw,ap*au+at*ay,av*aq+ax*aw,av*au+ax*ay,az*aq+aB*aw+aA,az*au+aB*ay+aC];
}function w(ao){return ao[0]===1&&ao[1]===0&&ao[2]===0&&ao[3]===1&&ao[4]===0&&ao[5]===0;
}}(window,parseFloat));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/ttf",["pdf/core","util/main"],b);
}(function(){(function(u){function f(w,v){return Object.prototype.hasOwnProperty.call(w,v);
}function q(v){return Object.keys(v).sort(function(w,x){return w-x;
}).map(parseFloat);
}var o=u.kendo.pdf;
var a=o.BinaryStream;
function d(v){this.raw=v;
this.scalerType=v.readLong();
this.tableCount=v.readShort();
this.searchRange=v.readShort();
this.entrySelector=v.readShort();
this.rangeShift=v.readShort();
var y=this.tables={};
for(var x=0;
x<this.tableCount;
++x){var w={tag:v.readString(4),checksum:v.readLong(),offset:v.readLong(),length:v.readLong()};
y[w.tag]=w;
}}d.prototype={readTable:function(x,v){var w=this.tables[x];
if(!w){throw new Error("Table "+x+" not found in directory");
}return this[x]=w.table=new v(this,w);
},render:function(I){var G=Object.keys(I).length;
var z=Math.pow(2,Math.floor(Math.log(G)/Math.LN2));
var D=z*16;
var x=Math.floor(Math.log(z)/Math.LN2);
var C=G*16-D;
var B=a();
B.writeLong(this.scalerType);
B.writeShort(G);
B.writeShort(D);
B.writeShort(x);
B.writeShort(C);
var w=G*16;
var A=B.offset()+w;
var y=null;
var H=a();
for(var J in I){if(f(I,J)){var F=I[J];
B.writeString(J);
B.writeLong(this.checksum(F));
B.writeLong(A);
B.writeLong(F.length);
H.write(F);
if(J=="head"){y=A;
}A+=F.length;
while(A%4){H.writeByte(0);
A++;
}}}B.write(H.get());
var E=this.checksum(B.get());
var v=2981146554-E;
B.offset(y+8);
B.writeLong(v);
return B.get();
},checksum:function(v){v=a(v);
var w=0;
while(!v.eof()){w+=v.readLong();
}return w&4294967295;
}};
function c(x){function v(z,y){this.definition=y;
this.length=y.length;
this.offset=y.offset;
this.file=z;
this.rawData=z.raw;
this.parse(z.raw);
}v.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var w in x){if(f(x,w)){v[w]=v.prototype[w]=x[w];
}}return v;
}var g=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.revision=v.readLong();
this.checkSumAdjustment=v.readLong();
this.magicNumber=v.readLong();
this.flags=v.readShort();
this.unitsPerEm=v.readShort();
this.created=v.read(8);
this.modified=v.read(8);
this.xMin=v.readShort_();
this.yMin=v.readShort_();
this.xMax=v.readShort_();
this.yMax=v.readShort_();
this.macStyle=v.readShort();
this.lowestRecPPEM=v.readShort();
this.fontDirectionHint=v.readShort_();
this.indexToLocFormat=v.readShort_();
this.glyphDataFormat=v.readShort_();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeLong(this.revision);
w.writeLong(0);
w.writeLong(this.magicNumber);
w.writeShort(this.flags);
w.writeShort(this.unitsPerEm);
w.write(this.created);
w.write(this.modified);
w.writeShort_(this.xMin);
w.writeShort_(this.yMin);
w.writeShort_(this.xMax);
w.writeShort_(this.yMax);
w.writeShort(this.macStyle);
w.writeShort(this.lowestRecPPEM);
w.writeShort_(this.fontDirectionHint);
w.writeShort_(v);
w.writeShort_(this.glyphDataFormat);
return w.get();
}});
var j=c({parse:function(v){v.offset(this.offset);
var w=this.file.head.indexToLocFormat;
if(w===0){this.offsets=v.times(this.length/2,function(){return 2*v.readShort();
});
}else{this.offsets=v.times(this.length/4,v.readLong);
}},offsetOf:function(v){return this.offsets[v];
},lengthOf:function(v){return this.offsets[v+1]-this.offsets[v];
},render:function(x){var y=a();
var w=x[x.length-1]>65535;
for(var v=0;
v<x.length;
++v){if(w){y.writeLong(x[v]);
}else{y.writeShort(x[v]/2);
}}return{format:w?1:0,table:y.get()};
}});
var h=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.advanceWidthMax=v.readShort();
this.minLeftSideBearing=v.readShort_();
this.minRightSideBearing=v.readShort_();
this.xMaxExtent=v.readShort_();
this.caretSlopeRise=v.readShort_();
this.caretSlopeRun=v.readShort_();
this.caretOffset=v.readShort_();
v.skip(4*2);
this.metricDataFormat=v.readShort_();
this.numOfLongHorMetrics=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort_(this.ascent);
w.writeShort_(this.descent);
w.writeShort_(this.lineGap);
w.writeShort(this.advanceWidthMax);
w.writeShort_(this.minLeftSideBearing);
w.writeShort_(this.minRightSideBearing);
w.writeShort_(this.xMaxExtent);
w.writeShort_(this.caretSlopeRise);
w.writeShort_(this.caretSlopeRun);
w.writeShort_(this.caretOffset);
w.write([0,0,0,0,0,0,0,0]);
w.writeShort_(this.metricDataFormat);
w.writeShort(v.length);
return w.get();
}});
var k=c({parse:function(v){v.offset(this.offset);
this.version=v.readLong();
this.numGlyphs=v.readShort();
this.maxPoints=v.readShort();
this.maxContours=v.readShort();
this.maxComponentPoints=v.readShort();
this.maxComponentContours=v.readShort();
this.maxZones=v.readShort();
this.maxTwilightPoints=v.readShort();
this.maxStorage=v.readShort();
this.maxFunctionDefs=v.readShort();
this.maxInstructionDefs=v.readShort();
this.maxStackElements=v.readShort();
this.maxSizeOfInstructions=v.readShort();
this.maxComponentElements=v.readShort();
this.maxComponentDepth=v.readShort();
},render:function(v){var w=a();
w.writeLong(this.version);
w.writeShort(v.length);
w.writeShort(this.maxPoints);
w.writeShort(this.maxContours);
w.writeShort(this.maxComponentPoints);
w.writeShort(this.maxComponentContours);
w.writeShort(this.maxZones);
w.writeShort(this.maxTwilightPoints);
w.writeShort(this.maxStorage);
w.writeShort(this.maxFunctionDefs);
w.writeShort(this.maxInstructionDefs);
w.writeShort(this.maxStackElements);
w.writeShort(this.maxSizeOfInstructions);
w.writeShort(this.maxComponentElements);
w.writeShort(this.maxComponentDepth);
return w.get();
}});
var i=c({parse:function(v){v.offset(this.offset);
var w=this.file,x=w.hhea;
this.metrics=v.times(x.numOfLongHorMetrics,function(){return{advance:v.readShort(),lsb:v.readShort_()};
});
var y=w.maxp.numGlyphs-w.hhea.numOfLongHorMetrics;
this.leftSideBearings=v.times(y,v.readShort_);
},forGlyph:function(v){var w=this.metrics;
var x=w.length;
if(v<x){return w[v];
}return{advance:w[x-1].advance,lsb:this.leftSideBearings[v-x]};
},render:function(v){var y=a();
for(var w=0;
w<v.length;
++w){var x=this.forGlyph(v[w]);
y.writeShort(x.advance);
y.writeShort_(x.lsb);
}return y.get();
}});
var e=function(){function y(C){this.raw=C;
}y.prototype={compound:false,render:function(){return this.raw.get();
}};
var v=1;
var z=8;
var x=32;
var B=64;
var A=128;
function w(C){this.raw=C;
var E=this.glyphIds=[];
var F=this.idOffsets=[];
while(true){var D=C.readShort();
F.push(C.offset());
E.push(C.readShort());
if(!(D&x)){break;
}C.skip(D&v?4:2);
if(D&A){C.skip(8);
}else{if(D&B){C.skip(4);
}else{if(D&z){C.skip(2);
}}}}}w.prototype={compound:true,render:function(E){var F=a(this.raw.get());
for(var C=0;
C<this.glyphIds.length;
++C){var D=this.glyphIds[C];
F.offset(this.idOffsets[C]);
F.writeShort(E[D]);
}return F.get();
}};
return c({parse:function(){this.cache={};
},glyphFor:function(F){var C=this.cache;
if(f(C,F)){return C[F];
}var H=this.file.loca;
var G=H.lengthOf(F);
if(G===0){return C[F]=null;
}var D=this.rawData;
var J=this.offset+H.offsetOf(F);
var K=a(D.slice(J,G));
var I=K.readShort_();
var M=K.readShort_();
var O=K.readShort_();
var L=K.readShort_();
var N=K.readShort_();
var E=C[F]=I==-1?new w(K):new y(K);
E.numberOfContours=I;
E.xMin=M;
E.yMin=O;
E.xMax=L;
E.yMax=N;
return E;
},render:function(D,I,H){var J=a(),G=[];
for(var E=0;
E<I.length;
++E){var F=I[E];
var C=D[F];
G.push(J.offset());
if(C){J.write(C.render(H));
}}G.push(J.offset());
return{table:J.get(),offsets:G};
}});
}();
var l=function(){function v(x,w){this.text=x;
this.length=x.length;
this.platformID=w.platformID;
this.platformSpecificID=w.platformSpecificID;
this.languageID=w.languageID;
this.nameID=w.nameID;
}return c({parse:function(x){x.offset(this.offset);
x.readShort();
var w=x.readShort();
var B=this.offset+x.readShort();
var z=x.times(w,function(){return{platformID:x.readShort(),platformSpecificID:x.readShort(),languageID:x.readShort(),nameID:x.readShort(),length:x.readShort(),offset:x.readShort()+B};
});
var C=this.strings={};
for(var y=0;
y<z.length;
++y){var A=z[y];
x.offset(A.offset);
var D=x.readString(A.length);
if(!C[A.nameID]){C[A.nameID]=[];
}C[A.nameID].push(new v(D,A));
}this.postscriptEntry=C[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(A){var D=this.strings;
var C=0;
for(var w in D){if(f(D,w)){C+=D[w].length;
}}var z=a();
var E=a();
z.writeShort(0);
z.writeShort(C);
z.writeShort(6+12*C);
for(w in D){if(f(D,w)){var y=w==6?[new v(A,this.postscriptEntry)]:D[w];
for(var x=0;
x<y.length;
++x){var B=y[x];
z.writeShort(B.platformID);
z.writeShort(B.platformSpecificID);
z.writeShort(B.languageID);
z.writeShort(B.nameID);
z.writeShort(B.length);
z.writeShort(E.offset());
E.writeString(B.text);
}}}z.write(E.get());
return z.get();
}});
}();
var p=function(){var v=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return c({parse:function(w){w.offset(this.offset);
this.format=w.readLong();
this.italicAngle=w.readFixed_();
this.underlinePosition=w.readShort_();
this.underlineThickness=w.readShort_();
this.isFixedPitch=w.readLong();
this.minMemType42=w.readLong();
this.maxMemType42=w.readLong();
this.minMemType1=w.readLong();
this.maxMemType1=w.readLong();
var y;
switch(this.format){case 65536:case 196608:break;
case 131072:y=w.readShort();
this.glyphNameIndex=w.times(y,w.readShort);
this.names=[];
var x=this.offset+this.length;
while(w.offset()<x){this.names.push(w.readString(w.readByte()));
}break;
case 151552:y=w.readShort();
this.offsets=w.read(y);
break;
case 262144:this.map=w.times(this.file.maxp.numGlyphs,w.readShort);
break;
}},glyphFor:function(w){switch(this.format){case 65536:return v[w]||".notdef";
case 131072:var x=this.glyphNameIndex[w];
if(x<v.length){return v[x];
}return this.names[x-v.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[w]||65535;
}},render:function(A){if(this.format==196608){return this.raw();
}var B=a(this.rawData.slice(this.offset,32));
B.writeLong(131072);
B.offset(32);
var z=[];
var D=[];
for(var w=0;
w<A.length;
++w){var x=A[w];
var C=this.glyphFor(x);
var y=v.indexOf(C);
if(y>=0){z.push(y);
}else{z.push(v.length+D.length);
D.push(C);
}}B.writeShort(A.length);
for(w=0;
w<z.length;
++w){B.writeShort(z[w]);
}for(w=0;
w<D.length;
++w){B.writeByte(D[w].length);
B.writeString(D[w]);
}return B.get();
}});
}();
var b=function(){function v(y,z,x){var A=this;
A.platformID=y.readShort();
A.platformSpecificID=y.readShort();
A.offset=z+y.readLong();
y.saveExcursion(function(){var B;
y.offset(A.offset);
A.format=y.readShort();
switch(A.format){case 0:A.length=y.readShort();
A.language=y.readShort();
for(var J=0;
J<256;
++J){x[J]=y.readByte();
}break;
case 4:A.length=y.readShort();
A.language=y.readShort();
var P=y.readShort()/2;
y.skip(6);
var F=y.times(P,y.readShort);
y.skip(2);
var R=y.times(P,y.readShort);
var K=y.times(P,y.readShort_);
var L=y.times(P,y.readShort);
var C=(A.length+A.offset-y.offset())/2;
var I=y.times(C,y.readShort);
for(J=0;
J<P;
++J){var Q=R[J],D=F[J];
for(B=Q;
B<=D;
++B){var H;
if(L[J]===0){H=B+K[J];
}else{var M=L[J]/2-(P-J)+(B-Q);
H=I[M]||0;
if(H!==0){H+=K[J];
}}x[B]=H&65535;
}}break;
case 6:A.length=y.readShort();
A.language=y.readShort();
B=y.readShort();
var N=y.readShort();
while(N-->0){x[B++]=y.readShort();
}break;
case 12:y.readShort();
A.length=y.readLong();
A.language=y.readLong();
var O=y.readLong();
while(O-->0){B=y.readLong();
var E=y.readLong();
var G=y.readLong();
while(B<=E){x[B++]=G++;
}}break;
default:if(u.console){u.console.error("Unhandled CMAP format: "+A.format);
}}});
}function w(K,M){var y=q(K);
var U=[];
var D=[];
var J=null;
var B=null;
function L(W){return M[K[W]];
}for(var H=0;
H<y.length;
++H){var x=y[H];
var F=L(x);
var z=F-x;
if(J==null||z!==B){if(J){D.push(J);
}U.push(x);
B=z;
}J=x;
}if(J){D.push(J);
}D.push(65535);
U.push(65535);
var R=U.length;
var S=R*2;
var Q=2*Math.pow(2,Math.floor(Math.log(R)/Math.LN2));
var E=Math.log(Q/2)/Math.LN2;
var P=S-Q;
var A=[];
var O=[];
var G=[];
for(H=0;
H<R;
++H){var T=U[H];
var C=D[H];
if(T==65535){A.push(0);
O.push(0);
break;
}var V=L(T);
if(T-V>=32768){A.push(0);
O.push(2*(G.length+R-H));
for(var I=T;
I<=C;
++I){G.push(L(I));
}}else{A.push(V-T);
O.push(0);
}}var N=a();
N.writeShort(3);
N.writeShort(1);
N.writeLong(12);
N.writeShort(4);
N.writeShort(16+R*8+G.length*2);
N.writeShort(0);
N.writeShort(S);
N.writeShort(Q);
N.writeShort(E);
N.writeShort(P);
D.forEach(N.writeShort);
N.writeShort(0);
U.forEach(N.writeShort);
A.forEach(N.writeShort_);
O.forEach(N.writeShort);
G.forEach(N.writeShort);
return N.get();
}return c({parse:function(x){var z=this;
var y=z.offset;
x.offset(y);
z.codeMap={};
z.version=x.readShort();
var A=x.readShort();
z.tables=x.times(A,function(){return new v(x,y,z.codeMap);
});
},render:function(x,y){var z=a();
z.writeShort(0);
z.writeShort(1);
z.write(w(x,y));
return z.get();
}});
}();
var n=c({parse:function(v){v.offset(this.offset);
this.version=v.readShort();
this.averageCharWidth=v.readShort_();
this.weightClass=v.readShort();
this.widthClass=v.readShort();
this.type=v.readShort();
this.ySubscriptXSize=v.readShort_();
this.ySubscriptYSize=v.readShort_();
this.ySubscriptXOffset=v.readShort_();
this.ySubscriptYOffset=v.readShort_();
this.ySuperscriptXSize=v.readShort_();
this.ySuperscriptYSize=v.readShort_();
this.ySuperscriptXOffset=v.readShort_();
this.ySuperscriptYOffset=v.readShort_();
this.yStrikeoutSize=v.readShort_();
this.yStrikeoutPosition=v.readShort_();
this.familyClass=v.readShort_();
this.panose=v.times(10,v.readByte);
this.charRange=v.times(4,v.readLong);
this.vendorID=v.readString(4);
this.selection=v.readShort();
this.firstCharIndex=v.readShort();
this.lastCharIndex=v.readShort();
if(this.version>0){this.ascent=v.readShort_();
this.descent=v.readShort_();
this.lineGap=v.readShort_();
this.winAscent=v.readShort();
this.winDescent=v.readShort();
this.codePageRange=v.times(2,v.readLong);
if(this.version>1){this.xHeight=v.readShort();
this.capHeight=v.readShort();
this.defaultChar=v.readShort();
this.breakChar=v.readShort();
this.maxContext=v.readShort();
}}},render:function(){return this.raw();
}});
var s=100000;
function m(){var x="",w=s+"";
for(var v=0;
v<w.length;
++v){x+=String.fromCharCode(w.charCodeAt(v)-48+65);
}++s;
return x;
}function r(v){this.font=v;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=m()+"+"+this.font.psName;
}r.prototype={use:function(v){var z=this;
if(typeof v=="string"){return kendo.util.ucs2decode(v).reduce(function(B,A){return B+String.fromCharCode(z.use(A));
},"");
}var w=z.unicodes[v];
if(!w){w=z.next++;
z.subset[w]=v;
z.unicodes[v]=w;
var y=z.font.cmap.codeMap[v];
if(y){z.ncid2ogid[w]=y;
if(z.ogid2ngid[y]==null){var x=z.nextGid++;
z.ogid2ngid[y]=x;
z.ngid2ogid[x]=y;
}}}return w;
},encodeText:function(v){return this.use(v);
},glyphIds:function(){return q(this.ogid2ngid);
},glyphsFor:function(w,z){if(!z){z={};
}for(var x=0;
x<w.length;
++x){var y=w[x];
if(!z[y]){var v=z[y]=this.font.glyf.glyphFor(y);
if(v&&v.compound){this.glyphsFor(v.glyphIds,z);
}}}return z;
},render:function(){var x=this.glyphsFor(this.glyphIds());
for(var B in x){if(f(x,B)){B=parseInt(B,10);
if(this.ogid2ngid[B]==null){var z=this.nextGid++;
this.ogid2ngid[B]=z;
this.ngid2ogid[z]=B;
}}}var A=q(this.ngid2ogid);
var C=A.map(function(E){return this.ngid2ogid[E];
},this);
var v=this.font;
var w=v.glyf.render(x,C,this.ogid2ngid);
var y=v.loca.render(w.offsets);
this.lastChar=this.next-1;
var D={cmap:b.render(this.ncid2ogid,this.ogid2ngid),glyf:w.table,loca:y.table,hmtx:v.hmtx.render(C),hhea:v.hhea.render(C),maxp:v.maxp.render(C),post:v.post.render(C),name:v.name.render(this.psName),head:v.head.render(y.format),"OS/2":v.os2.render()};
return this.font.directory.render(D);
},cidToGidMap:function(){var z=a(),w=0;
for(var v=this.firstChar;
v<this.next;
++v){while(w<v){z.writeShort(0);
w++;
}var y=this.ncid2ogid[v];
if(y){var x=this.ogid2ngid[y];
z.writeShort(x);
}else{z.writeShort(0);
}w++;
}return z.get();
}};
function t(A,x){var B=this;
var v=B.contents=a(A);
if(v.readString(4)=="ttcf"){if(!x){throw new Error("Must specify a name for TTC files");
}v.readLong();
var y=v.readLong();
for(var w=0;
w<y;
++w){var z=v.readLong();
v.saveExcursion(function(){v.offset(z);
B.parse();
});
if(B.psName==x){return;
}}throw new Error("Font "+x+" not found in collection");
}else{v.offset(0);
B.parse();
}}t.prototype={parse:function(){var v=this.directory=new d(this.contents);
this.head=v.readTable("head",g);
this.loca=v.readTable("loca",j);
this.hhea=v.readTable("hhea",h);
this.maxp=v.readTable("maxp",k);
this.hmtx=v.readTable("hmtx",i);
this.glyf=v.readTable("glyf",e);
this.name=v.readTable("name",l);
this.post=v.readTable("post",p);
this.cmap=v.readTable("cmap",b);
this.os2=v.readTable("OS/2",n);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(v){return this.hmtx.forGlyph(v).advance*this.scale;
},makeSubset:function(){return new r(this);
}};
o.TTFFont=t;
}(window));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/text-metrics",["kendo.core","util/main"],b);
}(function(){(function(a){var e=document,f=window.kendo,b=f.Class,k=f.util,d=k.defined;
var h=b.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,q){var o=this,p=o._map,m={key:n,value:q};
p[n]=m;
if(!o._head){o._head=o._tail=m;
}else{o._tail.newer=m;
m.older=o._tail;
o._tail=m;
}if(o._length>=o._size){p[o._head.key]=null;
o._head=o._head.newer;
o._head.older=null;
}else{o._length++;
}},get:function(n){var o=this,m=o._map[n];
if(m){if(m===o._head&&m!==o._tail){o._head=m.newer;
o._head.older=null;
}if(m!==o._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=o._tail;
m.newer=null;
o._tail.newer=m;
o._tail=m;
}return m.value;
}}});
var c=a("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function l(){return{width:0,height:0,baseline:0};
}var j=b.extend({init:function(m){this._cache=new h(1000);
this._initOptions(m);
},options:{baselineMarkerSize:1},measure:function(v,t,n){if(!v){return l();
}var u=k.objectKey(t),p=k.hashKey(v+u),o=this._cache.get(p);
if(o){return o;
}var s=l();
var r=n?n:c;
var m=this._baselineMarker().cloneNode(false);
for(var q in t){var w=t[q];
if(d(w)){r.style[q]=w;
}}a(r).text(v);
r.appendChild(m);
e.body.appendChild(r);
if((v+"").length){s.width=r.offsetWidth-this.options.baselineMarkerSize;
s.height=r.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(p,s);
}r.parentNode.removeChild(r);
return s;
},_baselineMarker:function(){return a("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
j.current=new j();
function i(o,n,m){return j.current.measure(o,n,m);
}function g(o,m){var p=[];
if(o.length>0&&document.fonts){try{p=o.map(function(q){return document.fonts.load(q);
});
}catch(n){f.logToConsole(n);
}Promise.all(p).then(m,m);
}else{m();
}}f.util.TextMetrics=j;
f.util.LRUCache=h;
f.util.loadFonts=g;
f.util.measureText=i;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/base64",["util/main"],b);
}(function(){(function(){var e=window.kendo,a=e.deepExtend,d=String.fromCharCode;
var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function b(p){var q="";
var g,h,j,k,l,m,n;
var o=0;
p=c(p);
while(o<p.length){g=p.charCodeAt(o++);
h=p.charCodeAt(o++);
j=p.charCodeAt(o++);
k=g>>2;
l=(g&3)<<4|h>>4;
m=(h&15)<<2|j>>6;
n=j&63;
if(isNaN(h)){m=n=64;
}else{if(isNaN(j)){n=64;
}}q=q+f.charAt(k)+f.charAt(l)+f.charAt(m)+f.charAt(n);
}return q;
}function c(j){var k="";
for(var h=0;
h<j.length;
h++){var g=j.charCodeAt(h);
if(g<128){k+=d(g);
}else{if(g<2048){k+=d(192|g>>>6);
k+=d(128|g&63);
}else{if(g<65536){k+=d(224|g>>>12);
k+=d(128|g>>>6&63);
k+=d(128|g&63);
}}}}return k;
}a(e.util,{encodeBase64:b,encodeUTF8:c});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("mixins/observers",["kendo.core"],b);
}(function(){(function(a){var e=Math,d=window.kendo,b=d.deepExtend,c=a.inArray;
var f={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(g){if(!this._observers){this._observers=[g];
}else{this._observers.push(g);
}return this;
},removeObserver:function(g){var i=this.observers();
var h=c(g,i);
if(h!=-1){i.splice(h,1);
}return this;
},trigger:function(i,g){var k=this._observers;
var j;
var h;
if(k&&!this._suspended){for(h=0;
h<k.length;
h++){j=k[h];
if(j[i]){j[i](g);
}}}return this;
},optionsChange:function(g){g=g||{};
g.element=this;
this.trigger("optionsChange",g);
},geometryChange:function(){this.trigger("geometryChange",{element:this});
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=e.max((this._suspended||0)-1,0);
return this;
},_observerField:function(g,h){if(this[g]){this[g].removeObserver(this);
}this[g]=h;
h.addObserver(this);
}};
b(d,{mixins:{ObserversMixin:f}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("pdf/drawing",["kendo.core","kendo.color","kendo.drawing","pdf/core"],b);
}(function(){(function(q,a){var j=q.drawing;
var p=q.geometry;
var E=q.pdf.TEXT_RENDERING_MODE;
var c={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var r={butt:0,round:1,square:2};
var s={miter:0,round:1,bevel:2};
function y(M,H){var K=[],N=[],P=M.options;
function L(S,Q,R){if(!R){R=P;
}if(R.pdf&&R.pdf[S]!=null){return R.pdf[S];
}return Q;
}var O=L("multiPage");
M.traverse(function(Q){d({Image:function(R){if(N.indexOf(R.src())<0){N.push(R.src());
}},Text:function(R){var S=q.pdf.parseFontDef(R.options.font);
var T=q.pdf.getFontURL(S);
if(K.indexOf(T)<0){K.push(T);
}}},Q);
});
function J(){if(--I>0){return;
}var R=new q.pdf.Document({producer:L("producer"),title:L("title"),author:L("author"),subject:L("subject"),keywords:L("keywords"),creator:L("creator"),date:L("date")});
function Q(U){var V=U.options;
var aa=w(U);
var T=aa.bbox;
U=aa.root;
var Y=L("paperSize",L("paperSize","auto"),V),S=false;
if(Y=="auto"){if(T){var Z=T.getSize();
Y=[Z.width,Z.height];
S=true;
var W=T.getOrigin();
aa=new j.Group();
aa.transform(new p.Matrix(1,0,0,1,-W.x,-W.y));
aa.append(U);
U=aa;
}else{Y="A4";
}}var X;
X=R.addPage({paperSize:Y,margin:L("margin",L("margin"),V),addMargin:S,landscape:L("landscape",L("landscape",false),V)});
g(U,X,R);
}if(O){M.children.forEach(Q);
}else{Q(M);
}H(R.render(),R);
}var I=2;
q.pdf.loadFonts(K,J);
q.pdf.loadImages(N,J);
}function G(I,H){y(I,function(J){H("data:application/pdf;base64,"+J.base64());
});
}function F(I,H){y(I,function(J){H(new Blob([J.get()],{type:"application/pdf"}));
});
}function z(J,I,K,H){if(window.Blob&&!q.support.browser.safari){F(J,function(L){q.saveAs({dataURI:L,fileName:I});
if(H){H(L);
}});
}else{G(J,function(L){q.saveAs({dataURI:L,fileName:I,proxyURL:K});
if(H){H(L);
}});
}}function d(J,H){var I=J[H.nodeType];
if(I){return I.call.apply(I,arguments);
}return H;
}function g(H,K,L){if(H.options._pdfDebug){K.comment("BEGIN: "+H.options._pdfDebug);
}var M=H.transform();
var J=H.opacity();
K.save();
if(J!=null&&J<1){K.setOpacity(J);
}C(H,K,L);
B(H,K,L);
if(M){var I=M.matrix();
K.transform(I.a,I.b,I.c,I.d,I.e,I.f);
}A(H,K,L);
d({Path:l,MultiPath:k,Circle:f,Arc:e,Text:n,Image:i,Group:h,Rect:m},H,K,L);
K.restore();
if(H.options._pdfDebug){K.comment("END: "+H.options._pdfDebug);
}}function C(J,N){var O=J.stroke&&J.stroke();
if(!O){return;
}var H=O.color;
if(H){H=x(H);
if(H==null){return;
}N.setStrokeColor(H.r,H.g,H.b);
if(H.a!=1){N.setStrokeOpacity(H.a);
}}var P=O.width;
if(P!=null){if(P===0){return;
}N.setLineWidth(P);
}var I=O.dashType;
if(I){N.setDashPattern(c[I],0);
}var K=O.lineCap;
if(K){N.setLineCap(r[K]);
}var L=O.lineJoin;
if(L){N.setLineJoin(s[L]);
}var M=O.opacity;
if(M!=null){N.setStrokeOpacity(M);
}}function B(I,L){var J=I.fill&&I.fill();
if(!J){return;
}if(J instanceof j.Gradient){return;
}var H=J.color;
if(H){H=x(H);
if(H==null){return;
}L.setFillColor(H.r,H.g,H.b);
if(H.a!=1){L.setFillOpacity(H.a);
}}var K=J.opacity;
if(K!=null){L.setFillOpacity(K);
}}function A(I,J,K){var H=I.clip();
if(H){b(H,J,K);
J.clip();
}}function D(H){return H&&(H instanceof j.Gradient||H.color&&!/^(none|transparent)$/i.test(H.color)&&(H.width==null||H.width>0)&&(H.opacity==null||H.opacity>0));
}function v(I,N,O,S){var K=I.fill();
if(K instanceof j.Gradient){if(S){N.clipStroke();
}else{N.clip();
}var M=K instanceof j.RadialGradient;
var Q,J;
if(M){Q={x:K.center().x,y:K.center().y,r:0};
J={x:K.center().x,y:K.center().y,r:K.radius()};
}else{Q={x:K.start().x,y:K.start().y};
J={x:K.end().x,y:K.end().y};
}var R=K.stops.elements().map(function(W){var V=W.offset();
if(/%$/.test(V)){V=parseFloat(V)/100;
}else{V=parseFloat(V);
}var U=x(W.color());
U.a*=W.opacity();
return{offset:V,color:U};
});
R.unshift(R[0]);
R.push(R[R.length-1]);
var L={userSpace:K.userSpace(),type:M?"radial":"linear",start:Q,end:J,stops:R};
var H=I.rawBBox();
var T=H.topLeft(),P=H.getSize();
H={left:T.x,top:T.y,width:P.width,height:P.height};
N.gradient(L,H);
return true;
}}function u(H,I,J){if(D(H.fill())&&D(H.stroke())){if(!v(H,I,J,true)){I.fillStroke();
}}else{if(D(H.fill())){if(!v(H,I,J,false)){I.fill();
}}else{if(D(H.stroke())){I.stroke();
}else{I.nop();
}}}}function t(L,K){var M=L.segments;
if(M.length==4&&L.options.closed){var H=[];
for(var I=0;
I<M.length;
++I){if(M[I].controlIn()){return false;
}H[I]=M[I].anchor();
}var J=H[0].y==H[1].y&&H[1].x==H[2].x&&H[2].y==H[3].y&&H[3].x==H[0].x||H[0].x==H[1].x&&H[1].y==H[2].y&&H[2].x==H[3].x&&H[3].y==H[0].y;
if(J){K.rect(H[0].x,H[0].y,H[2].x-H[0].x,H[2].y-H[0].y);
return true;
}}}function b(J,L,M){var Q=J.segments;
if(Q.length===0){return;
}if(!t(J,L,M)){for(var N,K=0;
K<Q.length;
++K){var P=Q[K];
var H=P.anchor();
if(!N){L.moveTo(H.x,H.y);
}else{var O=N.controlOut();
var I=P.controlIn();
if(O&&I){L.bezier(O.x,O.y,I.x,I.y,H.x,H.y);
}else{L.lineTo(H.x,H.y);
}}N=P;
}if(J.options.closed){L.close();
}}}function l(H,I,J){b(H,I,J);
u(H,I,J);
}function k(H,J,L){var K=H.paths;
for(var I=0;
I<K.length;
++I){b(K[I],J,L);
}u(H,J,L);
}function f(H,J,K){var I=H.geometry();
J.circle(I.center.x,I.center.y,I.radius);
u(H,J,K);
}function e(H,J,K){var L=H.geometry().curvePoints();
J.moveTo(L[0].x,L[0].y);
for(var I=1;
I<L.length;
){J.bezier(L[I].x,L[I++].y,L[I].x,L[I++].y,L[I].x,L[I++].y);
}u(H,J,K);
}function n(H,J){var L=q.pdf.parseFontDef(H.options.font);
var K=H._position;
var I;
if(H.fill()&&H.stroke()){I=E.fillAndStroke;
}else{if(H.fill()){I=E.fill;
}else{if(H.stroke()){I=E.stroke;
}}}J.transform(1,0,0,-1,K.x,K.y+L.fontSize);
J.beginText();
J.setFont(q.pdf.getFontURL(L),L.fontSize);
J.setTextRenderingMode(I);
J.showText(H.content(),H._pdfRect?H._pdfRect.width():null);
J.endText();
}function h(I,K,L){if(I._pdfLink){K.addLink(I._pdfLink.url,I._pdfLink);
}var H=I.children;
for(var J=0;
J<H.length;
++J){g(H[J],K,L);
}}function i(H,I){var M=H.src();
if(!M){return;
}var J=H.rect();
var L=J.getOrigin();
var K=J.getSize();
I.transform(K.width,0,0,-K.height,L.x,L.y+K.height);
I.drawImage(M);
}function m(H,J,K){var I=H.geometry();
J.rect(I.origin.x,I.origin.y,I.size.width,I.size.height);
u(H,J,K);
}function o(I,K){var H=a.Deferred();
for(var J in K){if(J=="margin"&&I.options.pdf&&I.options.pdf._ignoreMargin){continue;
}I.options.set("pdf."+J,K[J]);
}j.pdf.toDataURL(I,H.resolve);
return H.promise();
}function x(I){var H=q.parseColor(I,true);
return H?H.toRGB():null;
}function w(P){var J=false;
var M=p.Matrix.unit();
var K=null;
var I;
do{I=false;
P=N(P);
}while(P&&I);
return{root:P,bbox:K};
function H(S){I=true;
return S;
}function Q(S){return S.visible()&&S.opacity()>0&&(D(S.fill())||D(S.stroke()));
}function O(S){var T=[];
for(var V=0;
V<S.length;
++V){var U=N(S[V]);
if(U!=null){T.push(U);
}}return T;
}function R(W,T){var U=J;
var V=M;
if(W.transform()){M=M.multiplyCopy(W.transform().matrix());
}var S=W.clip();
if(S){S=S.bbox();
if(S){S=S.bbox(M);
J=J?p.Rect.intersect(J,S):S;
}}try{return T();
}finally{J=U;
M=V;
}}function L(T){if(J==null){return false;
}var S=T.rawBBox().bbox(M);
if(J&&S){S=p.Rect.intersect(S,J);
}return S;
}function N(S){return R(S,function(){if(!(S instanceof j.Group||S instanceof j.MultiPath)){var T=L(S);
if(!T){return H(null);
}K=K?p.Rect.union(K,T):T;
}return d({Path:function(U){if(U.segments.length===0||!Q(U)){return H(null);
}return U;
},MultiPath:function(V){if(!Q(V)){return H(null);
}var U=new j.MultiPath(V.options);
U.paths=O(V.paths);
if(U.paths.length===0){return H(null);
}return U;
},Circle:function(U){if(!Q(U)){return H(null);
}return U;
},Arc:function(U){if(!Q(U)){return H(null);
}return U;
},Text:function(U){if(!/\S/.test(U.content())||!Q(U)){return H(null);
}return U;
},Image:function(U){if(!(U.visible()&&U.opacity()>0)){return H(null);
}return U;
},Group:function(V){var U=new j.Group(V.options);
U.children=O(V.children);
U._pdfLink=V._pdfLink;
if(V!==P&&U.children.length===0&&!V._pdfLink){return H(null);
}return U;
},Rect:function(U){if(!Q(U)){return H(null);
}return U;
}},S);
});
}}q.deepExtend(j,{exportPDF:o,pdf:{toDataURL:G,toBlob:F,saveAs:z,toStream:y}});
}(window.kendo,window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.pdf",["kendo.core","pdf/core","pdf/ttf","pdf/drawing","kendo.drawing"],b);
}(function(){var a={id:"pdf",name:"PDF export",description:"PDF Generation framework",mixin:true,category:"framework",depends:["core","drawing"]};
(function(c,b){c.PDFMixin={extend:function(d){d.events.push("pdfExport");
d.options.pdf=this.options;
d.saveAsPDF=this.saveAsPDF;
d._drawPDF=this._drawPDF;
d._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator v."+c.version,date:null},saveAsPDF:function(){var f=new b.Deferred();
var g=f.promise();
var d={promise:g};
if(this.trigger("pdfExport",d)){return;
}var e=this.options.pdf;
e.multiPage=e.multiPage||e.allPages;
this._drawPDF(f).then(function(h){return c.drawing.exportPDF(h,e);
}).done(function(h){c.saveAs({dataURI:h,fileName:e.fileName,proxyURL:e.proxyURL,forceProxy:e.forceProxy,proxyTarget:e.proxyTarget});
f.resolve();
}).fail(function(h){f.reject(h);
});
return g;
},_drawPDF:function(d){var e=new b.Deferred();
c.drawing.drawDOM(this.wrapper).done(function(g){var f={page:g,pageNumber:1,progress:1,totalPages:1};
d.notify(f);
e.resolve(f.page);
}).fail(function(f){e.reject(f);
});
return e;
},_drawPDFShadow:function(f,e){f=f||{};
var h=this.wrapper;
var g=b("<div class='k-pdf-export-shadow'>");
if(f.width){g.css({width:f.width,overflow:"visible"});
}h.before(g);
g.append(f.content||h.clone(true,true));
var d=b.Deferred();
setTimeout(function(){var i=c.drawing.drawDOM(g,e);
i.always(function(){g.remove();
}).then(function(){d.resolve.apply(d,arguments);
}).fail(function(){d.reject.apply(d,arguments);
}).progress(function(){d.progress.apply(d,arguments);
});
},15);
return d.promise();
}};
}(kendo,window.kendo.jQuery));
return kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
