(function(b,a){a("kendo.popup",["kendo.core"],b);
}(function(){var a={id:"popup",name:"Pop-up",category:"framework",depends:["core"],advanced:true};
(function(b,J){var u=window.kendo,I=u.ui,L=I.Widget,F=u.support,s=u.getOffset,z="open",l="close",o="deactivate",d="activate",k="center",v="left",C="right",G="top",j="bottom",c="absolute",t="hidden",i="body",w="location",B="position",K="visible",q="effects",e="k-state-active",f="k-state-border",g=/k-state-border-(\w+)/,h=".k-picker-wrap, .k-dropdown-wrap, .k-link",x="down",p=b(document.documentElement),M=b(window),D="scroll",n=F.transitions.css,H=n+"transform",r=b.extend,y=".kendoPopup",E=["font-size","font-family","font-stretch","font-style","font-weight","line-height"];
function m(N,O){if(!N||!O){return false;
}return N===O||b.contains(N,O);
}var A=L.extend({init:function(N,O){var Q=this,P;
O=O||{};
if(O.isRtl){O.origin=O.origin||j+" "+C;
O.position=O.position||G+" "+C;
}L.fn.init.call(Q,N,O);
N=Q.element;
O=Q.options;
Q.collisions=O.collision?O.collision.split(" "):[];
Q.downEvent=u.applyEventMap(x,u.guid());
if(Q.collisions.length===1){Q.collisions.push(Q.collisions[0]);
}P=b(Q.options.anchor).closest(".k-popup,.k-group").filter(":not([class^=km-])");
O.appendTo=b(b(O.appendTo)[0]||P[0]||i);
Q.element.hide().addClass("k-popup k-group k-reset").toggleClass("k-rtl",!!O.isRtl).css({position:c}).appendTo(O.appendTo).on("mouseenter"+y,function(){Q._hovered=true;
}).on("mouseleave"+y,function(){Q._hovered=false;
});
Q.wrapper=b();
if(O.animation===false){O.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}r(O.animation.open,{complete:function(){Q.wrapper.css({overflow:K});
Q._activated=true;
Q._trigger(d);
}});
r(O.animation.close,{complete:function(){Q._animationClose();
}});
Q._mousedownProxy=function(R){Q._mousedown(R);
};
if(F.mobileOS.android){Q._resizeProxy=function(R){setTimeout(function(){Q._resize(R);
},600);
};
}else{Q._resizeProxy=function(R){Q._resize(R);
};
}if(O.toggleTarget){b(O.toggleTarget).on(O.toggleEvent+y,b.proxy(Q.toggle,Q));
}},events:[z,d,l,o],options:{name:"Popup",toggleEvent:"click",origin:j+" "+v,position:G+" "+v,anchor:i,appendTo:null,collision:"flip fit",viewport:window,copyAnchorStyles:true,autosize:false,modal:false,adjustSize:{width:0,height:0},animation:{open:{effects:"slideIn:down",transition:true,duration:200},close:{duration:100,hide:true}}},_animationClose:function(){var O=this;
var N=O.wrapper.data(w);
O.wrapper.hide();
if(N){O.wrapper.css(N);
}if(O.options.anchor!=i){O._hideDirClass();
}O._closing=false;
O._trigger(o);
},destroy:function(){var Q=this,O=Q.options,N=Q.element.off(y),P;
L.fn.destroy.call(Q);
if(O.toggleTarget){b(O.toggleTarget).off(y);
}if(!O.modal){p.unbind(Q.downEvent,Q._mousedownProxy);
Q._toggleResize(false);
}u.destroy(Q.element.children());
N.removeData();
if(O.appendTo[0]===document.body){P=N.parent(".k-animation-container");
if(P[0]){P.remove();
}else{N.remove();
}}},open:function(V,W){var T=this,Q={isFixed:!isNaN(parseInt(W,10)),x:V,y:W},P=T.element,S=T.options,O,U,N=b(S.anchor),R=P[0]&&P.hasClass("km-widget");
if(!T.visible()){if(S.copyAnchorStyles){if(R&&E[0]=="font-size"){E.shift();
}P.css(u.getComputedStyles(N[0],E));
}if(P.data("animating")||T._trigger(z)){return;
}T._activated=false;
if(!S.modal){p.unbind(T.downEvent,T._mousedownProxy).bind(T.downEvent,T._mousedownProxy);
T._toggleResize(false);
T._toggleResize(true);
}T.wrapper=U=u.wrap(P,S.autosize).css({overflow:t,display:"block",position:c});
if(F.mobileOS.android){U.css(H,"translatez(0)");
}U.css(B);
if(b(S.appendTo)[0]==document.body){U.css(G,"-10000px");
}T.flipped=T._position(Q);
O=T._openAnimation();
if(S.anchor!=i){T._showDirClass(O);
}P.data(q,O.effects).kendoStop(true).kendoAnimate(O);
}},_openAnimation:function(){var N=r(true,{},this.options.animation.open);
N.effects=u.parseEffects(N.effects,this.flipped);
return N;
},_hideDirClass:function(){var N=b(this.options.anchor);
var P=((N.attr("class")||"").match(g)||["","down"])[1];
var O=f+"-"+P;
N.removeClass(O).children(h).removeClass(e).removeClass(O);
this.element.removeClass(f+"-"+u.directions[P].reverse);
},_showDirClass:function(N){var P=N.effects.slideIn?N.effects.slideIn.direction:"down";
var O=f+"-"+P;
b(this.options.anchor).addClass(O).children(h).addClass(e).addClass(O);
this.element.addClass(f+"-"+u.directions[P].reverse);
},position:function(){if(this.visible()){this.flipped=this._position();
}},toggle:function(){var N=this;
N[N.visible()?l:z]();
},visible:function(){return this.element.is(":"+K);
},close:function(R){var S=this,Q=S.options,T,N,P,O;
if(S.visible()){T=S.wrapper[0]?S.wrapper:u.wrap(S.element).hide();
S._toggleResize(false);
if(S._closing||S._trigger(l)){S._toggleResize(true);
return;
}S.element.find(".k-popup").each(function(){var V=b(this),U=V.data("kendoPopup");
if(U){U.close(R);
}});
p.unbind(S.downEvent,S._mousedownProxy);
if(R){N={hide:true,effects:{}};
}else{N=r(true,{},Q.animation.close);
P=S.element.data(q);
O=N.effects;
if(!O&&!u.size(O)&&P&&u.size(P)){N.effects=P;
N.reverse=true;
}S._closing=true;
}S.element.kendoStop(true);
T.css({overflow:t});
S.element.kendoAnimate(N);
if(R){S._animationClose();
}}},_trigger:function(N){return this.trigger(N,{type:N});
},_resize:function(N){var O=this;
if(F.resize.indexOf(N.type)!==-1){clearTimeout(O._resizeTimeout);
O._resizeTimeout=setTimeout(function(){O._position();
O._resizeTimeout=null;
},50);
}else{if(!O._hovered||O._activated&&O.element.hasClass("k-list-container")){O.close();
}}},_toggleResize:function(P){var O=P?"on":"off";
var N=F.resize;
if(!(F.mobileOS.ios||F.mobileOS.android)){N+=" "+D;
}this._scrollableParents()[O](D,this._resizeProxy);
M[O](N,this._resizeProxy);
},_mousedown:function(P){var U=this,O=U.element[0],R=U.options,N=b(R.anchor)[0],V=R.toggleTarget,T=u.eventTarget(P),S=b(T).closest(".k-popup"),Q=S.parent().parent(".km-shim").length;
S=S[0];
if(!Q&&S&&S!==U.element[0]){return;
}if(b(P.target).closest("a").data("rel")==="popover"){return;
}if(!m(O,T)&&!m(N,T)&&!(V&&m(b(V)[0],T))){U.close();
}},_fit:function(O,P,Q){var N=0;
if(O+P>Q){N=Q-(O+P);
}if(O<0){N=-O;
}return N;
},_flip:function(P,T,N,U,Q,S,O){var R=0;
O=O||T;
if(S!==Q&&S!==k&&Q!==k){if(P+O>U){R+=-(N+T);
}if(P+R<0){R+=N+T;
}}return R;
},_scrollableParents:function(){return b(this.options.anchor).parentsUntil("body").filter(function(O,N){return u.isScrollable(N);
});
},_position:function(U){var aj=this,S=aj.element,ao=aj.wrapper,ac=aj.options,ak=b(ac.viewport),ar=F.zoomLevel(),X=!!(ak[0]==window&&window.innerWidth&&ar<=1.02),O=b(ac.anchor),ad=ac.origin.toLowerCase().split(" "),ah=ac.position.toLowerCase().split(" "),Q=aj.collisions,ai,ae,af,aq=10002,W=0,R=document.documentElement,Y,am,an,al;
if(ac.viewport===window){am={top:window.pageYOffset||document.documentElement.scrollTop||0,left:window.pageXOffset||document.documentElement.scrollLeft||0};
}else{am=ak.offset();
}if(X){an=window.innerWidth;
al=window.innerHeight;
}else{an=ak.width();
al=ak.height();
}if(X&&R.scrollHeight-R.clientHeight>0){an-=u.support.scrollbar();
}ai=O.parents().filter(ao.siblings());
if(ai[0]){af=Math.max(Number(ai.css("zIndex")),0);
if(af){aq=af+10;
}else{ae=O.parentsUntil(ai);
for(Y=ae.length;
W<Y;
W++){af=Number(b(ae[W]).css("zIndex"));
if(af&&aq<af){aq=af+10;
}}}}ao.css("zIndex",aq);
if(U&&U.isFixed){ao.css({left:U.x,top:U.y});
}else{ao.css(aj._align(ad,ah));
}var ag=s(ao,B,O[0]===ao.offsetParent()[0]),aa=s(ao),P=O.offsetParent().parent(".k-animation-container,.k-popup,.k-group");
if(P.length){ag=s(ao,B,true);
aa=s(ao);
}aa.top-=am.top;
aa.left-=am.left;
if(!aj.wrapper.data(w)){ao.data(w,r({},ag));
}var ab=r({},aa),Z=r({},ag),N=ac.adjustSize;
if(Q[0]==="fit"){Z.top+=aj._fit(ab.top,ao.outerHeight()+N.height,al/ar);
}if(Q[1]==="fit"){Z.left+=aj._fit(ab.left,ao.outerWidth()+N.width,an/ar);
}var V=r({},Z);
var T=S.outerHeight();
var ap=ao.outerHeight();
if(!ao.height()&&T){ap=ap+T;
}if(Q[0]==="flip"){Z.top+=aj._flip(ab.top,T,O.outerHeight(),al/ar,ad[0],ah[0],ap);
}if(Q[1]==="flip"){Z.left+=aj._flip(ab.left,S.outerWidth(),O.outerWidth(),an/ar,ad[1],ah[1],ao.outerWidth());
}S.css(B,c);
ao.css(Z);
return Z.left!=V.left||Z.top!=V.top;
},_align:function(Y,Z){var ab=this,T=ab.wrapper,N=b(ab.options.anchor),ad=Y[0],V=Y[1],ae=Z[0],W=Z[1],P=s(N),R=b(ab.options.appendTo),S,af=T.outerWidth(),U=T.outerHeight(),Q=N.outerWidth(),O=N.outerHeight(),ac=P.top,X=P.left,aa=Math.round;
if(R[0]!=document.body){S=s(R);
ac-=S.top;
X-=S.left;
}if(ad===j){ac+=O;
}if(ad===k){ac+=aa(O/2);
}if(ae===j){ac-=U;
}if(ae===k){ac-=aa(U/2);
}if(V===C){X+=Q;
}if(V===k){X+=aa(Q/2);
}if(W===C){X-=af;
}if(W===k){X-=aa(af/2);
}return{top:ac,left:X};
}});
I.plugin(A);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
