(function(b,a){a("kendo.resizable",["kendo.core","kendo.draganddrop"],b);
}(function(){var a={id:"resizable",name:"Resizable",category:"framework",depends:["core","draganddrop"],advanced:true};
(function(b,m){var f=window.kendo,l=f.ui,o=l.Widget,g=b.proxy,e=f.isFunction,c=b.extend,d="horizontal",n="vertical",k="start",i="resize",j="resizeend";
var h=o.extend({init:function(p,q){var r=this;
o.fn.init.call(r,p,q);
r.orientation=r.options.orientation.toLowerCase()!=n?d:n;
r._positionMouse=r.orientation==d?"x":"y";
r._position=r.orientation==d?"left":"top";
r._sizingDom=r.orientation==d?"outerWidth":"outerHeight";
r.draggable=new l.Draggable(q.draggableElement||p,{distance:1,filter:q.handle,drag:g(r._resize,r),dragcancel:g(r._cancel,r),dragstart:g(r._start,r),dragend:g(r._stop,r)});
r.userEvents=r.draggable.userEvents;
},events:[i,j,k],options:{name:"Resizable",orientation:d},resize:function(){},_max:function(p){var s=this,q=s.hint?s.hint[s._sizingDom]():0,r=s.options.max;
return e(r)?r(p):r!==m?s._initialElementPosition+r-q:r;
},_min:function(p){var r=this,q=r.options.min;
return e(q)?q(p):q!==m?r._initialElementPosition+q:q;
},_start:function(p){var s=this,r=s.options.hint,q=b(p.currentTarget);
s._initialElementPosition=q.position()[s._position];
s._initialMousePosition=p[s._positionMouse].startLocation;
if(r){s.hint=e(r)?b(r(q)):r;
s.hint.css({position:"absolute"}).css(s._position,s._initialElementPosition).appendTo(s.element);
}s.trigger(k,p);
s._maxPosition=s._max(p);
s._minPosition=s._min(p);
b(document.body).css("cursor",q.css("cursor"));
},_resize:function(q){var u=this,r=u._maxPosition,s=u._minPosition,p=u._initialElementPosition+(q[u._positionMouse].location-u._initialMousePosition),t;
t=s!==m?Math.max(s,p):p;
u.position=t=r!==m?Math.min(r,t):t;
if(u.hint){u.hint.toggleClass(u.options.invalidClass||"",t==r||t==s).css(u._position,t);
}u.resizing=true;
u.trigger(i,c(q,{position:t}));
},_stop:function(p){var q=this;
if(q.hint){q.hint.remove();
}q.resizing=false;
q.trigger(j,c(p,{position:q.position}));
b(document.body).css("cursor","");
},_cancel:function(p){var q=this;
if(q.hint){q.position=m;
q.hint.css(q._position,q._initialElementPosition);
q._stop(p);
}},destroy:function(){var p=this;
o.fn.destroy.call(p);
if(p.draggable){p.draggable.destroy();
}},press:function(q){if(!q){return;
}var p=q.position(),r=this;
r.userEvents.press(p.left,p.top,q[0]);
r.targetPosition=p;
r.target=q;
},move:function(q){var t=this,r=t._position,s=t.targetPosition,p=t.position;
if(p===m){p=s[r];
}s[r]=p+q;
t.userEvents.move(s.left,s.top);
},end:function(){this.userEvents.end();
this.target=this.position=m;
}});
f.ui.plugin(h);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
