(function(b,a){a("kendo.toolbar",["kendo.core","kendo.userevents","kendo.popup"],b);
}(function(){var a={id:"toolbar",name:"ToolBar",category:"web",description:"The ToolBar widget displays one or more command buttons divided into groups.",depends:["core"]};
(function(b,am){var x=window.kendo,k=x.Class,an=x.ui.Widget,U=b.proxy,v=x.isFunction,z=x.keys,ah="k-toolbar",f="k-button",G="k-overflow-button",ae="k-toggle-button",g="k-button-group",X="k-split-button",W="k-separator",R="k-popup",V="k-toolbar-resizable",Z="k-state-active",aa="k-state-disabled",ab="k-state-hidden",s="k-group-start",r="k-group-end",T="k-primary",t="k-icon",u="k-i-",h="k-button-icon",i="k-button-icontext",B="k-list-container k-split-container",Y="k-split-button-arrow",E="k-overflow-anchor",I="k-overflow-container",p="k-toolbar-first-visible",A="k-toolbar-last-visible",l="click",ad="toggle",C="open",m="close",L="overflowOpen",H="overflowClose",K="never",F="auto",D="always",J="k-overflow-hidden",y=x.attr("uid");
x.toolbar={};
var n={overflowAnchor:'<div tabindex="0" class="k-overflow-anchor"></div>',overflowContainer:'<ul class="k-overflow-container k-list-container"></ul>'};
x.toolbar.registerComponent=function(ao,aq,ap){n[ao]={toolbar:aq,overflow:ap};
};
var w=x.Class.extend({addOverflowAttr:function(){this.element.attr(x.attr("overflow"),this.options.overflow||F);
},addUidAttr:function(){this.element.attr(y,this.options.uid);
},addIdAttr:function(){if(this.options.id){this.element.attr("id",this.options.id);
}},addOverflowIdAttr:function(){if(this.options.id){this.element.attr("id",this.options.id+"_overflow");
}},attributes:function(){if(this.options.attributes){this.element.attr(this.options.attributes);
}},show:function(){this.element.removeClass(ab).show();
this.options.hidden=false;
},hide:function(){this.element.addClass(ab).hide();
this.options.hidden=true;
},remove:function(){this.element.remove();
},enable:function(ao){if(ao===am){ao=true;
}this.element.toggleClass(aa,!ao);
this.options.enable=ao;
},twin:function(){var ao=this.element.attr(y);
if(this.overflow){return this.toolbar.element.find("["+y+"='"+ao+"']").data(this.options.type);
}else{if(this.toolbar.options.resizable){return this.toolbar.popup.element.find("["+y+"='"+ao+"']").data(this.options.type);
}}}});
x.toolbar.Item=w;
var e=w.extend({init:function(ap,aq){var ao=ap.useButtonTag?b('<button tabindex="0"></button>'):b('<a href tabindex="0"></a>');
this.element=ao;
this.options=ap;
this.toolbar=aq;
this.attributes();
if(ap.primary){ao.addClass(T);
}if(ap.togglable){ao.addClass(ae);
this.toggle(ap.selected);
}if(ap.url!==am&&!ap.useButtonTag){ao.attr("href",ap.url);
if(ap.mobile){ao.attr(x.attr("role"),"button");
}}if(ap.group){ao.attr(x.attr("group"),ap.group);
this.group=this.toolbar.addToGroup(this,ap.group);
}if(!ap.togglable&&ap.click&&v(ap.click)){this.clickHandler=ap.click;
}if(ap.togglable&&ap.toggle&&v(ap.toggle)){this.toggleHandler=ap.toggle;
}},toggle:function(ap,ao){ap=!!ap;
if(this.group&&ap){this.group.select(this);
}else{if(!this.group){this.select(ap);
}}if(ao&&this.twin()){this.twin().toggle(ap);
}},getParentGroup:function(){if(this.options.isChild){return this.element.closest("."+g).data("buttonGroup");
}},_addGraphics:function(){var ao=this.element,ap=this.options.icon,av=this.options.spriteCssClass,aq=this.options.imageUrl,at,au,ar;
if(av||aq||ap){at=true;
ao.contents().not("span.k-sprite,span."+t+",img.k-image").each(function(ax,aw){if(aw.nodeType==1||aw.nodeType==3&&b.trim(aw.nodeValue).length>0){at=false;
}});
if(at){ao.addClass(h);
}else{ao.addClass(i);
}}if(ap){au=ao.children("span."+t).first();
if(!au[0]){au=b('<span class="'+t+'"></span>').prependTo(ao);
}au.addClass(u+ap);
}else{if(av){au=ao.children("span.k-sprite").first();
if(!au[0]){au=b('<span class="k-sprite"></span>').prependTo(ao);
}au.addClass(av);
}else{if(aq){ar=ao.children("img.k-image").first();
if(!ar[0]){ar=b('<img alt="icon" class="k-image" />').prependTo(ao);
}ar.attr("src",aq);
}}}}});
x.toolbar.Button=e;
var ai=e.extend({init:function(ap,aq){e.fn.init.call(this,ap,aq);
var ao=this.element;
ao.addClass(f);
this.addIdAttr();
if(ap.align){ao.addClass("k-align-"+ap.align);
}if(ap.showText!="overflow"&&ap.text){if(ap.mobile){ao.html('<span class="km-text">'+ap.text+"</span>");
}else{ao.html(ap.text);
}}ap.hasIcon=ap.showIcon!="overflow"&&(ap.icon||ap.spriteCssClass||ap.imageUrl);
if(ap.hasIcon){this._addGraphics();
}this.addUidAttr();
this.addOverflowAttr();
this.enable(ap.enable);
if(ap.hidden){this.hide();
}this.element.data({type:"button",button:this});
},select:function(ao){if(ao===am){ao=false;
}this.element.toggleClass(Z,ao);
this.options.selected=ao;
}});
x.toolbar.ToolBarButton=ai;
var M=e.extend({init:function(ap,aq){this.overflow=true;
e.fn.init.call(this,ap,aq);
var ao=this.element;
if(ap.showText!="toolbar"&&ap.text){if(ap.mobile){ao.html('<span class="km-text">'+ap.text+"</span>");
}else{ao.html('<span class="k-text">'+ap.text+"</span>");
}}ap.hasIcon=ap.showIcon!="toolbar"&&(ap.icon||ap.spriteCssClass||ap.imageUrl);
if(ap.hasIcon){this._addGraphics();
}if(!ap.isChild){this._wrap();
}this.addOverflowIdAttr();
this.attributes();
this.addUidAttr();
this.addOverflowAttr();
this.enable(ap.enable);
ao.addClass(G+" "+f);
if(ap.hidden){this.hide();
}this.element.data({type:"button",button:this});
},_wrap:function(){this.element=this.element.wrap("<li></li>").parent();
},overflowHidden:function(){this.element.addClass(J);
},select:function(ao){if(ao===am){ao=false;
}if(this.options.isChild){this.element.toggleClass(Z,ao);
}else{this.element.find(".k-button").toggleClass(Z,ao);
}this.options.selected=ao;
}});
x.toolbar.OverflowButton=M;
x.toolbar.registerComponent("button",ai,M);
var j=w.extend({createButtons:function(ao){var at=this.options;
var ar=at.buttons||[];
var aq;
for(var ap=0;
ap<ar.length;
ap++){if(!ar[ap].uid){ar[ap].uid=x.guid();
}aq=new ao(b.extend({mobile:at.mobile,isChild:true,type:"button"},ar[ap]),this.toolbar);
aq.element.appendTo(this.element);
}},refresh:function(){this.element.children().filter(":not('."+ab+"'):first").addClass(s);
this.element.children().filter(":not('."+ab+"'):last").addClass(r);
}});
x.toolbar.ButtonGroup=j;
var aj=j.extend({init:function(ap,aq){var ao=this.element=b("<div></div>");
this.options=ap;
this.toolbar=aq;
this.addIdAttr();
if(ap.align){ao.addClass("k-align-"+ap.align);
}this.createButtons(ai);
this.attributes();
this.addUidAttr();
this.addOverflowAttr();
this.refresh();
ao.addClass(g);
this.element.data({type:"buttonGroup",buttonGroup:this});
}});
x.toolbar.ToolBarButtonGroup=aj;
var N=j.extend({init:function(ap,aq){var ao=this.element=b("<li></li>");
this.options=ap;
this.toolbar=aq;
this.overflow=true;
this.addOverflowIdAttr();
this.createButtons(M);
this.attributes();
this.addUidAttr();
this.addOverflowAttr();
this.refresh();
ao.addClass((ap.mobile?"":g)+" k-overflow-group");
this.element.data({type:"buttonGroup",buttonGroup:this});
},overflowHidden:function(){this.element.addClass(J);
}});
x.toolbar.OverflowButtonGroup=N;
x.toolbar.registerComponent("buttonGroup",aj,N);
var al=w.extend({init:function(ap,aq){var ao=this.element=b('<div class="'+X+'" tabindex="0"></div>');
this.options=ap;
this.toolbar=aq;
this.mainButton=new ai(b.extend({},ap,{hidden:false}),aq);
this.arrowButton=b('<a class="'+f+" "+Y+'"><span class="'+(ap.mobile?"km-icon km-arrowdown":"k-icon k-i-arrow-s")+'"></span></a>');
this.popupElement=b('<ul class="'+B+'"></ul>');
this.mainButton.element.removeAttr("href tabindex").appendTo(ao);
this.arrowButton.appendTo(ao);
this.popupElement.appendTo(ao);
if(ap.align){ao.addClass("k-align-"+ap.align);
}if(!ap.id){ap.id=ap.uid;
}ao.attr("id",ap.id+"_wrapper");
this.addOverflowAttr();
this.addUidAttr();
this.createMenuButtons();
this.createPopup();
this._navigatable();
this.mainButton.main=true;
this.enable(ap.enable);
if(ap.hidden){this.hide();
}ao.data({type:"splitButton",splitButton:this,kendoPopup:this.popup});
},_navigatable:function(){var ao=this;
ao.popupElement.on("keydown","."+f,function(ap){var aq=b(ap.target).parent();
ap.preventDefault();
if(ap.keyCode===z.ESC||ap.keyCode===z.TAB||ap.altKey&&ap.keyCode===z.UP){ao.toggle();
ao.focus();
}else{if(ap.keyCode===z.DOWN){o(aq,"next").focus();
}else{if(ap.keyCode===z.UP){o(aq,"prev").focus();
}else{if(ap.keyCode===z.SPACEBAR||ap.keyCode===z.ENTER){ao.toolbar.userEvents.trigger("tap",{target:b(ap.target)});
}}}}});
},createMenuButtons:function(){var ar=this.options;
var aq=ar.menuButtons;
var ap;
for(var ao=0;
ao<aq.length;
ao++){ap=new ai(b.extend({mobile:ar.mobile,type:"button",click:ar.click},aq[ao]),this.toolbar);
ap.element.wrap("<li></li>").parent().appendTo(this.popupElement);
}},createPopup:function(){var ap=this.options;
var ao=this.element;
this.popupElement.attr("id",ap.id+"_optionlist").attr(y,ap.rootUid);
if(ap.mobile){this.popupElement=c(this.popupElement);
}this.popup=this.popupElement.kendoPopup({appendTo:ap.mobile?b(ap.mobile).children(".km-pane"):null,anchor:ao,isRtl:this.toolbar._isRtl,copyAnchorStyles:false,animation:ap.animation,open:d,activate:function(){this.element.find(":kendoFocusable").first().focus();
},close:function(){ao.focus();
}}).data("kendoPopup");
this.popup.element.on(l,"a.k-button",S);
},remove:function(){this.popup.element.off(l,"a.k-button");
this.popup.destroy();
this.element.remove();
},toggle:function(){this.popup.toggle();
},enable:function(ao){if(ao===am){ao=true;
}this.mainButton.enable(ao);
this.options.enable=ao;
},focus:function(){this.element.focus();
},hide:function(){if(this.popup){this.popup.close();
}this.element.addClass(ab).hide();
this.options.hidden=true;
},show:function(){this.element.removeClass(ab).hide();
this.options.hidden=false;
}});
x.toolbar.ToolBarSplitButton=al;
var P=w.extend({init:function(at,au){var ao=this.element=b('<li class="'+X+'"></li>'),ar=at.menuButtons,aq;
this.options=at;
this.toolbar=au;
this.overflow=true;
this.mainButton=new M(b.extend({isChild:true},at));
this.mainButton.element.appendTo(ao);
for(var ap=0;
ap<ar.length;
ap++){aq=new M(b.extend({mobile:at.mobile,isChild:true},ar[ap]),this.toolbar);
aq.element.appendTo(ao);
}this.addUidAttr();
this.addOverflowAttr();
this.mainButton.main=true;
ao.data({type:"splitButton",splitButton:this});
},overflowHidden:function(){this.element.addClass(J);
}});
x.toolbar.OverflowSplitButton=P;
x.toolbar.registerComponent("splitButton",al,P);
var ak=w.extend({init:function(ap,aq){var ao=this.element=b("<div>&nbsp;</div>");
this.element=ao;
this.options=ap;
this.toolbar=aq;
this.attributes();
this.addIdAttr();
this.addUidAttr();
this.addOverflowAttr();
ao.addClass(W);
ao.data({type:"separator",separator:this});
}});
var O=w.extend({init:function(ap,aq){var ao=this.element=b("<li>&nbsp;</li>");
this.element=ao;
this.options=ap;
this.toolbar=aq;
this.overflow=true;
this.attributes();
this.addUidAttr();
this.addOverflowIdAttr();
ao.addClass(W);
ao.data({type:"separator",separator:this});
},overflowHidden:function(){this.element.addClass(J);
}});
x.toolbar.registerComponent("separator",ak,O);
var ac=w.extend({init:function(aq,ap,ar){var ao=v(aq)?aq(ap):aq;
if(!(ao instanceof jQuery)){ao=b("<div></div>").html(ao);
}else{ao=ao.wrap("<div></div>").parent();
}this.element=ao;
this.options=ap;
this.options.type="template";
this.toolbar=ar;
this.attributes();
this.addUidAttr();
this.addIdAttr();
this.addOverflowAttr();
ao.data({type:"template",template:this});
}});
x.toolbar.TemplateItem=ac;
var Q=w.extend({init:function(aq,ap,ar){var ao=v(aq)?b(aq(ap)):b(aq);
if(!(ao instanceof jQuery)){ao=b("<li></li>").html(ao);
}else{ao=ao.wrap("<li></li>").parent();
}this.element=ao;
this.options=ap;
this.options.type="template";
this.toolbar=ar;
this.overflow=true;
this.attributes();
this.addUidAttr();
this.addOverflowIdAttr();
this.addOverflowAttr();
ao.data({type:"template",template:this});
},overflowHidden:function(){this.element.addClass(J);
}});
x.toolbar.OverflowTemplateItem=Q;
function d(){var ao=this.options.anchor,ap=ao.outerWidth(),aq;
x.wrap(this.element).addClass("k-split-wrapper");
if(this.element.css("box-sizing")!=="border-box"){aq=ap-(this.element.outerWidth()-this.element.width());
}else{aq=ap;
}this.element.css({fontFamily:ao.css("font-family"),"min-width":aq});
}function af(ao){if(!ao.target.is(".k-toggle-button")){ao.target.toggleClass(Z,ao.type=="press");
}}function c(ao){ao=b(ao);
return ao.hasClass("km-actionsheet")?ao.closest(".km-popup-wrapper"):ao.addClass("km-widget km-actionsheet").wrap('<div class="km-actionsheet-wrapper km-actionsheet-tablet km-widget km-popup"></div>').parent().wrap('<div class="km-popup-wrapper k-popup"></div>').parent();
}function S(ao){ao.preventDefault();
}function o(aq,ap){var ar=ap==="next"?b.fn.next:b.fn.prev;
var at=ap==="next"?b.fn.first:b.fn.last;
var ao=ar.call(aq);
if(ao.is(":kendoFocusable")||!ao.length){return ao;
}if(ao.find(":kendoFocusable").length){return at.call(ao.find(":kendoFocusable"));
}return o(ao,ap);
}var q=k.extend({init:function(ao){this.name=ao;
this.buttons=[];
},add:function(ao){this.buttons[this.buttons.length]=ao;
},remove:function(ao){var ap=b.inArray(ao,this.buttons);
this.buttons.splice(ap,1);
},select:function(ao){var aq;
for(var ap=0;
ap<this.buttons.length;
ap++){aq=this.buttons[ap];
aq.select(false);
}ao.select(true);
if(ao.twin()){ao.twin().select(true);
}}});
var ag=an.extend({init:function(ao,aq){var ar=this;
an.fn.init.call(ar,ao,aq);
aq=ar.options;
ao=ar.wrapper=ar.element;
ao.addClass(ah+" k-widget");
this.uid=x.guid();
this._isRtl=x.support.isRtl(ao);
this._groups={};
ao.attr(y,this.uid);
ar.isMobile=typeof aq.mobile==="boolean"?aq.mobile:ar.element.closest(".km-root")[0];
ar.animation=ar.isMobile?{open:{effects:"fade"}}:{};
if(ar.isMobile){ao.addClass("km-widget");
t="km-icon";
u="km-";
f="km-button";
g="km-buttongroup km-widget";
Z="km-state-active";
aa="km-state-disabled";
}if(aq.resizable){ar._renderOverflow();
ao.addClass(V);
ar.overflowUserEvents=new x.UserEvents(ar.element,{threshold:5,allowSelection:true,filter:"."+E,tap:U(ar._toggleOverflow,ar)});
ar._resizeHandler=x.onResize(function(){ar.resize();
});
}else{ar.popup={element:b([])};
}if(aq.items&&aq.items.length){for(var ap=0;
ap<aq.items.length;
ap++){ar.add(aq.items[ap]);
}}ar.userEvents=new x.UserEvents(document,{threshold:5,allowSelection:true,filter:"["+y+"="+this.uid+"] a."+f+", ["+y+"="+this.uid+"] ."+G,tap:U(ar._buttonClick,ar),press:af,release:af});
ar.element.on(l,"a.k-button",S);
ar._navigatable();
if(aq.resizable){ar.popup.element.on(l,+"a.k-button",S);
}if(aq.resizable){this._toggleOverflowAnchor();
}x.notify(ar);
},events:[l,ad,C,m,L,H],options:{name:"ToolBar",items:[],resizable:true,mobile:null},addToGroup:function(ao,aq){var ap;
if(!this._groups[aq]){ap=this._groups[aq]=new q();
}else{ap=this._groups[aq];
}ap.add(ao);
return ap;
},destroy:function(){var ao=this;
ao.element.find("."+X).each(function(aq,ap){b(ap).data("kendoPopup").destroy();
});
ao.element.off(l,"a.k-button");
ao.userEvents.destroy();
if(ao.options.resizable){x.unbindResize(ao._resizeHandler);
ao.overflowUserEvents.destroy();
ao.popup.element.off(l,"a.k-button");
ao.popup.destroy();
}an.fn.destroy.call(ao);
},add:function(ar){var ao=n[ar.type],av=ar.template,ax,aw=this,aq=aw.isMobile?"":"k-item k-state-default",at=ar.overflowTemplate,au;
b.extend(ar,{uid:x.guid(),animation:aw.animation,mobile:aw.isMobile,rootUid:aw.uid});
if(ar.menuButtons){for(var ap=0;
ap<ar.menuButtons.length;
ap++){b.extend(ar.menuButtons[ap],{uid:x.guid()});
}}if(av&&!at){ar.overflow=K;
}else{if(!ar.overflow){ar.overflow=F;
}}if(ar.overflow!==K&&aw.options.resizable){if(at){au=new Q(at,ar,aw);
}else{if(ao){au=new ao.overflow(ar,aw);
au.element.addClass(aq);
}}if(au){if(ar.overflow===F){au.overflowHidden();
}au.element.appendTo(aw.popup.container);
aw.angular("compile",function(){return{elements:au.element.get()};
});
}}if(ar.overflow!==D){if(av){ax=new ac(av,ar,aw);
}else{if(ao){ax=new ao.toolbar(ar,aw);
}}if(ax){if(aw.options.resizable){ax.element.appendTo(aw.element).css("visibility","hidden");
aw._shrink(aw.element.innerWidth());
ax.element.css("visibility","visible");
}else{ax.element.appendTo(aw.element);
}aw.angular("compile",function(){return{elements:ax.element.get()};
});
}}},_getItem:function(ao){var ap,at,ar,aq=this.options.resizable,au;
ap=this.element.find(ao);
if(!ap.length){ap=b(".k-split-container[data-uid="+this.uid+"]").find(ao);
}au=ap.length?ap.data("type"):"";
at=ap.data(au);
if(at){if(at.main){ap=ap.parent("."+X);
au="splitButton";
at=ap.data(au);
}if(aq){ar=at.twin();
}}else{if(aq){ap=this.popup.element.find(ao);
au=ap.length?ap.data("type"):"";
ar=ap.data(au);
if(ar&&ar.main){ap=ap.parent("."+X);
au="splitButton";
ar=ap.data(au);
}}}return{type:au,toolbar:at,overflow:ar};
},remove:function(ao){var ap=this._getItem(ao);
if(ap.toolbar){ap.toolbar.remove();
}if(ap.overflow){ap.overflow.remove();
}this.resize(true);
},hide:function(ao){var ap=this._getItem(ao);
if(ap.toolbar){if(ap.toolbar.options.type==="button"&&ap.toolbar.options.isChild){ap.toolbar.hide();
ap.toolbar.getParentGroup().refresh();
}else{if(!ap.toolbar.options.hidden){ap.toolbar.hide();
}}}if(ap.overflow){if(ap.overflow.options.type==="button"&&ap.overflow.options.isChild){ap.overflow.hide();
ap.overflow.getParentGroup().refresh();
}else{if(!ap.overflow.options.hidden){ap.overflow.hide();
}}}this.resize(true);
},show:function(ao){var ap=this._getItem(ao);
if(ap.toolbar){if(ap.toolbar.options.type==="button"&&ap.toolbar.options.isChild){ap.toolbar.show();
ap.toolbar.getParentGroup().refresh();
}else{if(ap.toolbar.options.hidden){ap.toolbar.show();
}}}if(ap.overflow){if(ap.overflow.options.type==="button"&&ap.overflow.options.isChild){ap.toolbar.show();
ap.overflow.getParentGroup().refresh();
}else{if(ap.overflow.options.hidden){ap.overflow.show();
}}}this.resize(true);
},enable:function(ao,ap){var aq=this._getItem(ao);
if(typeof ap=="undefined"){ap=true;
}if(aq.toolbar){aq.toolbar.enable(ap);
}if(aq.overflow){aq.overflow.enable(ap);
}},getSelectedFromGroup:function(ao){return this.element.find("."+ae+"[data-group='"+ao+"']").filter("."+Z);
},toggle:function(ao,ap){var aq=b(ao),ar=aq.data("button");
if(ar.options.togglable){if(ap===am){ap=true;
}ar.toggle(ap,true);
}},_renderOverflow:function(){var ar=this,aq=n.overflowContainer,ap=ar._isRtl,ao=ap?"left":"right";
ar.overflowAnchor=b(n.overflowAnchor).addClass(f);
ar.element.append(ar.overflowAnchor);
if(ar.isMobile){ar.overflowAnchor.append('<span class="km-icon km-more"></span>');
aq=c(aq);
}else{ar.overflowAnchor.append('<span class="k-icon k-i-arrow-s"></span>');
}ar.popup=new x.ui.Popup(aq,{origin:"bottom "+ao,position:"top "+ao,anchor:ar.overflowAnchor,isRtl:ap,animation:ar.animation,appendTo:ar.isMobile?b(ar.isMobile).children(".km-pane"):null,copyAnchorStyles:false,open:function(at){var au=x.wrap(ar.popup.element).addClass("k-overflow-wrapper");
if(!ar.isMobile){au.css("margin-left",(ap?-1:1)*((au.outerWidth()-au.width())/2+1));
}else{ar.popup.container.css("max-height",parseFloat(b(".km-content:visible").innerHeight())-15+"px");
}if(ar.trigger(L)){at.preventDefault();
}},activate:function(){this.element.find(":kendoFocusable").first().focus();
},close:function(at){if(ar.trigger(H)){at.preventDefault();
}this.element.focus();
}});
ar.popup.element.on("keydown","."+f,function(at){var ax=b(at.target),aw=ax.parent(),av=aw.is("."+g)||aw.is("."+X),au;
at.preventDefault();
if(at.keyCode===z.ESC||at.keyCode===z.TAB||at.altKey&&at.keyCode===z.UP){ar._toggleOverflow();
ar.overflowAnchor.focus();
}else{if(at.keyCode===z.DOWN){au=!av||av&&ax.is(":last-child")?aw:ax;
o(au,"next").focus();
}else{if(at.keyCode===z.UP){au=!av||av&&ax.is(":first-child")?aw:ax;
o(au,"prev").focus();
}else{if(at.keyCode===z.SPACEBAR||at.keyCode===z.ENTER){ar.userEvents.trigger("tap",{target:b(at.target)});
}}}}});
if(ar.isMobile){ar.popup.container=ar.popup.element.find("."+I);
}else{ar.popup.container=ar.popup.element;
}ar.popup.container.attr(y,this.uid);
},_toggleOverflowAnchor:function(){var ao=false;
if(this.options.mobile){ao=this.popup.element.find("."+I).children(":not(."+J+", ."+R+")").length>0;
}else{ao=this.popup.element.children(":not(."+J+", ."+R+")").length>0;
}if(ao){this.overflowAnchor.css({visibility:"visible",width:""});
}else{this.overflowAnchor.css({visibility:"hidden",width:"1px"});
}},_buttonClick:function(ao){var ax=this,au,aw,at,av,ar=ao.target.closest("."+Y).length,aq,ap,ay;
ao.preventDefault();
if(ar){ax._toggle(ao);
return;
}aw=b(ao.target).closest("."+f,ax.element);
if(aw.hasClass(E)){return;
}at=aw.data("button");
if(!at&&ax.popup){aw=b(ao.target).closest("."+G,ax.popup.container);
at=aw.parent("li").data("button");
}if(!at||!at.options.enable){return;
}if(at.options.togglable){aq=v(at.toggleHandler)?at.toggleHandler:null;
at.toggle(!at.options.selected,true);
ap={target:aw,group:at.options.group,checked:at.options.selected,id:at.options.id};
if(aq){aq.call(ax,ap);
}ax.trigger(ad,ap);
}else{aq=v(at.clickHandler)?at.clickHandler:null;
ap={sender:ax,target:aw,id:at.options.id};
if(aq){aq.call(ax,ap);
}ax.trigger(l,ap);
}if(at.options.url){if(at.options.attributes&&at.options.attributes.target){ay=at.options.attributes.target;
}window.open(at.options.url,ay||"_self");
}if(aw.hasClass(G)){ax.popup.close();
}av=aw.closest(".k-split-container");
if(av[0]){au=av.data("kendoPopup");
(au?au:av.parents(".km-popup-wrapper").data("kendoPopup")).close();
}},_navigatable:function(){var ao=this;
ao.element.attr("tabindex",0).focus(function(){var ap=b(this).find(":kendoFocusable:first");
if(ap.is("."+E)){ap=o(ap,"next");
}ap[0].focus();
}).on("keydown",U(ao._keydown,ao));
},_keydown:function(ao){var ax=b(ao.target),au=ao.keyCode,at=this.element.children(":not(.k-separator):visible");
if(au===z.TAB){var ap=ax.parentsUntil(this.element).last(),av=false,aq=false;
if(!ap.length){ap=ax;
}if(ap.is("."+E)){if(ao.shiftKey){ao.preventDefault();
}if(at.last().is(":kendoFocusable")){at.last().focus();
}else{at.last().find(":kendoFocusable").last().focus();
}}if(!ao.shiftKey&&at.index(ap)===at.length-1){if(ap.is("."+g)){av=ax.is(":last-child");
}else{av=true;
}}if(ao.shiftKey&&at.index(ap)===1){if(ap.is("."+g)){aq=ax.is(":first-child");
}else{aq=true;
}}if(av&&this.overflowAnchor&&this.overflowAnchor.css("visibility")!=="hidden"){ao.preventDefault();
this.overflowAnchor.focus();
}if(aq){ao.preventDefault();
this.wrapper.prev(":kendoFocusable").focus();
}}if(ao.altKey&&au===z.DOWN){var aw=b(document.activeElement).data("splitButton");
var ar=b(document.activeElement).is("."+E);
if(aw){aw.toggle();
}else{if(ar){this._toggleOverflow();
}}return;
}if((au===z.SPACEBAR||au===z.ENTER)&&!ax.is("input, checkbox")){ao.preventDefault();
if(ax.is("."+X)){ax=ax.children().first();
}this.userEvents.trigger("tap",{target:ax});
return;
}},_toggle:function(ao){var aq=b(ao.target).closest("."+X).data("splitButton"),ap;
ao.preventDefault();
if(!aq.options.enable){return;
}if(aq.popup.element.is(":visible")){ap=this.trigger(m,{target:aq.element});
}else{ap=this.trigger(C,{target:aq.element});
}if(!ap){aq.toggle();
}},_toggleOverflow:function(){this.popup.toggle();
},_resize:function(ap){var ao=ap.width;
if(!this.options.resizable){return;
}this.popup.close();
this._shrink(ao);
this._stretch(ao);
this._markVisibles();
this._toggleOverflowAnchor();
},_childrenWidth:function(){var ao=0;
this.element.children(":visible:not('."+ab+"')").each(function(){ao+=b(this).outerWidth(true);
});
return Math.ceil(ao);
},_shrink:function(ap){var ao,ar;
if(ap<this._childrenWidth()){ar=this.element.children(":visible:not([data-overflow='never'], ."+E+")");
for(var aq=ar.length-1;
aq>=0;
aq--){ao=ar.eq(aq);
if(ap>this._childrenWidth()){break;
}else{this._hideItem(ao);
}}}},_stretch:function(ap){var ao,aq;
if(ap>this._childrenWidth()){aq=this.element.children(":hidden:not('."+ab+"')");
for(var ar=0;
ar<aq.length;
ar++){ao=aq.eq(ar);
if(ap<this._childrenWidth()||!this._showItem(ao,ap)){break;
}}}},_hideItem:function(ao){ao.hide();
if(this.popup){this.popup.container.find(">li[data-uid='"+ao.data("uid")+"']").removeClass(J);
}},_showItem:function(ap,ao){if(ap.length&&ao>this._childrenWidth()+ap.outerWidth(true)){ap.show();
if(this.popup){this.popup.container.find(">li[data-uid='"+ap.data("uid")+"']").addClass(J);
}return true;
}return false;
},_markVisibles:function(){var ao=this.popup.container.children(),ap=this.element.children(":not(.k-overflow-anchor)"),aq=ao.filter(":not(.k-overflow-hidden)"),ar=ap.filter(":visible");
ao.add(ap).removeClass(p+" "+A);
aq.first().add(ar.first()).addClass(p);
aq.last().add(ar.last()).addClass(A);
}});
x.ui.plugin(ag);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
