(function(b,a){a("kendo.validator",["kendo.core"],b);
}(function(){var a={id:"validator",name:"Validator",category:"web",description:"The Validator offers an easy way to do a client-side form validation.",depends:["core"]};
(function(b,y){var m=window.kendo,C=m.ui.Widget,q=".kendoValidator",k="k-invalid-msg",l=new RegExp(k,"i"),j="k-invalid",B="k-valid",f=/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/i,z=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i,i=":input:not(:button,[type=submit],[type=reset],[disabled],[readonly])",d=":checkbox:not([disabled],[readonly])",r="[type=number],[type=range]",c="blur",o="name",g="form",p="novalidate",v=b.proxy,u=function(E,D){if(typeof D==="string"){D=new RegExp("^(?:"+D+")$");
}return D.test(E);
},n=function(D,F,E){var G=D.val();
if(D.filter(F).length&&G!==""){return u(G,E);
}return true;
},h=function(D,E){if(D.length){return D[0].attributes[E]!=null;
}return false;
};
if(!m.ui.validator){m.ui.validator={rules:{},messages:{}};
}function w(D){var F=m.ui.validator.ruleResolvers||{},G={},E;
for(E in F){b.extend(true,G,F[E].resolve(D));
}return G;
}function e(D){return D.replace(/&amp/g,"&amp;").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");
}function s(D){D=(D+"").split(".");
if(D.length>1){return D[1].length;
}return 0;
}function t(D){if(b.parseHTML){return b(b.parseHTML(D));
}return b(D);
}function x(G,H){var E=b(),F,D;
for(var I=0,J=G.length;
I<J;
I++){F=G[I];
if(l.test(F.className)){D=F.getAttribute(m.attr("for"));
if(D===H){E=E.add(F);
}}}return E;
}var A=C.extend({init:function(D,E){var G=this,F=w(D),H="["+m.attr("validate")+"!=false]";
E=E||{};
E.rules=b.extend({},m.ui.validator.rules,F.rules,E.rules);
E.messages=b.extend({},m.ui.validator.messages,F.messages,E.messages);
C.fn.init.call(G,D,E);
G._errorTemplate=m.template(G.options.errorTemplate);
if(G.element.is(g)){G.element.attr(p,p);
}G._inputSelector=i+H;
G._checkboxSelector=d+H;
G._errors={};
G._attachEvents();
G._isValidated=false;
},events:["validate","change"],options:{name:"Validator",errorTemplate:'<span class="k-widget k-tooltip k-tooltip-validation"><span class="k-icon k-i-warning"> </span> #=message#</span>',messages:{required:"{0} is required",pattern:"{0} is not valid",min:"{0} should be greater than or equal to {1}",max:"{0} should be smaller than or equal to {1}",step:"{0} is not valid",email:"{0} is not valid email",url:"{0} is not valid URL",date:"{0} is not valid date",dateCompare:"End date should be greater than or equal to the start date"},rules:{required:function(E){var D=E.filter("[type=checkbox]").length&&!E.is(":checked"),F=E.val();
return !(h(E,"required")&&(F===""||!F||D));
},pattern:function(D){if(D.filter("[type=text],[type=email],[type=url],[type=tel],[type=search],[type=password]").filter("[pattern]").length&&D.val()!==""){return u(D.val(),D.attr("pattern"));
}return true;
},min:function(D){if(D.filter(r+",["+m.attr("type")+"=number]").filter("[min]").length&&D.val()!==""){var E=parseFloat(D.attr("min"))||0,F=m.parseFloat(D.val());
return E<=F;
}return true;
},max:function(D){if(D.filter(r+",["+m.attr("type")+"=number]").filter("[max]").length&&D.val()!==""){var E=parseFloat(D.attr("max"))||0,F=m.parseFloat(D.val());
return E>=F;
}return true;
},step:function(E){if(E.filter(r+",["+m.attr("type")+"=number]").filter("[step]").length&&E.val()!==""){var F=parseFloat(E.attr("min"))||0,H=parseFloat(E.attr("step"))||1,I=parseFloat(E.val()),D=s(H),G;
if(D){G=Math.pow(10,D);
return Math.floor((I-F)*G)%(H*G)/Math.pow(100,D)===0;
}return(I-F)%H===0;
}return true;
},email:function(D){return n(D,"[type=email],["+m.attr("type")+"=email]",f);
},url:function(D){return n(D,"[type=url],["+m.attr("type")+"=url]",z);
},date:function(D){if(D.filter("[type^=date],["+m.attr("type")+"=date]").length&&D.val()!==""){return m.parseDate(D.val(),D.attr(m.attr("format")))!==null;
}return true;
}},validateOnBlur:true},destroy:function(){C.fn.destroy.call(this);
this.element.off(q);
},value:function(){if(!this._isValidated){return false;
}return this.errors().length===0;
},_submit:function(D){if(!this.validate()){D.stopPropagation();
D.stopImmediatePropagation();
D.preventDefault();
return false;
}return true;
},_checkElement:function(D){var E=this.value();
this.validateInput(D);
if(this.value()!==E){this.trigger("change");
}},_attachEvents:function(){var D=this;
if(D.element.is(g)){D.element.on("submit"+q,v(D._submit,D));
}if(D.options.validateOnBlur){if(!D.element.is(i)){D.element.on(c+q,D._inputSelector,function(){D._checkElement(b(this));
});
D.element.on("click"+q,D._checkboxSelector,function(){D._checkElement(b(this));
});
}else{D.element.on(c+q,function(){D._checkElement(D.element);
});
if(D.element.is(d)){D.element.on("click"+q,function(){D._checkElement(D.element);
});
}}}},validate:function(){var E;
var D;
var I=false;
var H;
var G=this.value();
this._errors={};
if(!this.element.is(i)){var F=false;
E=this.element.find(this._inputSelector);
for(D=0,H=E.length;
D<H;
D++){if(!this.validateInput(E.eq(D))){F=true;
}}I=!F;
}else{I=this.validateInput(this.element);
}this.trigger("validate",{valid:I});
if(G!==I){this.trigger("change");
}return I;
},validateInput:function(F){F=b(F);
this._isValidated=true;
var M=this,L=M._errorTemplate,K=M._checkValidity(F),N=K.valid,D="."+k,E=F.attr(o)||"",G=M._findMessageContainer(E).add(F.next(D).filter(function(){var O=b(this);
if(O.filter("["+m.attr("for")+"]").length){return O.attr(m.attr("for"))===E;
}return true;
})).hide(),J;
F.removeAttr("aria-invalid");
if(!N){J=M._extractMessage(F,K.key);
M._errors[E]=J;
var I=t(L({message:e(J)}));
var H=G.attr("id");
M._decorateMessageContainer(I,E);
if(H){I.attr("id",H);
}if(!G.replaceWith(I).length){I.insertAfter(F);
}I.show();
F.attr("aria-invalid",true);
}else{delete M._errors[E];
}F.toggleClass(j,!N);
F.toggleClass(B,N);
return N;
},hideMessages:function(){var F=this,D="."+k,E=F.element;
if(!E.is(i)){E.find(D).hide();
}else{E.next(D).hide();
}},_findMessageContainer:function(E){var H=m.ui.validator.messageLocators,I,D=b();
for(var F=0,G=this.element.length;
F<G;
F++){D=D.add(x(this.element[F].getElementsByTagName("*"),E));
}for(I in H){D=D.add(H[I].locate(this.element,E));
}return D;
},_decorateMessageContainer:function(D,E){var F=m.ui.validator.messageLocators,G;
D.addClass(k).attr(m.attr("for"),E||"");
for(G in F){F[G].decorate(D,E);
}D.attr("role","alert");
},_extractMessage:function(F,G){var H=this,D=H.options.messages[G],E=F.attr(o);
D=m.isFunction(D)?D(F):D;
return m.format(F.attr(m.attr(G+"-msg"))||F.attr("validationMessage")||F.attr("title")||D||"",E,F.attr(G)||F.attr(m.attr(G)));
},_checkValidity:function(D){var F=this.options.rules,E;
for(E in F){if(!F[E].call(this,D)){return{valid:false,key:E};
}}return{valid:true};
},errors:function(){var F=[],E=this._errors,D;
for(D in E){F.push(E[D]);
}return F;
}});
m.ui.plugin(A);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
