(function(a,j){Type.registerNamespace("Telerik.Web");
Type.registerNamespace("Telerik.Web.UI");
var c=window.document.documentElement;
var i=a.proxy;
var b=Telerik.Web.UI;
var e=b.EventNamesMap;
var d=e.down;
var h=e.move;
var k=e.up;
var f=".millionColorsPalette";
var g=".millionCustomColorsPalette";
$telerik.toColorPicker=function(l){return l;
};
$telerik.findColorPicker=$find;
a.registerEnum(b,"PaletteModes",{WebPalette:1,RGBSliders:2,HSB:4,HSV:8,All:(1+2+4+8)});
b.ColorPickerColorChangeEventArgs=function(l){b.ColorPickerColorChangeEventArgs.initializeBase(this);
this._oldColor=l;
};
b.ColorPickerColorChangeEventArgs.prototype={get_oldColor:function(){return this._oldColor;
}};
b.ColorPickerColorChangeEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorChangeEventArgs",Sys.EventArgs);
b.ColorPickerColorPreviewEventArgs=function(l){b.ColorPickerColorPreviewEventArgs.initializeBase(this);
this._color=l;
};
b.ColorPickerColorPreviewEventArgs.prototype={get_color:function(){return this._color;
}};
b.ColorPickerColorPreviewEventArgs.registerClass("Telerik.Web.UI.ColorPickerColorPreviewEventArgs",Sys.EventArgs);
b.ColorPickerColorSelectingEventArgs=b.ColorPickerColorPreviewEventArgs;
b.RadColorPicker=function(l){b.RadColorPicker.initializeBase(this,[l]);
this._selectedColor=null;
this._selectedColorName="";
this._autoPostBack=false;
this._enabled=true;
this._previewColor=true;
this._showIcon=false;
this._showEmptyColor=true;
this._lastPreviewColor="";
this._elementsByColor=[];
this._indexByColor=[];
this._mouseUpHandler=null;
this._localization=null;
this._popupBehavior=null;
this._paletteDisplayed=false;
this._uniqueID=null;
this._columns=18;
this._items=null;
this._width=0;
this._skin="Default";
this._overlay=false;
this._keepInScreenBounds=true;
this._isTouchSkin=false;
this._paletteModes=b.PaletteModes.WebPalette;
this._selectedTab=null;
this._selectedContainer=null;
this._tabStrip=null;
this._multiPage=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this._rgbSlidersDefaultValue=255;
this._rgbSlidersDefaultSize=217;
this._redInput=null;
this._greenInput=null;
this._blueInput=null;
this._hexColorInput=null;
this._applyButton=null;
this._defaultRGBWidth=270;
this._rgbSlidersMinSize=115;
this._eventStartedInControl=false;
this._inputAvoidRecursion=false;
this._sliderAvoidRecursion=false;
this._shouldPreventColorPreview=false;
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this._millionColorsSliderWidth="22px";
this._millionColorsSliderHeight="162px";
this._millionColorsInputs=null;
this._millionColorsHandleDragging=null;
this._millionColorsAvoidRecursion=false;
this._millionColorsSliderAvoidRecursion=false;
this._millionColorsHSVPaletteSize={width:"160px",height:"160px"};
this._millionColorsHSBPaletteSize={width:"256px",height:"160px"};
this._rightToLeft=false;
this._enableCustomColor=false;
this._customColorOkButton=null;
this._customColorCancelButton=null;
this._customColorPalette=null;
this._customColorPopupBehavior=null;
this._customColorModalExtender=null;
this._customColorPreviewElement=null;
this._hexCustomColorInput=null;
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
this._millionCustomColorsInputs={r:null,g:null,b:null,h:null,s:null,l:null};
this._millionCustomColorsHandleDragging=null;
this._showRecentColors=false;
this._recentColorsWrapper=null;
this._recentColors=[];
this._recentElementsByColor=[];
this._accessKey="";
this._tabIndex=0;
this._iconLink=null;
this._paletteSizes={};
this._renderer=null;
this.ShowPalette=this.showPalette;
this.HidePalette=this.hidePalette;
this.GetIconContainer=this.getIconContainer;
this.GetPaletteContainer=this.getPaletteContainer;
};
b.RadColorPicker.prototype={initialize:function(){b.RadColorPicker.callBaseMethod(this,"initialize");
this._renderer=this._getRenderer();
this._calculateRenderSettings();
var l=this.get_element();
if($telerik.isRightToLeft(l)){Sys.UI.DomElement.addCssClass(l,"RadColorPickerRTL");
Sys.UI.DomElement.addCssClass(l,"RadColorPickerRTL_"+this._skin);
this._rightToLeft=true;
}this._initializeFields();
this._localization=eval(this._localization);
if(!this._showIcon){this._paletteDisplayed=true;
this._initializeColorElementsArray();
this._setElementsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
}this._initializeEventHandlers();
this._applyAccessKey();
this.set_selectedColor(this._selectedColor,false,true);
if(this._items){this._items=eval(this._items);
}this.raiseEvent("load");
},_getRenderer:function(){if(this._renderMode===b.RenderMode.Classic){var l=this.isSkin("Silk")||this.isSkin("Glow");
var m={isSilkOrGlowSkin:l,isTouchSkin:this._isTouchSkin};
return new b.ColorPicker.ClassicRenderer(m);
}else{if(this._renderMode===b.RenderMode.Lite){return new b.ColorPicker.LightweightRenderer();
}else{throw Error("RadColorPicker with ID: "+this.get_id()+" has no defined RenderMode.");
}}},isSkin:function(l){return Sys.UI.DomElement.containsCssClass(this.get_element(),"RadColorPicker_"+l);
},_initializeFields:function(){var m=this.get_id();
this._wrapperElement=$get(m);
this._previewElement=$get(m+"_preview");
this._emptyColorElement=$get(m+"_emptycolor");
this._iconElement=$get(m+"_icon");
var t=this._iconWrapperElement=$get(m+"_label");
if(t){this._iconLink=$telerik.getChildrenByTagName(t,"a")[0];
this._iconColorElement=$telerik.getChildrenByTagName(t,"em")[0];
}var y=this._paletteWrapperElement=$get(m+"_palette");
if(y){var B=this._tabStrip=$telerik.getChildByClassName(y,"rcpTabs");
this._multiPage=$telerik.getChildByClassName(y,"rcpViews");
var C=this._webPalettePageView=$get(m+"_webPalette");
this._webPaletteWrapper=(C)?$telerik.getChildByClassName(C,"rcpWebPalette"):null;
var z=this._rgbPageView=$get(m+"_rgbSliders");
this._millionColorsPageView=$get(m+"_millionColors");
this._selectedContainer=(C)?C:(z?z:this._millionColorsPageView);
if(B){var D=this.isModeEnabled(b.PaletteModes.WebPalette);
var A=this.isModeEnabled(b.PaletteModes.RGBSliders);
var q=this.isModeEnabled(b.PaletteModes.HSB);
var r=this.isModeEnabled(b.PaletteModes.HSV);
var w=B.getElementsByTagName("a");
for(var s=0;
s<w.length;
s++){if(D){this._addRelAttribute(w[s],"_webPalette",m);
D=false;
continue;
}if(A){this._addRelAttribute(w[s],"_rgbSliders",m);
A=false;
continue;
}if(q){this._addRelAttribute(w[s],"_millionColors",m);
q=false;
continue;
}if(r){this._addRelAttribute(w[s],"_millionColors",m);
r=false;
}}for(var u=0,v=w.length;
u<v;
u++){this._initializeTabHandler(w[u]);
}this._selectedTab=$telerik.getElementByClassName(B,"rcpSelectedTab","li");
}this._recentColorsWrapper=$get(m+"_recentColors");
var o=this._header=$telerik.getChildByClassName(y,"rcpHeader");
if(o){var l=this._applyButton=$telerik.getChildByClassName(o,"rcpApplyButton");
if(l){this._initializeApplyHandler(l);
}var n=this._customColorButton=$telerik.getChildByClassName(o,"rcpCustomColorButton");
if(n){this._initializeCustomColorHandler(n);
}}}this._redInput=$get(m+"_redInput");
this._greenInput=$get(m+"_greenInput");
this._blueInput=$get(m+"_blueInput");
var p=this._hexColorInput=$get(m+"_hexInput");
if(this.get_redSlider()){this._initializeRgbInputHandler(this._redInput);
this._initializeRgbInputHandler(this._greenInput);
this._initializeRgbInputHandler(this._blueInput);
this._initializeRgbSliderHandler(this.get_redSlider());
this._initializeRgbSliderHandler(this.get_greenSlider());
this._initializeRgbSliderHandler(this.get_blueSlider());
}if(p){this._initializeHexHandler(p);
}this._millionColorsPalette=$get(m+"_millionColorsPalette");
this._initializeMillionColorsPaletteHandler();
this._millionColorsHandle=$get(m+"_millionColorsHandle");
this._initializeMillionColorsSliderHandler();
var x=this._millionColorsInputs={r:$get(m+"_rInput"),g:$get(m+"_gInput"),b:$get(m+"_bInput"),h:$get(m+"_hInput"),s:$get(m+"_sInput"),l:$get(m+"_lInput"),v:$get(m+"_vInput")};
this._initializeMillionColorsRgbInputHandler(x.r);
this._initializeMillionColorsRgbInputHandler(x.g);
this._initializeMillionColorsRgbInputHandler(x.b);
this._initializeMillionColorsInputHandler(x.h);
this._initializeMillionColorsInputHandler(x.s);
this._initializeMillionColorsInputHandler(x.l);
this._initializeMillionColorsInputHandler(x.v);
},_addRelAttribute:function(m,n,l){if(m){m.rel=l+n;
}},dispose:function(){a(c).offEvent(f);
a(c).offEvent(g);
this._disposeControl("_millionColorsHandleDragging");
this._disposeControl("_popupBehavior");
this._disposeControl("_customColorPopupBehavior");
this._disposeControl("_customColorModalExtender");
this._disposeControl("_millionCustomColorsHandleDragging");
this._disposeHandlers();
this._selectedTab=null;
this._selectedContainer=null;
var r=this._tabStrip;
if(r){var p=r.getElementsByTagName("a");
for(var n=0,o=p.length;
n<o;
n++){$clearHandlers(p[n]);
}}var l=this._accessKeyTextbox;
if(l){$clearHandlers(l);
l.removeAttribute("accessKey");
this._accessKeyTextbox=null;
}this._tabStrip=null;
this._multiPage=null;
this._webPaletteWrapper=null;
this._webPalettePageView=null;
this._rgbPageView=null;
this._millionColorsPageView=null;
this._header=null;
this.set_redSlider(null);
this.set_greenSlider(null);
this.set_blueSlider(null);
this.set_hiddenSlider(null);
this._clearHandlers("_redInput");
this._clearHandlers("_greenInput");
this._clearHandlers("_blueInput");
this._clearHandlers("_hexColorInput");
this._clearHandlers("_applyButton");
this._clearHandlers("_customColorButton");
this._millionColorsPalette=null;
this._millionColorsHandle=null;
this.set_millionColorsSlider(null);
var q=this._millionColorsInputs;
this._clearHandlers(null,q.r);
this._clearHandlers(null,q.g);
this._clearHandlers(null,q.b);
this._clearHandlers(null,q.h);
this._clearHandlers(null,q.s);
this._clearHandlers(null,q.l);
this._clearHandlers(null,q.v);
this._millionColorsInputs=null;
this._paletteSizes=null;
this._elementsByColor=null;
this._indexByColor=null;
this._recentColors=null;
this._recentElementsByColor=null;
this._clearHandlers("_recentColorsWrapper");
this._customColorPreviewElement=null;
this._clearHandlers("_customColorOkButton");
this._clearHandlers("_customColorCancelButton");
this._clearHandlers("_hexCustomColorInput");
this._millionCustomColorsPalette=null;
this._millionCustomColorsHandle=null;
if(this.get_millionCustomColorsSlider()){this.get_millionCustomColorsSlider().dispose();
}this.set_millionCustomColorsSlider(null);
q=this._millionCustomColorsInputs;
this._clearHandlers(null,q.r);
this._clearHandlers(null,q.g);
this._clearHandlers(null,q.b);
this._clearHandlers(null,q.h);
this._clearHandlers(null,q.s);
this._clearHandlers(null,q.l);
this._millionCustomColorsInputs=null;
var m=this._customColorPalette;
if(m){if(m.parentNode){m.parentNode.removeChild(m);
}this._customColorPalette=null;
}b.RadColorPicker.callBaseMethod(this,"dispose");
},repaint:function(){this._setElementsSize();
var l=this._paletteWrapperElement;
if(l){this._setRightRoundedCornerAndShadowHeight(l);
}},_disposeControl:function(m){var l=this[m];
if(l){l.dispose();
this[m]=null;
}},_clearHandlers:function(n,l){var o=(!l);
var m=o?this[n]:l;
if(m){$clearHandlers(m);
if(o){this[n]=null;
}}},_initializeColorElementsArray:function(){var s=this._webPaletteWrapper;
if(!s){return;
}var o=[];
var q=[];
var n=s.getElementsByTagName("a");
for(var p=0,r=n.length;
p<r;
p++){var m=n[p];
if(this._getColorBoxElement(m)){var l=this._getElementColor(m);
o[l]=m;
q[l]=p;
if(p>0){m.setAttribute("tabindex","-1");
}}}this._elementsByColor=o;
this._indexByColor=q;
},_setElementsSize:function(){if($telerik.getInvisibleParent(this.get_element())){return;
}var n=this._selectedContainer;
var m=b.PaletteModes.WebPalette;
var o="_setWebPaletteSize";
if(n==this._rgbPageView){m=b.PaletteModes.RGBSliders;
o="_setRGBSize";
}else{if(n==this._millionColorsPageView){m=(b.PaletteModes.HSB+b.PaletteModes.HSV);
o="_setMillionColorsSize";
}}var p=this._showIcon;
var t=p?this._paletteWrapperElement:this._wrapperElement;
if(!t){return;
}var l=this._getElementsSize(m);
var s=l.width;
this._renderer.setElementInlineWidthStyle(t,s);
this[o](l);
if(!p){var q=this._tabStrip;
if(q){var r=$telerik.getSize(q).height-1;
if(r>0&&parseInt(t.style.paddingBottom,10)!=r){t.style.paddingBottom=r+"px";
}}}if(this._tabStrip){this._renderer.setTabStripWidth(this._tabStrip,this._multiPage,this._skin);
}},_setWebPaletteSize:function(n){var v=this._webPaletteWrapper;
if(!v){return;
}if(this.isModeEnabled(b.PaletteModes.WebPalette)){var u=n.colorBoxSize;
var p=$telerik.isOpera;
var r=n.colorBoxSizeOpera;
var m=v.getElementsByTagName("li");
for(var o=0,q=m.length;
o<q;
o++){var l=m[o];
var t=l.getElementsByTagName("span");
if(t.length>0){var s=t[0];
this._renderer.setColorRectangleDimensions(s,u);
}if(p){l.style.width=r+"px";
}}}},_setRecentColorsSize:function(){var l=this._recentColorsWrapper;
if(this._showRecentColors&&l){l.style.height=this._getRecentColorWrapperSize()+"px";
}},_setRGBSize:function(l){var m=l.sliderSize;
this.get_redSlider().set_width(m);
this.get_greenSlider().set_width(m);
this.get_blueSlider().set_width(m);
},_setMillionColorsSize:function(l){var n=l.sliderSize;
var m=this.get_millionColorsSlider();
this._renderer.setMillionColorsSliderHeight(m,n);
if(this._millionColorsPalette.style.backgroundSize===j){this._setPaletteWidthWhenBackgroundSizeIsUnsupported();
}},_setPaletteWidthWhenBackgroundSizeIsUnsupported:function(){var m=this._isMillionColorsTabSelected();
var l=(m.HSV)?this._millionColorsHSVPaletteSize:this._millionColorsHSBPaletteSize;
this._setPaletteSize(this._millionColorsPalette,l);
},_setPaletteSize:function(l,n){var m=l.style;
m.width=n.width;
m.height=n.height;
},_getElementsSize:function(x){var C=this._paletteSizes;
var D=this._width;
var G=(D>0);
var A=this.getElementContentBox(this._paletteWrapperElement).horizontal;
var H=this._showIcon;
var B=$telerik.getComputedStyle(this._paletteWrapperElement,"boxSizing");
var o=(B==="content-box")?A:0;
var L=H?o:this.getElementBox(this._wrapperElement).horizontal;
var K=A+this._renderer.getElementContentBox(this._multiPage).horizontal;
if(!H){K+=L;
}var w=Math.max(0,K)+this._getMinimumPaletteWidth();
var m,n,I;
if(this.isModeEnabled(b.PaletteModes.WebPalette)&&(x==b.PaletteModes.WebPalette)){var J=this._getWebPaletteElemenentsSize(D,w,K);
m=J.colorSize;
n=J.colorSizeOpera;
D=J.width-L;
C.webPalette=D;
}else{if(this.isModeEnabled(b.PaletteModes.RGBSliders)&&(x==b.PaletteModes.RGBSliders)){var F=this._defaultRGBWidth;
var E=Math.max(this._rgbSlidersMinSize,w);
if(!G){D=this._renderer.getRgbPaletteWidth(F,E);
}if(D<E){D=E;
}I=this._getRGBElemenentsSize(D,K);
D-=L;
C.rgbSliders=D;
}else{var s=this.isModeEnabled(b.PaletteModes.HSB)&&this.isPaletteMode(x,"HSB");
var t=this.isModeEnabled(b.PaletteModes.HSV)&&this.isPaletteMode(x,"HSV");
if(s||t){var p={paletteWrapperElement:this._paletteWrapperElement,multiPage:this._multiPage,millionColorsPalette:this._millionColorsPalette,millionColorsSlider:this._millionColorsSlider,colorPicker:this.get_element()};
I=this._renderer.getHsbSliderHeight(this._millionColorsPalette,this._millionColorsSlider);
var y=this._renderer.getInitialHsbPaletteWidth(p);
var u=Math.max(y,w);
var q=D;
if(!G||(G&&D<u)){q=u;
}q-=L;
C.hsb=q;
var l=this._millionColorsPalette.style.backgroundSize!==j;
var z=this._renderer.getInitialHsvPaletteWidth(l,p);
var v=Math.max(z,w);
var r=D;
if(!G||(G&&D<v)){r=v;
}r-=L;
C.hsv=r;
D=s?q:r;
}}}this._paletteSizes=C;
return{colorBoxSize:m,colorBoxSizeOpera:n,sliderSize:I,width:D};
},_getMinimumPaletteWidth:function(){var n=0;
var l=this._header;
if(l){n+=this.getElementBox(l).horizontal;
a(l).children(":visible").each(function(r,q){n+=q.offsetWidth+$telerik.getMarginBox(q).horizontal;
});
}var o=0;
var p=this._tabStrip;
if(p){o+=this.getElementBox(p).horizontal;
var m=parseInt($telerik.getCurrentStyle(p,"left",0),10);
if(!isNaN(m)){o+=m;
}a(p).children("ul").children(":visible").each(function(r,q){o+=q.offsetWidth+$telerik.getMarginBox(q).horizontal;
});
}return Math.max(0,Math.max(n,o));
},_getRecentColorWrapperSize:function(){var n=0;
var m=this._recentColorsWrapper;
if(m&&this._showRecentColors){var l=m.getElementsByTagName("li");
if(l.length>1&&m.style.height){return m.style.height;
}var p;
if(l.length==1){var o=l[0].getElementsByTagName("span");
if(o.length==1&&((a.trim(o[0].innerHTML)=="")||(a.trim(o[0].innerHTML)=="&nbsp;"))){p=l[0];
}}if(!p){p=this._createColorElement({},true);
m.appendChild(p);
}n=$telerik.getContentSize(m).height;
m.removeChild(p);
}return n;
},_getWebPaletteElemenentsSize:function(m,l,n){n+=this.getElementContentBox(this._webPalettePageView).horizontal;
return this._getColorBoxSize(m,l,n,this._webPaletteWrapper);
},_getColorBoxSize:function(u,t,z,x){var m=0;
var n=0;
var y=x;
if(y){z+=this.getElementContentBox(y).horizontal;
var s=$telerik.getFirstChildByTagName(y,"li");
if(s){n=$telerik.getOuterSize(s).width;
m+=this.getElementContentBox(s).horizontal;
var l=$telerik.getFirstChildByTagName(s,"a");
if(l){m+=this.getElementContentBox(l).horizontal;
var w=$telerik.getFirstChildByTagName(l,"span");
m+=this.getElementContentBox(w).horizontal;
}}}var r=this._columns;
var v=u;
if(!v){u=z+r*n;
}u=Math.max(t,u);
if(v){var q=u-z;
q=(q<1)?1:q;
n=parseInt(q/r,10);
n=(n<1)?1:n;
}var p=n;
var o=n-m;
o=(o<1)?1:o;
return{colorSize:o,colorSizeOpera:p,width:u};
},_getRGBElemenentsSize:function(m,q){q+=this.getElementContentBox(this._rgbPageView).horizontal;
var p=this._rgbSlidersDefaultSize-q;
var l=this._defaultRGBWidth;
if(m!=l){var n=this._redInput;
var o=$telerik.getChildrenByTagName(n.parentNode,"label")[0];
p=m-q;
p-=this._renderer.getOuterWidth(n);
p-=this._renderer.getOuterWidth(o);
if(p<50){p=50;
}}return p;
},_createPalette:function(s){if(this._webPaletteWrapper){return;
}var t=this._webPaletteWrapper=this._createElement("ul",null,{className:"rcpWebPalette"});
s.appendChild(t);
var p=0;
var n=this._columns;
var q=this._items;
if(this._tabIndex&&q.length>0){q[0].tabIndex=this._tabIndex;
}for(var o=0,r=q.length;
o<r;
o++){if(p==n){p=0;
var l=this._createElement("li",null,{className:"rcpBreakLine"});
t.appendChild(l);
}p++;
var m=this._createColorElement(q[o]);
t.appendChild(m);
}},_createColorElement:function(l,p){var o=(this._selectedColor==l.value)&&!p?"rcpSelectedColor":"rcpColorBox";
var m=this._createElement("li");
var n=this._createA(l.title,o,null,l.value);
if(l.tabIndex){n.setAttribute("tabindex",l.tabIndex);
}var q=this._createElement("span",l.value);
n.appendChild(q);
m.appendChild(n);
return m;
},_createHeader:function(s,o){if(!s){return;
}var p=this.isModeEnabled(b.PaletteModes.WebPalette);
var r=(this.isModeEnabled(b.PaletteModes.RGBSliders)||this.isModeEnabled(b.PaletteModes.HSB)||this.isModeEnabled(b.PaletteModes.HSV));
var n="rcpHeader";
var m=this._enableCustomColor;
if(!o){if(!this._previewColor&&!this._showEmptyColor&&!(p&&m)&&p){n+=" rcpEmptyHeader";
}}var u=o?$telerik.getChildByClassName(s,"rcpHeader"):this._header;
if(!u){u=this._createDiv(n);
s.appendChild(u);
if(!o){this._header=u;
}}this._createPreviewElement(u,o);
var q,t;
if(!o){this._createEmptyColorElement(u);
if(p&&m&&!this._customColorButton){var l=this._localization[14];
q=this._customColorButton=this._createA(l,"rcpImageButton rcpCustomColorButton");
if(this._tabIndex){q.setAttribute("tabindex",this._tabIndex);
}u.appendChild(q);
this._initializeCustomColorHandler(q);
t=this._createElement("span",l);
q.appendChild(t);
}this._createApplyButton((!p&&r),u);
}else{if(this._customColorOkButton){return;
}q=this._customColorCancelButton=this._createA(null,"rcpButton rcpCancelButton");
u.appendChild(q);
$addHandler(q,"click",Function.createDelegate(this,this._cancelClick));
t=this._createElement("span",this._localization[17]);
q.appendChild(t);
q=this._customColorOkButton=this._createA(null,"rcpButton rcpOkButton");
u.appendChild(q);
$addHandler(q,"click",Function.createDelegate(this,this._okClick));
t=this._createElement("span",this._localization[16]);
q.appendChild(t);
if(this._materialRippleManager){this._materialRippleManager.initializeRippleZone({element:u,rippleConfigurations:[{containerSelector:".rcpButton"}]});
}}},_createApplyButton:function(o,l){if(o&&!this._applyButton){var p=l?l:this._header;
if(!p){return;
}var m=this._applyButton=this._createA(null,"rcpButton rcpApplyButton");
if(this._tabIndex){m.setAttribute("tabindex",this._tabIndex);
}p.appendChild(m);
this._initializeApplyHandler(m);
var n=this._createElement("span",this._localization[7]);
m.appendChild(n);
}},_createRoundedCornersAndShadow:function(n,m){var l=Function.createDelegate(this,this._createDiv);
this._renderer.createRoundedCornersAndShadow(n,m,this._showIcon,l);
},_setRightRoundedCornerAndShadowHeight:function(l){this._renderer.setRightRoundedCornerAndShadowHeight(l);
},_createRgbSliders:function(p){if(this.get_redSlider()){return;
}var o=this._createElement("ul");
p.appendChild(o);
var l=this.get_id();
var n=l+"_redSlider";
var m=l+"_redInput";
this._createRgbSliderWithInput(n,"rcpSlider rcpRedSlider","_redSlider",m,"rcpInput rcpRedInput","_redInput","R:",o);
n=l+"_greenSlider";
m=l+"_greenInput";
this._createRgbSliderWithInput(n,"rcpSlider rcpGreenSlider","_greenSlider",m,"rcpInput rcpGreenInput","_greenInput","G:",o);
n=l+"_blueSlider";
m=l+"_blueInput";
this._createRgbSliderWithInput(n,"rcpSlider rcpBlueSlider","_blueSlider",m,"rcpInput rcpBlueInput","_blueInput","B:",o);
this._updateRgbSlidersUI(this._getRgbFromHex());
},_createRgbSliderWithInput:function(t,s,u,n,m,o,q,w){var r=this._createElement("li");
w.appendChild(r);
var p=this._createElement("label",q,{htmlFor:n});
r.appendChild(p);
var v=this._createDiv(s,t);
r.appendChild(v);
this[u]=this._createSlider(v);
var l=this._createInput(m,this._rgbSlidersDefaultValue,n);
if(this._tabIndex){l.setAttribute("tabindex",this._tabIndex);
}r.appendChild(l);
this._initializeRgbInputHandler(l);
this[o]=l;
},_createSlider:function(l){var n=this._rgbSlidersDefaultValue;
var m=this._rgbSlidersDefaultSize+"px";
var p={itemData:[],_width:m,_skin:this._skin,maximumValue:n,value:n,_increaseText:this._localization[8],_decreaseText:this._localization[9],_tabIndex:-1,showIncreaseHandle:false,showDecreaseHandle:false,_dragText:this._localization[10]};
var o=$create(b.RadSlider,p,null,null,l);
this._initializeRgbSliderHandler(o);
return o;
},_rgbValuesToHex:function(p,n,l){var o="#";
var m=function(r){var q=parseInt(r,10).toString(16);
o=o+(q.length==1?"0"+q:q);
};
m(p);
m(n);
m(l);
m=null;
return o;
},_createHexColorInput:function(p,o){var l=o?null:this._selectedColor;
if(!l){var q=this._rgbSlidersDefaultValue;
l=this._rgbValuesToHex(q,q,q);
}var m=o?"_hexCustomColorInput":"_hexColorInput";
var n=this[m]=this._createInput("rcpHexInput",l);
if(this._tabIndex){n.setAttribute("tabindex",this._tabIndex);
}n.setAttribute("title",this._localization[18]);
n.setAttribute("dir","ltr");
p.appendChild(n);
if(!o&&this.isModeEnabled(b.PaletteModes.WebPalette)){n.readOnly="readonly";
}this._initializeHexHandler(n,o);
},_createMillionColors:function(w,q){if(this[q?"get_millionCustomColorsSlider":"get_millionColorsSlider"]()){return;
}var l=this.get_id();
var r=this[q?"_millionCustomColorsPalette":"_millionColorsPalette"]=this._createDiv("rcpMillionColorsPalette",(l+(q?"_millionCustomColorsPalette":"_millionColorsPalette")));
w.appendChild(r);
this._initializeMillionColorsPaletteHandler(q);
var n=this[q?"_millionCustomColorsHandle":"_millionColorsHandle"]=this._createElement("div","<!-- / -->",{className:"rcpMillionColorsHandle"},{top:"0px",left:"0px"});
r.appendChild(n);
var u=this._createDiv("rcpMillionColorsSlider",(l+(q?"_millionCustomColorsSlider":"_millionColorsSlider")));
w.appendChild(u);
var m=(q||this._isModeSelected(b.PaletteModes.HSB))?this._localization[11]:this._localization[12];
var s=0;
var t={itemData:[],_height:this._millionColorsSliderHeight,_width:this._millionColorsSliderWidth,_skin:this._skin,maximumValue:100,value:s,orientation:1,showIncreaseHandle:false,showDecreaseHandle:false,_tabIndex:-1,_dragText:m};
this[q?"set_millionCustomColorsSlider":"set_millionColorsSlider"]($create(b.RadSlider,t,null,null,u));
this._initializeMillionColorsSliderHandler(q);
var p=this._createDiv("rcpInputsWrapper");
w.appendChild(p);
var v=this._createElement("ul");
p.appendChild(v);
var o=q?"InputCustom":"Input";
this._createListItemWithInput((l+"_r"+o),"rcpInput rcpRedInput","r","R:","_initializeMillionColorsRgbInputHandler",v,null,q);
this._createListItemWithInput((l+"_g"+o),"rcpInput rcpGreenInput","g","G:","_initializeMillionColorsRgbInputHandler",v,null,q);
this._createListItemWithInput((l+"_b"+o),"rcpInput rcpBlueInput","b","B:","_initializeMillionColorsRgbInputHandler",v,null,q);
v=this._createElement("ul",null,{className:"rcpMillionColorsInputs"});
p.appendChild(v);
this._createListItemWithInput((l+"_h"+o),"rcpInput rcpHInput","h","H:","_initializeMillionColorsInputHandler",v,null,q);
this._createListItemWithInput((l+"_s"+o),"rcpInput rcpSInput","s","S:","_initializeMillionColorsInputHandler",v,null,q);
if(q||this.isModeEnabled(b.PaletteModes.HSB)){this._createListItemWithInput((l+"_l"+o),"rcpInput rcpLInput","l","B:","_initializeMillionColorsInputHandler",v,"rcpLInputWrapper",q);
}if(!q&&this.isModeEnabled(b.PaletteModes.HSV)){this._createListItemWithInput((l+"_v"+o),"rcpInput rcpVInput","v","V:","_initializeMillionColorsInputHandler",v,"rcpVInputWrapper");
}},_createListItemWithInput:function(o,n,p,s,l,v,t,q){var u=this._createElement("li",null,{className:t});
v.appendChild(u);
var r=this._createElement("label",s,{htmlFor:o});
u.appendChild(r);
var m=this._createInput(n,0,o);
if(this._tabIndex){m.setAttribute("tabindex",this._tabIndex);
}u.appendChild(m);
this[l](m,q);
this[q?"_millionCustomColorsInputs":"_millionColorsInputs"][p]=m;
},_createCustomColorPalette:function(){var o=this._customColorPalette=this._createDiv(this.get_element().className+" rcpCustomColorWrapper");
var m=this.get_element();
var q=$telerik.getCurrentStyle(m,"zIndex",4000);
q=isNaN(q)?parseInt(m.style.zIndex,10):q;
q=isNaN(q)?4000:q;
o.style.zIndex=q+2;
o.style.position="absolute";
document.body.appendChild(o);
var n=this._createDiv("rcpPalette");
o.appendChild(n);
this._createRoundedCornersAndShadow(n,true);
this._createHeader(n,true);
var p=this._createDiv("rcpPageView rcpMillionColorsPageView rcpHsbPageView");
n.appendChild(p);
this._createMillionColors(p,true);
this._configureMillionCustomColorsSliderHeight();
this._setRightRoundedCornerAndShadowHeight(n);
var l=this._millionCustomColorsPalette.style;
if(l.backgroundSize===j){l.height=this._millionColorsHSBPaletteSize.height;
}return o;
},_configureMillionCustomColorsSliderHeight:function(){var m=this._renderer.getHsbSliderHeight(this._millionCustomColorsPalette,this._millionCustomColorsSlider);
var l=this.get_millionCustomColorsSlider();
this._renderer.setMillionColorsSliderHeight(l,m);
},_calculateRenderSettings:function(){this._defaultRGBWidth=this._isTouchSkin?300:270;
},_rgbSliderValueChanged:function(p,l){if(this._sliderAvoidRecursion){return;
}var o=this.get_redSlider().get_value();
var n=this.get_greenSlider().get_value();
var m=this.get_blueSlider().get_value();
this._sliderAvoidRecursion=true;
this._updateHexPreview(o,n,m);
this._updateRgbInputUI(p);
this._sliderAvoidRecursion=false;
},_millionColorsSliderValueChanged:function(o,l){if(this._sliderAvoidRecursion||this._millionColorsSliderAvoidRecursion){return;
}var n=(o===this.get_millionCustomColorsSlider());
var m=this._getMillionColorsCoordinates(n);
this._sliderAvoidRecursion=true;
this._updateMillionColorsInputsUI(m.x,m.y,n);
this._sliderAvoidRecursion=false;
},_hexColorChange:function(l,n){if(!l){return;
}if(!n&&this._isModeSelected(b.PaletteModes.WebPalette)){return;
}var p=l.target||l.srcElement;
if(!p){return;
}var m=p.value;
if(!this._validateHexValue(m)){this._previewCurrentColor((n?"#FFFFFF":this._selectedColor),null,null,n);
return;
}if(this._inputAvoidRecursion){return;
}if(n||this._selectedContainer){var o=this._getRgbFromHex(m);
var q=(n||this._isModeSelected(b.PaletteModes.HSB))?"_updateHslPaletteElementsUI":(this._isModeSelected(b.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":"_updateHsvPaletteElementsUI");
this._inputAvoidRecursion=true;
this[q](o,null,n);
this._inputAvoidRecursion=false;
}},_hexCustomColorChange:function(l){this._hexColorChange(l,true);
},_rgbInputValueChange:function(m){if(!m){return;
}var p=m.target||m.srcElement;
if(!this._validateDecInput(p,0,255)){p.value=this._getSliderFromInput(p).get_value();
return;
}if(this._inputAvoidRecursion){return;
}var o=parseInt(this._redInput.value,10);
var n=parseInt(this._greenInput.value,10);
var l=parseInt(this._blueInput.value,10);
this._inputAvoidRecursion=true;
this._updateHexPreview(o,n,l);
this._updateRgbSliderUI(null,null,p);
this._inputAvoidRecursion=false;
},_millionColorsInputValueChange:function(l,p){if(!l){return;
}var t=l.target||l.srcElement;
var n=p||this._isMillionColorsTabSelected().HSB;
var q=this[p?"_millionCustomColorsInputs":"_millionColorsInputs"];
var m=(t.id==q.h.id)?360:100;
if(!this._validateDecInput(t,0,m)){var s=n?"_resetHslInputValue":"_resetHsvInputValue";
this[s](t,p);
return;
}if(this._inputAvoidRecursion){return;
}var u=n?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
var o=parseInt(q.h.value,10);
var r={h:((o==360)?0:o),s:parseInt(q.s.value,10)/100,l:(q.l?parseInt(q.l.value,10)/100:null),v:(q.v?parseInt(q.v.value,10)/100:null),hueValue:o};
this._inputAvoidRecursion=true;
this[u](null,r,p);
this._inputAvoidRecursion=false;
},_millionCustomColorsInputValueChange:function(l){return this._millionColorsInputValueChange(l,true);
},_millionColorsRgbInputValueChange:function(l,m){if(!l){return;
}var p=l.target||l.srcElement;
if(!this._validateDecInput(p,0,255)){this._resetRgbInputValue(p,m);
return;
}if(this._inputAvoidRecursion){return;
}if(m||this._selectedContainer){var n=this[m?"_millionCustomColorsInputs":"_millionColorsInputs"];
var o={r:parseInt(n.r.value,10),g:parseInt(n.g.value,10),b:parseInt(n.b.value,10)};
var q=(m||this._isMillionColorsTabSelected().HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI";
this._inputAvoidRecursion=true;
this[q](o,null,m);
this._inputAvoidRecursion=false;
}},_millionCustomColorsRgbInputValueChange:function(l){return this._millionColorsRgbInputValueChange(l,true);
},_onMillionColorsPaletteDown:function(o,r){var m=this;
var t=r?m._millionCustomColorsPalette:m._millionColorsPalette;
var s=r?g:f;
var q=r?m._millionCustomColorsHandle:m._millionColorsHandle;
var n=r?m._onMillionCustomColorsPaletteColorSelect:m._onMillionColorsPaletteColorSelect;
var u=r?m._onMillionCustomColorsPaletteUp:m._onMillionColorsPaletteUp;
var p=o.target;
var l=a(c);
if(!m._enabled||(p!==t&&p!==q)){return;
}o.preventDefault();
m._onMillionColorsPaletteColorSelect(o,r);
l.offEvent(h+s);
l.onEvent(h+s,i(n,m));
l.offEvent(k+s);
l.onEvent(k+s,i(u,m));
},_onMillionColorsPaletteColorSelect:function(m,n){var l=this;
var o=n?l._millionCustomColorsPalette:l._millionColorsPalette;
var p=l._getSelectedColorPosition(o,m);
m.preventDefault();
l._updateMillionColorsPaletteUI(p.x,p.y,n);
},_onMillionCustomColorsPaletteColorSelect:function(l){this._onMillionColorsPaletteColorSelect(l,true);
},_getSelectedColorPosition:function(p,n){var m=this;
var r=m.getPaletteRange(p);
var q=$telerik.getLocation(p);
var l=$telerik.getBorderBox(p);
var u=$telerik.getTouchEventLocation(n);
var o=$telerik.isTouchDevice?{left:u.x,top:u.y}:$telerik.getDocumentRelativeCursorPosition(n.originalEvent||n);
var s=Math.round(o.left-q.x-l.left);
var t=Math.round(o.top-q.y-l.top);
s=(s<0)?0:(s>r.x?r.x:s);
t=(t<0)?0:(t>r.y?r.y:t);
return{x:s,y:t};
},_updateMillionColorsPaletteUI:function(n,o,m){var l=this;
l._updateMillionColorsHandleUI(n,o,m);
l._updateMillionColorsInputsUI(n,o,m);
},_onMillionColorsPaletteUp:function(m,n){var o=n?g:f;
var l=a(c);
l.offEvent(h+o);
l.offEvent(k+o);
},_onMillionCustomColorsPaletteUp:function(l,m){this._onMillionColorsPaletteUp(l,true);
},getPaletteElement:function(l){return this[l?"_millionCustomColorsPalette":"_millionColorsPalette"];
},getPaletteRange:function(l){var m=$telerik.getContentSize(l);
return{x:m.width,y:m.height};
},_onMillionCustomColorsPaletteDown:function(l){this._onMillionColorsPaletteDown(l,true);
},_updateRgbSlidersUI:function(l){if(!l){return;
}this._updateRgbSliderUI(this.get_redSlider(),l.r);
this._updateRgbSliderUI(this.get_greenSlider(),l.g);
this._updateRgbSliderUI(this.get_blueSlider(),l.b);
},_updateRgbSliderUI:function(o,p,l){var m=o;
var n=p;
if(!m){if(!l){return;
}m=this._getSliderFromInput(l);
n=parseInt(l.value,10);
}m.set_value(n);
},_updateRgbInputUI:function(l){if(!l){return;
}this._getInputFromSlider(l).value=l.get_value();
},_updateMillionColorsHandleUI:function(p,q,n){var l=this[n?"_millionCustomColorsHandle":"_millionColorsHandle"];
var m=$telerik.getSize(l);
var o={x:p-Math.floor(m.width/2),y:q-Math.floor(m.height/2)};
$telerik.setLocation(l,o);
},_updateMillionColorsInputsUI:function(p,q,n){if(this._inputAvoidRecursion){return;
}var o=this._isMillionColorsTabSelected();
var m=n||o.HSB;
if(!m&&!o.HSV){return;
}var l=this[m?"_getHslFromCoordinates":"_getHsvFromCoordinates"](p,q,n);
var r=this[m?"_hslToRgb":"_hsvToRgb"](l.h,l.s,l[m?"l":"v"]);
this[m?"_updateHslSliderBackground":"_updateHsvPaletteBackground"](l,n);
this._updateMillionColorsInputsValues(r,l,n);
this._updateHexPreview(r.r,r.g,r.b,n);
},_updateMillionColorsInputsValues:function(o,n,m){var l=this[m?"_millionCustomColorsInputs":"_millionColorsInputs"];
if(o){l.r.value=o.r;
l.g.value=o.g;
l.b.value=o.b;
}l.h.value=Math.round(n.hueValue);
l.s.value=Math.round(n.s*100);
if(n.l!=null){l.l.value=Math.round(n.l*100);
}if(n.v!=null){l.v.value=Math.round(n.v*100);
}},_updateHslPaletteElementsUI:function(q,m,o){if(!q&&!m){return;
}var r=(q)?q:this._hslToRgb(m.h,m.s,m.l);
var n=(m)?m:this._rgbToHsl(q);
this._updateHexPreview(r.r,r.g,r.b,o);
this._updateMillionColorsInputsValues(r,n,o);
this._updateHslSliderBackground(n,o);
var p=this.getPaletteElement(o);
var l=this.getPaletteRange(p);
this._updateMillionColorsHandleUI(Math.round(n.h*l.x/360),l.y-Math.round(n.s*l.y),o);
var s=o?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
s.set_value(100-Math.round(n.l*100));
},_updateHslSliderBackground:function(m,n){var l=this._hslToRgb(m.h,m.s,0.5);
var o=n?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
if(o._trackElement){o._trackElement.style.backgroundColor=this._rgbValuesToHex(l.r,l.g,l.b);
}},_updateHsvPaletteElementsUI:function(p,l){if(!p&&!l){return;
}var q=(p)?p:this._hsvToRgb(l.h,l.s,l.v);
var m=(l)?l:this._rgbToHsv(p);
this._updateHexPreview(q.r,q.g,q.b);
this._updateMillionColorsInputsValues(q,m);
this._updateHsvPaletteBackground(m);
var o=this.getPaletteElement(false);
var n=this.getPaletteRange(o);
this._updateMillionColorsHandleUI(Math.round(m.s*n.x),n.y-Math.round(m.v*n.y));
this.get_millionColorsSlider().set_value(100-Math.round(m.h*100/360));
},_updateHsvPaletteBackground:function(m){var l=this._hsvToRgb(m.h,1,1);
this._millionColorsPalette.style.backgroundColor=this._rgbValuesToHex(l.r,l.g,l.b);
},_updateHexPreview:function(p,m,l,n){if(this._shouldPreventColorPreview){return;
}var o=this._rgbValuesToHex(p,m,l);
this._previewCurrentColor(o,true,null,n);
},_getRgbFromHex:function(l){var m=l;
if(!m){var n=this._selectedColor;
m=(n)?n:"#FFFFFF";
}return this._hexToRgb(m);
},_resetRgbInputValue:function(p,q){var s;
var m=this[q?"_hexCustomColorInput":"_hexColorInput"];
if(m){s=this._getRgbFromHex(m.value);
}else{var l=this._getMillionColorsCoordinates(q);
if(q||this._isModeSelected(b.PaletteModes.HSB)){var n=this._getHslFromCoordinates(l.x,l.y,q);
s=this._hslToRgb(n.h,n.s,n.l);
}else{if(this._isModeSelected(b.PaletteModes.HSV)){var o=this._getHsvFromCoordinates(l.x,l.y);
s=this._hsvToRgb(o.h,o.s,o.v);
}}}var r=this[q?"_millionCustomColorsInputs":"_millionColorsInputs"];
p.value=(p===r.r)?s.r:(p===r.g?s.g:s.b);
},_resetHslInputValue:function(n,o){var l=this._getMillionColorsCoordinates(o);
var m=this._getHslFromCoordinates(l.x,l.y,o);
this._updateMillionColorsInputsValues(null,m,o);
},_resetHsvInputValue:function(n){var l=this._getMillionColorsCoordinates();
var m=this._getHsvFromCoordinates(l.x,l.y);
this._updateMillionColorsInputsValues(null,m);
},_validateDecInput:function(m,p,o){var l=parseInt(m.value,10);
var n=(!isNaN(l));
if(n){n=(l>=p&&l<=o);
}return n;
},_validateHexValue:function(l){var m=/^#?(([0-9a-f]{3})|([0-9a-f]{6}))$/i;
return m.test(l);
},_getSliderFromInput:function(l){var m=this._getColorElementPrefix(l.id.toLowerCase());
return this[m+"Slider"];
},_getInputFromSlider:function(m){var l=this._getColorElementPrefix(m.get_id().toLowerCase());
return this[l+"Input"];
},_getColorElementPrefix:function(l){var m="";
if(!l){return m;
}if(l.indexOf("red")>-1){m="_red";
}else{if(l.indexOf("green")>-1){m="_green";
}else{if(l.indexOf("blue")>-1){m="_blue";
}}}return m;
},_getMillionColorsCoordinates:function(n){var l=this[n?"_millionCustomColorsHandle":"_millionColorsHandle"];
if(!l){return{x:0,y:0};
}var m=$telerik.getSize(l);
var o=parseInt(l.style.left,10)+Math.floor(m.width/2);
var p=parseInt(l.style.top,10)+Math.floor(m.height/2);
return{x:o,y:p};
},_getHslFromCoordinates:function(r,s,o){var q=this.getPaletteElement(o);
var l=this.getPaletteRange(q);
var n=(r/l.x*360);
var m=(r==l.x)?0:n;
var t=1-s/l.y;
var u=o?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
var p=1-(u.get_value()/100);
return{h:m,s:t,l:p,hueValue:n};
},_getHsvFromCoordinates:function(p,q){var s=this.get_millionColorsSlider().get_value();
var n=360*(1-s/100);
var m=(s==0)?0:n;
var o=this.getPaletteElement(false);
var l=this.getPaletteRange(o);
var r=p/l.x;
var t=1-q/l.y;
return{h:m,s:r,v:t,hueValue:n};
},_hexToRgb:function(l){if(!l){return null;
}var n={r:0,g:0,b:0};
if(l.indexOf("#")!=-1){l=l.substring(1,l.length);
}if(l.length==3){var m=function(o){return(o+o);
};
l=l.replace(/([0-9a-f])/gi,m);
}n.r=parseInt(l.substring(0,2),16);
n.g=parseInt(l.substring(2,4),16);
n.b=parseInt(l.substring(4,6),16);
return n;
},_hslToRgb:function(m,q,n){var l=this._hueToRgb(m);
l=this._addRgbVectors(this._multiplyRgbVectorByNum(q,l),this._multiplyRgbVectorByNum((1-q),{r:128,g:128,b:128}));
if(n!=0.5){var o=(n<0.5)?{r:0,g:0,b:0}:{r:255,g:255,b:255};
var p=2*Math.abs(0.5-n);
l=this._addRgbVectors(this._multiplyRgbVectorByNum(p,o),this._multiplyRgbVectorByNum((1-p),l));
}return l;
},_hsvToRgb:function(l,n,q){var m={r:0,g:0,b:0};
if(n==0){m={r:q,g:q,b:q};
}else{var o=(1-n)*q;
var p=q*n*(l%60)/60;
if(l<60){m={r:q,g:(o+p),b:o};
}else{if(l<120){m={r:q-p,g:q,b:o};
}else{if(l<180){m={r:o,g:q,b:o+p};
}else{if(l<240){m={r:o,g:q-p,b:q};
}else{if(l<300){m={r:o+p,g:o,b:q};
}else{if(l<360){m={r:q,g:o,b:q-p};
}}}}}}}return this._multiplyRgbVectorByNum(255,m);
},_hueToRgb:function(l){var o={};
var n=l/60;
var m=n-Math.floor(n);
if(n<1){o={r:1,g:m,b:0};
}else{if(n<2){o={r:(1-m),g:1,b:0};
}else{if(n<3){o={r:0,g:1,b:m};
}else{if(n<4){o={r:0,g:(1-m),b:1};
}else{if(n<5){o={r:m,g:0,b:1};
}else{o={r:1,g:0,b:(1-m)};
}}}}}return this._multiplyRgbVectorByNum(255,o);
},_rgbToHsl:function(p){var m={};
var o=Math.min(Math.min(p.r,p.g),p.b);
var n=Math.max(Math.max(p.r,p.g),p.b);
var q=(n+o);
var l=n-o;
m.l=q/(2*255);
if(l==0){m.h=0;
m.s=0;
}else{m.s=l/((m.l<=0.5)?q:(2*255-q));
m.h=this._rgbToHue(p,l);
}m.hueValue=m.h;
return m;
},_rgbToHsv:function(p){var m={};
var n=Math.max(Math.max(p.r,p.g),p.b);
var o=Math.min(Math.min(p.r,p.g),p.b);
var l=n-o;
m.v=(n/255);
if(l==0){m.h=0;
m.s=0;
}else{m.s=(l/n);
m.h=this._rgbToHue(p,l);
}m.hueValue=m.h;
return m;
},_rgbToHue:function(n,l){var m=0;
if(n.r>=n.g&&n.g>=n.b){m=60*(n.g-n.b)/l;
}else{if(n.g>=n.r&&n.r>=n.b){m=60+60*(n.g-n.r)/l;
}else{if(n.g>=n.b&&n.b>=n.r){m=120+60*(n.b-n.r)/l;
}else{if(n.b>=n.g&&n.g>=n.r){m=180+60*(n.b-n.g)/l;
}else{if(n.b>=n.r&&n.r>=n.g){m=240+60*(n.r-n.g)/l;
}else{if(n.r>=n.b&&n.b>=n.g){m=300+60*(n.r-n.b)/l;
}}}}}}return Math.round(m);
},_isModeSelected:function(o,l,r){var n=false;
var p=l?l:this._selectedContainer;
if(p){if(o==b.PaletteModes.WebPalette){n=(this._webPalettePageView===p);
}else{if(o==b.PaletteModes.RGBSliders){n=(this._rgbPageView===p);
}else{var q=r?r:this._selectedTab;
var m=this._isMillionColorsTabSelected(q);
n=(o==b.PaletteModes.HSB)?m.HSB:m.HSV;
}}}return n;
},_isMillionColorsTabSelected:function(m){var l=m;
if(!l){l=this._selectedTab;
}if(l){var n=this._getTextFromTab(l);
return{HSB:(n==this._localization[5]),HSV:(n==this._localization[6])};
}else{return{HSB:this.isModeEnabled(b.PaletteModes.HSB),HSV:this.isModeEnabled(b.PaletteModes.HSV)};
}},_getTextFromTab:function(m){var l=this._renderer.getTabTextParentTagName();
return m.getElementsByTagName(l)[0].innerHTML;
},_fixInRgbRange:function(l,m){if(m){l=Math.round(l);
}if(l<0){l=0;
}else{if(l>255){l=255;
}}return l;
},_addRgbVectors:function(l,m){return{r:this._fixInRgbRange(l.r+m.r),g:this._fixInRgbRange(l.g+m.g),b:this._fixInRgbRange(l.b+m.b)};
},_multiplyRgbVectorByNum:function(l,m){return{r:this._fixInRgbRange(m.r*l,true),g:this._fixInRgbRange(m.g*l,true),b:this._fixInRgbRange(m.b*l,true)};
},isModeEnabled:function(l){return l&this._paletteModes?true:false;
},isPaletteMode:function(m,l){return m&b.PaletteModes[l];
},_createTabStrip:function(){if(this._multiPage){return;
}var m=this.get_element();
var l=this.get_id();
var w=this._showIcon;
var t=this._paletteWrapperElement=this._createDiv("rcpPalette",(l+"_palette"));
if(w){if(!$telerik.isIE6){t.style.position="absolute";
}t.style.visibility="hidden";
}m.appendChild(t);
this._createRoundedCornersAndShadow(t);
if(w){var B=$telerik.getCurrentStyle(m,"zIndex",4000);
B=isNaN(B)?parseInt(m.style.zIndex,10):B;
B=isNaN(B)?4000:B;
t.style.zIndex=B+1;
}var A=this.isModeEnabled(b.PaletteModes.WebPalette);
var v=this.isModeEnabled(b.PaletteModes.RGBSliders);
var p=this.isModeEnabled(b.PaletteModes.HSB);
var q=this.isModeEnabled(b.PaletteModes.HSV);
var u=this.get_id();
var y=null;
if((A+v+p+q)>1){var z=this._tabStrip=this._createDiv("rcpTabs");
t.appendChild(z);
y=this._createElement("ul");
z.appendChild(y);
}this._createHeader(t);
var r=this._multiPage=this._createElement("div",null,{className:"rcpViews"});
t.appendChild(r);
var o=u+"_webPalette";
var n="rcpPageView";
var x=true;
if(A){this._createTabWithContainer(x,n,r,"_webPalettePageView","_createPalette",this._localization[3],y,o);
x=false;
}if(v){o=u+"_rgbSliders";
this._createTabWithContainer(x,(n+" rcpRGBPageView"),r,"_rgbPageView","_createRgbSliders",this._localization[4],y,o);
x=false;
}var s;
if(p){o=u+"_millionColors";
s=n+" rcpMillionColorsPageView rcpHsbPageView";
this._createTabWithContainer(x,s,r,"_millionColorsPageView","_createMillionColors",this._localization[5],y,o);
x=false;
}if(q){o=u+"_millionColors";
s=n+" rcpMillionColorsPageView rcpHsvPageView";
this._createTabWithContainer(x,s,r,"_millionColorsPageView","_createMillionColors",this._localization[6],y,o);
}this._setElementsSize();
this._initializeColorElementsArray();
this._initializePalleteEventHandlers();
if(this._recentColors&&this._recentColors.length>0){this._updateRecentColors();
}if(!this._popupBehavior){this._popupBehavior=$create(Telerik.Web.PopupBehavior,{id:l+"PopupBehavior",parentElement:this._iconWrapperElement,overlay:this._overlay,keepInScreenBounds:this._keepInScreenBounds,manageVisibility:false},null,null,t);
}this._setRightRoundedCornerAndShadowHeight(t);
},_createRecentColors:function(l){if(!this._showRecentColors||!l||this._recentColorsWrapper){return;
}var m=document.createElement("div");
m.className="rcpRecentColorsWrapper";
l.appendChild(m);
var r=this.get_id()+"_recentColors";
var p=this._localization[15];
if(p){var o=this._createElement("span",p,{className:"rcpRecentColorsLabel"});
m.appendChild(o);
}var q=this._recentColorsWrapper=this._createElement("ul",null,{className:"rcpRecentColors",id:r});
m.appendChild(q);
this._setRecentColorsSize();
this._setRightRoundedCornerAndShadowHeight(this._paletteWrapperElement);
if($telerik.isIE6){var n=this.get_element();
n.style.cssText=n.style.cssText;
}$addHandlers(q,{mouseover:this._onBoxMouseOver,mouseup:this._onRecentBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._recentColorsKeyDown},this);
},_createTabWithContainer:function(q,m,p,r,o,u,t,n){var s;
if(t){s=this._createTab(u,n);
t.appendChild(s);
}var l=this[r];
if(!l){l=this[r]=this._createDiv(m,n,null,(q?null:"none"));
p.appendChild(l);
}if(q){this._updateTabSelection(s,l);
this[o](l);
}},_createTab:function(o,n){var m=this._createElement("li");
var l=this._createA(o,null,n);
if(this._tabIndex){l.setAttribute("tabindex",this._tabIndex);
}this._initializeTabHandler(l);
m.appendChild(l);
this._renderer.setLinkContent(l,o);
return m;
},_createEmptyColorElement:function(n){if(!this._showEmptyColor||this._emptyColorElement){return;
}var m=this._localization[2];
var l=this._emptyColorElement=this._createA(m,"rcpImageButton rcpEmptyColor");
l.id=this.get_id()+"_emptycolor";
if(this._tabIndex){l.setAttribute("tabindex",this._tabIndex);
}n.appendChild(l);
var o=this._createElement("span",m);
l.appendChild(o);
},_createPreviewElement:function(m,l){if(!l&&!this._previewColor){return;
}var n=l?"#fff":this._selectedColor;
if(!n){n="#fff";
}var q=l?"_customColorPreviewElement":"_previewElement";
if(this[q]){return;
}var p=this.get_id()+(l?"_customColorPreview":"_preview");
var o=this[q]=this._createDiv("rcpColorPreview",p,n,null,"<!-- / -->");
m.appendChild(o);
this._createHexColorInput(m,l);
},_tabClicked:function(o){if(this._enabled){var x=(o.target||o.srcElement);
var y=this._getParentByTagName(x,"li");
var l=this._getParentByTagName(x,"a");
if(!l){return;
}var m=l.getAttribute("rel");
var n=$get(m);
if(!y||!n){return;
}var w=this._isModeSelected(b.PaletteModes.RGBSliders,n);
var q=this._isModeSelected(b.PaletteModes.HSB,n,y);
var v=q||this._isModeSelected(b.PaletteModes.HSV,n,y);
var u="webPalette";
this._updateHeader(w||v);
this._updateTabSelection(y,n);
if(this._isModeSelected(b.PaletteModes.WebPalette,n)){this._createPalette(n);
}else{if(w){this._createRgbSliders(n);
u="rgbSliders";
}else{if(v){this._createMillionColors(n);
u=q?"hsb":"hsv";
var r=this.get_millionColorsSlider();
q?r.set_dragText(this._localization[11]):r.set_dragText(this._localization[12]);
}}}this._setElementsSize();
var t=this._paletteSizes[u];
var s=this._paletteWrapperElement;
var z=this._showIcon?s:this._wrapperElement;
this._renderer.setElementInlineWidthStyle(z,t);
this._setRightRoundedCornerAndShadowHeight(s);
this.set_selectedColor(this._selectedColor,false,true);
this._updateOverlaySize();
if($telerik.isIE){var p=this.get_element();
p.style.cssText=p.style.cssText;
}}return $telerik.cancelRawEvent(o);
},_updateTabSelection:function(p,l){if(p&&l){var m=this._isMillionColorsTabSelected(p);
if(m.HSB){Sys.UI.DomElement.removeCssClass(l,"rcpHsvPageView");
Sys.UI.DomElement.addCssClass(l,"rcpHsbPageView");
}else{if(m.HSV){Sys.UI.DomElement.removeCssClass(l,"rcpHsbPageView");
Sys.UI.DomElement.addCssClass(l,"rcpHsvPageView");
}}var o=this._selectedTab;
var n=this._selectedContainer;
if(o&&n){Sys.UI.DomElement.removeCssClass(o,"rcpSelectedTab");
n.style.display="none";
}Sys.UI.DomElement.addCssClass(p,"rcpSelectedTab");
l.style.display="";
}this._selectedTab=p;
this._selectedContainer=l;
},_updateHeader:function(n){if(n&&!this._applyButton){this._createApplyButton(n);
}var l=this._applyButton;
if(l){l.style.display=n?"":"none";
}var m=this._customColorButton;
if(m){m.style.display=n?"none":"";
}var p=this._hexColorInput;
if(p){p.readOnly=n?"":"readonly";
}var o=this._header;
if(o){Sys.UI.DomElement.removeCssClass(o,"rcpEmptyHeader");
if(!n&&!m&&!p&&!this._emptyColorElement){Sys.UI.DomElement.addCssClass(o,"rcpEmptyHeader");
}}},_updateOverlaySize:function(){var m=this._paletteWrapperElement;
var l=m._hideWindowedElementsIFrame;
if(!l){return;
}$telerik.setSize(l,$telerik.getOuterSize(m));
},_initializeTabHandler:function(l){$addHandler(l,"click",Function.createDelegate(this,this._tabClicked));
},_initializeApplyHandler:function(l){$addHandler(l,"click",Function.createDelegate(this,this._applyClick));
},_initializeCustomColorHandler:function(l){$addHandler(l,"click",Function.createDelegate(this,this._customColorClick));
},_initializeHexHandler:function(m,n){if(!n){if(!this.isModeEnabled(b.PaletteModes.RGBSliders)&&!this.isModeEnabled(b.PaletteModes.HSB)&&!this.isModeEnabled(b.PaletteModes.HSV)){return;
}}var l=n?"_hexCustomColorChange":"_hexColorChange";
var o=n?"_hexCustomKeyDown":"_hexKeyDown";
$addHandlers(m,{blur:this[l],keydown:this[o]},this);
},_initializeRgbInputHandler:function(l){$addHandlers(l,{blur:this._rgbInputValueChange,keydown:this._rgbInputKeyDown},this);
},_initializeRgbSliderHandler:function(m){var l=this;
var o=function(q,p){l._rgbSliderValueChanged(q,p);
};
var n=function(){l._eventStartedInControl=true;
};
m.add_valueChanged(o);
if(this._showIcon){m.add_slideStart(n);
}},_initializeMillionColorsRgbInputHandler:function(m,n){if(!m){return;
}var l=n?"_millionCustomColorsRgbInputValueChange":"_millionColorsRgbInputValueChange";
var o=n?"_millionCustomColorsRgbInputKeyDown":"_millionColorsRgbInputKeyDown";
$addHandlers(m,{blur:this[l],keydown:this[o]},this);
},_initializeMillionColorsInputHandler:function(m,n){if(!m){return;
}var l=n?"_millionCustomColorsInputValueChange":"_millionColorsInputValueChange";
var o=n?"_millionCustomColorsInputKeyDown":"_millionColorsInputKeyDown";
$addHandlers(m,{blur:this[l],keydown:this[o]},this);
},_initializeMillionColorsSliderHandler:function(l){var n=l?this.get_millionCustomColorsSlider():this.get_millionColorsSlider();
if(!n){return;
}var m=this;
var p=function(r,q){m._millionColorsSliderValueChanged(r,q);
};
var o=function(){m._eventStartedInControl=true;
};
n.add_valueChanged(p);
if(this._showIcon){n.add_slideStart(o);
}},_initializeMillionColorsPaletteHandler:function(l){if(l){this._initializeCustomMillionColorsPaletteHandler();
}else{this._initializeRegularMillionColorsPaletteHandler();
}},_initializeRegularMillionColorsPaletteHandler:function(){var m=this;
var n=this._millionColorsPalette;
var l=a(c);
if(n){l.onEvent(d+f,i(m._onMillionColorsPaletteDown,m));
}},_initializeCustomMillionColorsPaletteHandler:function(){var m=this;
var n=m._millionCustomColorsPalette;
var l=a(c);
if(n){l.onEvent(d+g,i(m._onMillionCustomColorsPaletteDown,m));
}},_createElement:function(t,p,m,r){var o=document.createElement(t);
for(var l in m){var n=m[l];
if(n!=null&&n.toString()!=""){o[l]=n;
}}for(var q in r){var s=r[q];
if(s!=null&&s.toString()!=""){o.style[q]=s;
}}if(p){o.innerHTML=p;
}return o;
},_createA:function(o,m,n,l){return this._createElement("a",null,{className:m,href:"#",title:o,rel:n},{backgroundColor:l});
},_createDiv:function(m,o,l,n,p){return this._createElement("div",p,{className:m,id:o},{background:l,display:n});
},_createInput:function(l,n,m){return this._createElement("input",null,{className:l,id:m,type:"text",value:n});
},getElementBox:function(m){var l=this._renderer.getElementBox(m);
return l;
},getElementContentBox:function(m){var l=this.getElementBox(m);
if(m){var n=$telerik.getMarginBox(m);
l.horizontal=l.horizontal+n.horizontal;
l.vertical=l.vertical+n.vertical;
}return l;
},showPalette:function(){if(this._paletteDisplayed){return;
}this._createTabStrip();
var r=this._popupBehavior;
var n=r._firstPopup;
var t=$telerik.isOpera?$telerik.originalGetLocation(this._iconWrapperElement).y-$telerik.getLocation(this._iconWrapperElement).y:0;
if(this.get_keepInScreenBounds()){this._paletteWrapperElement._originalHeight=this._paletteWrapperElement.style.height;
this._paletteWrapperElement.style.height=this.getPaletteHeight()+"px";
}r.set_x(0);
r.set_y($telerik.getSize(this._iconWrapperElement).height+t);
r.show();
if(this.get_keepInScreenBounds()){this._paletteWrapperElement.style.height=this._paletteWrapperElement._originalHeight;
this._paletteWrapperElement._originalHeight=null;
}var q=this._paletteWrapperElement;
q.style.visibility="";
if(n&&this._selectedContainer){var o=this._paletteSizes;
var p=this._isModeSelected(b.PaletteModes.WebPalette)?o.webPalette:(this._isModeSelected(b.PaletteModes.RGBSliders)?o.rgbSliders:(this._isModeSelected(b.PaletteModes.HSB)?o.hsb:o.hsv));
var s=this._showIcon?q:this._wrapperElement;
this._renderer.setElementInlineWidthStyle(s,p);
}var l=this._applyButton;
var m=this._customColorButton;
if($telerik.isIE6&&(l||m)){if(l){l.style.visibility="visible";
}if(m){m.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(l){l.style.visibility="";
}if(m){m.style.visibility="";
}}),0);
}this.set_selectedColor(this._selectedColor,false,true);
this._paletteDisplayed=true;
this.raiseEvent("popUpShow",Sys.EventArgs.Empty);
},hidePalette:function(){var m=this._popupBehavior;
if(m){var l=this._paletteWrapperElement;
l.style.top="-9999px";
l.style.left="-9999px";
m.hide();
}this._paletteDisplayed=false;
},getIconContainer:function(){return this._iconWrapperElement;
},getPaletteContainer:function(){return this._paletteWrapperElement;
},getPaletteHeight:function(){var l=a(this._paletteWrapperElement);
var m=this._renderer.getPaletteHeight(l);
return m;
},get_selectedColor:function(){return this._selectedColor;
},set_selectedColor:function(y,w,v){if(!y||(y.toString().toLowerCase()=="null")){y=null;
}else{if(!this._validateHexValue(y)){return;
}if(y.indexOf("#")!=-1){y=y.substring(1,y.length);
}if(y.length==3){var o=function(z){return(z+z);
};
y=y.replace(/([0-9a-f])/gi,o);
}y="#"+y;
}var u=this._selectedColor;
if(!u){u=null;
}if(y!=null){y=y.toUpperCase();
}if(y!=u){var l=a.raiseCancellableControlEvent(this,"colorChanging",{oldColor:u,newColor:y});
if(l){var t=this._getBoxElementByColor(u);
if(t!=null){t.focus();
}var s=this._getBoxElementByColor(y);
if(s!=null){s.blur();
}return;
}}this._selectedColor=y;
this._previewCurrentColor(y);
if(this._showIcon){this._setIconColor(y);
}if(!w&&this._selectedContainer){if(this._isModeSelected(b.PaletteModes.WebPalette)){var p=this._emptyColorElement;
var n=this._getMarkedElement();
if(n!=null){if(n!=p){n.className="rcpColorBox";
}}n=this._getBoxElementByColor(y);
if(n!=null){this._setMarkedElement(n);
if(n!=p){n.className="rcpSelectedColor";
}}}else{var x=this._isModeSelected(b.PaletteModes.RGBSliders)?"_updateRgbSlidersUI":(this._isModeSelected(b.PaletteModes.HSB)?"_updateHslPaletteElementsUI":"_updateHsvPaletteElementsUI");
var m=(y===null||y===j)&&this._isModeSelected(b.PaletteModes.HSB)?{r:128,g:128,b:128}:this._getRgbFromHex(y);
this._millionColorsSliderAvoidRecursion=true;
var r=y===null;
this._shouldPreventColorPreview=r;
this[x](m);
this._millionColorsSliderAvoidRecursion=false;
if(this._shouldPreventColorPreview){this._shouldPreventColorPreview=false;
}}}if(!v){this._updateRecentColors(y);
}this.updateClientState();
if(this._selectedColor!=u){var q=new b.ColorPickerColorChangeEventArgs(u);
this.raiseEvent("colorChange",q);
if(this._autoPostBack){this._raiseColorChangedServerEvent();
}}},get_selectedColorTitle:function(){var l=this._getBoxElementByColor(this._selectedColor);
if(l!=null){return l.getAttribute("title");
}return this._selectedColor;
},get_enabled:function(){return this._enabled;
},set_enabled:function(t){if(this._enabled==t){return;
}this._enabled=t;
if(!this._wrapperElement){return;
}var m=[this.get_redSlider(),this.get_greenSlider(),this.get_blueSlider(),this.get_millionColorsSlider()];
var o,q;
for(o=0,q=m.length;
o<q;
o++){var s=m[o];
if(s&&s.set_enabled){s.set_enabled(t);
}}var l=[this._hexColorInput,this._redInput,this._greenInput,this._blueInput,this._accessKeyTextbox];
var r=this._millionColorsInputs;
if(r){l=l.concat([r.r,r.g,r.b,r.h,r.s,r.l,r.v]);
}var n=this.get_element(),p;
if(t){Sys.UI.DomElement.removeCssClass(n,"rcpDisabled");
n.removeAttribute("disabled");
for(o=0,q=l.length;
o<q;
o++){p=l[o];
if(p){p.removeAttribute("disabled");
}}}else{Sys.UI.DomElement.addCssClass(n,"rcpDisabled");
n.setAttribute("disabled","disabled");
for(o=0,q=l.length;
o<q;
o++){p=l[o];
if(p){p.setAttribute("disabled","disabled");
}}}},get_overlay:function(){return this._overlay;
},set_overlay:function(n){this._overlay=n;
var l=this._customColorPopupBehavior;
if(l){l.set_overlay(n);
}var m=this._popupBehavior;
if(m){m.set_overlay(n);
if(this._showIcon&&this._paletteDisplayed){m.show();
}}},get_keepInScreenBounds:function(){return this._keepInScreenBounds;
},set_keepInScreenBounds:function(n){this._keepInScreenBounds=n;
var l=this._customColorPopupBehavior;
if(l){l.set_keepInScreenBounds(n);
}var m=this._popupBehavior;
if(m){m.set_keepInScreenBounds(n);
if(this._showIcon&&this._paletteDisplayed){m.show();
}}},_initializeEventHandlers:function(){this._initializePalleteEventHandlers();
if(this._showIcon){$addHandlers(this._iconLink,{click:this._onIconMouseUp,keydown:this._iconKeyDown},this);
$addHandlers(this._iconColorElement,{click:this._onIconMouseUp,keydown:this._iconKeyDown},this);
$addHandlers(this.get_element(),{mousedown:this._onWrapperMouseDown},this);
this._mouseUpHandler=Function.createDelegate(this,this._onMouseUp);
$telerik.addExternalHandler(document,"mouseup",this._mouseUpHandler);
}},_applyAccessKey:function(){if(!this._accessKey){return;
}if($telerik.isChrome||$telerik.isSafari){var m=document.createElement("div");
m.style.width="0px";
m.style.height="0px";
m.style.overflow="hidden";
this.get_element().appendChild(m);
var l=this._accessKeyTextbox=document.createElement("input");
l.setAttribute("type","text");
var n=this.get_id()+"ColorPickerAccessKey";
l.setAttribute("name",n);
l.setAttribute("id",n);
l.setAttribute("accessKey",this._accessKey);
m.appendChild(l);
$addHandlers(l,{focus:this._accessKeyPressed},this);
}},_accessKeyPressed:function(l){var m=this._iconLink;
if(!m){m=this._getFirstChildByTagName(this._tabStrip,"a");
if(!m){m=this._getFirstChildByTagName(this._webPaletteWrapper,"a");
if(!m){m=this._redInput;
if(!m&&this._millionColorsInputs){m=this._millionColorsInputs.r;
}}}}if(m){m.focus();
}},_getFirstChildByTagName:function(m,n){if(m){var l=m.getElementsByTagName(n);
if(l&&l.length>0){return l[0];
}}return null;
},_iconKeyDown:function(l){l=l.rawEvent||l;
var m=l.keyCode||l.which;
var n=(m==Sys.UI.Key.esc)||(l.altKey&&m==Sys.UI.Key.up);
var o=l.altKey&&(m==Sys.UI.Key.down);
if(!o&&!n){return;
}$telerik.cancelRawEvent(l);
if(n){this.hidePalette();
}else{this.showPalette();
}return false;
},_hexCustomKeyDown:function(l){this._hexKeyDown(l,true);
},_hexKeyDown:function(l,m){l=l.rawEvent||l;
var n=l.keyCode||l.which;
if(n!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(l);
this._hexColorChange(l,m);
if(m){this._okClick();
}else{this._applyClick(l);
}return false;
},_rgbInputKeyDown:function(l){l=l.rawEvent||l;
var m=l.keyCode||l.which;
if(m!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(l);
this._rgbInputValueChange(l);
this._applyClick(l);
return false;
},_millionCustomColorsRgbInputKeyDown:function(l){this._millionColorsRgbInputKeyDown(l,true);
},_millionColorsRgbInputKeyDown:function(l,m){l=l.rawEvent||l;
var n=l.keyCode||l.which;
if(n!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(l);
this._millionColorsRgbInputValueChange(l,m);
if(m){this._okClick();
}else{this._applyClick(l);
}return false;
},_millionCustomColorsInputKeyDown:function(l){this._millionColorsInputKeyDown(l,true);
},_millionColorsInputKeyDown:function(l,m){l=l.rawEvent||l;
var n=l.keyCode||l.which;
if(n!=Sys.UI.Key.enter){return;
}$telerik.cancelRawEvent(l);
this._millionColorsInputValueChange(l,m);
if(m){this._okClick();
}else{this._applyClick(l);
}return false;
},_webPaletteKeyDown:function(o){o=o.rawEvent||o;
var q=o.keyCode||o.which;
if(q==Sys.UI.Key.enter){$telerik.cancelRawEvent(o);
this._onBoxClick(o);
}else{var n=this._getColorBoxElement(o.target||o.srcElement);
if(!n){return;
}var m=this._indexByColor[this._getElementColor(n)];
var l=this._columns;
var p=this._webPaletteWrapper.getElementsByTagName("a");
var r=m;
switch(q){case Sys.UI.Key.up:r-=l;
break;
case Sys.UI.Key.down:r+=l;
break;
case Sys.UI.Key.left:r-=1;
break;
case Sys.UI.Key.right:r+=1;
break;
case Sys.UI.Key.home:r=0;
break;
case Sys.UI.Key.end:r=p.length-1;
break;
default:return;
}r=Math.max(0,Math.min(p.length-1,r));
var s=p[r];
s.focus();
this._previewCurrentColor(this._getElementColor(s),true,s.title);
}$telerik.cancelRawEvent(o);
return false;
},_recentColorsKeyDown:function(n){n=n.rawEvent||n;
var p=n.keyCode||n.which;
if(p==Sys.UI.Key.enter){this._onRecentBoxClick(n);
}else{var s=this._recentColors;
if(!s){return;
}var m=this._getColorBoxElement(n.target||n.srcElement);
if(!m){return;
}var l=Array.indexOf(s,this._getElementColor(m));
var o=this._recentColorsWrapper.getElementsByTagName("a");
var q=l;
switch(p){case Sys.UI.Key.up:q-=1;
break;
case Sys.UI.Key.down:q+=1;
break;
case Sys.UI.Key.left:q-=1;
break;
case Sys.UI.Key.right:q+=1;
break;
case Sys.UI.Key.home:q=0;
break;
case Sys.UI.Key.end:q=o.length-1;
break;
default:return;
}q=Math.max(0,Math.min(o.length-1,q));
var r=o[q];
r.focus();
this._previewCurrentColor(this._getElementColor(r),true,r.title);
}$telerik.cancelRawEvent(n);
return false;
},_initializePalleteEventHandlers:function(){var m=this._webPaletteWrapper;
if(m){$addHandlers(m,{mouseover:this._onBoxMouseOver,mouseup:this._onBoxClick,mouseout:this._onBoxMouseOut,click:$telerik.cancelRawEvent,selectstart:$telerik.cancelRawEvent,keydown:this._webPaletteKeyDown},this);
}var l=this._emptyColorElement;
if(l&&this._showEmptyColor){$addHandlers(l,{click:this._onEmptyColorClick},this);
}},_disposeHandlers:function(){var m=this._webPaletteWrapper;
if(m){$clearHandlers(m);
}var l=this._emptyColorElement;
if(l&&this._showEmptyColor){$clearHandlers(l);
}if(this._showIcon){$clearHandlers(this._iconLink);
$clearHandlers(this._iconColorElement);
$clearHandlers(this.get_element());
$telerik.removeExternalHandler(document,"mouseup",this._mouseUpHandler);
this._iconWrapperElement=null;
this._iconLink=null;
}this._mouseUpHandler=null;
},_raiseColorChangedServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},_onMouseUp:function(l){if(!this._enabled){return;
}if(this._eventStartedInControl){this._eventStartedInControl=false;
return;
}var m=l.target||l.srcElement;
if($telerik.isDescendantOrSelf(this._paletteWrapperElement,m)){return;
}this.hidePalette();
},_onBoxMouseOver:function(m){if(!this._enabled){return;
}var n=this._getColorBoxElement(m.target||m.srcElement);
if(n==null){return;
}var l=this._getElementColor(n);
this._previewCurrentColor(l,true,n.title);
},_onBoxMouseOut:function(m){if($telerik.isMouseOverElementEx(this._webPaletteWrapper,m)){return;
}var n=this._recentColorsWrapper;
var l=this.get_selectedColor();
if(n){if($telerik.isMouseOverElementEx(n,m)){return;
}if(this._selectedContainer&&!this._isModeSelected(b.PaletteModes.WebPalette)){l=this._getColorFromRGBControls();
}}this._previewCurrentColor(l);
},_applyClick:function(l){if(this._enabled){var n=this._hexColorInput;
var m=n?n.value:this._getColorFromRGBControls();
this._applyColorAndClose(m,true);
}return $telerik.cancelRawEvent(l);
},_cancelClick:function(l){return this._closeCustomColorPalette(l);
},_okClick:function(l){if(this._enabled){var n=this._hexCustomColorInput;
var m=n?n.value:this._getColorFromRGBControls(true);
this.set_selectedColor(m);
return this._closeCustomColorPalette(l);
}return $telerik.cancelRawEvent(l);
},_customColorClick:function(o){var p=this._customColorModalExtender;
var r=this._customColorPopupBehavior;
if(!r){var n=this._customColorPalette;
if(!n){n=this._createCustomColorPalette();
}p=this._customColorModalExtender=new b.ModalExtender(n);
r=this._customColorPopupBehavior=$create(Telerik.Web.PopupBehavior,{id:this.get_id()+"CustomColorPopupBehavior",overlay:this._overlay,parentElement:document.documentElement,keepInScreenBounds:this._keepInScreenBounds},null,null,n);
}var l=this._getCentralBounds();
r.set_x(l.x);
r.set_y(l.y);
r.show();
this._renderer.adjustCustomColorPopupWidth(r.get_elementToShow());
p.show();
this._millionColorsSliderAvoidRecursion=true;
this._updateHslPaletteElementsUI(this._getRgbFromHex("#808080"),null,true);
this._millionColorsSliderAvoidRecursion=false;
var q=this._customColorOkButton;
var m=this._customColorCancelButton;
if($telerik.isIE6&&(q||m)){if(q){q.style.visibility="visible";
}if(m){m.style.visibility="visible";
}setTimeout(Function.createDelegate(this,function(){if(q){q.style.visibility="";
}if(m){m.style.visibility="";
}}),0);
}this._millionCustomColorsInputs.r.focus();
if(this._showIcon){this.hidePalette();
}return $telerik.cancelRawEvent(o);
},_getCentralBounds:function(){var m=this._customColorPalette;
var l={width:parseInt($telerik.getCurrentStyle(m,"width","350px"),10),height:parseInt($telerik.getCurrentStyle(m,"height","325px"),10)||325};
var n=this._getViewportBounds();
var o=parseInt((n.width-l.width)/2,10);
var p=parseInt((n.height-l.height)/2,10);
l.x=o+n.scrollLeft;
l.y=p+n.scrollTop;
return l;
},_getViewportBounds:function(){var l=$telerik.getClientBounds();
var m=$telerik.getCorrectScrollLeft(document.documentElement)||$telerik.getCorrectScrollLeft(document.body);
var n=document.documentElement.scrollTop||document.body.scrollTop;
l.scrollLeft=m;
l.scrollTop=n;
if(this.isIE){if(l.width==0){l.width=document.body.clientWidth;
}if(l.height==0){l.height=document.body.clientHeight;
}}return l;
},_getColorFromRGBControls:function(m){var n;
if(!m&&this._isModeSelected(b.PaletteModes.RGBSliders)){n={r:this.get_redSlider().get_value(),g:this.get_greenSlider().get_value(),b:this.get_blueSlider().get_value()};
}else{var l=this[m?"_millionCustomColorsInputs":"_millionColorsInputs"];
n={r:parseInt(l.r.value,10),g:parseInt(l.g.value,10),b:parseInt(l.b.value,10)};
}return this._rgbValuesToHex(n.r,n.g,n.b);
},_onEmptyColorClick:function(l){if(this._enabled){this._applyColorAndClose(null);
}return $telerik.cancelRawEvent(l);
},_applyColorAndClose:function(l,o,n){var m=this._showIcon;
this.set_selectedColor(l,(m||o),n);
if(m){this.hidePalette();
}},_closeCustomColorPalette:function(l){var m=this._customColorModalExtender;
if(m){m.hide();
}var n=this._customColorPopupBehavior;
if(n){n.hide();
}return $telerik.cancelRawEvent(l);
},_onWrapperMouseDown:function(l){if(!this._enabled){return;
}this._eventStartedInControl=true;
},_onIconMouseUp:function(l){if(this._enabled){if(this._paletteDisplayed){this.hidePalette();
}else{this.showPalette();
}}return $telerik.cancelRawEvent(l);
},_getElementColor:function(l){if(l==this._emptyColorElement){return null;
}return l.firstChild.innerHTML;
},_setIconColor:function(l){var n=(l)?l:this._localization[13];
var m=a.trim(this._localization[0]+" "+this._localization[1].toString().replace("{0}",n));
if(m!=""){this._iconWrapperElement.title=m;
}if(l){a(this._iconWrapperElement).removeClass("rcpEmptyIcon");
a(this._iconElement).css("background-color",l);
}else{a(this._iconWrapperElement).addClass("rcpEmptyIcon");
a(this._iconElement).empty();
}},_onBoxClick:function(l,m){if(this._enabled){this._eventStartedInControl=false;
if(l.button){return;
}var n=this._getColorBoxElement(l.target||l.srcElement);
if(!n){return;
}this._applyColorAndClose(this._getElementColor(n),false,m);
}return $telerik.preventDefault(l);
},_onRecentBoxClick:function(l){return this._onBoxClick(l,true);
},_getMarkedElement:function(){var p=this._markedElement;
if(p){return p;
}var q=this._webPaletteWrapper;
if(!q){return null;
}var l=q.getElementsByTagName("A");
for(var n=0,o=l.length;
n<o;
n++){var m=l[n];
if(m.className=="rcpSelectedColor"){return m;
}}return null;
},_setMarkedElement:function(l){this._markedElement=l;
},_getColorBoxElement:function(l){var n=3;
var m=0;
while(m<n){if(l.className=="rcpColorBox"||l.className=="rcpSelectedColor"||l.className.indexOf("rcpEmptyColor")>-1){return l;
}m++;
l=l.parentNode;
}return null;
},_getParentByTagName:function(l,o){var n=3;
var m=0;
while(m<n){if(l.tagName.toLowerCase()==o){return l;
}m++;
l=l.parentNode;
}return null;
},_getBoxElementByColor:function(l){if(!l){return this._emptyColorElement;
}l=l.toUpperCase();
return this._elementsByColor[l];
},_previewCurrentColor:function(l,r,q,o){if(!this.get_isInitialized()){return;
}if(r&&(l!=this._lastPreviewColor)){var m=new b.ColorPickerColorPreviewEventArgs(l);
this.raiseEvent("colorPreview",m);
}this._lastPreviewColor=l;
if(!this._previewColor&&!o){return;
}if(l==null){q=this._localization[2];
}if(l!=null){l=l.toUpperCase();
}if(!q){q=l;
}var p=this[o?"_customColorPreviewElement":"_previewElement"];
if(p&&l!=null){a(p).removeClass("rcpEmptyColorPreview").css("background-color",l);
}else{a(p).addClass("rcpEmptyColorPreview").removeAttr("style");
}var n=this[o?"_hexCustomColorInput":"_hexColorInput"];
if(n){n.value=(l)?l:q;
}},_updateRecentColors:function(q){var u=this._recentColors;
if(q){var o=Array.indexOf(u,q);
if(o>-1){u.splice(o,1);
}if(u.unshift(q)>this._columns){u.pop();
}}if(this._showRecentColors&&u.length>0){if(!this._recentColorsWrapper){this._createRecentColors(this._multiPage);
}var v=this._recentColorsWrapper;
if(v){var w=this._recentElementsByColor;
for(var n=0,p=u.length;
n<p;
n++){var t=u[n];
var s=this._getBoxElementByColor(t);
var m={value:t,title:(s?s.title:t)};
var l=w[n];
if(!l){var r=this._createColorElement(m,true);
v.appendChild(r);
w[w.length]=l=$telerik.getFirstChildByTagName(r,"a");
}else{l.title=m.title;
l.style.backgroundColor=m.value;
var x=$telerik.getFirstChildByTagName(l,"span");
if(x){x.innerHTML=m.value;
}}l.removeAttribute("tabIndex");
if(n>0){l.setAttribute("tabIndex","-1");
}else{if(this._tabIndex){l.setAttribute("tabIndex",this._tabIndex);
}}}if(w.length>0){v.style.height="";
}}}},get_rippleZonesConfiguration:function(){return[{element:this.get_element(),rippleConfigurations:[{containerSelector:".rcpTabs > ul > li, .rcpButton, .rcpImageButton, .rcpIcon > a"}]}];
},saveClientState:function(){var m=["selectedColor"];
var n={};
for(var l=0;
l<m.length;
l++){n[m[l]]=this["get_"+m[l]]();
}return Sys.Serialization.JavaScriptSerializer.serialize(n);
}};
a.registerControlProperties(b.RadColorPicker,{paletteModes:b.PaletteModes.WebPalette,hiddenSlider:null,redSlider:null,greenSlider:null,blueSlider:null,millionColorsSlider:null,millionCustomColorsSlider:null});
a.registerControlEvents(b.RadColorPicker,["load","colorPreview","colorChanging","colorChange","popUpShow"]);
b.RadColorPicker.registerClass("Telerik.Web.UI.RadColorPicker",b.RadWebControl);
})($telerik.$);
(function(b){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.ColorPicker");
var a=Telerik.Web.UI.ColorPicker;
a.BaseRenderer=function(){};
a.BaseRenderer.prototype={setElementInlineWidthStyle:Function.emptyFunction,setColorRectangleDimensions:Function.emptyFunction,setMillionColorsSliderHeight:Function.emptyFunction,getRgbPaletteWidth:Function.emptyFunction,getInitialHsbPaletteWidth:Function.emptyFunction,getElementContentBox:Function.emptyFunction,getElementBox:Function.emptyFunction,getHsbSliderHeight:Function.emptyFunction,getHsvSliderHeight:Function.emptyFunction,createRoundedCornersAndShadow:Function.emptyFunction,setRightRoundedCornerAndShadowHeight:Function.emptyFunction,getTabTextParentTagName:Function.emptyFunction,setLinkContent:Function.emptyFunction,getPaletteHeight:Function.emptyFunction,adjustCustomColorPopupWidth:Function.emptyFunction,getOuterWidth:Function.emptyFunction,setTabStripWidth:Function.emptyFunction};
a.BaseRenderer.registerInterface("Telerik.Web.UI.ColorPicker.BaseRenderer");
})();
(function(a,c){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.ColorPicker");
var b=Telerik.Web.UI.ColorPicker;
b.ClassicRenderer=function(d){this._defaultHSBWidth=d.isTouchSkin?380:345;
this._defaultHSVWidth=d.isTouchSkin?380:d.isSilkOrGlowSkin?345:249;
};
b.ClassicRenderer.prototype={setElementInlineWidthStyle:function(d,e){if(d&&parseInt(d.style.width,10)!=e){d.style.width=e+"px";
}},setColorRectangleDimensions:function(d,e){if(parseInt(d.style.width,10)!=e){d.style.width=e+"px";
d.style.height=e+"px";
}},setMillionColorsSliderHeight:function(){},getRgbPaletteWidth:function(e,d){return e;
},getInitialHsbPaletteWidth:function(){return this._defaultHSBWidth;
},getInitialHsvPaletteWidth:function(d,e){if(d){return this._defaultHSVWidth;
}else{return this.calculateHsvWrapperWidthWithDefaultPaletteSize(e);
}},calculateHsvWrapperWidthWithDefaultPaletteSize:function(d){var j=this.getElementContentBox(d.paletteWrapperElement).horizontal;
var k=$telerik.getElementByClassName(d.multiPage,"rcpMillionColorsPageView","div");
var l=j+this.getElementContentBox(k).horizontal;
var h=162;
var i=this.getOuterWidth(d.millionColorsSlider.get_element());
var f=$telerik.getElementByClassName(d.colorPicker,"rcpInputsWrapper","div");
var g=this.getOuterWidth(f);
var e=h+i+g+l;
return e;
},getOuterWidth:function(d){return $telerik.getOuterSize(d).width;
},getElementContentBox:function(e){var d=this.getElementBox(e);
if(e){var f=$telerik.getMarginBox(e);
d.horizontal=d.horizontal+f.horizontal;
d.vertical=d.vertical+f.vertical;
}return d;
},getElementBox:function(f){var e={horizontal:0,vertical:0};
if(f){var d=$telerik.getBorderBox(f);
var g=$telerik.getPaddingBox(f);
e.horizontal=d.horizontal+g.horizontal;
e.vertical=d.vertical+g.vertical;
}return e;
},getHsbSliderHeight:function(){},createRoundedCornersAndShadow:function(h,f,g,d){var e=d("rcpRoundedRight");
h.appendChild(e);
e=d("rcpRoundedBottomRight");
h.appendChild(e);
e=d("rcpRoundedBottomLeft");
h.appendChild(e);
if($telerik.isIE6){return;
}if(f||g){e=d("rcpRightShadow");
h.appendChild(e);
e=d("rcpCornerShadow");
h.appendChild(e);
e=d("rcpBottomShadow");
h.appendChild(e);
}},setRightRoundedCornerAndShadowHeight:function(e){var d=$telerik.getContentSize(e).height+"px";
a(e).children(".rcpRoundedRight").css("height",d);
a(e).children(".rcpRightShadow").css("height",d);
},getTabTextParentTagName:function(){return"span";
},setLinkContent:function(d,f){var e=document.createElement("span");
e.innerHTML=f;
d.appendChild(e);
},getPaletteHeight:function(d){var e=d.find(".rcpRoundedRight").height()+d.find(".rcpRoundedBottomRight").height()+d.find(".rcpTabs").height();
return e;
},adjustCustomColorPopupWidth:function(){},setTabStripWidth:function(){}};
b.ClassicRenderer.registerClass("Telerik.Web.UI.ColorPicker.ClassicRenderer",null,b.BaseRenderer);
})($telerik.$);
(function(b){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.ColorPicker");
var a=Telerik.Web.UI.ColorPicker;
a.LightweightRenderer=function(){};
a.LightweightRenderer.prototype={getFontSize:function(c){return parseInt($telerik.getComputedStyle(c,"fontSize"),10);
},setElementInlineWidthStyle:function(c,e){var d=Math.ceil(e)/this.getFontSize(c);
c.style.width=d+"em";
},setColorRectangleDimensions:function(c,d){c.style.width=d/this.getFontSize(c)+"em";
c.style.height=d/this.getFontSize(c)+"em";
},setMillionColorsSliderHeight:function(c,d){c.set_height(d);
},getRgbPaletteWidth:function(d,c){return c;
},getInitialHsbPaletteWidth:function(c){return this.getInitialPaletteWidth(c);
},getInitialPaletteWidth:function(c){var i=this.getElementContentBox(c.paletteWrapperElement).horizontal;
var j=$telerik.getElementByClassName(c.multiPage,"rcpMillionColorsPageView","div");
var k=i+this.getElementContentBox(j).horizontal;
var g=this.getOuterWidth(c.millionColorsPalette);
var h=this.getOuterWidth(c.millionColorsSlider.get_element());
var e=$telerik.getElementByClassName(c.colorPicker,"rcpInputsWrapper","div");
var f=this.getOuterWidth(e);
var d=g+h+f+k;
return d;
},getInitialHsvPaletteWidth:function(c,d){return this.getInitialPaletteWidth(d);
},getElementContentBox:function(d){var c=this.getElementBox(d);
if(d){var e=this.getMarginBox(d);
c.horizontal=c.horizontal+e.horizontal;
c.vertical=c.vertical+e.vertical;
}return c;
},getElementBox:function(e){var d={horizontal:0,vertical:0};
if(e){var c=$telerik.getBorderBox(e);
var f=$telerik.getPaddingBox(e);
f.horizontal=this.getDistanceStyleValue(e,"paddingLeft")+this.getDistanceStyleValue(e,"paddingRight");
f.vertical=this.getDistanceStyleValue(e,"paddingTop")+this.getDistanceStyleValue(e,"paddingBottom");
d.horizontal=c.horizontal+f.horizontal;
d.vertical=c.vertical+f.vertical;
}return d;
},getDistanceStyleValue:function(c,e){var d=parseFloat(parseFloat($telerik.getComputedStyle(c,e)).toFixed(2));
return isNaN(d)?0:d;
},getMarginBox:function(d){var c={top:this.getDistanceStyleValue(d,"marginTop"),right:this.getDistanceStyleValue(d,"marginRight"),bottom:this.getDistanceStyleValue(d,"marginBottom"),left:this.getDistanceStyleValue(d,"marginLeft")};
c.horizontal=c.left+c.right;
c.vertical=c.top+c.bottom;
return c;
},getOuterWidth:function(c){return this.getElementContentBox(c).horizontal+this.getElementSize(c).width;
},getElementSize:function(c){var e=this.getDistanceStyleValue(c,"width");
var d=this.getDistanceStyleValue(c,"height");
return{width:e,height:d};
},getHsbSliderHeight:function(c,d){var e=this.getMarginBox(d.get_element());
return $telerik.getOuterSize(c).height-e.vertical;
},createRoundedCornersAndShadow:function(){},setRightRoundedCornerAndShadowHeight:function(){},getTabTextParentTagName:function(){return"a";
},setLinkContent:function(c,d){c.innerHTML=d;
},getPaletteHeight:function(c){var d=c.find(".rcpHeader").height()+c.find(".rcpViews").height()+c.find(".rcpTabs").height();
return d;
},adjustCustomColorPopupWidth:function(c){var e=c.style.width;
if(e.indexOf("em")!==-1){return;
}var d=parseInt(e,10)/this.getFontSize(c)+"em";
c.style.width=d;
},setTabStripWidth:function(f,h,e){if(e.indexOf("Material")>-1){var d=this.getElementSize(h);
var g=d.width;
var c=parseFloat($telerik.getComputedStyle(f,"left"),10);
var i=Math.round(g)-Math.round(c);
this.setElementInlineWidthStyle(f,i);
}}};
a.LightweightRenderer.registerClass("Telerik.Web.UI.ColorPicker.LightweightRenderer",null,a.BaseRenderer);
})();
