(function(a,D){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI;
var l=b.EventType;
var m=window;
var j=m.document;
var c=m.$telerik;
var w=m.Math;
var A=a.proxy;
var k="";
var z="px";
var B=".telerikRotator";
var g=Function.createDelegate;
c.toRotator=function(E){return E;
};
c.findRotator=$find;
a.registerEnum(b,"RotatorScrollDirection",{Left:1,Right:2,Up:4,Down:8});
a.registerEnum(b,"RotatorAnimationType",{None:1,Fade:2,Pulse:3,CrossFade:4});
a.registerEnum(b,"RotatorType",{AutomaticAdvance:1,ButtonsOver:2,Buttons:3,SlideShow:4,SlideShowButtons:5,FromCode:6,Carousel:7,CarouselButtons:8,CoverFlow:9,CoverFlowButtons:10});
b.RadRotator=function(E){var F=this;
b.RadRotator.initializeBase(F,[E]);
F._enabled=true;
F._postBackReference=null;
F._webServiceSettings=new b.WebServiceSettings({});
F._webServiceLoader=null;
F._containerElement=null;
F._clickDelegate=null;
F._mouseOutDelegate=null;
F._mouseOverDelegate=null;
F._itemShownDelegate=null;
F._rotatorDisposed=false;
F._scrollDuration=500;
F._canPause=true;
F._domScrollSpeed=0.6;
F._itemWidth=null;
F._itemHeight=null;
F._isLODEnabled=null;
F._lastLODRequestPassed=false;
F._firstLODRequestPassed=false;
F._noActiveLODRequest=true;
F._relativeWrapper=null;
F._clipElement=null;
F._itemsElement=null;
F._loadingSign=null;
F._rightButton=null;
F._leftButton=null;
F._downButton=null;
F._upButton=null;
F._firstItem=null;
F._imageItems=[];
F._initialAngle=(w.PI/2);
F._carouselAnimationAngle=F._initialAngle;
F._coverFlowAnimationIndex=-1;
F._pendingImage=null;
F._imageOnLoadDelegate=null;
F._automaticAdvanceStarted=false;
F._nextItemIndex=-1;
F._persistedItemIndex=-1;
F._isMouseOverClipElement=false;
F._clientDataSourceID=k;
F._clientTemplate=k;
F._clientDataSource=null;
F._dataSource=null;
F._ieTouchActionManager=new b.Helpers.IETouchActionManager();
F._dragHandler=A(F._onDrag,F);
F._dragEndHandler=A(F._onDragEnd,F);
};
b.RadRotator.prototype={initialize:function(){b.RadRotator.callBaseMethod(this,"initialize");
this._rotatorDisposed=false;
this._isLODEnabled=!this.isCarousel()&&!this.isCoverFlow()&&this.get_webServiceSettings().get_method();
this._setChildElements();
this._createUI();
var E=this.get_initialItemIndex();
if(this._isLODEnabled){this._enableDisableAllButtonsUnconditionally(false);
this._loadChildrenFromWebService(E);
}else{this._createChildItems();
this._initialItemSet=false;
this._loadInitialFrame();
this._enableDisableButtons();
}this._attachEventHandlers(true);
this.add_parentShown(this.get_element());
if(c.isSafari){this._mouseWheelDelegate=g(this,this._mouseWheelHandler);
$addHandler(this._relativeWrapper,"mousewheel",this._mouseWheelDelegate);
}this.raiseEvent("load",Sys.EventArgs.Empty);
if(!this._isLODEnabled){this._startAutomaticAdvance();
}this._itemShownHandler();
if(this._persistedItemIndex!=-1){this.set_currentItemIndex(this._persistedItemIndex);
}if(this.get_enableDragScrolling()&&c.isTouchDevice&&Telerik.Web.Browser.scrollBarWidth==0){Sys.UI.DomElement.addCssClass(this.get_element(),"rrTouchEnabled");
}},dispose:function(){var E=this;
if(this._imageOnLoadDelegate&&this._pendingImage){c.removeExternalHandler(this._pendingImage,"load",this._imageOnLoadDelegate);
this._pendingImage=null;
this._imageOnLoadDelegate=null;
}this._firstItem=null;
this._previousCrossFadeItems=this._currentCrossFadeItems=null;
this._rotatorDisposed=true;
this._attachEventHandlers(false);
this._containerElement=null;
if(this._animation){if(this._animation.dispose){this._animation.dispose();
}this._animation=null;
}this._imageItems=null;
b.RadRotatorAnimation._removeScrollAnimation(this.get_id());
if(this._rightButton){$clearHandlers(this._rightButton);
}if(this._leftButton){$clearHandlers(this._leftButton);
}if(this._downButton){$clearHandlers(this._downButton);
}if(this._upButton){$clearHandlers(this._upButton);
}if(c.isSafari){if(this._mouseWheelDelegate&&this._relativeWrapper){$removeHandler(this._relativeWrapper,"mousewheel",this._mouseWheelDelegate);
}}if(this._itemsElement){$clearHandlers(this._itemsElement);
}E._ieTouchActionManager.dispose();
b.RadRotator.callBaseMethod(this,"dispose");
},saveClientState:function(){return this.get_persistCurrentItemOnPostBack()?'{"currentItemIndex":'+this.get_currentItemIndex()+"}":null;
},get_currentItemIndex:function(){var E=this.get_currentItem();
return E?E.get_index():-1;
},_createChildItems:function(){var G=this;
var E=c.getChildrenByTagName(G.get_containerElement(),"li");
for(var F=0;
F<E.length;
F++){var H=$create(b.RadRotatorItem,G.get_items()[F],null,null,E[F]);
H.get_index();
E[F]._item=H;
G.get_items()[F]=H;
}G._createClientDataBoundItems();
},_createClientDataBoundItems:function(){var E=this;
if(E._clientDataSourceID){E._dataBindToClientDataSource();
}else{E._dataBindToCustomDataSource();
}},_dataBindToClientDataSource:function(){var F=this,E=F.get_clientDataSource();
if(E){F._initializeClientDataSource(E);
}else{this._initializeClientDataSourceDelegate=g(this,this._initializeClientDataSourceHandler);
Sys.Application.add_load(this._initializeClientDataSourceDelegate);
}},_initializeClientDataSourceHandler:function(){var E=this;
E._initializeClientDataSource(E.get_clientDataSource());
if(E._initializeClientDataSourceDelegate){Sys.Application.remove_load(E._initializeClientDataSourceDelegate);
E._initializeClientDataSourceDelegate=null;
}},_dataBindToCustomDataSource:function(){var F=this,E=F.get_dataSource();
if(E){F.dataBind();
}},_initializeClientDataSource:function(E){var F=this;
if(E&&(E instanceof b.RadClientDataSource)){F._clientDataSource=E;
F._bindToClientDataSourceChangeEvent();
F._clientDataSource.fetch();
}},_bindToClientDataSourceChangeEvent:function(){var F=this,E=F.get_clientDataSource();
if(E&&(E instanceof b.RadClientDataSource)){if(!F._clientDataSourceChangeDelegate){F._clientDataSourceChangeDelegate=g(F,F._clientDataSourceChangeHandler);
}E.remove_change(F._clientDataSourceChangeDelegate);
E.add_change(F._clientDataSourceChangeDelegate);
}},_clientDataSourceChangeHandler:function(){var G=this,E=G.get_clientDataSource();
if(E){var F=E._kendoDataSource.view();
G.set_dataSource(F);
G.dataBind();
}},dataBind:function(){var G=this,E=G.get_containerElement(),F=G.get_dataSource();
if(!G.get_appendClientDataBoundItems()){G.clearItems();
G.start();
}if(F){G.repaint();
G._createDataBoundItems(F);
E.style.width="";
E.style.height="";
G.repaint();
}},set_dataSource:function(E){var F=this;
F._dataSource=E;
},get_dataSource:function(){var E=this;
return E._dataSource;
},_createDataBoundItems:function(E){var H=this,F=E.length;
for(var G=0;
G<F;
G++){H._createDataBoundItem(E[G]);
}H._raiseDataBound();
},_createDataBoundItem:function(F){var H=this,I=null,G=null,E=null;
I=H._initializeRotatorDataItem(F);
G=H._createRotatorItem(I);
H._raiseItemDataBound(G,F);
E=H.get_currentItemIndex();
H.set_currentItemIndex(E);
},_initializeRotatorDataItem:function(F){var G=this;
var H={CssClass:F.CssClass,Visible:F.Visible};
var E=b.TemplateRenderer.renderTemplate(F,G);
if(E){H.Html=E;
}return H;
},_raiseItemDataBound:function(H,E){var G=this;
G._itemDataBoundHandler=G.get_events().getHandler(p);
if(H&&G._itemDataBoundHandler){var F=new b.RotatorItemDataBoundEventArgs(H,E);
G.raiseEvent(p,F);
}},_raiseDataBound:function(){this.raiseEvent(i,Sys.EventArgs.Empty);
},get_clientDataSourceID:function(){return this._clientDataSourceID;
},set_clientDataSourceID:function(E){this._clientDataSourceID=E;
},get_clientDataSource:function(){var F=this,E=$find(F.get_clientDataSourceID());
if(E&&(E instanceof b.RadClientDataSource)){return E;
}return null;
},get_clientTemplate:function(){return this._clientTemplate;
},set_clientTemplate:function(E){this._clientTemplate=E;
},_mouseWheelHandler:function(E){this._customSafariScroll(E.rawEvent.wheelDeltaX,E.rawEvent.wheelDeltaY);
E.preventDefault();
},_customSafariScroll:function(H,I){var F=H!=0?"Left":I!=0?"Top":null;
if(!F){return;
}var G=H||I;
var E=this._domScrollSpeed*G;
this._customDomScrollBy(-E,F);
},_customDomScrollBy:function(H,E){var I="scroll"+E;
for(var G=this._relativeWrapper;
G&&G.tagName;
G=G.parentNode){var F=G[I];
G[I]+=H;
if(G[I]!=F){return;
}}},_getNextItemToShow:function(){var E=this._nextItemIndex;
var G=this.getItemHtmlElements();
var F=this.isCarousel()||(this.get_wrapFrames()&&!this.isCoverFlow());
var H=null;
if(E<0){E=this._getCurrentItemIndex();
if(this.isScrollingForward()){E++;
}else{E--;
}if(F){if(E<0){E=G.length-1;
}else{if(E>G.length-1){E=0;
}}}if(E>=0&&E<G.length){H=G[E];
}}else{if(F){E=E%G.length;
}if(E>=0&&E<G.length){H=this.get_items()[E].get_element();
}}return H;
},_startAutomaticAdvance:function(){if(this.isAutomaticAdvance()&&!isNaN(this.get_frameDuration())){this._automaticAdvanceTimeOut=window.setTimeout(g(this,this._startAutoPlayItems),this.get_frameDuration());
}},get_firstItem:function(){var E=this._firstItem;
if(!E){var F=this.getItemHtmlElements();
E=this.isScrollingForward()?F[0]:F[F.length-1];
}return E;
},get_currentItem:function(){var F=this.getItemHtmlElements();
var E=this._getCurrentItemIndex();
return((0<=E&&E<F.length)?F[E].control:null);
},_getCurrentItemIndex:function(){var L=this.getItemHtmlElements();
var K=L.length;
var H=-1;
if(K<1){return -1;
}var I=this.isCarousel();
if(I||this.isCoverFlow()){var F=this._animation;
if(!F){H=this.get_initialItemIndex();
}else{if(I){var E=F.get_angle()-this._initialAngle;
H=w.round(w.abs(E)/((w.PI*2)/K));
if(E>0&&H>0){H=K-H;
}H%=K;
}else{H=F.get_index();
}}}else{var M=parseInt(L[0].parentNode.style.left,10),G="left";
if(isNaN(M)||M==0){M=parseInt(L[0].parentNode.style.top,10);
G="top";
}while(++H<K&&M<0){var J=c.getOuterSize(L[H]);
M=M+(G=="top"?J.height:J.width);
}}return H;
},set_currentItemIndex:function(L,E){var Q=this.get_items();
if(!this.get_enabled()||L<0||L>=Q.length){return;
}var R=Q[L];
if(!R){return;
}var M=this.isCarousel();
var N=this.isCoverFlow();
if(E&&(M||N)){var F=this._animation;
if(F&&this.get_pauseOnMouseOver()){F._isPaused=false;
F._isPlaying=true;
F._getAnimationQuery().filter("[paused='true']").removeAttr("paused").removeAttr("elapsedTime");
F.stop();
}this._nextItemIndex=L;
this.scrollItem();
this._nextItemIndex=-1;
}else{if(M){this._changeCarouselAngleByIndex(L);
if(!this._animation){this.set_currentItemIndex(L,true);
}}else{if(N){this._changeCoverFlowIndexByIndex(L);
if(!this._animation){this.set_currentItemIndex(L,true);
}}else{var S=R.get_element();
var W=this.get_wrapFrames();
if(W){var U=this.getItemHtmlElements();
for(var K=0,T=U.length;
K<T;
K++){if(S===U[K]){L=K;
break;
}}}var V=this._itemsElement;
var G=this._getCurrentItemIndex();
var H=parseInt(V.style.left,10)||0;
var I=parseInt(V.style.top,10)||0;
var J=(G-L);
var P=c.getOuterSize(S);
var O=this.isVertical();
if(this.get_slideShowAnimationSettings().type==b.RotatorAnimationType.CrossFade){this._resetCrossFadeAnimation();
}if(O){V.style.top=I+J*P.height+"px";
}else{V.style.left=H+J*P.width+"px";
}if(W){this._fillEmptyVisibleItems(L);
}this.raiseEvent("itemShown",new b.RotatorEventArgs(R));
}}}if(!M){this._enableDisableButtons();
}this.updateClientState();
},_fillEmptyVisibleItems:function(E){var G=this.getItemHtmlElements().length,H=w.min(this._getVisibleItemsCount(),G),F=parseInt(H-G+E,10);
if(!isNaN(F)){while(F-->0){this._shiftItemInList();
}}},_changeCarouselAngleByIndex:function(K,I,R,J){var H=this._imageItems;
var M=H.length;
if(M<1){return;
}if(K<0){K=0;
}else{if(K>(M-1)){K%=M;
}}var O=(w.PI*2)/M;
var L=I?a(H[0].element).attr("telerikCarouselAngle"):null;
var E=((typeof(L)!="undefined"&&L!=null)?L:this._initialAngle)-K*O;
if(E.toString().indexOf("e")>-1){E=(w.round(E*10000)/10000);
}var F=this._animation;
if(F){F.set_angle(E);
}else{this._carouselAnimationAngle=E;
}var G=b.RadRotatorAnimation.get_scrollAnimationProperties(this.get_id());
var Q=/^([\d+-.]+)(.*)$/;
var P=!a.support.opacity&&(G&&G.opacity!=null);
var N=this._getScrollAnimationOptions(R,J);
a.each(H,function(U,ab){var Z=this;
var Y=w.sin(E);
var V=N.minScale;
var X=V+(Y+1)*((1-V)/2);
var ac=N.xO+(((w.cos(E+w.PI)*N.xR)-Z.outerWidth/2)*X);
var ad=N.yO+((Y*N.yR)*X);
var S=a.extend({},G);
if(G){a.each(S,function(ae,ag){var af=Q.exec(ag);
S[ae]=af?(af[1]*X+af[2]):ag;
});
}var T=this.element;
T.telerikCarouselAngle=E;
var aa="px";
var W=a.extend(S,{width:Z.width*X+aa,height:Z.height*X*(P&&this.reflection?2:1)+aa,position:"absolute",left:ac+aa,top:ad+aa,zIndex:parseInt(X*100,10)});
a(T).css("display","none").css(W).css("display","");
E+=O;
if(E.toString().indexOf("e")>-1){E=(w.round(E*10000)/10000);
}});
},_getTransformProperty:function(){var E="transform";
if(c.isIE9Mode){E="msTransform";
}else{if(c.isIE){E="filter";
}else{if(c.isFirefox){E="MozTransform";
}else{if(c.isSafari){E="WebkitTransform";
}else{if(c.isOpera){E="OTransform";
}}}}}return E;
},_changeCoverFlowIndexByIndex:function(J,S,I){var H=this._imageItems;
var L=H.length;
if(L<1){return;
}if(J<0){J=0;
}else{if(J>(L-1)){J%=L;
}}var E=this._animation;
if(E){E.set_index(J);
}else{this._coverFlowAnimationIndex=J;
}var G=b.RadRotatorAnimation.get_scrollAnimationProperties(this.get_id());
var R=/^([\d+-.]+)(.*)$/;
var M=this._getScrollAnimationOptions(S,I);
var K=this.isVertical();
var N=H[J];
var O={top:M.yO-N.outerHeight/2,right:M.xO+N.outerWidth/2,bottom:M.yO+N.outerHeight/2,left:M.xO-N.outerWidth/2};
var F=M.matrix;
if(F.m11==1&&F.m22==1&&F.m12==0&&F.m21==0){F=null;
}var Q=this._getTransformProperty();
var P=("filter"==Q)&&F;
a.each(H,function(Z,am){var af=this;
var T=(Z-J);
var Y=(T==0);
var ae=Y?1:M.minScale;
var X=(T>0);
var an=K?(M.xO+af.outerWidth/2-af.outerWidth*ae):(O[X?"right":"left"]);
var ao=K?(O[X?"bottom":"top"]):(M.yO+af.outerHeight/2-af.outerHeight*ae);
var ac=T;
if(ac>0){if(K){ao+=M.yR+(--ac*M.yItemSpacing);
}else{an+=M.xR+(--ac*M.xItemSpacing);
}}else{if(ac<0){if(K){ao+=-(M.yR+af.outerHeight*ae)+(++ac*M.yItemSpacing);
}else{an+=-(M.xR+af.outerWidth*ae)+(++ac*M.xItemSpacing);
}}else{an+=M.selectedItemOffsetX;
ao+=M.selectedItemOffsetY;
}}var U=a.extend({},G);
if(G&&!Y){a.each(U,function(ap,ar){var aq=R.exec(ar);
U[ap]=aq?(aq[1]*ae+aq[2]):ar;
});
}var al="px";
var ad=a.extend(U,{width:af.width*ae+al,height:af.height*ae*(P&&this.reflection?2:1)+al,position:"absolute",zIndex:((L-w.abs(T))*100)});
var ah=0;
var aj=0;
if(F){var aa=a.extend({},F);
var ab=Y?0:(T<0?-1:1);
aa.m12*=ab;
aa.m21*=ab;
if(Y){aa.m11=aa.m22=1;
}var W=("filter"==Q);
var ag="matrix("+aa.m11+", "+aa.m21+", "+aa.m12+", "+aa.m22+", 0, 0)";
if(W){ag="progid:DXImageTransform.Microsoft.Matrix(FilterType='bilinear',M11="+aa.m11+", M12="+aa.m12+", M21="+aa.m21+", M22="+aa.m22+",sizingMethod='auto expand')";
}ad[Q]=ag;
var ai=w.abs(aa.m11)+w.abs(aa.m12);
var ak=w.abs(aa.m21)+w.abs(aa.m22);
if(!K){ah=ab*((1-ai)/2);
}else{aj=ab*((1-ak)/2);
}if(W&&!Y){ah+=(ai-1)/2;
aj+=(ak-1)/2;
if(F.m12&&this.reflection){ah*=2;
}}}ad.left=an-ah*ae*af.outerWidth+al;
ad.top=ao-aj*ae*af.outerHeight+al;
var V=this.element;
V.telerikCoverFlowIndex=T;
a(V).css("display","none").css(ad).css("display","");
});
},_needsShift:function(H){if(null==H){H=this.get_animationDirection();
}var K=this._itemsElement;
var N=this._clipElement;
var L=parseInt(K.style.left,10);
var M=parseInt(K.style.top,10);
var J=c.getOuterSize(K);
var O=c.getContentSize(N);
var F=this.get_firstItem();
if(!F){return false;
}var G=c.getOuterSize(F);
var E=false;
var I=b.RotatorScrollDirection;
switch(H){case I.Left:E=L+J.width<O.width+G.width;
break;
case I.Up:E=M+J.height<O.height+G.height;
break;
case I.Right:E=L*-1<G.width;
break;
case I.Down:E=M*-1<G.height;
break;
}return E;
},_getMoveAnimation:function(){if(!this._animation){var F=this.isCarousel();
var E=(this.get_frameDuration()<5?"easeLinear":null);
var G;
if(F||this.isCoverFlow()){G=new b.Animations[F?"jCarousel":"jCoverFlow"](this,this._itemsElement,this._imageItems,this.get_scrollDuration(),this._getScrollAnimationOptions(),b.RadRotatorAnimation.get_scrollAnimationProperties(this.get_id()),E);
if(F){G.set_angle(this._carouselAnimationAngle);
}else{G.set_index(this._coverFlowAnimationIndex==-1?this.get_initialItemIndex():this._coverFlowAnimationIndex);
}}else{G=new b.Animations.jMove(this,this._itemsElement,this.get_scrollDuration(),true,false,E);
}G.initialize();
G.set_isCyclic(this.isAutomaticAdvance()||this._isRotatorTypeEnabled(b.RotatorType.ButtonsOver));
this._animation=G;
}return this._animation;
},_initializeAnimationHandlers:function(E){this._animation.add_started(E.started);
this._animation.add_ended(E.ended);
if(this._isPaused){this._animation.pause();
}},_getScrollAnimationOptions:function(F,E){var J=F;
var I=E;
if(!J||!I){var K=c.getContentSize(this._clipElement);
J=J?J:K.width;
I=I?I:K.height;
}var H=b.RadRotatorAnimation.get_scrollAnimationOptions(this.get_id());
H.minScale=(isNaN(H.minScale)||H.minScale<0||H.minScale>1)?0.5:H.minScale;
H.reflectionHeight=isNaN(H.reflectionHeight)?0:H.reflectionHeight;
H.reflectionOpacity=isNaN(H.reflectionOpacity)?1:H.reflectionOpacity;
H.xO=isNaN(H.xO)?parseInt(J/2,10):H.xO;
if(this.isCarousel()){H.xR=isNaN(H.xR)?parseInt(J/2.3,10):H.xR;
H.yR=isNaN(H.yR)?parseInt(I/6,10):H.yR;
H.yO=isNaN(H.yO)?parseInt(H.minScale*((I-(1-H.minScale)*H.yR)/2),10):H.yO;
H.matrix=null;
}else{if(this.isCoverFlow()){var G=this.isVertical();
H.xR=isNaN(H.xR)?(G?0:15):H.xR;
H.yR=isNaN(H.yR)?(G?15:0):H.yR;
H.yO=isNaN(H.yO)?parseInt(I/2,10):H.yO;
H.xItemSpacing=isNaN(H.xItemSpacing)?(G?0:100):H.xItemSpacing;
H.yItemSpacing=isNaN(H.yItemSpacing)?(G?100:0):H.yItemSpacing;
H.selectedItemOffsetX=isNaN(H.selectedItemOffsetX)?0:H.selectedItemOffsetX;
H.selectedItemOffsetY=isNaN(H.selectedItemOffsetY)?0:H.selectedItemOffsetY;
H.matrix.m11=isNaN(H.matrix.m11)?1:H.matrix.m11;
H.matrix.m12=isNaN(H.matrix.m12)?0:H.matrix.m12;
H.matrix.m21=isNaN(H.matrix.m21)?0:H.matrix.m21;
H.matrix.m22=isNaN(H.matrix.m22)?1:H.matrix.m22;
H.coverFlowDirection=isNaN(H.coverFlowDirection)?1:(H.coverFlowDirection<0?-1:1);
}}return H;
},scrollViewport:function(){if(!this.get_enabled()){return;
}var E=this._itemsElement;
if(!this._animation){var F=this._getMoveAnimation();
this._initItemAnimation=g(this,function(){if(this.get_wrapFrames()&&!this._hasViewportWidth()){if(!this._isLODEnabled||this._noActiveLODRequest){var L=this.getItemHtmlElements().length;
for(var I=0;
I<L;
I++){this._shiftItemInList();
if(this._hasViewportWidth()){break;
}}}}var K=this._getViewPortPixelsToScroll();
var J=this.isScrollingForward();
if(this.get_vertical()){var H=parseInt(E.style.top,10)+(J?-K:K);
F.set_vertical(H);
}else{var G=parseInt(E.style.left,10)+(J?-K:K);
F.set_horizontal(G);
}if(this.isSlideShow()){this._initCrossFadeItemAnimation();
E.style.visibility="hidden";
}});
this._initializeAnimationHandlers({started:g(this,function(I,G){this.stopViewportAnimation();
if(!this.get_wrapFrames()&&!this._canSlideMore()){if(!this._isLODEnabled||this._lastLODRequestPassed){G.set_cancel(true);
return false;
}}this._doLoadOnDemand(G);
var H=this.get_currentItem();
var J=new b.RotatorCancelEventArgs(H);
this.raiseEvent("itemShowing",J);
if(J.get_cancel&&J.get_cancel()){G.set_cancel(true);
return false;
}this._initItemAnimation();
}),ended:g(this,function(){if(!this._isLODEnabled||this._lastLODRequestPassed){this._enableDisableButtons();
}if(this.isSlideShow()){var G=this.get_slideShowAnimationSettings().type||b.RotatorAnimationType.None;
if(b.RotatorAnimationType.CrossFade!=G){E.style.visibility="visible";
}this.runSlideShowAnimation();
}else{var H=this.get_currentItem();
this.raiseEvent("itemShown",new b.RotatorEventArgs(H));
}this.updateClientState();
})});
}this._animation.play();
},_getVisibleItemsCount:function(){var H=this._getVarSizeAttribute();
var G=this.getItemHtmlElements();
var E=this._getCurrentItemIndex();
if(E==-1||E>=G.length){return 0;
}var F=c.getOuterSize(G[E])[H];
if(!F&&this._isLODEnabled){F=this.get_vertical()?parseInt(this._itemHeight,10):parseInt(this._itemWidth,10);
}var I=parseInt(c.getContentSize(this._clipElement)[H]/F,10);
return I;
},_initCrossFadeItemAnimation:function(){var E=this.get_slideShowAnimationSettings().type||b.RotatorAnimationType.None;
if(b.RotatorAnimationType.CrossFade==E){var L=this._itemsElement;
var K=(-1)*parseInt(L.style.top,10)+"px";
var I=(-1)*parseInt(L.style.left,10)+"px";
var M=this.getItemHtmlElements();
var F=this._getCurrentItemIndex();
if(F>=M.length){return;
}var P=this._getVarSizeAttribute();
var J=c.getOuterSize(M[F])[P];
var Q=this._getVisibleItemsCount();
var N=F+(this.isScrollingForward()?1:-1)*Q;
if(N>=0&&N<M.length){var G=a(M[F]).css({left:I,top:K});
var O=a(M[N]).css({left:I,top:K});
var H=this.get_vertical();
while(--Q){if(H){K=(parseInt(K,10)+J+"px");
}else{I=(parseInt(I,10)+J+"px");
}if(++F<M.length){G=G.add(a(M[F]).css({left:I,top:K}));
}if(++N<M.length){O=O.add(a(M[N]).css({left:I,top:K}));
}}G.css({position:"absolute",visibility:"visible",opacity:1});
O.css({position:"absolute",visibility:"visible",opacity:0});
}}},scrollItem:function(){if(!this.get_enabled()){return;
}if(this.isCarousel()||this.isCoverFlow()){return this._scrollImageItem();
}var E=this._itemsElement;
if(!this._animation){var F=this._animation=this._getMoveAnimation();
this._initItemAnimation=g(this,function(){var J=this._getNextItemToShow();
if(!J){return;
}this._firstItem=J;
var I=c.getOuterSize(J);
if(this.isScrollingForward()){I.width*=-1;
I.height*=-1;
}if(this.get_vertical()){var H=parseInt(E.style.top,10)+I.height;
F.set_vertical(H);
}else{var G=parseInt(E.style.left,10)+I.width;
F.set_horizontal(G);
}});
this._initializeAnimationHandlers({started:g(this,function(I,G){var K=this.get_wrapFrames();
if(!K&&!this._canSlideMore()){if(!this._isLODEnabled||this._lastLODRequestPassed){G.set_cancel(true);
return false;
}}this._doLoadOnDemand(G);
var H=this.get_currentItem();
var J=new b.RotatorCancelEventArgs(H);
this.raiseEvent("itemShowing",J);
if(J.get_cancel&&J.get_cancel()){G.set_cancel(true);
return false;
}if(K&&this._needsShift()){if(!this._isLODEnabled||this._noActiveLODRequest){this._shiftItemInList();
}}if(this._stopAnimationButtonOver){return;
}this._initItemAnimation();
}),ended:g(this,function(){if(!this._isLODEnabled||this._lastLODRequestPassed){this._enableDisableButtons();
}var G=this.get_currentItem();
if(G!=null){this.raiseEvent("itemShown",new b.RotatorEventArgs(G));
}this.updateClientState();
if(this._stopAnimationButtonOver){return;
}if(this.isAutomaticAdvance()||this._isRotatorTypeEnabled(b.RotatorType.ButtonsOver)){if(this.get_frameDuration()>0){this._setAnimationTimeout(this.get_frameDuration());
}else{this._animation.play();
}}})});
}this._animation.stop();
this._animation.play();
},_scrollImageItem:function(){var E=this.isCarousel();
var F=this.isCoverFlow();
if(!this._animation){var G=this._imageItems.length;
if(G<1){return;
}this._animation=this._getMoveAnimation();
this._initializeAnimationHandlers({started:g(this,function(J,H){var I=this._getNextItemToShow();
if(!I){H.set_cancel(true);
return false;
}var K=new b.RotatorCancelEventArgs(I.control);
this.raiseEvent("itemShowing",K);
if(K.get_cancel&&K.get_cancel()){H.set_cancel(true);
return false;
}this._initItemAnimation();
}),ended:g(this,function(){var H=this._itemsElement;
if(!H||!H.parentNode){return;
}if(a(H).children("li:animated").length>1){return;
}if(F){this._enableDisableButtons();
}var I=this.get_currentItem();
if(I!=null){this.raiseEvent("itemShown",new b.RotatorEventArgs(I));
}if(this.isAutomaticAdvance()){if(this.get_frameDuration()>0){this._setAnimationTimeout(this.get_frameDuration());
}else{this._animation.play();
}}this.updateClientState();
})});
this._initItemAnimation=g(this,function(){var J=this._getCurrentItemIndex(true);
var P=this._getNextItemToShow().control.get_index();
var H=J-P;
if(E){H=w.abs(H);
if(H>w.floor(G/2)){H=w.abs(G-H);
}var L=(J+w.floor(G/2))%G;
if(P<=L&&P<=J){P+=G;
}if(L<J){L+=G;
}if(L>=P&&P>=J){H*=(-1);
}var N=this.getItemHtmlElements();
var S=(N.length>0)?((w.PI*2)/N.length):0;
H*=S;
var I=this._animation.get_angle()+H;
var M=this._initialAngle;
var R=w.PI*2+S;
if(w.round((I-(M+R))/S)==0||w.round((I-(M-R))/S)==0){var Q=P!=1?(P-G)*S:0;
I=M+H+Q;
}if(I.toString().indexOf("e")>-1){I=(w.round(I*10000)/10000);
}var K=I-H;
a(N).each(function(U,T){if(K.toString().indexOf("e")>-1){K=(w.round(K*10000)/10000);
}T.telerikCarouselAngle=K;
K+=S;
});
this._animation.set_angle(I);
}else{var O=this._animation.get_index()-this._getScrollAnimationOptions().coverFlowDirection*H;
this._animation.set_index(O);
}});
}this._animation.stop();
this._animation.play();
},_checkItemsSize:function(){var H=c.getOuterSize(this._itemsElement);
var E=this.get_vertical();
var F=(E)?H.height:H.width;
var G=(E)?this.get_height():this.get_width();
return parseInt(F,10)>parseInt(G,10);
},_shiftItemInList:function(){var O=(this._initialItemSet&&this.get_enableRandomOrder());
var K=this._itemsElement;
var J=this.getItemHtmlElements();
var H=this.get_vertical();
var G=this.isScrollingForward();
var E=parseInt(K.style.left,10);
var F=parseInt(K.style.top,10);
var L=0;
if(O){var P=this._getVisibleItemsCount();
var N=w.ceil(w.random()*(J.length-P))-1;
L=G?N:N+P;
}else{L=G?0:J.length-1;
}var M=J[L];
var I=c.getOuterSize(M);
M.parentNode.removeChild(M);
if(!G){K.insertBefore(M,K.firstChild);
}if(H){K.style.top=(F+(G?I.height:-I.height))+"px";
}else{K.style.left=(E+(G?I.width:-I.width))+"px";
}if(G){K.appendChild(M);
}return M;
},_shuffleFrames:function(){if(!this._canShuffle()){return;
}var E=this._getShuffledArray(a.makeArray(this.getItemHtmlElements()));
while(E.length){this._itemsElement.appendChild(E.pop());
}},_getShuffledArray:function(E){var F=[];
while(E.length){F.push(this._extractRandomFromArray(E));
}return F;
},_extractRandomFromArray:function(E){return E.splice(w.random()*E.length,1)[0];
},_canShuffle:function(){return !this._initialItemSet&&this.get_enableRandomOrder();
},_loadInitialFrame:function(){var G=this.get_initialItemIndex();
if(!this.isCarousel()&&!this.isCoverFlow()){this._shuffleFrames();
var E=this.get_defaultAnimationDirection();
var F=b.RotatorScrollDirection;
var H=this.isVertical();
var J=this._itemsElement;
var K=c.getOuterSize(J);
var L=c.getContentSize(this._clipElement);
var M=0;
var N=0;
G=this.get_initialItemIndex();
if(G>=0){if(H){N=(E==F.Up)?0:-K.height+L.height;
}else{M=(E==F.Left)?0:-K.width+L.width;
}}else{if(G==-1){if(H){N=(E==F.Down)?-K.height:L.height;
}else{M=(E==F.Right)?-K.width:L.width;
}}}J.style.left=M+"px";
J.style.top=N+"px";
if(G>0&&!this._initialItemSet){for(var I=0;
I<G;
I++){this._shiftItemInList();
}J.style.left=M+"px";
J.style.top=N+"px";
}}if(!this._initialItemSet&&G>=0){this.raiseEvent("itemShown",new b.RotatorEventArgs(this.get_items()[G]));
}this._initialItemSet=true;
},_setImageItems:function(){if(this._imageItems.length>0){return;
}var G={};
if(this._itemWidth){G.width=parseInt(this._itemWidth,10);
}if(this._itemHeight){G.height=parseInt(this._itemHeight,10);
}var F=(G.width&&G.height);
var E=[];
a(this.getItemHtmlElements()).each(function(I,J){var N=a.extend({},G);
if(!F){var M=a(J).css("float","left");
N=a.extend(c.getContentSize(J),N);
M.css("float","");
}var H=c.getBorderBox(J);
var L=c.getPaddingBox(J);
var K=c.getMarginBox(J);
H.horizontal+=L.horizontal+K.horizontal;
H.vertical+=L.vertical+K.vertical;
E[I]=a.extend(N,{element:J,outerWidth:(N.width+H.horizontal),outerHeight:(N.height+H.vertical)});
});
this._imageItems=E;
},stop:function(){this._clearAnimationTimeout();
this._canPause=false;
this.pause();
},pause:function(){if(this._isPaused){return;
}this._isPaused=true;
if(this._animation&&this._animation.get_isActive()){this._animation.pause();
}},start:function(){this._canPause=true;
this._isPaused=false;
this.resume();
},resume:function(){var E=this._animation;
if(!E||!E._isPlaying){if(this._timeoutPassed||!this._isPaused){if(E){E.play(this._timeoutPassed);
}}else{if(this._isPaused){if(E&&E.get_isActive()){E.play();
}}}}this._isPaused=false;
},isViewportScrollMode:function(){var E=b.RotatorType;
if(this._isRotatorTypeEnabled(E.AutomaticAdvance)||this._isRotatorTypeEnabled(E.ButtonsOver)||this._isRotatorTypeEnabled(E.FromCode)||this._isRotatorTypeEnabled(E.Carousel)||this._isRotatorTypeEnabled(E.CarouselButtons)||this._isRotatorTypeEnabled(E.CoverFlow)||this._isRotatorTypeEnabled(E.CoverFlowButtons)){return false;
}return true;
},_getButtonScrollDirection:function(E){var F=b.RotatorScrollDirection;
var G=F.Left;
switch(E){case this._rightButton:G=F.Left;
break;
case this._leftButton:G=F.Right;
break;
case this._downButton:G=F.Up;
break;
case this._upButton:G=F.Down;
break;
}return G;
},_buttonClicked:function(H){if(!this.get_enabled()){c.cancelRawEvent(H);
return false;
}this._raiseItemClickedFlags();
var E=this._animation;
if(E&&E.get_isPlaying()){E.stop();
}var G=H.target;
var I=G.parentNode;
if(I&&Sys.UI.DomElement.containsCssClass(I,"RadButton")){G=I;
}if(this._isButtonDisabled(G)||this.get_items().length==0){return;
}var F=new b.RotatorButtonEventArgs(G);
this.raiseEvent("buttonClick",F);
if(F.get_cancel()){return;
}var J=this._getButtonScrollDirection(G);
this.set_animationDirection(J);
if(this.isCarousel()||this.isCoverFlow()){this.scrollItem();
}else{this.scrollViewport();
}return c.cancelRawEvent(H);
},_buttonOver:function(G){if(!this.get_enabled()){c.cancelRawEvent(G);
return false;
}var F=G.target;
if(this._isButtonDisabled(F)||this.get_items().length==0){return;
}var E=new b.RotatorButtonEventArgs(F);
this.raiseEvent("buttonOver",E);
if(E.get_cancel()){return;
}var H=this._getButtonScrollDirection(F);
this.set_animationDirection(H);
this._stopAnimationButtonOver=false;
this.scrollItem();
return c.cancelRawEvent(G);
},_buttonOut:function(G){if(!this.get_enabled()){c.cancelRawEvent(G);
return false;
}var F=G.target;
if(this._isButtonDisabled(F)){return;
}var E=new b.RotatorButtonEventArgs(F);
this.raiseEvent("buttonOut",E);
if(E.get_cancel()){return;
}var H=this._getButtonScrollDirection(F);
this.set_animationDirection(H);
this._stopAnimationButtonOver=true;
return c.cancelRawEvent(G);
},_initializeButtonsRotatorType:function(){this._rightButton=c.getElementByClassName(this._rootElement,this._rotatorRightClass);
this._leftButton=c.getElementByClassName(this._rootElement,this._rotatorLeftClass);
this._downButton=c.getElementByClassName(this._rootElement,this._rotatorDownClass);
this._upButton=c.getElementByClassName(this._rootElement,this._rotatorUpClass);
var J=this.get_controlButtons(),I=this._clipElement,N=b.RotatorScrollDirection,M=[N.Right,N.Left,N.Down,N.Up],F=[this._leftButton,this._rightButton,this._upButton,this._downButton],L=[J.LeftButtonID?$get(J.LeftButtonID):null,J.RightButtonID?$get(J.RightButtonID):null,J.UpButtonID?$get(J.UpButtonID):null,J.DownButtonID?$get(J.DownButtonID):null],K=[this._rotatorLeftClass,this._rotatorRightClass,this._rotatorUpClass,this._rotatorDownClass],R=["marginLeft","marginRight","marginTop","marginBottom"],S=["width","width","height","height"];
for(var P=0;
P<F.length;
P++){var E=F[P];
var H=(null!=L[P])?L[P]:E;
this._createButton(E,K[P]);
if(this._isScrollDirectionEnabled(M[P])&&null==L[P]){E.style.display="block";
var T=S[P];
var G=parseInt(c.getBounds(E)[T],10);
if(isNaN(G)){G=0;
}I.style[R[P]]=G+"px";
}if(this._isRotatorTypeEnabled(b.RotatorType.Buttons)||this._isRotatorTypeEnabled(b.RotatorType.SlideShowButtons)||this._isRotatorTypeEnabled(b.RotatorType.CarouselButtons)||this._isRotatorTypeEnabled(b.RotatorType.CoverFlowButtons)){if(!Sys.UI.DomElement.containsCssClass(H,"RadButton")){$clearHandlers(H);
}$addHandlers(H,{click:this._buttonClicked},this);
}else{$clearHandlers(H);
$addHandlers(H,{mouseover:this._buttonOver,mouseout:this._buttonOut},this);
}}this._ensureButtonsPosition();
this._rightButton=L[1]||this._rightButton;
this._leftButton=L[0]||this._leftButton;
this._downButton=L[3]||this._downButton;
this._upButton=L[2]||this._upButton;
var O=false;
for(var Q=0;
Q<L.length;
Q++){if(L[Q]){O=true;
}break;
}return O;
},_ensureButtonsPosition:function(){this.set_buttonTopPosition(this._leftButton);
this.set_buttonTopPosition(this._rightButton);
this.set_buttonLeftPosition(this._upButton);
this.set_buttonLeftPosition(this._downButton);
},set_buttonTopPosition:function(E){if(!E||this._isHeightInPersent()){return;
}var F=((this._element.offsetHeight/2)-(E.offsetHeight/2)+10)+"px";
a(E).css({top:F});
},set_buttonLeftPosition:function(E){if(!E||this._isWidthInPersent()){return;
}var F=((this._element.offsetWidth/2)-(E.offsetWidth/2)+10)+"px";
a(E).css({left:F});
},runSlideShowAnimation:function(){var H=this._itemsElement;
var F=this.get_slideShowAnimationSettings().duration||500;
var E=this.get_slideShowAnimationSettings().type||b.RotatorAnimationType.None;
var G=g(this,function(){if(!H||!H.parentNode){return;
}var J=(E==b.RotatorAnimationType.CrossFade);
if(J&&a(H).children("li:animated").length>1){return;
}this._canPause=true;
if(E!=b.RotatorAnimationType.None){if(J){a(this.getItemHtmlElements()).css({position:"",visibility:""});
a(H).css("visibility","visible");
}else{a(H).css("opacity","1");
}}var K=this.get_currentItem();
this.raiseEvent("itemShown",new b.RotatorEventArgs(K));
if(!this.get_pauseOnMouseOver()||(!this._isMouseOverClipElement)){if(this.isAutomaticAdvance()){var I=this.get_frameDuration();
if(I>=0){this._setAnimationTimeout(I);
}}}});
switch(E){case b.RotatorAnimationType.Fade:this._canPause=false;
a(H).css("opacity","0").fadeTo(F,1,G);
break;
case b.RotatorAnimationType.Pulse:this._canPause=false;
a(H).fadeTo(F,0).fadeTo(F,1,G);
break;
case b.RotatorAnimationType.CrossFade:this._canPause=false;
this._runCrossFadeSlideShowAnimation(F,G);
break;
default:G();
break;
}},_runCrossFadeSlideShowAnimation:function(G,H){var M=this._itemsElement;
var L=(-1)*parseInt(M.style.top,10)+"px";
var J=(-1)*parseInt(M.style.left,10)+"px";
var N=this.getItemHtmlElements();
var E=this._getCurrentItemIndex();
if(E>=N.length){return;
}var Q=this._getVarSizeAttribute();
var K=c.getOuterSize(N[E])[Q];
var R=parseInt(c.getContentSize(this._clipElement)[Q]/K,10);
var O=E-(this.isScrollingForward()?1:-1)*R;
if(O>=0&&O<N.length){var P=a(N[O]).css({left:J,top:L});
var F=a(N[E]).css({left:J,top:L});
var I=this.get_vertical();
while(--R){if(I){L=(parseInt(L,10)+K+"px");
}else{J=(parseInt(J,10)+K+"px");
}if(++O<N.length){P=P.add(a(N[O]).css({left:J,top:L}));
}if(++E<N.length){F=F.add(a(N[E]).css({left:J,top:L}));
}}P.fadeTo(G,0,H);
F.fadeTo(G,1,H);
this._previousCrossFadeItems=P;
this._currentCrossFadeItems=F;
}},_resetCrossFadeAnimation:function(){if(!this._previousCrossFadeItems||!this._currentCrossFadeItems){return;
}this._previousCrossFadeItems.stop(true,true);
this._currentCrossFadeItems.stop(true,true);
a(this.getItemHtmlElements()).css({position:"",visibility:"",opacity:1});
a(this._itemsElement).css({visibility:"visible",opacity:1});
},_getVarSizeAttribute:function(E){return(this.get_vertical()?"height":"width");
},_hasViewportWidth:function(F){if(null==F){F=this.get_animationDirection();
}var I=this._itemsElement;
var L=this._clipElement;
var J=parseInt(I.style.left,10);
var K=parseInt(I.style.top,10);
var H=c.getOuterSize(I);
var M=c.getContentSize(L);
var E=false;
var G=b.RotatorScrollDirection;
switch(F){case G.Left:E=H.width+J<M.width*2;
break;
case G.Up:E=H.height+K<M.height*2;
break;
case G.Right:E=(J*-1<M.width);
break;
case G.Down:E=(K*-1<M.height);
break;
}return !E;
},stopViewportAnimation:function(){var F=this._animation;
if(!F){return;
}if(F.get_isPlaying()){F.stop();
var E=this.get_vertical();
var G=E?F.get_vertical():F.get_horizontal();
if(null!=G){this._itemsElement.style[E?"top":"left"]=G+"px";
}}},_getViewPortPixelsToScroll:function(){var F=this.get_vertical();
var G=c.getContentSize(this._clipElement);
var E=F?G.height:G.width;
return E;
},showNext:function(E){this.set_animationDirection(E?E:b.RotatorScrollDirection.Left);
if(!this._checkItemsSize()&&!this.isCarousel()&&!this.isCoverFlow()&&(!this._isLODEnabled||this._lastLODRequestPassed)){return;
}if(this.isViewportScrollMode()){this.scrollViewport();
}else{this.scrollItem();
}},getItemHtmlElements:function(){var F=this._itemsElement;
if(!this._hasCleanedList){var H=F.childNodes;
for(var E=0;
E<H.length;
E++){var G=H[E];
if(G&&G.tagName!="LI"){F.removeChild(G);
E--;
}}this._hasCleanedList=true;
}return F.childNodes;
},_setAnimationTimeout:function(E){this._clearAnimationTimeout();
this._currentAnimationTimeout=window.setTimeout(g(this,function(){if(!this._isPaused){this.resume();
}this._timeoutPassed=true;
}),E);
},_clearAnimationTimeout:function(){if(this._currentAnimationTimeout){window.clearTimeout(this._currentAnimationTimeout);
}this._currentAnimationTimeout=0;
this._timeoutPassed=false;
},isAutomaticAdvance:function(){var E=b.RotatorType;
if(this._isRotatorTypeEnabled(E.AutomaticAdvance)||this._isRotatorTypeEnabled(E.SlideShow)||this._isRotatorTypeEnabled(E.Carousel)||this._isRotatorTypeEnabled(E.CoverFlow)){return true;
}return false;
},isCarousel:function(){var E=b.RotatorType;
if(this._isRotatorTypeEnabled(E.Carousel)||this._isRotatorTypeEnabled(E.CarouselButtons)){return true;
}return false;
},isCoverFlow:function(){var E=b.RotatorType;
if(this._isRotatorTypeEnabled(E.CoverFlow)||this._isRotatorTypeEnabled(E.CoverFlowButtons)){return true;
}return false;
},isSlideShow:function(){var E=b.RotatorType;
if(this._isRotatorTypeEnabled(E.SlideShow)||this._isRotatorTypeEnabled(E.SlideShowButtons)){return true;
}return false;
},isScrollingForward:function(){return this.isScrollingLeft()||this.isScrollingUp();
},isScrollingLeft:function(){return this._isAnimationDirectionOn(b.RotatorScrollDirection.Left);
},isScrollingUp:function(){return this._isAnimationDirectionOn(b.RotatorScrollDirection.Up);
},_isAnimationDirectionOn:function(E){return E==this.get_animationDirection()?true:false;
},_enableDisableButtons:function(){var I=this.get_rotatorType();
if(I==b.RotatorType.AutomaticAdvance||I==b.RotatorType.Carousel||I==b.RotatorType.CoverFlow){return;
}var J=this.get_wrapFrames();
var G=this.isCarousel();
var H=this.isCoverFlow();
var E=(J&&!H)||G;
var F=b.RotatorScrollDirection;
this._enableButton(this._rightButton,E||this._canSlideMore(F.Left));
this._enableButton(this._leftButton,E||this._canSlideMore(F.Right));
this._enableButton(this._downButton,E||this._canSlideMore(F.Up));
this._enableButton(this._upButton,E||this._canSlideMore(F.Down));
},_enableDisableAllButtonsUnconditionally:function(E){this._enableButton(this._rightButton,E);
this._enableButton(this._leftButton,E);
this._enableButton(this._downButton,E);
this._enableButton(this._upButton,E);
},_enableButton:function(E,F){if(!E){return;
}if(F){Sys.UI.DomElement.removeCssClass(E,this._rotatorButtonDisabledClass);
E.removeAttribute("disabled");
}else{Sys.UI.DomElement.addCssClass(E,this._rotatorButtonDisabledClass);
E.setAttribute("disabled","disabled");
}},_canSlideMore:function(H){if(null==H){H=this.get_animationDirection();
}var E=false;
var I=b.RotatorScrollDirection;
if(this.isCoverFlow()){var G=this._getCurrentItemIndex();
var F=this._getScrollAnimationOptions().coverFlowDirection;
var K=(H==I.Right||H==I.Down);
var J=(H==I.Left||H==I.Up);
if((K&&F==1)||(J&&F==-1)){E=G>0;
}else{if((J&&F==1)||(K&&F==-1)){E=G<this.getItemHtmlElements().length-1;
}}}else{var M=this._itemsElement;
var P=this._clipElement;
var N=parseInt(M.style.left,10);
var O=parseInt(M.style.top,10);
var L=c.getBounds(M);
var Q=c.getBounds(P);
if(H==I.Left){E=(L.width+N)>Q.width;
}else{if(H==I.Up){E=(L.height+O)>Q.height;
}else{if(H==I.Right){E=(N<0);
}else{if(H==I.Down){E=(O<0);
}}}}}return E;
},_getCalculatedAnimationDirection:function(){var E=this.get_animationDirection();
var G=b.RotatorScrollDirection;
var F=23;
switch(E){case G.Left:F=21;
break;
case G.Down:F=32;
break;
case G.Up:F=12;
break;
default:F=23;
}return F;
},startAutoPlay:function(){if(this._rotatorDisposed){return;
}this._loadInitialFrame();
this._startAutoPlayItems();
},_startAutoPlayItems:function(){if(this._rotatorDisposed){return;
}if((this.isCarousel()||this.isCoverFlow())&&!this._automaticAdvanceStarted){this._automaticAdvanceStarted=true;
return;
}this.showNext(this.get_defaultAnimationDirection());
},get_defaultAnimationDirection:function(){var F=b.RotatorScrollDirection;
var E=0;
if(this._isScrollDirectionEnabled(F.Left)){E=F.Left;
}else{if(this._isScrollDirectionEnabled(F.Up)){E=F.Up;
}else{if(this._isScrollDirectionEnabled(F.Right)){E=F.Right;
}else{if(this._isScrollDirectionEnabled(F.Down)){E=F.Down;
}}}}if(!E){E=F.Left;
}return E;
},get_containerElement:function(){return this._itemsElement;
},_setChildElements:function(){this._rotatorListClass="rrItemsList";
this._rotatorListItemClass="rrItem";
this._rotatorVerticalClass="rrVerticalList";
this._rotatorRelativeWrapperClass=("rrRelativeWrapper");
this._rotatorClipRegionClass="rrClipRegion";
this._rotatorRightClass="rrButtonRight";
this._rotatorLeftClass="rrButtonLeft";
this._rotatorDownClass="rrButtonDown";
this._rotatorUpClass="rrButtonUp";
this._rotatorButtonDisabledClass="rrButtonDisabled";
this._rootElement=this.get_element();
this._relativeWrapper=c.getElementByClassName(this._rootElement,this._rotatorRelativeWrapperClass);
this._clipElement=c.getElementByClassName(this._rootElement,this._rotatorClipRegionClass);
this._itemsElement=c.getElementByClassName(this._rootElement,this._rotatorListClass);
if(this.get_items().length==0&&this._itemsElement.children.length){this._itemsElement.removeChild(this._itemsElement.firstChild);
}this._fixEmptyList();
},_fixEmptyList:function(){var E=this._itemsElement.getElementsByTagName("li");
if(this.get_items().length==0&&E.length==1){this._itemsElement.removeChild(E[0]);
}},_createUI:function(){if(!this.isVisible()){return;
}var P=this.get_element(),O=this._relativeWrapper,E=this._clipElement,F={top:0,bottom:0,left:0,right:0,horizontal:0,vertical:0},K=this._hasButtons();
if(!P){return;
}if(!this._isCreated){var L=true;
if(K){L=this._initializeButtonsRotatorType();
}if(L){Sys.UI.DomElement.addCssClass(P,"rrNoBorder");
}F=c.getBorderBox(E);
this._fixRootElementSize();
O.style.height=P.offsetHeight+F.vertical+"px";
O.style.width=P.offsetWidth+F.horizontal+"px";
this._isCreated=true;
}else{if(K){F=c.getBorderBox(E);
}}if(this.get_vertical()){this.set_vertical(true);
}O.style.overflow="auto";
E.style.overflow="auto";
var N=this._itemsElement;
if(this._isLODEnabled){N.style.width="";
N.style.height="";
}var I=10000,G;
try{I=1000+N.offsetWidth*c.getChildrenByTagName(N,"li").length;
}catch(J){I=10000;
}E.style.width=w.max(I,10000)+"px";
E.style.height="10000px";
var H=c.getMarginBox(E);
I=w.max(0,(O.offsetWidth-H.horizontal-F.horizontal))+"px";
G=w.max(0,(O.offsetHeight-H.vertical-F.vertical))+"px";
var M=this.isCarousel()||this.isCoverFlow();
if(M){this._setImageItemsSize(parseInt(I,10),parseInt(G,10),true);
}N.style.width=M?I:(this.get_vertical()?O.style.width:N.offsetWidth+"px");
N.style.height=M?G:(N.offsetHeight+"px");
O.style.overflow="";
E.style.width=I;
E.style.height=G;
E.style.overflow="hidden";
E.style.position="relative";
N.style.position="relative";
P.style.visibility="visible";
this._ensureWrappersPersentWidht();
},_hasButtons:function(){var E=this;
return E._isRotatorTypeEnabled(b.RotatorType.Buttons)||E._isRotatorTypeEnabled(b.RotatorType.ButtonsOver)||E._isRotatorTypeEnabled(b.RotatorType.SlideShowButtons)||E._isRotatorTypeEnabled(b.RotatorType.CarouselButtons)||E._isRotatorTypeEnabled(b.RotatorType.CoverFlowButtons);
},_ensureWrappersPersentWidht:function(){var E=this;
if(E._isWidthInPersent()){E._relativeWrapper.style.width="auto";
E._clipElement.style.width="auto";
}},_isWidthInPersent:function(){return this._element.style.width.indexOf("%")>-1;
},_isHeightInPersent:function(){return this._element.style.height.indexOf("%")>-1;
},_setImageItemsSize:function(F,E,G){if(this._shouldWaitForImagesToLoad(F,E)){this._waitForImagesToLoad(g(this,function(){this._finishSetImageItemSize(F,E,G);
}));
}else{this._finishSetImageItemSize(F,E,G);
}},_finishSetImageItemSize:function(F,E,H){if(H){this._shuffleFrames();
this._setImageItems();
if(this.isCarousel()){this._changeCarouselAngleByIndex(this.get_initialItemIndex(),true,F,E);
}else{this._changeCoverFlowIndexByIndex(this.get_initialItemIndex(),F,E);
}var G=this.getItemHtmlElements();
a(G).children("div").css({width:"100%",height:"100%"}).children("img").css({width:"100%",height:"100%"});
}this._createReflection(F,E);
if(H){this._startAutomaticAdvance();
}},_shouldWaitForImagesToLoad:function(F,E){var G=(this._imageItems.length>0);
var I=(this._itemWidth&&this._itemHeight);
var H=this._toCreateReflection(F,E);
return(!G&&!I)||H;
},_waitForImagesToLoad:function(E){var H=a(this._itemsElement).find("img");
this._imagesToLoad=H.length;
this._imagesLoadedDelegate=E;
this._imageOnLoadDelegate=g(this,this._loadedImageHandler);
for(var F=0,I=H.length;
F<I;
F++){var G=H[F];
if(this._isImageLoading(G)){c.addExternalHandler(G,"load",this._imageOnLoadDelegate);
G.src=G.src;
}else{this._imagesToLoad--;
}}this._checkImagesLoaded();
},_isImageLoading:function(E){return(E.width===D)||(E.src!=""&&(E.complete!==D)&&E.complete===false);
},_loadedImageHandler:function(E){c.removeExternalHandler(E.target||E.srcElement,"load",this._imageOnLoadDelegate);
this._imagesToLoad--;
this._checkImagesLoaded();
},_checkImagesLoaded:function(){if(this._imagesToLoad<=0){this._imagesLoadedDelegate.call(this);
this._imagesLoadedDelegate=Function.emptyFunction;
}},_fixRootElementSize:function(){var G=this.get_element();
if(!G){return;
}var E=b.RotatorScrollDirection;
var F=parseInt(G.style.paddingLeft,10);
if(F&&!isNaN(F)&&this._isScrollDirectionEnabled(E.Left)){G.style.width=(parseInt(G.style.width,10)+F)+"px";
G.style.paddingLeft="";
}F=parseInt(G.style.paddingRight,10);
if(F&&!isNaN(F)&&this._isScrollDirectionEnabled(E.Right)){G.style.width=(parseInt(G.style.width,1)+F)+"px";
G.style.paddingRight="";
}F=parseInt(G.style.paddingTop,10);
if(F&&!isNaN(F)&&this._isScrollDirectionEnabled(E.Up)){G.style.height=(parseInt(G.style.height,10)+F)+"px";
G.style.paddingTop="";
}F=parseInt(G.style.paddingBottom,10);
if(F&&!isNaN(F)&&this._isScrollDirectionEnabled(E.Down)){G.style.height=(parseInt(G.style.height,10)+F)+"px";
G.style.paddingBottom="";
}},_toCreateReflection:function(F,E){var G=this._getScrollAnimationOptions(F,E);
return(!this.isVertical()&&(this.isCoverFlow()||this.isCarousel())&&G.reflectionHeight>0&&G.reflectionOpacity>0);
},_createReflection:function(I,H){var K=this._imageItems;
if(!K||K.length==0||K[0].reflection||!this._toCreateReflection(I,H)){return;
}var N=this._getScrollAnimationOptions(I,H);
var J=N.reflectionHeight;
J=N.reflectionHeight=(J>1)?1:J;
var M=N.reflectionOpacity;
M=N.reflectionOpacity=(M>1)?1:M;
var P=J;
var G=(J<=0.5)?0:(J-0.5);
var L=N.matrix;
var E=b.RadRotatorAnimation.get_scrollAnimationProperties(this.get_id());
var O=(L!=null&&("filter"==this._getTransformProperty())&&!(L.m11==1&&L.m22==1&&L.m12==0&&L.m21==0))||(E&&E.opacity!=null&&!a.support.opacity);
a.each(K,function(W,Y){var T=this.element;
var V=T.getElementsByTagName("img");
V=(V&&V.length>0)?V[0]:null;
var X={width:"100%",height:"100%"};
if(V&&!this.reflection){var Q=j.createElement("canvas");
if(Q.getContext){Q.height=this.height;
Q.width=this.width;
T.appendChild(Q);
var S=Q.getContext("2d");
S.save();
S.globalAlpha=M;
S.translate(0,this.height);
S.scale(1,-1);
S.drawImage(V,0,0,this.width,this.height);
S.restore();
S.globalCompositeOperation="destination-in";
var U=S.createLinearGradient(0,0,0,this.height);
U.addColorStop(0,"rgba(255, 255, 255, "+P+")");
U.addColorStop((J>=0.5)?1:2*J,"rgba(255, 255, 255, "+G+")");
S.fillStyle=U;
S.rect(0,0,this.width,this.height);
S.fill();
this.reflection=Q;
}else{var R=a(V).clone(false).appendTo(T);
if(c.isIE){R.css({filter:"progid:DXImageTransform.Microsoft.BasicImage(rotation=2, mirror=1) progid:DXImageTransform.Microsoft.Alpha(opacity="+P*M*100+", style=1, finishOpacity="+G*M*100+", startx=0, starty=0, finishx=0, finishy="+this.height*((J>=0.5)?1:2*J)+")"});
}this.reflection=R[0];
if(O){a(T).children("div").css({height:"50%"});
X.height="50%";
}}a(this.reflection).css(X);
}});
var F=this._animation;
if(O&&(!F||!F.get_isPlaying())){if(this.isCoverFlow()){this._changeCoverFlowIndexByIndex(this._getCurrentItemIndex(),I,H);
}else{if(this.isCarousel()){this._changeCarouselAngleByIndex(this._getCurrentItemIndex(),false,I,H);
}}}},_createButton:function(E,F){var G=E;
if(!G){G=j.createElement("div");
}if(!G.className){G.className=this._rotatorDownClass;
}return G;
},_isButtonDisabled:function(E){if(!E){return true;
}return Sys.UI.DomElement.containsCssClass(E,this._rotatorButtonDisabledClass);
},_isScrollDirectionEnabled:function(E){return E&this.get_scrollDirection()?true:false;
},_isRotatorTypeEnabled:function(E){return E==this.get_rotatorType()?true:false;
},get_scrollDuration:function(){if(this.isSlideShow()){return 1;
}else{return this._scrollDuration;
}},set_scrollDuration:function(E){this._scrollDuration=E;
if(this._animation){this._animation.set_duration(this.get_scrollDuration());
}},set_vertical:function(F){var E=this._itemsElement;
if(E){Sys.UI.DomElement.addCssClass(E,this._rotatorVerticalClass);
}},get_vertical:function(){var E=b.RotatorScrollDirection;
return(this._isScrollDirectionEnabled(E.Down)||this._isScrollDirectionEnabled(E.Up));
},isVertical:function(){if(this._itemsElement){return Sys.UI.DomElement.containsCssClass(this._itemsElement,this._rotatorVerticalClass);
}return false;
},get_height:function(){return this.get_element().style.height;
},set_height:function(E){this.get_element().style.height=this._toStyleComplientValue(E);
if(this.isVisible()){this._isCreated=false;
this.repaint();
}},get_width:function(){return this.get_element().style.width;
},set_width:function(E){this.get_element().style.width=this._toStyleComplientValue(E);
if(this.isVisible()){this._isCreated=false;
this.repaint();
}},_toStyleComplientValue:function(E){return isNaN(E)?E:E+"px";
},_attachEventHandlers:function(H){var G=this;
var E=this.get_containerElement();
if(null==E){return;
}var F=a(E).find("li."+this._rotatorListItemClass);
if(H!=false){this._clickDelegate=g(this,this._mouseClickHandler);
this._mouseOutDelegate=g(this,this._mouseOutHandler);
this._mouseOverDelegate=g(this,this._mouseOverHandler);
this._itemShownDelegate=g(this,this._itemShownHandler);
F.on({mouseenter:this._mouseOverDelegate,mouseleave:this._mouseOutDelegate});
$addHandler(E,"click",this._clickDelegate);
if(this.get_enableDragScrolling()&&!this.isCarousel()&&!this.isCoverFlow()&&!this.isSlideShow()){G._dragStartHandler=A(G._onDragStart,G);
a(E).onEvent(l.Down+B,G._dragStartHandler);
G._ieTouchActionManager.element=E;
G._ieTouchActionManager.allowUserTouch();
G._dragStartHandler=A(G._onDragStart,G);
G._attachImagesDragHandler();
}this.add_itemShown(this._itemShownDelegate);
if(c.isSafari){this._documentClickDelegate=g(this,this._documentClickHandler);
this._keyDownDelegate=g(this,this._keyDownHandler);
c.addHandler(j,"click",this._documentClickDelegate);
c.addHandler(j,"keydown",this._keyDownDelegate);
}}else{if(this._mouseOverDelegate){F.off({mouseenter:this._mouseOverDelegate,mouseleave:this._mouseOutDelegate});
}if(this._clickDelegate){$removeHandler(E,"click",this._clickDelegate);
}if(this._dragStartHandler){a(E).offEvent(l.Down+B,G._dragStartHandler);
}if(this._imgDragStartHandler){G._detachImagesDragHandler();
}this._clickDelegate=this._mouseOutDelegate=this._mouseOverDelegate=this._dragStartHandler=null;
if(this._itemShownDelegate){this.remove_itemShown(this._itemShownDelegate);
}if(c.isSafari){if(this._documentClickDelegate){c.removeHandler(j,"click",this._documentClickDelegate);
this._documentClickDelegate=null;
}if(this._keyDownDelegate){c.removeHandler(j,"keydown",this._keyDownDelegate);
this._keyDownDelegate=null;
}}}},_attachImagesDragHandler:function(){var E=this;
E._imgDragStartHandler=A(E._imgDragStart,E);
E._getRotatorItemImages().on("dragstart"+B,E._imgDragStartHandler);
},_detachImagesDragHandler:function(){var E=this;
E._getRotatorItemImages().off("dragstart"+B,E._imgDragStartHandler);
},_imgDragStart:function(E){E.preventDefault();
},_getRotatorItemImages:function(){return a(this.get_element()).find(".rrItemsList .rrItem img");
},_documentClickHandler:function(E){if(this._itemClickedChanged){this._itemClickedChanged=false;
}else{if(this._itemClicked){this._itemClicked=false;
}}},_keyDownHandler:function(E){if(this._itemClicked&&(E.keyCode>32&&E.keyCode<41)&&a(E.target).is("body")){return c.cancelRawEvent(E.rawEvent);
}},_itemShownHandler:function(E){if(typeof(b.RadTicker)=="undefined"){return;
}var G=this.get_items();
for(var F=0,H=G.length;
F<H;
F++){var I=G[F];
if(this._isItemVisible(I)){this._fireTickersForItem(I);
}else{this._resetTickersForItem(I);
}}},_mouseOverHandler:function(E){var G=this;
if(G._isMouseOverClipElement){return;
}G._isMouseOverClipElement=true;
if(G.isAutomaticAdvance()&&G._canPause&&G.get_pauseOnMouseOver()){if(G.get_frameDuration()<100){this._isPaused=true;
}else{G.pause();
}}var F=G._getItemFromEvent(E.currentTarget);
if(null!=F){G.raiseEvent("mouseOver",new b.RotatorEventArgs(F));
}},_mouseOutHandler:function(E){var G=this;
if(G._isMouseOverItemsList(E.originalEvent)){return;
}G._isMouseOverClipElement=false;
if(G.isAutomaticAdvance()&&G._canPause&&G.get_pauseOnMouseOver()){G._isPaused=false;
G._setAnimationTimeout(G.get_frameDuration());
}var F=G._getItemFromEvent(E.currentTarget);
if(null!=F){G.raiseEvent("mouseOut",new b.RotatorEventArgs(F));
}return false;
},_isMouseOverItemsList:function(H){var G=c.getBounds(this.get_containerElement());
var F=c.getBounds(this._clipElement);
var E=new Telerik.Web.UI.Bounds(F.x,F.y,w.min(F.width,G.width),w.min(F.height,G.height));
var I=c.getDocumentRelativeCursorPosition(H);
return c.containsPoint(E,I.x,I.y);
},_mouseClickHandler:function(E){this._raiseItemClickedFlags();
if(!this.get_enabled()){c.cancelRawEvent(E.rawEvent);
return false;
}var G=this._getItemFromEvent(E.target);
if(null!=G){var F=new b.RotatorCancelEventArgs(G);
this.raiseEvent("itemClicking",F);
if(F.get_cancel&&F.get_cancel()){c.cancelRawEvent(E.rawEvent);
return false;
}window.setTimeout(g(this,function(){this.raiseEvent("itemClicked",new b.RotatorEventArgs(G));
this._postback(G.getServerIndex());
}),0);
}},_raiseItemClickedFlags:function(){this._itemClicked=true;
this._itemClickedChanged=true;
},_startMousePos:{},_startListPos:{},_onDragStart:function(E){var G=this;
var F=c.getEventLocation(E);
this._eventDirectionName=this.isVertical()?"clientY":"clientX";
G._startMousePos=F[G._eventDirectionName];
G._finishDragStart();
c.cancelRawEvent(E);
},_finishDragStart:function(){var H=this;
var E=a(j);
if(this.isAutomaticAdvance()){this.stop();
}var G=this.get_containerElement();
this._startListPos=this.isVertical()?parseInt(G.style.top,10):parseInt(G.style.left,10);
this._draggingCssDirection=this._getCssDirection();
var F=this._getOffsetDimension();
this._maxDragOffset=parseInt(this._clipElement.style[this._getCssDimension()],10)-G[F];
E.onEvent(l.Move+B,H._dragHandler);
E.onEvent(l.Up+B,H._dragEndHandler);
},_onDrag:function(F){var H=this;
var G=c.getEventLocation(F);
var E=G[H._eventDirectionName]-H._startMousePos;
this._offsetListWhenDragging(E);
c.cancelRawEvent(F);
},_offsetListWhenDragging:function(E){var G=this;
var F=G._itemsElement;
var H=w.min(0,G._startListPos+E);
G._isDragged=true;
F.style[G._draggingCssDirection]=w.max(G._maxDragOffset,H)+z;
},_onDragEnd:function(F){var G=this;
var E=a(j);
E.offEvent(l.Move+B,G._dragHandler);
E.offEvent(l.Up+B,G._dragEndHandler);
this.snapToEdge();
if(this.isAutomaticAdvance()){this.start();
}c.cancelRawEvent(F);
var H=!!this._isDragged;
this.add_itemClicking(function(J,I){I.set_cancel(H);
});
delete this._isDragged;
},getItemAtEdge:function(){return this._getElementAtEdge().control;
},snapToEdge:function(){var I=this;
var G=I._getElementAtEdge();
var F=I._getCssDirection();
var H=I._getOffsetDirection();
var E=I.get_containerElement();
if(G){E.style[F]=(-1)*G[H]+z;
}},_getElementAtEdge:function(){var E=this._getCssDirection();
var G=parseInt(this.isVertical()?this._itemHeight:this._itemWidth,10);
var H=this.get_containerElement();
var I=-1*parseInt(H.style[E],10);
var F=I<0?0:w.round(I/G-0.15);
return a("li",H)[F];
},_getCssDirection:function(){return this.isVertical()?"top":"left";
},_getCssDimension:function(){return this.isVertical()?"height":"width";
},_getOffsetDirection:function(){return this.isVertical()?"offsetTop":"offsetLeft";
},_getOffsetDimension:function(){return this.isVertical()?"offsetHeight":"offsetWidth";
},_postback:function(E){if(!this._postBackReference){return;
}var F=this._postBackReference.replace("arguments",E);
eval(F);
},_isItemVisible:function(G){var J=c.getContentSize(this._clipElement);
var H=c.getLocation(this._clipElement);
J.x=H.x;
J.y=H.y;
var F=c.getOuterSize(G.get_element());
H=c.getLocation(G.get_element());
F.x=H.x;
F.y=H.y;
var E=(c.containsPoint(J,F.x,F.y)&&c.containsPoint(J,F.x+F.width,F.y+F.height));
var I=(c.containsPoint(F,J.x,J.y)&&c.containsPoint(F,J.x+J.width,J.y+J.height));
return E||I;
},_fireTickersForItem:function(F){var I=F.get_tickers();
for(var E=0,G=I.length;
E<G;
E++){if(I[E]){var H=$find(I[E]);
if(H){H.startTicker();
}}}},_resetTickersForItem:function(F){var I=F.get_tickers();
for(var E=0,G=I.length;
E<G;
E++){if(I[E]){var H=$find(I[E]);
if(H){H.resetTicker();
}}}},_getItemFromEvent:function(F){var E=this.get_containerElement();
var G=null;
while(null!=F&&F!=E&&F!=j){if(F.tagName.toLowerCase()=="li"&&null!=F._item&&Object.getTypeName(F._item)=="Telerik.Web.UI.RadRotatorItem"){G=F._item;
}F=F.parentNode;
}return G;
},_initializeWebServiceLoader:function(){this._webServiceLoader=new b.WebServiceLoader(this.get_webServiceSettings());
this._webServiceLoader.add_loadingStarted(g(this,this._onItemLoadingStarted));
this._webServiceLoader.add_loadingSuccess(g(this,this._onItemLoadingSuccess));
this._webServiceLoader.add_loadingError(g(this,this._onItemLoadingError));
},_loadChildrenFromWebService:function(F){if(!this._webServiceLoader){this._initializeWebServiceLoader();
}var E=new Sys.CancelEventArgs();
E._argument=null;
E.get_argument=function(){return this._argument;
};
E.set_argument=function(H){this._argument=H;
};
this.raiseEvent("itemsRequesting",E);
if(E.get_cancel()){return;
}var G={itemIndex:F,argument:E.get_argument()};
this._webServiceLoader.loadData(G);
},loadItemsFromWebService:function(F){var E=F||0,H=this;
if(H.get_items().length==0){H._nextItemIndex=-1;
}var G=function(J,I){H.set_currentItemIndex(E);
H.start();
H.remove_itemsRequested(G);
};
H.add_itemsRequested(G);
H._enableDisableAllButtonsUnconditionally(false);
H._loadChildrenFromWebService(E);
},showLoadingSign:function(H){if(!this._loadingSign){var E=this._clipElement;
var F=j.createElement("div");
E.appendChild(F);
var G=F.style;
G.width="16px";
G.height="16px";
G.position="absolute";
G.left=w.round(E.offsetWidth/2)-8+"px";
G.top=w.round(E.offsetHeight/2)-8+"px";
Sys.UI.DomElement.addCssClass(F,"rrLoadingSign");
this._loadingSign=F;
}if(H){this._loadingSign.style.display="";
}else{this._loadingSign.style.display="none";
}},_onItemLoadingStarted:function(F,E){this._enableDisableAllButtonsUnconditionally(false);
this.showLoadingSign(true);
},_onItemLoadingSuccess:function(K,E){var J=E.get_data();
var I=this._itemsElement;
var H=I.children.length;
if(!this._firstLODRequestPassed&&H>0){I.innerHTML="";
var F=I.firstChild;
if(F&&I.removeChild){I.removeChild(F);
}}if(J&&J.length>0){for(var G=0;
G<J.length;
G++){this.addRotatorItem(J[G],H);
if(!this.isScrollingForward()){this._shiftItemInList();
}}if(this._hasButtons()){this._repaintUI();
}else{this.repaint();
}if(!this._firstLODRequestPassed){this._firstLODRequestPassed=true;
this._loadInitialFrame();
this._enableDisableAllButtonsUnconditionally(true);
this.raiseEvent("itemsRequested",Sys.EventArgs.Empty);
}else{this._enableDisableButtons();
this.raiseEvent("itemsRequested",Sys.EventArgs.Empty);
}}else{this._lastLODRequestPassed=true;
this._enableDisableButtons();
}this.showLoadingSign(false);
this._noActiveLODRequest=true;
if(this._animation&&!this._isRotatorTypeEnabled(b.RotatorType.ButtonsOver)){this._animation.play();
}},_onItemLoadingError:function(H,G){var F=G.get_message();
if(!F){F="No error data available";
}var E=new Telerik.Web.UI.RotatorErrorEventArgs(F);
this.raiseEvent("itemsRequestFailed",E);
if(!E.get_cancelErrorAlert()){alert("RadRotator items request failed :\n Exception="+F);
}this.showLoadingSign(false);
this._lastLODRequestPassed=true;
this._noActiveLODRequest=true;
this._enableDisableButtons();
if(this._animation&&!this._isRotatorTypeEnabled(b.RotatorType.ButtonsOver)){this._animation.play();
}},addRotatorItem:function(G,F){var H=this,E=H.get_containerElement();
H._createRotatorItem(G,F);
if(!H._isLODEnabled){E.style.width="";
E.style.height="";
H.repaint();
}},_createRotatorItem:function(J,G){if(G<0){return;
}var H=this.get_items(),F=this.get_containerElement(),I=F.ownerDocument.createElement("li");
a(I).addClass(this._rotatorListItemClass);
if(this._itemWidth){I.style.width=parseInt(this._itemWidth,10)+"px";
}if(this._itemHeight){I.style.height=parseInt(this._itemHeight,10)+"px";
}if(!J){J={};
}if(J.Html===D){J.Html="";
}if(J.CssClass===D){J.CssClass="";
}if(J.Visible===D){J.Visible=true;
}I.innerHTML=J.Html;
var E={cssClass:J.CssClass,visible:J.Visible};
var K=$create(b.RadRotatorItem,E,null,null,I);
I._item=K;
if(G>=F.children.length||typeof(G)=="undefined"||G==null||this._isLODEnabled){F.appendChild(I);
Array.add(H,K);
}else{F.insertBefore(I,F.children[G]);
Array.insert(this.get_items(),G,K);
this._fixItemsIndices(H,G);
}return K;
},removeRotatorItem:function(G){var L=this.get_items();
var M=L.length;
G=parseInt(G,10);
G=isNaN(G)||G>=M?M-1:G;
if(G<0){G=0;
}var E=this.get_containerElement();
if(M){this.pause();
var F=this._getCurrentItemIndex();
var I=L.splice(G,1)[0];
var K=I.get_element();
var J=c.getOuterSize(K);
E.removeChild(K);
E.style.width="";
E.style.height="";
this._firstItem=null;
if(L.length<1){this.stop();
return;
}this.repaint();
this._fixItemsIndices(L,G);
var H=this.isVertical();
if(H){var O=w.floor(parseInt(this._itemsElement.style.top,10)/J.height);
if(O!=0&&F<=w.abs(O)){this._itemsElement.style.top=(-(F-1)*J.height)+"px";
}}else{var N=w.floor(parseInt(this._itemsElement.style.left,10)/J.width);
if(N!=0&&F<=w.abs(N)){this._itemsElement.style.left=(-(F-1)*J.width)+"px";
}}var P=this.get_rotatorType();
if(P==b.RotatorType.AutomaticAdvance||P==b.RotatorType.SlideShow||P==b.RotatorType.FromCode){this.resume();
}}},_fixItemsIndices:function(G,F){var H=G.length;
for(var E=F;
E<H;
E++){G[E]._index=-1;
}},clearItems:function(){this.stop();
var E=this.get_containerElement();
var G=this.get_items();
while(G.length){var F=G.pop();
E.removeChild(F.get_element());
}var H=new Telerik.Web.UI.Bounds(0,0,0,0);
c.setBounds(this._itemsElement,H);
},isEmptyItemElement:function(){return;
},_doLoadOnDemand:function(E){var F=this._loadNextFrame();
if(this._isLODEnabled&&this._noActiveLODRequest&&F){this._animation.stop();
E.set_cancel(true);
this._noActiveLODRequest=false;
this._enableDisableAllButtonsUnconditionally(false);
this._loadChildrenFromWebService(F);
return false;
}},_loadNextFrame:function(){var E=this._getCurrentItemIndex();
var I=this._getVisibleItemsCount()||1;
var G=this.get_items().length;
var F=null;
var H=this.isScrollingForward()?E+I:E-1;
if(this.isViewportScrollMode()){H=this.isScrollingForward()?H+I-1:H-I+1;
}if(this._isLODEnabled&&!this.get_items()[H]){if(!this._lastLODRequestPassed){F=G;
}}return F;
},isVisible:function(){return(c.getInvisibleParent(this.get_element())==null);
},repaint:function(){window.clearTimeout(this._automaticAdvanceTimeOut);
var E=this.get_currentItemIndex();
this._repaintUI();
if(!this._animation){this._startAutomaticAdvance();
}else{if(this._animation.dispose){this._animation.dispose();
}this._animation=null;
this._startAutoPlayItems();
}this.set_currentItemIndex(E);
},_repaintUI:function(){if(this._isWidthInPersent()){this._relativeWrapper.style.width=this._relativeWrapper.offsetWidth+"px";
this._clipElement.style.width=this._clipElement.offsetWidth+"px";
}this._createUI();
this._enableDisableButtons();
},get_webServiceSettings:function(){return this._webServiceSettings;
},set_webServiceSettings:function(F){var E=Sys.Serialization.JavaScriptSerializer.deserialize(F);
this._webServiceSettings=new b.WebServiceSettings(E);
},get_enabled:function(){return this._enabled;
},get_rippleZonesConfiguration:function(){return[{element:this.get_element(),rippleConfigurations:[{containerSelector:".rrButton"}]}];
},set_enabled:function(E){if(E!=this._enabled){this._enabled=E;
if(this.get_isInitialized()){if(E){this.start();
}else{this.stop();
}}}}};
a.registerControlProperties(b.RadRotator,{skin:"Default",pauseOnMouseOver:true,persistCurrentItemOnPostBack:false,items:null,rotatorType:b.RotatorType.AutomaticAdvance,wrapFrames:true,scrollDirection:b.RotatorScrollDirection.Left+b.RotatorScrollDirection.Right,frameDuration:2000,controlButtons:{},initialItemIndex:0,slideShowAnimationSettings:{},animationDirection:b.RotatorScrollDirection.Left,enableRandomOrder:false,enableDragScrolling:false,appendClientDataBoundItems:false});
var o="itemClicking",n="itemClicked",y="mouseOver",x="mouseOut",t="itemShowing",u="itemShown",v="load",f="buttonOver",e="buttonOut",d="buttonClick",r="itemsRequested",q="itemsRequestFailed",s="itemsRequesting",p="itemDataBound",i="dataBound",C="templateDataBound";
a.registerControlEvents(b.RadRotator,[o,n,y,x,t,u,v,f,e,d,r,q,s,p,i,C]);
b.RadRotator.registerClass("Telerik.Web.UI.RadRotator",b.RadWebControl);
var h=function(F,E){b[F]=function(){var G=Array.prototype.slice.call(arguments);
b[F].initializeBase(this,G);
};
b[F].registerClass("Telerik.Web.UI."+F,E);
};
b.RotatorEventArgs=function(E){b.RotatorEventArgs.initializeBase(this);
this._item=E;
};
b.RotatorEventArgs.prototype={get_item:function(){return this._item;
}};
b.RotatorEventArgs.registerClass("Telerik.Web.UI.RotatorEventArgs",Sys.EventArgs);
h("RadRotatorEventArgs",Telerik.Web.UI.RotatorEventArgs);
b.RotatorCancelEventArgs=function(E){b.RotatorCancelEventArgs.initializeBase(this);
this._item=E;
};
b.RotatorCancelEventArgs.prototype={get_item:function(){return this._item;
}};
b.RotatorCancelEventArgs.registerClass("Telerik.Web.UI.RotatorCancelEventArgs",Sys.CancelEventArgs);
h("RadRotatorCancelEventArgs",Telerik.Web.UI.RotatorCancelEventArgs);
b.RotatorButtonEventArgs=function(E){b.RotatorButtonEventArgs.initializeBase(this);
this._button=E;
};
b.RotatorButtonEventArgs.prototype={get_button:function(){return this._button;
}};
b.RotatorButtonEventArgs.registerClass("Telerik.Web.UI.RotatorButtonEventArgs",Sys.CancelEventArgs);
h("RadRotatorButtonEventArgs",Telerik.Web.UI.RotatorButtonEventArgs);
b.RotatorErrorEventArgs=function(E){b.RotatorErrorEventArgs.initializeBase(this);
this._cancelErrorAlert=false;
this._errorMessage=E;
};
b.RotatorErrorEventArgs.prototype={get_errorMessage:function(){return this._errorMessage;
},get_cancelErrorAlert:function(){return this._cancelErrorAlert;
},set_cancelErrorAlert:function(E){this._cancelErrorAlert=E;
}};
b.RotatorErrorEventArgs.registerClass("Telerik.Web.UI.RotatorErrorEventArgs",Sys.EventArgs);
h("RadRotatorErrorEventArgs",Telerik.Web.UI.RotatorErrorEventArgs);
b.RotatorItemDataBoundEventArgs=function(F,E){var G=this;
b.RotatorItemDataBoundEventArgs.initializeBase(G);
G._item=F;
G._dataItem=E;
};
b.RotatorItemDataBoundEventArgs.prototype={get_item:function(){return this._item;
},get_dataItem:function(){return this._dataItem;
}};
b.RotatorItemDataBoundEventArgs.registerClass("Telerik.Web.UI.RotatorItemDataBoundEventArgs",Sys.EventArgs);
h("RadRotatorItemDataBoundEventArgs",Telerik.Web.UI.RotatorItemDataBoundEventArgs);
b.RadRotatorItem=function(E){b.RadRotatorItem.initializeBase(this,[E]);
this._visible=null;
this._cssClass=null;
this._index=-1;
};
b.RadRotatorItem.prototype={initialize:function(){b.RadRotatorItem.callBaseMethod(this,"initialize");
this._tickers=null;
},dispose:function(){b.RadRotatorItem.callBaseMethod(this,"dispose");
},get_index:function(){if(this._index==-1){var F=0;
var E=this.get_element();
var G=E.parentNode;
if(null!=G){var H=c.getChildrenByTagName(G,"li");
if(null!=H){F=0;
while(F<H.length&&H[F]!=E){F++;
}if(F==H.length){F=0;
}}}this._index=F;
}return this._index;
},getServerIndex:function(){var F=a(this.get_element());
var E=F.children("div");
if(E.length>0){var G=E[0].id.match(/_i(\d+)$/);
if(G){return parseInt(G[1],10);
}}return this.get_index();
},get_visible:function(){return this._visible;
},set_visible:function(E){this._visible=E;
},get_cssClass:function(){return this._cssClass;
},set_cssClass:function(E){this._cssClass=E;
},get_tickers:function(){if(null==this._tickers&&typeof(b.RadTicker)!="undefined"){this._tickers=[];
for(var F=0,G=c.radControls.length;
F<G;
F++){var E=c.radControls[F];
if(b.RadTicker.isInstanceOfType(E)&&c.isDescendant(this.get_element(),E.get_element())){Array.add(this._tickers,E.get_id());
}}}return this._tickers;
}};
b.RadRotatorItem.registerClass("Telerik.Web.UI.RadRotatorItem",Sys.UI.Control);
b.RadRotatorAnimationClass=function(){this._scrollAnimations={};
};
b.RadRotatorAnimationClass.prototype={get_scrollAnimationProperties:function(E){if(!E||!this._scrollAnimations[E]){return null;
}return this._scrollAnimations[E].properties;
},set_scrollAnimationProperties:function(G,F){if(!G){return;
}var E=this._scrollAnimations;
if(!E[G]){E[G]={};
}if(typeof(F)=="undefined"||F==null){delete E[G].properties;
}else{E[G].properties=F;
}},get_scrollAnimationOptions:function(G){if(!G){return null;
}var E=this._scrollAnimations;
var F=E[G]?E[G].options:{};
F=a.extend({},{xR:this.get_xRadius(G),yR:this.get_yRadius(G),xO:this.get_xCenter(G),yO:this.get_yCenter(G),minScale:this.get_minimumScale(G),xItemSpacing:this.get_xItemSpacing(G),yItemSpacing:this.get_yItemSpacing(G),selectedItemOffsetX:this.get_selectedItemOffsetX(G),selectedItemOffsetY:this.get_selectedItemOffsetY(G),matrix:this.get_matrix(G),reflectionHeight:this.get_reflectionHeight(G),reflectionOpacity:this.get_reflectionOpacity(G),coverFlowDirection:this.get_coverFlowDirection(G)},F);
return F;
},set_scrollAnimationOptions:function(G,F){if(!G){return;
}var E=this._scrollAnimations;
if(!E[G]){E[G]={};
}if(typeof(F)=="undefined"||F==null){delete E[G].options;
}E[G].options=a.extend({},this.get_scrollAnimationOptions(),F);
},get_xRadius:function(E){return this._getScrollAnimationOption(E,"xR");
},set_xRadius:function(E,F){this._setScrollAnimationOption(E,"xR",F);
},get_yRadius:function(E){return this._getScrollAnimationOption(E,"yR");
},set_yRadius:function(E,F){this._setScrollAnimationOption(E,"yR",F);
},get_xCenter:function(E){return this._getScrollAnimationOption(E,"xO");
},set_xCenter:function(E,F){this._setScrollAnimationOption(E,"xO",F);
},get_yCenter:function(E){return this._getScrollAnimationOption(E,"yO");
},set_yCenter:function(E,F){this._setScrollAnimationOption(E,"yO",F);
},get_minimumScale:function(E){return this._getScrollAnimationOption(E,"minScale");
},set_minimumScale:function(F,E){this._setScrollAnimationOption(F,"minScale",E);
},get_xItemSpacing:function(E){return this._getScrollAnimationOption(E,"xItemSpacing");
},set_xItemSpacing:function(E,F){this._setScrollAnimationOption(E,"xItemSpacing",F);
},get_yItemSpacing:function(E){return this._getScrollAnimationOption(E,"yItemSpacing");
},set_yItemSpacing:function(E,F){this._setScrollAnimationOption(E,"yItemSpacing",F);
},get_selectedItemOffsetX:function(E){return this._getScrollAnimationOption(E,"selectedItemOffsetX");
},set_selectedItemOffsetX:function(E,F){this._setScrollAnimationOption(E,"selectedItemOffsetX",F);
},get_selectedItemOffsetY:function(E){return this._getScrollAnimationOption(E,"selectedItemOffsetY");
},set_selectedItemOffsetY:function(E,F){this._setScrollAnimationOption(E,"selectedItemOffsetY",F);
},get_matrix:function(F){var E=this._getScrollAnimationOption(F,"matrix");
E=a.extend({},{m11:Number.NaN,m12:Number.NaN,m21:Number.NaN,m22:Number.NaN},E);
return E;
},set_matrix:function(F,E){this._setScrollAnimationOption(F,"matrix",E);
},get_reflectionHeight:function(E){return this._getScrollAnimationOption(E,"reflectionHeight");
},set_reflectionHeight:function(F,E){this._setScrollAnimationOption(F,"reflectionHeight",E);
},get_reflectionOpacity:function(E){return this._getScrollAnimationOption(E,"reflectionOpacity");
},set_reflectionOpacity:function(F,E){this._setScrollAnimationOption(F,"reflectionOpacity",E);
},get_coverFlowDirection:function(E){return this._getScrollAnimationOption(E,"coverFlowDirection");
},set_coverFlowDirection:function(F,E){this._setScrollAnimationOption(F,"coverFlowDirection",E);
},_getScrollAnimationOption:function(F,E){if(!F||!this._scrollAnimations[F]||!this._scrollAnimations[F].options){return Number.NaN;
}return this._scrollAnimations[F].options[E];
},_setScrollAnimationOption:function(H,F,G){if(!H){return;
}var E=this._scrollAnimations;
if(!E[H]){E[H]={};
}if(!E[H].options){E[H].options={};
}E[H].options[F]=G;
},_removeScrollAnimation:function(F){var E=this._scrollAnimations[F];
if(E){delete E.options;
delete E.properties;
E=null;
}delete this._scrollAnimations[F];
},getInstance:function(){return this;
}};
b.RadRotatorAnimationClass.registerClass("Telerik.Web.UI.RadRotatorAnimationClass",null);
if(!b.RadRotatorAnimation){b.RadRotatorAnimation=new b.RadRotatorAnimationClass();
}})($telerik.$);
