(function(a,c){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList;
a.registerEnum(b,"TileType",{RadTextTile:0,RadImageTile:1,RadImageAndTextTile:2,RadIconTile:3,RadContentTemplateTile:4,RadLiveTile:5});
a.registerEnum(b,"TileListSelectionMode",{None:1,Single:2,Multiple:4});
a.registerEnum(b,"TileListScrollingMode",{Auto:1,None:2,Native:4,Accelerated:8});
})($telerik.$);
(function(b){Type.registerNamespace("Telerik.Web.UI");
Type.registerNamespace("Telerik.Web.UI.TileList");
var a=Telerik.Web.UI.TileList;
a.TileCollection=function(){this._array=[];
};
a.TileCollection.prototype={add:function(c){this._array[this._array.length]=c;
},insertAt:function(c,d){this._array.splice(d,0,c);
},removeAt:function(c){this._array.splice(c,1);
},get_count:function(){return this._array.length;
},getItem:function(c){return this._array[c];
},indexOf:function(d){if(typeof d!="undefined"){for(var c=0,e=this._array.length;
c<e;
c++){if(this._array[c]===d){return c;
}}}return -1;
},forEach:function(e){for(var d=0,c=this.get_count();
d<c;
d++){if(e(this._array[d],d)===false){break;
}}},clear:function(){var c=this._array;
for(var d=c.length;
d>0;
d--){c.pop();
}}};
a.TileCollection.registerClass("Telerik.Web.UI.TileList.TileCollection");
})();
(function(a,c){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList;
b.TileGroup=function(){this._tiles=null;
};
b.TileGroup.prototype={get_tiles:function(){if(this._tiles==null){this._tiles=new b.TileCollection();
}return this._tiles;
},addTile:function(d){this.get_tiles().add(d);
},getTileIndex:function(d){return this._tiles.indexOf(d);
},getTile:function(d){return this._tiles.getItem(d);
}};
a.registerControlProperties(b.TileGroup,{element:null,name:""});
b.TileGroup.registerClass("Telerik.Web.UI.TileList.TileGroup");
})($telerik.$);
(function(a,c){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList;
b.TileGroupCollection=function(){this._array=[];
};
b.TileGroupCollection.prototype={add:function(d){this._array[this._array.length]=d;
},insertAt:function(d,e){this._array.splice(e,0,d);
},removeAt:function(d){this._array.splice(d,1);
},get_count:function(){return this._array.length;
},getItem:function(d){return this._array[d];
},getItemByName:function(f){for(var d=0,e=this._array.length;
d<e;
d++){if(this._array[d].get_name()===f){return this._array[d];
}}return null;
},getItemIndexByName:function(f){if(f){for(var d=0,e=this._array.length;
d<e;
d++){if(this._array[d].get_name()===f){return d;
}}}return -1;
},indexOf:function(e){if(typeof e!="undefined"){for(var d=0,f=this._array.length;
d<f;
d++){if(this._array[d]===e){return d;
}}}return -1;
},forEach:function(f){for(var e=0,d=this.get_count();
e<d;
e++){if(f(this._array[e],e)===false){break;
}}},clear:function(){var d=this._array;
for(var e=d.length;
e>0;
e--){d.pop();
}}};
b.TileGroupCollection.registerClass("Telerik.Web.UI.TileList.TileGroupCollection");
})($telerik.$);
(function(m){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList,a=$telerik.$,l=".RadTileList",h="RadTile",i=".RadTile",d=".rtlistScrollWrapper",c=".rtlistGroupSeparator",j="rtlistWrapper",k=".rtlistWrapper",e="rtileSquare",f="rtileStub",g=".rtileStub";
b.TileDraggingStrategy=function(n){this.draggable=n;
this.initialize();
};
b.TileDraggingStrategy.prototype={initialize:function(){var n=this.draggable._element;
this._draggedElement=n;
this._tileListElement=a(n).closest(l);
this._tileList=this._tileListElement[0].control;
this._createStubTile(n);
this._setDraggingStyling(n);
this._initializeBorderWrappers();
this._rowsCount=this.draggable.tileList.get_tileRows()||0;
this._tileWrapperHeight=this._tileList._tileWrapperHeight+this._tileList._getHeaderHeight();
this._sqaureTileStubHtml='<div class="'+h+" "+e+" "+f+'" style="visibility:hidden;">&nbsp;</div>';
},_createStubTile:function(n){if(!this._draggingClone){this._draggingClone=a(n).clone().html("&nbsp;").css("visibility","hidden").insertBefore(n)[0];
}},_setDraggingStyling:function(p){var C=this._tileList,o=$telerik.getBounds(this._draggingClone),r=this._tileListElement.offset(),z=this._tileListElement.css("position"),q=z=="absolute"||z=="relative",x=(q)?r.left:0,y=(q)?r.top:0,A=(q||$telerik.isOpera)?this._tileListElement.scrollLeft():0,B=(q||$telerik.isOpera)?this._tileListElement.scrollTop():0,v=0,w=0,t=0,u=0,s=this._tileListElement.offsetParent().get(0);
while(s&&s.tagName!="HTML"){var n=a(s);
v+=s.offsetLeft;
w+=s.offsetTop;
t+=n.scrollLeft();
u+=n.scrollTop();
s=n.offsetParent().get(0);
}if(C._initialScrollLeft){A-=C._initialScrollLeft;
}a(p).css({"z-index":99999,position:"absolute",left:o.x-x-v+A+t,top:o.y-y-w+B+u});
},_initializeBorderWrappers:function(){this._firstWrapper=a(k+":first",this._tileListElement)[0];
this._lastWrapper=a(k+":last",this._tileListElement)[0];
},_removeDraggingStyling:function(){a(this.draggable._element).css({"z-index":"",top:"",left:"",position:"relative"});
},_hitTileGroupTest:function(r){var s=this._getTileCenterPoint(this.draggable._element,r),q=this._draggingClone.parentNode;
if(q!==this._startTileWrapper){this._initializeDraggingContext(q);
}var n=this._hitTileGroups||[];
for(var o=0,p=n.length;
o<p;
o++){var t=n[o];
if(this._tileGroupIsHit(t,s)){this._moveDraggingClone(t);
return;
}}},_getTileCenterPoint:function(n,o){var p=o.x;
if($telerik.isOpera){p-=this._tileListElement.scrollLeft();
}return{x:p+parseInt(a(n).css("width"),10)/2,y:o.y+parseInt(a(n).css("height"),10)/2};
},_initializeDraggingContext:function(n){this._tileGroup=n.parentNode;
this._startTileWrapper=n;
this._previousTileWrapper=null;
this._nextTileWrapper=null;
a(g,this._tileListElement).remove();
if(n!=this._firstWrapper){this._previousTileWrapper=a(n).prev(k)[0]||a(k+":last",a(n.parentNode).prev().prev()[0])[0];
}if(n!=this._lastWrapper){this._nextTileWrapper=a(n).next(k)[0]||a(k+":first",a(n.parentNode).next().next()[0])[0];
}this._initializeHitTileGroups();
},_initializeHitTileGroups:function(){var o=[],n=this._getHitTileGroups(a(this._startTileWrapper).children(i),"parentWrapper");
this._initializeBorderGroups(n,"parentWrapper");
o=a.merge(o,n);
if(this._previousTileWrapper){n=this._getHitTileGroups(a(this._previousTileWrapper).children(i),"previousParentWrapper");
this._initializeBorderGroups(n,"previousParentWrapper");
o=a.merge(o,n);
}if(this._nextTileWrapper){n=this._getHitTileGroups(a(this._nextTileWrapper).children(i),"nextParentWrapper");
this._initializeBorderGroups(n,"nextParentWrapper");
o=a.merge(o,n);
}this._hitTileGroups=o;
},_initializeBorderGroups:function(n,o){if(o=="previousParentWrapper"){this._previousTileWrapperLastGroup=n[n.length-1];
}else{if(o=="nextParentWrapper"){this._nextTileWrapperFirstGoup=n[0];
}}},_tileGroupIsHit:function(r,q){for(var o=0,p=r.length;
o<p;
o++){try{if(r[o]&&$telerik.containsPoint($telerik.getBounds(r[o]),q.x,q.y)){return true;
}}catch(n){return false;
}}return false;
},_moveDraggingClone:function(n){},_preservWrapperHeight:function(u){if(!u){return;
}var v=false,s=(this._tileWrapperHeight<=u.offsetHeight)?this._getNextWrapper(u):null,q=a(u).next(k).get(0),r;
var p=this.$getWrapperLastTileElement(u);
while(p.length>0&&this._tileWrapperHeight<u.offsetHeight){p.prependTo(s);
p=this.$getWrapperLastTileElement(u);
}p=this.$getWrapperLastTileElement(u);
r=p.get(0);
if(q&&!s){if(p.hasClass(e)&&r!=this._draggingClone){var t=p.prev(i).get(0);
if(t&&(t.offsetTop!=r.offsetTop)){var o=this.$getWrapperFirstTileElement(q);
if(o.hasClass(e)){o.appendTo(u);
}s=q;
}}if(this._tileWrapperHeight<=u.offsetHeight){var n=this.$getWrapperFirstTileElement(q);
v=u.offsetHeight===0;
while(!v){if(n.length>0){n.appendTo(u);
if(this._tileWrapperHeight>=u.offsetHeight){n=this.$getWrapperFirstTileElement(q);
s=q;
}else{n.appendTo(q);
v=true;
}}else{v=true;
}}}}if(!this._removeIfEmpty(q)){this._preservWrapperHeight(q);
}},_removeIfEmpty:function(p){if(!p){return false;
}var n=false,o=p.parentNode;
this._removeStubsIn(p);
a(o).children(k).each(function(q,r){if(r.children.length==0){a(r).remove();
n=true;
}});
if(o&&o.children.length==0){a(o).next(c).remove().end().remove();
n=true;
}if(n){this.draggable.tileList._initializeScrollingWrapper();
}return n;
},_getNextWrapper:function(r){var p=this,q=0,o=a(r).next(k)[0],n;
if(!o){o=a('<div class="'+j+'">').insertAfter(r).get(0);
n=a(p._tileListElement).children(d+":first");
q=n.width()+500;
n.css("width",q+"px");
p.draggable.tileList._initializeScrollingWrapper();
p._initializeBorderWrappers();
}return o;
},_appendMissingTilesStubs:function(p,n){var q=p.offsetHeight===0;
while(!q){var o=a(this._sqaureTileStubHtml).appendTo(p)[0];
if(this._tileWrapperHeight>=p.offsetHeight){n.push([o]);
o=a(this._sqaureTileStubHtml).appendTo(p).get(0);
n.push([o]);
}else{a(o).remove();
q=true;
}}},_removeStubsIn:function(n){a(n).children(g).remove();
},$getNextTileElement:function(n){return a(n).next(i);
},$getPrevTileElement:function(n){return a(n).prev(i);
},$getWrapperFirstTileElement:function(n){return a(n).children(i).first();
},$getWrapperLastTileElement:function(n){return a(n).children(i).last();
},reset:function(){a(this._draggingClone).remove();
a(g,this._tileListElement).remove();
this._draggingClone=null;
this._startTileWrapper=null;
this._previousTileWrapper=null;
this._nextTileWrapper=null;
this._hitTileGroups=null;
}};
b.TileDraggingStrategy.registerClass("Telerik.Web.UI.TileList.TileDraggingStrategy");
})();
(function(e){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList,a=$telerik.$,c="rtileSquare",d=".rtlistWrapper";
b.WideTileDraggingStrategy=function(f){b.WideTileDraggingStrategy.initializeBase(this,[f]);
};
b.WideTileDraggingStrategy.prototype={_getHitTileGroups:function(f,l,g){var j=this,i=false,h=[],k=(f.get(0))?f.get(0).parentNode:null;
f.each(function(o,n){if(!i){if(n!==j._draggingClone&&n!==j._draggedElement){var r=[],p=a(n).hasClass(c),m=j.$getNextTileElement(n);
r.push(n);
if(p&&m.hasClass(c)){r.push(m.get(0));
i=true;
}else{if(p&&g!==false){var q=a(j._sqaureTileStubHtml).insertAfter(n).get(0);
r.push(q);
}}h.push(r);
}}else{i=false;
}});
if(g!==false){this._appendMissingTilesStubs(k,h,l);
}return h;
},_moveDraggingClone:function(m){var k=this,f=this.$getNextTileElement(this._draggingClone);
if(m.length==1){var l=m[0];
if(f.get(0)===l){a(this._draggingClone).insertAfter(l);
}else{a(this._draggingClone).insertBefore(l);
}}else{if(f.get(0)===m[0]){a(this._draggingClone).insertAfter(m[1]);
}else{a(this._draggingClone).insertBefore(m[0]);
}}var n=this._draggingClone.parentNode,g=n.parentNode;
if(this._tileGroup===g){var h=0,j=0;
if(n===this._previousTileWrapper){for(h=this._previousTileWrapperLastGroup.length-1;
h>=0;
h--){a(this._previousTileWrapperLastGroup[h]).prependTo(this._startTileWrapper);
}}else{if(n===this._nextTileWrapper){for(h=0,j=this._nextTileWrapperFirstGoup.length;
h<j;
h++){a(this._nextTileWrapperFirstGoup[h]).appendTo(this._startTileWrapper);
}}}}else{a(d,this._tileGroup).each(function(o,p){k._preservWrapperHeight(p);
});
this._preservWrapperHeight(n);
}this._removeIfEmpty(this._startTileWrapper,"test");
this._initializeDraggingContext(n);
}};
b.WideTileDraggingStrategy.registerClass("Telerik.Web.UI.TileList.WideTileDraggingStrategy",Telerik.Web.UI.TileList.TileDraggingStrategy);
})();
(function(a,f){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList,e=".RadTile",d=".rtileStub",g="rtileWide",c="rtileSquare";
b.SquareTileDraggingStrategy=function(h){b.SquareTileDraggingStrategy.initializeBase(this,[h]);
};
b.SquareTileDraggingStrategy.prototype={_getHitTileGroups:function(h,n,i){var l=this,j=[],k=false,m=(h.get(0))?h.get(0).parentNode:null;
h.each(function(q,p){var r=p===l._draggingClone;
if(!k){if(p!==l._draggedElement){var s=a(p).hasClass(c),o=l.$getNextTileElement(p);
if(!r){j.push([p]);
}if(s&&o.hasClass(c)){var t=o.get(0);
if(t!==l._draggingClone){j.push([t]);
}k=true;
}else{if(s&&i!==false){var u=a(l._sqaureTileStubHtml).insertAfter(p).get(0);
j.push([u]);
}}}}else{k=false;
}});
if(i!==false){this._appendMissingTilesStubs(m,j);
}return j;
},_moveDraggingClone:function(o){var n=o[0],l=a(n),p=this._tileWrapperHeight;
a(d,this._tileListElement).each(function(s,t){if(t!=n){a(t).remove();
}});
var m=this._draggingClone.parentNode;
var i=this.$getNextTileElement(this._draggingClone);
var k=this.$getPrevTileElement(this._draggingClone);
var j=this.$getPrevTileElement(n);
if(i.get(0)===n&&i.get(0)!==j.get(0)&&!(a(n).hasClass(g)&&k.hasClass(c)&&k.get(0).offsetTop==this._draggingClone.offsetTop)){a(this._draggingClone).insertAfter(n);
}else{a(this._draggingClone).insertBefore(n);
}if(l.is(g)){l.remove();
}var q=this._draggingClone.parentNode;
if(this._removeIfEmpty(this._startTileWrapper)){this._startTileWrapper=null;
}this._removeStubsIn(q);
if(this._nextTileWrapper&&this._startTileWrapper&&this._startTileWrapper!==q&&this._startTileWrapper.parentNode===q.parentNode&&q===this._nextTileWrapper){this._fillStartWrapperFreeSquareSpace();
var r=p<=this._startTileWrapper.offsetHeight;
while(q.children.length>1&&!r){var h=this.$getWrapperFirstTileElement(q);
if(h.get(0)==this._draggingClone){h=h.next(e);
}h.appendTo(this._startTileWrapper);
if(p<this._startTileWrapper.offsetHeight){h.appendTo(q);
r=true;
}}}if(q.parentNode!=m.parentNode){this._preservWrapperHeight(m);
}if(p<q.offsetHeight){this._preservWrapperHeight(q);
}this._initializeDraggingContext(q);
},_fillStartWrapperFreeSquareSpace:function(){if(this._checkForFreeLastSquareSpace(this._startTileWrapper)){var k=this._draggingClone.parentNode,h=null;
if(this._draggingClone===this.$getWrapperFirstTileElement(k).get(0)){var j=this.$getNextTileElement(this._draggingClone);
if(j.hasClass(c)){h=j;
}}else{var i=this.$getWrapperFirstTileElement(k);
if(i.hasClass(c)){h=i;
}}if(h){h.appendTo(this._startTileWrapper);
}}},_checkForFreeLastSquareSpace:function(j){var h=this.$getWrapperLastTileElement(j);
if(h.hasClass(c)){var i=this.$getPrevTileElement(h.get(0));
return i.length==0||i.hasClass(g)||(i.hasClass(c)&&h.offset().top!=i.offset().top);
}return false;
}};
b.SquareTileDraggingStrategy.registerClass("Telerik.Web.UI.TileList.SquareTileDraggingStrategy",Telerik.Web.UI.TileList.TileDraggingStrategy);
})($telerik.$);
(function(a,c){Type.registerNamespace("Telerik.Web.UI.TileList");
var b=Telerik.Web.UI.TileList,d="rtileWide";
b.TileDraggingStrategyFactory={createTileDraggingStrategy:function(e){if(a(e._element).hasClass(d)){return new b.WideTileDraggingStrategy(e);
}else{return new b.SquareTileDraggingStrategy(e);
}}};
})($telerik.$);
(function(a,P){Type.registerNamespace("Telerik.Web.UI.TileList");
$telerik.toTileList=function(Q){return Q;
};
$telerik.findTileList=$find;
var c=Telerik.Web.UI,d=Telerik.Web.UI.TileList,b=Sys.Serialization.JavaScriptSerializer,f=c.EventType.Down+".TL",t="rtlistRtl",r="rtlistHidden",u=".rtlistScrollWrapper",g="rtlistGroup",h=".rtlistGroup",l="rtlistGroupSeparator",m=".rtlistGroupSeparator",n="rtlistGroupSeparatorVisible",o=".rtlistGroupSeparatorVisible",i="rtlistHeader",k=".rtlistHeader",p="rtlistTitle",q=".rtlistTitle",j='<div class="'+i+'"><h6 class="'+p+'">&nbsp;</h6></div>',K="rtlistWrapper",L=".rtlistWrapper",F="RadTile",G=".RadTile",J="rtileSquare",s="(max-width: 768px)";
c.RadTileList=function(Q){var R=this;
c.RadTileList.initializeBase(R,[Q]);
R.Skin="Default";
R._embeddedSkin=true;
R._dataBindings=null;
R._height="";
R._width="";
R._groups=null;
R._tileGroupsJson="";
R._groupTitlesExist=false;
R._allTiles=[];
R._postBackReference=null;
R._renderMode=c.RenderMode.Classic;
R._mouseScroller=null;
R._wheelScrollinSpeed=45;
R._endHitScrollSpeed=4;
R._touchScrollExtender=null;
R._scrollingMode=d.TileListScrollingMode.Auto;
R._selectionMode=d.TileListSelectionMode.None;
R._tileWrapperHeight=null;
R._$element=a(Q);
R._initilaHeight=Q.style.height;
R._$scrollWrapper=R._$element.children(u+":first");
R._clientDataSourceID="";
R._clientDataSource=null;
R._clientDataSourceChangeHanlderDelgate=Function.createDelegate(this,this._clientDataSourceChangeHanlder);
R._bottomHeight=25;
R._groupNames="";
};
c.RadTileList.prototype={initialize:function(){var Q=this;
c.RadTileList.callBaseMethod(Q,"initialize");
Q.raiseEvent(N,Sys.EventArgs.Empty);
Q._groupTitlesExist=Q.get_groupTitles().length>0;
Q._setRightToLeft();
Q._initializeTileWrapperHeight();
Q._initializeGroupData();
Q._updateTileGroupsJson();
Q._initializeTilesDragAndDrop();
Q._initializeMouseScroll();
Q._initializeTouchScrollExtender();
Q._initializeScrollingWrapper();
Q._scrollTileListThrottle=a.throttle(10,Q._mouseScrollHandler);
Q._preventDefaultDelegate=function(R){$telerik.cancelRawEvent(R);
};
Q._ensureElementHeight();
Q._attachMatchMediaListeners();
Q._initializeElementRightToLeft();
Q._initializeClientDataBinding();
Q._$scrollWrapper.removeClass(r);
Q.raiseEvent(O,Sys.EventArgs.Empty);
},_initializeElementRightToLeft:function(){var Q=this;
if($telerik.isIE7&&Q._isRightToLeft){Q._element.style.direction="rtl";
Q._initialScrollLeft=Q._element.scrollLeft+10;
}},_setRightToLeft:function(){var Q=this;
if($telerik.isRightToLeft(Q.get_element())){Q._isRightToLeft=true;
Q._$element.addClass(t);
}},_ensureElementHeight:function(){var S=this,Q=S.get_allTiles(),R=Q&&Q.length>0;
if(R&&S._tileWrapperHeight!=99999999&&S.get_element().style.height==""){S._setElementHeight(S._$element.height()+S._bottomHeight+"px");
}},_attachMatchMediaListeners:function(){var Q=this;
if(window.matchMedia&&Q._renderMode==c.RenderMode.Mobile){Q._mediaListenerDelegate=Function.createDelegate(Q,Q._mediaListener);
Q._mediaQuery=window.matchMedia(s);
Q._mediaQuery.addListener(Q._mediaListenerDelegate);
}},_mediaListener:function(){this.repaint();
},_initializeTilesDragAndDrop:function(){var S=this,Q=S.get_allTiles(),T;
for(var R=0;
R<Q.length;
R++){T=Q[R];
S._initializeTileDragAndDrop(T);
}},repaint:function(){var Q=this;
Q._$scrollWrapper.css("width","auto");
Q._removeTileWrappers();
Q._initializeTileWrapperHeight();
Q._moveTilesInGroups();
Q._initializeTilesDragAndDrop();
Q._initializeScrollingWrapper();
Q._initializeMouseScroll();
Q._ensureElementHeight();
Q._initializeTouchScrollExtender();
Q._initializeTouchScrolling();
Q._$element.scrollLeft(0);
},_initializeTileWrapperHeight:function(){var R=this,S=R.get_tileRows(),Q=R._getHeaderHeight();
if(R._groupsAreFloated()){if(S>0){R._tileWrapperHeight=R._getDefaultTileHeight()*S;
R._setElementHeight(R._tileWrapperHeight+Q+R._bottomHeight);
}else{R._tileWrapperHeight=R._$element.height()-Q;
}}else{R._tileWrapperHeight=99999999;
}},_getHeaderHeight:function(){var R=this,Q;
if(!R._headerHeight){if(R._hasTitles()){Q=a(j).appendTo(R.get_element());
R._headerHeight=Q.height();
Q.remove();
}else{R._headerHeight=0;
}}return R._headerHeight;
},_hasTitles:function(){return this._groupTitlesExist;
},_getDefaultTileHeight:function(){var R=this,Q;
if(!R._defaultTileHeight){Q=a("<div class='"+F+" "+J+"' style='display: none;'>").appendTo(R.get_element());
var T=Math.ceil(parseFloat($telerik.getComputedStyle(Q.get(0),"height")));
var U=Math.ceil(parseFloat(Q.css("margin-top")));
var S=Math.ceil(parseFloat(Q.css("margin-bottom")));
R._defaultTileHeight=T+U+S;
Q.remove();
}return this._defaultTileHeight+4;
},_initializeGroupData:function(){var Q=this;
a(G,Q.get_element()).each(function(R,T){var S=T.control;
Q._appendTileInTileList(S);
});
this._initializeGroupNames();
},_initializeGroupNames:function(){var Q=this._groupNames;
if(Q){Q=b.deserialize(Q);
if(Q.length>0){this.get_groups().forEach(function(R,S){R.set_name(Q[S]||"");
});
}}},_appendTileInTileList:function(S){var R=this,U=S.get_groupIndex()||0,T=R.get_TileGroupByIndex(U),V=T.get_tiles(),Q=R.get_allTiles();
T.addTile(S);
R._moveTileInGroup(S,T);
Q.push(S);
R._attachTileEvents(S);
S.set_autoPostBack(R.get_autoPostBack());
if(isNaN(parseInt(S.get_originalGroupId(),10))){S.set_originalGroupId(U);
}if(isNaN(parseInt(S.get_originalGroupIndex(),10))){S.set_originalGroupIndex(V.get_count()-1);
}if(isNaN(parseInt(S.get_originalAllTilesIndex(),10))){S.set_originalAllTilesIndex(Q.length-1);
}},get_TileGroupByIndex:function(Q){return this.get_groups().getItem(Q)||this._appendTileGroup();
},_appendTileGroup:function(S){var T=this,U=new d.TileGroup(),Q=T.get_groups();
Q.add(U);
var R=Q.get_count()-1;
var V=T._getHeaderHtml(R);
U._element=a('<div class="'+g+'">'+V+"</div>").appendTo(T._$scrollWrapper[0]).get(0);
if(typeof(S)!="undefined"){U.set_name(S.toString());
}T._appendGroupSeparatorElement();
return U;
},_getHeaderHtml:function(S){var R="";
if(this._hasTitles()){var Q=this.get_groupTitles();
var T=Q[S]||"&nbsp;";
if(T){R=j.replace("&nbsp;",T);
}}return R;
},_appendGroupSeparatorElement:function(){a('<div class="'+l+'">&nbsp;</div>').appendTo(this._$scrollWrapper[0]);
},_moveTilesInGroups:function(){var Q=this;
Q.get_groups().forEach(function(R){R.get_tiles().forEach(function(S){Q._moveTileInGroup(S,R);
});
});
},_removeTileWrappers:function(){var Q=this;
a("."+K,Q.get_element()).each(function(T,S){var R=S.parentNode;
a(G,S).each(function(V,U){a(U).appendTo(R);
});
});
a("."+K,Q.get_element()).remove();
},_moveTileInGroup:function(S,U){var R=this,T=S.get_element(),V=U._element,W=a(V).children(L+":last").get(0);
if(!W){W=R._createTileWrapper(V);
}a(T).appendTo(W);
var Q=this._tileWrapperHeight+this._getHeaderHeight();
if(R._groupsAreFloated()&&a(W).height()>Q){W=R._createTileWrapper(V);
a(T).appendTo(W);
}},_createTileWrapper:function(Q){return a('<div class="'+K+'">').appendTo(Q).get(0);
},_initializeTileDragAndDrop:function(Q){this._removeDraggableWidget(Q);
if(this.get_enableDragAndDrop()||(this._isTouchDevice()&&this.isSelectionOn())){this._initializeDraggableWidget(Q);
}},_initializeDraggableWidget:function(T){if(T._draggableWidget){this._removeDraggableWidget(T);
}var S=T.get_element(),Q=$telerik.getComputedStyle(S,"cursor"),R=new Telerik.Web.UI.Widgets.Draggable(S,{cursorType:Q||"default",shouldPreventDefault:false,enableDelay:true,customScrollingEvaluator:function(W,X){var Y=W._getEventLocation(X),Z=W.startEventLocation,U=Math.abs(Z.x-Y.x),V=Math.abs(Z.y-Y.y);
return U>10||V>10;
}});
R.tile=T;
R.tileList=this;
T._draggableWidget=R;
this._attachDraggableEvents(T._draggableWidget);
},_removeDraggableWidget:function(Q){var R=Q._draggableWidget;
if(R&&R._options){this._removeDraggableEvents(R);
R.tile=null;
R.dispose();
R=null;
}},_attachDraggableEvents:function(R){var Q=this;
Q._dragStartingDelegate=Function.createDelegate(Q,Q._onDragStarting);
Q._dragStartDelegate=Function.createDelegate(Q,Q._onDragStart);
Q._draggingDelegate=Function.createDelegate(Q,Q._onDragging);
Q._dragEndtDelegate=Function.createDelegate(Q,Q._onDragEnd);
R.add_dragStarting(Q._dragStartingDelegate);
R.add_dragStart(Q._dragStartDelegate);
R.add_dragging(Q._draggingDelegate);
R.add_dragEnd(Q._dragEndtDelegate);
},_removeDraggableEvents:function(R){var Q=this;
if(Q._dragStartingDelegate){R.remove_dragStart(Q._dragStartingDelegate);
}if(Q._dragStartDelegate){R.remove_dragStart(Q._dragStartDelegate);
}if(Q._draggingDelegate){R.remove_dragging(Q._draggingDelegate);
}if(Q._dragEndtDelegate){R.remove_dragEnd(Q._dragEndtDelegate);
}},_onDragStarting:function(R,Q){R.startEventLocation=R._getEventLocation(Q._domEvent);
R.tile.set_dragStarted(false);
},_enableTilesDraggableWidget:function(V,R){var Q=this.get_allTiles();
for(var S=0,T=Q.length;
S<T;
S++){var U=Q[S];
if(U!==R){U._draggableWidget.set_enabled(V);
}}},_onDragStart:function(S,Q){var V=this,R=Q._domEvent,T=V.get_enableDragAndDrop(),U=new c.TileListCancelEventArgs(S.tile,null),W=S.tile;
U.draggableEventArgs=Q;
V.raiseEvent(B,U);
if(U.get_cancel()||R.button===2){S._tlDragStarted=false;
Q.set_cancel(true);
}else{S._tlDragStarted=true;
W.set_dragStarted(true);
V._disposeTouchScrollExtender();
if(V._isTouchEvent(R)){V._setTouchSelectionStart(S);
V._enableTilesDraggableWidget(false,W);
}else{Q.set_cancel(!T);
}if(T){V._initializeDraggingContext(S);
V._moveDraggedElementToTileListElement(S);
V._startListElementHitTestInerval(S);
V._startListEndHitTestInterval(S);
}}},_isTouchEvent:function(Q){return c.Widgets.Draggable.isTouchEvent(Q);
},_setTouchSelectionStart:function(Q){var S=this,R=Q._element;
a(R).onEvent(f,S._preventDefaultDelegate);
if(S.isSelectionOn()){S._setSelectionStyling(Q,true);
}},_setSelectionStyling:function(Q,R){Q.tile._setIntentionSelectionUI(R);
},_initializeDraggingContext:function(Q){Q._deltaX=0;
Q._deltaY=0;
Q._draggingPosition=null;
Q._draggingStrategy=d.TileDraggingStrategyFactory.createTileDraggingStrategy(Q);
},_moveDraggedElementToTileListElement:function(Q){this.get_element().appendChild(Q._element);
},_startListElementHitTestInerval:function(Q){this._tileGroupHitTestInerval=window.setInterval(Function.createDelegate(this,function(){this._tileElementHitTest(Q);
}),15);
},_tileElementHitTest:function(Q){var R=Q._draggingStrategy;
if(R&&Q._draggingPosition){R._hitTileGroupTest(Q._draggingPosition);
this._hitTileListGroupSeparator(Q);
}},_startListEndHitTestInterval:function(Q){var R=this;
if(R.get_scrollingMode()!=d.TileListScrollingMode.None&&R._tileWrappersAreFloated()){R._tileListEndHitTestInterval=window.setInterval(Function.createDelegate(R,function(){R._tileListEndHitTest(Q);
}),200);
}},_tileListEndHitTest:function(Q){if(Q&&Q._draggingPosition){var V=this._endHitScrollSpeed,R=this.get_element(),U=a(R).offsetParent().get(0),S=R.offsetLeft+((U)?U.offsetLeft:0),T=S+parseInt(a(R).css("width"),10),W=Q._draggingPosition.x,X=W+parseInt(a(Q._element).css("width"),10);
if(this._isRightToLeft){if(X>T){this._scrollTileListThrottle(null,V,false);
}if(W<S){this._scrollTileListThrottle(null,-V,false);
}}else{if(X>T){this._scrollTileListThrottle(null,-V,false);
}else{if(W<S){this._scrollTileListThrottle(null,V,false);
}}}}},_onDragging:function(S,Q){var U=this,R=Q._domEvent;
$telerik.cancelRawEvent(R);
if(S._tlDragStarted===true){S._draggingPosition=Q.get_newPosition();
U._setDraggingDeltas(S,Math.abs(Q._delta.x),Math.abs(Q._delta.y));
if(U._isTouchEvent(R)&&U.isSelectionOn()){U._handleTouchSelection(S,Q);
}if(U._hasMoved(S)){var T=new c.TileListEventArgs(S.tile);
T.draggableEventArgs=Q;
U.raiseEvent(C,T);
}}else{Q.set_cancel(true);
}},_setDraggingDeltas:function(S,Q,R){if(S._deltaY<R){S._deltaY=R;
}if(S._deltaX<Q){S._deltaX=Q;
}},_hasMoved:function(Q){return Q._deltaX!==0||Q._deltaY!==0;
},_handleTouchSelection:function(R,Q){var S=this;
if(Math.abs(Q._delta.y)<40&&!S._selectionPointReached){if(S._dragSelection!==true){S._setSelectionConstrains(R);
S._dragSelection=true;
S._setSelectionStyling(R,true);
}}else{S._selectionPointReached=true;
S._setSelectionStyling(R,false);
S._dragSelection=false;
S._removeSelectionConstrains(R);
Q.set_cancel(!S.get_enableDragAndDrop());
}},_setSelectionConstrains:function(Q){var R=Q._element,S=a(R).offset().left;
a.extend(Q.get_constraints(),{minX:S,maxX:S+parseInt(R.offsetWidth,10)});
},_removeSelectionConstrains:function(Q){a.extend(Q.get_constraints(),{minX:null,maxX:null});
},_hitTileListGroupSeparator:function(Q){var Z=this,S=Q._element,R=Q._draggingStrategy,Y=(R)?R._getTileCenterPoint(S,Q._draggingPosition):$telerik.getBounds(S),X=Z._getSeparatorElements();
Z._hideVisibleSeaprator();
for(var U=0,V=X.length;
U<V;
U++){var W=X[U],T=Z._getSeparatorBounds(W);
if($telerik.containsPoint(T,Y.x,Y.y)){a(W).addClass(n);
break;
}}},_getSeparatorElements:function(){return this._$scrollWrapper.children(m).toArray();
},_getVisibleSeaprator:function(){return this._$scrollWrapper.children(m+o+":first");
},_hideVisibleSeaprator:function(){this._getVisibleSeaprator().removeClass(n);
},_getSeparatorBounds:function(R){var Q=$telerik.getBounds(R);
Q.x-=20;
Q.width+=50;
return Q;
},_onDragEnd:function(R,Q){var S=this,T=R.tile,U;
S._clearHitTestIntervals();
U=S._riseTileDroppingEvent(R,Q);
if(R._tlDragStarted!==true){S._dropDraggedElement(R);
Q.set_cancel(true);
}else{R._tlDragStarted=false;
if(S._isTouchEvent(Q._domEvent)){S._enableTilesDraggableWidget(true);
}S._removeDraggingStyling(R);
S._removeDraggedElementMouseDownPreventDefault(R);
S._setDraggedTileSelectionState(R,Q);
S._dropDraggedElement(R);
S._handleClickAfterDragging(R,Q);
T.clearDragStarted();
S._clearDraggingContext(R);
S._resetAllTilesArray();
S._resetTileGroups();
S._updateTileGroupsJson();
if(!U.get_cancel()){S.raiseEvent(D,S._getTileDroppedEventArgs(T));
}window.setTimeout(function(){S._initializeTouchScrollExtender();
},100);
}},_riseTileDroppingEvent:function(R,Q){var T=this._hasMoved(R);
var S=new c.TileListCancelEventArgs(R.tile,null);
S.draggableEventArgs=Q;
if(T){this.raiseEvent(E,S);
if(S.get_cancel()){R._tlDragStarted=false;
}}else{S.set_cancel(true);
}return S;
},_clearHitTestIntervals:function(){window.clearInterval(this._tileGroupHitTestInerval);
window.clearInterval(this._tileListEndHitTestInterval);
},_dropDraggedElement:function(Q){var S=Q._draggingStrategy;
if(S){S._draggedElement=null;
var T=this._getVisibleSeaprator().get(0);
var R=S._draggingClone;
if(T){this._moveDraggingCloneToNewGroup(R,T);
}a(Q._element).insertBefore(R);
S.reset();
}},_moveDraggingCloneToNewGroup:function(Q,T){var S=this,R;
S._hideVisibleSeaprator();
R=S._inserTileListGroupAfter(T);
if(R){a(Q).appendTo(a(L,R)[0]);
S._initializeScrollingWrapper();
}},_inserTileListGroupAfter:function(S){if(S){a(S).clone().insertAfter(S);
var Q=a('<div class="'+g+'">'+this._getHeaderHtml()+'<div class="'+K+'"></div></div>').insertAfter(S).get(0);
var R=a(h).index(Q);
var T=new d.TileGroup();
T._element=Q;
this.get_groups().insertAt(T,R);
return Q;
}return null;
},_removeDraggingStyling:function(Q){if(Q._draggingStrategy){Q._draggingStrategy._removeDraggingStyling();
}},_removeDraggedElementMouseDownPreventDefault:function(Q){a(Q._element).offEvent(f,this._preventDefaultDelegate);
},_setDraggedTileSelectionState:function(R,Q){if(this._isTouchEvent(Q._domEvent)){var T=R.tile,S=a(R._element).hasClass("rtileSelectIntention");
T._setIntentionSelectionUI(false);
T.set_selected(S);
}},_handleClickAfterDragging:function(R,Q){var T=R.tile,S=this.get_enableDragAndDrop()&&!this._isTouchEvent(Q._domEvent)&&R._deltaX<5&&R._deltaY<5;
if(S){T.set_dragStarted(false);
if(!$telerik.isFirefox&&!$telerik.isMobileSafari){T._mouseClickHandler();
}R._deltaY=0;
R._deltaX=0;
}},_clearDraggingContext:function(Q){this._selectionPointReached=false;
Q._draggingPosition=null;
this._removeEmptyGroups();
},_removeEmptyGroups:function(){var Q=this;
this._$scrollWrapper.children(h).each(function(T,S){var R=a(S);
R.children(L).each(function(U,V){if(V.children.length==0){a(V).remove();
}});
if(R.children(L).length==0){R.next(m).remove().end().remove();
Q.get_groups().removeAt(T);
}});
},_resetAllTilesArray:function(){var Q=this;
this._allTiles=[];
a(G,this.get_element()).each(function(S,R){if(R.control){Q._allTiles.push(R.control);
}});
},_resetTileGroups:function(){var R=this,S,Q=R.get_groups();
a(h,this.get_element()).each(function(U,T){S=Q.getItem(U)||new d.TileGroup();
S.get_tiles().clear();
S._element=T;
a(G,T).each(function(W,V){S.addTile(V.control);
});
Q.add(S);
});
},updateTileGroupsState:function(){this._updateTileGroupsJson();
},_updateTileGroupsJson:function(){var Q=this,R=[];
a(h,Q.get_element()).each(function(T,S){a(G,S).filter(":visible").each(function(W,V){var U=V.control;
if(U){R.push([T,U.get_originalGroupId(),U.get_originalGroupIndex()]);
}});
});
if(R.length>0){Q._tileGroupsJson=(R.length>0)?b.serialize(R):"";
}Q.updateClientState();
},_getTileDroppedEventArgs:function(S,Q){var R=new c.TileListEventArgs(S);
R.group=this.get_groupByTile(S);
R.draggableEventArgs=Q;
return R;
},get_groupByTile:function(R){var Q=null;
this.get_groups().forEach(function(S,T){if(S.getTileIndex(R)!=-1){Q=S;
return false;
}});
return Q;
},_attachTileEvents:function(R,S){var Q=this;
Q._onTileSelectingDelegate=Function.createDelegate(Q,Q._onTileSelecting);
Q._onTileSelectedDelegate=Function.createDelegate(Q,Q._onTileSeleced);
Q._onTileClickingDelegate=Function.createDelegate(Q,Q._onTileClicking);
Q._onTileClickedDelegate=Function.createDelegate(Q,Q._onTileClicked);
R.add_selecting(Q._onTileSelectingDelegate);
R.add_selected(Q._onTileSelectedDelegate);
R.add_clicking(Q._onTileClickingDelegate);
R.add_clicked(Q._onTileClickedDelegate);
},_onTileSelecting:function(W,Q){var V=this,U=d.TileListSelectionMode,T=V.get_selectionMode(),X=V.get_allTilesIndex(W),S,R,Y;
if(T!=U.None){S=new c.TileListCancelEventArgs(W,Q.get_value());
S.set_cancel(Q.get_cancel());
V.raiseEvent(I,S);
R=S.get_cancel();
Y=S.get_value();
Q.set_cancel(R);
Q.set_value(Y);
if(!R){if(Y&&T==U.Single){V.clearSelection(X);
}}}},_onTileSeleced:function(S,Q){var R=new c.TileListEventArgs(S,Q.get_newValue(),Q.get_oldValue());
this.raiseEvent(H,R);
Q.set_cancel(R.get_cancel());
},_onTileClicking:function(S,Q){var R=new c.TileListCancelEventArgs(S,Q.get_value());
R.set_cancel(Q.get_cancel());
this.raiseEvent(w,R);
Q.set_cancel(R.get_cancel());
Q.set_value(R.get_value());
},_onTileClicked:function(S,Q){var R=new c.TileListEventArgs(S,Q.get_newValue(),Q.get_oldValue());
this.raiseEvent(v,R);
Q.set_cancel(R.get_cancel());
},_initializeMouseScroll:function(){var R=this,Q=R.get_scrollingMode();
R._disposeMouseScroller();
if(R._groupsAreFloated()&&Q!=d.TileListScrollingMode.None&&!R._mouseScroller){R._mouseScroller=new c.Widgets.MouseScroll(R.get_element(),Function.createDelegate(R,R._mouseScrollHandler),{cancelRawEvent:true});
}},_mouseScrollHandler:function(T,R,X){var W=this,V=(W._isRightToLeft&&(!$telerik.isIE||$telerik.isIE7))?parseInt(R,10):-(parseInt(R,10)),S=W.get_element(),U=S.scrollLeft+(V*W._wheelScrollinSpeed);
var Q={duration:500,complete:function(){}};
if(X!==false){Q.easing="easeInQuad";
}a(S).stop(true).animate({scrollLeft:U},Q);
},_initializeTouchScrollExtender:function(){var Q=this;
if(Q._shouldCreateTouchScrollExtender(Q.get_scrollingMode())&&Q._tileWrappersAreFloated()){Q._createTouchScrollExtender();
}else{Q._disposeTouchScrollExtender();
}},_initializeTouchScrolling:function(){var R=this,Q=R.get_element();
if(R._scrollingMode==d.TileListScrollingMode.Accelerated&&$telerik.isTouchDevice){a(Q).addClass("rtlistScrollTouch");
}else{a(Q).removeClass("rtlistScrollTouch");
}},_initializeScrollingWrapper:function(){var S=this,R=S._$scrollWrapper,Q=S._$element;
R.css({width:"1000000px"}).css({width:S._calculateScrollingWrapperWidth()});
if(R.width()>Q.width()){Q.css({overflowX:""});
}},_calculateScrollingWrapperWidth:function(){var S=this,U=0,R=S.get_element(),Q=a(L+":first",R),T=Q.width();
if(!S._tileWrappersAreFloated()){return"auto";
}else{if(!S._groupsAreFloated()){a(h,R).each(function(W,V){var X=a(L,V).length;
U=Math.max(U,X*T);
});
}else{a(h+","+m,this.get_element()).each(function(){var V=a(this);
U+=V.width()+(parseInt(V.css("margin-left"),10)||0)+(parseInt(V.css("margin-right"),10)||0)+5;
});
}}return U?U+"px":"";
},_tileWrappersAreFloated:function(){var U=this,S=U.get_element(),Q=a(L+":first",U.get_element()),T,R;
if(Q.length==0){T=a('<div class="'+K+'">').appendTo(S);
R=T.css("float");
T.remove();
}else{R=Q.css("float");
}return R=="left"||R=="right";
},_groupsAreFloated:function(){var T=this,Q=a(m+":first",T.get_element()),S;
if(Q.length==0){var R=a('<div class="'+K+'">').appendTo(T._$scrollWrapper[0]);
S=R.css("float");
R.remove();
}else{S=Q.css("float");
}return S=="left"||S=="right";
},_shouldCreateTouchScrollExtender:function(Q){return Q==d.TileListScrollingMode.Accelerated&&!$telerik.isTouchDevice;
},_createTouchScrollExtender:function(){var R=this;
if(!R._touchScrollExtender){var Q=R.get_element();
if(Q){R._touchScrollExtender=new c.TouchScrollExtender(Q);
R.overWriteCancelEvents(R._touchScrollExtender);
R._touchScrollExtender.initialize();
}}},overWriteCancelEvents:function(Q){Q._cancelEvents=function(S,T,U,R){if((!T||!U)||(R!="compositeDragger"&&T&&U&&Math.abs(T.dragStartY-U.y)<200)){$telerik.cancelRawEvent(S);
}};
},dispose:function(){var Q=this;
Q._detachMatchMediaListeners();
Q._detachAllTilesEvents();
Q._disposeTouchScrollExtender();
Q._disposeMouseScroller();
c.RadTileList.callBaseMethod(Q,"dispose");
},_detachMatchMediaListeners:function(){var Q=this;
if(Q._mediaQuery&&Q._mediaListenerDelegate){Q._mediaQuery.removeListener(Q._mediaListenerDelegate);
}},_detachAllTilesEvents:function(){var Q=this.get_allTiles();
for(var R=0;
R<Q.length;
R++){this._detachTileEvents(Q[R]);
}},_disposeTouchScrollExtender:function(){var Q=this;
if(Q._touchScrollExtender){Q._touchScrollExtender.dispose();
Q._touchScrollExtender=null;
Q._intializeOverflowX();
}},_detachTileEvents:function(R){var Q=this;
R.remove_selecting(Q._onTileSelectingDelegate);
R.remove_selected(Q._onTileSelectedDelegate);
R.remove_clicking(Q._onTileClickingDelegate);
R.remove_clicked(Q._onTileClickedDelegate);
},_disposeMouseScroller:function(){var Q=this;
if(Q._mouseScroller){Q._mouseScroller.dispose();
Q._mouseScroller=null;
}},_initializeClientDataBinding:function(){var R=this,Q=R.get_clientDataSourceID();
if(Q&&$find(Q)==null){Sys.Application.add_load(function(){R.dataBind();
});
}else{R.dataBind();
}},dataBind:function(){var R=this,Q=R.get_clientDataSource();
if(Q){R._bindToClientDataSource(Q);
}else{R._dataBind();
}},_removeAllTiles:function(){var Q=this.get_allTiles();
while(Q.length>0){var R=Q.pop();
this._removeTile(R);
}this.get_groups().clear();
this._$scrollWrapper[0].innerHTML="";
},_removeTile:function(R){this._detachTileEvents(R);
this._removeDraggableWidget(R);
var Q=R.get_element();
R.dispose();
a(Q).remove();
},_bindToClientDataSource:function(Q){if(Q&&(Q instanceof c.RadClientDataSource)){Q.remove_change(this._clientDataSourceChangeHanlderDelgate);
Q.add_change(this._clientDataSourceChangeHanlderDelgate);
Q.fetch();
}},_clientDataSourceChangeHanlder:function(S){var Q=this.get_clientDataSource();
var R=Q.view();
this.set_dataSource(R);
this._dataBind();
},_dataBind:function(){var U=this,Q=U.get_dataSource(),T=!U.get_appendClientDataBoundItems();
if(Q&&typeof(Q.length)!="undefined"){if(T){U._removeAllTiles();
}for(var R=0,S=Q.length;
R<S;
R++){this._createTile(Q[R]);
}this._resetAllTilesArray();
this.repaint();
this._riseTileListDataBoundEvent();
}},_riseTileListDataBoundEvent:function(){var Q=Sys.EventArgs();
this.raiseEvent(M,Q);
},_createTile:function(R){var V=this,S=V.get_tileDataParser(),X=S.get_tileData(R),W=null,T;
T=V._riseTileCreatingEvent(R,X);
X=T.get_tileData();
if(T.get_cancel()){return null;
}var Z=c.TileRendererFactory.createTileRenderer(X.tileType),Y=Z.renderTile(X),U=V._getGroupIndexByName(X.groupName),Q=a(Y).appendTo(V._$scrollWrapper[0]);
V._deleteUnnecessaryProperties(X);
V._ensureTileElementId(Q);
X._postBackReference="__doPostBack('"+Q.attr("id")+"','arguments')";
W=$create(Telerik.Web.UI[X.tileType],X,null,null,Q.get(0));
V._setTileSkin(Q);
W.set_enableSelection(V.isSelectionOn());
W.set_groupIndex(U);
V._riseTileDataBoundEvent(W,R);
V._appendTileInTileList(W);
return W;
},_setTileSkin:function(Q){var R=this.get_skin();
if(R&&R!="Default"){Q.removeClass("RadTile_Default").addClass("RadTile_"+R);
}},_deleteUnnecessaryProperties:function(Q){if(!Q){return;
}delete Q.peekTemplate;
delete Q.contentTemplate;
delete Q.groupName;
},_getGroupIndexByName:function(S){var T=this,R=T.get_groups(),Q=0;
S=(typeof(S)=="undefined")?"":S.toString();
if(R.get_count()>0){if(S==""){Q=R.get_count()-1;
}else{Q=R.getItemIndexByName(S);
if(Q==-1){Q=R.get_count();
T._appendTileGroup(S);
}}}else{T._appendTileGroup(S);
}return Q;
},_ensureTileElementId:function(Q){if(Q&&!Q.id){var S=this.get_id()+"_ctl",R=1;
while($get(S+R)!=null){R++;
}Q.attr("id",S+R);
}},_riseTileCreatingEvent:function(Q,S){var R=new c.TileListDataCancelEventArgs(Q,S);
this.raiseEvent(z,R);
return R;
},_riseTileDataBoundEvent:function(S,Q){var R=new c.TileListDataEventArgs(S,Q);
this.raiseEvent(A,R);
},get_tileDataParser:function(){var Q=this;
if(!this._tileDataParser){var R=new c.TileDataParser(this.get_dataBindings());
R.observe({templateDataBound:function(S){Q.raiseEvent(x,S);
},peekTemplateDataBound:function(S){Q.raiseEvent(y,S);
}});
this._tileDataParser=R;
}return this._tileDataParser;
},get_clientDataSourceID:function(){return this._clientDataSourceID;
},set_clientDataSourceID:function(Q){this._clientDataSource=null;
this._dataSource=null;
this._clientDataSourceID=Q;
},get_clientDataSource:function(){var Q=this.get_clientDataSourceID();
if(Q){var R=$find(Q);
if(R&&R instanceof c.RadClientDataSource){return R;
}}return this._clientDataSource;
},set_clientDataSource:function(Q){this.set_clientDataSourceID("");
this._clientDataSource=Q;
},saveClientState:function(){var R=this._hasTitles()?',"tileGroupTitles":'+Sys.Serialization.JavaScriptSerializer.serialize(this._getTileGroupTitles()):"";
var Q=this._getGroupNamesClientState();
return'{"tileGroupIndices":'+this._tileGroupsJson+R+Q+"}";
},_getGroupNamesClientState:function(){var Q=[];
var R=false;
this.get_groups().forEach(function(S){var T=S.get_name();
if(!R&&T){R=true;
}Q.push(T);
});
return R?',"tileGroupNames":'+Sys.Serialization.JavaScriptSerializer.serialize(Q):"";
},_getTileGroupTitles:function(){var Q=[];
this.get_groups().forEach(function(R){var S=a("."+p,R.get_element()).html();
if(S=="&nbsp;"||S==" "){S="";
}Q.push(S);
});
return Q;
},get_width:function(){return this._width;
},set_width:function(R){var Q=this;
if(typeof R=="string"&&R.indexOf("%")>0){Q._width=R;
}else{var S=parseInt(R,10);
Q._width=!isNaN(S)?S+"px":"";
}Q._setElementWidth(Q._width);
},_setElementWidth:function(Q){this._$element.css("width",Q);
},get_height:function(){return this._height;
},set_height:function(S){var R=this,Q=parseInt(S,10);
R._height=!isNaN(Q)?Q+"px":"";
R._setElementHeight(R._height);
},get_scrollingMode:function(){return this._scrollingMode;
},set_scrollingMode:function(S){var R=this,Q=R.get_element();
R._scrollingMode=S;
if(S==d.TileListScrollingMode.None){Q.scrollLeft=0;
}R._initializeMouseScroll();
R._initializeTouchScrollExtender();
R._initializeTouchScrolling();
R._intializeOverflowX();
},get_selectionMode:function(){return this._selectionMode;
},set_selectionMode:function(V){var U=this,R;
U._selectionMode=V;
R=U.isSelectionOn();
if(!R){U.clearSelection();
}a.each(U.get_allTiles(),function(W,X){X.set_enableSelection(R);
U._initializeTileDragAndDrop(X);
});
if(U._selectionMode==d.TileListSelectionMode.Single){var T=U.get_selectedTiles();
var S=true;
for(var Q=T.length-1;
Q>=0;
Q--){T[Q].set_selected(S);
S=false;
}}},isSelectionOn:function(){return this.get_selectionMode()!=d.TileListSelectionMode.None;
},clearSelection:function(R){var Q=this.get_allTiles(),U;
for(var S=0,T=Q.length;
S<T;
S++){U=Q[S];
if(U.get_selected()){if(S!=R){U.set_selected(false);
}}}},_intializeOverflowX:function(){var S=this,R=S.get_scrollingMode(),Q=d.TileListScrollingMode;
if(R==Q.None||(R==Q.Accelerated&&!$telerik.isTouchDevice)){S._$element.addClass("rtlistScrollHidden");
}else{S._$element.removeClass("rtlistScrollHidden");
}},_setElementHeight:function(Q){this._$element.css("height",Q);
},get_groups:function(){var Q=this;
if(!Q._groups){Q._groups=new d.TileGroupCollection();
}return Q._groups;
},getGroup:function(Q){return this.get_groups().getItem(Q);
},getGroupIndex:function(Q){return this.get_groups().indexOf(Q);
},set_groupTitle:function(R,T){var S=this;
var Q=R&&R.get_element();
var U=S.get_groupTitles();
if(Q){U[S.getGroupIndex(R)]=T;
S._resetGroupTitles();
S._resetHeaderElements();
a(q,Q).html(T||"&nbsp;");
if(!S._groupTitlesExist){S._groupTitlesExist=true;
if(!S._initilaHeight){S.get_element().style.height="";
}S.repaint();
}}S.updateClientState();
},clearGroupTitles:function(){var Q=this;
Q.set_groupTitles([]);
Q._groupTitlesExist=false;
Q._$element.find("."+i).remove();
if(!Q._initilaHeight){Q.get_element().style.height="";
}Q.repaint();
},_resetGroupTitles:function(){var T=[];
var Q=this.get_groupTitles();
for(var R=0;
R<this.get_groups().get_count();
R++){var S=Q[R]||"";
if(S=="&nbsp;"||S==" "){S="";
}T[R]=S;
}this.set_groupTitles(T);
},_resetHeaderElements:function(){this.get_groups().forEach(function(R){var Q=R.get_element();
if(a(k,Q).length==0){a(Q).prepend(j);
}});
},get_allTiles:function(){return this._allTiles;
},set_allTiles:function(Q){this._allTiles=Q;
},get_tileByName:function(T){if(T){var Q=this.get_allTiles();
for(var R=0,S=Q.length;
R<S;
R++){var U=Q[R];
if(T==U.get_name()){return U;
}}}return null;
},get_selectedTiles:function(){return a.grep(this.get_allTiles(),function(Q){return Q.get_selected()===true;
});
},get_allTilesIndex:function(S){var T=this.get_allTiles();
for(var Q=0,R=T.length;
Q<R;
Q++){if(S===T[Q]){return Q;
}}return -1;
},get_tileByAllTilesIndex:function(Q){var R=this.get_allTiles();
return(Q>=0&&Q<R.length)?R[Q]:null;
},get_dataBindings:function(){return this._dataBindings;
},set_dataBindings:function(Q){this._disposeTileDataParser();
this._dataBindings=Q;
},_disposeTileDataParser:function(){if(this._tileDataParser){this._tileDataParser.disposeEvents();
this._tileDataParser=null;
}},_isTouchDevice:function(){return"createTouch" in document||$telerik.isTouchDevice||$telerik.isMobileIE10;
}};
a.registerControlProperties(c.RadTileList,{autoPostBack:false,tileRows:0,enableDragAndDrop:false,skin:"Default",groupTitles:[],dataSource:null,appendClientDataBoundItems:false});
var O="load",N="init",I="tileSelecting",H="tileSelected",w="tileClicking",v="tileClicked",B="tileDragStart",C="tileDragging",E="tileDropping",D="tileDropped",z="tileCreating",A="tileDataBound",M="tileListDataBound",x="clientTileContentTemplateDataBound",y="clientTilePeekTemplateDataBound";
a.registerControlEvents(c.RadTileList,[O,N,I,H,w,v,B,C,E,D,z,A,x,y,M]);
c.RadTileList.registerClass("Telerik.Web.UI.RadTileList",c.RadWebControl);
var e=function(R,Q){c[R]=function(){var S=Array.prototype.slice.call(arguments);
c[R].initializeBase(this,S);
};
c[R].registerClass("Telerik.Web.UI."+R,Q);
};
c.TileListCancelEventArgs=function(Q,R){c.TileListCancelEventArgs.initializeBase(this);
this._tile=Q;
this._value=R;
};
c.TileListCancelEventArgs.prototype={get_tile:function(){return this._tile;
},get_value:function(){return this._value;
},set_value:function(Q){this._value=Q;
}};
c.TileListCancelEventArgs.registerClass("Telerik.Web.UI.TileListCancelEventArgs",Sys.CancelEventArgs);
e("RadTileListCancelEventArgs",Telerik.Web.UI.TileListCancelEventArgs);
c.TileListDataEventArgs=function(R,Q){this._tile=R;
this._dataItem=Q;
};
c.TileListDataEventArgs.prototype={get_tile:function(){return this._tile;
},get_dataItem:function(){return this._dataItem;
}};
c.TileListDataEventArgs.registerClass("Telerik.Web.UI.TileListDataEventArgs",Sys.EventArgs);
e("RadTileListDataEventArgs",Telerik.Web.UI.TileListDataEventArgs);
c.TileListDataCancelEventArgs=function(Q,R){c.TileListDataCancelEventArgs.initializeBase(this);
this._dataItem=Q;
this._tileData=R;
};
c.TileListDataCancelEventArgs.prototype={get_tileData:function(){return this._tileData;
},set_tileData:function(Q){this._tileData=Q;
},get_dataItem:function(){return this._dataItem;
}};
c.TileListDataCancelEventArgs.registerClass("Telerik.Web.UI.TileListDataCancelEventArgs",Sys.CancelEventArgs);
e("RadTileListDataCancelEventArgs",Telerik.Web.UI.TileListDataCancelEventArgs);
c.TileListEventArgs=function(S,Q,R){c.TileListEventArgs.initializeBase(this);
this._newValue=Q;
this._oldValue=R;
this._tile=S;
};
c.TileListEventArgs.prototype={get_oldValue:function(){return this._oldValue;
},get_newValue:function(){return this._newValue;
},get_tile:function(){return this._tile;
}};
c.TileListEventArgs.registerClass("Telerik.Web.UI.TileListEventArgs",Sys.CancelEventArgs);
e("RadTileListEventArgs",Telerik.Web.UI.TileListEventArgs);
})($telerik.$);
(function(f){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI,a=$telerik.$,c=Telerik.Web.UI.TileList,d="peekTemplateDataBound",e="templateDataBound";
b.TileDataParser=function(g){this._dataBindings=g||{};
b.TileDataParser.makeEventHandler(this);
this._riseTemplateDataBoundEventDelegate=Function.createDelegate(this,this._riseTemplateDataBoundEvent);
this._risePeekTemplateDataBoundEventDelegate=Function.createDelegate(this,this._risePeekTemplateDataBoundEvent);
};
b.TileDataParser.prototype={get_tileData:function(g){this._result={badgeData:{},peekTemplateSettingsData:{},tileType:"RadTextTile",titleData:{}};
this._applyCommonBinding(g);
return this._result;
},_applyCommonBinding:function(g){this.set_commonTileBinding(g);
this.set_textTileBinding(g);
this.set_imageTileBinding(g);
this.set_imageAndTextTileBinding(g);
this.set_iconTileBinding(g);
this.set_contentTemplateTileBinding(g);
this.set_liveTileBinding(g);
},set_commonTileBinding:function(h){this.set_tileType(h);
this.set_shape();
this.set_target();
this.set_peekTemplate(h);
var g=this._dataBindings.commonTileBinding;
this._applyDataField(g,"Shape",h);
this._applyDataField(g,"NavigateUrl",h);
this._applyDataField(g,"Target",h);
this._applyDataField(g,"Name",h);
this._applyDataField(g,"GroupName",h);
this.set_title(h);
this.set_badge(h);
},set_textTileBinding:function(g){this._applyDataField(this._dataBindings.textTileBinding,"Text",g,"RadTextTile");
},set_imageTileBinding:function(g){this._applyDataField(this._dataBindings.imageTileBinding,"ImageUrl",g,"RadImageTile");
},set_imageAndTextTileBinding:function(g){this._applyDataField(this._dataBindings.imageAndTextTileBinding,"Text",g,"RadImageAndTextTile");
this._applyDataField(this._dataBindings.imageAndTextTileBinding,"ImageUrl",g,"RadImageAndTextTile");
},set_iconTileBinding:function(g){this._applyDataField(this._dataBindings.iconTileBinding,"ImageUrl",g,"RadIconTile");
},set_contentTemplateTileBinding:function(j){var g="",h=this._dataBindings.contentTemplateTileBinding;
if(this._result.tileType=="RadContentTemplateTile"&&h){g=h.clientContentTemplate;
var i=h.dataClientContentTemplateField;
if(j&&i){g=j[i];
}}if(g){this._result.contentTemplate=this._renderTemplate(j,g,this._riseTemplateDataBoundEventDelegate);
}},set_liveTileBinding:function(i){if(this._result.tileType=="RadLiveTile"){var j=this._dataBindings.liveTileBinding,g="";
if(j){g=j.clientTemplate;
var h=j.dataClientTemplateField;
if(i&&h){g=i[h];
}if(g){this._result.clientTemplate=g;
}}this._applyDataField(j,"UpdateInterval",i,"RadLiveTile");
}},set_tileType:function(h){var g=this._dataBindings.commonTileBinding,j="";
if(g){j=g.tileType;
var i=g.dataTileTypeField;
if(i&&h){j=h[i];
}if(j){j=!isNaN(parseInt(j,10))?this._getTileTypeString(j):j;
this._result.tileType=j;
}}},_getTileTypeString:function(h){if(!isNaN(h)){for(var g in c.TileType){if(h==c.TileType[g]){return g;
}}}return"";
},set_shape:function(){var g=this._dataBindings.commonTileBinding;
if(g&&g.shape==b.TileShape.Wide){this._result.shape=b.TileShape.Wide;
}},set_target:function(){var g=this._dataBindings.commonTileBinding;
if(g&&g.target){this._result.target=g.target;
}},set_peekTemplate:function(h){var i=this._dataBindings.clientTilePeekTemplate,g=this._dataBindings.dataClientTilePeekTemplateField;
if(g&&h){i=h[g];
}if(i){this._result.peekTemplate=this._renderTemplate(h,i,this._risePeekTemplateDataBoundEventDelegate);
}},_renderTemplate:function(g,k,j){var l=this._getTemplateFunction(k),i=this._dataBindClientTemplate(l,g);
if(j){var h=j(g,l,i);
i=h.get_html();
}return i;
},_getTemplateFunction:function(i){if(!i){return null;
}var j;
if(!this._templateCache){this._templateCache={};
}var g=this._templateCache[i];
if(g){return g;
}try{j=b.Template.compile(i);
}catch(h){throw Error.invalidOperation(String.format("Error creating template: {0}",h.message));
}this._templateCache[i]=j;
return j;
},_dataBindClientTemplate:function(i,g){if(i){try{return i(g||{});
}catch(h){throw Error.invalidOperation(String.format("Error rendering template: {0}",h.message));
}}return"";
},_riseTemplateDataBoundEvent:function(g,j,i){var h=new b.RadTemplateBoundEventArgs(g,j,i);
this.trigger(e,h);
return h;
},_risePeekTemplateDataBoundEvent:function(g,j,i){var h=new b.RadTemplateBoundEventArgs(g,j,i);
this.trigger(d,h);
return h;
},_applyDataField:function(g,h,i,k){if(k&&k!=this._result.tileType){return;
}if(g&&g["data"+h+"Field"]){var j=g["data"+h+"Field"];
if(i[j]){this._result[h.charAt(0).toLowerCase()+h.slice(1)]=i[j];
}}},set_title:function(h){var g=this._dataBindings.commonTileBinding;
if(g&&g.dataTitleTextField){var j=h[g.dataTitleTextField];
if(j){this._setTitleProperty("text",j);
}}if(g&&g.dataTitleImageUrlField){var i=h[g.dataTitleImageUrlField];
if(i){this._setTitleProperty("imageUrl",i);
}}},_setTitleProperty:function(g,h){if(g&&h){if(!this._result.titleData){this._result.titleData={};
}this._result.titleData[g]=h;
}},set_badge:function(h){var g=this._dataBindings.commonTileBinding;
if(g&&g.dataBadgeValueField){var k=h[g.dataBadgeValueField];
if(!isNaN(k)){this._setBadgeProperty("value",k);
}}if(g&&g.dataBadgeImageUrlField){var i=h[g.dataBadgeImageUrlField];
if(i){this._setBadgeProperty("imageUrl",i);
}}if(g&&g.dataBadgePredefinedTypeField){var j=h[g.dataBadgePredefinedTypeField];
if(j){this._setBadgeProperty("predefinedType",j);
}}},_setBadgeProperty:function(g,h){if(g){if(!this._result.badgeData){this._result.badgeData={};
}this._result.badgeData[g]=h;
}}};
b.TileDataParser.registerClass("Telerik.Web.UI.TileDataParser");
b.TileDataParser.makeEventHandler=function(g){(function(){var i={};
a.extend(g,{observe:function(k,j){a.each(k,function(l,m){h(l,m,j);
});
},trigger:function(){var j=Array.prototype.slice.call(arguments),k=j.shift(),l=i[k];
if(a.type(l)==="array"){for(var m=0;
m<l.length;
m++){l[m].func.apply(l[m].context,j);
}}},disposeEvents:function(){for(var j in i){delete i[j];
}}});
function h(k,l,j){var m=i[k]||[];
m.push({func:l,context:j});
i[k]=m;
}})();
};
})();
(function(){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.TileFactory={createTile:function(b,c){return typeof a[b.tileType]=="function"?$create(a[b.tileType],b,null,null,c):$create(a.RadBaseTile,b,null,null,c);
}};
})();
(function(){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI,b="RadTile",c="rtileSquare",e="rtileWide",d="rtileContent";
a.TileRenderer=function(){};
a.TileRenderer.prototype={renderTile:function(f){var g="";
g+=this.renderBeginTag(f);
g+=this.renderPeekTemplate(f);
g+=this.renderContentWrapper(f);
g+=this.renderContent(f);
g+=this.renderContentWrapperEndTag(f);
g+=this.renderTitle(f);
g+=this.renderBadge(f);
g+=this.renderEndTag(f);
return g;
},renderBeginTag:function(f){var g="";
if(f&&f.id){g=' id="'+f.id+'"';
}return"<div"+this.get_id(f)+' class="'+b+" "+this.get_skinClass(f)+" "+this.get_shapeClass(f)+" "+this.get_tileTypeClass()+'">';
},renderPeekTemplate:function(f){if(f&&f.peekTemplate){var g=f.id?'id="'+f.id+'_P" ':"";
return"<div "+g+'class="rtilePeekContent" style="display:none;position:absolute;z-index:1;">'+f.peekTemplate+"</div>";
}return"";
},get_id:function(f){if(f&&f.id){return' id="'+f.id+'"';
}return"";
},get_skinClass:function(f){if(f){var g=f.skin;
if(g===""){return"";
}else{if(g){return b+"_"+f.skin;
}}}return b+"_Default";
},get_shapeClass:function(f){if(f&&f.shape==a.TileShape.Wide){return e;
}return c;
},get_tileTypeClass:function(){return"RadTextTile";
},renderContentWrapper:function(){return'<div class="'+d+'">';
},renderContent:function(f){return"";
},renderTitle:function(f){if(f&&f.titleData){var g=f.titleData;
if(g.imageUrl){return'<img alt="" src="'+g.imageUrl+'" class="rtileTitle">';
}if(g.text){return'<h6 class="rtileTitle">'+g.text+"</h6>";
}}return"";
},renderBadge:function(h){if(h&&h.badgeData){var f=h.badgeData,i=f.value;
if(!isNaN(i)){return'<div class="rtileBadge">'+i+"</div>";
}if(f.predefinedType){var g;
for(g in a.TileBadgeType){if(f.predefinedType==a.TileBadgeType[g]){return'<div class="rtileBadge rtileBadgeIcon rtile'+g+'Badge"> </div>';
}}}if(f.imageUrl){return'<img alt="" src="'+f.imageUrl+'" class="rtileBadge">';
}}return"";
},renderContentWrapperEndTag:function(){return"</div>";
},renderEndTag:function(f){return"</div>";
}};
a.TileRenderer.registerClass("Telerik.Web.UI.TileRenderer");
})();
(function(c){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI,b="rtileContent";
a.ContentTemplateTileRenderer=function(){a.ContentTemplateTileRenderer.initializeBase(this);
};
a.ContentTemplateTileRenderer.prototype={renderContentWrapper:function(d){var e=(d&&d.id)?'id="'+d.id+'_C" ':"";
return"<div "+e+'class="'+b+'">';
},renderContent:function(d){if(d&&d.contentTemplate){return d.contentTemplate;
}return" ";
},get_tileTypeClass:function(){return"RadContentTemplateTile";
}};
a.ContentTemplateTileRenderer.registerClass("Telerik.Web.UI.ContentTemplateTileRenderer",a.TileRenderer);
})();
(function(c){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI,b="rtileTopContent";
a.IconTileRenderer=function(){a.IconTileRenderer.initializeBase(this);
};
a.IconTileRenderer.prototype={renderContent:function(d){if(d&&d.imageUrl){return'<div class="'+b+'"><img alt="" src="'+d.imageUrl+'" class="rtileIconImage" /></div>';
}return"";
},get_tileTypeClass:function(){return"RadIconTile";
}};
a.IconTileRenderer.registerClass("Telerik.Web.UI.IconTileRenderer",a.TileRenderer);
})();
(function(b){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.ImageAndTextTileRenderer=function(){a.ImageAndTextTileRenderer.initializeBase(this);
};
a.ImageAndTextTileRenderer.prototype={renderContent:function(c){var d=(c&&c.imageUrl)?c.imageUrl:"";
var e=(c&&c.text)?c.text:" ";
return'<div class="rtileTopContent"><img alt="" src="'+d+'" class="rtileContentImage"></div><div class="rtileBottomContent">'+e+"</div>";
},get_tileTypeClass:function(){return"RadImageAndTextTile";
}};
a.ImageAndTextTileRenderer.registerClass("Telerik.Web.UI.ImageAndTextTileRenderer",a.TileRenderer);
})();
(function(b){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.ImageTileRenderer=function(){a.ImageTileRenderer.initializeBase(this);
};
a.ImageTileRenderer.prototype={renderContent:function(c){if(c&&c.imageUrl){return'<img alt="" src="'+c.imageUrl+'" class="rtileIconImage" />';
}return"";
},get_tileTypeClass:function(){return"RadImageTile";
}};
a.ImageTileRenderer.registerClass("Telerik.Web.UI.ImageTileRenderer",a.TileRenderer);
})();
(function(b){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.LiveTileRenderer=function(){a.LiveTileRenderer.initializeBase(this);
};
a.LiveTileRenderer.prototype={renderContent:function(c){return'<div class="rtileClientTemplateContainer"> </div>';
},get_tileTypeClass:function(){return"RadLiveTile";
}};
a.LiveTileRenderer.registerClass("Telerik.Web.UI.LiveTileRenderer",a.TileRenderer);
})();
(function(c){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI,b="rtileTopContent";
a.TextTileRenderer=function(){a.TextTileRenderer.initializeBase(this);
};
a.TextTileRenderer.prototype={renderContent:function(d){var e=(d&&d.text)?d.text:"";
return'<div class="'+b+'">'+e+"</div>";
}};
a.TextTileRenderer.registerClass("Telerik.Web.UI.TextTileRenderer",a.TileRenderer);
})();
(function(b){Type.registerNamespace("Telerik.Web.UI");
var a=Telerik.Web.UI;
a.TileRendererFactory={createTileRenderer:function(c){switch(c){case"RadIconTile":return new a.IconTileRenderer();
case"RadImageTile":return new a.ImageTileRenderer();
case"RadImageAndTextTile":return new a.ImageAndTextTileRenderer();
case"RadContentTemplateTile":return new a.ContentTemplateTileRenderer();
case"RadLiveTile":return new a.LiveTileRenderer();
default:return new a.TextTileRenderer();
}}};
})();
