(function(b,a){a("util/main",["kendo.core"],b);
}(function(){(function(){var q=Math,n=window.kendo,f=n.deepExtend;
var i=q.PI/180,r=Number.MAX_VALUE,u=-Number.MAX_VALUE,N="undefined";
function g(P){return typeof P!==N;
}function G(R,Q){var P=x(Q);
return q.round(R*P)/P;
}function x(P){if(P){return q.pow(10,P);
}else{return 1;
}}function p(R,Q,P){return q.max(q.min(R,P),Q);
}function y(P){return P*i;
}function h(P){return P/i;
}function l(P){return typeof P==="number"&&!isNaN(P);
}function O(Q,P){return g(Q)?Q:P;
}function K(P){return P*P;
}function w(Q){var R=[];
for(var P in Q){R.push(P+Q[P]);
}return R.sort().join("");
}function j(R){var P=2166136261;
for(var Q=0;
Q<R.length;
++Q){P+=(P<<1)+(P<<4)+(P<<7)+(P<<8)+(P<<24);
P^=R.charCodeAt(Q);
}return P>>>0;
}function k(P){return j(w(P));
}var v=Date.now;
if(!v){v=function(){return new Date().getTime();
};
}function c(P){var R=P.length,Q,T=r,S=u;
for(Q=0;
Q<R;
Q++){S=q.max(S,P[Q]);
T=q.min(T,P[Q]);
}return{min:T,max:S};
}function e(P){return c(P).min;
}function d(P){return c(P).max;
}function J(P){return H(P).min;
}function I(P){return H(P).max;
}function H(P){var T=r,S=u;
for(var Q=0,R=P.length;
Q<R;
Q++){var U=P[Q];
if(U!==null&&isFinite(U)){T=q.min(T,U);
S=q.max(S,U);
}}return{min:T===r?undefined:T,max:S===u?undefined:S};
}function o(P){if(P){return P[P.length-1];
}}function a(P,Q){P.push.apply(P,Q);
return P;
}function E(P){return n.template(P,{useWithBlock:false,paramName:"d"});
}function A(P,Q){return g(Q)&&Q!==null?" "+P+"='"+Q+"' ":"";
}function z(P){var R="";
for(var Q=0;
Q<P.length;
Q++){R+=A(P[Q][0],P[Q][1]);
}return R;
}function D(P){var R="";
for(var Q=0;
Q<P.length;
Q++){var S=P[Q][1];
if(g(S)){R+=P[Q][0]+":"+S+";";
}}if(R!==""){return R;
}}function C(P){if(typeof P!=="string"){P+="px";
}return P;
}function B(R){var S=[];
if(R){var Q=n.toHyphens(R).split("-");
for(var P=0;
P<Q.length;
P++){S.push("k-pos-"+Q[P]);
}}return S.join(" ");
}function m(P){return P===""||P===null||P==="none"||P==="transparent"||!g(P);
}function b(Q){var P={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var S=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var R="";
while(Q>0){if(Q<S[0]){S.shift();
}else{R+=P[S[0]];
Q-=S[0];
}}return R;
}function F(S){S=S.toLowerCase();
var P={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var U=0,R=0;
for(var Q=0;
Q<S.length;
++Q){var T=P[S.charAt(Q)];
if(!T){return null;
}U+=T;
if(T>R){U-=2*R;
}R=T;
}return U;
}function s(Q){var P=Object.create(null);
return function(){var S="";
for(var R=arguments.length;
--R>=0;
){S+=":"+arguments[R];
}if(S in P){return P[S];
}return Q.apply(this,arguments);
};
}function L(T){var S=[],P=0,R=T.length,U,Q;
while(P<R){U=T.charCodeAt(P++);
if(U>=55296&&U<=56319&&P<R){Q=T.charCodeAt(P++);
if((Q&64512)==56320){S.push(((U&1023)<<10)+(Q&1023)+65536);
}else{S.push(U);
P--;
}}else{S.push(U);
}}return S;
}function M(P){return P.map(function(R){var Q="";
if(R>65535){R-=65536;
Q+=String.fromCharCode(R>>>10&1023|55296);
R=56320|R&1023;
}Q+=String.fromCharCode(R);
return Q;
}).join("");
}function t(P,Q){if(P.length<2){return P.slice();
}function R(T,V){var Y=[],U=0,W=0,X=0;
while(U<T.length&&W<V.length){if(Q(T[U],V[W])<=0){Y[X++]=T[U++];
}else{Y[X++]=V[W++];
}}if(U<T.length){Y.push.apply(Y,T.slice(U));
}if(W<V.length){Y.push.apply(Y,V.slice(W));
}return Y;
}return function S(T){if(T.length<=1){return T;
}var V=Math.floor(T.length/2);
var U=T.slice(0,V);
var W=T.slice(V);
U=S(U);
W=S(W);
return R(U,W);
}(P);
}f(n,{util:{MAX_NUM:r,MIN_NUM:u,append:a,arrayLimits:c,arrayMin:e,arrayMax:d,defined:g,deg:h,hashKey:j,hashObject:k,isNumber:l,isTransparent:m,last:o,limitValue:p,now:v,objectKey:w,round:G,rad:y,renderAttr:A,renderAllAttr:z,renderPos:B,renderSize:C,renderStyle:D,renderTemplate:E,sparseArrayLimits:H,sparseArrayMin:J,sparseArrayMax:I,sqr:K,valueOrDefault:O,romanToArabic:F,arabicToRoman:b,memoize:s,ucs2encode:M,ucs2decode:L,mergeSort:t}});
n.drawing.util=n.util;
n.dataviz.util=n.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/text-metrics",["kendo.core","util/main"],b);
}(function(){(function(a){var e=document,f=window.kendo,b=f.Class,k=f.util,d=k.defined;
var h=b.extend({init:function(m){this._size=m;
this._length=0;
this._map={};
},put:function(n,q){var o=this,p=o._map,m={key:n,value:q};
p[n]=m;
if(!o._head){o._head=o._tail=m;
}else{o._tail.newer=m;
m.older=o._tail;
o._tail=m;
}if(o._length>=o._size){p[o._head.key]=null;
o._head=o._head.newer;
o._head.older=null;
}else{o._length++;
}},get:function(n){var o=this,m=o._map[n];
if(m){if(m===o._head&&m!==o._tail){o._head=m.newer;
o._head.older=null;
}if(m!==o._tail){if(m.older){m.older.newer=m.newer;
m.newer.older=m.older;
}m.older=o._tail;
m.newer=null;
o._tail.newer=m;
o._tail=m;
}return m.value;
}}});
var c=a("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function l(){return{width:0,height:0,baseline:0};
}var j=b.extend({init:function(m){this._cache=new h(1000);
this._initOptions(m);
},options:{baselineMarkerSize:1},measure:function(v,t,n){if(!v){return l();
}var u=k.objectKey(t),p=k.hashKey(v+u),o=this._cache.get(p);
if(o){return o;
}var s=l();
var r=n?n:c;
var m=this._baselineMarker().cloneNode(false);
for(var q in t){var w=t[q];
if(d(w)){r.style[q]=w;
}}a(r).text(v);
r.appendChild(m);
e.body.appendChild(r);
if((v+"").length){s.width=r.offsetWidth-this.options.baselineMarkerSize;
s.height=r.offsetHeight;
s.baseline=m.offsetTop+this.options.baselineMarkerSize;
}if(s.width>0&&s.height>0){this._cache.put(p,s);
}r.parentNode.removeChild(r);
return s;
},_baselineMarker:function(){return a("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
j.current=new j();
function i(o,n,m){return j.current.measure(o,n,m);
}function g(o,m){var p=[];
if(o.length>0&&document.fonts){try{p=o.map(function(q){return document.fonts.load(q);
});
}catch(n){f.logToConsole(n);
}Promise.all(p).then(m,m);
}else{m();
}}f.util.TextMetrics=j;
f.util.LRUCache=h;
f.util.loadFonts=g;
f.util.measureText=i;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("util/base64",["util/main"],b);
}(function(){(function(){var e=window.kendo,a=e.deepExtend,d=String.fromCharCode;
var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function b(p){var q="";
var g,h,j,k,l,m,n;
var o=0;
p=c(p);
while(o<p.length){g=p.charCodeAt(o++);
h=p.charCodeAt(o++);
j=p.charCodeAt(o++);
k=g>>2;
l=(g&3)<<4|h>>4;
m=(h&15)<<2|j>>6;
n=j&63;
if(isNaN(h)){m=n=64;
}else{if(isNaN(j)){n=64;
}}q=q+f.charAt(k)+f.charAt(l)+f.charAt(m)+f.charAt(n);
}return q;
}function c(j){var k="";
for(var h=0;
h<j.length;
h++){var g=j.charCodeAt(h);
if(g<128){k+=d(g);
}else{if(g<2048){k+=d(192|g>>>6);
k+=d(128|g&63);
}else{if(g<65536){k+=d(224|g>>>12);
k+=d(128|g>>>6&63);
k+=d(128|g&63);
}}}}return k;
}a(e.util,{encodeBase64:b,encodeUTF8:c});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("mixins/observers",["kendo.core"],b);
}(function(){(function(a){var e=Math,d=window.kendo,b=d.deepExtend,c=a.inArray;
var f={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(g){if(!this._observers){this._observers=[g];
}else{this._observers.push(g);
}return this;
},removeObserver:function(g){var i=this.observers();
var h=c(g,i);
if(h!=-1){i.splice(h,1);
}return this;
},trigger:function(i,g){var k=this._observers;
var j;
var h;
if(k&&!this._suspended){for(h=0;
h<k.length;
h++){j=k[h];
if(j[i]){j[i](g);
}}}return this;
},optionsChange:function(g){g=g||{};
g.element=this;
this.trigger("optionsChange",g);
},geometryChange:function(){this.trigger("geometryChange",{element:this});
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=e.max((this._suspended||0)-1,0);
return this;
},_observerField:function(g,h){if(this[g]){this[g].removeObserver(this);
}this[g]=h;
h.addObserver(this);
}};
b(d,{mixins:{ObserversMixin:f}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
(function(b,a){a("kendo.dataviz.chart.funnel",["kendo.dataviz.chart","kendo.drawing"],b);
}(function(){var a={id:"dataviz.chart.funnel",name:"Funnel Chart",category:"dataviz",depends:["dataviz.chart"],hidden:true};
(function(b,F){var v=window.kendo,l=v.deepExtend,o=b.extend,u=v.isFunction,D=v.template,G=v.util,c=G.append,m=v.drawing,t=v.geometry,k=v.dataviz,i=v.drawing.Color,h=k.ChartElement,x=k.PieChartMixin,y=k.PlotAreaBase,z=k.PlotAreaFactory,A=k.Point2D,f=k.Box2D,B=k.SeriesBinder,E=k.TextBox,d=k.autoFormat,n=k.evalOptions,w=G.limitValue,C=k.seriesTotal;
var g="category",j="color",p="funnel",H="value",e="black",I="white";
var r=y.extend({render:function(){var J=this,K=J.series;
J.createFunnelChart(K);
},createFunnelChart:function(M){var L=this,J=M[0],K=new q(L,{series:M,legend:L.options.legend,neckRatio:J.neckRatio,dynamicHeight:J.dynamicHeight,dynamicSlope:J.dynamicSlope,segmentSpacing:J.segmentSpacing,highlight:J.highlight});
L.appendChart(K);
},appendChart:function(J,K){y.fn.appendChart.call(this,J,K);
c(this.options.legend.items,J.legendItems);
}});
var q=h.extend({init:function(L,K){var J=this;
h.fn.init.call(J,K);
J.plotArea=L;
J.points=[];
J.labels=[];
J.legendItems=[];
J.render();
},options:{neckRatio:0.3,width:300,dynamicSlope:false,dynamicHeight:true,segmentSpacing:0,labels:{visible:false,align:"center",position:"center"}},formatPointValue:function(K,J){return d(J,K.value);
},render:function(){var J=this,Q=J.options,K=J.plotArea.options.seriesColors||[],L=K.length,T=Q.series[0],R,N,M=T.data;
if(!M){return;
}var U=C(T),V,O;
for(O=0;
O<M.length;
O++){R=B.current.bindPoint(T,O);
V=R.valueFields.value;
if(V===null||V===F){continue;
}N=R.fields;
if(!u(T.color)){T.color=N.color||K[O%L];
}N=l({index:O,owner:J,series:T,category:N.category,dataItem:M[O],percentage:Math.abs(V)/U,visibleInLegend:N.visibleInLegend,visible:N.visible},N);
var S=J.createSegment(V,N);
var P=J.createLabel(V,N);
if(S&&P){S.append(P);
}}},evalSegmentOptions:function(K,M,J){var L=J.series;
n(K,{value:M,series:L,dataItem:J.dataItem,index:J.index},{defaults:L._defaults,excluded:["data","toggle","visual"]});
},createSegment:function(N,K){var J=this,L;
var M=l({},K.series);
J.evalSegmentOptions(M,N,K);
J.createLegendItem(N,M,K);
if(K.visible!==false){L=new s(N,M,K);
o(L,K);
J.append(L);
J.points.push(L);
return L;
}},createLabel:function(S,M){var K=this,P=M.series,L=M.dataItem,N=l({},K.options.labels,P.labels),Q=S,R;
if(N.visible){if(N.template){var O=D(N.template);
Q=O({dataItem:L,value:S,percentage:M.percentage,category:M.category,series:P});
}else{if(N.format){Q=d(N.format,Q);
}}if(!N.color&&N.align==="center"){var J=new i(P.color).percBrightness();
if(J>180){N.color=e;
}else{N.color=I;
}}K.evalSegmentOptions(N,S,M);
R=new E(Q,l({vAlign:N.position},N));
K.labels.push(R);
return R;
}},labelPadding:function(){var M=this.labels,L,J,O,N={left:0,right:0},K;
for(K=0;
K<M.length;
K++){L=M[K];
J=L.options.align;
if(J!=="center"){O=M[K].box.width();
if(J==="left"){N.left=Math.max(N.left,O);
}else{N.right=Math.max(N.right,O);
}}}return N;
},reflow:function(L){var K=this,Z=K.options,ae=K.points,M=ae.length,N=Z.neckRatio<=1,S,R,T,ab,aa,Y,J=L.clone().unpad(K.labelPadding()),ai=J.width(),ac=0,ad=N?0:(ai-ai/Z.neckRatio)/2,af=Z.segmentSpacing,O=Z.dynamicSlope,ah=J.height()-af*(M-1),V=N?Z.neckRatio*ai:ai;
if(!M){return;
}if(O){var Q=ae[0],U=Q,X,W;
b.each(ae,function(aj,ak){if(ak.percentage>U.percentage){U=ak;
}});
T=Q.percentage/U.percentage*ai;
ad=(ai-T)/2;
for(S=0;
S<M;
S++){aa=ae[S].percentage;
X=ae[S+1];
W=X?X.percentage:aa;
ab=ae[S].points=[];
R=Z.dynamicHeight?ah*aa:ah/M;
if(!aa){Y=W?0:ai/2;
}else{Y=(ai-T*(W/aa))/2;
}Y=w(Y,0,ai);
ab.push(new t.Point(J.x1+ad,J.y1+ac));
ab.push(new t.Point(J.x1+ai-ad,J.y1+ac));
ab.push(new t.Point(J.x1+ai-Y,J.y1+R+ac));
ab.push(new t.Point(J.x1+Y,J.y1+R+ac));
ad=Y;
ac+=R+af;
T=w(ai-2*Y,0,ai);
}}else{var ag=N?ai:ai-ad*2,P=(ag-V)/2;
for(S=0;
S<M;
S++){ab=ae[S].points=[];
aa=ae[S].percentage;
Y=Z.dynamicHeight?P*aa:P/M;
R=Z.dynamicHeight?ah*aa:ah/M;
ab.push(new t.Point(J.x1+ad,J.y1+ac));
ab.push(new t.Point(J.x1+ai-ad,J.y1+ac));
ab.push(new t.Point(J.x1+ai-ad-Y,J.y1+R+ac));
ab.push(new t.Point(J.x1+ad+Y,J.y1+R+ac));
ad+=Y;
ac+=R+af;
}}for(S=0;
S<M;
S++){ae[S].reflow(L);
}}});
l(q.fn,x);
var s=h.extend({init:function(M,J,L){var K=this;
h.fn.init.call(K,J);
K.value=M;
K.options.index=L.index;
},options:{color:I,border:{width:1}},reflow:function(J){var M=this,L=M.points,K=M.children[0];
M.box=new f(L[0].x,L[0].y,L[1].x,L[2].y);
if(K){K.reflow(new f(J.x1,L[0].y,J.x2,L[2].y));
}},createVisual:function(){var K=this;
var J=K.options;
var L;
h.fn.createVisual.call(this);
if(J.visual){L=J.visual({category:K.category,dataItem:K.dataItem,value:K.value,series:K.series,percentage:K.percentage,points:K.points,options:J,createVisual:function(){return K.createPath();
}});
}else{L=K.createPath();
}if(L){this.visual.append(L);
}},createPath:function(){var K=this.options;
var J=K.border;
var L=m.Path.fromPoints(this.points,{fill:{color:K.color,opacity:K.opacity},stroke:{color:J.color,opacity:J.opacity,width:J.width}}).close();
return L;
},createHighlight:function(J){return m.Path.fromPoints(this.points,J);
},highlightVisual:function(){return this.visual.children[0];
},highlightVisualArgs:function(){var J=m.Path.fromPoints(this.points).close();
return{options:this.options,path:J};
},highlightOverlay:function(P,N){var O=this.options,M=O.highlight||{};
if(M.visible===false){return;
}var J=M.border||{};
var K=o({},N,{fill:M.color,stroke:J.color,strokeOpacity:J.opacity,strokeWidth:J.width,fillOpacity:M.opacity});
var L=P.createPolyline(this.points,true,K);
return L;
},tooltipAnchor:function(K){var J=this.box;
return new A(J.center().x-K/2,J.y1);
},formatValue:function(J){var K=this;
return K.owner.formatPointValue(K,J);
}});
l(s.fn,k.PointEventsMixin);
z.current.register(r,[p]);
B.current.register([p],[H],[g,j,"visibleInLegend","visible"]);
l(k,{FunnelChart:q,FunnelSegment:s});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(a,b,c){(c||b)();
}));
