CREATE LOGIN [bill.hipps]
    WITH PASSWORD = N'hujWTacduLrzdgstgZqkrljqmsFT7_&#$!~<pf{mbhrobavk', SID = 0xB2752FDAA12AC940A262C2DA7362EBA8, DEFAULT_DATABASE = [ECN5_ACCOUNTS], DEFAULT_LANGUAGE = [us_english];

