CREATE TABLE [dbo].[Basechannel] (
    [BaseChannelID]         INT              IDENTITY (1, 1) NOT NULL,
    [BaseChannelName]       VARCHAR (100)    NULL,
    [ChannelURL]            VARCHAR (50)     NULL,
    [BounceDomain]          VARCHAR (100)    NULL,
    [AccessCommunicator]    BIT              CONSTRAINT [DF_BaseChannel_AccessCommunicator] DEFAULT ((0)) NULL,
    [AccessCreator]         BIT              CONSTRAINT [DF_BaseChannel_AccessCreator] DEFAULT ((0)) NULL,
    [AccessCollector]       BIT              CONSTRAINT [DF_BaseChannel_AccessCollector] DEFAULT ((0)) NULL,
    [AccessPublisher]       BIT              CONSTRAINT [DF_BaseChannel_AccessPublisher] DEFAULT ((0)) NULL,
    [AccessCharity]         BIT              CONSTRAINT [DF_BaseChannel_AccessCharity] DEFAULT ((0)) NULL,
    [DisplayAddress]        VARCHAR (255)    NULL,
    [Address]               VARCHAR (255)    NULL,
    [City]                  VARCHAR (255)    NULL,
    [State]                 VARCHAR (255)    NULL,
    [Country]               VARCHAR (50)     NULL,
    [Zip]                   VARCHAR (50)     NULL,
    [Salutation]            VARCHAR (50)     NULL,
    [ContactName]           VARCHAR (255)    NULL,
    [ContactTitle]          VARCHAR (255)    NULL,
    [Phone]                 VARCHAR (255)    NULL,
    [Fax]                   VARCHAR (50)     NULL,
    [Email]                 VARCHAR (255)    NULL,
    [WebAddress]            VARCHAR (255)    NULL,
    [InfoContentID]         INT              NULL,
    [MasterCustomerID]      INT              NULL,
    [ChannelPartnerType]    SMALLINT         CONSTRAINT [DF_BaseChannels_ChannelPartnerType] DEFAULT (4) NOT NULL,
    [RatesXml]              VARCHAR (2000)   CONSTRAINT [DF_BaseChannels_RatesXml] DEFAULT (' ') NOT NULL,
    [ChannelType]           VARCHAR (50)     NULL,
    [IsBranding]            BIT              CONSTRAINT [DF_Basechannel_IsBranding] DEFAULT ((0)) NULL,
    [EmailThreshold]        INT              CONSTRAINT [DF_BaseChannels_EmailThreshold] DEFAULT ((0)) NULL,
    [BounceThreshold]       INT              NULL,
    [FooterSource]          TEXT             NULL,
    [HeaderSource]          TEXT             NULL,
    [CreatedDate]           DATETIME         CONSTRAINT [DF_BaseChannel_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedUserID]         INT              NULL,
    [IsDeleted]             BIT              CONSTRAINT [DF_BaseChannel_IsDeleted] DEFAULT ((0)) NULL,
    [UpdatedDate]           DATETIME         NULL,
    [UpdatedUserID]         INT              NULL,
    [MSCustomerID]          INT              NULL,
    [BrandLogo]             VARCHAR (500)    NULL,
    [BrandSubDomain]        VARCHAR (50)     NULL,
    [BaseChannelGuid]       UNIQUEIDENTIFIER NULL,
    [SoftBounceThreshold]   INT              NULL,
    [TestBlastLimit]        INT              NULL,
    [AccessKey]             UNIQUEIDENTIFIER CONSTRAINT [DF_BaseChannel_AccessKey] DEFAULT (newid()) NULL,
    [PlatformClientGroupID] INT              NULL,
    CONSTRAINT [PK_BaseChannels] PRIMARY KEY CLUSTERED ([BaseChannelID] ASC) WITH (FILLFACTOR = 80)
);





